### ISSUE TITLE
Photon 3.0 reset root password

### ISSUE THREAD

**Issue by dinonovak** [vmware/photon#1000]
I am trying to reset root password using https://vmware.github.io/photon/assets/files/html/3.0/photon_troubleshoot/resetting-a-lost-root-password.html

Photon OS 3.0 (x86_64) - Kernel 4.19.112-1.ph3-esx

but after pressing F10 I am getting following error
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell

I am getting root [ /]# prompt but disk no root is mounted

Please advise.
D

**Comment by YustasSwamp** [comment]
While you are in the root shell, can you provide an output (screenshot?) of the following items, please:
1) `mount`
2) `fdisk -l` if present, `cat /proc/partitions` if not
3) `cat /proc/cmdline`
4) `blkid`
5) `dmesg | grep initr`

Thanks

**Comment by sshedi** [comment]
Also try with steps given in the following link: https://kb.vmware.com/s/article/2147144

**Comment by YustasSwamp** [comment]
@dinonovak any updates?

**Comment by dinonovak** [comment]
Hi all, found the password so there was no need for recovery process. Looks like I managed to find easy way out.
