### ISSUE TITLE
Support a Dockerfile for building RPMs

### ISSUE THREAD

**Issue by akutz** [vmware/photon#1002]
Hi all,

It would be nice to support a Dockerfile for building RPMs. Here's an example of one that works for building Go binaries:

```Dockerfile
FROM photon:latest
LABEL maintainer akutz@vmware.com

RUN tdnf -y remove toybox && \
    tdnf -y install \
      build-essential \
      file findutils \
      go gzip \
      rpm-build \
      sed \
      tar \
      xargs

# Set WORKDIR to the default BUILDROOT
WORKDIR /usr/src/photon/

ENTRYPOINT ["/bin/bash"]
```

**Comment by suezzelur** [comment]
Please use this sdk - https://vmware.github.io/photon/assets/files/html/3.0/photon_installation/build-package-kernel-using-script.html
