### ISSUE TITLE
photon_extras_3.0_aarch64 repo does not exist

### ISSUE THREAD

**Issue by gregorkistler** [vmware/photon#1004]
Hi,

seems like the extras repo for Photon OS 3.0 is currently missing under https://packages.vmware.com/photon/3.0/.

Tried to build a Dockerfile which currently ends in something like this:
```
Error: 404 when downloading https://packages.vmware.com/photon/3.0/photon_extras_3.0_aarch64/repodata/repomd.xml
. Please check repo url.
Error: TDNFGetRepoMD 1622
Error: Failed to synchronize cache for repo 'VMware Photon Extras 3.0 (aarch64)' from 'https://packages.vmware.com/photon/3.0/photon_extras_3.0_aarch64'
using empty dict to provide pw_dict
```

Executed command was `tdnf install sudo tzdata -y >> /dev/null` in a recently pulled photon:3.0 Docker image.

Thanks in advance.

**Comment by ppadmavilasom** [comment]
@gregorkistler indeed. thanks for letting us know. available now.
