### ISSUE TITLE
How to build minimal ISO?

### ISSUE THREAD

**Issue by cocowalla** [vmware/photon#1005]
The docs include instructions on [how to build the ISO](https://github.com/vmware/photon/blob/master/docs/photon_installation/build_the_iso.md).

Photon now publishes a minimal ISO package, which is only ~280MB - it would be great if we could have instructions on how to build this too?

**Comment by cocowalla** [comment]
Oops, just noticed there is a `minimal-iso` target in the makefile! Still, would be nice to update the docs

**Comment by mikeroySoft** [comment]
This is now a part of the doc "[Building the ISO](https://vmware.github.io/photon/docs/installation-guide/building-images/build-iso-from-source/build-the-iso/)"
