### ISSUE TITLE
Include hyperv-daemons package

### ISSUE THREAD

**Issue by cocowalla** [vmware/photon#1006]
When building with Packer for Hyper-V, the `hyperv-daemons` package is required if your VM uses DHCP, so that Packer can determine the IP that the VM is assigned.

Unfortunately, `hyperv-daemons` isn't available through `tdnf install` - is it possible to include the `hyperv-daemons` package?

**Comment by cocowalla** [comment]
OK, so it appears the package *is* in Photon, but it's called `hyper-v` instead of `hyperv-daemons`.

For anyone else who finds this useful, also note that the `hypervkvpd` service is named `hv_kvp_daemon` in Photon.

**Comment by ylluminate** [comment]
Great, thanks for this. This seems a little bit hidden and should be better documented. `rpm -ql hyper-v` also reveals two other daemons that may also need to be enabled:
```
systemctl enable hv_fcopy_daemon
systemctl enable hv_vss_daemon
```

To be comprehensive, here's what I did all together:
```
yum install hyper-v
systemctl enable hv_kvp_daemon
systemctl enable hv_fcopy_daemon
systemctl enable hv_vss_daemon
```
