### ISSUE TITLE
hyper-v.spec installs files with incorrect filenames

### ISSUE THREAD

**Issue by cocowalla** [vmware/photon#1007]
The `hv_kvp_daemon` service expects to fine files `hv_get_dhcp_info` and `hv_get_dns_info` in the path, but [hyper-v.spec](https://github.com/vmware/photon/blob/master/SPECS/hyper-v/hyper-v.spec) installs them as `/usr/bin/hv_get_dhcp_info.sh` and `/usr/bin/hv_get_dns_info.sh` (note the trailing .sh extension).

You can verify this by installing he `hyper-v` package, starting the `hv_kvp_daemon` service and then checking the status a few seconds later with `systemctl status hv_kvp_daemon` (this will print logs showing it can't find the files in question).

**Comment by YustasSwamp** [comment]
@cocowalla , thanks for the report.
@Vasavisirnapalli , please look at it.

**Comment by ssahani** [comment]
Happy to take a patch for this

**Comment by cocowalla** [comment]
> Happy to take a patch for this

Do you mean a PR, or are you specifically looking for a patch file?

**Comment by ssahani** [comment]
yep can you send one

**Comment by ssahani** [comment]
https://github.com/vmware/photon/commit/91ac448a78bd777803f072a51d01d3ea0b3bc0ef is merged. Thanks for your contribution.  Keep them coming.

**Comment by ssahani** [comment]
BTW please verify for KVP_SCRIPTS_PATH and it works .

**Comment by cocowalla** [comment]
@ssahani 

> BTW please verify for KVP_SCRIPTS_PATH and it works .

Just booted up a Photon box with the Hyper-V daemon installed, but there doesn't seem to be an env var `KVP_SCRIPTS_PATH` set - verified it's also not set for the `hv_kvp_daemon` or `hv_vss_daemon` processes. Also, there are no Hyper-V scripts (or symlinks) in `/usr/libexec`, which doesn't fit what you said.

So, I looked a bit further, and I guess you (or I 😄) are confusing a [later version](https://github.com/torvalds/linux/blob/master/tools/hv/hv_kvp_daemon.c) of hv_kvp_daemon.c with the one that Photon [actually uses](https://elixir.bootlin.com/linux/v4.9/source/tools/hv/hv_kvp_daemon.c).

From `hyper-v.spec`, the source URL is:
https://elixir.bootlin.com/linux/v4.9/source/tools/hv

And we can see there that [hv_kvp_daemon.c](https://elixir.bootlin.com/linux/v4.9/source/tools/hv/hv_kvp_daemon.c) does not use `KVP_SCRIPTS_PATH` - it doesn't specify a directory at all, just looking for `hv_get_dns_info` and friends on the `PATH`.

**Comment by akaher** [comment]
Thanks @cocowalla.

I was not aware that you are using Photon 2.0. So >= Photon 3.0, hyper-v.spec would require KVP_SCRIPTS_PATH changes. Is it possible for you to crosscheck same with Photon 3.0 or Photon 4.0.

**Comment by cocowalla** [comment]
@akaher I'm not using 2.0, I'm on Photon 3.0 Rev2 😕 

I think the source of all this confusion here is that the `hyper-v.spec` file doesn't appear to have been updated properly:

1. I was going by the URL in `hyper-v.spec` in `master`, but I see the problem (well, one of them!) - the _Version_ has been bumped, but the _URL_ still points to version 4.9 (https://elixir.bootlin.com/linux/v4.9/source/tools/hv).

2. The other thing is that `hyper-v.spec` at _all_ the `3.0` tags (including `3.0-Update2`), still has both Version and URL 4.9:

```
Summary:        Hyper-V tools
Name:           hyper-v
Version:        4.9
...
URL:            https://elixir.bootlin.com/linux/v4.9/source/tools/hv
```

So... how does the spec file decide where to get the files from?

**Comment by akaher** [comment]
Just follow the Version. And yes right only Photon 4.0 should be impacted.

**Comment by akaher** [comment]
@cocowalla, expecting hyper-v package of Photon 4.0 is having problem because of KVP_SCRIPTS_PATH. You could execute following steps to confirm on Photon 3.0:
wget https://packages.vmware.com/photon/4.0/photon_release_4.0_x86_64/x86_64/hyper-v-5.9-1.ph4.x86_64.rpm
rpm -Uvh hyper-v-5.9-1.ph4.x86_64.rpm

If you have Photon 4.0, you could directly execute: 'tdnf install -y hyper-v'

Thanks !!!
