### ISSUE TITLE
Can't connect to packer host from VM when boot to download kickstart json file 

### ISSUE THREAD

**Issue by jzhang2018** [vmware/photon#1009]
Packer 1.4.3
vsphere-iso 2.3
Photon 3 minimum iso

I am trying to working on using packer to build the VM from iso. The template file looks like this:

``{
  "variables": {
	  "ks_path": ""
	},
	
  "builders": [
    {
      "type": "vsphere-iso",

      "vcenter_server":      "vcsas11001.mycloud.com",
      "username":            "administrator@vsphere.local",
      "password":            "mypassword",
      "insecure_connection": "true",
      "vm_name": "photon3-min-1",
      "notes": "Build via Packer",
      "cluster": "VxRail-Virtual-SAN-Cluster-123456",
      "host": "esxas11001.mycloud.com",
      "datastore": "VxRail-Virtual-SAN-Datastore-123456",
      "folder": "MyCloudAPI VMs",
      
      "guest_os_type": "vmwarePhoton64Guest",

      "ssh_username": "root",
      "ssh_password": "root!23456,

      "CPUs":             2,
      "RAM":              4096,
      "RAM_reserve_all": false,
      "network": "Management Network-123456",

      "convert_to_template": false,

      "disk_controller_type":  "pvscsi",
      "disk_size":        25000,
      "disk_thin_provisioned": true,

      "network_card": "vmxnet3",

      "iso_paths": ["[VxRail-Virtual-SAN-Datastore-123456] iso/photon-minimal-3.0-58f9c74.iso"],
      "iso_checksum": "ae28558e57f5d8aefb8b479c9fac7473079156e1",
      "iso_checksum_type": "sha1",
      "floppy_files": [
        "{{user `ks_path`}}/pt3-min-ks.json"
      ],
      "http_directory": "/home/admin/iac/packer/",
      "boot_command": ["<esc><wait>", 
				"vmlinuz initrd=initrd.img root=/dev/ram0 loglevel=3 ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/pt3-min-ks.json photon.media=cdrom",
				"<enter>"]
    }
  ]
}

When build it failed at getting kickstart from the packer host. See attached screenshot for details. Also from the VM, I can't curl the packer host for get the file. The error is the host is not reachable. From another VM I get the same result. The mini http server within Packer seems can't be reached from the outside. Not sure why. Where do I look into this issue? I have already spent lots of time on this.

Thanks in advance.

J
![pt3-min](https://user-images.githubusercontent.com/34825364/80927283-cf2b6980-8d6a-11ea-875b-546d9ff82961.png)

**Comment by dcasota** [comment]
Accept a ssh_password value ending of ".

If your setup doesn't work, you may have a look to the 3.0Rev2U1 bits photon-minimal-3.0-a0f216d.iso. There were some kickstart related issues mentioned using previous releases.
- https://github.com/vmware/photon/issues/970
- https://github.com/vmware/photon/issues/953
- https://github.com/vmware/photon/issues/976

There is the alternative method building the VM from ova, see https://communities.vmware.com/message/2892795, though.

**Comment by jzhang2018** [comment]
Hi dcasota,

Thanks for the reply. I will read through your comments and links to see what I can do. One quick question, what does this comment mean?

Accept a ssh_password value ending of ".

I have hard coded password (will use encrypted one or vault when overcome this issue): 

"ssh_password": "Dees12345!",

Any problem here?

Thanks again,

J

**Comment by dcasota** [comment]
@jzhang2018 you may share your setup findings that would be great. The json file was mispelled. Learned much from communities.vmware.com. Welcome!

**Comment by jzhang2018** [comment]
Oh, I see. In my work copy I have it ending with ". I had to change it to something won't offend our policy :-). The one in the json is:

"ssh_password": "root!23456",

I always run packer validate before the build. On another note, our real use case is to use GA iso and not the minimum. I even can't reach the point as the minimum one. It halts at the boot with blank screen. Not even take <esc><wait>.

J

**Comment by jzhang2018** [comment]
The issue actually is due to the environment does not allow DHCP so there is no IP address assigned during the boot time therefore the http communication won't reach out to the packer host. This is the issue mentioned in https://github.com/vmware/photon/issues/976. No solution for that. I have to switch to ISO approach and now it is working as expected. Close this case.
