### ISSUE TITLE
Missing cmp command after upgrade?

### ISSUE THREAD

**Issue by NoLooseEnds** [vmware/photon#1012]
After upgrading the latest packages, suddenly `cmp` is missing. `cmp` should be a part of [coreutils](https://github.com/vmware/photon/blob/master/SPECS/coreutils/coreutils.spec) that I have installed, but it is no longer present.

Unfortunately that breaks part of my oh-my-zsh install:
```
/home/username/.oh-my-zsh/oh-my-zsh.sh:71: command not found: cmp
```

**Comment by dcasota** [comment]
is diffutils package removed or installed?

**Comment by NoLooseEnds** [comment]
I did not do anything to that system except for upgrading, so if cmp always was in the diffutils package, that is strange.

Anyhow, diffutils was not currently installed, and after installing `cmp` worked.

Thanks
