### ISSUE TITLE
tdnf should support installing from HTTP and HTTP GPG keys

### ISSUE THREAD

**Issue by voor** [vmware/photon#1017]
Currently `tdnf` will fail if it tries to install from a URL provided package, for example:

```
tdnf install -y http://example.com/example.rpm
```

I would expect this to work.

Additionally, GPG files in `.repo` files are required to be files, and cannot be provided as URLs.

**Comment by suezzelur** [comment]
@voor Please submit this enhancement in vmware/tdnf repo
