### ISSUE TITLE
Password complexity

### ISSUE THREAD

**Issue by mamenezesp** [vmware/photon#1019]
I need set up password complexity in my photon os server, how can i configure the password that need must have lower and upper case and numbers?

**Comment by dcasota** [comment]
Try this. In /etc/pam.d/system-auth and in /etc/pam.d/system-password right after the comment line add the following oneliner ```password requisite pam_cracklib.so try_first_pass retry=3 lcredit=1 ucredit=1 dcredit=1```. 

```try_first_pass retry=3``` means three attempts to change the password
``lcredit=1`` means password must include at least 1 lower case character
``ucredit=1`` means password must include at least 1 upper case character
``dcredit=1`` means password must include at least 1 digit

This [weblink ](https://pubs.vmware.com/vi35u2/wwhelp/wwhimpl/common/html/wwhelp.htm?context=server_config&file=sc_security_servcon.17.9.html) might be in most parts helpful, although it is related to the service console on esxi (on Photon there is no ```esxcfg-auth```).

You could add to the oneliner ```enforce=everyone```, however with that setting in effect, you enforce password complexity for root as well.

**Comment by YustasSwamp** [comment]
@dcasota thanks for the answer!
