### ISSUE TITLE
Why is toybox considered a better default than coreutils?

### ISSUE THREAD

**Issue by gerhard** [vmware/photon#1021]
I keep finding myself needing to remove `toybox` and installing `coreutils` for essentials commands to work. I would not expect <kbd>expr</kbd> or <kbd>dircolors</kbd> to be missing from a base OS, no matter how slim it is. I have found several issues listed in this repository because of this: https://github.com/vmware/photon/issues/990, https://github.com/vmware/photon/issues/959, https://github.com/vmware/photon/issues/890

Why is `toybox` considered a better default than `coreutils`?

**Comment by YustasSwamp** [comment]
We are working on fix to make toybox non-conflicting in 3.0.
After this change you won't be forced to remove toybox. Even though coreutils and toybox can be installed together.

**Comment by gerhard** [comment]
That is a welcome change!

The question remains: why is `coreutils` missing from the default Photon 3 distribution?

Another essential command that is missing is <kbd>sed</kbd>. For example, <kbd>erl</kbd>, the command that starts the Erlang VM runtime, requires <kbd>sed</kbd> to be present.

My goal is to understand how the decision is made what packages ship in the default Photon 3 Docker image.

---

### A relevant tangent (hence the separator)

<kbd>localectl</kbd> is missing from `photonos-docker-local.artifactory.eng.vmware.com/photon3:20200522` and <kbd>tdnf</kbd> does not find which package provides it. How do I get the following example to work in the context of this Docker image? https://vmware.github.io/photon/assets/files/html/3.0/photon_admin/changing-the-locale.html

Answer: add <kbd>*</kbd> in front of the missing command

<details>
<summary><kbd>tdnf provides *localectl</kbd></summary>
<pre>
systemd-239-10.ph3.x86_64 : Systemd-239
Repo	 : photon
systemd-239-24.ph3.x86_64 : systemd-239
Repo	 : photon-updates
systemd-239-23.ph3.x86_64 : systemd-239
Repo	 : photon-updates
systemd-239-22.ph3.x86_64 : systemd-239
Repo	 : photon-updates
systemd-239-21.ph3.x86_64 : systemd-239
Repo	 : photon-updates
systemd-239-20.ph3.x86_64 : Systemd-239
Repo	 : photon-updates
systemd-239-19.ph3.x86_64 : Systemd-239
Repo	 : photon-updates
systemd-239-18.ph3.x86_64 : Systemd-239
Repo	 : photon-updates
systemd-239-17.ph3.x86_64 : Systemd-239
Repo	 : photon-updates
systemd-239-15.ph3.x86_64 : Systemd-239
Repo	 : photon-updates
systemd-239-14.ph3.x86_64 : Systemd-239
Repo	 : photon-updates
systemd-239-13.ph3.x86_64 : Systemd-239
Repo	 : photon-updates
systemd-239-12.ph3.x86_64 : Systemd-239
Repo	 : photon-updates
systemd-239-11.ph3.x86_64 : Systemd-239
Repo	 : photon-updates
systemd-239-24.ph3.x86_64 : systemd-239
Repo	 : @System
</pre>
</details>

**Comment by YustasSwamp** [comment]
Requirement was the minimal size of the image. currently it is 13MB (33MB uncompressed).
If you replace toybox with normal tools, the size will be increased in 2-3 times.
Current (minimal) content of the docker image: bash, toys, tdnf (and dependencies).
We would happy to have just busybox and tdnf. But busybox license is not friendly.

Many consumers are OK with toybox, but many of them remove toybox in a first place to avoid conflicts. From the feedback we receiving: customers want to have toybox as is, and ability to replace some of toybox tools by regular ones.

**Comment by YustasSwamp** [comment]
Regarding original ask.
toybox is not just coreutils. Only ~30% of toys are coreutils alternatives.
Rest of the toys are alternatives of: bzip2, cpio, diffutils, expect, e2fsprogs, file, findutils, grep, gzip, iotop, iputils, kdb, kmod,  netcat, net-tools, parted, patch, pciutils, procps-ng, psmisc, sed, shadow-tools, tar, usb-utils, linux-utils, vim-extra, witch and others.
Toybox provides really valuable tools set with just 300Kb in size.

**Comment by gerhard** [comment]
That explains it, thanks.

I found this page useful to understand toybox: http://landley.net/toybox/about.html

This was a good reference regarding the status of commands: http://landley.net/toybox/status.html

Thanks 👍🏻
