### ISSUE TITLE
Temporary failure in name resolution

### ISSUE THREAD

**Issue by cpeuschel** [vmware/photon#1024]
Hi,

if i run "ping google.de" i got follow error message "ping: google.de: Temporary failure in name resolution"

My static network connection in "/etc/systemd/network/10-static-en.network":
[Match]
Name=e*

[Network]
Address=xx.x.xx.xx/24
Gateway=xx.x.xx.x
DNS=xx.x.x.xx xx.x.x.xx xx.x.x.xx

Can someone help me?

**Comment by ssahani** [comment]
After setting we need to restrart both networkd and resolved. 

See the status `systemd-resolve --status`

also please make sure  symlink /etc/resolv.conf
``` 
sudo ln -s /run/systemd/resolve/resolv.conf /etc/resolv.conf
```

**Comment by cpeuschel** [comment]
its working. Thank you.
