### ISSUE TITLE
Support Wireguard and wireguard-tools RPM in Photon

### ISSUE THREAD

**Issue by voor** [vmware/photon#1025]
I am hoping this is fairly straightforward since all that wireguard needs is built into more modern kernels

https://www.wireguard.com/

https://git.zx2c4.com/wireguard-tools/about/

https://centos.pkgs.org/7/epel-x86_64/wireguard-tools-1.0.20200513-1.el7.x86_64.rpm.html

**Comment by ssahani** [comment]
I am not too sure  kernel ```Linux photon 4.19.129-1.ph3 #1-photon SMP Tue Jun 30 02:21:48 UTC 2020 x86_64 GNU/Linux ```
has the kernel driver. 

```
▶ ip link add dev wg0 type wireguard
RTNETLINK answers: Operation not supported
```

cc @YustasSwamp ?

**Comment by ssahani** [comment]
In photon 4.0 systemd version would be >= 245 which automatically supports wireguard.  See https://www.freedesktop.org/software/systemd/man/systemd.netdev.html#%5BWireGuard%5D%20Section%20Options

**Comment by YustasSwamp** [comment]
Will target it to Photon OS 4.0 release with support provided by systemd.

**Comment by ssahani** [comment]
closing as it's merged now
