### ISSUE TITLE
Support for QinHeng Electronics HL-340 USB-Serial adapter (CH340)

### ISSUE THREAD

**Issue by mihalski** [vmware/photon#1027]
Hi,

I was hoping to use Photon OS 3 far a dedicated Zigbee adapter gateway but it does not seem to support the serial to USB device that my Zigbee dongle uses. When connected I get the following:
```
[68363.889980] usb 2-2.1: new full-speed USB device number 5 using uhci_hcd
[68365.115834] usb 2-2.1: New USB device found, idVendor=1a86, idProduct=7523, bcdDevice= 2.62
[68365.115837] usb 2-2.1: New USB device strings: Mfr=0, Product=2, SerialNumber=0
[68365.115839] usb 2-2.1: Product: USB2.0-Serial
```
And `lsusb` shows:
```
Bus 002 Device 005: ID 1a86:7523 QinHeng Electronics HL-340 USB-Serial adapter
```

According to the manufacturer I should be getting:
```
[152343.203201] usb 1-1.4: new full-speed USB device number 5 using dwc_otg
[152343.336384] usb 1-1.4: New USB device found, idVendor=1a86, idProduct=7523, bcdDevice= 2.62
[152343.336400] usb 1-1.4: New USB device strings: Mfr=0, Product=2, SerialNumber=0
[152343.336409] usb 1-1.4: Product: USB2.0-Serial
[152343.338315] ch341 1-1.4:1.0: ch341-uart converter detected
[152343.341440] usb 1-1.4: ch341-uart converter now attached to ttyUSB0
```

Could this be added to Photon OS 3? Or is there a configuration tweak I could perform to make it work?

Thank you in advance.

Regards,
Michal

**Comment by dcasota** [comment]
@mihalski  you might try make run https://raw.githubusercontent.com/torvalds/linux/master/drivers/usb/serial/ch341.c . ```modprobe usbserial``` on photon3 using linux-esx did work with in reference to [#750](https://github.com/vmware/photon/issues/750). hope this helps.

**Comment by mihalski** [comment]
@dcasota Thank you for your response.

I tried that and it loaded the usbserial module but still did not create a device. I removed the usb device and replugged it in while the usebsertal module was loaded and everything behaved as before.

For the record I also have a seperate Photon OS 3 VM with aa wave device and that works fine.

I noticed that the usb device is SUPPOSED to load using dwc_otg but instead loads using uhci_hcd if that is of any help.

Regards,
Michal

**Comment by YustasSwamp** [comment]
Added. Will be available in linux-4.19.138-2.ph3

**Comment by mihalski** [comment]
I've just tried with 4.19.154-3.ph3-esx and nothing appears to have changed. Still no ch341-uart and still no ttyUSB device.
Just tried on a Debian 10 VM and it works.

I don't know what the problem is.

Regards,
Michal

**Comment by nwpr** [comment]
Can confirm that.
And I think that's because the change in e839f43 is not there anymore as the file was removed.
The change has to be done again in the other spec configs.

**Comment by dcasota** [comment]
@mihalski In a generic environment I've upgraded from 4.19.79 to latest (4.19.154-1), and downgraded step by step. Actually with all other than kernel 4.19.138-2,  ```modinfo ch341``` is not found. On kernel 4.19.138-2 confirmed by @YustasSwamp  it throws out:
```
root@ph3 [ ~ ]# modinfo ch341
filename:       /lib/modules/4.19.138-2.ph3/kernel/drivers/usb/serial/ch341.ko.xz
license:        GPL v2
alias:          usb:v1A86p5523d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v1A86p7523d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v1A86p7522d*dc*dsc*dp*ic*isc*ip*in*
alias:          usb:v4348p5523d*dc*dsc*dp*ic*isc*ip*in*
depends:        usbserial,usbcore
retpoline:      Y
intree:         Y
name:           ch341
vermagic:       4.19.138-2.ph3 SMP mod_unload
```
[...]

Does the usb serial adapter (alias, vendor id + product id) with the kernel release  4.19.138-2 work in your env? Can you confirm? There weren't many commits to https://github.com/torvalds/linux/commits/master/drivers/usb/serial/ch341.c since July 2020 though.

**Comment by YustasSwamp** [comment]
ch341 module was added only to generic linux (`tdnf install linux`)
https://github.com/vmware/photon/blob/3.0/SPECS/linux/config#L4164
But not in linux-esx (`uname -r` reports -esx suffix):
https://github.com/vmware/photon/blob/3.0/SPECS/linux/config-esx#L2655

So, if you need ch341, please switch to generic kernel.

**Comment by mihalski** [comment]
> ch341 module was added only to generic linux (`tdnf install linux`)
> https://github.com/vmware/photon/blob/3.0/SPECS/linux/config#L4164
> But not in linux-esx (`uname -r` reports -esx suffix):
> https://github.com/vmware/photon/blob/3.0/SPECS/linux/config-esx#L2655
> 
> So, if you need ch341, please switch to generic kernel.

Thanks for the tip.

Does this mean I should be using the non ESX Photon kernel despite using VMware ESXi?

Regards,
Michal

**Comment by YustasSwamp** [comment]
`linux-esx` and `linux` use same sources and almost same patchset on top, with only noticeable change is drivers/modules set support (.config file differences)
`linux-esx` designed to run only on ESXi VMs. It supports devices which are only present there.
`linux` is generic kernel, which works on different hypervisors as well as bare metal.
