### ISSUE TITLE
CNI Version is far out of date

### ISSUE THREAD

**Issue by idrennanvmware** [vmware/photon#1030]
Current CNI version is 0.8.6 and the version in master here is 0.7.5

Can we please update this?

**Comment by ssahani** [comment]
If you using photon 3 the version is https://github.com/vmware/photon/blob/3.0/SPECS/cni/cni.spec#L3 ```Version:        0.8.3```

**Comment by idrennanvmware** [comment]
You are correct.  The latest version is 0.8.6 - is it possible to get this on a frequent update cycle?   It appears to have reasonably regular updates

**Comment by ssahani** [comment]
yeah I think that is possible.

**Comment by ssahani** [comment]
mered now https://github.com/vmware/photon/commit/9cca6a525b9f4869ca9459dcf60bf334d4d640e1

**Comment by idrennanvmware** [comment]
thanks so much!!

**Comment by ssahani** [comment]
Can you please close it.
