### ISSUE TITLE
EOL of Photon OS?

### ISSUE THREAD

**Issue by martinsvmw** [vmware/photon#1031]
Hi good afternoon,
Can you pleae tell me where can i find the EOL of Photon OS versions?

**Comment by dcasota** [comment]
Not sure, but Photon OS 1.0 definitely is eol.
https://www.vmware.com/content/dam/digitalmarketing/vmware/en/pdf/support/product-lifecycle-matrix.pdf

In respect to the following weblink content, parts of Photon OS 2.0 still get some years of support.
https://csrc.nist.gov/Projects/Cryptographic-Module-Validation-Program/Certificate/3514

**Comment by suezzelur** [comment]
@dcasota the Photon Platform mentioned in the first document is not equivalent to Photon OS. Photon OS 1.0 is currently being maintained as you can see from the advisories here : https://github.com/vmware/photon/wiki/Security-Advisories-1
The second document is only about the FIPS validation sunset date for 2.0 kernel module and not for the OS itself.

@martinsvmw what product are you referring to in relation to this query?

**Comment by martinsvmw** [comment]
@suezzelur to be more specific, VMware Skyline. I have asked the BU and here, because we do not have any reference on our EOL product matrix

**Comment by dcasota** [comment]
see [Photon Blog](https://blogs.vmware.com/vsphere/2022/01/photon-1-x-end-of-support-announcement.html)
