### ISSUE TITLE
DNS configuration issue with Docker containers

### ISSUE THREAD

**Issue by PlkMarudny** [vmware/photon#1033]
I launch PhotonOS 3.0 on vSphere (from *.ova image). After a static IP configuration:
```
[Match]
Name=eth0

[Network]
DHCP=no
Address=10.20.64.25/24
Gateway=10.20.64.1
DNS=10.20.32.11
DNS=10.20.32.12`
````

 /etc/resolv.conf contains the single entry:

```
root@photon-machine [ /etc/docker ]# cat /etc/resolv.conf
# This file is managed by man:systemd-resolved(8). Do not edit.
#
# This is a dynamic resolv.conf file for connecting local clients to the
# internal DNS stub resolver of systemd-resolved. This file lists all
# configured search domains.
#
# Run "resolvectl status" to see details about the uplink DNS servers
# currently in use.
#
# Third party programs must not access this file directly, but only through the
# symlink at /etc/resolv.conf. To manage man:resolv.conf(5) in a different way,
# replace this symlink by a static file or a different symlink.
#
# See man:systemd-resolved.service(8) for details about the supported modes of
# operation for /etc/resolv.conf.

nameserver 127.0.0.53
```

and this is fine, as DNS work.
But the content of the /etc/resolv.conf is copied by Docker to a container created, effectively leaving it with host DNS configuration that of course does not work. 
Is there anything I am missing here?

**Comment by ssahani** [comment]
```

[Match]
Name=eth0

[Network]
DHCP=no
Address=10.20.64.25/24
Gateway=10.20.64.1
DNS=10.20.32.11
DNS=10.20.32.12`  <=    invalid '
```


It's a stub listener for systemd-resolved.   Please see https://www.freedesktop.org/software/systemd/man/systemd-resolved.service.html#/etc/resolv.conf. 

I have not tested it. You not able to reach the stub listener ? 

you can symlink or copy to below according to the use case.
```

/run/systemd/resolve/stub-resolv.conf
/usr/lib/systemd/resolv.conf
/run/systemd/resolve/resolv.conf
```

**Comment by PlkMarudny** [comment]
Thanks for the answer. The backtick is a typo. My question is more general. How Docker works (and Docker is installed by definition in PhotonOS) with DNS is to copy /etc/resolv.conf into the container. If systemd-resolved is used, the stub 127.0.0.53 is used in a container and of course the container has no DNS access. Of course, I disabled systemd-resolved altogether in the host PhotonOS, linked /etc/resolv.conf to another file that contains IPs of my DNS servers and in such a configuration containers work.
I would suggest this is mentioned somewhere in documentation.

**Comment by ssahani** [comment]
I tested this now . it works .
```
sus@photon ~
❯ docker run -i -t ubuntu:20.10 /bin/bash
root@1945de0d9912:/# ping google.com

oot@1945de0d9912:/# ping google.com
PING google.com (172.217.166.110) 56(84) bytes of data.
64 bytes from 172.217.166.110 (172.217.166.110): icmp_seq=1 ttl=113 time=26.5 ms
64 bytes from 172.217.166.110 (172.217.166.110): icmp_seq=2 ttl=113 time=26.5 ms
64 bytes from 172.217.166.110 (172.217.166.110): icmp_seq=3 ttl=113 time=26.5 ms
^C
--- google.com ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2003ms
rtt min/avg/max/mdev = 26.484/26.510/26.546/0.026 ms
root@1945de0d9912:/# cat /etc/resolv.conf
# This file is managed by man:systemd-resolved(8). Do not edit.
#
# This is a dynamic resolv.conf file for connecting local clients directly to
# all known uplink DNS servers. This file lists all configured search domains.
#
# Third party programs must not access this file directly, but only through the
# symlink at /etc/resolv.conf. To manage man:resolv.conf(5) in a different way,
# replace this symlink by a static file or a different symlink.
#
# See man:systemd-resolved.service(8) for details about the supported modes of
# operation for /etc/resolv.conf.

nameserver 10.112.192.1
nameserver 10.112.16.131
nameserver 10.16.200.110
```

It copies from `/run/systemd/resolve/resolv.conf`

**Comment by PlkMarudny** [comment]
It does not work for me, however. Static IP configured for the host eth0, two DNS servers. Photon 3.0 from .OVA, no updates.
Using node images (-full, -slim), or alpine.

`
nameserver 127.0.0.53
`

is copied to a container.

**Comment by ssahani** [comment]
https://github.com/vmware/photon/issues/1033#issuecomment-664502044 does not solve your purpose ?

**Comment by PlkMarudny** [comment]
Not really, I mean the host can access the stub of course, but the container not. Anyway, turning off systemd-resolved worked.

**Comment by ssahani** [comment]
how does that work ?

**Comment by ssahani** [comment]
Closing because of lack of response.
