### ISSUE TITLE
Upgrade glibc in Photon3 to 2.29

### ISSUE THREAD

**Issue by edwardbadboy** [vmware/photon#1035]
Hi,

Recently we found a glibc 2.28 problem, it sometimes leads to process stuck when getting a rdlock ([bug](https://sourceware.org/bugzilla/show_bug.cgi?id=23861)).

This bug would affect applications using pthread rwlock, such as OpenvSwitch ([issue](https://github.com/openvswitch/ovs-issues/issues/175)).

Is it possible to upgrade glibc to 2.29? They fixed the problem in this release.

**Comment by YustasSwamp** [comment]
Thanks for report.
Fixed in glibc-2.28-8.ph3 by applying the patch.
https://github.com/vmware/photon/commit/d8cc4284ee00b4d4196ec8d38085f7eddcf8a39d
