### ISSUE TITLE
Missing kernel modules to support software iSCSI with the open-iscsi package

### ISSUE THREAD

**Issue by gizmotronic** [vmware/photon#1039]
**Photon OS version:** 3.0
**Kernel version:** 4.19.138-2.ph3

The open-iscsi package depends on the `iscsi_tcp` kernel module to support iSCSI targets over TCP. This module is missing in at least linux-esx-4.19.138-2.ph3, which prevents Photon guest VMs from using such targets.

How to reproduce:

1. Install the open-iscsi package
2. Configure the initiator in /etc/iscsi/initiatorname.scsi
3. Enable and start services
4. Attempt iSCSI target discovery: `iscsiadm -m discovery -t sendtargets -p 1.2.3.4`

The following messages are logged on the guest console:

```
libkmod: kmod_module_insert_module: could not find module by name='iscsi_tcp'
iscsiadm: Could not insert module tcp. Kmod error -2
iscsiadm: iSCSI driver tcp is not loaded. Load the module then retry the command.
iscsiadm: Could not perform SendTargets discovery: iSCSI driver not found. Please make sure it is loaded, and retry the operation
```

Investigating the error shows that `iscsi_tcp.ko` is not available in the filesystem because the kernel configuration does not include `CONFIG_ISCSI_TCP`.

Please consider adding this kernel module. We’ve had to fall back to using a different OS in order to get a project off the ground, but would prefer to use Photon on all of our cluster nodes.

**Comment by YustasSwamp** [comment]
Thanks for report.

For iSCSI support please use generic kernel. `tdnf install -y linux`
Any reasons for linux-esx use in your VMs? We might consider adding iscsi modules to linux-esx.

**Comment by gizmotronic** [comment]
Our VMs run in a VMware environment, and so we're using the VMware hypervisor optimized kernel.

Some additional background: our application deploys in a Kubernetes cluster. We normally use NFS for persistent storage, and this works well in the vast majority of cases. However, the application requires NFS v4.2, which our storage backend doesn't support. So, we've set up iSCSI LUNs to provide persistent storage, instead.

We can try the generic kernel. Do we lose any meaningful optimizations as compared to linux-esx?

**Comment by YustasSwamp** [comment]
For generic VMs only optimization you loose are: kernel boot time and kernel size.
All paravirt improvements are already in `linux`

**Comment by Aqualie** [comment]
I've run into the same issue as well however I've installed the open-iscsi package on my vmware tanzu guest cluster worker nodes and are receiving the same error. It'd be great if we can have support for this added in for tanzu guest workers by default as this should be 100% upstream kubernetes but it does not support ISCSI volumes as per the Kubernetes docs: https://kubernetes.io/docs/concepts/storage/volumes/#iscsi
