### ISSUE TITLE
Real-time flavor photon os issues

### ISSUE THREAD

**Issue by dcasota** [vmware/photon#1042]
I'm trying to use the real-time flavor of the new photon 3.0 Rev 2 Update 3 photon-rt-3.0-a383732.iso.

Here some findings:
1) Simple boot from a physical usb stick installed from photon-rt-3.0-a383732.iso
Right after the Photon install menu appears, it stops within isoInstaller.py.
![IMG_8857](https://user-images.githubusercontent.com/14890243/93503256-18deb000-f918-11ea-8149-fbe4de3a2c28.JPG)
This is clear as on a physical box photon_media  is not on /dev/sr0. 

2) To mount and boot the iso inside ram I used a tiny tool called ventoy. In short, the physical usb stick is created and the photon-rt-3.0-a383732.iso must be placed 1:1 on the partition suggested there. The Photon install menu appears. Now /dev/cdrom is linked to /dev/sr0 which is default.
The configuration steps License Agreement/ select disk/network configuration/hostname and password appear. The installation on a different disk works fine. I've selected the same physical usb stick to install the real-time system. The started installation breaks at partitioning when overwriting the ventoy bootloader bits.
![IMG_8859](https://user-images.githubusercontent.com/14890243/93505239-e4b8be80-f91a-11ea-9457-fd5bf8434af9.JPG)

The installer.log file there shows:
Command failed on ```mkfs -t ext4 /dev/sdb3```
Error code: 1
The file /dev/sdb3 does not exist and no size was specified.
Exception: Failed to format ext4 partition @ /dev/sdb3

In installer.py the recognition of the partition before line 1256 shouldn't return wrong partitions in case of photon_media = cdrom. Hope this helps.

Are there docs planned? Some information about the real-time flavor would be nice.

**Comment by srivatsabhat** [comment]
@dcasota : Thank you for the bug report! We will look into it.

The linux-rt kernel flavor is based on the PREEMPT_RT patchset, applied on top of the 4.19.x stable kernel series. You can find more information about the PREEMPT_RT patchset here:

https://wiki.linuxfoundation.org/realtime/start
https://wiki.linuxfoundation.org/realtime/preempt_rt_versions

**Comment by dcasota** [comment]
Wasn‘t aware of - just read the blog post there /lwnnetpreparing_for_the_realtime_future. Thanks!

**Comment by bordoloih** [comment]
@dcasota: If you try to overwrite the usb stick you will also end up overwriting the installer bits which are not in memory. This will cause the installation to fail. 
I just wanted to clarify whether your suggestion to make sure that the user does not get the option to install on the same partition?

**Comment by dcasota** [comment]
@bordoloih there wasn't an announcement about the new option real-time flavor, but the bits photon-rt-3.0-a383732.iso were downloadable already. I'm curious, so I started some studies. First, the created mount media - it booted but didn't get to the installer menu. With @srivatsabhat information I've learned the difference to a bootable live usb drive. Yes the mount media - the photon.iso booted - would have been overwritten by the installer bits then - at least that was my expectation. The same way inside ram, the installer menu appears but the overwrite of the underlying drive fails.
In that particular cases the drive mounted is on a physical usb stick with no write protect switch at all.

I started a review of the code of the mount media detection in isoinstaller.py. mount media is not the installation source in any case. A mount media can be cdrom and http. The isoinstaller.py cmdline related code holds some valuable mount alternative using uuid or label. That's the reason why I'm asking about additional docs. In case of no uuid/label related user specific cmdline imho the code actually is unfinished. The installation source can be a drive, url, nfs or cifs. If the installation source is a drive, particularly it should be checked if mount media is cdrom or not.

When it comes to install, in my two cases reviewed, the mount media is detected as cdrom, and the installation source should be successfully recognized as drive /dev/sdb, /dev/sr, .... Imho the uuid/label including pxe boot could(should?) span over all of these.

Hope this helps. I'm not a python pro though.

**Comment by dcasota** [comment]
Hi,

Booting from physical boot stick provisioned with - or booted inside ram - the photon-rt-4.0-1526e30ba.iso produces a similar issue to the 1st in the initial description with photon-rt-3.0-a383732.iso . The 2nd issue has gone. 

![image](https://user-images.githubusercontent.com/14890243/109387543-46397c00-7902-11eb-8666-a392034567f4.png)

Will post some python findings.

**Comment by dcasota** [comment]
Here some boot medium detection findings.

#A boot medium detection BEFORE root auto login
At a non photon time it was possible to detect the boot medium during ```%pre --interpreter=busybox``` by using the vsish command.
```
ks=`vsish -e get /system/bootCmdLine`
echo "$ks" | grep -i "ks=usb" 1>/dev/null 2>/dev/null
if [ $? -eq 0 ]; then
	installmedium=cdrom
fi
echo "$ks" | grep -i "ks=http:" 1>/dev/null 2>/dev/null
if [ $? -eq 0 ]; then
	installmedium=url
fi
if [ "$installmedium" == "" ]; then
		# TODO
		echo "The installmedium is not supported. Press a key to reboot."
		read
		reboot
fi
```
With that, it was super easy to set the installation source path in case of usb or http and to use that mapping in ```%post --interpreter=busybox```.

In photon neither isoinstaller.py its ```/proc/cmdline``` exposes the information about the boot medium nor ```ks_path = options.install_config_file```.

That said, the recipe below of isoinstaller.py has prerequisites for boot medium detection before root auto login, with today conditions of mbr/uefi/aarch64/x86_64.
```
        # Path to RPMS repository: local media or remote URL
        # If --repo-path= provided - use it,
        # if not provided - use kernel repo= parameter,
        # if not provided - use /RPMS path from photon_media,
        # exit otherwise
```
In installer.py line 359/360 the 'live' scenario case, the drive (cdrom) is ejected, so in a post root auto login scenario it must be mounted again.

#B boot medium detection AFTER root auto login
As described in #A, I didn't find a recipe of standard boot medium detection before root auto login.
Hence, any scenario B is a workaround, and that's not good.

Boot medium detection after root auto login for sure is possible. Eg. ```'journalctl | grep -A 6 "ROOT LOGIN"'``` offers information about the boot medium, but from a standardization perspective it is not good to expand it with something like this.

**Comment by gpiyush-dev** [comment]
Hi @dcasota 

Currently, if you want to boot photon from a media type other than cdrom you can do so by providing the UUID of the disk in the kernel command line. While booting in bios mode press tab to enter into the command line and edit `photon.media=cdrom` to `photon.media=UUID=<uuid of the disk>`  and then hit enter to boot.

In order to find out UUID you can use this command -
`sudo blkid`

While mounting the media in isoInstaller.py cmdline is appended with the UUID provided in photon.media - https://github.com/vmware/photon-os-installer/blob/02fb97af5d28ca4d00ca7deee139badf4bc48d76/photon_installer/isoInstaller.py#L145.

If nothing is provided then by default cdrom(/dev/sr0) is taken as mount media.

**Comment by dcasota** [comment]
Hi Piyush,
The reflection about dynamic UUID detection in a prephase of the kernel command entry default behavior is absolutely true. 
See #1113, the actual grub cascade equation "No UUID passed" = "cdrom" ergo /dev/cdrom or /dev/sr0 is somewhat old. 
No clue yet. Daniel

**Comment by gpiyush-dev** [comment]
In order to support other devices than cdrom for boot a minor change is required in the installer such that user can provide something like `photon.media=sdb1` from kernel command line and installer mounts /dev/sdb1 to /mnt/media.

Changes are in review for this. Will update, once it gets merged.

**Comment by ssahani** [comment]
Thanks @gpiyush-dev

**Comment by ssahani** [comment]
@dcasota can we close this?

**Comment by dcasota** [comment]
Choice photon.media=/dev/<disk> looks good to me too. Closed.

Still cannot test it myself to better contribute with an early qualified feedback. Sorry for the trouble in the past. Will have a look to it as soon as newer download bits will be made available. Must go through the docs and do some hands-on learning step by step about the recompiling workflow of photon os.

**Comment by dcasota** [comment]
In this scenario the workflow output doesn't end with the _first_ "Can not mount the cd" (see https://github.com/vmware/photon-os-installer/blob/02fb97af5d28ca4d00ca7deee139badf4bc48d76/photon_installer/isoInstaller.py, Line 152, and not with that one on line 167), hence , falsely, one if/elif clause before has already been applied.

**Comment by dcasota** [comment]
close ticket. Findings: Use workaround with uuid, write iso to usb works, for 3.0 rt iso on Ventoy do use the latest version.

**Comment by bjornbouetsmith** [comment]
Hi,
The /dev/xx fix is only a partial fix.

I have written the Photon CD to an USB - but since its VFAT - the /dev/xx mount does not work and when the installer tries to mount the usb - it fails with:
~~~
mount: /mnt/media: bad option; for several filesystems (e.g. nfs,cifs) you might need a /sbin/mount.<type> helper program
~~~

Just as would happen if I manually do a 
~~~
mount /dev/xx /mnt/media
~~~
I would need to add a -t vfat

i,.e.
~~~
mount -t vfat /dev/xx /mnt/media
~~~

I have tried "hacking" it by adding a -t into the kick start command line, but it seems like that does not get picked up:
~~~
linux /isolinux/vmlinuz root=/dev/ram0 loglevel=3 photon.media="/dev/disk/by-id/usb-SanDisk_Ultra_Fit_4C530000091102118494-0:0-part1 -t vfat"
~~~

I picks up the /dev/disk/by-id fine, but then it assumes that it can use whatever default filesystem for the device - which is wrong - I am not sure how it works with CDROM - because that is using the same filesystem - but perhaps there is some special handling for /dev/sr0 ?

**Comment by dcasota** [comment]
@bjornbouetsmith yes, good one. And, an implementation it's not trivial at all. The more I've read about constellations
firmware, ntp/hwclock, uefi/mbr boot, crypted/secure boot, ostree-awareness, and all kind of fs btrfs, ntfs, vfat, tarfs, ... + medias the more I understand why Photon OS Installer is highly focussed on use cases' product boards with prioritized features.

**Comment by imranrazakhan** [comment]
@bjornbouetsmith  @dcasota  I prepared usb with **myiso** label and in arguments provided below and it works for me

`photon.media=/dev/disk/by-label/myiso`
