### ISSUE TITLE
IPIP tunnels don't work when hardware offload is enabled on 4.19.132 and up

### ISSUE THREAD

**Issue by randomvariable** [vmware/photon#1047]
This is a tracking issue for Kubernetes for an existing problem with IPIP tunnels not working when hardware offload is enabled on PhotonOS kernels 4.19.132 and up.

**Comment by ssahani** [comment]
Closing as https://github.com/vmware/photon/commit/a4fbe1263ef61965f6880089c2534825da12c119 is merged.
