### ISSUE TITLE
Update OpenSSH from 7.2 to 8.1 and above

### ISSUE THREAD

**Issue by franekSoftSF** [vmware/photon#1049]
Hi,
How can I update the OpenSSH package offline.

OpenSSH version 7.2 to 8.1 and above

**Comment by suezzelur** [comment]
This will be part of our 4.0 release (early 2021).

**Comment by ssahani** [comment]
As 4.0 is released now closing. https://blogs.vmware.com/vsphere/2021/02/photon-os-4-0-release-announcement.html 
https://github.com/vmware/photon/blob/4.0/SPECS/openssh/openssh.spec#L3
