### ISSUE TITLE
Bootstrap Guide inside VMWare vSphere

### ISSUE THREAD

**Issue by schmitch** [vmware/photon#106]
Hello, It would be great to have a SIMPLE bootstrap guide for VMWare vSphere where I can bootstrap a small cluster. 
Also It would be great if this would work on VMWare vSphere Essentials, where I don't specify compute clusters on top of VMWare.

**Comment by kganugapati** [comment]
?Hi, when you say cluster what kind of cluster are you referring to?

________________________________

**Comment by schmitch** [comment]
Currently the first cluster I mean't was just to bootstrap a cluster over any number of vsphere nodes.
And the second I meant the vmware cluster functionality with vsphere.

Currently we have a vmware vsphere essentials version and use it with 3 nodes, however we manually deployed CoreOS where we have a small virtual iso attached to every node that contains the cloud-init.
However thats really ugly, and it would be great if we could do the same with photon, just without that.

**Comment by ppadmavilasom** [comment]
Resolution to #549 will resolve this
