### ISSUE TITLE
error: /boot/vmlinuz-4.19.154-3.ph3-esx has invalid signature.

### ISSUE THREAD

**Issue by omarc1492** [vmware/photon#1066]
Upgrading to `linux-esx 4.19.154-3.ph3-esx` causes VM to not boot.

Is there a way to tell status of certificate or signature of the new kernel before updating and hopefully preventing a boot failure after updating to new kernel?

Note: Installed `photon-hw13_uefi-3.0-a383732.ova` which includes `4.19.132-5.ph3-esx`

**Comment by smaliakkal** [comment]
@omarc1492 , Sorry for the inconvenience. we have changed the key and updated grub.
Could you please follow the below wiki ? 
https://github.com/vmware/photon/wiki/Frequently-Asked-Questions#q-after-updating-Kernel-rpm-VM-fails-to-boot-with-secure-boot

**Comment by omarc1492** [comment]
I reverted to a backup done prior to upgrading kernel.

1. Boot VM from backup
2. `tdnf upgrade`
3. Follow link posted by @smaliakkal
```
wget https://github.com/vmware/photon/raw/3.0/installer/EFI_x86_64/BOOT/bootx64.efi
wget https://github.com/vmware/photon/raw/3.0/installer/EFI_x86_64/BOOT/grubx64.efi
cp bootx64.efi /boot/efi/EFI/Boot
cp grubx64.efi /boot/efi/EFI/Boot
sha256sum /boot/efi/EFI/Boot/*

bc5769ca377ed6c7149d884496f3602e905d7a8d4935b134557584543818ee2d /boot/efi/EFI/Boot/bootx64.efi
c5c342488b5ff89f19120e44dde7ffdb169909db5c16603c7b8d52af749bb3d7 /boot/efi/EFI/Boot/grubx64.efi
```
4. I get the same error

**Comment by YustasSwamp** [comment]
You can just disable "secure boot" in boot options instead of revert from backup.

Did you update just bootloader (shim/grub)? What about kernel image? Is it old, reverted from backup, now?

Both bootloader and kernel must use same key. Either both of them should be new or old.

**Comment by omarc1492** [comment]
I tried that as well. I disabled "secure boot", booted into machine and installed `bootx64.efi` and `grubx64.efi` with kernel version at `4.19.154-3.ph3-esx`.

**Comment by Stefanpintdeinbusiness** [comment]
![IMG_20221201_101203](https://user-images.githubusercontent.com/119588704/205030125-83205bd9-724f-44a6-9b74-d186d011aa0b.jpg)
Hallo, diese Fehler zeigt er mir beim Start an und ich hab WLAN und komme nicht ins Internet. Dns adresse nicht gefunden zeigt er an. 
![IMG_20221201_101135](https://user-images.githubusercontent.com/119588704/205030146-76c7e765-a8a0-4fc5-ba68-3aca5ce13b6e.jpg)
