### ISSUE TITLE
Wireguard support

### ISSUE THREAD

**Issue by jkirklan** [vmware/photon#1071]
I have several customers that are bandwidth constrained but want to run encrypted networks.  They would like to run wireguard instead of ipsec.  I don't see wireguard support enabled in Photon("# CONFIG_EQUALIZER is not set" in the spec files).  Please enable support for wireguard.  Thanks

**Comment by ssahani** [comment]
Duplicate of https://github.com/vmware/photon/issues/1025

**Comment by ssahani** [comment]
cc @srivatsabhat

**Comment by ssahani** [comment]
https://github.com/vmware/photon/commit/7b64e84bc1d93d41712582dc143eba8cb9bad1a7 closing as it's merged now

**Comment by SourceQuality** [comment]
Hi, I a having trouble with this. I am on 4.0, but when I use` ip link add dev wg0 type wireguard` I get an error stating
`RTNETLINK answers: Operation not supported`

**Comment by ssahani** [comment]
It will be in final release of photo.  A little bit more to wait please https://github.com/vmware/photon/blob/4.0/SPECS/linux/config-esx#L1889
