### ISSUE TITLE
Error downloading metalink-0.1.3-2.ph3.x86_64.rpm

### ISSUE THREAD

**Issue by jorgelon** [vmware/photon#1072]
When I do a tdnf clean all and then tdnf -y upgrade I get

Error: 404 when downloading https://dl.bintray.com/vmware/photon_updates_3.0_x86_64/x86_64/libmetalink-0.1.3-2.ph3.x86_64.rpm
. Please check repo url.
Error(1622) : Invalid argument

VMware Photon OS 3.0
PHOTON_BUILD_NUMBER=49d932d

**Comment by tapakund** [comment]
can you try ```tdnf update photon-repos``` and see if this helps?

**Comment by jorgelon** [comment]
now the error is 
Error: 404 when downloading https://packages.vmware.com/photon/3.0/photon_updates_3.0_x86_64/x86_64/linux-esx-4.19.154-3.ph3.x86_64.rpm
. Please check repo url.
Error(1622) : Invalid argument

**Comment by tapakund** [comment]
Yes, thats because previously your cache was from dl.bintray.com and now after updating photon-repos, it's packages.vmware.com. So, doing ```tdnf clean all``` followed by ```tdnf makecache``` will rebuild your cache from the updated repo.

Let me know if you still see any issue.

Thanks!

**Comment by jorgelon** [comment]
now it is working. thank you
