### ISSUE TITLE
run tdnf command all response "Error: 401 when downloading https://dl.bintray.com/vmware/photon_release_3.0_x86_64/repodata/repomd.xml"

### ISSUE THREAD

**Issue by liyan-su** [vmware/photon#1074]
when I use tdnf command for "tdnf upgrade --security", "tdnf upgrade", "tdnf check-update", "tdnf repolist --refresh", "tdnf distro-sync","tdnf makecache" in a container all response msg as below:

`Refreshing metadata for: 'VMware Photon Linux 3.0(x86_64)'
Error: 401 when downloading https://dl.bintray.com/vmware/photon_release_3.0_x86_64/repodata/repomd.xml
. Please check repo url.
Error: Failed to synchronize cache for repo 'VMware Photon Linux 3.0(x86_64)' from 'https://dl.bintray.com/vmware/photon_release_3.0_x86_64'
Disabling Repo: 'VMware Photon Linux 3.0(x86_64)'
Refreshing metadata for: 'VMware Photon Linux 3.0(x86_64) Updates'
Error: 401 when downloading https://dl.bintray.com/vmware/photon_updates_3.0_x86_64/repodata/repomd.xml
. Please check repo url.
Error: Failed to synchronize cache for repo 'VMware Photon Linux 3.0(x86_64) Updates' from 'https://dl.bintray.com/vmware/photon_updates_3.0_x86_64'
Disabling Repo: 'VMware Photon Linux 3.0(x86_64) Updates'
Refreshing metadata for: 'VMware Photon Extras 3.0(x86_64)'
Error: 401 when downloading https://dl.bintray.com/vmware/photon_extras_3.0_x86_64/repodata/repomd.xml
. Please check repo url.
Error: Failed to synchronize cache for repo 'VMware Photon Extras 3.0(x86_64)' from 'https://dl.bintray.com/vmware/photon_extras_3.0_x86_64'
Disabling Repo: 'VMware Photon Extras 3.0(x86_64)'
Nothing to do.
`

**Comment by liyan-su** [comment]
tdnf: 2.0.0

**Comment by liyan-su** [comment]
I curl these link:
root [ ~ ]# curl https://dl.bintray.com/vmware/photon_release_3.0_x86_64/repodata/repomd.xml
root [ ~ ]# curl https://dl.bintray.com/vmware/photon_updates_3.0_x86_64
<html><body>Moved to <a href="http://dl.bintray.com:80/v1/content/vmware/photon_updates_3.0_x86_64/">http://dl.bintray.com:80/v1/content/vmware/photon_updates_3.0_x86_64/</a></body></html>

**Comment by ssahani** [comment]
```
$ cd /etc/yum.repos.d/
$ sed -i 's/dl.bintray.com\/vmware/packages.vmware.com\/photon\/$releasever/g' photon.repo photon-updates.repo photon-extras.repo photon-debuginfo.repo
--


```

**Comment by TnTBass** [comment]
https://kb.vmware.com/s/article/81304
^ More details on the fix @ssahani posted.

**Comment by ssahani** [comment]
thanks @TnTBass

**Comment by lucdekens** [comment]
While I appreciate the fix (and it works), the basic issue is still there in all the package (ISO, OVA...).
Those are all still pointing at the old repo.

Shouldn't the move of the repositories have involved a rebuild of all those packages?
