### ISSUE TITLE
Suggestion: Cloud-init inspired .iso similar to CoreOS, Ubuntu Snappy, etc.

### ISSUE THREAD

**Issue by cdrage** [vmware/photon#108]
Similar to other atomic/cloud platforms.  Be able to install without going through the .iso process. Read from cloud-init and initialize on first-boot.

**Comment by moander** [comment]
+10

**Comment by ppadmavilasom** [comment]
apologize for the late response but are you referring to an ova installation? can you provide more details?

**Comment by cdrage** [comment]
@ppadmavilasom no, similar to https://coreos.com/os/docs/latest/cloud-config.html or http://www.projectatomic.io/blog/2014/10/getting-started-with-cloud-init/

**Comment by rgeorgiev** [comment]
Any update? 
Will be really valuable to have a way to pass cloud-init as part of Ovf/ova install, e.g. same as CoreOs or Ubuntu

**Comment by ppadmavilasom** [comment]
Similar to the config steps here: http://www.projectatomic.io/blog/2014/10/getting-started-with-cloud-init/

Photon can be configured similarly if you start from the minimal ova, then follow this guide - https://github.com/vmware/photon/blob/master/docs/cloud-init.md

Refer to the "Making a seed iso" section in the link above.
