### ISSUE TITLE
Support Options Not Clear

### ISSUE THREAD

**Issue by mstarks01** [vmware/photon#1080]
- The README links to the Slack channel, but this appears to be invite only.
- The FAQ suggests visiting the VMWare microsite, but links to a marketing page for something called Pivotal Labs

I don't see any indications of a mailing list or IRC channel. How can we engage?

**Comment by ssahani** [comment]
Please raise a github issue  ad of now . We may consider for public mailing list and IRC .

**Comment by mstarks01** [comment]
Sorry, I'm not sure what you mean by this response.

**Comment by ssahani** [comment]
you can raise a issue here if you need support.

**Comment by mstarks01** [comment]
Understood, but please consider a platform more conducive to interactive conversations.

**Comment by ssahani** [comment]
yes sure thanks !

**Comment by ssahani** [comment]
We have a slack channel . Please join #photon https://code.vmware.com/web/code/join. thanks !
