### ISSUE TITLE
Documentation: Wrong links

### ISSUE THREAD

**Issue by FredFoo** [vmware/photon#1085]
https://vmware.github.io/photon/assets/files/html/3.0/photon_user/kickstart.html

Still points to bintray resources - results in 404's

**Comment by zdyxry** [comment]
In this [guide]（https://vmware.github.io/photon/assets/files/html/3.0/photon_admin/Photon-RPM-OSTree-7-Installing-a-host-against-a-custom-server-repository.html） , " Kickstart Support in Photon OS" link to "photon_admin/kickstart.md" , but it's not found, may be need link to "photon_user/kickstart.html"?

**Comment by eeinworks8** [comment]
Please fix your documentation links.  ALL LINKS ARE BROKEN. It makes it very difficult to use your product.  Everything is linking to a rool url of:
https://vmware.github.io/photon/assets/files/html/3.0/

Every link shows a 404 error.  

Test case: 
google "photon os directory structure"
Click the first link for vmware.github.io
Get 404 error

**Comment by mikeroySoft** [comment]
Links for the "old" docs site have been updated so URL's (like those from Google) pointing to them don't fail, while keeping the new docs site structure in tact.  

The 3.0 docs can't easily be updated in their current form because they were made with Gitbook, so the best we can do for now is prevent the 404's. 

The new [docs for 4.0](https://vmware.github.io/photon/docs/) should have all the correct links.

**Comment by dcasota** [comment]
Hi @mikeroySoft,

Could you provide a best practice recipe on how to contribute to photon-hugo? It is not the idea to generate more work for a pull request of an orphan weblink or a spelling issue that's absolutely clear but what's the right way? Before people do head banging, please, correct the recipe or rewrite it completely!

1) do a fork of 'vmware/photon'
2) in your repo in 'photon-hugo' branch in '/content/en/docs-v3/user-guide/' edit the file 'working-with-kickstart.md'
3) changes made: 'https://bintray.com/vmware/photon' replaced with 'https://packages.vmware.com/photon'
4) Do a commit: Click 'Commit directly to the photon-hugo branch.'
5) on your forked code page click 'Compare & pull request'
6) In the 'open a pull request' dialog describe the pull request.
    The pull should not conflict.
    Let 'allow edit by maintainers' selected and click on 'create pull request'
7) Wait and follow the process provided by maintainers.

Some follow-up questions for newbies like me: After the pull has been been accepted, should the fork been deleted and recreated in case of a new tiny pull? How to update the fork manually or automatically? It is clear that software developers never ever would delete a fork.

Many thanks for your assistance!
