### ISSUE TITLE
Bug: installer calls docker

### ISSUE THREAD

**Issue by FredFoo** [vmware/photon#1087]
Version: Photon OS 3.0 Revision 3 Binaries (minimal.iso)

If you run a kickstart install with the line

`"packagelist_file": "packages_minimal.json"`

the installation runs fine. Change it to 

`"packages": ["minimal", "linux", "initramfs", "linux-esx", "lvm2", "less", "sudo"]`

instead you see that the installer tries to call docker for some reason. Installation fails. I would expect that it just does the same thing as the packages line above sets the same information that is contained in packages_minimal.json

![Screenshot_dockerNoSuchFile](https://user-images.githubusercontent.com/6617497/103474305-a2d65a00-4ddd-11eb-8617-7fdfbe0e15a0.png)

**Comment by FredFoo** [comment]
Sorry, I was to general :) This happens if you add a package to the packages list that is not contained in the initial set of RPMS that are available during this stage of the installation. In my case I did have the nano editor package at the end of the list.

**Comment by suezzelur** [comment]
nano is not part of minimal iso (vim is), please install using the full iso if nano is needed.

**Comment by FredFoo** [comment]
So you say that the installer bugging out and trying to call docker is totally normal for just mentioning a package that might not be in the scope of the distribution? And its normal behaviour in case the user has a typo in a package name?

Okay.
