### ISSUE TITLE
Is there support for HW 17's watchdog functionality?

### ISSUE THREAD

**Issue by ecrode** [vmware/photon#1091]
Seems that esxi's new watchdog functionality is great for keeping my reverse proxy (via docker on photon) up and running. In few rare instances, CPU usage and harddrive read rate skyrockets while system becomes unresponcive (via SSH, etc). Only answer seems to be reboot of VM via esxi as I've yet to identify the root cause (be it with nginx, docker or photon itself). It happens seldom enough that it's not a big issue for me, but requires a manual intervention to resolve.

How can I get the [watchdog timer](https://blogs.vmware.com/vsphere/2020/05/vsphere-7-virtual-watchdog.html) supported on the photon os? Can't seem to find a good source of information. 

Thank you for your support.

**Comment by suezzelur** [comment]
The kernel config is currently not enabled, we will look into enabling it for generic kernel.

**Comment by akaher** [comment]
Looks like CONFIG_WDAT_WDT needs to enable to have wdat_wdt.ko driver.

@ecrode would like to know which Photon version and which Photon Linux flavour you are using. You can execute following command to get this info: 
rpm -qa | grep linux

**Comment by ecrode** [comment]
Thanks @akaher, here is the output:
`util-linux-libs-2.32-1.ph3.x86_64
linux-api-headers-4.19.87-1.ph3.noarch
util-linux-2.32-1.ph3.x86_64
libselinux-2.8-1.ph3.x86_64
linux-esx-4.19.87-1.ph3.x86_64`

**Comment by akaher** [comment]
Thanks @ecrode for info.

@suezzelur, @YustasSwamp, needs to enable for linux-esx as well along with linux-generic.

Changes for linux-generic:
+CONFIG_ACPI_WATCHDOG=y
+CONFIG_WDAT_WDT=m

Changes for linux-esx:
+CONFIG_ACPI_WATCHDOG=y
+CONFIG_WATCHDOG=y
+CONFIG_WATCHDOG_CORE=y
+CONFIG_WDAT_WDT=m

Please let me know if it's fine to do above changes for Photon 3.0 and Photon 4.0.

**Comment by YustasSwamp** [comment]
Sounds good. Please add it.

**Comment by akaher** [comment]
Changes are in review.

**Comment by akaher** [comment]
Changes have been merged to linux-4.19.174-2.ph3.x86_64.rpm, linux-esx-4.19.174-2.ph3.x86_64.rpm. I will update once these will be published.

**Comment by akaher** [comment]
Following rpms have been published to https://packages.vmware.com/:
linux-4.19.174-2.ph3.x86_64.rpm, linux-esx-4.19.174-2.ph3.x86_64.rpm

Please use >= linux-4.19.174-2.ph3.x86_64.rpm, linux-esx-4.19.174-2.ph3.x86_64.rpm.
