### ISSUE TITLE
strace and perl

### ISSUE THREAD

**Issue by FredFoo** [vmware/photon#1092]
Version: Photon OS 3.0 Revision 3 Binaries (minimal.iso)

I installed strace and the 1.4mb package comes with a 54mb perl dependency. I checked the SPEC file for the strace package and the last change says that it removed this dependency 3 months ago. But it did that for a version 4.21 and the one I got when I installed from the official repo was 4.25 ...

Can you check the changelog in the [SPEC](https://github.com/vmware/photon/blob/master/SPECS/strace/strace.spec) and see if it makes sense to you? The package version created from this is lower than the one that is already in the repo.

**Comment by ssahani** [comment]
ouch 
```*   Tue Sep 22 2020 Harinadh D <hdommaraju@vmware.com> 4.21-2
-   Seperate strace-graph to remove perl dependency
*   Wed Jul 01 2020 Gerrit Photon <photon-checkins@vmware.com> 4.21-1
-   Automatic Version Bump
*   Tue Nov 13 2018 Srinidhi Rao <srinidhir@vmware.com> 4.25-11 ``` 

will fix . Thanks.

**Comment by ssahani** [comment]
https://github.com/vmware/photon/commit/a5173701c2ba182b42af9fe8965c6851b165e148 version is upgraded for master. for 3.0 it's under review.

**Comment by ssahani** [comment]
closing as https://github.com/vmware/photon/commit/04028ce39a6e61827fee15b15835499fb46647e1 is merged
