### ISSUE TITLE
Pre-Photon 4.0 Download Links needs to be fixed

### ISSUE THREAD

**Issue by lamw** [vmware/photon#1093]
The [Photon OS download links page](https://github.com/vmware/photon/wiki/Downloading-Photon-OS) still contain the old `dl.bintray` URL for pre-Photon 4.0 downloads, which are no longer valid and prompts for username/password when clicked. `dl.bintray.com/vmware` needs to be replaced with `packages.vmware.com`

**Comment by mikeroySoft** [comment]
Links look updated now
