### ISSUE TITLE
[Q] PowerShell on Photon OS type rendering issue when running in ttyd

### ISSUE THREAD

**Issue by dmilov** [vmware/photon#1094]
I'm running PowerShell on a Photon OS 3.0 with https://github.com/tsl0922/ttyd 
The issue is initially filed under the ttyd repo https://github.com/tsl0922/ttyd/issues/562 but since it is reproducible only with Photon OS I'm raising the question here.

Can somebody suggest what could be the reason for ttyd UI to print all previously typed characters on typing the next character in the command line?

Here is how 'Get-ChildItem' command looks like
![image](https://user-images.githubusercontent.com/10736688/104338728-7a4a1080-54ff-11eb-90ce-dee8054a2f7a.png)

**Comment by dcasota** [comment]
The misbehavior might correlate to the issue https://github.com/PowerShell/PowerShell/issues/11599.

Quick check result:
v7.0.3: still a temp file CoreFxPipe_PSHost.* left after pwsh exit. 
v.7.1.0: ok
v.7.2.0.p2(latest): ok

```
root [ /tmp ]# ls -la
total 16
drwxrwxrwt 1 root root 4096 2021-01-12 18:05 .
drwxr-xr-x 1 root root 4096 2021-01-12 17:48 ..
-rwxr-xr-x 1 root root 6729 2021-01-12 18:01 Pwsh7.2.0.p2OnPhotonOS.sh
root [ /tmp ]# pwsh7.2.0-preview.2
PowerShell 7.2.0-preview.2
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS /tmp> ls -la
total 20
drwxrwxrwt 1 root root 4096 2021-01-12 18:05 .
drwxr-xr-x 1 root root 4096 2021-01-12 17:48 ..
drwxrwxrwx 3 root root 4096 2021-01-12 18:05 .dotnet
srwxr-xr-x 1 root root    0 2021-01-12 18:05 CoreFxPipe_PSHost.D6E90D85.730.None.pwsh7.2.0-preview.2
-rwxr-xr-x 1 root root 6729 2021-01-12 18:01 Pwsh7.2.0.p2OnPhotonOS.sh
prwx------ 1 root root    0 2021-01-12 18:05 clr-debug-pipe-730-401381-in
prwx------ 1 root root    0 2021-01-12 18:05 clr-debug-pipe-730-401381-out
srw------- 1 root root    0 2021-01-12 18:05 dotnet-diagnostic-730-401381-socket
PS /tmp> exit
root [ /tmp ]# ls -la
total 20
drwxrwxrwt 1 root root 4096 2021-01-12 18:05 .
drwxr-xr-x 1 root root 4096 2021-01-12 17:48 ..
drwxrwxrwx 3 root root 4096 2021-01-12 18:05 .dotnet
-rwxr-xr-x 1 root root 6729 2021-01-12 18:01 Pwsh7.2.0.p2OnPhotonOS.sh
root [ /tmp ]#
```

**Comment by dmilov** [comment]
Thanks for the suggestion. Checked with PS 7.1, it doesn't solve the problem. 

I believe t is something related to the PowerShell host on Photon OS. If I run `bash` initially with `ttyd` and then interactively run `pwsh` from bash it works fine. If I run `pwsh` directly though I get this weird misbehavior.

**Comment by dcasota** [comment]
Have you already tried ```tty``` with ```-T linux```? ```CMD ["ttyd", "-T", "linux", "-p", "8086", "/bin/pwsh"]```

**Comment by dmilov** [comment]
> 
> 
> Have you already tried `tty` with `-T linux`? `CMD ["ttyd", "-T", "linux", "-p", "8086", "/bin/pwsh"]`

I had not tried with the "linux" value. 

That solves the problem.

Thank You!
