### ISSUE TITLE
In what way is Photon OS "optimized for VMware? Link not working

### ISSUE THREAD

**Issue by mitchellmaler** [vmware/photon#1095]
Was doing some research on in what way Photon was optimized for VMware and the link "Deploying Cloud-Native Applications with Photon OS" in the documentation FAQ does not work to go over the 1.0 optimizations.

Is there another place where it lists all the different optimizations that are in Photon 1.0+ for VMware?

**Comment by dcasota** [comment]
@mitchellmaler this might be a question for VMware marketing. Relating to the documentation "Deploying Cloud-Native Applications with Photon OS" you're right - its weblink in https://blogs.vmware.com/cloudnative/2017/06/06/deploying-cloud-native-applications-photon-os-white-paper/ seems to be orphan actually, well that's true. 

In each VMware product built on Photon there are tons of mentions, related kb articles, etc. - a research for 'all the different optimizations' more specific by product leads to a panorama view of your own.

For the open source product the Photon OS documentation on https://vmware.github.io/photon/ is a good starting point.
Especially with in correlation to the linux kernel release and chip architecture supported there always were some exciting news.

**Comment by mitchellmaler** [comment]
@dcasota Thanks for the information!
