### ISSUE TITLE
Is there any way to deploy mysql community server on photonOS3

### ISSUE THREAD

**Issue by Tejad039** [vmware/photon#1097]
I am trying to deploy mysql community server on photon OS using Dockerfile
As there is no mysql package is available in tdnf repo i have tried adding mysql repo. But this installing mysql is failing with multiple dependencies.

**Comment by ssahani** [comment]
Can you precisely attach logs what is failing and what steps you followed. thanks !

**Comment by Tejad039** [comment]
Hi Susant,
 
Thanks for responding.
 
I am trying to port the mysql running on oracle baseOS to Photon 3.0. This Dockerfile will create mysql community server as container.
 
https://github.com/mysql/mysql-docker/blob/mysql-server/8.0/Dockerfile
 
I have added oracle and mysql rpm repo and when I execute mysql rpm I am getting below exception.
 
root [ /data ]# rpm -ivh mysql-community-server-8.0.22-1.el8.x86_64.rpmwarning: mysql-community-server-8.0.22-1.el8.x86_64.rpm: Header V3 DSA/SHA1 Signature, key ID 5072e1f5: NOKEYerror: Failed dependencies:        libcrypto.so.1.1()(64bit) is needed by mysql-community-server-8.0.22-1.el8.x86_64        libcrypto.so.1.1(OPENSSL_1_1_0)(64bit) is needed by mysql-community-server-8.0.22-1.el8.x86_64        libcrypto.so.1.1(OPENSSL_1_1_1)(64bit) is needed by mysql-community-server-8.0.22-1.el8.x86_64        libnuma.so.1()(64bit) is needed by mysql-community-server-8.0.22-1.el8.x86_64        libnuma.so.1(libnuma_1.1)(64bit) is needed by mysql-community-server-8.0.22-1.el8.x86_64        libnuma.so.1(libnuma_1.2)(64bit) is needed by mysql-community-server-8.0.22-1.el8.x86_64        libssl.so.1.1()(64bit) is needed by mysql-community-server-8.0.22-1.el8.x86_64        libssl.so.1.1(OPENSSL_1_1_0)(64bit) is needed by mysql-community-server-8.0.22-1.el8.x86_64        libssl.so.1.1(OPENSSL_1_1_1)(64bit) is needed by mysql-community-server-8.0.22-1.el8.x86_64        libstdc++.so.6()(64bit) is needed by mysql-community-server-8.0.22-1.el8.x86_64        libstdc++.so.6(CXXABI_1.3)(64bit) is needed by mysql-community-server-8.0.22-1.el8.x86_64        libstdc++.so.6(CXXABI_1.3.11)(64bit) is needed by mysql-community-server-8.0.22-1.el8.x86_64        libstdc++.so.6(CXXABI_1.3.3)(64bit) is needed by mysql-community-server-8.0.22-1.el8.x86_64        libstdc++.so.6(CXXABI_1.3.5)(64bit) is needed by mysql-community-server-8.0.22-1.el8.x86_64        libstdc++.so.6(CXXABI_1.3.8)(64bit) is needed by mysql-community-server-8.0.22-1.el8.x86_64        libstdc++.so.6(CXXABI_1.3.9)(64bit) is needed by mysql-community-server-8.0.22-1.el8.x86_64        libstdc++.so.6(GLIBCXX_3.4)(64bit) is needed by mysql-community-server-8.0.22-1.el8.x86_64        libstdc++.so.6(GLIBCXX_3.4.11)(64bit) is needed by mysql-community-server-8.0.22-1.el8.x86_64        libstdc++.so.6(GLIBCXX_3.4.14)(64bit) is needed by mysql-community-server-8.0.22-1.el8.x86_64        libstdc++.so.6(GLIBCXX_3.4.15)(64bit) is needed by mysql-community-server-8.0.22-1.el8.x86_64        libstdc++.so.6(GLIBCXX_3.4.17)(64bit) is needed by mysql-community-server-8.0.22-1.el8.x86_64        libstdc++.so.6(GLIBCXX_3.4.18)(64bit) is needed by mysql-community-server-8.0.22-1.el8.x86_64        libstdc++.so.6(GLIBCXX_3.4.19)(64bit) is needed by mysql-community-server-8.0.22-1.el8.x86_64        libstdc++.so.6(GLIBCXX_3.4.20)(64bit) is needed by mysql-community-server-8.0.22-1.el8.x86_64        libstdc++.so.6(GLIBCXX_3.4.21)(64bit) is needed by mysql-community-server-8.0.22-1.el8.x86_64        libstdc++.so.6(GLIBCXX_3.4.22)(64bit) is needed by mysql-community-server-8.0.22-1.el8.x86_64        libstdc++.so.6(GLIBCXX_3.4.9)(64bit) is needed by mysql-community-server-8.0.22-1.el8.x86_64        libtirpc.so.3()(64bit) is needed by mysql-community-server-8.0.22-1.el8.x86_64        libtirpc.so.3(TIRPC_0.3.0)(64bit) is needed by mysql-community-server-8.0.22-1.el8.x86_64        libtirpc.so.3(TIRPC_0.3.3)(64bit) is needed by mysql-community-server-8.0.22-1.el8.x86_64        mysql-community-client(x86-64) >= 8.0.11 is needed by mysql-community-server-8.0.22-1.el8.x86_64        mysql-community-common(x86-64) = 8.0.22-1.el8 is needed by mysql-community-server-8.0.22-1.el8.x86_64        net-tools is needed by mysql-community-server-8.0.22-1.el8.x86_64        procps is needed by mysql-community-server-8.0.22-1.el8.x86_64        shadow-utils is needed by mysql-community-server-8.0.22-1.el8.x86_64        systemd is needed by mysql-community-server-8.0.22-1.el8.x86_64root [ /data ]# yum install libcryptoError(1011) : No matching packages
 
Thank you
Tejaswi.D
 
----- Original message -----From: Susant Sahani <notifications@github.com>To: vmware/photon <photon@noreply.github.com>Cc: Tejad039 <tejad039@in.ibm.com>, Author <author@noreply.github.com>Subject: [EXTERNAL] Re: [vmware/photon] Is there any way to deploy mysql community server on photonOS3 (#1097)Date: Fri, Jan 15, 2021 11:40 PM 
 
Can you precisely attach logs what is failing and what steps you followed. thanks !

**Comment by ssahani** [comment]
Community edition is not supported. Please use https://github.com/vmware/photon/blob/master/SPECS/mysql/mysql.spec

**Comment by Tejad039** [comment]
Hi Susant,
 
This mysql package is just development header right? or is it complete mysql server.?
 
If this indeed a mysql server, Do you have any vmware document which points how to install and configure.?
 
                                                %package devel                                                                                 Summary: Development headers for mysql                                                                                 Requires: %{name} = %{version}-%{release}                        
 
Thank you
Tejaswi.D
 
----- Original message -----From: Susant Sahani <notifications@github.com>To: vmware/photon <photon@noreply.github.com>Cc: Tejad039 <tejad039@in.ibm.com>, Author <author@noreply.github.com>Subject: [EXTERNAL] Re: [vmware/photon] Is there any way to deploy mysql community server on photonOS3 (#1097)Date: Sat, Jan 16, 2021 2:07 PM 
 
Community edition is not supported. Please use https://github.com/vmware/photon/blob/master/SPECS/mysql/mysql.spec

**Comment by ssahani** [comment]
yeah it's just client. The el8 version won;t be compatible. You may try with the compressed tar version . But It won't be supported. 

Please test with mariadb
```
> sudo tdnf install mariadb-server

Installing:
mariadb-errmsg                                     x86_64                    10.3.11-2.ph3                     photon                       2.33M 2444723
mariadb-server                                     x86_64                    10.3.11-2.ph3                     photon                    120.42M 126271768

Total installed size: 122.75M 128716491
Is this ok [y/N]: y

Downloading:
mariadb-errmsg                          767461   100%
mariadb-server                        37915681   100%
Testing transaction
Running transaction
Installing/Updating: mariadb-errmsg-10.3.11-2.ph3.x86_64
Installing/Updating: mariadb-server-10.3.11-2.ph3.x86_64

Complete!

> sudo systemctl start mariadb


> sudo systemctl status mariadb
● mariadb.service - MariaDB 10.3.11 database server
   Loaded: loaded (/lib/systemd/system/mariadb.service; disabled; vendor preset: disabled)
   Active: active (running) since Sat 2021-01-16 10:12:06 UTC; 19s ago
     Docs: man:mysqld(8)
           https://mariadb.com/kb/en/library/systemd/
  Process: 22076 ExecStartPost=/bin/sh -c systemctl unset-environment _WSREP_START_POSITION (code=exited, status=0/SUCCESS)
  Process: 22041 ExecStartPre=/bin/sh -c [ ! -e /usr/bin/galera_recovery ] && VAR= ||   VAR=`/usr/bin/galera_recovery`; [ $? -eq 0 ]   && systemctl set-environment _W>
  Process: 22039 ExecStartPre=/bin/sh -c systemctl unset-environment _WSREP_START_POSITION (code=exited, status=0/SUCCESS)
 Main PID: 22044 (mysqld)
   Status: "Taking your SQL requests now..."
    Tasks: 30 (limit: 4915)
   Memory: 72.4M
   CGroup: /system.slice/mariadb.service
           └─22044 /usr/sbin/mysqld

Jan 16 10:12:06 photon mysqld[22044]: 2021-01-16 10:12:06 0 [Note] InnoDB: 10.3.11 started; log sequence number 1630815; transaction id 21
Jan 16 10:12:06 photon mysqld[22044]: 2021-01-16 10:12:06 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
Jan 16 10:12:06 photon mysqld[22044]: 2021-01-16 10:12:06 0 [Note] InnoDB: Buffer pool(s) load completed at 210116 10:12:06
Jan 16 10:12:06 photon mysqld[22044]: 2021-01-16 10:12:06 0 [Note] Plugin 'FEEDBACK' is disabled.
Jan 16 10:12:06 photon mysqld[22044]: 2021-01-16 10:12:06 0 [Note] Server socket created on IP: '::'.
Jan 16 10:12:06 photon mysqld[22044]: 2021-01-16 10:12:06 0 [Note] Reading of all Master_info entries succeded
Jan 16 10:12:06 photon mysqld[22044]: 2021-01-16 10:12:06 0 [Note] Added new Master_info '' to hash table
Jan 16 10:12:06 photon mysqld[22044]: 2021-01-16 10:12:06 0 [Note] /usr/sbin/mysqld: ready for connections.
Jan 16 10:12:06 photon mysqld[22044]: Version: '10.3.11-MariaDB'  socket: '/var/lib/mysql/mysqld.sock'  port: 3306  Source distribution
Jan 16 10:12:06 photon systemd[1]: Started MariaDB 10.3.11 database server.
lines 1-25/25 (END)

```
