### ISSUE TITLE
Photon 3 x86_64 update repo missing files ??

### ISSUE THREAD

**Issue by yokevin1** [vmware/photon#1101]
Is the Photon 3 Update repo incomplete ?  (https://packages.vmware.com/photon/3.0/photon_updates_3.0_x86_64/x86_64/)

Seem to be having issues doing a **yum update**   First file it hits is zstd-libs-1.4.5-1.ph3.x86_64.rpm is missing....

**Comment by dcasota** [comment]
Not sure about your first question, but zstd is in https://packages.vmware.com/photon/photon_publish_rpms/x86_64/. 
```
tdnf list zstd
zstd.x86_64                                                                                 1.4.5-1.ph3                                          photon-updates
```
```tdnf install zstd``` works fine.
Better use ```tdnf distro-sync``` for updates than ```yum update```.
Actually the latest zstd release 1.4.5-2.ph3 seems to be in the 4.0 repo https://packages.vmware.com/photon/4.0/photon_srpms_4.0_x86_64/ only.

**Comment by yokevin1** [comment]
Good points about using **tdnf**  - old habits :)

Yes the 3.0 repo seems to error out.  Though it may be a mirror problem but not it seems as I was checking via the sites directory list as well.

I see 4.0 RC is now out, perhaps that's the right path going forward.

**Comment by Satira7** [comment]
It looks like there are rpm packages starting with a-l in the update repository. Other packages are missing.

**Comment by suezzelur** [comment]
Are you still facing the issue with tdnf update? THe package is available in the repository, the fact that it is not listed is a CDN listing limitation, but `tdnf list zstd-libs` should show all the options

**Comment by yokevin1** [comment]
Only partially.... seems like a local mirror issue.   Can the CDN be fixed as this seems quite poor that it cannot.
