### ISSUE TITLE
How to install older version of NodeJs on photon os container?

### ISSUE THREAD

**Issue by Tejad039** [vmware/photon#1105]
Hi there,

The current version photon contains NodeJs v13.8 but I need NodeJs v8.14. How to install this with all dependencies?

root [ / ]# tdnf -y install nodejs

Installing:
libffi                                              x86_64                    3.2.1-6.ph3                        photon                         39.28k 40224
xz                                                  x86_64                    5.2.4-1.ph3                        photon                       166.45k 170445
python3-libs                                        x86_64                    3.7.5-8.ph3                        photon-updates              22.96M 24079511
ncurses                                             x86_64                    6.1-2.ph3                          photon-updates               357.89k 366475
python3                                             x86_64                    3.7.5-8.ph3                        photon-updates                2.94M 3084342
libstdc++                                           x86_64                    7.3.0-4.ph3                        photon                        1.62M 1694772
nodejs                                              x86_64                    13.8.0-4.ph3                       photon-updates              84.49M 88591204

Total installed size: 112.56M 118026973

Downloading:
libffi                                   25288   100%
xz                                       91109   100%
python3-libs                           8097425   100%
ncurses                                 210102   100%
python3                                1187527   100%
libstdc++                               534592   100%
nodejs                                32231893   100%
Testing transaction
Running transaction
Installing/Updating: ncurses-6.1-2.ph3.x86_64
Installing/Updating: libstdc++-7.3.0-4.ph3.x86_64
Installing/Updating: xz-5.2.4-1.ph3.x86_64
Installing/Updating: libffi-3.2.1-6.ph3.x86_64
Installing/Updating: python3-3.7.5-8.ph3.x86_64
Installing/Updating: python3-libs-3.7.5-8.ph3.x86_64
Installing/Updating: nodejs-13.8.0-4.ph3.x86_64

Complete!
root [ / ]# KIBANA_VERSION 6.5.4
root [ / ]# rm -rf /opt/kibana-${KIBANA_VERSION}-linux-x86_64/node
root [ / ]#  mkdir -p /opt/kibana-${KIBANA_VERSION}-linux-x86_64/node/bin
root [ / ]# ln -sf /usr/bin/node /opt/kibana-${KIBANA_VERSION}-linux-x86_64/node/bin/node
root [ / ]# /opt/kibana-${KIBANA_VERSION}-linux-x86_64/bin/kibana-plugin install "https://oss.sonatype.org/content/repositories/releases/com/floragunn/search-guard-kibana-plugin/$SG_VERSION/search-guard-kibana-plugin-$SG_VERSION.zip"
Kibana does not support the current Node.js version v13.8.0. Please use Node.js v8.14.0.

**Comment by YustasSwamp** [comment]
The lowest version we have is 8.17.0. Try `tdnf install nodejs-8.17.0`.

**Comment by dna2github** [comment]
maybe you can try `npm install -g n` and then `n 8.14.0`

**Comment by YustasSwamp** [comment]
@Tejad039 did it work for you?

**Comment by ssahani** [comment]
Closing as no response from user. Please reopen if required
