### ISSUE TITLE
tdnf check-update Error: 404 when downloading xml

### ISSUE THREAD

**Issue by koznov** [vmware/photon#1107]
Hello!

Trying to update package list for installing parted - no luck:
root@178vcd01 [ ~ ]# tdnf check-update
Refreshing metadata for: 'VMware Photon Extras 2.0(x86_64)'
Error: 404 when downloading https://dl.bintray.com/vmware/photon_extras_2.0_x86_64/repodata/repomd.xml
. Please check repo url.
Error: Failed to synchronize cache for repo 'VMware Photon Extras 2.0(x86_64)' from 'https://dl.bintray.com/vmware/photon_extras_2.0_x86_64'
Disabling Repo: 'VMware Photon Extras 2.0(x86_64)'
Refreshing metadata for: 'VMware Photon Linux 2.0(x86_64) Updates'
Error: 404 when downloading https://dl.bintray.com/vmware/photon_updates_2.0_x86_64/repodata/repomd.xml
. Please check repo url.
Error: Failed to synchronize cache for repo 'VMware Photon Linux 2.0(x86_64) Updates' from 'https://dl.bintray.com/vmware/photon_updates_2.0_x86_64'
Disabling Repo: 'VMware Photon Linux 2.0(x86_64) Updates'
Refreshing metadata for: 'VMware Photon Linux 2.0(x86_64)'
Error: 404 when downloading https://dl.bintray.com/vmware/photon_release_2.0_x86_64/repodata/repomd.xml
. Please check repo url.
Error: Failed to synchronize cache for repo 'VMware Photon Linux 2.0(x86_64)' from 'https://dl.bintray.com/vmware/photon_release_2.0_x86_64'
Disabling Repo: 'VMware Photon Linux 2.0(x86_64)'

root@178vcd01 [ ~ ]# cat /etc/photon-release
VMware Photon OS 2.0
PHOTON_BUILD_NUMBER=0922243

Maybe there is some network problems on your side, where reps are placed?

**Comment by keerthanakalyan** [comment]
Hello,

We have migrated from bintray to packages.vmware.com. Please follow this to change the repos.

https://kb.vmware.com/s/article/81304
