### ISSUE TITLE
Unable to mount remote NFS shares

### ISSUE THREAD

**Issue by sifotes** [vmware/photon#1111]
**Release:**
```
NAME="VMware Photon OS"
VERSION="4.0"
ID=photon
VERSION_ID=4.0
PRETTY_NAME="VMware Photon OS/Linux"
ANSI_COLOR="1;34"
HOME_URL="https://vmware.github.io/photon/"
BUG_REPORT_URL="https://github.com/vmware/photon/issues"
```
**nfs-utils installed:**
```
Name          : nfs-utils
Arch          : x86_64
Epoch         : 0
Version       : 2.5.1
Release       : 2.ph4
```
**rpcbind running:** 
```
root@photon2 [ ~ ]# systemctl status rpcbind
● rpcbind.service - RPC Bind Service
     Loaded: loaded (/usr/lib/systemd/system/rpcbind.service; disabled; vendor preset: disabled)
     Active: active (running) since Tue 2021-02-16 16:54:41 UTC; 1h 41min ago
TriggeredBy: ● rpcbind.socket
   Main PID: 453082 (rpcbind)
```
**To reproduce, mount nfs share from terminal:**
```
mount -t nfs my.nfs.server:/my/mount mountPoint/
```

When mounting from the terminal or with fstab, _mount_ hangs until killed.

Relevant logs: 

> Feb 16 18:23:56 hostname kernel: NFS4: Couldn't follow remote path
> Feb 16 18:23:56 hostname kernel: NFS: Unsupported transport protocol udp

**Expected behavior:** 
Mount NFS share successfully, available at mount point provided.

I have ensured the share is working from a non photon os within the same subnet.

**Comment by YustasSwamp** [comment]
Thanks for reporting.
Did you try NFS v3?

**Comment by sifotes** [comment]
Adding _-o nfsvers=3_ on the client mount command results in a immediate failure rather than a hung command.

> mount.nfs: access denied by server while mounting my.nfs.server/my/mount

**Comment by sifotes** [comment]
After some additional testing, this issue seems to be inconsistently affecting me across multiple distributions. I can't narrow it down but I'll retract my blame from Photon for the time being.
