### ISSUE TITLE
libfdt

### ISSUE THREAD

**Issue by spyroot** [vmware/photon#1112]
Folks,

I see in RT kernel source tree libfdt but I don't see that you are pushing it in normal places.  Is there any particular reason?
It would be nice if you could push it normal location lib64 include etc.

I essence that will provide an option to use -lfdt

Thank you

**Comment by srivatsabhat** [comment]
Hi @spyroot 

As I understand, libfdt is provided by the dtc package, and the library file is already packaged under the standard library path that we use for other libraries as well in Photon: https://github.com/vmware/photon/blob/8bc688b43bb674de457053fe66e967c4b46d8c98/SPECS/dtc/dtc.spec#L52

Did you try installing dtc-devel package and see if that works for you?

Also, I didn't get why this is specific to the RT kernel (linux-rt). Can you elaborate please?

cc @akaher

**Comment by spyroot** [comment]
The reason I asked t I saw some patches applied in the source tree, so I was not sure.  I guess it might not be specific to RT. I was working with RT and cross-checking, fdt. 

Essentially DPKD and Intel OPAE SDK (i.e., all N3000 IFPGDA drivers, etc.) need libfdt.  I manage to port it manually and compile it directly.  But I don't think I can pull a valid package.  In essence, it might create confusion for links unless it statically linked.    

I need to cross-check the spec you indicate.  
Thank you

**Comment by akaher** [comment]
@spyroot /usr/lib64 is softlink to /usr/lib.

**Comment by srivatsabhat** [comment]
Hi @spyroot, were you able to try out the dtc-devel package which provides the libfdt library in Photon? Is there anything else that needs to be addressed in this Github issue?

Thank you!

**Comment by ssahani** [comment]
@spyroot  Could you please share the feedback

**Comment by ssahani** [comment]
closing because of lack of response. Please reopen if needed
