### ISSUE TITLE
[DOCS] Photon OS Documentation - Pictures missing & broken bintray URLs in 'Print entire section' 

### ISSUE THREAD

**Issue by dcasota** [vmware/photon#1115]
**Expected behavior**
In webbrowser 'Print entire section' shows up with pictures & valid url in the photon os documentation.

**Actual behavior**
Pictures are not displayed at all.
A few broken urls.

**Information about the Issue**

**Steps to reproduce the behavior - missing pictures & wrong url redirections**
#edited comment updates 26.02.2021
In webbrowser https://vmware.github.io/photon/docs/ > Klick on 'Print entire section' (https://vmware.github.io/photon/docs/printview/)
Search text "The Photon OS Documentation provides information about how to install, configure, and use VMware Photon OS™."
Right after, PhotonOS Logo doesn't show up with a picture.

See "3.5.2 - Importing the OVA for Photon OS 4.0 > 1. Start the Import Process [...] Create new virtual machine" -> picture missing from https://github.com/vmware/photon/blob/master/docs/images/create-virtual-machine.png
See next steps too, pictures are missing.

See "7.10 - Performance Issues > Throughput Performance" > url redirects to https://vmware.github.io/photon/docs/printview/throughput_performance.md

**Steps to reproduce the behavior - broken bintray url**
In webbrowser https://vmware.github.io/photon/docs/ > Klick on 'Print entire section' (https://vmware.github.io/photon/docs/printview/)

Search "bintray" -> page not found. "Bintray" repo has changed for all releases a while ago to "Packages" repo https://packages.vmware.com/photon, in reference to https://kb.vmware.com/s/article/81304.

---
I apologize I'm not familiar with providing a better way to contribute eg. making pull requests (a slim tutorial would be nice).  Nevertheless, I hope this helps. Daniel

**Comment by mikeroySoft** [comment]
Thanks for sharing... I'll look into it =)

**Comment by mikeroySoft** [comment]
I think this is all sorted now, at least with the v4 docs... #1171 
I didn't go through docs-v3 diligently, but v4 (/docs/ should be a pretty good reference for what to change in docs-v3 to make it work as expected.

**Comment by dcasota** [comment]
Hi @mikeroySoft,

Could you double check these chapters, too?

3.5.3 - Installing the ISO Image for Photon OS 4.0
Pictures missing in Step 11

3.12 - Deploying a Containerized Application in Photon OS
Pictures missing in Step 2+3

4.3.3 - Creating a Startup Service
Typo in: Use systemd to create a startup service.

**Comment by mikeroySoft** [comment]
Thanks @dcasota, cleaned them up in #1174
