### ISSUE TITLE
Documentation - Broken link from Wiki to 4.0 Documentation

### ISSUE THREAD

**Issue by abidlen** [vmware/photon#1116]
From the wiki page - https://github.com/vmware/photon/wiki

Click the link “Photon OS 4.0 Documentation” in the “4.0 GA Documentation” Section

Takes you to https://vmware.github.io/photon/assets/files/html/4.0/index.html
Where you get an error “Not Found

**Comment by mikeroySoft** [comment]
link should be https://vmware.github.io/photon/docs/ but I don't think I have edit rights to the wiki

**Comment by ssahani** [comment]
Fixed with https://github.com/vmware/photon/wiki/Home/a9aedce7297dd4c7ae0978698624a29d630d1b3b
