### ISSUE TITLE
unknown ioctl 1976 on arm64 vms

### ISSUE THREAD

**Issue by vMarkus** [vmware/photon#1117]
Source:
https://packages.vmware.com/photon/4.0/GA/ova/photon-aarch64-hw13-uefi-4.0-1526e30ba0.ova and https://packages.vmware.com/photon/4.0/GA/iso/photon-4.0-1526e30ba-aarch64.iso

after installation
tdnf -y open-vm-tools

and start of "systemctl start vmtoolsd.service"
messages of "Unknown ioctl 1976" are flooding console output

Blacklisting modules

blacklist vsock_loopback
blacklist vmw_vsock_virtio_transport_common
blacklist vmw_vsock_vmci_transport

via /etc/modprobe.d/blacklist-lounge-vm.conf gets rid of the message flood. 
Please compare to https://github.com/vmware/open-vm-tools/issues/425

I can reproduce the issue for OVA and ISO VMs using latest ESXionARM Fling https://flings.vmware.com/esxi-arm-edition w/RPi4

**Comment by ssahani** [comment]
Maybe we should add this by default to  ```/etc/modprobe.d/blacklist-lounge-vm.conf```

```
blacklist vsock_loopback
blacklist vmw_vsock_virtio_transport_common
install vsock_loopback /usr/bin/true
install vmw_vsock_virtio_transport_common /usr/bin/true
```
/cc @oliverkurth

**Comment by mikeroySoft** [comment]
yah, +1... 
this issue is annoying (aarch64 here as well)...

**Comment by ssahani** [comment]
@sshedi ?

**Comment by sshedi** [comment]
Yes, this was reported long back during 4.0 beta stage. open-vm-tools need to answer this, this won't cause any disruption to functionalities but a flood of entries in dmesg. Did we disable any kernel configs in 4.0 related to this?

If not, we can simply blacklist these modules by default in Photon. @YustasSwamp

**Comment by dcasota** [comment]
+1 on 5.10.78-1.ph4 (aarch64 iso developer)

**Comment by sshedi** [comment]
This issue has been fixed in this commit:
https://github.com/vmware/photon/commit/f8d5716c5ecd2c46ef24d70d452769444bf5cf7c

Somebody please crosscheck it.
@ssahani Please close this issue.
