### ISSUE TITLE
[DOCS] Git commit links at bottom of the page go to incorrect URL

### ISSUE THREAD

**Issue by mikeroySoft** [vmware/photon#1118]
At the bottom of the /docs/ pages, there are links that represent the lastEdit and commit of the currently viewed page.

example: Last modified February 10, 2021: bugfix (bad9007)

The url represents the incorrect commit hash, as it's coming from the Hugo generator repo that builds the template.

As such, the template needs to be altered so that it represents the right repo and the right change hash.

**Comment by mikeroySoft** [comment]
I have the issue resolved in my fork now.
I solved it by bringing the Hugo project into vmware/photon in the photon-huge branch.
I then created a GitHub action in that branch to build the site and publish to the gh-pages branch (the branch selected for GitHub Pages in settings) 

The bottom of the docs now reflect the commits I make to the photon-huge branch.

**Comment by ssahani** [comment]
Thanks @mikeroySoft !

**Comment by ssahani** [comment]
Also https://vmware.github.io/photon/docs/command-line-reference/command-line-interfaces/photon-network-config-manager-cli/ . Display is borked

**Comment by mikeroySoft** [comment]
This should be fixed in https://github.com/vmware/photon/commit/3f54ed1175f77f199e8dc2138f2925e8e05df522
