### ISSUE TITLE
[DOCS] Checking Firewall Rules / Default Firewall Settings

### ISSUE THREAD

**Issue by robpomeroy** [vmware/photon#1125]
The docs say:

> You can supplement the `iptables` commands by using `lsof` to, for instance, see the processes listening on ports:

(See [Checking Firewall Rules](https://vmware.github.io/photon/docs/troubleshooting-guide/network-troubleshooting/checking-firewall-rules/) and [Default Firewall Settings](https://vmware.github.io/photon/docs/administration-guide/security-policy/default-firewall-settings/).)

But Photon seems not to include `lsof`, out of the box - even in the Developer install.

    root [ /etc/sysconfig ]# lsof -i -P -n
    bash: lsof: command not found

(I see it's available via `tdnf`.)

**Comment by ssahani** [comment]
Well not every once needs it. If you need then please install via tdnf thanks

**Comment by robpomeroy** [comment]
Indeed. I suppose I'm viewing the documentation from the perspective of a beginner. I worked it out. 🙂

**Comment by ssahani** [comment]
CLosing then.
