### ISSUE TITLE
Update Photon OS 4.0 RC to GA / systemd-udev 247.2-2 > 247.3-1

### ISSUE THREAD

**Issue by t3easy** [vmware/photon#1127]
After updating our 4.0 RC we have two versions of systemd-udev installed
```
tdnf list systemd-udev 
systemd-udev.x86_64                                      247.2-2.ph4                       @System
systemd-udev.x86_64                                      247.3-1.ph4                       @System
systemd-udev.x86_64                                      247.3-1.ph4                photon-release
```
Trying to remove the old version fails
```
tdnf distro-sync 

Removing:
systemd-udev                    x86_64          247.2-2.ph4           @System           8.45M 8863168

Total installed size:   8.45M 8863168
Is this ok [y/N]: y
Testing transaction
Running transaction
/var/tmp/rpm-tmp.WljdXr: line 1: fg: no job control
/var/tmp/rpm-tmp.p4BGTt: line 1: fg: no job control
Error(1525) : rpm transaction failed
```

Reinstall the new fails:
```
tdnf reinstall systemd-udev-247.3-1.ph4

Reinstalling:
systemd-udev                    x86_64          247.3-1.ph4           photon-release    8.50M 8908222

Total installed size:   8.50M 8908222
Is this ok [y/N]: y

Downloading:
systemd-udev                           1337144   100%
Testing transaction
Found 27 problems
file /usr/bin/bootctl from install of systemd-udev-247.3-1.ph4.x86_64 conflicts with file from package systemd-udev-247.2-2.ph4.x86_64
file /usr/bin/systemd-hwdb from install of systemd-udev-247.3-1.ph4.x86_64 conflicts with file from package systemd-udev-247.2-2.ph4.x86_64
file /usr/bin/udevadm from install of systemd-udev-247.3-1.ph4.x86_64 conflicts with file from package systemd-udev-247.2-2.ph4.x86_64
file /usr/lib/systemd/system-generators/systemd-bless-boot-generator from install of systemd-udev-247.3-1.ph4.x86_64 conflicts with file from package systemd-udev-247.2-2.ph4.x86_64
file /usr/lib/systemd/system-generators/systemd-hibernate-resume-generator from install of systemd-udev-247.3-1.ph4.x86_64 conflicts with file from package systemd-udev-247.2-2.ph4.x86_64
file /usr/lib/systemd/systemd-backlight from install of systemd-udev-247.3-1.ph4.x86_64 conflicts with file from package systemd-udev-247.2-2.ph4.x86_64
file /usr/lib/systemd/systemd-bless-boot from install of systemd-udev-247.3-1.ph4.x86_64 conflicts with file from package systemd-udev-247.2-2.ph4.x86_64
file /usr/lib/systemd/systemd-fsck from install of systemd-udev-247.3-1.ph4.x86_64 conflicts with file from package systemd-udev-247.2-2.ph4.x86_64
file /usr/lib/systemd/systemd-growfs from install of systemd-udev-247.3-1.ph4.x86_64 conflicts with file from package systemd-udev-247.2-2.ph4.x86_64
file /usr/lib/systemd/systemd-hibernate-resume from install of systemd-udev-247.3-1.ph4.x86_64 conflicts with file from package systemd-udev-247.2-2.ph4.x86_64
file /usr/lib/systemd/systemd-makefs from install of systemd-udev-247.3-1.ph4.x86_64 conflicts with file from package systemd-udev-247.2-2.ph4.x86_64
file /usr/lib/systemd/systemd-modules-load from install of systemd-udev-247.3-1.ph4.x86_64 conflicts with file from package systemd-udev-247.2-2.ph4.x86_64
file /usr/lib/systemd/systemd-pstore from install of systemd-udev-247.3-1.ph4.x86_64 conflicts with file from package systemd-udev-247.2-2.ph4.x86_64
file /usr/lib/systemd/systemd-quotacheck from install of systemd-udev-247.3-1.ph4.x86_64 conflicts with file from package systemd-udev-247.2-2.ph4.x86_64
file /usr/lib/systemd/systemd-random-seed from install of systemd-udev-247.3-1.ph4.x86_64 conflicts with file from package systemd-udev-247.2-2.ph4.x86_64
file /usr/lib/systemd/systemd-remount-fs from install of systemd-udev-247.3-1.ph4.x86_64 conflicts with file from package systemd-udev-247.2-2.ph4.x86_64
file /usr/lib/systemd/systemd-rfkill from install of systemd-udev-247.3-1.ph4.x86_64 conflicts with file from package systemd-udev-247.2-2.ph4.x86_64
file /usr/lib/systemd/systemd-sleep from install of systemd-udev-247.3-1.ph4.x86_64 conflicts with file from package systemd-udev-247.2-2.ph4.x86_64
file /usr/lib/systemd/systemd-timesyncd from install of systemd-udev-247.3-1.ph4.x86_64 conflicts with file from package systemd-udev-247.2-2.ph4.x86_64
file /usr/lib/systemd/systemd-vconsole-setup from install of systemd-udev-247.3-1.ph4.x86_64 conflicts with file from package systemd-udev-247.2-2.ph4.x86_64
file /usr/lib/systemd/systemd-volatile-root from install of systemd-udev-247.3-1.ph4.x86_64 conflicts with file from package systemd-udev-247.2-2.ph4.x86_64
file /usr/lib/udev/ata_id from install of systemd-udev-247.3-1.ph4.x86_64 conflicts with file from package systemd-udev-247.2-2.ph4.x86_64
file /usr/lib/udev/cdrom_id from install of systemd-udev-247.3-1.ph4.x86_64 conflicts with file from package systemd-udev-247.2-2.ph4.x86_64
file /usr/lib/udev/fido_id from install of systemd-udev-247.3-1.ph4.x86_64 conflicts with file from package systemd-udev-247.2-2.ph4.x86_64
file /usr/lib/udev/mtd_probe from install of systemd-udev-247.3-1.ph4.x86_64 conflicts with file from package systemd-udev-247.2-2.ph4.x86_64
file /usr/lib/udev/scsi_id from install of systemd-udev-247.3-1.ph4.x86_64 conflicts with file from package systemd-udev-247.2-2.ph4.x86_64
file /usr/lib/udev/v4l_id from install of systemd-udev-247.3-1.ph4.x86_64 conflicts with file from package systemd-udev-247.2-2.ph4.x86_64
Error(1525) : rpm transaction failed

```

**Comment by ssahani** [comment]
Could you paste the logs during the first upgradation which says something failed because of some transaction
```
%post udev
udevadm hwdb --update &>/dev/null || :

%preun udev
%systemd_preun systemd-udev{d,-settle,-trigger}.service systemd-udevd-{control,kernel}.socket systemd-timesyncd.service

%postun udev
%systemd_postun_with_restart systemd-udevd.service
```

I think for this manually downloading and install could solve it https://packages.vmware.com/photon/4.0/photon_release_4.0_x86_64/x86_64/systemd-udev-247.3-1.ph4.x86_64.rpm
rpm -Uvh
or --force

**Comment by t3easy** [comment]
I tried the force update but it fails, too.
```
rpm -Uvh --force systemd-udev-247.3-1.ph4.x86_64.rpm
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:systemd-udev-247.3-1.ph4         ################################# [ 33%]
/var/tmp/rpm-tmp.bGMpSH: line 1: fg: no job control
error: %preun(systemd-udev-247.3-1.ph4.x86_64) scriptlet failed, exit status 1
error: systemd-udev-247.3-1.ph4.x86_64: erase failed
/var/tmp/rpm-tmp.BzzrTJ: line 1: fg: no job control
error: %preun(systemd-udev-247.2-2.ph4.x86_64) scriptlet failed, exit status 1
error: systemd-udev-247.2-2.ph4.x86_64: erase failed
```

**Comment by ssahani** [comment]
I see please first erase with ```rpm --noscripts -e systemd-udev-247.2-2.ph4.x86_64```

**Comment by t3easy** [comment]
Thank you, that worked:
```
rpm --noscripts -e systemd-udev-247.2-2.ph4.x86_64
tdnf reinstall systemd-udev-247.3-1.ph4

Reinstalling:
systemd-udev                                                              x86_64                               247.3-1.ph4                                       photon-release                                  8.50M 8908222

Total installed size:   8.50M 8908222
Is this ok [y/N]: y

Downloading:
systemd-udev                           1337144   100%
Testing transaction
Running transaction
Installing/Updating: systemd-udev-247.3-1.ph4.x86_64

Complete!
```

**Comment by sadrian80** [comment]
I encounter a similar situation as @t3easy :
- Headless RPi 4
- PhotonOS 4.0 boot media via BalenaEtcher
- Edited sshd_conf (permitrootlogin yes)

`root@photon-rpi [ ~ ]# tdnf upgrade
Refreshing metadata for: 'VMware Photon Linux 4.0 (aarch64)'
Refreshing metadata for: 'VMware Photon Linux 4.0 (aarch64) Updates'
Refreshing metadata for: 'VMware Photon Extras 4.0 (aarch64)'
photon-extras                              123   100%
Installing:
libxml2                                             aarch64                   2.9.12-4.ph4                       photon-updates                1.53M 1603845
ncurses-devel                                       aarch64                   6.2-6.ph4                          photon-updates                6.23M 6533031
coreutils-selinux                                   aarch64                   9.1-1.ph4                          photon-updates                6.41M 6721713

Total installed size:  14.17M 14858589

Upgrading:
zlib                                                aarch64                   1.2.11-3.ph4                       photon-updates               108.09k 110686
xz-libs                                             aarch64                   5.2.5-2.ph4                        photon-updates               153.08k 156752
xz                                                  aarch64                   5.2.5-2.ph4                        photon-updates               162.71k 166620
vim                                                 aarch64                   8.2.5164-1.ph4                     photon-updates                3.42M 3583831
util-linux-libs                                     aarch64                   2.37.4-1.ph4                       photon-updates               792.81k 811842
util-linux                                          aarch64                   2.37.4-1.ph4                       photon-updates                6.82M 7156127
procps-ng                                           aarch64                   3.3.17-1.ph4                       photon-updates                1.39M 1452308
pkg-config                                          aarch64                   0.29.2-4.ph4                       photon-updates               630.25k 645380
photon-repos                                        noarch                    4.0-3.ph4                          photon-updates                   4.10k 4199
photon-release                                      noarch                    4.0-2.ph4                          photon-updates                   3.31k 3388
pcre-libs                                           aarch64                   8.44-3.ph4                         photon-updates               408.67k 418482
pcre                                                aarch64                   8.44-3.ph4                         photon-updates               969.18k 992441
nss-libs                                            aarch64                   3.72-1.ph4                         photon-updates                2.23M 2337958
nspr                                                aarch64                   4.32-1.ph4                         photon-updates               337.20k 345297
nettle                                              aarch64                   3.7.3-1.ph4                        photon-updates               716.37k 733561
motd                                                noarch                    0.1.3-7.ph4                        photon-updates                   3.18k 3261
lz4                                                 aarch64                   1.9.2-2.ph4                        photon-updates               416.85k 426854
linux-firmware                                      noarch                    20210817-1.ph4                     photon-updates              25.42M 26652508
linux                                               aarch64                   5.10.118-5.ph4                     photon-updates              46.88M 49156716
libselinux                                          aarch64                   3.3-1.ph4                          photon-updates               178.24k 182514
libpwquality                                        aarch64                   1.4.2-2.ph4                        photon-updates               350.45k 358860
libgcrypt                                           aarch64                   1.9.4-1.ph4                        photon-updates               943.89k 966539
libcap                                              aarch64                   2.43-2.ph4                         photon-updates               110.58k 113236
krb5                                                aarch64                   1.17-7.ph4                         photon-updates                3.19M 3344634
iptables                                            aarch64                   1.8.7-5.ph4                        photon-updates                1.56M 1631040
iproute2                                            aarch64                   5.10.0-2.ph4                       photon-updates                2.24M 2351323
gzip                                                aarch64                   1.12-2.ph4                         photon-updates               141.83k 145237
grub2-efi-image                                     aarch64                   2.06-3.ph4                         photon-updates                1.11M 1159168
gptfdisk                                            aarch64                   1.0.7-2.ph4                        photon-updates               788.26k 807180
gnutls                                              aarch64                   3.7.1-2.ph4                        photon-updates                3.82M 4006412
glibc-iconv                                         aarch64                   2.32-11.ph4                        photon-updates                6.82M 7155289
glibc                                               aarch64                   2.32-11.ph4                        photon-updates                7.09M 7432557
glib                                                aarch64                   2.68.0-1.ph4                       photon-updates                3.61M 3789179
expat-libs                                          aarch64                   2.2.9-9.ph4                        photon-updates               161.16k 165026
expat                                               aarch64                   2.2.9-9.ph4                        photon-updates                 31.46k 32216
elfutils-libelf                                     aarch64                   0.181-4.ph4                        photon-updates               101.03k 103455
elfutils                                            aarch64                   0.181-4.ph4                        photon-updates                3.44M 3606965
dracut                                              aarch64                   050-8.ph4                          photon-updates               834.30k 854323
cracklib                                            aarch64                   2.9.7-2.ph4                        photon-updates                 44.52k 45585
cpio                                                aarch64                   2.13-7.ph4                         photon-updates               439.39k 449940
ncurses-terminfo                                    aarch64                   6.2-6.ph4                          photon-updates                2.01M 2105268
rpm                                                 aarch64                   4.16.1.3-9.ph4                     photon-updates               331.61k 339570
ncurses                                             aarch64                   6.2-6.ph4                          photon-updates               322.97k 330722
lua                                                 aarch64                   5.4.4-2.ph4                        photon-updates               757.09k 775261
openssh                                             aarch64                   8.8p1-3.ph4                        photon-updates                      0.00b 0
python3                                             aarch64                   3.10.0-3.ph4                       photon-updates                3.29M 3447992
systemd-rpm-macros                                  noarch                    247.11-3.ph4                       photon-updates                   5.45k 5581
systemd-libs                                        aarch64                   247.11-3.ph4                       photon-updates                1.58M 1655116
systemd-pam                                         aarch64                   247.11-3.ph4                       photon-updates               453.64k 464525
systemd-udev                                        aarch64                   247.11-3.ph4                       photon-updates                8.12M 8511205
tdnf-cli-libs                                       aarch64                   3.3.1-1.ph4                        photon-updates                 92.06k 94267
rpm-libs                                            aarch64                   4.16.1.3-9.ph4                     photon-updates               816.95k 836556
libsolv                                             aarch64                   0.7.19-4.ph4                       photon-updates                1.08M 1135211
ncurses-libs                                        aarch64                   6.2-6.ph4                          photon-updates               601.09k 615520
curl                                                aarch64                   7.83.1-2.ph4                       photon-updates               257.64k 263824
curl-libs                                           aarch64                   7.83.1-2.ph4                       photon-updates               592.52k 606736
libarchive                                          aarch64                   3.4.3-5.ph4                        photon-updates               849.79k 870180
libssh2                                             aarch64                   1.9.0-4.ph4                        photon-updates               246.02k 251920
openssh-clients                                     aarch64                   8.8p1-3.ph4                        photon-updates                4.68M 4909897
openssh-server                                      aarch64                   8.8p1-3.ph4                        photon-updates                1.09M 1139100
python3-libs                                        aarch64                   3.10.0-3.ph4                       photon-updates              24.73M 25928814
systemd                                             aarch64                   247.11-3.ph4                       photon-updates              37.06M 38863257
tdnf                                                aarch64                   3.3.1-1.ph4                        photon-updates               342.31k 350524
wpa_supplicant                                      aarch64                   2.10-1.ph4                         photon-updates                1.14M 1198947
openssl                                             aarch64                   3.0.3-3.ph4                        photon-updates                5.80M 6077072
ca-certificates-pki                                 aarch64                   20201001-2.ph4                     photon-updates               766.71k 785110
ca-certificates                                     aarch64                   20201001-2.ph4                     photon-updates               761.37k 779645
bzip2-libs                                          aarch64                   1.0.8-4.ph4                        photon-updates                 70.26k 71950
bzip2                                               aarch64                   1.0.8-4.ph4                        photon-updates               120.79k 123688
Linux-PAM                                           aarch64                   1.4.0-5.ph4                        photon-updates              983.71k 1007319

Total installed size: 226.41M 237403666

Removing:
coreutils                                           aarch64                   8.32-3.ph4                         @System                       5.89M 6177792

Total installed size:   5.89M 6177792

Obsoleting:
coreutils                                           aarch64                   8.32-3.ph4                         @System                       5.89M 6177792

Total installed size:   5.89M 6177792
Is this ok [y/N]: y

Downloading:
libxml2                                 649057   100%
ncurses-devel                          1234089   100%
coreutils-selinux                      1348060   100%
zlib                                     63079   100%
xz-libs                                  88675   100%
xz                                       88371   100%
vim                                    1575994   100%
util-linux-libs                         288564   100%
util-linux                             1705196   100%
procps-ng                               425789   100%
pkg-config                              243051   100%
photon-repos                             11308   100%
photon-release                           10575   100%
pcre-libs                               167230   100%
pcre                                    341778   100%
nss-libs                                953961   100%
nspr                                    148596   100%
nettle                                  378690   100%
motd                                     11898   100%
lz4                                     154979   100%
linux-firmware                         5212950   100%
linux                                 28423964   100%
libselinux                               80897   100%
libpwquality                             99279   100%
libgcrypt                               455445   100%
libcap                                   50258   100%
krb5                                   1230204   100%
iptables                                438461   100%
iproute2                                942854   100%
gzip                                     78323   100%
grub2-efi-image                         310769   100%
gptfdisk                                191483   100%
gnutls                                 1395480   100%
glibc-iconv                            1663867   100%
glibc                                  2458078   100%
glib                                   1278468   100%
expat-libs                               70458   100%
expat                                    20927   100%
elfutils-libelf                          77723   100%
elfutils                                805130   100%
dracut                                  261875   100%
cracklib                                 25727   100%
cpio                                    119673   100%
ncurses-terminfo                        592764   100%
rpm                                      78729   100%
ncurses                                 189124   100%
lua                                     199785   100%
openssh                                  11369   100%
python3                                1343992   100%
systemd-rpm-macros                       17448   100%
systemd-libs                            563060   100%
systemd-pam                             215561   100%
systemd-udev                           1297356   100%
tdnf-cli-libs                            40388   100%
rpm-libs                                327426   100%
libsolv                                 304013   100%
ncurses-libs                            254499   100%
curl                                    150004   100%
curl-libs                               285819   100%
libarchive                              376641   100%
libssh2                                 113976   100%
openssh-clients                         886191   100%
openssh-server                          473550   100%
python3-libs                           7682341   100%
systemd                                7505396   100%
tdnf                                    111680   100%
wpa_supplicant                          484801   100%
openssl                                2195214   100%
ca-certificates-pki                     301741   100%
ca-certificates                         323398   100%
bzip2-libs                               40928   100%
bzip2                                    70689   100%
Linux-PAM                               371427   100%
Testing transaction
Running transaction
Installing/Updating: glibc-2.32-11.ph4.aarch64
Installing/Updating: zlib-1.2.11-3.ph4.aarch64
Installing/Updating: openssl-3.0.3-3.ph4.aarch64
Installing/Updating: bzip2-libs-1.0.8-4.ph4.aarch64
Installing/Updating: xz-libs-5.2.5-2.ph4.aarch64
Installing/Updating: ncurses-libs-6.2-6.ph4.aarch64
Installing/Updating: ncurses-6.2-6.ph4.aarch64
Installing/Updating: util-linux-libs-2.37.4-1.ph4.aarch64
Installing/Updating: elfutils-libelf-0.181-4.ph4.aarch64
Installing/Updating: krb5-1.17-7.ph4.aarch64
Installing/Updating: util-linux-2.37.4-1.ph4.aarch64
Installing/Updating: pcre-libs-8.44-3.ph4.aarch64
Installing/Updating: libselinux-3.3-1.ph4.aarch64
Installing/Updating: coreutils-selinux-9.1-1.ph4.aarch64
Installing/Updating: Linux-PAM-1.4.0-5.ph4.aarch64
Installing/Updating: libcap-2.43-2.ph4.aarch64
Installing/Updating: expat-libs-2.2.9-9.ph4.aarch64
Installing/Updating: lua-5.4.4-2.ph4.aarch64
Installing/Updating: openssh-clients-8.8p1-3.ph4.aarch64
Installing/Updating: xz-5.2.5-2.ph4.aarch64
Installing/Updating: libssh2-1.9.0-4.ph4.aarch64
Installing/Updating: pkg-config-0.29.2-4.ph4.aarch64
Installing/Updating: lz4-1.9.2-2.ph4.aarch64
Installing/Updating: libgcrypt-1.9.4-1.ph4.aarch64
Installing/Updating: ca-certificates-pki-20201001-2.ph4.aarch64
Installing/Updating: curl-libs-7.83.1-2.ph4.aarch64
Installing/Updating: ca-certificates-20201001-2.ph4.aarch64
Installing/Updating: curl-7.83.1-2.ph4.aarch64
Installing/Updating: systemd-libs-247.11-3.ph4.aarch64
Installing/Updating: ncurses-devel-6.2-6.ph4.aarch64
Installing/Updating: cpio-2.13-7.ph4.aarch64
Installing/Updating: expat-2.2.9-9.ph4.aarch64
Installing/Updating: python3-3.10.0-3.ph4.aarch64
'/usr/bin/python' -> '/usr/bin/python3'
Installing/Updating: python3-libs-3.10.0-3.ph4.aarch64
Installing/Updating: cracklib-2.9.7-2.ph4.aarch64
Installing/Updating: pcre-8.44-3.ph4.aarch64
Installing/Updating: glib-2.68.0-1.ph4.aarch64
Installing/Updating: ncurses-terminfo-6.2-6.ph4.aarch64
Installing/Updating: openssh-server-8.8p1-3.ph4.aarch64
Installing/Updating: libxml2-2.9.12-4.ph4.aarch64
Installing/Updating: libarchive-3.4.3-5.ph4.aarch64
Installing/Updating: elfutils-0.181-4.ph4.aarch64
Installing/Updating: bzip2-1.0.8-4.ph4.aarch64
Installing/Updating: nspr-4.32-1.ph4.aarch64
Installing/Updating: nss-libs-3.72-1.ph4.aarch64
Installing/Updating: rpm-libs-4.16.1.3-9.ph4.aarch64
Installing/Updating: libsolv-0.7.19-4.ph4.aarch64
Installing/Updating: nettle-3.7.3-1.ph4.aarch64
Installing/Updating: gnutls-3.7.1-2.ph4.aarch64
Installing/Updating: tdnf-cli-libs-3.3.1-1.ph4.aarch64
Installing/Updating: systemd-rpm-macros-247.11-3.ph4.noarch
Installing/Updating: systemd-pam-247.11-3.ph4.aarch64
Installing/Updating: systemd-247.11-3.ph4.aarch64
initramfs (re)generation triggerin 1 2 2.0-6.ph4
Installing/Updating: systemd-udev-247.11-3.ph4.aarch64
Installing/Updating: dracut-050-8.ph4.aarch64
Installing/Updating: motd-0.1.3-7.ph4.noarch
Installing/Updating: iptables-1.8.7-5.ph4.aarch64
Installing/Updating: openssh-8.8p1-3.ph4.aarch64
Installing/Updating: tdnf-3.3.1-1.ph4.aarch64
Installing/Updating: rpm-4.16.1.3-9.ph4.aarch64
Installing/Updating: libpwquality-1.4.2-2.ph4.aarch64
Installing/Updating: gptfdisk-1.0.7-2.ph4.aarch64
Installing/Updating: linux-5.10.118-5.ph4.aarch64
initrd generation of kernel 5.10.118-5.ph4 will be triggered later
Installing/Updating: iproute2-5.10.0-2.ph4.aarch64
Installing/Updating: procps-ng-3.3.17-1.ph4.aarch64
Installing/Updating: vim-8.2.5164-1.ph4.aarch64
Installing/Updating: wpa_supplicant-2.10-1.ph4.aarch64
Installing/Updating: gzip-1.12-2.ph4.aarch64
Installing/Updating: glibc-iconv-2.32-11.ph4.aarch64
Installing/Updating: grub2-efi-image-2.06-3.ph4.aarch64
Installing/Updating: linux-firmware-20210817-1.ph4.noarch
Installing/Updating: photon-release-4.0-2.ph4.noarch
Installing/Updating: photon-repos-4.0-3.ph4.noarch
/var/tmp/rpm-tmp.dA28QJ: line 1: fg: no job control
Removing: rpm-4.16.1.2-1.ph4.aarch64
detected uninstall of tdnf/motd, disabling tdnf-cache-updateinfo.timer
Removing: tdnf-3.0.0-5.ph4.aarch64
Removing: rpm-libs-4.16.1.2-1.ph4.aarch64
Removing: iproute2-5.10.0-1.ph4.aarch64
Removing: iptables-1.8.7-1.ph4.aarch64
Failed to try-restart ip6tables.service: Unit ip6tables.service not found.
Removing: nss-libs-3.57-2.ph4.aarch64
Removing: nspr-4.29-1.ph4.aarch64
Removing: wpa_supplicant-2.9-2.ph4.aarch64
Removing: gptfdisk-1.0.5-1.ph4.aarch64
Removing: libpwquality-1.4.2-1.ph4.aarch64
Removing: procps-ng-3.3.16-1.ph4.aarch64
Removing: vim-8.2.1361-1.ph4.aarch64
Removing: motd-0.1.3-6.ph4.noarch
detected upgrade of tdnf/motd, restarting tdnf-cache-updateinfo.timer
initrd of kernel 5.10.4-16.ph4 removed
Removing: linux-5.10.4-16.ph4.aarch64
Removing: openssh-8.4p1-2.ph4.aarch64
Removing: grub2-efi-image-2.04-2.ph4.aarch64
Removing: linux-firmware-20210209-1.ph4.noarch
Removing: photon-release-4.0-1.ph4.noarch
Removing: photon-repos-4.0-2.ph4.noarch
Removing: openssh-server-8.4p1-2.ph4.aarch64
Removing: python3-3.9.1-2.ph4.aarch64
Removing: python3-libs-3.9.1-2.ph4.aarch64
Removing: openssh-clients-8.4p1-2.ph4.aarch64
Removing: libsolv-0.6.35-7.ph4.aarch64
Removing: dracut-050-7.ph4.aarch64
Removing: systemd-pam-247.3-1.ph4.aarch64
Removing: systemd-247.3-1.ph4.aarch64
Removing: util-linux-2.36-2.ph4.aarch64
Removing: elfutils-0.181-2.ph4.aarch64
Removing: systemd-libs-247.3-1.ph4.aarch64
Removing: glib-2.66.1-1.ph4.aarch64
Removing: curl-7.74.0-1.ph4.aarch64
Removing: curl-libs-7.74.0-1.ph4.aarch64
Removing: gnutls-3.6.15-3.ph4.aarch64
Removing: krb5-1.17-4.ph4.aarch64
Removing: Linux-PAM-1.4.0-2.ph4.aarch64
Removing: libarchive-3.4.3-3.ph4.aarch64
Removing: xz-5.2.5-1.ph4.aarch64
Removing: pcre-8.44-2.ph4.aarch64
Removing: libselinux-3.1-1.ph4.aarch64
Removing: libssh2-1.9.0-3.ph4.aarch64
Removing: expat-2.2.9-3.ph4.aarch64
Removing: cracklib-2.9.7-1.ph4.aarch64
Removing: coreutils-8.32-3.ph4.aarch64
Removing: xz-libs-5.2.5-1.ph4.aarch64
Removing: elfutils-libelf-0.181-2.ph4.aarch64
Removing: util-linux-libs-2.36-2.ph4.aarch64
Removing: bzip2-1.0.8-3.ph4.aarch64
Removing: pkg-config-0.29.2-3.ph4.aarch64
Removing: glibc-iconv-2.32-2.ph4.aarch64
Removing: zlib-1.2.11-2.ph4.aarch64
Removing: nettle-3.6-1.ph4.aarch64
Removing: libgcrypt-1.8.6-2.ph4.aarch64
Removing: lz4-1.9.2-1.ph4.aarch64
Removing: expat-libs-2.2.9-3.ph4.aarch64
Removing: cpio-2.13-3.ph4.aarch64
Removing: lua-5.3.5-1.ph4.aarch64
Removing: bzip2-libs-1.0.8-3.ph4.aarch64
Removing: pcre-libs-8.44-2.ph4.aarch64
Removing: libcap-2.43-1.ph4.aarch64
Removing: tdnf-cli-libs-3.0.0-5.ph4.aarch64
Removing: gzip-1.10-1.ph4.aarch64
Removing: ca-certificates-20201001-1.ph4.aarch64
Removing: ncurses-terminfo-6.2-3.ph4.aarch64
Removing: ca-certificates-pki-20201001-1.ph4.aarch64
Removing: systemd-rpm-macros-247.3-1.ph4.noarch
Removing: openssl-1.1.1i-2.ph4.aarch64
Removing: ncurses-6.2-3.ph4.aarch64
Removing: ncurses-libs-6.2-3.ph4.aarch64
Removing: glibc-2.32-2.ph4.aarch64
**Created symlink /etc/systemd/system/basic.target.wants/rpmdb-rebuild.service → /usr/lib/systemd/system/rpmdb-rebuild.service.
(re)generate initramfs for all kernels, transfilertriggerin 2.0-6.ph4
Creating /boot/initrd.img-5.10.118-5.ph4
Error(1525) : rpm transaction failed**
`

I tried above steps but the issue persists:
`root@photon-rpi [ ~ ]# rpm --noscripts -e systemd-udev-247.11-3.ph4
root@photon-rpi [ ~ ]# tdnf install systemd-udev-247.11-3.ph4          

Upgrading:
systemd-udev                                        aarch64                   247.11-3.ph4                       photon-updates                8.12M 8511205

Total installed size:   8.12M 8511205
Is this ok [y/N]: y

Downloading:
systemd-udev                           1297356 100%
Testing transaction
Running transaction
Installing/Updating: systemd-udev-247.11-3.ph4.aarch64
/var/tmp/rpm-tmp.iydRur: line 1: fg: no job control
package systemd-udev-247.3-1.ph4.aarch64: script error in %preun
Error(1525) : rpm transaction failed
`

Could you guide me on troubleshooting @ssahani?
