### ISSUE TITLE
Photon 3: new python2 does not have `xml.etree.ElementTree` which break LogInsight 8

### ISSUE THREAD

**Issue by dna2github** [vmware/photon#1128]
Deployed a LogInsight 8.1.0 instance (from OVA) and it is running on Photon OS.

```
# https://kb.vmware.com/s/article/81304
cd /etc/yum.repos.d/
sed  -i 's/dl.bintray.com\/vmware/packages.vmware.com\/photon\/$releasever/g' photon.repo photon-updates.repo photon-extras.repo photon-debuginfo.repo
```

to make sure we can update os packages.

`ps -ef | grep loginsight` and there are lots of java processes

after `tdnf install git`, it will automatically update python2 and then LogInsight process breaks (now `ps -ef | grep loginsight`, java processes gone).

well, I just want to git clone and install webhook-shim from source: https://github.com/vmw-loginsight/webhook-shims, but loginsight service down!

**we find that the updated python2 does not compiled with xml support** (e.g. no `xml.etree.ElementTree`).

anyway, we have 2 ways to fix it:
- compile python2 with xml support works (requires more packages installed, gcc, binutils, glibc-devel, ...)
- mv python to python.bak and create soft link to python3 works.

LogInsight works before my update, so that there should be xml support in original python.
**could you add xml support back for latest python2 package in Photon? Thx in advance.**

**Comment by ssahani** [comment]
Thanks for the investigation. Any photon version is this ?

**Comment by dna2github** [comment]
at least, i found python2 issues on these versions:

Linux localhost 4.19.29-1.ph3
Linux localhost 4.19.164-3.ph3-esx

**Comment by tapakund** [comment]
> tdnf install python2 && python2 -c 'import xml.etree.ElementTree; print 1'

Unable to repro this on photon 3.0

```
root@photon-4a0e7f2307d4 [ ~ ]# cat /etc/photon-release
VMware Photon OS 3.0
PHOTON_BUILD_NUMBER=11dd065
root@photon-4a0e7f2307d4 [ ~ ]# tdnf install python2 && python2 -c 'import xml.etree.ElementTree; print 1'
Package python2 is already installed.
Nothing to do.
1
root@photon-4a0e7f2307d4 [ ~ ]#
root@photon-4a0e7f2307d4 [ ~ ]# ls -la /usr/bin/python2
lrwxrwxrwx 1 root root 9 Jul 24  2020 /usr/bin/python2 -> python2.7
root@photon-4a0e7f2307d4 [ ~ ]# ls -la /usr/bin/python2.7
-rwxr-xr-x 1 root root 15336 Jul 24  2020 /usr/bin/python2.7
root@photon-4a0e7f2307d4 [ ~ ]#
```

Did you check if you have 'python-xml' installed or not?

```
root@photon-4a0e7f2307d4 [ ~ ]# rpm -qa | grep python-xml
python-xml-2.7.17-5.ph3.x86_64
root@photon-4a0e7f2307d4 [ ~ ]#
```

**Comment by dna2github** [comment]
**currently the problem is: `tdnf install git` -> `automatically update python2` -> `break loginsight` (Linux localhost 4.19.29-1.ph3 (LogInsight Version 8.1.0-15961774))

in LogInsight, there is no `python3-xml` installed but `python3 -c "import xml.etree.EleementTree; print 1"` works but `python2` failed**

and your solution is to install a dependency library `python-xml` ..
.
if `python-xml` include `xml` lib and I think it works. but i wonder why `python3-xml` is installed by default but `python-xml` is not a required dependency for `python2`?

and check in Linux localhost 4.19.164-3.ph3-esx (photon-hw13_uefi-3.0-26156e2); yes, after `tdnf update` and then python2 has `xml.etree.EleementTree`.

**Comment by ssahani** [comment]
hmm how did you installed loginsight ?

**Comment by dna2github** [comment]
> Deployed a LogInsight 8.1.0 instance (from OVA) and it is running on Photon OS.

**Comment by ssahani** [comment]
Should not loginsignt package have ```requires``` in the spec . We don't provide it .

```
 > sudo tdnf install loginsight
loginsight package not found or not installed
Error(1011) : No matching packages
~ >
```

**Comment by dna2github** [comment]
> Should not loginsignt package have `requires` in the spec . We don't provide it .
> 
> ```
>  > sudo tdnf install loginsight
> loginsight package not found or not installed
> Error(1011) : No matching packages
> ~ >
> ```

loginsight is not available via `tdnf`; it is released as an OVA file and can be imported into ESXi, where it is a VM with Photon 3.

**Comment by dna2github** [comment]
python has a built-in xml support and do not need extra `python-xml`. and kindly again:

```
actually the bug can reproduce in a common Photon 3:
tdnf install python2 (tdnf remove python-xml python3-xml);
then python3's xml lib still works but python2 does not and need extra python-xml.
```

**Comment by ssahani** [comment]
You mean the python itself should support python-xml  ? why

**Comment by dna2github** [comment]
> You mean the python itself should support python-xml ? why

The problem is: LogInsight can be broken when `tdnf install git`; if `python-xml` essential package, why `tdnf install git` -> `install python2` but `python-xml` is not installed (and why by default LogInsight can run? and after `tdnf install git` and `python2` updated and it is broken? which means that, before in `dl.bintray.com`, the python2 has built-in xml support, and after move to `packages.vmware.com`, python2 xml support is missing)

moreover, why in there is built-in xml support for python3 but no support for python2?

**Comment by ssahani** [comment]
we don't support loginsignt. Hence not out bug.
