### ISSUE TITLE
Broken links in Security Advisories for 2.0

### ISSUE THREAD

**Issue by jinxka** [vmware/photon#1170]
Hello,

There is a missing parenthesis on the link for Security-Updates-2-329 and Security-Updates-2-330

https://github.com/vmware/photon/wiki/Security-Advisories-2

![image](https://user-images.githubusercontent.com/11526533/112301039-d5377b00-8c99-11eb-96c6-05863b1455c8.png)

**Comment by ssahani** [comment]
It would be great if you send a patch. Thanks in advance

**Comment by smaliakkal** [comment]
@ssahani ,@jinxka ,

Sorry for late reply, didn't see this issue earlier. It is corrected.

**Comment by YustasSwamp** [comment]
Thanks!
