### ISSUE TITLE
Enable CONFIG_FANOTIFY_ACCESS_PERMISSIONS in the kernel

### ISSUE THREAD

**Issue by sand7000** [vmware/photon#1177]
CONFIG_FANOTIFY is enabled but CONFIG_FANOTIFY_ACCESS_PERMISSIONS is not. This means some security software including sophos antivirus does not work properly.

**Comment by ssahani** [comment]
Which version of photon is this ? /CC @YustasSwamp

**Comment by sand7000** [comment]
I installed using photon-4.0-1526e30ba.iso which I downloaded from https://packages.vmware.com/photon/4.0/GA/iso/

**Comment by YustasSwamp** [comment]
Will be added

**Comment by Vasavisirnapalli** [comment]
@keerthanakalyan is working on it

**Comment by keerthanakalyan** [comment]
Enabled CONFIG_FANOTIFY_ACCESS_PERMISSIONS in Photon 3.0 and 4.0 branches
3.0 - https://github.com/vmware/photon/commit/086c06d343e883f0cd46d8e77ba1c30a60d7e642 
4.0 - https://github.com/vmware/photon/commit/79f1240947204d50e1c2a44dce930aa7b77c7b27

**Comment by ssahani** [comment]
Thanks @keerthanakalyan
