### ISSUE TITLE
openssl-c_rehash package doesn't need to depend on perl

### ISSUE THREAD

**Issue by jpeach** [vmware/photon#1179]
OpenSSL now has a `openssl rehash` command that is mean to do the same thing as the c_rehash perl script. This means that the `openssl-c_rehash` package is obsolete, and that `rehash_ca_certificates.sh` should probably be implemented in terms of `openssl rehash`.

**Comment by ssahani** [comment]
Which photon version is it and package version please. /CC @tapakund

**Comment by satya-rajesh** [comment]
We are fixing it:
1) Removing c_rehash utility from packaging (as openssl has the option)
2) Remove perl dependencies
3) Use openssl rehash in rehash_ca_certificates.sh

**Comment by tapakund** [comment]
changes are merged https://github.com/vmware/photon/commit/875d985717579e0042e356cf59bd9d9190b36200
