### ISSUE TITLE
No PCI devices information on Photon OS as Azure virtual machine V2

### ISSUE THREAD

**Issue by dcasota** [vmware/photon#1180]
Hi,

fyi On the Azure hyperscaler platform recently there were some changes which have impact to Photon OS PCI devices detection. The Azure virtual machine generation V2 implementation got a newly pushed Bios firmware.

V1 still goes with MBR and is on ```Microsoft Corporation Virtual Machine/Virtual Machine, BIOS 090008  12/07/2018```

Newly created V2 virtual machines now are on  ```Microsoft Corporation Virtual Machine/Virtual Machine, BIOS Hyper-V UEFI Release v4.1 10/27/2020```
There were different dates with same Bios release number 4.1 in the past (at least one: ```BIOS Hyper-V UEFI Release v4.1 04/02/2020```). Afaik there is no get-vmfirmware and set-vmfirmware for Azure virtual machines Bios.

In a V1 virtual machine ```lspci``` and ```lshw``` works flawlessly, tested on Ph3rev2 + Ph4.

In a V2 virtual machine, lspci (v3.7.0) does not give any output, and produces warnings.
```
# lspci -M
WARNING: Bus mapping can be reliable only with direct hardware access enabled.

pcilib: Cannot open /sys/bus/pci/devices/0000:00:00.0/config
pcilib: Cannot open /sys/bus/pci/devices/0000:00:01.0/config
[...]
```
It is reproducible at least on Ph3rev2 and on Ph4. Tested on: Location Switzerlandnorth, VMSize Standard_B1ms, no accelerated networking, WALinuxAgent 2.2.53.1.

btw V2 is a 'trusted launch for Azure virtual machines' mandatory prerequisite. Accordingly to the preview feature it requires the creation of new virtual machines, and cannot be enabled on existing virtual machines that were initially created without it.

**Comment by YustasSwamp** [comment]
@dcasota thanks for heads up! What kernel do you use `uname -r`?

**Comment by dcasota** [comment]
generic, 5.10.35-1.ph4

**Comment by ssahani** [comment]
Also ```lspci: /usr/share/misc/pci.ids: No such file or directory
00:08.0 Class 0300: 1414:5353
00:07.0 Class 0601: 8086:7110
00:00.0 Class 0600: 8086:7192
00:07.3 Class 0680: 8086:7113
00:07.1 Class 0101: 8086:7111
```

**Comment by dcasota** [comment]
@ssahani @YustasSwamp Here's the [journalctl-debug.txt](https://github.com/vmware/photon/files/6541930/journalctl-debug.txt). See log entry ```PCI: System does not support PCI```, however it occurs after the entry ```efi: Failed to lookup EFI memory descriptor for```.

**Comment by sshedi** [comment]
@dcasota - can you please try below steps once?

1. Append `add_efi_memmap` in `/boot/grub/grub.cfg`.
```
menuentry "Photon" {
    linux /boot/$photon_linux root=$rootpartition $photon_cmdline $systemd_cmdline add_efi_memmap
    if [ -f /boot/$photon_initrd ]; then
        initrd /boot/$photon_initrd
    fi
}
```

2. Then run `rpm -q --scripts <installed-grub2-version> (can be obtained by running: $ rpm -q grub2-efi-image)`
3. Run `$ wget http://pci-ids.ucw.cz/v2.2/pci.ids -O /usr/share/misc/pci.ids`

Reboot and then try `lspci`

**Comment by akaher** [comment]
@dcasota, thanks for reporting this.

This is observed on both:
BIOS Hyper-V UEFI Release v4.1 10/27/2020
BIOS Hyper-V UEFI Release v4.1 04/02/2020

Please share the logs of https://github.com/Azure/linux-image-validations

**Comment by akaher** [comment]
@dcasota, deployed Ubuntu Gen V2: 
Linux akaher-ubuntu 5.8.0-1032-azure #34-Ubuntu SMP Thu May 6 08:29:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

And observed same issue:
[    0.140827] PCI: System does not support PCI

Have you seen any Linux Distro which doesn't have this issue? If no, then might be this is Azure issue.

**Comment by dcasota** [comment]
The rhel_ouput.json image validation logs didn't help. No idea if it would work with efi boot = false.  Still investigating in automation.

In my setup ```/proc/iomem``` clearly shows ```3ff9b000-3ffcafff : Unknown E820 type``` and in journalctl the memory map beginning with ```0x000000003ff9b000``` is declared as ```type 20```. And, facing Azure' ```ACPI: Core revision 20200925``` (journalctl entry), the 820.c source with prerequired acpi + firmware-map is evolving. At least in 820.c ```static struct e820_entry *__e820__mapped_all``` there were some changes after kernel 5.10.  pci=noacpi fails, add_efi_memmap (++) and some further tests with cmdline parameters didn't help getting PCI functionality (V2 + efi boot = false) back.

No hurry. Indeed I think there is no workaround available., too.

**Comment by akaher** [comment]
I had test rpm of Kernel v5.12 (1-2 month old version), tested on Photon but no luck.

**Comment by dcasota** [comment]
This PCI devices detection "issue" seems to be a new Azure feature preview, and counts for Photon, too. Just tried out secure boot on Ubuntu 20.04, gen2, and it's the same result, indeed.

```
Local@myTVM:~$ uname -r
5.4.0-1047-azure
Local@myTVM:~$ cat /etc/os-release | grep VERSION
VERSION="20.04.2 LTS (Focal Fossa)"
VERSION_ID="20.04"
VERSION_CODENAME=focal
Local@myTVM:~$ uname -r
5.4.0-1047-azure
Local@myTVM:~$ mokutil --sb-state
SecureBoot enabled
Local@myTVM:~$ journalctl -k | grep PCI
May 29 14:58:36 myTVM kernel: [mem 0x40000000-0xffffffff] available for PCI devices
May 29 14:58:36 myTVM kernel: ACPI: bus type PCI registered
May 29 14:58:36 myTVM kernel: acpiphp: ACPI Hot Plug PCI Controller Driver version: 0.5
May 29 14:58:36 myTVM kernel: PCI: Using host bridge windows from ACPI; if necessary, use "pci=nocrs" and report a bug
May 29 14:58:36 myTVM kernel: PCI: Using ACPI for IRQ routing
May 29 14:58:36 myTVM kernel: PCI: System does not support PCI
May 29 14:58:36 myTVM kernel: PCI: CLS 0 bytes, default 64
May 29 14:58:36 myTVM kernel: PCI-DMA: Using software bounce buffering for IO (SWIOTLB)
May 29 14:58:36 myTVM kernel: shpchp: Standard Hot Plug PCI Controller Driver version: 0.4
Local@myTVM:/boot$ ls -ll
total 39437
-rw------- 1 root root  4463644 Apr 22 13:42 System.map-5.4.0-1047-azure
-rw-r--r-- 1 root root   154633 Apr 22 13:42 config-5.4.0-1047-azure
drwx------ 3 root root      512 Jan  1  1970 efi
drwxr-xr-x 5 root root     4096 May 13 16:25 grub
lrwxrwxrwx 1 root root       27 May 13 16:24 initrd.img -> initrd.img-5.4.0-1047-azure
-rw-r--r-- 1 root root 26849588 May 13 16:25 initrd.img-5.4.0-1047-azure
lrwxrwxrwx 1 root root       27 May 13 16:24 initrd.img.old -> initrd.img-5.4.0-1047-azure
lrwxrwxrwx 1 root root       24 May 13 16:24 vmlinuz -> vmlinuz-5.4.0-1047-azure
-rw------- 1 root root  8900864 Apr 22 13:24 vmlinuz-5.4.0-1047-azure
lrwxrwxrwx 1 root root       24 May 13 16:24 vmlinuz.old -> vmlinuz-5.4.0-1047-azure
Local@myTVM:/boot$
```

In /boot there are these two files system.map-{version}-azure and config-{version}-azure. They look like a huge(!) memory+config map , with option type values. Not sure if it is allowed to modify the entries and what impact each entry has. Didn't find any low-level docs.

In addition, the method used of creating a temporary w2k19 virtual machine gen2 to use it as virtual hardware for creating a Photon Az gen2 image does not work for secure boot. Okay, that's solvable.

I'll close this issue, sorry folks for the trouble.
