### ISSUE TITLE
[DOCS] Downloading Photon OS

### ISSUE THREAD

**Issue by hanscees** [vmware/photon#1181]
where to find howto login in the ova package? Please add a link or something.

**Comment by dcasota** [comment]
Hi @hanscees,
The ova format is readable by the ovftool, see https://www.vmware.com/support/developer/ovf/

Hope this helps. Daniel

**Comment by ssahani** [comment]
I am not sure about the question. Is it how to login to ova  ? root/changeme

https://vmware.github.io/photon/assets/files/html/3.0/photon_installation/importing_ova_for_photon_os_3.0.html

**Comment by hanscees** [comment]
Hi, 
sorry my question was not clear.
I downloaded the ova fine and deployed it.  However I needed the root passwd to log in and could not find it. Found it after a bit of searching. Perhaps if someone is as lame as me a link to the "deploy ova" html page would have helped.

**Comment by ssahani** [comment]
Closing it then?
