### ISSUE TITLE
sshd starts even after being disabled

### ISSUE THREAD

**Issue by chetwisniewski** [vmware/photon#1183]
I have a Photon OS 4 install on my ESXi server. I want it to be a dumb router and listen on no ports. I have disabled sshd.socket and sshd.service through systemd, yet it starts again every boot. Is this a bug? How to override?

**Comment by ssahani** [comment]
It's getting started by cloud-init

```
cloud-init.service:Wants=sshd.service
cloud-init.service:Before=sshd.service
```

Please mask it 
```
systemctl mask sshd.service

```

**Comment by ssahani** [comment]
Closing
