### ISSUE TITLE
Cannot install yum via tdnf (Hawkey general runtime error)

### ISSUE THREAD

**Issue by ayoubhbn** [vmware/photon#1184]
Hello everyone!

I want to use Ansible to automate some VMware vSphere processus like VM creation and the first step would be to install pip and pyvmomi and for that I need to install yum via **tdnf install yum**

However, I get this error.

![Screenshot](https://user-images.githubusercontent.com/49964333/115413499-be2a7100-a1e4-11eb-9e4d-56d6e9fe101b.png)

The screenshot above also provides information about Photon OS version and the enabled repos.

I would appreciate any help. Thank you.

**Comment by dcasota** [comment]
Since Photon OS 3.0 Ansible plays quite nicely, see @texiwill [VMware Software Manager 6.4.5 and above](https://github.com/Texiwill/aac-lib/tree/master/vsm).
#879 this hasn't been officially backported to 2.0. though.

**Comment by YustasSwamp** [comment]
As @dcasota mentioned, it is available in Photon 3.0 and higher. We do not have a plans to backport it to older Photon versions.
@ayoubhbn please consider updating Photon version.
