### ISSUE TITLE
Package request: nmap and other basic system administration tools

### ISSUE THREAD

**Issue by mkrupczakVMware** [vmware/photon#1186]
I'm an employee at vmware and I was having trouble recently with a customer's lab setup due to the limited packages available through tdnf on Photon OS. 

For instance, there were networking and security errors that could not be properly debugged due to the lack of simple system tools such as nmap. 

The estimated impact on customers is high, as they will expect the availability of these kind of tools to follow operations and security best practices. 

Recommend that such packages are made available as soon as possible, or improved methods for extra packages are made standard. 

An example list of some common and uncommon systems tools:

https://github.com/mkrupczakVMware/gettools

**Comment by ssahani** [comment]
You only want nmap or some other packages too. And which version of photon is this ?

**Comment by mkrupczakVMware** [comment]
@ssahani Version 3.0 of Proton

nmap is critical, other packages would be very nice

I can build out a list of other really important tools if necessary, but off the top of my head:

htop
ncdu
curl
dig
dos2unix
mg
vim
ethtool
finger
git
iftop
iostat
iotop
less
lsof
lspci
more
mtr
nmon
ntop
openssl
openvpn
smartmontools
tmux
whois

**Comment by mkrupczakVMware** [comment]
I'm not aware of an "extra packages" available as an alternative to tndf on Photon, but an extra packages solution should really be promoted as an option for customers. 

I'm only a novice sysadmin and I was really wigged out by the lack of available packages. 

I know on Centos/RHEL for instance, EPEL is almost essential for best practices systems administration. Not having this extensibility on Photon severely limits customer success in usage.

**Comment by ssahani** [comment]
hmm did you tested precisely which are not available. Superficially I can see more than half of them is available . Please test first then update the request .

**Comment by mkrupczakVMware** [comment]
Well then, almost half aren't! 

nmap is an essential

Still, the topic of this issue: needing nmap and a better extra packages solution, exists irrespective to the availability of individual packages. This will be a major pain point for customers

**Comment by ssahani** [comment]
Please test and make precise request . We can add nmap though. nmap can be added though .
/CC @suezzelur

**Comment by mkrupczakVMware** [comment]
As has already been stated @ssahani , this is on Photon 3.0

I have already tested and my precise request is:
add nmap as a package and get a workable extra packages solution or no customer will ever want to touch this crappy off-brand Linux distro
