### ISSUE TITLE
cant install wget on photon 3

### ISSUE THREAD

**Issue by hanscees** [vmware/photon#1188]
Is the photon3 repo in trouble perhaps? 

this happens when I try to install wget:

`tdnf update
Nothing to do.
root@mail [ ~ ]# wget https://dl.bintray.com/vmware/photon_release_3.0_x86_64/repodata/repomd.xml
-bash: wget: command not found
root@mail [ ~ ]# tdnf install wget

Installing:
wget                     x86_64       1.20.3-1.ph3     photon-updates   2.80M 2936976

Total installed size:   2.80M 2936976
Is this ok [y/N]:y

Downloading:
Error: 404 when downloading https://dl.bintray.com/vmware/photon_updates_3.0_x86_64/x86_64/wget-1.20.3-1.ph3.x86_64.rpm
. Please check repo url.
Error processing package: x86_64/wget-1.20.3-1.ph3.x86_64.rpm
Error(1622) : Invalid argument
`

**Comment by ssahani** [comment]
Ahh please see https://kb.vmware.com/s/article/82322

**Comment by hanscees** [comment]
Thanks! that solves the problem. 
But I was under the impression that the repro change should have gone automagically? I do not run k8, just some photon hosts on esxi.

**Comment by hanscees** [comment]
but I still get an error on the extra repofile 
vi /etc/yum.repos.d/photon-extras.repo

if I change that file to 
`[photon-extras]
name=VMware Photon Extras $releasever ($basearch)
baseurl=https://packages.vmware.com/photon/photon_extras_$releasever_$basearch
gpgkey=file:///etc/pki/rpm-gpg/VMWARE-RPM-GPG-KEY
gpgcheck=1
enabled=1
skip_if_unavailable=True`

I get an error

**Comment by hanscees** [comment]
wait that urls for the extra should be 
baseurl=https://packages.vmware.com/photon/$releasever/photon_extras_$releasever_$basearch

got it

**Comment by hanscees** [comment]
so for all repos
`sed -i 's#baseurl=https://dl.bintray.com/vmware#baseurl=https://packages.vmware.com/photon/$releasever#g' /etc/yum.repos.d/photon.repo

sed -i 's#baseurl=https://dl.bintray.com/vmware#baseurl=https://packages.vmware.com/photon/$releasever#g' /etc/yum.repos.d/photon-updates.repo

sed -i 's#baseurl=https://dl.bintray.com/vmware#baseurl=https://packages.vmware.com/photon/$releasever#g' /etc/yum.repos.d/photon-extras.repo

`
and then tdnf update.

I am not happy by the way, since I have missed many updates unwanted of course

**Comment by ssahani** [comment]
It's changed way back from october last year https://github.com/vmware/photon/wiki/changes-to-repository-location-in-photon

**Comment by ssahani** [comment]
CLosing as I think issue is resolved
