### ISSUE TITLE
Pi4 PoE Hat Active Cooling Support

### ISSUE THREAD

**Issue by theCiscoGeek** [vmware/photon#1190]
Is it possible to have the PoE driver included on the next build? My Pi farm (and others without a doubt) is powered by PoE, but without the driver the fan on the official pi PoE hat isn't operational and they cook themselves. At this point I have only a basic knowledge of how to compile a kernel, and I don't have the skillset to add this driver and test independently, but I'm more than happy to do whatever I can to help this along.

Here's what I believe the necessary driver is, though for a slightly newer kernel version than the current GA (from the RasberryPi Github):
https://github.com/raspberrypi/firmware/blob/master/modules/5.10.33-v8%2B/kernel/drivers/hwmon/rpi-poe-fan.ko

**Comment by akaher** [comment]
@YustasSwamp rpi-poe-fan.ko not upstreamed, so stability of this driver not sure. Please suggest.
Source Code: https://github.com/raspberrypi/linux/blob/rpi-5.10.y/drivers/hwmon/rpi-poe-fan.c

**Comment by YustasSwamp** [comment]
Should be fine. Let's add it.

**Comment by ssahani** [comment]
closed via https://github.com/vmware/photon/commit/9ed3df365be53f72b6ebaaf1c8b0505a349587aa

**Comment by akaher** [comment]
Changes have been merged to linux-5.10.35-3.ph4.aarch64.rpm.

This rpm will be published at following location:
https://packages.vmware.com/photon/4.0/photon_updates_4.0_aarch64/aarch64/

Once published, please use 'tdnf update linux'.

Thanks @theCiscoGeek.

**Comment by theCiscoGeek** [comment]
Outstanding, thank you!!!

I'll keep my eye out for it!
