### ISSUE TITLE
Photon OS 4 - PHOTON_BUILD_NUMBER=1526e30ba

### ISSUE THREAD

**Issue by gorans73** [vmware/photon#1194]
No ping or login screen on Vm console after tdnf update

**sudo tdnf check-update**
systemd.x86_64                               247.6-1.ph4          photon-updates
systemd-libs.x86_64                          247.6-1.ph4          photon-updates
systemd-pam.x86_64                           247.6-1.ph4          photon-updates
systemd-rpm-macros.noarch                    247.6-1.ph4          photon-updates
systemd-udev.x86_64                          247.6-1.ph4          photon-updates

**sudo tdnf update**

Upgrading:
systemd-udev                                                x86_64                        247.6-1.ph4                             photon-updates                      8.50M 8916728
systemd-rpm-macros                                          noarch                        247.6-1.ph4                             photon-updates                         5.45k 5581
systemd-pam                                                 x86_64                        247.6-1.ph4                             photon-updates                      1.45M 1515438
systemd-libs                                                x86_64                        247.6-1.ph4                             photon-updates                      6.74M 7063212
systemd                                                     x86_64                        247.6-1.ph4                             photon-updates                    66.82M 70063879

Total installed size:  83.51M 87564838
Is this ok [y/N]: **y**

Downloading:
systemd-udev                           1338276   100%
systemd-rpm-macros                       16471   100%
systemd-pam                             475086   100%
systemd-libs                           1305110   100%
systemd                               11202915   100%
Testing transaction
Running transaction
Installing/Updating: systemd-libs-247.6-1.ph4.x86_64
Installing/Updating: systemd-rpm-macros-247.6-1.ph4.noarch
Installing/Updating: systemd-pam-247.6-1.ph4.x86_64
Installing/Updating: systemd-247.6-1.ph4.x86_64
initramfs (re)generation triggerin 1 2 2.0-6.ph4
Installing/Updating: systemd-udev-247.6-1.ph4.x86_64
/var/tmp/rpm-tmp.D89i4a: line 1: fg: no job control
Removing: systemd-pam-247.3-1.ph4.x86_64
Removing: systemd-247.3-1.ph4.x86_64
Removing: systemd-rpm-macros-247.3-1.ph4.noarch
Removing: systemd-libs-247.3-1.ph4.x86_64
(re)generate initramfs for all kernels, transfilertriggerin 2.0-6.ph4
Creating /boot/initrd.img-5.10.25-10.ph4-esx
Error(1525) : rpm transaction failed

After this reboot and result is no ping or login prompt on VM console, just a blanc screen...
Any ideas?

**Comment by gorans73** [comment]
**cat /etc/os-release**
NAME="VMware Photon OS"
VERSION="4.0"
ID=photon
VERSION_ID=4.0
PRETTY_NAME="VMware Photon OS/Linux"
ANSI_COLOR="1;34"
HOME_URL="https://vmware.github.io/photon/"
BUG_REPORT_URL="https://github.com/vmware/photon/issues"

**cat /etc/photon-release**
VMware Photon OS 4.0
PHOTON_BUILD_NUMBER=1526e30ba

**Comment by dcasota** [comment]
@gorans73 Comparing with your findings, did you start with a vanilla Ph4 or as upgrade from Ph3?

1) Photon OS 3.0 + upgrade to 4.0
The vanilla Ph3 runs with iptables chain input&output config DROP. So no ping.
At the moment of started ```sudo photon-upgrade.sh``` right before the reboot is executed, you get the issue
```
Reboot is recommended after an upgrade. Reboot now(y/n)?y
/bin/photon-upgrade.sh: line 71: reboot: command not found
```
In this situaton before reboot, Ph3 iptables chain input&output runs with temporary config ACCEPT. Restarted as Ph4, the config is on DROP again.

2) Photon OS 4.0
The vanilla Ph4 runs with iptables chain input&output config ACCEPT. 


[Vhd pristine setup Photon OS 4.0.txt](https://github.com/vmware/photon/files/6539613/Pristine.setup.Photon.OS.4.0.txt)

[Vhd pristine setup Photon OS 3.0 + Upgrade to 4.0.txt](https://github.com/vmware/photon/files/6539610/Pristine.setup.Photon.OS.3.0.%2B.Upgrade.to.4.0.txt)

**Comment by ssahani** [comment]
>After this reboot and result is no ping or login prompt on VM console, just a blanc screen...
Any ideas?

Need the logs
https://vmware.github.io/photon/assets/files/html/3.0/photon_troubleshoot/enabling-systemd-debug.html

**Comment by gorans73** [comment]
@dcasota started with plain vanila Ph4... did all steps as you, but no luck
@ssahani enabled: systemctl enable debug-shell.service run tdnf update, reboot.. no ping... open vm console and enter shell Ctrl+Alt+F9
run systemctl list-jobs 
Networking showing as starting and hanging there
cd to /etc/systemd/network
[ /etc/systemd/network ]$ ls
99-dhcp-en.network  99-static-en.network
mv 99-static-en.network 10-static-en.network
reboot
all good now...
Thanx for help guys...
