### ISSUE TITLE
nginx before 1.20.1 has a vulnerability CVE.

### ISSUE THREAD

**Issue by wangyanghack** [vmware/photon#1199]
nginx has a vulnerability CVE.
CNNVD recommend upgrade nginx to the latest versions(1.20.1, 1.21.0) which has been patched for this vulnerability. Have nginx-1.19.3 in photon-4 been fixed this vulnerability?
http://www.cnnvd.org.cn/web/xxk/ldxqById.tag?CNNVD=CNNVD-202105-1581

**Comment by wangyanghack** [comment]
I find this patch, I think photon-4.0 has fix it. So Can I think the image photon:latest has fix it? Right?
https://github.com/vmware/photon/blob/4.0/SPECS/nginx/0001-nginx-DNS-Resolver-Off-by-One-Heap-Write-in-ngx_reso.patch
Thanks

**Comment by tapakund** [comment]
Yes, nginx-1.19.3-2 have the fix in photon 4.0

I think default photon:latest does not have nginx, but if you install nginx it would pull the latest with the fix

root [ / ]# tdnf install nginx

Installing:
pcre-libs                x86_64       8.44-2.ph4       photon-release 271.63k 278154
nginx                    x86_64       1.19.3-2.ph4     photon-updates   1.81M 1893088

Total installed size:   2.07M 2171242
Is this ok [y/N]: y

Downloading:
pcre-libs                               102037   100%
nginx                                   652796   100%
Testing transaction
Running transaction
Installing/Updating: pcre-libs-8.44-2.ph4.x86_64
Installing/Updating: nginx-1.19.3-2.ph4.x86_64

Complete!
root [ / ]#

**Comment by wangyanghack** [comment]
OK! thanks a lot!
