### ISSUE TITLE
can Photon run on a KVM host?

### ISSUE THREAD

**Issue by vrms** [vmware/photon#1214]
The README says

   _"Optimized for VMware hypervisor: The Linux kernel is tuned for performance when Photon OS runs on VMware ESXi."_

now I am wondering whether that means it runs better (optimized) or only on ESXi Hosts? I am asking based on [this thread](https://serverfault.com/questions/1069968/rebuild-a-vmware-machine-in-kvm-with-an-ova-file?noredirect=1#comment1396053_1069968) which indicates that the pks.ova (which is photon) fails to run on KVM and VirtualBox.

**Comment by vrms** [comment]
figured it basically out (by installing on a local KVM host). And on first sight it seems to be running.

I can not tell how good or bad though due to lack of understanding/expertise

**Comment by ssahani** [comment]
Thanks for the update
