### ISSUE TITLE
Can anyone help me with the EOL date for Photon 3.0 ?

### ISSUE THREAD

**Issue by prabal1m** [vmware/photon#1216]

**Comment by dcasota** [comment]
Imho there is no eol published. In addition to Linux kernel support plans see discussion https://github.com/vmware/photon/issues/1031

**Comment by dcasota** [comment]
see [Photon Blog](https://blogs.vmware.com/vsphere/2022/01/photon-1-x-end-of-support-announcement.html)

**Comment by ssahani** [comment]
![image](https://user-images.githubusercontent.com/145210/149157968-7ade3a9e-adb9-4573-a9ae-80b2d56200d5.png)
