### ISSUE TITLE
Package Request: tpm2-pkcs11

### ISSUE THREAD

**Issue by gabefighter99** [vmware/photon#1219]
Hello there,

I'm working out of ATG and we would really appreciate a tpm2-pkcs11 package. We need it to be used together with vTPM, in order to implement the PKCS#11 keystore.

Building from source is a pain, but some pointers that might come in handy when building/writing the SPEC: dependencies are listed on the git repository, most of them are available as packages. Notably, OpenSC is not packaged and must be built from source, but requires PCSC (again from source).

This is for the latest version of photon.

**Comment by YustasSwamp** [comment]
Hi @gabefighter99 This package looks valuable to add to Photon. Just to double check, are you using Photon OS 4.0?

**Comment by gabefighter99** [comment]
Yeap

**Comment by gabefighter99** [comment]
Any progress on the packaging for the tool? Or an ETA?

**Comment by Vasavisirnapalli** [comment]
@vbrahmajosyula is looking in to it. Will update by next week

**Comment by Vasavisirnapalli** [comment]
@vbrahmajosyula1

**Comment by vbrahmajosyula1** [comment]
The change is in review. Will update when its available to try.

**Comment by vbrahmajosyula1** [comment]
packages available in 4.0 updates repo
