### ISSUE TITLE
FQDN hostname is no longer preserved in latest Photon OS

### ISSUE THREAD

**Issue by lamw** [vmware/photon#1220]
There seems to be a regression in behavior in how FQDN hostname is persisted in latest Photon OS 3.x/4.x release. 

More details can be found https://williamlam.com/2021/08/quick-tip-preserving-fqdn-hostname-on-photon-os.html and workaround for us was to simply `touch /etc/cloud/cloud-init.disabled`

We did not see this behavior in PH 3 Rev 2, where cloud-init was on `cloud-init-19.4-12.ph3.noarch` but now using same build or even newer, cloud-init is `cloud-init-21.2-2.ph4.noarch` and has this behavior change caused unnecessary troubleshooting until I found this problem and workaround

**Comment by sshedi** [comment]
This has been fixed in https://github.com/vmware/photon/commit/632ccf0ca79f44a485cb384f3da1e22bcb554850
@ssahani please close this issue.
