### ISSUE TITLE
Install python3 without tdnf (Photon OS 4)

### ISSUE THREAD

**Issue by ygbillet** [vmware/photon#1261]
Hello,

I was having some issues with updating. It seems python3 was the problem.
So i uninstalled Python 3 without realizing that it was essential to tdnf.

Is there an clean way to reinstall python3 without tdnf ?

**Comment by oliverkurth** [comment]
Hi @ygbillet ,

I am confused - first, tdnf does not depend on python3, so uninstalling it should not uninstall tdnf. Second, tdnf cannot uninstall itself - it will check any operation would result in uninstalling and aborts if it would.

Which version of Photon is this? I am wondering if you are talking about dnf, but we don't ship that.

**Comment by ygbillet** [comment]
Hi @oliverkurth,

I uninstall python3 with tdnf. Next things was to re-install python3 with tdnf.
```
$ sudo tdnf install python3
Error(1304) : Solv - I/O error
```
Because i got this error after uninstalling Python3 with `tdnf.` I thought it was coming from there.

Have you an idea about this error ?

**Comment by oliverkurth** [comment]
Okay, I misunderstood the problem. I thought you uninstalled tdnf by accident.

First try `tdnf makecache` to get the latest metadata, then try again. If that does not help, do `tdnf list installed` and send the output.

**Comment by ygbillet** [comment]
```
$ sudo tdnf makecache
Error(1304) : Solv - I/O error
```

It seems that any command with `tdnf ...` end with `Error(1304) : Solv - I/O error`

**Comment by ygbillet** [comment]
I just reinstall `tdnf` with rpm.

Everything seems right !

**Comment by oliverkurth** [comment]
Glad you have it resolved.

I am still wondering if we have a bug, so if you can share any details about what led to this situation that would help.

**Comment by ygbillet** [comment]
Sure.

I tried to update my system with `tdnf update`. Result was 
```
Found 8 problems
python3.9dist(configobj) is needed by cloud-init-21.4-1.ph4.noarch
Testing transaction
Found 45 problems
/bin/python3 is needed by (installed) python3-chardet-3.0.4-2.ph4.noarch
Error(1525) : rpm transaction failed
```
From my point of view it seems there was a problem with python3.
Found similar answer on another issue. 

So i removed and re-installed python3-netiface.x86_64 and update packages one-by-one (start with minimal). Not working. I decided to uninstall python3 hoping it would resolve my problem.

I uninstalled it with `tdnf remove python3`.

When i tried to use `tdnf` after, every command was in error : `Error(1304) : Solv - I/O error`.

I saved the output of my console. I could send it to you if necessary.

**Comment by oliverkurth** [comment]
> I saved the output of my console. I could send it to you if necessary.

Yes, that would be helpful.

**Comment by ygbillet** [comment]
> > I saved the output of my console. I could send it to you if necessary.
> 
> Yes, that would be helpful.

By email or in this thread ?

**Comment by oliverkurth** [comment]
> By email or in this thread ?

You can send it to okurth at vmware dot com , if you don't want to send in this thread. You can also attach it as a file if it's too long.

**Comment by ygbillet** [comment]
Here it is [2021-12-02 tdnf error.txt](https://github.com/vmware/photon/files/7645647/2021-12-02.tdnf.error.txt).

I took the liberty to redact user and hostname.
