### ISSUE TITLE
kernel headers are missing

### ISSUE THREAD

**Issue by antwerplog** [vmware/photon#1263]
Installing bcc and bcc-tools using tdnf from vmware repos are not working.
Linux-headers are needed for several includes.
Can someone please explain on how to add the necessary kernel-headers ?
thanks

**Comment by antwerplog** [comment]
just adding that linux-api-headers doesnt solve the case
thanks in advance !

**Comment by YustasSwamp** [comment]
Hi @antwerplog 
Please check what version of the kernel you have running: `uname -r`
and then install same version of linux-devel or linux-esx-devel

**Comment by antwerplog** [comment]
#tdnf install linux-esx-devel-$(uname -rm)
Error(1011) : No matching packages
#tdnf install linux-esx-devel-$(uname -rm)
Error(1011) : No matching packages

**Comment by keerthanakalyan** [comment]
Hi @antwerplog ,

Find the installed kernel version using `uname -r` and install the version like the example below (without -esx at the end):
`tdnf install linux-esx-devel-4.19.97-7.ph3`

**Comment by antwerplog** [comment]
works great ! thank you
