### ISSUE TITLE
rsyslog logging does not work

### ISSUE THREAD

**Issue by 3rd3** [vmware/photon#1276]
### Describe the bug

I am trying to run rsyslog on VMware Photon OS 4.0 (2f5aad892), however logging does not seem to work.

### Reproduction steps

```bash
tdnf install -y rsyslog
systemctl start rsyslog
logger "Test"
# No changed file in the past 60 seconds
find /var/log -mmin 1
# Nothing appended here
tail -n 10 /var/log/messages
```

### Expected behavior

The logged messages should be written to some files in `/var/log`.

**Comment by tapakund** [comment]
@3rd3 kindly share ```/etc/rsyslog.conf```

**Comment by 3rd3** [comment]
@tapakund It is the default configuration that comes with the package.

**Comment by 3rd3** [comment]
The default config is missing a catch-all rule like `*.*;auth,authpriv,kern.none   /var/log/syslog`.
