### ISSUE TITLE
tdnf autoremove 

### ISSUE THREAD

**Issue by 3rd3** [vmware/photon#1288]
### Is your feature request related to a problem? Please describe.

When uninstalling packages the installed dependencies are not removed automatically.

### Describe the solution you'd like

It would be nice if `tdnf` would implement `autoremove`/`autoerase`.

**Comment by oliverkurth** [comment]
It's being worked in: https://github.com/vmware/tdnf/pull/283

**Comment by oliverkurth** [comment]
The feature is merged into the tdnf source, but still needs to be added to Photon.

**Comment by oliverkurth** [comment]
It's in Photon 4.0 now.
