### ISSUE TITLE
How to install qemu guest agent 

### ISSUE THREAD

**Issue by leganck** [vmware/photon#1289]
### Is your feature request related to a problem? Please describe.

I install photon os in Proxmox VE and I want to enable qemu guest agent

### Describe the solution you'd like

Install qemu guest agent using tdnf

**Comment by dcasota** [comment]
I'm not familiar with proxmox. Actually there is no qemu-guest-agent SPEC, indeed, but have you tried to make post-install? eg.
```
tdnf install -y wget tar ninja-build glib-devel pixman pixman-devel libgcrypt libgcrypt-devel build-essential
wget https://download.qemu.org/qemu-6.2.0.tar.xz
tar xvf qemu-6.2.0.tar.xz
cd qemu-6.2.0/
./configure
make install
```

**Comment by leganck** [comment]
> 

I'll try

**Comment by si458** [comment]
for others is they need it 
https://rpmfind.net/linux/RPM/opensuse/15.2/x86_64/qemu-guest-agent-4.2.0-lp152.8.1.x86_64.html
i was able to install this version and it autostarts and all works no problems
`tdnf install https://rpmfind.net/linux/opensuse/distribution/leap/15.2/repo/oss/x86_64/qemu-guest-agent-4.2.0-lp152.8.1.x86_64.rpm`

**Comment by snapshotleisure** [comment]
Just for info for others, I have figured out the build to make a photon os qemu guest agent, based off the qemu img spec from photon team.

https://github.com/snapshotleisure/photon-os-qemu-guest-agent

**Comment by bdruth** [comment]
Heads up for anyone else coming around here looking for something that works in early 2025 - 

```
rpm -ivh http://rpmfind.net/linux/almalinux/8.10/AppStream/x86_64/os/Packages/qemu-guest-agent-6.2.0-49.module_el8.10.0+3839+c94ce74b.x86_64.rpm --nodeps
```

this seems to work. I still needed to create the service as described in @snapshotleisure's repo link, and of course enable the guest agent support on the VM (it's disabled by default, at least on my proxmox install).

**Comment by stanthewizzard** [comment]
rpm -ivh http://rpmfind.net/linux/almalinux/8.10/AppStream/x86_64/os/Packages/qemu-guest-agent-6.2.0-49.module_el8.10.0+3839+c94ce74b.x86_64.rpm --nodeps

and 

```
cat > /etc/systemd/system/qemu-guest-agent.service << EOF
[Unit]
Description=QEMU Guest Agent
BindsTo=dev-virtio\x2dports-org.qemu.guest_agent.0.device
After=dev-virtio\x2dports-org.qemu.guest_agent.0.device

[Service]
ExecStart=-/usr/bin/qemu-ga
Restart=always
RestartSec=0

[Install]
WantedBy=multi-user.target
EOF
```

with

systemctl enable qemu-guest-agent
systemctl start qemu-guest-agent

failes with A dependency job for qemu-guest-agent.service failed. See 'journalctl -xe' for details.

Thanks for help

**Comment by oliverkurth** [comment]
It's not recommended to install RPMs from other distributions in Photon OS.

**Comment by snapshotleisure** [comment]
Yes, generally not recommended and hence why I came up build the script, I wonder if its possible for me to do a PR with my spec so they can include it in the repo... let me give it a try. Alternatively I use to have a ansible script that automates the build for me and chucks it in my private repo which I can then use to update my photonOS VM's. I'ved moved off photonOS for now, but I can try and dig up the script if anyone is interested in doing this via ansible

**Comment by stanthewizzard** [comment]
I'm leaving esxi for proxmox. Will be leaving photon for Debian after.
But for now, I'll use your tuto

**Comment by dcasota** [comment]
Leaving Linux for Windows would be leaving.
Well, actually Linux people love MCP J
