### ISSUE TITLE
Photon 4.0 on ESXi 6.7 sends incorrect hostname during DHCP

### ISSUE THREAD

**Issue by robpomeroy** [vmware/photon#1327]
### Describe the bug

I have a guest Photon OS 4.0 Rev2 VM, provisioned from OVA with virtual hardware v13 (UEFI Secure Boot), running on an ESXi 6.7 host. No matter what configuration I tweak, during DHCP configuration, Photon either sends no hostname, or the wrong hostname.

Hostname is configured as "**docker01**.ipa.pomeroy.me" (in `/etc/hostname`). My DHCP server (pfSense 2.6.0) receives the hostname "**photon-machine**.ipa.pomeroy.me".

I see that "photon-machine" is defined in `/var/lib/cloud/data/set-hostname`.  And `/var/run/result.json` shows:

```
{
 "v1": {
  "datasource": "DataSourceNone",
  "errors": []
 }
}
```

It is my desire to have Photon OS guests register their preferred hostname with DHCP, and through the DHCP server, DNS.

### Reproduction steps

1. Build VM from OVA on ESXi 6.7
2. Change hostname using `hostnamectl set-hostname docker01.ipa.pomeroy.me`
3. Add the following to `/etc/systemd/network/99-dhcp-en.network`:

```
[DHCP]
ClientIdentifier=mac
```

4. Add to `/etc/dhcp/dhclient.conf`:

```
send host-name = gethostname();
```

Reboot and observe new lease in DHCP server's logs, with incorrect hostname.

### Expected behavior

DHCP server should receive the desired hostname, rather than the cloud-init (?) default.

### Additional context

I have never used `cloud-init`, but my understanding is that I shouldn't need to edit `/var/lib/cloud/data/set-hostname`. In `/var/log/cloud-init.log`, I see:

```
2022-05-26 07:59:53,964 - DataSourceVMware.py[DEBUG]: Getting guestinfo value for key hostname
2022-05-26 07:59:53,964 - subp.py[DEBUG]: Running command ['/usr/bin/vmware-rpctool', 'info-get guestinfo.hostname'] with allowed return codes [0] (shell=False, capture=True)
2022-05-26 07:59:53,966 - DataSourceVMware.py[DEBUG]: No value found for key hostname
```

### Workaround

For now, I'm using DHCP reservations.

**Comment by dcasota** [comment]
Hi,
the following checks may help
- the vm on ESXi has automatic mac address generation or static one? were there mac address changes? 
- Guest OS set to VMware Photon OS (64-vit)? ( ref link https://communities.vmware.com/t5/Photon-OS-Discussions/Photon-DHCP-not-working-correctly-on-vSphere-6-0/td-p/1401904 )
- @ssahani worked on this issue but several years ago ( ref link https://github.com/systemd/systemd/issues/6612 )

**Comment by ssahani** [comment]
Please see https://www.freedesktop.org/software/systemd/man/systemd.network.html#SendHostname=

```
[DHCPv4]
ClientIdentifier=mac
SendHostname=yes
```

By default it's true. Can you capture the traffic to see what is being sent ```tshark -V -i eth0 udp port 67 or 68```. It should be in discoverer. DO

```
 sudo networkctl reconfigure eth0
```

to reconfigure the eth0
```
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether 00:0c:29:7f:be:0f brd ff:ff:ff:ff:ff:ff
    altname eno1
    altname enp11s0
    altname ens192
```

```

Dynamic Host Configuration Protocol (Discover)
    Message type: Boot Request (1)
    Hardware type: Ethernet (0x01)
    Hardware address length: 6
    Hops: 0
    Transaction ID: 0x398bd502
    Seconds elapsed: 1
    Bootp flags: 0x0000 (Unicast)
        0... .... .... .... = Broadcast flag: Unicast
        .000 0000 0000 0000 = Reserved flags: 0x0000
    Client IP address: 0.0.0.0
    Your (client) IP address: 0.0.0.0
    Next server IP address: 0.0.0.0
    Relay agent IP address: 0.0.0.0
    Client MAC address: VMware_7f:be:0f (00:0c:29:7f:be:0f)
    Client hardware address padding: 00000000000000000000
    Server host name not given
    Boot file name not given
    Magic cookie: DHCP
    Option: (53) DHCP Message Type (Discover)
        Length: 1
        DHCP: Discover (1)
    Option: (61) Client identifier
        Length: 19
        IAID: b6220feb
        DUID Type: assigned by vendor based on Enterprise number (2)
        Enterprise-number: Tom Gundersen (systemd) (43793)
        Identifier: c32e77f901a666c2
    Option: (55) Parameter Request List
        Length: 9
        Parameter Request List Item: (1) Subnet Mask
        Parameter Request List Item: (3) Router
        Parameter Request List Item: (6) Domain Name Server
        Parameter Request List Item: (12) Host Name
        Parameter Request List Item: (15) Domain Name
        Parameter Request List Item: (33) Static Route
        Parameter Request List Item: (42) Network Time Protocol Servers
        Parameter Request List Item: (120) SIP Servers
        Parameter Request List Item: (121) Classless Static Route
    Option: (57) Maximum DHCP Message Size
        Length: 2
        Maximum DHCP Message Size: 576
    Option: (12) Host Name
        Length: 4
        Host Name: Zeus <=================
    Option: (255) End
        Option End: 255
```

**Comment by robpomeroy** [comment]
> Hi, the following checks may help
> 
> * the vm on ESXi has automatic mac address generation or static one? were there mac address changes?
> * Guest OS set to VMware Photon OS (64-bit)? ( ref link https://communities.vmware.com/t5/Photon-OS-Discussions/Photon-DHCP-not-working-correctly-on-vSphere-6-0/td-p/1401904 )
> * @ssahani worked on a systemd clientidentifier=mac issue but several years ago ( ref link [systemd-networkd ignores ClientIdentifier=mac configuration systemd/systemd#6612](https://github.com/systemd/systemd/issues/6612) )

@dcasota:

* The VM generates a MAC on first boot and retains this MAC through its lifetime.
* That article is the reason I added `ClientIdentifier=mac` to my systemd-network config. I also clear the Machine ID before first boot (e.g. when cloning the VM). :+1:
* That seems to be a different issue (though possibly for similar reasons).

The issue here isn't that DHCP is failing in any way: it's that **the Photon OS machine is sending the wrong hostname**.

**Comment by robpomeroy** [comment]
@ssahani - I'm very willing to do a traffic capture. Just not quite sure how. I imagine that pfSense can do it - but I've never tried. Are you able to guide? I haven't yet tested booting the machine with the NIC disconnected, incidentally, so that might be an option.

I did already try adding:

```
[DHCPv4] 
SendHostname=yes
Hostname=docker01.ipa.pomeroy.me
```

I placed that in the `/etc/systemd/network/99-dhcp-en.network` and it was completely ignored (apparently). Adding the `ClientIdentifier=mac` to this same file made a difference to how DHCP registration behaved, so I don't understand why these settings are ineffective.

**Comment by robpomeroy** [comment]
PS @dcasota & @ssahani - thanks very much for your replies. I really appreciate the help.

**Comment by dcasota** [comment]
is hostname=fqdn supported? what happens with Hostname=docker01 ?

**Comment by robpomeroy** [comment]
> is hostname=fqdn supported? what happens with Hostname=docker01 ?

@dcasota Bingo! Yes, that correctly registers the hostname. And furthermore, that line (`Hostname=`) isn't required, if I change the system's hostname from docker01.ipa.pomeroy.me to docker01.

So it looks like my mistake was to include the FQDN when setting the system hostname. Embarrassing!

Note that with the hostname set as a bare hostname, no FQDN, there is no need to modify the systemd/networkd config or the dhclient config. Hosts register correctly.

Thanks again for your support with this. Sorry that it appears to have been my own fault!

**Comment by dcasota** [comment]
@ssahani spotted it immediately (see hostname Zeus <=====).
Learning Photon OS is learning a language. I’m often a Raj - it’s not bad. Could be worse! By Photon OS docs studies I‘ve started learning Linux. #Thankful #faulttolerance
