### ISSUE TITLE
Multiple disks partitioning 

### ISSUE THREAD

**Issue by khaaliid** [vmware/photon#1335]
### Is your feature request related to a problem? Please describe.

We have multiple types of servers in which we need to install the Photon-OS in an unattendant manner. These servers can have 1 or more disks. Is there a way to change the partitioning strategy based on how many disks we have in the server ?

### Describe the solution you'd like

If it is possible to keep the partitions and disk options in the kickstart file as optional and do the partition manually by the post-install script then proceed with the OS installation.

### Describe alternatives you've considered

We can do re-partitioning by a script which can be run after the first startup.

**Comment by jaankit** [comment]
yes, you can partition multiple disk by defining partition table in kickstart file. Ex: https://github.com/vmware/photon-os-installer/blob/52c657ed4c512b85a713b5e79c5de0dbff67b7fe/photon_installer/ks_config.txt#L168

Also you can explore 'preinstall' and 'preinstallscripts' feature in photon-os-installer which executes before creation of photon-chroot : https://github.com/vmware/photon-os-installer/blob/52c657ed4c512b85a713b5e79c5de0dbff67b7fe/photon_installer/ks_config.txt#L241

**Comment by YustasSwamp** [comment]
kickstart file does support multidisks partitioning and if you need additional logic it can be executed as preinstall script, see comment from Ankit above.
