### ISSUE TITLE
cant access https://github.com/vmware/photon/wiki/Downloading-Photon-OS

### ISSUE THREAD

**Issue by roozbehk** [vmware/photon#1342]
### Describe the bug

I can not download images, https://github.com/vmware/photon/wiki/Downloading-Photon-OS is not accessible. 

_No response_

**Comment by dcasota** [comment]
The download backend e.g. https://packages.vmware.com/photon/4.0/Rev2 works though.

**Comment by tapakund** [comment]
Thanks for reporting, we are checking on the same.

**Comment by dcasota** [comment]
the website is back. Don't move, someone can confirm integrity checks sha...?

**Comment by tapakund** [comment]
We will confirm on the integrity soon.

Just for info: Yesterday I opened a ticket for this issue and github has deployed a fix already. Hope this wont occur again.

**Comment by tapakund** [comment]
This seems to be good. Wiki wasn't updated post March 03, 2021 and security advisories are up to date. Hence closing this issue.
