### ISSUE TITLE
Query: Is Photon OS primarily for container host OS or can be used as image for running containers? 

### ISSUE THREAD

**Issue by RamWebDev** [vmware/photon#1345]
### Describe the bug

Query: Is Photon OS primarily designed and tuned to work for container "host" OS (i.e. OS to be used for Nodes in EKS or ESX Server OS etc) or can be used as an image for running docker containers?
As the tiny dnf or tdnf has very limited packages in its repo and how would one install several packages that would be required for container application development?

I was trying to use Photon as a base image for my application container. And my application would need me to have a puppeteer running in my container and it has below as pre-requites list of packages that are to be installed in the container for puppeteer to work

        libpangocairo-1.0-0 \
        libx11-xcb1 \
        libxcomposite1 \
        libxcursor1 \
        libxdamage1 \
        libxi6 \
        libxtst6 \
        libnss3 \
        libcups2 \
        libxss1 \
        libxrandr2 \
        libgconf-2-4 \
        libasound2 \
        libatk1.0-0 \
        libgtk-3-0 \
        libxcb-dri3-0 \
        libdrm2 \
        libgbm1

And these packages are ### not available to be installed via tdnf. However, available with other popular package managers such as apt-get, apt, etc

================================
**Below is the Docker file:**

FROM photon:4.0

RUN tdnf install -y curl \
    && tdnf install -y nodejs \
    && tdnf install -y shadow \
    && tdnf install -y pmd-cli
    
 # Other application packages like a puppeteer, and phantom are required by the application for several of its usecases. 

================================
  

### Reproduction steps

```bash
1.
2.
3.
...
```

### Expected behavior

Suggest me whether to go ahead and use Photon as base container image for my application containers. If yes, then how to install below list of packages in Photon container?

        libpangocairo-1.0-0 \
        libx11-xcb1 \
        libxcomposite1 \
        libxcursor1 \
        libxdamage1 \
        libxi6 \
        libxtst6 \
        libnss3 \
        libcups2 \
        libxss1 \
        libxrandr2 \
        libgconf-2-4 \
        libasound2 \
        libatk1.0-0 \
        libgtk-3-0 \
        libxcb-dri3-0 \
        libdrm2 \
        libgbm1

If Photon OS is primary designed and tuned as a host container OS, then I will continue to use Photon OS for EKS Node OS and for base container image, I will use other flavours of Linux such as Ubuntu or others.

**Comment by dcasota** [comment]
Photon OS does not provide a host X11 environment. There were some attempts and you might find some of the packages in the [Vivace repo](https://packages.vmware.com/photon/vivace/vivace_4.0_x86_64/x86_64/).

That said, the tremendous NVidia progress in AI kicks in here. There is so much innovation, and, they use most of the listed packages as well. Tao toolkit, deepstream and Triton inference server - NVidia customizes their own images and provide own security scanning information. If you have seen those docker containers - it's nuts size, 7GB++ for one container (!)

Nevertheless, to come back, for those GPU/UI scenarios actually Photon OS does not include an "essential" package, and yes, in my personal opinion such an essential package would be nice. Good catch.

**Comment by YustasSwamp** [comment]
Photon OS is designed to be container host or appliances base. Despite we have container base image in dockerhub, we do not provide thousands packages to be general purpose container base OS.
