### ISSUE TITLE
Request for 'open-vm-tools' package update 

### ISSUE THREAD

**Issue by hgkang-openbase** [vmware/photon#1352]
### Describe the bug

Photon's package repository should provide latest(12.1.0) open-vm-tools package, which is currently providing 12.0.5.
VMSA-2022-0024 is disclosed on 2022-08-23 and open-vm-tools 12.1.0 has been released. https://github.com/vmware/open-vm-tools/releases/tag/stable-12.1.0

### Reproduction steps

```bash
1. tdnf list --installed open-vm-tools
open-vm-tools.x86_64                                              12.0.5-2.ph4                             @System

2. tdnf install --upgrade open-vm-tools
Package open-vm-tools is already installed.
Nothing to do.
```

### Expected behavior

An update for open-vm-tools 12.1.0 should be available.

**Comment by sshedi** [comment]
Under review, changes will be merged soon.

**Comment by shivania2** [comment]
Upgraded Open-vm-tools  to 12.1.0

```
root@photon-dd15d8b0b23droot [ ~ ]# tdnf list open-vm-tools-12.1.0-1.ph4 
open-vm-tools.x86_64                                                                                                                  12.1.0-1.ph4                                                                       photon-updates
```
