### ISSUE TITLE
net-snmp flood of error message about missing /proc/net/if_inet6 if IPv6 is disabled

### ISSUE THREAD

**Issue by ufoonline** [vmware/photon#1356]
### Describe the bug

Hello,

net-snmp flood messages file with 'ipaddress_linux: could not open /proc/net/if_inet6: No such file or directory' if ipv6 is disabled on the system.

Package: net-snmp-5.8-8.ph4.x86_64

If you have disabled IPv6 (set ipv6.disable=1 in /boot/systemd.cfg) net-snmpd () will write a lot 

### Reproduction steps

1. add 'ipv6.disable=1' in /boot/systemd.cfg
2. reboot
3. tdnf install net-snmp
4. systemctl start snmpd
5. systemctl status snmpd

### Expected behavior

No error messages

**Comment by ssahani** [comment]
Yes https://sourceforge.net/p/net-snmp/bugs/2903. We need to fix it

**Comment by ssahani** [comment]
Fixed by https://github.com/vmware/photon/commit/1a85b73b5107db5cd3bb83880dda32242e122884

**Comment by otheus** [comment]
The priority should be WARN or NOTICE not an ERR. 
Or there shuld be a way to disable from it even being executed. (I couldn't find a suitable option)
