### ISSUE TITLE
changed root password after a fresh Ph4.0U2 installation expires after a day

### ISSUE THREAD

**Issue by dcasota** [vmware/photon#1359]
### Describe the bug

changed root password after a fresh photon-ova_uefi-4.0-c001795b80.ova installation expires after a day

### Reproduction steps

1. Deploy https://packages.vmware.com/photon/4.0/Rev2/ova/photon-ova_uefi-4.0-c001795b80.ova on ESXi 7.0U3g
2. login and ```tdnf update -y```. Actual release 5.10.142-1.ph4-esx .
4. reboot, login and change password
5. shutdown
6. After ~ a day, the login does not work anymore.

Provisioning: October 4th
Login issue: October 6th
journalctl extract from October 4th
![image](https://user-images.githubusercontent.com/14890243/194272546-9c25b8ed-6403-4b7c-a2cf-ac26079b3af5.png)

### Expected behavior

The login workflow detects that the default root password has to be changed. The default of root password expiration time of a day however is somewhat short. A longer expiration time makes more sense.

### Additional context

The process of resetting the root password, and with the reproduction steps from above, there is no pam_tally2 command neither in /sbin nor somewhere else (?)

**Comment by sshedi** [comment]
You can use `chage -l root` to know more on password expiration details and same command can be used to configure password expiration configs. To reset root password, you need to get into console or do ssh login and enter password manually after expiration.

And pam_tally2 is not there in Ph4, latest linux-pam uses `faillock` for managing account locking and other tasks.

**Comment by dcasota** [comment]
Started the vm, logged-in successfully, no 'changed password expiration time after a day' issue. Fantastic. close this.
