### ISSUE TITLE
Cannot update package ntp

### ISSUE THREAD

**Issue by dark2phoenix** [vmware/photon#1368]
### Describe the bug

When I try to update package ntp it fails:

```
tdnf install ntp
Refreshing metadata for: 'VMware Photon Extras 4.0 (x86_64)'
Refreshing metadata for: 'VMware Photon Linux 4.0 (x86_64) Updates'
Refreshing metadata for: 'VMware Photon Linux 4.0 (x86_64)'
photon-release                          342894 100%
Installing:
libevent                                                x86_64                      2.1.8-3.ph4                          photon-updates                  766.02k 784405
ntp                                                     x86_64                      4.2.8p15-6.ph4                       photon-updates                   6.42M 6731215

Total installed size:   7.17M 7515620
Is this ok [y/N]: y

Downloading:
libevent                                222109 100%
Error: 404 when downloading https://packages.vmware.com/photon/4.0/photon_updates_4.0_x86_64/x86_64/ntp-4.2.8p15-6.ph4.x86_64.rpm
. Please check repo url.
Error processing package: x86_64/ntp-4.2.8p15-6.ph4.x86_64.rpm
Error(1622) : Invalid argument
```

### Reproduction steps

1. tdnf install ntp
2. select yes

### Expected behavior

tdnf points to the package that actually downloadable which is [ntp-4.2.8p15-7.ph4.x86_64.rpm](https://packages.vmware.com/photon/4.0/photon_updates_4.0_x86_64/x86_64/ntp-4.2.8p15-7.ph4.x86_64.rpm).  The index appears to be pointing to an older version ntp-4.2.8.p15-6,

### Additional context

I was able to physically download the rpm and install it locally, but the index should really reflect the file that is out there.

**Comment by oliverkurth** [comment]
Did you try `tdnf makecache` ? It looks like your metadata are stale.

**Comment by Vasavisirnapalli** [comment]
@tapakund @ntsbtz

**Comment by dark2phoenix** [comment]
I did a `tdnf makecache` but that didn't work.  So I just wiped out all the tdnf config files, did a tdnf makecache and now it works fine.  Thank you or the tip!
