### ISSUE TITLE
Photon OS 2.0 - fix for netmgr

### ISSUE THREAD

**Issue by dcasota** [vmware/photon#1382]
### Describe the bug

In https://communities.vmware.com/t5/Photon-OS-Discussions/Can-t-add-static-routes-with-netmgr/m-p/2944275 a community user complained about a netmgr issue. In Photon OS 2.0, `netmgr ip_route --get --interface eth0` stops with "Error: value not found".

### Reproduction steps

See notes.txt in https://communities.vmware.com/t5/Photon-OS-Discussions/Can-t-add-static-routes-with-netmgr/m-p/2944001/highlight/true#M365

### Expected behavior

ipv4 route successfully added

### Additional context

Is https://github.com/vmware/photonos-netmgr/blob/master/cli/netmgrcli.c the latest source?

**Comment by sshedi** [comment]
Photon OS 2.0 is almost EOL (Jan 9th 2023). So we won't be fixing it.

Probably fix: https://github.com/vmware/photon/blob/4.0/SPECS/netmgmt/fix-section-name-parsing-logic.patch

It's in Ph4.
