### ISSUE TITLE
Photon 5 Beta install on workstation

### ISSUE THREAD

**Issue by suezzelur** [vmware/photon#1393]
### Describe the bug

Installation fails trying to find the cdrom blockdevice with the 5.0 beta ISOs. This is on workstation 17 on Windows. Is this a known issue?
![image](https://user-images.githubusercontent.com/12656953/221073037-23898d71-1bf1-468b-bbf2-cb0aa5a4a8c7.png)

### Reproduction steps

1. Create a new VM from ISO in workstation on Windows

### Expected behavior

Installation should be able to find the right block device

**Comment by vbrahmajosyula1** [comment]
The failure is because of IDE type CDROM. Latest linux kernels have deprecated/removed the driver. For the installer to work, please switch to SATA type CDROM in Workstation. We have an open ticket to exit gracefully in this case.
