### ISSUE TITLE
Include default root password for OVA

### ISSUE THREAD

**Issue by scott-weeden** [vmware/photon#1402]
### Describe the bug

I can't find anywhere in the documentation what the default password/login for the OVA file is.

### Reproduction steps

1. Install OVA with defaults
2.  Power up VM
3.  Receive Login prompt for undocumented root/password:
...

### Expected behavior

Expected root password / login on download page

### Additional context

I download Photon 5

**Comment by scott-weeden** [comment]
Nevermind, I found some documentation on VMWare.  In case anyone else is looking for it, press "e" at boot screen and add boot params
    init=/bin/bash
then set the root password using "passwd"

**Comment by tapakund** [comment]
The default login credentials of Photon OS 5.0 OVA is same as the previous photon releases. This is documented here: https://vmware.github.io/photon/docs/installation-guide/run-photon-on-vsphere/importing-photon-os-from-ova-on-vsphere/

Thanks!
