### ISSUE TITLE
tdnf updates on Photon OS 4 aarch64 vm finish with storage exceptions (WRITE FPDMA queued)

### ISSUE THREAD

**Issue by dcasota** [vmware/photon#1410]
### Describe the bug

On ESXi on Arm on usb storage, updating a Photon OS 4 aarch64 virtual machine (5.10.152-1.ph4) to latest (`tdnf update -y`) shows storage exceptions, systematicly only right after initramfs+initrd events.

Started vm
![image](https://user-images.githubusercontent.com/14890243/226107939-d3955545-de15-43d9-850b-b816f1119d81.png)

Exceptions during updates
![image](https://user-images.githubusercontent.com/14890243/226107976-5ff5781a-36b1-41d6-ab72-d268986756f4.png)
![image](https://user-images.githubusercontent.com/14890243/226107985-692d76c4-be9e-4bba-9feb-541bfc4740e4.png)
![image](https://user-images.githubusercontent.com/14890243/226107999-ab2d1192-ecc7-472a-8bef-52dc4a5f2a50.png)

### Reproduction steps

1. ESXi on Arm (updated from 1.11) 1.12 on RPi4b. On its usb3 ports, medias for ESXi + vmfs datastore 
2. Thickprovisioned vm from Photon OS 4 rev2 aarch64 iso
3. `tdnf update -y`

### Expected behavior

distinction:
- On ESXi on Arm (+Photon OS): Warn user about deprecated, unsupported or defect hardware component.
- On Photon OS: Sort of integrity check of already installed packages

### Additional context

Linked to esxi on arm https://flings.vmware.com/esxi-arm-edition/comments/21707#comment_21707 as well.

**Comment by sshedi** [comment]
Seems like a  disk issue in your VM. Try on a different machine.
