### ISSUE TITLE
ability to lock the version of a packet (exclude option or versionlock plugin)

### ISSUE THREAD

**Issue by bvivi57** [vmware/photon#1413]
### Is your feature request related to a problem? Please describe.

Hi
For security reasons, I would like to prevent the update of some packets when performing an update operation.
The need is to lock the version of some packages.

Maybe I searched wrong but I also tried the exclude option in the configuration file or in the command line, but the package is always updated.

### Describe the solution you'd like

For exemple : https://access.redhat.com/solutions/98873 or https://www.tecmint.com/exclude-package-updates-yum-dnf-command/ or https://www.hiroom2.com/2016/07/07/fedora-24-exclude-package-from-update/

**Comment by sshedi** [comment]
This is in progress: https://github.com/vmware/tdnf/pull/413

cc: @oliverkurth

**Comment by bvivi57** [comment]
Hi
Thanks !

**Comment by oliverkurth** [comment]
@bvivi57 , the feature has been in `tdnf` for some time, see https://github.com/vmware/tdnf/wiki/Configuration-Options#package-locks. Just do:

```
mkdir -p /etc/tdnf/locks.d
echo pkgname > /etc/tdnf/locks.d/pkgname.conf
```

@sshedi , https://github.com/vmware/tdnf/pull/413 is different. The "protected" feature would block a package from being removed but not from being upgraded.
