### ISSUE TITLE
How to run postgres on photon?

### ISSUE THREAD

**Issue by martha889** [vmware/photon#1419]
### Is your feature request related to a problem? Please describe.

I'm not able to locate the data directory for postgres and seeing this:

```
2023-04-03 02:20:11 UTC FATAL:  "/var/lib/postgresql/14/main" is not a valid data directory
2023-04-03 02:20:11 UTC DETAIL:  File "/var/lib/postgresql/14/main/PG_VERSION" is missing.
```

### Describe the solution you'd like

I'd like to make postgres run

**Comment by Vasavisirnapalli** [comment]
Could you please let us know the Photon version you are using @tapakund

**Comment by martha889** [comment]
Hi @Vasavisirnapalli Photon version is 4.0 and postgres version is 14
