### ISSUE TITLE
On VMware Workstation 17, vm provisioning with Ph5.0 iso fails

### ISSUE THREAD

**Issue by dcasota** [vmware/photon#1459]
### Describe the bug

Hi,
Please include in the 5.0 Release Notes an entry explicitly about to modify the default vm settings
- in CD/DVD Advanced Settings, use the Virtual Device Node SCSI, and not IDE anymore.
- use 2GB RAM. Photon OS starts with 1 GB RAM, but not with default 768MB RAM.

For example, the provisioning of a vm with the photon-minimal-5.0-dde71ec57.x86_64.iso  fails with
![image](https://user-images.githubusercontent.com/14890243/234576363-929e5172-c21c-404b-b59f-dc42c60d6e87.png)

### Reproduction steps

1. Workstation 17 Pro 17.0.2 build-21581411
2. **Default vm settings**
3. modify vm hardware to use 2GB RAM and 8 GB disk, EFI boot, encryption and vTPM
4. Boot from attached iso

### Expected behavior

Use vm default settings, again.

**Comment by tapakund** [comment]
Thanks @dcasota , closing this ticket.
