### ISSUE TITLE
ssh custom port not save after reboot

### ISSUE THREAD

**Issue by ssv1907** [vmware/photon#1477]
### Describe the bug

ssh custom port not save after reboot - photon-hw15-5.0-dde71ec57.x86_64.ova

### Reproduction steps

1. edit /etc/ssh/sshd_config (change port to 2211)
2. systemctl restart sshd
3. connect ssh to port 2211 is OK
4. reboot server
5. connect ssh to port 2211 fail, but to 22 is OK
...

### Expected behavior

ssh custom port not save after reboot

**Comment by sshedi** [comment]
Hi, which service is active post reboot? sshd.socket or sshd.service? Check using:
```
systemctl status sshd
systemctl status sshd.socket
```
