### ISSUE TITLE
Photon OS 4.0 to 5.0 Upgrade - How to?

### ISSUE THREAD

**Issue by Maximexe** [vmware/photon#1490]
### Describe the bug

Hello Team!

This may be a simple question and I apologize in advance. How do I update my Photon 4.0 to Photon 5.0 without losing any data? I saw there was a script in the Photon 3.0 wiki but I didnt want to run that without confirming it would work.

Thank you,
Maximexe

### Reproduction steps

1.
2.
3.
...

### Expected behavior

To update 4.0 to 5.0 without any data loss

**Comment by dcasota** [comment]
Hi,

see https://vmware.github.io/photon/docs-v5/installation-guide/upgrading-to-photon-os-4/

There are a few details (virtual hardware, uefi, containers, x86_64/arm64, flavor), but the upgrade itself runs smoothly.

Afaik it is in most parts the same script content as it was in Photon OS 2.0.

Yes, the wiki is a little bit outdated, but the docs content helps.

Hope this user voice helps.
-Daniel

**Comment by Maximexe** [comment]
This is amazing - thank you Daniel. This link may want to be put on the ReadMe for easy access :).

**Comment by oliverkurth** [comment]
Closing this, questions answered. Thank you @dcasota !
