### ISSUE TITLE
After the recent source code change why i am getting the following error while building photon:-                                       json_pp -t null < installer/package_list.json >/dev/null 2>&1 || { echo "Invalid installer/package_list.json. Aborting" >&2; exit 1; } 

### ISSUE THREAD

**Issue by Andrew219** [vmware/photon#151]

**Comment by toliaqat** [comment]
@Andrew219 please ignore this. Actually the make file is just running this command which has this "invalid ..." message inside, but actually the command was successful and didn't stop the build process. You can ignore this until it breaks your build.

**Comment by Andrew219** [comment]
Thanks toliaqat i trust you.
