### ISSUE TITLE
photon os microcode ?

### ISSUE THREAD

**Issue by hel1o-wor1d** [vmware/photon#1510]
### Is your feature request related to a problem? Please describe.

Does photon os need to update microcode ?
Alpine linux has packages to update microcode.

### Describe the solution you'd like

Does photon os need to update microcode ?
Alpine linux has packages to update microcode.

### Describe alternatives you've considered

Does photon os need to update microcode ?
Alpine linux has packages to update microcode.

### Additional context

Does photon os need to update microcode ?
Alpine linux has packages to update microcode.

**Comment by dcasota** [comment]
@hel1o-wor1d 再会。很高兴欢迎您来到这里。我已阅读你的问题。您期望 Photon OS 像 Alpine Linux 一样定期发布固件更新。正如他们正确指出的那样，开源 Photon OS 的情况并非如此。目前的 Linux 固件是今年 2 月份的。您可以在 https://github.com/vmware/photon/blob/5.0/SPECS/linux-firmware/linux-firmware.spec 中找到规范文件。支持使用您自己的存储库编译您自己的 Photon OS 安装，详情请参见 https://vmware.github.io/photon/docs-v5/installation-guide/building-images/。我希望答案对你有用。

**Comment by YustasSwamp** [comment]
@hel1o-wor1d , Photon OS is a Linux distro to run in clouds as a guest VM. We still do not officially support running Photon OS on a bare metal. This is a host OS responsibility to update CPUs microcode or BIOS firmware. Guest OS does not have these permissions, so we do not have this feature/package in Photon OS.

**Comment by YustasSwamp** [comment]
Close it as "Won't fix"/"Won't implement".
Will come back to this request again if/when we go with official bare metal support.
