### ISSUE TITLE
Photon's yum repos are not compatibale with RHELs's repo.

### ISSUE THREAD

**Issue by hel1o-wor1d** [vmware/photon#1511]
### Is your feature request related to a problem? Please describe.

Photon's yum repos are not compatibale with RHELs's repo.

### Describe the solution you'd like

Photon's yum repos are not compatibale with RHELs's repo.

### Describe alternatives you've considered

Photon's yum repos are not compatibale with RHELs's repo.

### Additional context

Photon's yum repos are not compatibale with RHELs's repo.

**Comment by sshedi** [comment]
Nowhere we have mentioned that we will support other distro's repos and unless a distro is a fork of the RHEL, RHEL's repos won't be compatible. Even in case of forked distros, it's not guaranteed to work.

Please close this issue as user error.
