### ISSUE TITLE
Can we do the same thing of 'tdnf upgrade --security -y' without internet access?

### ISSUE THREAD

**Issue by pcgeng** [vmware/photon#1512]
### Is your feature request related to a problem? Please describe.

In an air-gapped environment with Photon OS installed, we want to upgrade packages with security offline, just like 'tdnf upgrade --security -y', however this option from my understanding requires internet access. Can we?

### Describe the solution you'd like

I'm not sure whether we have the solution of the similar command like '--offline' here.

**Comment by pcgeng** [comment]
If we cannot, how can we do the package upgrade with security offline manually?

**Comment by sshedi** [comment]
Method 1. Download the repo using `reposync` facility, copy the downloaded files to your vm, setup a local repo and perform 
upgrade.

Method 2. Do `tdnf update` in a mirror machine with net connectivity, get the list of rpms that are updated, add ` keepcache=1` in /etc/tdnf/tdnf.conf, then do `tdnf update -y` updated rpms will be downloaded to tdnf cache dir and then same as method 1 above.

Method 3: Build an iso after rebasing your photon source code repo, copy the iso to your offline vm, mount the iso and updated packages from the iso repo.

**Comment by pcgeng** [comment]
@sshedi Thanks for your quick reply, do we have any documentation or KB for doing Method 1 or 2 or 3 with details? We need to provide it to our customer for reference.

**Comment by pcgeng** [comment]
@sshedi Do you team have any document or KB for the detailed steps of Method 1/2/3?

**Comment by oliverkurth** [comment]
I am afraid we don't have extensive documentation on any of that. But you can find documentation about `tdnf` here: https://github.com/vmware/tdnf/wiki . Specifically for `reoposync` : https://github.com/vmware/tdnf/wiki/Commands#reoposync

**Comment by pcgeng** [comment]
I think for customers with Federal and high security requirements in an air-gap environment, these wikis are not enough for how to perform the Method 1/2/3 offline with examples...

**Comment by pcgeng** [comment]
@sshedi @oliverkurth For method 1, how do we know the packages we need to upgrade for security and get the downloaded files from Photon? How can we setup a local repo?

**Comment by sshedi** [comment]
Get security updates list using:

Check this link for info on security updates: (same applies for tdnf)
https://www.thegeekdiary.com/how-to-list-or-install-only-security-updates-with-dnf-in-centos-rhel-8/

And for setting up local repo:
https://vmware.github.io/photon/assets/files/html/3.0/photon_admin/adding-a-new-repository.html

**Comment by pcgeng** [comment]
@sshedi thank you for providing the details, I'm trying `tdnf reposync` to download the repo, but it spent much time to complete, do you know how long it will take us to complete it and how much disk space it will occupy？

**Comment by sshedi** [comment]
There is no definite answer for the first question. It depends on your network quality.

For the second part, an entire repo (with only most recent RPMs) can take upto 4GB disk space in Ph4.

**Comment by oliverkurth** [comment]
I think questioned are addressed, closing this issue. Feel free to reopen if that is not the case.
