### ISSUE TITLE
nfs 4.1 mount stops working after linux-esx-6.1.53-8.ph5

### ISSUE THREAD

**Issue by HansKonings** [vmware/photon#1515]
### Describe the bug

After updating kernel to linux-esx-6.1.56-1.ph5 from linux-esx-6.1.53-8.ph5

mount nfs gives error:
mount.nfs: trying text-based options 'vers=4,minorversion=1,addr=192.168.80.10,clientaddr=192.168.80.132'
mount.nfs: mount(2): Protocol not supported

Tested up to kernel 6.1.56-8.ph5, failure still present.

### Reproduction steps

1. create nfs 4.1 server
2. install nfs-utils on client and mount from client with kernel linux-esx-6.1.53-8.ph5, mount success
3. yum install linux-esx-6.1.56-1.ph5
4. reboot, mount fails
...

### Expected behavior

Mount nfs 4.1 works on every kernel version

### Additional context

nfs v3 works fine
Using vsan file services for nfs server

**Comment by kashwindayan** [comment]
Hi @HansKonings ,
Tried reproducing the issue locally. But I see the mount is happening properly for the version  you mentioned.

root@photon-nfs-client [ ~ ]# mount | grep nfs_backup
10.102.83.12:/ on /root/nfs_backup type nfs4 (rw,relatime,vers=4.2,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=10.205.71.244,local_lock=none,addr=10.102.83.12)
root@photon-nfs-client [ ~ ]# uname -a
Linux photon-nfs-client 6.1.53-8.ph5-esx #1-photon SMP Fri Oct  6 03:03:51 UTC 2023 x86_64 GNU/Linux
root@photon-nfs-client [ ~ ]# tdnf install -y linux-esx-6.1.56-1.ph5

Upgrading:
linux-esx                     x86_64                 6.1.56-1.ph5                  photon-updates          20.81M                16.48M

.
.
.

root@photon-nfs-client [ ~ ]# reboot

------------------------------------------------------------------------
root@photon-nfs-client [ ~ ]# ls ~/nfs_backup/
root@photon-nfs-client [ ~ ]#  mount -v 10.102.83.12:/  ~/nfs_backup/
mount.nfs: timeout set for Wed Nov  1 00:16:23 2023
mount.nfs: trying text-based options 'vers=4.2,addr=10.102.83.12,clientaddr=10.205.71.244'
root@photon-nfs-client [ ~ ]# ls ~/nfs_backup/
.
.
.
.
root@photon-nfs-client [ ~ ]# uname -a
Linux photon-nfs-client 6.1.56-1.ph5-esx #1-photon SMP Tue Oct 10 03:03:13 UTC 2023 x86_64 GNU/Linux

- Can you please check if your rpc.gssd running?
- Can you paste ps -aux | grep rpc output from your client/server ?

**Comment by HansKonings** [comment]
Thanks kashwindayan

I have setup a nfs server on rhel8 to compare and this works:
192.168.80.101:/tmp/nfs on /mnt/tmp type nfs4 (rw,relatime,vers=4.1,rsize=524288,wsize=524288,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=192.168.80.132,local_lock=none,addr=192.168.80.101)

So issue is specifically with vsan file service nfs 4.1 as the server.

**Comment by jagnyadattat** [comment]
Please try upgrading photon OS to Photon5 kernel >= 6.1.62-3.ph5-esx
The protocol not supported issue reported above is not related to vSAN file services.

**Comment by HansKonings** [comment]
Hi Jagnyadattat,

Indeed it is fixed in 6.1.62-3.ph5-esx.
