### ISSUE TITLE
Documentation is incorrect, the operating mode of the DVD virtual hardware is important during installation

### ISSUE THREAD

**Issue by Randark-JMT** [vmware/photon#1524]
### Describe the bug

If you follow the installation instructions in the [Installing the ISO Image for Photon OS](https://vmware.github.io/photon/docs-v5/installation-guide/run-photon-on-workstation/installing-photon-os-from-iso-on-workstation/) for Vmware Workstation 17, you will not be able to complete the installation because the default connection mode of the DVD device given by Vmware Workstation is IDE mode, which will cause the Installer to fail to start.

![图片](https://github.com/vmware/photon/assets/56223739/db078869-f0ae-41e4-b07f-c97cded4fb16)

### Reproduction steps

1. Follow the installation steps according to the official documentation
2. trigger issue

### Expected behavior

Photon OS Install should start normally

### Additional context

Based on Vmware Workstation 17 Pro
Version: 17.0.0 build-20800274

**Comment by dcasota** [comment]
Hi @Vasavisirnapalli @YustasSwamp ,
would it be okay for the team, if I contribute to the docs Ph3.0-5.0
by pull requests e.g. page-by-page separated from https://github.com/vmware/photon/pull/1478 (only the green=verified files) ? 
I remember four years ago when I started as fresh Linux and Photon OS beginner. I was happy with the progress because the docs were in good shape. To rise the quality of docs continuously definitely is a big plus. Thanks for an answer in advance.

**Comment by dcasota** [comment]
@Randark-JMT 再会。我亲切地向你打招呼。请包涵。描述的问题应该参考https://vmware.github.io/photon/docs-v5/troubleshooting-guide/photon-installation-issue/进行维护，但是有几个声音认为在安装中会更好指导放置适当的告示。
如果 Photon OS 团队允许，我会提出一个应该接近您想要的建议。

**Comment by oliverkurth** [comment]
I think this is actually an issue with WS 17 because when you select "Photon OS" as the OS it should set the bus type to SATA. Let me raise that issue with them.

**Comment by oliverkurth** [comment]
Someone from the WS team asked for the log file `vmware.log`. Should be in the same folder as the other VM files. Can you please attach that?

**Comment by oliverkurth** [comment]
No need for the log file - I was told that this is already be fixed in WS 17.5.

Fee free to reopen if the issue persists with WS 17.5.

**Comment by Randark-JMT** [comment]
Cool! It was indeed a Vmware Workstation version issue, after I upgraded to 17.5.0 build-22583795, the installation process was problem-free, thanks a lot to those of you who offered help!

**Comment by YustasSwamp** [comment]
> Hi @Vasavisirnapalli @YustasSwamp , would it be okay for the team, if I contribute to the docs Ph3.0-5.0 by pull requests e.g. page-by-page separated from #1478 (only the green=verified files) ? I remember four years ago when I started as fresh Linux and Photon OS beginner. I was happy with the progress because the docs were in good shape. To rise the quality of docs continuously definitely is a big plus. Thanks for an answer in advance.

@dcasota contributions are always welcome, especially from the long time users like you! Thanks.
