### ISSUE TITLE
Fixing issues reported by tdnf check

### ISSUE THREAD

**Issue by mwoodpatrick** [vmware/photon#1525]
### Describe the bug

Is there a PhotonOS discussion forum somewhere that I can join?

I have the minimal set of packages installed on Photon OS V 5.0 (based on installing photon-minimal-5.0-dde71ec57.x86_64.iso) and after boot running:

tdnf update

but when running:

`sudo tdnf check`

I get:

```
1. package mysql-devel-8.0.35-2.ph5.x86_64 requires mysql = 8.0.35-2.ph5, but none of the providers can be installed
2. package ntpsec-1.2.2-2.ph5.x86_64 conflicts with ntp provided by ntp-4.2.8p17-1.ph5.x86_64
3. package openresty-1.21.4.1-9.ph5.x86_64 conflicts with nginx provided by nginx-1.25.2-2.ph5.x86_64
4. package mariadb-10.9.4-6.ph5.x86_64 conflicts with mysql provided by mysql-8.0.35-2.ph5.x86_64
5. package libsoup-doc-2.72.0-8.ph5.x86_64 requires libsoup = 2.72.0-8.ph5, but none of the providers can be installed
6. package mkpasswd-5.5.15-1.ph5.x86_64 conflicts with expect provided by expect-5.45.4-2.ph5.x86_64
7. package confd-3.26.1-6.ph5.x86_64 conflicts with calico-confd <= 0.16.0-20 provided by calico-confd-0.16.0-11.ph5.x86_64
8. package byacc-2.0.20221106-1.ph5.x86_64 conflicts with bison provided by bison-3.8.2-3.ph5.x86_64
Found 8 problem(s) while resolving
Error(1301) : Solv general runtime error
```
Does anyone know why this is or how best to fix?

### Reproduction steps

1. Boot PhotonOS using photon-minimal-5.0-dde71ec57.x86_64.iso
2. Run tdnf update
3. Run tdnf check
...

### Expected behavior

No package issues

### Additional context

I'm running PhotonOS on WSL-2 using QEMU on Debian distro:

```
qemu-system-x86_64 -name photon-debug --enable-kvm -drive
id=disk,file=photon-5.0-debug.qcow2,if=none -drive id=cdrom,file=photon-minimal-5.0-dde71ec57.x86_64.iso,media=cdrom,if=none,read-only=on -device ahci,id=ahci -device ide-hd,drive=disk,bus=ahci.0 -device ide-cd,drive=cdrom,bus=ahci.1 -m 4096 -net user,hostfwd=tcp::10022-:22 -net nic -virtfs local,path=/mnt/wsl,mount_tag=wsl,security_model=passthrough,id=wsl
```

**Comment by dcasota** [comment]
This packages conflict information is similar to #1385, see part-issue G), and https://github.com/vmware/photon/issues/1417#issuecomment-1550902949. At that time those few packages conflicts have been accepted for the win of a new major release in time.
There were a few tdnf check informations about packages conflicts in previous releases too, e.g. Ph4.0 starts with 28 conflicts. After a `tdnf update tdnf` there still are 17 conflicts.
From an outsider view, @oliverkurth and his team do a great job with respect of the limited resources they have been approved for the open-source Photon OS.

**Comment by oliverkurth** [comment]
There is not an issue in your VM. `tdnf check` merely shows what error you would get when trying to install *all* packages available in enabled repositories. There are many packages, some of them conflict with each other so those cannot be installed at the same time.
