### ISSUE TITLE
Problem building Python-3.10.7 on Photon OS missing  linux/limits.h

### ISSUE THREAD

**Issue by mwoodpatrick** [vmware/photon#1526]
### Describe the bug

After following the instructions in [Compiling C++ Code on the Minimal Version of Photon OS | (vmware.github.io)](https://vmware.github.io/photon/docs-v5/administration-guide/photon-os-packages/compiling-c-code-on-the-minimal-version-of-photon-os/) I tried to build python but it failed with 

	/usr/include/bits/local_lim.h:38:10: fatal error: linux/limits.h: No such file or directory
	   38 | #include <linux/limits.h>

### Reproduction steps

1.Download https://www.python.org/ftp/python/3.10.7/Python-3.10.7.tgz
2.tar xvf Python-"${version}".tgz &&
        cd Python-"${version}" &&
        ./configure --enable-optimizations &&
        sudo make altinstall
...

### Expected behavior

Should build python3

### Additional context

Was running on VMware Photon OS version 5.0

**Comment by dcasota** [comment]
Hi,

Unfortunately I wasn't able to reproduce the issue.

The following @sshedi-style code seems to work though.
It install as prerequirement the packages `tar curl gcc binutils make glibc-devel linux-api-headers zlib-devel`. 

Could you check the difference to your environment?

test environment: VMware Workstation 17 Pro , vm installed from photon-minimal-5.0-dde71ec57.x86_64.iso

remove python: `tdnf remove python3`
    
add test user:
```
useradd localuser
passwd localuser
usermod -a -G sudo localuser
su -l localuser
```



test script:
```
#!/bin/bash

topdir="$PWD"
ver="3.10.7"
srcname="Python-${ver}"
url="https://www.python.org/ftp/python/$ver/Python-$ver.tgz"
tarball="$(basename $url)"

pre_reqs=(tar curl gcc binutils make glibc-devel linux-api-headers zlib-devel)
if ! dpkg -s ${pre_reqs[@]} &>/dev/null; then
  sudo tdnf install -y ${pre_reqs[@]}
fi

fini() {
  local ret=$?

  cd "$topdir"
  if [ $ret -eq 0 ]; then
    sudo rm -rf "$srcname" "${tarball}"
  else
    sudo rm -rf "$srcname"
  fi

  exit $ret
}

trap fini EXIT

if ! ls "${tarball}" &> /dev/null; then
  sudo curl -J -L -O "$url"
fi

if ! sudo tar xvf "${tarball}"; then
  echo "ERROR: failed to extract downloaded tarball" 1>&2
  exit 1
fi

cd "$srcname"

if ! sudo ./configure --enable-optimizations; then
  echo "ERROR: configure failed" 1>&2
  exit 1
fi

if ! sudo make altinstall; then
  echo "ERROR: make failed" 1>&2
  exit 1
fi
```

**Comment by mwoodpatrick** [comment]
The script worked perfectly for me, many thanks, and closing

**Comment by dcasota** [comment]
Glad it worked 😀 An Apple a day keeps the docs away.
