### ISSUE TITLE
Ph 5.0 make build issues in packages sssd-2.8.2 and kubernetes-dashboard-2.7.0

### ISSUE THREAD

**Issue by dcasota** [vmware/photon#1528]
### Describe the bug

Ph 5.0 make build fails processing sssd-2.8.2 and kubernetes-dashboard-2.7.0 packages, see logfiles.
[build-kubernetes-dashboard-2.7.0.log](https://github.com/vmware/photon/files/13818992/build-kubernetes-dashboard-2.7.0.log)
[build-sssd-2.8.2.log](https://github.com/vmware/photon/files/13818993/build-sssd-2.8.2.log)
[sssd.log](https://github.com/vmware/photon/files/13818995/sssd.log)  

fyi observations
- During the last ten days, not all packages on packages.vmware.com/photon were downloadable (-> "not found").
- kubernetes-dashboard up to 2.7.0.9 has been placed in https://packages.vmware.com/photon/5.0/photon_5.0_x86_64/x86_64/. https://packages.vmware.com/photon/5.0/photon_updates_5.0_x86_64/x86_64/ contains the 2.7.0.11 version.

### Reproduction steps

Reference https://vmware.github.io/photon/docs-v5/installation-guide/building-images/build-iso-from-source/build-the-iso/

installed prerequirements: 
`tdnf install -y kpartx git bc build-essential createrepo_c texinfo wget python3-pip tar dosfstools cdrkit rpm-build`

### Expected behavior

successful make build.

### Additional context

btw. Happy New Year to the Photon OS team !

**Comment by prashant1221** [comment]
Happy New Year to you too. K8s-dashboard has been fixed by commit fc8b74616862c54.
sssd I was able to build successfully, can you try it again on latest commit.
Also which version of photon machine are you building it on?

**Comment by dcasota** [comment]
@prashant1221 Awesome, Thank You.

The make build process finished successfully with 1029 packages - thanks to the bump up of kubernetes-dashboard as part of nodejs 20.10.0 and the sssd bump up as part of gnutls 3.7.10. got resolved, too.

The photon-5.0-b773ede33.x86_64.iso outcome is from a classic make build with no custom repos.

Some observations:
- on the photon os builder machine (5.0 GA):
  - (No temporarily packages anymore with sha naming scheme, seen in publish or source - cannot remember.)
  - The needed bump wasn't obvious, at least for me. From a lessons learned perspective I'm not sure if I would be able to identify the cause myself next time and know how to respond.
    Hence, multiple srpms of the same package made it to the iso: [autoconf-2.71-2, autoconf-2.71-3],[emacs-28.2-3, emacs-28.2-4],...
  - Main.log is empty.

- on the iso:
  - EULA VMware General Terms still from 16 June 2022
  - OPEN_SOURCE_LICENSE_PHOTON_.TX seems to have an issue as packages are missing or in multiple versions: e.g. Section 2:
    - e.g. docker-23.0.1 + docker-23.0.2 but no docker 24.0.1 (packaged)
    - kubernetes-dashboard-2.0.3 (not packaged, but mentioned) and kubernetes-dashboard-2.7.0 (packaged)
    - ...

I will close the issue within 3 days. Let me know if I can provide you with any further information.

Namaskar

**Comment by dcasota** [comment]
fyi
- please, have a look to algorithm recommendations for openssh using ssh-audit, `tdnf install -y python3-pip` `pip3 install ssh-audit` `ssh-audit 127.0.0.1`. A few ciphers are listed as not recommended.
- minimal vm amount of ram is 824MB. With 768 mb ram (default e.g. in VMware by Broadcom Workstation 17.5) the vm installed photon-5.0-b773ede33.x86_64.iso (minimal) crashes.
   A thing to remember: With 824mb ram only, you have strange effects e.g. `lsmem` shows total online memory of 896M, and
   setups like `tdnf install -y awk libstdc++` `curl https://ollama.ai/install.sh | sh` `ollama serve &` `ollama run llama2` fail on step `curl`. This is for the docs.
- missing efi boot (shim-signed) support for baremetal boot
  btw. still that boot error message `error: ../../grub-core/fs/fshelp.c:257:file 'boot/grub2/x86_64-efi/vbe.mod' not found`

**Comment by prashant1221** [comment]
For k8s-dashboard, it was mistake from my side as I replaced the existing tarball hence there was shasum mismatch.
We'll keep the 3 points in mind
cc @tapakund @sshedi

**Comment by dcasota** [comment]
please mind kubernetes-dashboard on ph4 branch as well
