### ISSUE TITLE
tdnf makecache hangs on PhotonOS3

### ISSUE THREAD

**Issue by sebma** [vmware/photon#1530]
### Describe the bug

tdnf makecache hangs on VMware Photon OS 3.0

### Reproduction steps

1. Clean the tdnf cache
```shell
$ sudo tdnf clean all
Cleaning repos: photon photon-extras photon-updates
Cleaning up everything
$ 
```
2. Rebuild the tdnf cache
```shell
$ sudo tdnf makecache
Refreshing metadata for: 'VMware Photon Linux 3.0 (x86_64) Updates'
^Coton-updates                            9558   100%
$ 
```

### Expected behavior

The cache is downloaded.

### Additional context

VMware Photon OS 3.0

**Comment by sebma** [comment]
It somehow took 4 minutes to make the cache : 

```shell
$ time sudo tdnf makecache
Refreshing metadata for: 'VMware Photon Linux 3.0 (x86_64) Updates'
Refreshing metadata for: 'VMware Photon Extras 3.0 (x86_64)'
Refreshing metadata for: 'VMware Photon Linux 3.0 (x86_64)'
Metadata cache created.                2498249   100%

real    3m58.512s
user    3m52.216s
sys     0m1.616s
$
```

**Comment by oliverkurth** [comment]
Can you send the content of the repo files in `/etc/yum.repos.d/`? Make sure you have `skip_md_filelists=1` set, especially for `/etc/yum.repos.d/photon.repo` which is the largest repo because it contains all versions.

Also, have you checked if network access is acceptable for other applications, or is it just `tdnf`?

**Comment by sshedi** [comment]
> Can you send the content of the repo files in `/etc/yum.repos.d/`? Make sure you have `skip_md_filelists=1` set, especially for `/etc/yum.repos.d/photon-updates.repo` which is the largest repo because it contains all versions.
> 
> Also, have you checked if network access is acceptable for other applications, or is it just `tdnf`?

Before doing this, you have to update `tdnf` to latest. It's a one time thing but there is no other option.
```
tdnf update -y tdnf
```
This might take a while to finish. Then add `skip_md_filelists=1` in repo file.

Then try `rm -rf /var/cache/tdnf/` and `tdnf makecache --refresh`

**Comment by oliverkurth** [comment]
Well yes, I was assuming that `tdnf` was updated to the latest what's available in Photon 3.0, maybe I shouldn't have. So which version is this?

Also, if this is an old version, there should be no need to edit the config file to add `skip_md_filelists=1` , it will be done in the post install script of the package. But double check in any case.

**Comment by sebma** [comment]
Here is my `tdnf` :
```shell
$ grep skip_md_filelists /etc/yum.repos.d/*.repo
$ sudo tdnf --version
tdnf: 3.1.0
$
```

**Comment by sebma** [comment]
Now I've just updated it :
```shell
$ sudo tdnf update tdnf

Upgrading:
tdnf-cli-libs                                                   x86_64                          3.1.15-2.ph3                               photon-updates                           70.24k 71928
tdnf                                                            x86_64                          3.1.15-2.ph3                               photon-updates                         313.71k 321243

Total installed size: 383.96k 393171
Is this ok [y/N]: y

Downloading:
tdnf-cli-libs                            37007   100%
tdnf                                    123865   100%
Testing transaction
Running transaction
Installing/Updating: tdnf-cli-libs-3.1.15-2.ph3.x86_64
Installing/Updating: tdnf-3.1.15-2.ph3.x86_64
Removing: tdnf-3.1.0-1.ph3.x86_64
Removing: tdnf-cli-libs-3.1.0-1.ph3.x86_64

Complete!
$ grep skip_md_filelists /etc/yum.repos.d/*.repo
$
```

**Comment by sebma** [comment]
Still have the same problem : 
```shell
$ sudo rm -rf /var/cache/tdnf/
$ time sudo tdnf makecache --refresh
Refreshing metadata for: 'VMware Photon Linux 3.0 (x86_64) Updates'
photon-updates                            9578   100%
$
```

**Comment by sebma** [comment]
The issue was solved by manually appending the line `skip_md_filelists=1` to the `/etc/yum.repos.d/*.repo` files.

Thanks a lot guys 👍
