### ISSUE TITLE
Installing network-config-manager on Photon 5 Causes Docker Networking to Stop Working

### ISSUE THREAD

**Issue by zackzhenzhang** [vmware/photon#1538]
### Describe the bug

On a Photon 5 VM where there are docker containers running, after network-config-manager is installed and the VM is rebooted, networking for docker containers stops working entirely.

### Reproduction steps

(Command executions in the reproduction steps are done using root account)

1. On a vcenter, set up a pristine Photon 5 VM using [Full ISO x86_64](https://packages.vmware.com/photon/5.0/GA/iso/photon-5.0-dde71ec57.x86_64.iso) , also properly configure the networking for the VM (i.e. properly assign static ip, netmask, gateway, DNS, NTP...etc). 
2. Enable & start docker 
![image](https://github.com/vmware/photon/assets/53420990/4a6ec947-1b21-47ee-bc26-02d94638cb9e)
3. Install network-config-manager (tdnf install -y network-config-manager)
![image](https://github.com/vmware/photon/assets/53420990/5bf1af12-1a51-42df-a1ad-b95202147a57)
4. Pull any docker image (in this example,  nginx) to local repo for testing purpose, create and run the docker container. 
![image](https://github.com/vmware/photon/assets/53420990/0c97f426-8559-468b-b439-53d3971cda2f)
5. From within the nginx container, do a ping to an external IP (blurred out in screenshot) that it is supposed to be able to reach, the ping is successful. 
![image](https://github.com/vmware/photon/assets/53420990/79e12035-2a91-4734-9b40-5a9ca87a5086)
6. Reboot the VM
![image](https://github.com/vmware/photon/assets/53420990/d808e473-add0-42f1-977f-928040fae2ba)
7. After the reboot and nginx container is up and running again, from within the container, do the same ping again, now the ping fails. 
![image](https://github.com/vmware/photon/assets/53420990/af296962-c3bd-4126-a124-250113768338)

### Expected behavior

In step 7 of the reproduction steps, from within the nginx container, the ping command should succeed like before the VM reboot

### Additional context

- The networking issue being reported here is mainly for docker containers, the networking for the Photon VM itself still works fine (i.e. the VM can still reach external IPs and vice versa like before the reboot).
- The key step to reproduce the issue is step 3, installing network-config-manager is what causes the networking issue after the reboot. Without this step, docker's networking would still work fine after the reboot.

**Comment by YustasSwamp** [comment]
@ssahani please take a look.

**Comment by ssahani** [comment]
It seems like firewall rule. To figure out that could you plaease disable nftable and try again

**Comment by zackzhenzhang** [comment]
@ssahani , thanks for looking into it.

I'm testing it out now, will let you know the result.

**Comment by zackzhenzhang** [comment]
@ssahani , yes indeed, nftables is the root cause. 

Installing network-config-manager also brings nftables into the system, and the default rules in /etc/nftables/nft_ruleset_photon.nft is causing the docker networking issue.

We were using iptables to configure the firewall and we are planning to continue to use iptables for it in the foreseeable future, so it's ok for us to disable nftables. So your suggestion works for our use case.

Thanks for looking into this issue, closing it as the solution has been found.
