### ISSUE TITLE
openjdk17-17.0.8 does not compile when building package with Photon OS 5.0 on WSL2

### ISSUE THREAD

**Issue by dcasota** [vmware/photon#1542]
### Describe the bug

no priority, just fyi

Make build of a new iso fails when building package openjdk17. As the summary suggests, when building in WSL2, the package 
[make build](https://github.com/vmware/photon/files/14481111/make.build.openjdk17.txt) fails. This doesn't happen e.g. on VMware Workstation.

The configuration script `./stage/photonroot/openjdk17-17.0.8/usr/src/photon/BUILD/jdk17u-jdk-17.0.8-5/build/.configure-support/generated-configure.sh` tries to analyze the environment. `x86_64-pc-wsl` as build system type is detected correctly, however openjdk-build os-cpu = `windows-x86_64`, windows environment type = `wsl1` and wslpath `not found` are wrong. The expected detection should include `linux-x86_64` with `wsl2` and `/bin/wslpath` or `/usr/bin/wslpath` (both are symbolic links of `/init`.

### Reproduction steps

1. @lamw-style of an unsupported but documented setup of Photon OS 5.0 on WSL2, documented [here](https://github.com/dcasota/photonos-scripts/wiki/Photon-OS-on-WSL2).
   Photon OS on WSL2 is installed as user distribution and not as replacement of the system distribution cbl-mariner.
2. [build iso from source](https://vmware.github.io/photon/docs-v5/installation-guide/building-images/build-iso-from-source/)

### Expected behavior

successful make build on Photon OS on WSL2

### Additional context
Similar to https://bugs.busybox.net/show_bug.cgi?id=14561.
I will update this issue in case of problem solving news.

**Comment by sshedi** [comment]
building Photon OS on WSL is not in our scope. Please don't create issues on something which are not in our scope.

**Comment by dcasota** [comment]
strange, starting `./stage/photonroot/openjdk17-17.0.8/usr/src/photon/BUILD/jdk17u-jdk-17.0.8-5/configure` manually, shows that wslpath is found in the 2nd turn, also, wsl2 is detected.

```
[...]
configure: WARNING: Ignoring value of PATHTOOL from the environment. Use command line variables instead.
checking for cygpath... [not found]
checking for wslpath... /usr/bin/wslpath
checking for cmd.exe... /mnt/c/Windows/system32/cmd.exe
checking build system type... x86_64-pc-wsl
checking host system type... x86_64-pc-wsl
checking target system type... x86_64-pc-wsl
checking openjdk-build os-cpu... windows-x86_64
checking openjdk-target os-cpu... windows-x86_64
checking compilation type... native
checking Windows environment type... wsl2
checking wsl2 drive prefix... '/mnt'
checking wsl2 root directory as Windows path... '\\wsl.localhost\Ph5'
checking wsl2 temp directory... /usr/bin/wslpath: Invalid argument
Usage:    -a    force result to absolute path format    -u    translate from a Windows path to a WSL path (default)    -w    translate from a WSL path to a Windows path    -m    translate from a WSL path to a Windows path, with '/' instead of '\'EX: wslpath 'c:\users'
/root/photon/stage/photonroot/openjdk17-17.0.8/usr/src/photon/BUILD/jdk17u-jdk-17.0.8-5/build/.configure-support/generated-configure.sh: line 12873: cd: Usage:    -a    force result to absolute path format    -u    translate from a Windows path to a WSL path (default)    -w    translate from a WSL path to a Windows path    -m    translate from a WSL path to a Windows path, with '/' instead of '\'EX: wslpath 'c:\users': No such file or directory
cp: cannot create regular file 'Usage:    -a    force result to absolute path format    -u    translate from a Windows path to a WSL path (default)    -w    translate from a WSL path to a Windows path    -m    translate from a WSL path to a Windows path, with '\''/'\'' instead of '\''\'\''EX: wslpath '\''c:\users'\''': No such file or directory
checking wsl2 release... 5.15.146.1-microsoft-standard-WSL2+
checking wsl2 version... #1 SMP Sat Mar 2 11:58:41 CET 2024
checking Windows version... /root/photon/stage/photonroot/openjdk17-17.0.8/usr/src/photon/BUILD/jdk17u-jdk-17.0.8-5/build/.configure-support/generated-configure.sh: line 12899: cd: too many arguments

checking wsl distribution... /root/photon/stage/photonroot/openjdk17-17.0.8/usr/src/photon/BUILD/jdk17u-jdk-17.0.8-5/build/.configure-support/generated-configure.sh: line 12924: -d: command not found

checking what kind of 'find' is first on the PATH... unix style
/root/photon/stage/photonroot/openjdk17-17.0.8/usr/src/photon/BUILD/jdk17u-jdk-17.0.8-5/make/scripts/fixpath.sh: illegal option -- a
/root/photon/stage/photonroot/openjdk17-17.0.8/usr/src/photon/BUILD/jdk17u-jdk-17.0.8-5/make/scripts/fixpath.sh: illegal option -- a
configure: error: The path of TOPDIR, which resolves as "/root/photon/stage/photonroot/openjdk17-17.0.8/usr/src/photon/BUILD/jdk17u-jdk-17.0.8-5", could not be imported.
```
The topdir issue has been mentioned in https://github.com/vmware/photon/issues/1412#issuecomment-1975245296.

**Comment by dcasota** [comment]
Same compile issue in (unsupported) WSL2 with latest openjdk17-17.0.13-2.ph5 package. Running `./stage/photonroot/openjdk17-17.013-2.ph5/usr/src/photon/BUILD/jdk17u-jdk-17.0.13-ga/configure` manually, results in a 'too long' path issue.

```
[...]
checking wsl2 release... 6.6.36.6-microsoft-standard-WSL2+
checking wsl2 version... #1 SMP Sun Dec 15 15:24:02 CET 2024
checking Windows version... 10.0.26100.2605
checking wsl distribution... /home/user/photon/stage/photonroot/openjdk17-17.0.13-2.ph5/usr/src/photon/BUILD/jdk17u-jdk-17.0.13-ga/build/.configure-support/generated-configure.sh: line 12940: -d: command not found

configure: error: Your base path is too long. It is 103 characters long, but only 100 is supported
configure exiting with result code 1
```
