### ISSUE TITLE
Trying to setup static IP using installer and afterwards checking through the docs still not working

### ISSUE THREAD

**Issue by typoworx-de** [vmware/photon#1543]
### Describe the bug

I'm having fresh installation in vmware esxi for photon. During install I've choosen static IP -- which did only work partial after install. DNS is not resolving for any reason. Ping to my gateway (endian firewall connected using VLAN in vmware) works. I'm using same setup for other linux vm's which works there.

### Reproduction steps

1.follow the docs and edit network config as I did
2.
3.
...

### Expected behavior

network should work and DNS too!

**Comment by dcasota** [comment]
Hi,

Here a few troubleshooting information.

Start with `ls /etc/systemd/network/`: Is there one single `.network` file?

Then, have a look to your network configuration.
You might need ip forwarding with `sysctl -w net.ipv4.ip_forward=1` and you might need to declare `GatewayOnlink=true`for the route.

```
cat > /etc/systemd/network/10-eth0-static.network << "EOF"
[Match]
Name=eth0

[Network]
DHCP=no
IPv6AcceptRA=no  
Domains=yourdomain.com                                                                                                                                                                        
Address=192.168.157.2/24
DNS=8.8.8.8,4.4.4.4
Gateway=192.168.157.1
NTP=pool.ntp.org

[Route]                                                                                                                                                                                        
Destination=192.168.157.0/24                                                                                                                                                                     
Gateway=192.168.157.1                                                                                                                                                                           
GatewayOnlink=true

[DHCP]
UseDNS=false
UseRoutes=true
EOF

chmod 644 /etc/systemd/network/10-eth0-static.network
systemctl restart systemd-networkd
systemctl restart systemd-resolved

sysctl -w net.ipv4.ip_forward=1
systemctl restart iptables
```

Check network: `networkctl`

Check (default) route: `resolvectl`

`/etc/nsswitch.conf` should already contain `hosts: files dns`. Do not modify manually `/run/systemd/resolve/resolv.conf` and `/etc/resolv.conf`.

**Comment by typoworx-de** [comment]
By the way ping using IP to my Firewall/Router IP 172.16.0.1 works. Resolving host-names (DNS) is stuck and doesn't work.

**Comment by typoworx-de** [comment]
I finally got it working like this. I don't know what was wrong -- a final reboot (again) did it. May be it was the route-section by adding Gateway and GatewayOnLink. But on my first test-install it worked without that (even after reboots).

/etc/systemd/network/99-static-en.network

```
[Match]
Name=eth0

[Network]
DHCP=no
Address=172.16.0.3/16
DNS=172.16.0.1,8.8.8.8,8.8.4.4
Gateway=172.16.0.1

[Route]
GatewayOnLink=true
Gateway=172.16.0.1
```
