### ISSUE TITLE
Static IP breaks network connections in Photon OS 5 on VMWare Workstation

### ISSUE THREAD

**Issue by buridan1999** [vmware/photon#1546]
### Describe the bug

I try few instruction for setting up static IP in Photon, first of all was use [this link](https://vmware.github.io/photon/assets/files/html/3.0/photon_admin/setting-a-static-ip-address.html).

I read also this [issue(888)](https://github.com/vmware/photon/issues/888), but can't find solution for this.

The config file /etc/systemd/network/90-static-en.network this:
```
[Match]
Name=eth0

[Network]
DHCP=no
Address=192.168.0.99/24
Gateway=192.168.0.1
```

After that I set the correct access permissions and I restart the deamon like described in the manual. But I can't ping google.com, can't connect to this VM with ssh(sshd is working on 22 port, and root is admited).

When I pinged when DHCP was still active, there was no problem. And at the first start DHCP give me 192.168.0.x so I doesn't try to setup static IP, but after VM restart it's changed to 172.x.x.x, which doesn't usefull and I tried set static IP for VM and failed.

When I run ifconfig:
![image](https://github.com/vmware/photon/assets/25010424/25238206-d472-4413-b59c-00ab98a95ce4)

I dont know what i'm doing wrong. i'm out of ideas.

### Reproduction steps

1. Install OVA to VMWare Workstation
2. Try to setup static IP for VM
3. That's it!

### Expected behavior

I expect that after that I have internet access on VM, and can connect with ssh to it.

### Additional context

Photon OS 5 OVA, 
VMWare Workstation 16.1.2 build-17966106, 
VM Adapter in Bridge mode

**Comment by dcasota** [comment]
Hi,

Check the cascade Windows networking + VMware By Broadcom Workstation networking + Photon OS networking.

#### Windows networking
- Check the configured ethernet adapters with `ipconfig /all`.
   Notice if any difference with naming similar to `vEthernet (Default Switch)` which are not visible with `netsh interface show interface` or (pwsh) `get-netadapter`.
- In case of active hyperv,
   - Check virtual switches with `get-vmswitch`
   - Check virtual ethernet adapter for hyperv with `get-vmnetworkadapter -all`.
     Typically you get an ip 172.x.x.x with an existing hyperv virtual ethernet adapter.
   - Check if any hyperv fw settings 
   `get-netfirewallhypervrule | where-object {$_.VMCreatorId -eq "{40E0AC32-46A5-438A-A0B2-2B479E8F2E90}"}`
   To reset the hyperv fw settings, you can use `get-netfirewallhypervrule | where-object {$_.VMCreatorId -eq "{40E0AC32-46A5-438A-A0B2-2B479E8F2E90}"} | remove-netfirewallhypervrule`.
- Check if any wrong port proxy with `netsh interface portproxy show all`. You can reset the settings with `netsh interface portproxy reset`.

#### VMware By Broadcom Workstation networking
In virtual network editor of VMware By Broadcom Workstation, select 'bridged' (or 'custom') and in VMnet information
- Bridged, check the 'bridged to' settings.
   Switch from _automatic_ to the specific network with  gw 192.168.0.1. Check if ping works.
   In 'Automatic settings', deselect the network adapters which shouldn't be eligible.

#### Photon OS networking
- yes, the [docs link](https://vmware.github.io/photon/assets/files/html/3.0/photon_admin/setting-a-static-ip-address.html) mentioned is fine.
- in case of multiple networks, see https://github.com/vmware/photon/issues/1543, especially [Route] section. The GatewayOnLink feature has been mentioned by @ssahani in https://github.com/vmware/photon/issues/719#issuecomment-429516439.
- fw iptables, nftables

**Comment by buridan1999** [comment]
> Hi,
> 
> Check the cascade Windows networking + VMware By Broadcom Workstation networking + Photon OS networking.
> 
> #### Windows networking
> * Check the configured ethernet adapters with `ipconfig /all`.
>   Notice if any difference with naming similar to `vEthernet (Default Switch)` which are not visible with `netsh interface show interface` or (pwsh) `get-netadapter`.
> * In case of active hyperv,
>   
>   * Check virtual switches with `get-vmswitch`
>   * Check virtual ethernet adapter for hyperv with `get-vmnetworkadapter -all`.
>     Typically you get an ip 172.x.x.x with an existing hyperv virtual ethernet adapter.
>   * Check if any hyperv fw settings
>     `get-netfirewallhypervrule | where-object {$_.VMCreatorId -eq "{40E0AC32-46A5-438A-A0B2-2B479E8F2E90}"}`
>     To reset the hyperv fw settings, you can use `get-netfirewallhypervrule | where-object {$_.VMCreatorId -eq "{40E0AC32-46A5-438A-A0B2-2B479E8F2E90}"} | remove-netfirewallhypervrule`.
> * Check if any wrong port proxy with `netsh interface portproxy show all`. You can reset the settings with `netsh interface portproxy reset`.
> 
> #### VMware By Broadcom Workstation networking
> In virtual network editor of VMware By Broadcom Workstation, select 'bridged' (or 'custom') and in VMnet information
> 
> * Bridged, check the 'bridged to' settings.
>   Switch from _automatic_ to the specific network with  gw 192.168.0.1. Check if ping works.
>   In 'Automatic settings', deselect the network adapters which shouldn't be eligible.
> 
> #### Photon OS networking
> * yes, the [docs link](https://vmware.github.io/photon/assets/files/html/3.0/photon_admin/setting-a-static-ip-address.html) mentioned is fine.
> * in case of multiple networks, see [Trying to setup static IP using installer and afterwards checking through the docs still not working #1543](https://github.com/vmware/photon/issues/1543), especially [Route] section. The GatewayOnLink feature has been mentioned by @ssahani in [Static routes not working #719 (comment)](https://github.com/vmware/photon/issues/719#issuecomment-429516439).
> * fw iptables, nftables

Thanks you a lot for help. It was problem with VMNet configuration, which brokern after VPN was enabled.
Sorry for your time.
