### ISSUE TITLE
esx variant of linux kernel image missing module `nf_tables` for photon 3

### ISSUE THREAD

**Issue by dlinsley** [vmware/photon#1548]
### Describe the bug

Latest versions for photon3 `linux-esx` package are missing kernel modules compared to generic `linux` package

kernel module found in `linux-4.19.307-3.ph3` but missing in `linux-esx-4.19.307-3.ph3`:  `nf_tables`

I don't know if this is intentional to have a drift of available kernel modules between the variants.

### Reproduction steps

1.  Install and boot `linux-4.19.307-3.ph3`
2.  `modprobe nf_tables` succeeds
3.  Install and boot `linux-esx-4.19.307-3.ph3`
4.  `modprobe nf_tables` fails

### Expected behavior

Expected `linux-esx` kernels to have same modules available in `linux` kernels.

### Additional context

Workaround is to not use `linux-esx`.  Replace with `linux`

lack of `nf_tables` module broke running current versions of [concourse](https://github.com/concourse/concourse) (7.10 & newer) on kubernetes on photon 3 with current `linux-esx` kernels for me.

**Comment by YustasSwamp** [comment]
Hi @dlinsley we recommend using generic kernel flavor to run k8s in regular VMs.
Main consumer for linux-esx is CRX runtime.
