### ISSUE TITLE
Enabling TCP BBR congestion control in Photon OS 5.0 GA

### ISSUE THREAD

**Issue by Tw-C** [vmware/photon#1566]
### Is your feature request related to a problem? Please describe.

It appears TCP BBR congestion control algorithm isn't enabled in latest Photon OS 5.0 GA despite https://github.com/vmware/photon/issues/801.

Also can't seem to find any official documentation about enabling it. Any pointer would be helpful & appreciated.

### Describe the solution you'd like

An easy option to enable TCP BBR congestion control algorithm or even have it enabled as default in newer Photon OS releases.

**Comment by YustasSwamp** [comment]
I assume you are using -esx flavor of the kernel (-esx suffix in `uname -r`). Please use generic kerel. `tdnf install linux -y && reboot`

**Comment by Tw-C** [comment]
> I assume you are using -esx flavor of the kernel (-esx suffix in `uname -r`). Please use generic kerel. `tdnf install linux -y && reboot`

You are correct, BBR is available in generic kernel but not -esx flavour, well-kept secret 😁 Thanks for the prompt reply!

On a different note, `/etc/sysctl.conf` doesn't appear to auto run on startup but moving to `/etc/sysctl.d/` works.

**Comment by YustasSwamp** [comment]
Only /etc/sysctl.d/ is handled by systemd!
For legacy compatibility /etc/sysctl.conf is a symlink to some file inside /etc/sysctl.d/...
If /etc/sysctl.conf just a regular file - it will be ignored.

**Comment by Tw-C** [comment]
Cheers for the tips, very useful indeed. Is there a knowledgebase somewhere listing out all these tips, as I've thoroughly dug through documentation at https://vmware.github.io/photon/docs-v5/ & almost gave up before asking here as a last resort 🤷
