### ISSUE TITLE
warning: %postun(coreutils-selinux-9.1-5.ph5.x86_64) scriptlet failed, exit status 1

### ISSUE THREAD

**Issue by jnovak-netsystemcz** [vmware/photon#1568]
### Describe the bug

Today I upgraded several PhotonOS 5.0 systems and on every of it I noticed:

Removing: coreutils-selinux-9.1-5.ph5.x86_64
warning: %postun(coreutils-selinux-9.1-5.ph5.x86_64) scriptlet failed, exit status 1
package coreutils-selinux-9.1-5.ph5.x86_64: script warning in %postun

new installed version is install coreutils-selinux-9.1-8.ph5.x86_64

It is obvious, that failure was caused by older package than the latest one. 
I noticed no issue after upgrade and even I checked logs I didn't find what was the reason for scriptlet failure.

I'm creating this report just to note that there might be some issue in post uninstall script in coreutils-selinux.

### Reproduction steps

1. tdnf update

### Expected behavior

No error during upgrade

**Comment by sshedi** [comment]
This is already fixed in: https://github.com/vmware/photon/commit/1e616ced88b25bc2f4b9a49c0326a10e48449ebd

Post upgrading to coreutils version mentioned in the above commit, you won't see the error again.
