### ISSUE TITLE
Photon4 to Photon5 upgrade is failing while consuming the ph5 packages from photon repository

### ISSUE THREAD

**Issue by Karthi4187** [vmware/photon#1575]
### Describe the bug

Photon4 to Photon5 upgrade is failing while consuming the ph5 packages from photon repository.

The upgrade is working fine before consuming these latest rpm updates.

Upgrade Command:
`/usr/bin/photon-upgrade.sh --skip-update --assume-yes --upgrade-os --repos=appliance-photon --install-all`

List of packages updated to latest recently:
```
glibc-2.36-15.ph5.x86_64
glibc-libs-2.36-15.ph5.x86_64
bash-5.2-5.ph5.x86_64
openssl-libs-3.0.15-5.ph5.x86_64
openssl-3.0.15-5.ph5.x86_64
Linux-PAM-1.5.3-5.ph5.x86_64
shadow-libs-4.13-8.ph5.x86_64
ca-certificates-pki-20230315-6.ph5.x86_64
ca-certificates-20230315-6.ph5.x86_64
shadow-tools-4.13-8.ph5.x86_64
shadow-4.13-.ph5.x86_64
openssl-c_rehash-3.0.15-5.ph5.x86_64
glibc-iconv-2.36-15.ph5.x86_64
linux-6.1.118-6.ph5.x86_64
glibc-lang-2.36-15.ph5.x86_64
postgresql14-libs-14.15-1.ph5.x86_64
postgresql14-client-14.15-1.ph5.x86_64
postgresql14-server-14.15-1.ph5.x86_64
postgresql14-14.15-1.ph5.x86_64
postgresql14-contrib-14.15-1.ph5.x86_64
```

Error log:
`2024-12-09T14:04:29+0000 Upgrading Photon OS from 4.0 to 5.0. Assuming that data backup has already been done.
2024-12-09T14:04:29+0000 
2024-12-09T14:04:30+0000 Recording list of all installed RPMs on this machine to /tmp/photon-upgrade.sh-2024-12-09-14-04-29/rpm-qa.txt.
2024-12-09T14:04:30+0000 Creating backup of RPM DB.
/usr/bin/cp: missing destination file operand after '/tmp/photon-upgrade.sh-2024-12-09-14-04-29'
Try '/usr/bin/cp --help' for more information.
2024-12-09T14:04:30+0000 Generating tdnf cache on Photon OS 4.0
Refreshing metadata for: 'vCenter bundled Photon OS 4.0 (x86_64)'
Metadata cache created.
2024-12-09T14:04:30+0000 Generating tdnf cache on Photon OS 5.0
Refreshing metadata for: 'vCenter bundled Photon OS 5.0 (x86_64)'
Metadata cache created.
2024-12-09T14:04:30+0000 Finding packages in the target repo. This may take several minutes.
2024-12-09T14:04:31+0000 All installed packages are validated in the target repo.
2024-12-09T14:04:31+0000 Generating tdnf cache on Photon OS 4.0
Refreshing metadata for: 'vCenter bundled Photon OS 4.0 (x86_64)'
Metadata cache created.
2024-12-09T14:04:31+0000 Determining enabled systemd units to be enabled post upgrade of OS...
2024-12-09T14:04:32+0000 Enabled systemd utils are: ( cloud-config.service cloud-final.service cloud-init.service crond.service getty@.service getty@tty1.service haveged.service iptables.service irqbalance.service rabbitmq-server.service rpmdb-rebuild.service sshd-keygen.service sshd.service systemd-networkd-wait-online.service systemd-networkd.service systemd-resolved.service vami-sfcb.service vgauthd.service vmtoolsd.service dm-event.socket systemd-networkd.socket machines.target remote-fs.target tdnf-cache-updateinfo.timer )
2024-12-09T14:04:32+0000 Determining disabled systemd units to be disabled post upgrade of OS...
2024-12-09T14:04:32+0000 Disabled systemd utils are: ( proc-sys-fs-binfmt_misc.mount auditd.service blk-availability.service console-getty.service debug-shell.service import-state.service loadmodules.service lvm2-monitor.service rsyslog.service saslauthd.service serial-getty@.service systemd-boot-check-no-failures.service systemd-journal-upload.service systemd-network-generator.service systemd-nspawn@.service systemd-pstore.service systemd-time-wait-sync.service systemd-timesyncd.service vaos.service cloud-init-hotplugd.socket systemd-journal-gatewayd.socket systemd-journal-remote.socket systemd-userdbd.socket exit.target halt.target kexec.target poweroff.target reboot.target logrotate.timer )
2024-12-09T14:04:32+0000 Rebuilding RPMDB.
2024-12-09T14:04:32+0000 successfully rebuilt RPMDB.
2024-12-09T14:04:32+0000 Upgrading Photon OS to 5.0 from 4.0
1. package python3-3.10.11-8.ph4.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
2. package python3-3.10.11-8.ph4.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
3. package python3-3.10.11-8.ph4.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
4. package vmware-studio-vami-service-update-3.0.0.7-0.x86_64 requires vmware-studio-vami-service-core, but none of the providers can be installed
5. package vmware-studio-vami-service-system-3.0.0.7-0.x86_64 requires vmware-studio-vami-service-core, but none of the providers can be installed
6. package python3-libs-3.10.11-8.ph4.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
7. package python3-libs-3.10.11-8.ph4.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
8. nothing provides libcrypt.so.1(XCRYPT_2.0)(64bit) needed by shadow-4.13-8.ph5.x86_64
9. package guile-2.0.13-4.ph4.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
10. package systemd-247.13-12.ph4.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
11. package python3-3.10.11-8.ph4.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
12. package python3-3.10.11-8.ph4.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
13. package python3-3.10.11-8.ph4.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
14. package python3-3.10.11-8.ph4.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
15. package python3-3.10.11-8.ph4.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
16. package python3-3.10.11-8.ph4.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
17. package python3-3.10.11-8.ph4.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
18. package python3-3.10.11-8.ph4.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
19. package python3-3.10.11-8.ph4.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
20. package python3-3.10.11-8.ph4.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
21. package python3-3.10.11-8.ph4.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
22. package python3-3.10.11-8.ph4.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
23. package python3-3.10.11-8.ph4.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
24. package python3-3.10.11-8.ph4.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
25. package python3-3.10.11-8.ph4.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
26. package python3-3.10.11-8.ph4.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
27. package vmware-studio-vami-service-network-3.0.0.7-0.x86_64 requires vmware-studio-vami-service-core, but none of the providers can be installed
28. package python3-requests-2.26.0-2.ph4.noarch requires python3.10dist(certifi) >= 2017.4.17, but none of the providers can be installed
29. package python3-3.10.11-8.ph4.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
30. package python3-3.10.11-8.ph4.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
31. package python3-3.10.11-8.ph4.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
32. package open-vm-tools-12.4.5-1.ph4.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
33. package perl-5.30.1-7.ph4.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
34. package vidm-kdc-1.0.0.0-a0c68cea13d26baef7fac4bcf4b893f52df1548c.x86_64 requires horizon-va-setup >= 2.5.0.0, but none of the providers can be installed
35. package vidm-certificate-proxy-24.07.0.0-9408d8c54af0e2ce6b36e2c437727d8425d79965.noarch requires horizon-va-setup > 2.2.0, but none of the providers can be installed
36. package vidm-certificate-auth-service-24.07.0.0-9408d8c54af0e2ce6b36e2c437727d8425d79965.noarch requires horizon-va-setup > 2.2.0, but none of the providers can be installed
37. package vidm-auth-adapters-24.07.0.0-9408d8c54af0e2ce6b36e2c437727d8425d79965.noarch requires horizon-va-setup > 2.2.0, but none of the providers can be installed
38. package vidm-analytics-service-1.0-62407b510fe20027b40e5545e1c79bca9e5de7ee.noarch requires horizon-va-setup > 3.2, but none of the providers can be installed
39. package vidm-accesscontrol-service-0.0.1-251172ef16f308f0e60aefe6f29ec1304c92a0f2.noarch requires horizon-va-setup > 3.2, but none of the providers can be installed
40. package svadmin-rpm-24.07.0.0-9408d8c54af0e2ce6b36e2c437727d8425d79965.noarch requires horizon-va-setup >= 2.2.0, but none of the providers can be installed
41. package notifications-0.1.0-0e0c12c4ce7bf6bd7bf7105660204cffae43c785.noarch requires horizon-va-setup > 19.11, but none of the providers can be installed
42. package horizon-workspace-tcserver-impl-24.07.0.0-9408d8c54af0e2ce6b36e2c437727d8425d79965.noarch requires horizon-va-setup > 2.2.0, but none of the providers can be installed
43. package horizon-webClients-rpm-24.07.0.0-9408d8c54af0e2ce6b36e2c437727d8425d79965.noarch requires horizon-va-setup > 2.2.0, but none of the providers can be installed
44. package horizon-va-update-24.12.0.0-7a4e2a9d3118b03cbe8458ee96b976d01b6cc0dc.noarch requires horizon-va-setup, but none of the providers can be installed
45. package horizon-service-rpm-24.07.0.0-9408d8c54af0e2ce6b36e2c437727d8425d79965.noarch requires horizon-va-setup > 2.2.0, but none of the providers can be installed
46. package horizon-opensearch-rpm-2.8.0-9408d8c54af0e2ce6b36e2c437727d8425d79965.noarch requires horizon-va-setup > 2.2.0, but none of the providers can be installed
47. package perl-5.30.1-7.ph4.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
48. package perl-5.30.1-7.ph4.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
49. package perl-5.30.1-7.ph4.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
50. package perl-5.30.1-7.ph4.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
51. package vmware-studio-vami-service-core-3.0.0.7-0.x86_64 requires vmware-studio-vami-servicebase, but none of the providers can be installed
52. package python3-libs-3.10.11-8.ph4.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
53. package python3-libs-3.10.11-8.ph4.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
54. package python3-libs-3.10.11-8.ph4.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
55. package python3-libs-3.10.11-8.ph4.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
56. package python3-libs-3.10.11-8.ph4.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
57. package python3-libs-3.10.11-8.ph4.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
58. package python3-libs-3.10.11-8.ph4.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
59. package python3-libs-3.10.11-8.ph4.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
60. package vmware-studio-vami-cimom-3.0.0.7-22671178.x86_64 requires python3-pywbem, but none of the providers can be installed
61. package python3-libs-3.10.11-8.ph4.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
62. package python3-libs-3.10.11-8.ph4.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
63. package python3-libs-3.10.11-8.ph4.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
64. package python3-libs-3.10.11-8.ph4.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
65. package python3-cffi-1.14.3-3.ph4.x86_64 requires python3.10dist(pycparser), but none of the providers can be installed
66. package python3-libs-3.10.11-8.ph4.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
67. package systemd-247.13-12.ph4.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
68. package systemd-247.13-12.ph4.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
69. package systemd-247.13-12.ph4.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
70. package systemd-247.13-12.ph4.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
71. package systemd-247.13-12.ph4.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
72. package systemd-247.13-12.ph4.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
73. package systemd-247.13-12.ph4.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
74. package systemd-247.13-12.ph4.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
75. package systemd-247.13-12.ph4.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
76. package util-linux-2.37.4-2.ph4.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
77. package util-linux-2.37.4-2.ph4.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
78. nothing provides libcrypt.so.1(XCRYPT_2.0)(64bit) needed by shadow-4.13-8.ph5.x86_64
79. nothing provides libcrypt.so.1(XCRYPT_2.0)(64bit) needed by shadow-4.13-8.ph5.x86_64
80. nothing provides libcrypt.so.1(XCRYPT_2.0)(64bit) needed by Linux-PAM-1.5.3-5.ph5.x86_64
81. package systemd-253.19-7.ph5.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
82. nothing provides libcrypt.so.1(XCRYPT_2.0)(64bit) needed by Linux-PAM-1.5.3-5.ph5.x86_64
83. nothing provides libcrypt.so.1(XCRYPT_2.0)(64bit) needed by shadow-4.13-8.ph5.x86_64
84. package python3-libs-3.11.9-5.ph5.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
85. package python3-libs-3.11.9-5.ph5.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
86. package python3-libs-3.11.9-5.ph5.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
87. package openssh-server-9.3p2-10.ph5.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
88. nothing provides libcrypt.so.1(XCRYPT_2.0)(64bit) needed by Linux-PAM-1.5.3-5.ph5.x86_64
89. nothing provides libcrypt.so.1(XCRYPT_2.0)(64bit) needed by Linux-PAM-1.5.3-5.ph5.x86_64
90. package util-linux-2.37.4-2.ph4.x86_64 requires util-linux-libs = 2.37.4-2.ph4, but none of the providers can be installed
91. package guile-2.0.13-4.ph4.x86_64 requires libffi.so.7()(64bit), but none of the providers can be installed
92. package util-linux-2.37.4-2.ph4.x86_64 requires libreadline.so.7()(64bit), but none of the providers can be installed
93. package systemd-247.13-12.ph4.x86_64 requires systemd-rpm-macros = 247.13-12.ph4, but none of the providers can be installed
94. package systemd-247.13-12.ph4.x86_64 requires systemd-pam = 247.13-12.ph4, but none of the providers can be installed
95. nothing provides libcrypt.so.1(XCRYPT_2.0)(64bit) needed by Linux-PAM-1.5.3-5.ph5.x86_64
96. nothing provides libcrypt.so.1(XCRYPT_2.0)(64bit) needed by shadow-4.13-8.ph5.x86_64
97. package systemd-247.13-12.ph4.x86_64 requires systemd-libs = 247.13-12.ph4, but none of the providers can be installed
98. nothing provides libcrypt.so.1(XCRYPT_2.0)(64bit) needed by shadow-4.13-8.ph5.x86_64
99. nothing provides libcrypt.so.1(XCRYPT_2.0)(64bit) needed by shadow-4.13-8.ph5.x86_64
100. package util-linux-2.38-5.ph5.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
101. package systemd-253.19-7.ph5.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
102. package vmware-studio-vami-servicebase-3.0.0.7-22671178.x86_64 requires /bin/sh, but none of the providers can be installed
103. package euc-common-catalog-1.0-1d2b85c7d1d075451996d9232d6d4454b75df9d6.noarch requires horizon-va-setup > 2.5, but none of the providers can be installed
104. package openssh-server-9.3p2-10.ph5.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
105. package horizon-va-setup-24.07.0.0-9408d8c54af0e2ce6b36e2c437727d8425d79965.noarch requires /usr/bin/vmware-toolbox-cmd, but none of the providers can be installed
106. package guile-2.2.7-6.ph5.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
107. nothing provides libcrypt.so.1(XCRYPT_2.0)(64bit) needed by shadow-4.13-8.ph5.x86_64
108. package cyrus-sasl-2.1.28-4.ph5.x86_64 requires libcrypt.so.1()(64bit), but none of the providers can be installed
109. nothing provides libcrypt.so.1(XCRYPT_2.0)(64bit) needed by Linux-PAM-1.5.3-5.ph5.x86_64
110. nothing provides libcrypt.so.1(XCRYPT_2.0)(64bit) needed by shadow-4.13-8.ph5.x86_64
111. nothing provides libcrypt.so.1(XCRYPT_2.0)(64bit) needed by shadow-libs-4.13-8.ph5.x86_64
Found 111 problem(s) while resolving
Error(1301) : Solv general runtime error
Refreshing metadata for: 'vCenter bundled Photon OS 5.0 (x86_64)'
2024-12-09T14:04:32+0000 Error in upgrading to Photon OS 5.0 from 4.0 ((tdnf error code: 21).
Original list of RPMs and RPM DB are stored in /tmp/photon-upgrade.sh-2024-12-09-14-04-29,  please provide contents of that folder along with system journal   logs for analysis; these logs can be captured using command-
 # /usr/bin/journalctl -xa > /tmp/photon-upgrade.sh-2024-12-09-14-04-29/journal.log
 Cannot continue. Aborting.
OS upgrade from photon 4 to photon 5 failed.`

### Reproduction steps

1. Perform upgrade using photon-upgrade script with local repository
2. /usr/bin/photon-upgrade.sh --skip-update --assume-yes --upgrade-os --repos=appliance-photon --install-all
3.
...

### Expected behavior

Upgrade should work with latest photon packages

**Comment by dcasota** [comment]
@Karthi4187 could be related to latest bash-5.2-5.ph5.x86_64 package.
```/usr/bin/cp: missing destination file operand after '/tmp/photon-upgrade.sh-2024-12-09-14-04-29'```
Can you downgrade the package to 5.2-3 and retry?

**Comment by Karthi4187** [comment]
Thanks for the quick response @sshedi and @dcasota.
We are able to proceed with upgrade once we added to libxcrypt-4.4.36-2 to appliance-photon repo.
Resolving this ticket.
