### ISSUE TITLE
Yum repos to add to enable us to install bridge-utils

### ISSUE THREAD

**Issue by willemdh** [vmware/photon#175]
Hello,

I installed full photon version. Which yum repositories can I safely add to /etc/yum.repos.d/ ?

I'm trying to install bridge-utils with 

    yum install bridge-utils

But I get "photon                                                                                                                                                             | 1.2 kB  00:00:00
photon-updates                                                                                                                                                     | 1.2 kB  00:00:00
Setting up Install Process
No package bridge-utils available.
Error: Nothing to do"

When following the Docker documentation for setting up a bridge: https://docs.docker.com/articles/networking/#bridge-building

brctl command is nnot found....

Thanks for claryfying how to make brctl work. Shouldn't this be included in the iso if using brctl is what Docker recommends to set up a bridge?

Tx and grtz

Willem

**Comment by toliaqat** [comment]
I assume you have installed Photon full from TP1 release that is not pointing to right repo. For the moment try downloading and installing manually using following commands.
```
wget https://dl.bintray.com/vmware/photon_release_1.0_x86_64/x86_64/bridge-utils-1.5-1.x86_64.rpm

rpm -Uvh bridge-utils-1.5-1.x86_64.rpm
```

Or

You can also try changing the /etc/yum.repos.d/photon.repo with following baseurl

```
baseurl=https://dl.bintray.com/vmware/photon_release_1.0_x86_64
gpgkey=file:///etc/pki/rpm-gpg/PHOTON-RPM-GPG-KEY
```

then

```
yum clean all
yum install bridge-utils
```

I tried above on TP1 full installation and it got brctl command working.

You can also build your own latest ISO from source code and that will be pointing to right yum repo.

**Comment by willemdh** [comment]
Toliaqat,

I changed
    https://dl.bintray.com/vmware/photon_release_1.0_TP1_x86_64
    gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY

to
    https://dl.bintray.com/vmware/photon_release_1.0_x86_64
    file:///etc/pki/rpm-gpg/PHOTON-RPM-GPG-KEY

and did
    yum clean all
    yum install bridge-utils
and was able to install bridge-utils. 
Thanks for the help!  Some other questions popup. As doing
    yum check-update
Now suddenly gives me a whole range of packages to be updated. If I do update them all, would this imply my Photon server is at version 1.0.0-195? As I indeed installed TP1, it would be nice if I don't have to reinstall later in time so I'm not longer working on a technical preview? 
Or would I have to start from scratch with a new iso version to be up-to-date?

Grtz and tx

**Comment by toliaqat** [comment]
Technical preview might not get updated automatically with the new version. And you would have to re-install new TP because there are expected changes that might not be compatible with two TPs. The ISO I provided to you is from our nightly build.
I should not have suggested to change photon.repo to point to new server because that path is not tested and we don't know what is going to break if you start update process from there. This path definitely not recommended for TP1.

Downloading the bridge-utils-rpm should have the simplest solution to have bridge-utils working in your TP1 installation, for now.
Or may be start using the ISO 1.0.0-195 to experiment on the latest build repo.

**Comment by willemdh** [comment]
Hmm I guess it's too late for that. I'll see if I can start from scratch with the 1.0.0-195 iso. I hope I don't have to start from scratch too much.. :) Is there (contrary to the TP1) an upgrade process for the 1.0.0-195 release to later versions? Or would I have to start from scratch again when a newer version is released?

**Comment by toliaqat** [comment]
We are working on that story and by 1.0 we will definitely have it squared to upgrade from 1.0 to next version.

**Comment by willemdh** [comment]
Ok, Guess I'm going to wait until upgrading is officially supported.
