### ISSUE TITLE
Photon ISO image does not boot

### ISSUE THREAD

**Issue by dnaeon** [vmware/photon#18]
Just trying out the ISO image from https://dl.bintray.com/vmware/photon/iso/1.0TP1/x86_64/ and it fails to boot properly.

![photon-boot](https://cloud.githubusercontent.com/assets/242827/7296694/98707640-e9ca-11e4-97ae-6d5579e47c77.jpg)

**Comment by snambakam** [comment]
i just tried this on Fusion-7.1.1 and on VMware Workstation 11.1.0 successfully.

**Comment by gregmmurray** [comment]
Without any other information, I suspect that you might have a corrupt ISO. Can you, please, redownload the ISO and, after confirming that you've got a valid copy?

If it helps, you can verify the ISO with sha1sum. Hash is here - https://bintray.com/artifact/download/vmware/photon/iso/1.0TP1/x86_64/photon-1.0TP1.iso.sha1sum

**Comment by mbassiouny** [comment]
Also, can you make sure you have the correct boot order.

**Comment by dnaeon** [comment]
Will test again today and see how it goes.

**Comment by dnaeon** [comment]
After several attempts I've finally managed to get the correct ISO image, so closing this issue. Thanks!
