### ISSUE TITLE
In the older source code version while building rpms i am getting the following errors

### ISSUE THREAD

**Issue by Andrew219** [vmware/photon#194]
Building package...... zlib
Spec file for package: zlib  is  /home/photon/nss-nspr-rpm/photon/SPECS/zlib/zlib.spec
Source path :zlib-1.2.8.tar.xz Source filename: /home/photon/nss-nspr-rpm/photon/stage/SOURCES/zlib-1.2.8.tar.xz
Building RPM... /usr/src/photon/SPECS/zlib.spec
Building rpm is failed
Building rpm is failed /usr/src/photon/SPECS/zlib.spec

Detailed logs show:-

gcc -O3  -D_LARGEFILE64_SOURCE=1 -DNO_STRERROR -DNO_vsnprintf -DHAVE_HIDDEN -o example64 example64.o -L. libz.a
/tools/lib/gcc/i686-pc-linux-gnu/4.8.2/../../../../i686-pc-linux-gnu/bin/ld: cannot find crt1.o: No such file or directory
/tools/lib/gcc/i686-pc-linux-gnu/4.8.2/../../../../i686-pc-linux-gnu/bin/ld: cannot find crti.o: No such file or directory
/tools/lib/gcc/i686-pc-linux-gnu/4.8.2/../../../../i686-pc-linux-gnu/bin/ld: cannot find -lc
/tools/lib/gcc/i686-pc-linux-gnu/4.8.2/../../../../i686-pc-linux-gnu/bin/ld: cannot find crtn.o: No such file or directory
collect2: error: ld returned 1 exit status
Makefile:170: recipe for target 'example' failed
make: *** [example] Error 1
make: *** Waiting for unfinished jobs....
/tools/lib/gcc/i686-pc-linux-gnu/4.8.2/../../../../i686-pc-linux-gnu/bin/ld: cannot find crt1.o: No such file or directory
/tools/lib/gcc/i686-pc-linux-gnu/4.8.2/../../../../i686-pc-linux-gnu/bin/ld: cannot find crti.o: No such file or directory
/tools/lib/gcc/i686-pc-linux-gnu/4.8.2/../../../../i686-pc-linux-gnu/bin/ld: cannot find -lc
/tools/lib/gcc/i686-pc-linux-gnu/4.8.2/../../../../i686-pc-linux-gnu/bin/ld: cannot find crtn.o: No such file or directory
collect2: error: ld returned 1 exit status
Makefile:182: recipe for target 'example64' failed
make: *** [example64] Error 1
/tools/lib/gcc/i686-pc-linux-gnu/4.8.2/../../../../i686-pc-linux-gnu/bin/ld: cannot find crt1.o: No such file or directory
/tools/lib/gcc/i686-pc-linux-gnu/4.8.2/../../../../i686-pc-linux-gnu/bin/ld: cannot find crti.o: No such file or directory
/tools/lib/gcc/i686-pc-linux-gnu/4.8.2/../../../../i686-pc-linux-gnu/bin/ld: cannot find -lc
/tools/lib/gcc/i686-pc-linux-gnu/4.8.2/../../../../i686-pc-linux-gnu/bin/ld: cannot find crtn.o: No such file or directory
collect2: error: ld returned 1 exit status
Makefile:173: recipe for target 'minigzip' failed
make: *** [minigzip] Error 1
error: Bad exit status from /var/tmp/rpm-tmp.1pLlZp (%build)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.1pLlZp (%build)

**Comment by mbassiouny** [comment]
I am not sure what's going on here, it might be depending on the host system you are building from. Can you please git pull to the latest, and let us know if you have any problems.
