### ISSUE TITLE
How to set a static ip?

### ISSUE THREAD

**Issue by netw0rm** [vmware/photon#205]
I want to use a static ip, but it dosen't work.

**Comment by vinaykul** [comment]
You can assign a static IP to an interface by replacing the /etc/systemd/network/10-dhcp-en.network file with 10-static-en.network file, and specifying the IP address in [Address] section. It should pick up the static IP on next boot. For details, please review: http://www.linuxfromscratch.org/lfs/view/systemd/chapter07/network.html

**Comment by grantcurell** [comment]
Warning: The file you create must be readable by other in order to work.

chmod o+r /etc/systemd/network/*
