### ISSUE TITLE
Photon build needs to supply OVA, ISO and docker image from same build

### ISSUE THREAD

**Issue by jivkodobrev** [vmware/photon#224]
ESXcloud build process needs to be able to pick up particular builds from Photon:
- ISO and OVA
- docker container image

The container image can be in docker hub (with a tag ID) or exported as TAR in the build location. We need to use the same build number for the OVA/ISO *AND* the container image.

The container image needs to be minimal, no kernel necessary

**Comment by toliaqat** [comment]
Following creates a minimal docker image without any extra stuff in it.

```
sudo make docker-image
```

docker image is available from docker hub.
```
docker run -it vmware/photon
```
