### ISSUE TITLE
systemd-networkd-wait-online hangs with host-only network on VMware Workstation

### ISSUE THREAD

**Issue by higebu** [vmware/photon#24]
systemd-networkd-wait-online hangs, when I add at least one host-only network to photon vm.

![systemd-networkd-wait-online-hanging](https://cloud.githubusercontent.com/assets/733288/7331395/61004940-eb48-11e4-9d8d-369a8a71c0f6.png)

**Comment by higebu** [comment]
My network settings is below:

```
[Match]
Name=eth*

[Network]
DHCP=v4
```

**Comment by ailispaw** [comment]
@higebu 
How about this? https://github.com/vmware/vagrant-guests-photon/pull/1

**Comment by higebu** [comment]
@ailispaw I didn't use Vagrant. But I'll check it.

**Comment by ailispaw** [comment]
@higebu You're right.
I still see as below. It doesn't seem to work with DHCP well.

```
$ systemctl list-units | grep systemd-networkd-wait-online
systemd-networkd-wait-online.service                                                                 loaded activating start     start Wait for Network to be Configured
$ networkctl list
IDX LINK             TYPE               OPERATIONAL SETUP
  1 lo               loopback           carrier     unmanaged
  2 eth0             ether              routable    configured
  3 eth1             ether              routable    configured
  4 eth2             ether              routable    configuring
  5 docker0          ether              routable    unmanaged
  7 veth77754ee      ether              degraded    unmanaged

6 links listed.
```

**Comment by ailispaw** [comment]
I applied @higebu 's https://github.com/higebu/photon/releases/download/systemd-216-2/systemd-216-2.x86_64.rpm to my box.
It works good for me.
Thanks.

**Comment by ppadmavilasom** [comment]
@higebu: systemd is updated to 228 in rc.  Please reopen if you see this issue in rc.
