### ISSUE TITLE
Please tell me VMware Photon logo image licensing

### ISSUE THREAD

**Issue by ysaotome** [vmware/photon#28]
I want to know the license of VMware Photon logo.

VMware Photon github.io landing pages logo image is GPLv2 License ?
https://github.com/vmware/photon/tree/gh-pages/assets/img

**Comment by ericgray** [comment]
Thanks for checking - I just verified that the logo itself is not licensed under GPLv2.

**Comment by ysaotome** [comment]
Thank you very much for feedbak.
Do you know about the logo use policy when describing the VMware Photon on blogs and articles?
