### ISSUE TITLE
"Links" in Getting Started guides are not clickable

### ISSUE THREAD

**Issue by michaelklishin** [vmware/photon#3]
Links in the PDF doc guides, e.g. [this Fusion one](http://vmware.github.io/photon/assets/files/getting_started_with_photon_on_vmware_fusion.pdf), are just blue text, not clickable.

**Comment by RobbieJVMW** [comment]
Thanks, slight problem with PDF conversation an updated doc with links will be appearing soon.

**Comment by drukelly** [comment]
I noticed when viewing the PDFs in Github's viewer, the links get suppressed. But when downloaded and opened with a PDF reader (Preview, Acrobat, etc.), the highlighted links work as intended.

**Comment by gregmmurray** [comment]
We've updated the PDFs and validated the links in several PDF viewers; as @drukelly mentioned, only the embedded Github viewer isn't rendering the PDF links properly. We'll investigate.
