### ISSUE TITLE
Config file based installation options

### ISSUE THREAD

**Issue by trodemaster** [vmware/photon#31]
I have spent some time customizing the photon template for use with our packer image building process. One thing that sticks out is that the installer is using keyboard input only to setup the install options. This is problematic as it relies on time based actions. 

Adding a kickstart style config file that can be downloaded from a http source is ideal in my mind. It doesn't necessarily have to be kickstart but would need to support the following options. 

* Accept EULA
* Disk selection --firstdisk
* OS flavor
    Micro
    Minimal
    Full

* Hostname
* IP Config
    Static or DHCP with DNS settings and such

* User Config
    setting root password
    enable ssh login for root

**Comment by mbassiouny** [comment]
Thank you very much for the feedback. We have this feature in our list of TODOs. Will keep you updated!

**Comment by frapposelli** [comment]
Strong :+1: on this

**Comment by jacobludriks** [comment]
agreed, this would be great!

**Comment by mcphailtom** [comment]
Absolutely a great idea!

**Comment by mbassiouny** [comment]
We have preliminary config based unattended installation, I am writing an md guide file of the supported configs. I will update the thread soon.

**Comment by mbassiouny** [comment]
Please checkout https://github.com/vmware/photon/blob/dev/docs/kickstart.md and https://github.com/vmware/photon/blob/dev/docs/PXE-boot.md
