### ISSUE TITLE
/tmp sizing

### ISSUE THREAD

**Issue by danwent** [vmware/photon#32]
Hi folks, I was installing lattice on photon, which writes a lot of stuff to /tmp .  However, in my default install of photon, /tmp is sized at 174M, and the lattice installer runs out of space in /tmp, despite my main partition having plenty of free space.  

Changing the size of the /tmp directory did not seem to be as simple as changing /etc/fstab .  Grepping around it seemed like maybe I could change /etc/mtabs , but the file was read-only, so I wasn't sure if it was auto-generated.   

So two questions: 
- why is the default for /tmp so small? 
- what is the recommended route to change this?  

thanks

**Comment by fivetanley** [comment]
I hate to +1, but I'm having this issue as well when writing ruby or node apps, which often can have a few hundred megabytes of dependencies. It would be great if the partition were larger or configurable.

**Comment by fivetanley** [comment]
@danwent I found this workaround on the VMWare forums:

> You can use this simple command to change the size of "/tmp" partition.
> `umount /tmp`
> `mount -t tmpfs -o size=10G tmpfs /tmp`
> change "size=10G"  to increase the size of the partition

https://communities.vmware.com/thread/509670
