### ISSUE TITLE
Bootable ISO

### ISSUE THREAD

**Issue by victorock** [vmware/photon#33]
There is no minimal bootable iso created to be reused with boot2docker and/or docker-machine.
Is there any plan to create a bootable ISO as part of make process?
Is there any plan to publish it with the installation ISO?

If it is a worth suggestion, please let me know if any help is required.

Sincerely,
Victor da Costa

**Comment by frapposelli** [comment]
I think it's an interesting suggestion, @toliaqat what do you think?

**Comment by toliaqat** [comment]
I agree on this and will be looking at the build scripts to generate minimal ISOs as output along side with full ISO.

**Comment by victorock** [comment]
@frapposelli the idea is to have a seamless integration with docker-machine.
Another step to consider is to submit a request for docker-machine team to change the utils/b2d.go to have their functions accepting additional parameters/fields, where we can specify the location to search for the latest ISO. With this approach no more requirements to have the ISO URL hardcoded in the VMware driver. (?)

**Comment by frapposelli** [comment]
@victorock I'm the maintainer for docker-machine VMware drivers, if we switch to photon (we still have gaps to be filled) I'll take care of the changes.

**Comment by toliaqat** [comment]
Following command now creates a live iso. Use it to boot photon from cdrom. After booting it cannot install on harddisk though.

```
sudo make live-iso
```

**Comment by ppadmavilasom** [comment]
In review with team, agree that this is a nice to have. There is no active development towards this feature.

**Comment by ppadmavilasom** [comment]
Not supporting this at the moment. PRs are welcome.
