### ISSUE TITLE
missing localhost entry in /etc/hosts

### ISSUE THREAD

**Issue by mgolfieri** [vmware/photon#364]
While installing photon-1.0TP2.ova on vCA (static-manual IP), I realized /etc/hosts doesn't sport the 127.0.0.1 localhost.localdom localhost entry.

**Comment by ppadmavilasom** [comment]
Working on adding this entry

**Comment by mgolfieri** [comment]
txs! And related IPv6 entry as well for ::1 if possible.

**Comment by ppadmavilasom** [comment]
127.0.0.1 localhost entry is added.
