### ISSUE TITLE
Calling `sudo make clean` in a broken build wipes all nodes in host's /dev/

### ISSUE THREAD

**Issue by sofar** [vmware/photon#378]
I had a `sudo make iso` build crash, and decided to `sudo make clean`. Because several mount points were still live the system recursively removed all the files in my systems' /dev/:

~/photon$ sudo make clean
...lots of failed `rm` output...
~/photon$ ls /dev
memory_bandwidth  pts

**Comment by sharathjg** [comment]
There was a check added to unmount the mounts in the chroot before removing the directory. however if you have fakeroot-ng you could build without sudo. That path is not well documented though.
