### ISSUE TITLE
Installer swallows Python exceptions

### ISSUE THREAD

**Issue by pedantic-git** [vmware/photon#383]
When something goes wrong with the installation (for example, the remote RPM dir specified in the `repo` parameter doesn't exist), the installer swallows the exception.

The code is [here](https://github.com/vmware/photon/blob/master/installer/installer.py#L86).

The `exit_gracefully()` method dumps the systemd logs to a file but the python exception name and stacktrace are lost, which means cases such as the above are not logged at all and are quite hard to debug.

**Comment by mbassiouny** [comment]
Thanks for the notice, currently we do not dump this exception to the same file, however you can see the python exception at /var/log/installer. We will work on having a consolidated persistent 1 log file.

**Comment by pedantic-git** [comment]
Hi Mahmoud

`/var/log/installer` is the place where I see the systemd logs (i.e. `modules.commons.LOG_FILE_NAME`).

As far as I can see, the python exception is completely swallowed and not logged anywhere. It looks like the "except" handler calls `self.exit_gracefully(None, None)` without passing the exception object to anything.

**Comment by mbassiouny** [comment]
It's confusing here, there are 2 files here, "/var/log/installer" and "/var/log/installer.log".  If you got a python exception, you will find it in "/var/log/installer" file.

**Comment by pedantic-git** [comment]
Ah! I understand. But sadly this didn't happen for any of the Python exceptions I encountered. There was no `/var/log/installer` file.

Are you sure this behaviour is not broken in TP2? The exception handler in [installer.py (line 86)](https://github.com/vmware/photon/blob/master/installer/installer.py#L86) looks like it consumes the exception without assigning it or passing it to anything.

**Comment by mbassiouny** [comment]
Sorry for delayed response. I missed that. Can you please provide me with the environment that you got that so I can see what's going on?

**Comment by pedantic-git** [comment]
Hi Mahmoud

Try setting up a photon installation with a PXE boot (as described [here](https://blogs.vmware.com/vsphere/2015/08/new-capabilities-in-project-photon-os-technical-preview-2-tp2.html) and in the linked article [here](http://www.vcritical.com/2015/08/new-network-and-scripted-install-features-in-photon-os-tp2/)).

If you set the `repo=` line in your kernel arguments to an https:// URL that has an invalid certificate (e.g. the IP address of the server) the installer will crash with the "Opps, Installer got interrupted." message (see #384) and drop you to a shell.

At this point, the Python exception (probably containing the string `CERTIFICATE_VERIFY_FAILED` is swallowed by the [except block](https://github.com/vmware/photon/blob/master/installer/installer.py#L86) and there is no `/var/log/installer` file generated.

Please let me know if you need anything else to help debug this!

**Comment by mbassiouny** [comment]
Yes, you are correct. Thank you for letting us know. @xiaolin-vmware please get a fix for that.

**Comment by xiaolin-vmware** [comment]
This issue is fixed in commit 34dfc7d. If you got a python exception, you will find it in "/var/log/installer.log" file.
