### ISSUE TITLE
Postinstall chroot has no resolv.conf (and hence no DNS)

### ISSUE THREAD

**Issue by pedantic-git** [vmware/photon#385]
When running the installer in pxe+kickstart mode, the machine that's booted from the ramdisk has an `/etc/resolv.conf` file that's autogenerated from the DHCP information.

As soon as the postinstall runs, the installer chroots to the target disk which has no resolv.conf file, meaning that any operations run inside the chroot that depend on DNS operations fail.

A simple workaround to this would be to copy the `/etc/resolv.conf` from the ramdisk to the target disk at the start of the postinstall. I _think_ NetworkManager will replace this file on first boot anyway so there is no harm in leaving it there at the end of the postinstall script.

I've tested this fixes the postinstall issues by artificially creating a hardcoded `/etc/resolv.conf` at the start of my postinstall script but it would be better if I didn't have to do this.

**Comment by ppadmavilasom** [comment]
@xiaolin-vmware looks like this issue was fixed. can you please confirm

**Comment by xiaolin-vmware** [comment]
It is fixed in commit 2da1ce6.
