### ISSUE TITLE
Issues with Zookeeper install on TP2

### ISSUE THREAD

**Issue by mattolenik** [vmware/photon#392]
When running "tdnf install -y zookeeper" on a new TP2 VM I see the following error:

> Testing transaction
> Running transaction
> chown: invalid user: 'zookeeper:hadoop'
> /var/tmp/rpm-tmp.m6td4d: line 7: -p: command not found
> 
> Complete!

**Comment by vinaykul** [comment]
We have a fix for this in our dev branch, along with another fix for the config file path. I'll close this issue when we have the fix in the master branch. The next release should have this fixed. 

Zookeeper package does install despite this issue. 
To run it, please use the following workaround:
# source /etc/profile.d/java-exports.sh
# useradd --shell /bin/bash -M -r --groups hadoop --home /usr/share/zookeeper zookeeper
# /sbin/update-zookeeper-env.sh --prefix=/usr --conf-dir=/etc/zookeeper --log-dir=/var/log/zookeeper --pid-dir=/var/run --var-dir=/var/zookeeper
# zkServer.sh start

**Comment by ppadmavilasom** [comment]
Closing this as resolved in rc. However #452 is currently affecting zookeeper and a fix is on the way.
