### ISSUE TITLE
Cannot start container: no space left on device

### ISSUE THREAD

**Issue by caglar10ur** [vmware/photon#394]
We occasionally get the error reported in https://github.com/opencontainers/runc/issues/133 

The kernel bug already fixed with https://github.com/torvalds/linux/commit/24ee3cf89bef04e8bc23788aca4e029a3f0f06d9 

We need to patch the default kernel with this patch (ESX optimized version works fine as 4.2.0 already contains the patch)

**Comment by YustasSwamp** [comment]
Default kernel was updated to 4.2.0 recently.
https://github.com/vmware/photon/commit/57f94ab762f4df448ff12e415caa4c325f0e2287
