### ISSUE TITLE
nano missing from minimal build

### ISSUE THREAD

**Issue by drothlis** [vmware/photon#396]
Commit 5d05cfcc refactored the way the list of default packages are defined, but also removed nano from the minimal build, perhaps unintentionally.

This breaks a lot of documentation out there, including the [faq](https://github.com/vmware/photon/wiki/Frequently-Asked-Questions#q-why-vivim-is-not-working-in-minimal-photon).

**Comment by suezzelur** [comment]
nano has been replaced by vi as the default in minimal builds. nano is still part of the full installation.
