### ISSUE TITLE
Unable to see more information

### ISSUE THREAD

**Issue by Muralidharsetty** [vmware/photon#399]
When I do "docker inspect" command, The result is more than screen size. not able to see complete information. Snapshots are attached.
Not just "docker inspect" command, It doesn't allow to view information which is off the screen.
I am using "photon OS" in vmware player. There should be someway to scroll up.

![capture](https://cloud.githubusercontent.com/assets/5921854/11269289/1830557e-8edc-11e5-9a3a-61654334be4d.PNG)
![capture1](https://cloud.githubusercontent.com/assets/5921854/11269290/1851e180-8edc-11e5-83ca-9c7a25eed83c.PNG)

**Comment by ppadmavilasom** [comment]
you could use <command> | less
Shift + mouse scroll might work for up /down from mac. 
If nothing else, ssh via your favorite terminal

**Comment by Muralidharsetty** [comment]
Ohh Yes, "| less" works. I don't know what was running in mind, I forgot that.
Thank you.
