### ISSUE TITLE
Cannot install Photon OS

### ISSUE THREAD

**Issue by bernardoVale** [vmware/photon#401]
I'm unable to install Photon OS on VSphere 6.

I've tried with both minimum and full .iso

After clicking on "Install" This occour:
<img width="723" alt="screen shot 2015-11-23 at 20 36 25" src="https://cloud.githubusercontent.com/assets/1888123/11352209/37748bdc-9222-11e5-9bfa-a11e82866be5.png">

After that the vm start to reboot and then infinity loop.
<img width="735" alt="screen shot 2015-11-23 at 20 36 31" src="https://cloud.githubusercontent.com/assets/1888123/11352210/37a7547c-9222-11e5-9f47-d1eb06dd6440.png">

**Comment by dthaluru** [comment]
Please make sure to set the memory above 700M..Then you won't see this issue

**Comment by dthaluru** [comment]
Please make sure to set the memory above 700M..Then you won't see this issue

**Comment by bernardoVale** [comment]
@dthaluru, it's working now, thanks for your help.

I've followed this VMware guide: https://vmware.github.io/photon/assets/files/getting_started_with_photon_on_vsphere.pdf and in one of the images the memory it's seted to 384MB. 

*The recommended virtual hardware settings for your Photon VM are heavily dependent upon container load you intend to run
within Photon. To start, we recommend 2 vCPU, 384MB memory, 20GB hard disk. Any unwanted devices should be removed.
Be sure to mount the Photon ISO on the CD/DVD Drive and click Connect At Power On.*

It will be nice if VMware could update this guide. For future generations...
