### ISSUE TITLE
Python2 package is broken

### ISSUE THREAD

**Issue by mattolenik** [vmware/photon#405]
"tdnf install python2" isn't good enough. When I ran that and then attempted to run python, I got:

```
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
ImportError: No module named site
```

It was only after installing some other Python library, which installed "python2-libs" as a dependency, that it began to work. This seems to be the root cause, as the python2.7/site-packages dir is empty without python2-libs, but python2 does not depend on python2-libs

**Comment by ppadmavilasom** [comment]
@mattolenik is python2-libs not getting installed as a dependency for python2?

**Comment by mattolenik** [comment]
No, it is not. Looking at the package spec, the dependency is missing: https://github.com/vmware/photon/blob/master/SPECS/python2/python2.spec

**Comment by ppadmavilasom** [comment]
fixed in rc.
