### ISSUE TITLE
Docker not reading Docker config file

### ISSUE THREAD

**Issue by mattolenik** [vmware/photon#414]
The tdnf spec for Docker does not include reading /etc/default/docker for config. As a result all Docker configuration is ignored. This is critical: right now there is no way to use Docker on PhotonOS unless you want default config options.

Here's a sample init script for Upstart. https://github.com/docker/docker/blob/master/contrib/init/upstart/docker.conf

Note line 42, where it places DOCKER_OPTS on the command line to start Docker after sourcing them from /etc/default/docker.

Edit: Proper fix in systemd is to use "EnvironmentFile" option set to "-/etc/default/docker" which will read the file only if it exists. Then DOCKER_OPTS can just be passed on the next line. Note that the "reference" systemd file in the official docker repo is incorrect and does not implement this.

**Comment by ppadmavilasom** [comment]
https://github.com/vmware/photon/commit/8423042f48bc28ebd70ee344edc250bca46de353
Will be in GA.
