### ISSUE TITLE
Cannot install net-tools

### ISSUE THREAD

**Issue by knesenko** [vmware/photon#415]
yum install net-tools gives the following error:
                     
Downloading Packages:
net-tools-1.60-2.ph1tp2.x86_64.rpm                                                                                                                    | 167 kB  00:00:01     
Running Transaction Check
Running Transaction Test

Transaction Check Error:
  file /sbin/ifconfig from install of net-tools-1.60-2.ph1tp2.x86_64 conflicts with file from package inetutils-1.9.2-2.ph1tp2.x86_64

Error Summary

**Comment by gregmmurray** [comment]
yum or tdnf?

fwiw, I get an error on tdnf, so this looks like it could be a problem with the package in the repo ...

**Comment by ppadmavilasom** [comment]
inetutils is being obsoleted - replaced by net-tools and iputils. So you will have success if you remove inetutils and install net-tools. This is probably caused by a net-tools spec that does not do the obsoletes correctly.

**Comment by knesenko** [comment]
@ppadmavilasom so Photon should be shipped with net-tools instead of inetutils by default ?

**Comment by ppadmavilasom** [comment]
tp2 has inetutils i believe. next version will have inetutils obsoleted by net-tools and iputils.
