### ISSUE TITLE
Vagrant box for TP2 is not working

### ISSUE THREAD

**Issue by hvram1** [vmware/photon#416]
I am using
* Windows 8.1 Pro 64bit 
* VirtualBox r 4.2.12.r84980  
* Vagrant version 1.7.3 . 

When I run the commands 

     vagrant init vmware/photon 
     vagrant up 

I get the following error

     VBoxManage.exe: error: 'Linux_64' is not a valid Guest OS type
     Interpreting C:\Users\xxx\.vagrant.d\boxes\vmware-VAGRANTSLASH-photon\1.1.0virtualbox\box.ovf...
     VBoxManage.exe: error: 'Linux_64' is not a valid Guest OS type
     VBoxManage.exe: error: Details: code E_INVALIDARG (0x80070057), component VirtualBox,  Interface IVirtualBox, callee IAppliance
     VBoxManage.exe: error: Context: "Interpret" at line 330 of file VBoxManageAppliance.cpp

**Comment by hvram1** [comment]
I had a colleague of mine try with VirtualBox 4.3 and this works without any problem . Can you add a dependency on this please ?

**Comment by frapposelli** [comment]
@hvram1 not sure that it's possible to add a dependency on a specific version of Virtualbox in our Vagrantfile (at least not without convoluted ifs)

**Comment by hvram1** [comment]
Sorry I mean add that as a dependency in the README.md
