### ISSUE TITLE
no space left on device - Using Photon OS, Tech Preview 2 - OVA

### ISSUE THREAD

**Issue by ccit-spence** [vmware/photon#417]
Using ```Photon OS, Tech Preview 2 - OVA``` from http://vmware.github.io/photon/

vSphere 6.0u1

I am able to get the ```vmwarecna/nginx``` to work.  Trying anything larger seems to fail.  

Example: ```docker run -d -p 5672:5672 -p 15672:15672 --net=host --name rabbitmq rabbitmq:3.5.6-management```

Results:

```
Error pulling image (3.5.6-management) from docker.io/library/rabbitmq, 
mkdir /var/lib/docker/overlay/4bae760d9b2f8e68203c5717c8ec91ca6bdbaeee1be7199a36b1c1d55011dbError 
pulling image (3.5.6-management) from docker.io/library/rabbitmq, 
mkdir /var/lib/docker/overlay/4bae760d9b2f8e68203c5717c8ec91ca6bdbaeee1be7199a36b1c1d55011dbce/tmproot828479203/usr/lib/tcltk/x86_64-linux-gnu/tk8.6: no space left on device
```

**Comment by gregmmurray** [comment]
How large does vSphere report the disk to be?

I just ran your example command and it completed successfully on Photon OS TP2 OVA fresh install on Workstation.

**Comment by sharathjg** [comment]
the ova itself will have a fixed disk size. if you need to increase the size of the disk you would have to install from the CD in a vm with a custom hard disk size.
