### ISSUE TITLE
Binutils dependencies are broken

### ISSUE THREAD

**Issue by mattolenik** [vmware/photon#420]
I ran into an issue with the version of flex in Photon, so decided to uninstall it with tdnf and build from source. However when I did "tdnf remove flex," it also wanted to remove bison, binutils, and binutils-dev. Binutils does not include flex and does not have a dependency on it. Strangely, I can uninstall binutils and flex is still there. Removing flex also tries to remove bison, which makes no sense. Installing bison also installs flex, which again, makes no sense. These are all independent packages and I'm not sure why there are dependencies between them. I have never seen these dependencies in any other distro. It makes it very difficult to get the packages on my system configured the way I want.

**Comment by ppadmavilasom** [comment]
binutils provides /usr/bin/ar which depends on flex so thats going to stay (removing flex is going to continue to remove binutils and binutils-dev if they are installed)

bison does not need a require for flex so i will remove that in the spec.

**Comment by ppadmavilasom** [comment]
Commit https://github.com/vmware/photon/commit/39a9900831545a85b626db61b3ac25b3059987ea
Will be in GA
