### ISSUE TITLE
[Question] Codebase is mostly Python ?

### ISSUE THREAD

**Issue by singam-sanjay** [vmware/photon#426]
How is that the OS is mostly written in Python with C contributing only a small amount ?

**Comment by YustasSwamp** [comment]
This repo contains build system (in Python) and SPEC files (rules from where to fetch sources and how to build them).
99% sources will be fetched from outside (bintray.com) during the build process.

**Comment by singam-sanjay** [comment]
Thank You @YustasSwamp
