### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by scriptjs** [vmware/photon#427]
I am confused about the licensing and seeking clarification. From the main page it appears the source code of the OS is completely open source and under the various open source licenses provided in this repo. Photon is clearly being promoted as an open source project not simply a project that uses some open source code.

That said, the ISO is distributed by vmware under the trademark Photon and is covered under a technical preview license. The Technical Preview License is a mix of a grant of an LGPL license to the software but limits rights granted under the LGPL by inclusion of additional terms in the preview license. I do not believe it meets with the LGPL open source license to revoke rights granted under its license by combining it with the additional terms under the Preview License.

```
For example, if you distribute copies of the library, whether gratis or for a fee, you must give the recipients all the rights that we gave you. You must make sure that they, too, receive or can get the source code. If you link other code with the library, you must provide complete object files to the recipients, so that they can relink them with the library after making changes to the library and recompiling it. And you must show them these terms so they know their rights.

We protect your rights with a two-step method: (1) we copyright the library, and (2) we offer you this license, which gives you legal permission to copy, distribute and/or modify the library.

To protect each distributor, we want to make it very clear that there is no warranty for the free library. Also, if the library is modified by someone else and passed on, the recipients should know that what they have is not the original version, so that the original author's reputation will not be affected by problems that might be introduced by others.

Finally, software patents pose a constant threat to the existence of any free program. We wish to make sure that a company cannot effectively restrict the users of a free program by obtaining a restrictive license from a patent holder. Therefore, we insist that any patent license obtained for a version of the library must be consistent with the full freedom of use specified in this license.
```
In the LGPL, the rights of modification and distribution are fully granted and cannot be restricted as well:
```
1. You may copy and distribute verbatim copies of the Library's complete source code as you receive it, in any medium, provided that you conspicuously and appropriately publish on each copy an appropriate copyright notice and disclaimer of warranty; keep intact all the notices that refer to this License and to the absence of any warranty; and distribute a copy of this License along with the Library.

You may charge a fee for the physical act of transferring a copy, and you may at your option offer warranty protection in exchange for a fee.

2. You may modify your copy or copies of the Library or any portion of it, thus forming a work based on the Library, and copy and distribute such modifications or work under the terms of Section 1 above, provided that you also meet all of these conditions:

a) The modified work must itself be a software library.
b) You must cause the files modified to carry prominent notices stating that you changed the files and the date of any change.
c) You must cause the whole of the work to be licensed at no charge to all third parties under the terms of this License.
d) If a facility in the modified Library refers to a function or a table of data to be supplied by an application program that uses the facility, other than as an argument passed when the facility is invoked, then you must make a good faith effort to ensure that, in the event an application does not supply such function or table, the facility still operates, and performs whatever part of its purpose remains meaningful.
(For example, a function in a library to compute square roots has a purpose that is entirely well-defined independent of the application. Therefore, Subsection 2d requires that any application-supplied function or table used by this function must be optional: if the application does not supply it, the square root function must still compute square roots.)

These requirements apply to the modified work as a whole. If identifiable sections of that work are not derived from the Library, and can be reasonably considered independent and separate works in themselves, then this License, and its terms, do not apply to those sections when you distribute them as separate works. But when you distribute the same sections as part of a whole which is a work based on the Library, the distribution of the whole must be on the terms of this License, whose permissions for other licensees extend to the entire whole, and thus to each and every part regardless of who wrote it.

Thus, it is not the intent of this section to claim rights or contest your rights to work written entirely by you; rather, the intent is to exercise the right to control the distribution of derivative or collective works based on the Library.

In addition, mere aggregation of another work not based on the Library with the Library (or with a work based on the Library) on a volume of a storage or distribution medium does not bring the other work under the scope of this License.
```

My confusion comes from this. Either Photon as distributed under the Technical Preview License cannot be open source  or it is because of the LGPL license grant. It is a perplexing mix since it is not possible to revoke rights granted under the LGPL while simultaneously restricted them. I hate this kind of thing. I am not a lawyer but a developer and I don't like this level of obfuscation when making decisions about software.

To get to an open source project that I can use without issues, I am assuming that if I fork and make modifications directly with the sources and create a modified OS, build and distribute an ISO under a name of my choosing for any purpose, I am bound only by the open source licenses accompanying the software and not by the technical preview license. Can someone at vmware please clarify this for me?

At this point my interest is in modifying the packages and producing various forms of machine images manipulated using qemu for my own purposes. So I have a use case for myself I simply wish to run with.

**Comment by gregmmurray** [comment]
Thanks for pointing out the discrepancy and resulting confusion. We're looking at this, now, and will get back to you.

**Comment by gregmmurray** [comment]
@scriptjs Thanks for your patience and sorry about the confusion. 

After conferring with the right folks, I think we can straighten this out for you with just a few key points. 

1.	The Tech Preview license governs the binary version of PhotonOS.  
2.	The Tech Preview license provides that any open source code included in PhotonOS is licensed per the terms of the respective open source package.
3.	The LGPL license does not prohibit licensing a binary version of PhotonOS.  It simply requires that the binary version be distributed along with the corresponding source which we do – the source is available on the VMware github site.
4.	Licensing the binary version of code that is open sourced is done by other companies such as Red Hat and Novell.
5.	Regarding the question you pose at the end of your query, you are correct – you are free to fork the PhotonOS source code, modify the sources and create a modified operating system and then build and distribute an ISO under a name of your choosing.

Does that help? Please let me know if you have additional questions or this isn't clear.

**Comment by scriptjs** [comment]
@gregmmurray I appreciate your reply. I will review this again in this context and come back to you if I have further questions. It does indicate software in object form excluding open source software so this helps substantially. Many thanks.
