### ISSUE TITLE
Httpd can not start after default installation

### ISSUE THREAD

**Issue by gsliu** [vmware/photon#430]
I install photon from full iso with default configuration, but httpd failed to start.

root [ ~ ]# systemctl start httpd.service
Job for httpd.service failed. See 'systemctl status httpd.service' and 'journalctl -xn' for details.
root [ ~ ]# journalctl -xn
-- Logs begin at Tue 2016-04-05 01:28:35 UTC, end at Tue 2016-04-05 01:30:15 UTC. --
Apr 05 01:30:14 photon-gengshengl systemd[1]: Cannot add dependency job for unit dracut-shutdown.service, ignoring: Unit dracut-shutdown.service failed to loa
Apr 05 01:30:14 photon-gengshengl httpd[356]: (20014)Internal error (specific information not available): AH00058: Error retrieving pid file logs/httpd.pid
Apr 05 01:30:14 photon-gengshengl httpd[356]: AH00059: Remove it before continuing if it is corrupted.
Apr 05 01:30:14 photon-gengshengl systemd[1]: httpd.service: main process exited, code=exited, status=1/FAILURE
Apr 05 01:30:14 photon-gengshengl systemd[1]: Failed to start The Apache HTTP Server.

**Comment by gsliu** [comment]
So I did some investigation on it, there maybe coupes of problems.

First, the dracut systemd service is not register correctly, the directory level is wrong.

lrwxrwxrwx 1 root root   70 Apr  7 06:00 dracut-shutdown.service -> ../../../../usr/lib/dracut/modules.d/98systemd/dracut-shutdown.service

It should be symbol link like below, after correction of symbol links, dracut  service could be started successfully.

lrwxrwxrwx 1 root root   70 Apr  7 06:00 dracut-shutdown.service -> ../../../../../usr/lib/dracut/modules.d/98systemd/dracut-shutdown.service

Second, by default there's httpd.pid file which causing apache can not be started even without systemd.

root [ /usr ]# apachectl start
(20014)Internal error (specific information not available): AH00058: Error retrieving pid file logs/httpd.pid
AH00059: Remove it before continuing if it is corrupted.

root [ ~ ]# ls /etc/httpd/logs/httpd.pid 
/etc/httpd/logs/httpd.pid

After removing this file, apache finally could be started.

root [ ~ ]# systemctl status httpd.service
* httpd.service - The Apache HTTP Server
   Loaded: loaded (/usr/lib/systemd/system/httpd.service; enabled)
   Active: activating (start) since Thu 2016-04-07 07:42:56 UTC; 5s ago
 Main PID: 750 (httpd)
   CGroup: /system.slice/httpd.service
           |-750 /usr/sbin/httpd -DFOREGROUND
           |-751 /usr/sbin/httpd -DFOREGROUND
           |-752 /usr/sbin/httpd -DFOREGROUND
           `-753 /usr/sbin/httpd -DFOREGROUND

**Comment by ppadmavilasom** [comment]
verified httpd service starts without issues from rc full
