### ISSUE TITLE
Addition of pgbouncer in available packages

### ISSUE THREAD

**Issue by michaelpq** [vmware/photon#433]
pgbouncer is a light-weight, robust connection pooler for PostgreSQL. This is not present
in the available packages. This needs as well libevent as a direct dependent.

**Comment by kaushik229** [comment]
I will be adding this soon.
One done, will update.

Thanks,
Kaushik

**Comment by kaushik229** [comment]
Package added to iso Full version.
Also systemd support files are added but not enabled. Can be controlled with systemctl commands after enabling the service.

**Comment by michaelpq** [comment]
Thanks!

**Comment by suezzelur** [comment]
@michaelpq why was this issue reopened?

**Comment by michaelpq** [comment]
Because at this point the commit relevant to pgbouncer was not showing up yet here. Now it is.
