### ISSUE TITLE
make install failing because of incorrect links in filesystem RPM

### ISSUE THREAD

**Issue by michaelpq** [vmware/photon#434]
While running a simple "make install" I bumped into the following error:
2016-04-08 13:10:12,772 - Toolchain Utils - ERROR - Cannot find filesystem rpm
2016-04-08 13:10:12,773 - Toolchain Utils - ERROR - Unable to build tool chain.
Traceback (most recent call last):
  File "/home/ioltas/git/photon/support/package-builder/ToolChainUtils.py", line 185, in buildCoreToolChainPackages
    self.installToolChainRPMS(chrootID)
  File "/home/ioltas/git/photon/support/package-builder/ToolChainUtils.py", line 201, in installToolChainRPMS
    self.prepareBuildRoot(chrootID)
  File "/home/ioltas/git/photon/support/package-builder/ToolChainUtils.py", line 61, in prepareBuildRoot
    raise Exception("Cannot find filesystem rpm")
Exception: Cannot find filesystem rpm
2016-04-08 13:10:12,778 - PackageManager - ERROR - Unable to build tool chain
2016-04-08 13:10:12,779 - PackageManager - ERROR - Cannot find filesystem rpm
2016-04-08 13:10:12,779 - /home/ioltas/git/photon/stage/LOGS/Main - ERROR - Caught an exception
2016-04-08 13:10:12,780 - /home/ioltas/git/photon/stage/LOGS/Main - ERROR - Cannot find filesystem rpm
Traceback (most recent call last):
  File "/home/ioltas/git/photon/support/package-builder/builder.py", line 128, in main
    buildAPackage(package, listBuildOptionPackages, options.pkgBuildOptionFile, options.buildThreads)
  File "/home/ioltas/git/photon/support/package-builder/builder.py", line 222, in buildAPackage
    pkgManager.buildPackages(listPackages, listBuildOptionPackages, pkgBuildOptionFile, buildThreads)
  File "/home/ioltas/git/photon/support/package-builder/PackageManager.py", line 105, in buildPackages
    self.buildToolChainPackages(listBuildOptionPackages, pkgBuildOptionFile, buildThreads)
  File "/home/ioltas/git/photon/support/package-builder/PackageManager.py", line 99, in buildToolChainPackages
    self.buildToolChain()
  File "/home/ioltas/git/photon/support/package-builder/PackageManager.py", line 96, in buildToolChain
    raise e
Exception: Cannot find filesystem rpm
make: *** [install] Error 1

This is visibly caused by the fact that filesystem is missing from stage/PUBLISHRPMS/x86_64. 

Then if I dig more into the logs for filesystem I find the following error:
+ ln -svfn usr/lib /home/ioltas/git/photon/stage/photonroot/build-core-toolchain/usr/src/photon/BUILDROOT/filesystem-1.0-1.ph1.x86_64/lib
'/home/ioltas/git/photon/stage/photonroot/build-core-toolchain/usr/src/photon/BUILDROOT/filesystem-1.0-1.ph1.x86_64/lib' -> 'usr/lib'
+ ln -svfn usr/bin /home/ioltas/git/photon/stage/photonroot/build-core-toolchain/usr/src/photon/BUILDROOT/filesystem-1.0-1.ph1.x86_64/bin
'/home/ioltas/git/photon/stage/photonroot/build-core-toolchain/usr/src/photon/BUILDROOT/filesystem-1.0-1.ph1.x86_64/bin' -> 'usr/bin'
+ ln -svfn usr/sbin /home/ioltas/git/photon/stage/photonroot/build-core-toolchain/usr/src/photon/BUILDROOT/filesystem-1.0-1.ph1.x86_64/sbin
'/home/ioltas/git/photon/stage/photonroot/build-core-toolchain/usr/src/photon/BUILDROOT/filesystem-1.0-1.ph1.x86_64/sbin' -> 'usr/sbin'
+ ln -svfn run/media /home/ioltas/git/photon/stage/photonroot/build-core-toolchain/usr/src/photon/BUILDROOT/filesystem-1.0-1.ph1.x86_64/media
'/home/ioltas/git/photon/stage/photonroot/build-core-toolchain/usr/src/photon/BUILDROOT/filesystem-1.0-1.ph1.x86_64/media' -> 'run/media'
+ ln -svfn usr/lib /home/ioltas/git/photon/stage/photonroot/build-core-toolchain/usr/src/photon/BUILDROOT/filesystem-1.0-1.ph1.x86_64/lib64
'/home/ioltas/git/photon/stage/photonroot/build-core-toolchain/usr/src/photon/BUILDROOT/filesystem-1.0-1.ph1.x86_64/lib64' -> 'usr/lib'
+ ln -svfn lib /home/ioltas/git/photon/stage/photonroot/build-core-toolchain/usr/src/photon/BUILDROOT/filesystem-1.0-1.ph1.x86_64/usr/lib64
'/home/ioltas/git/photon/stage/photonroot/build-core-toolchain/usr/src/photon/BUILDROOT/filesystem-1.0-1.ph1.x86_64/usr/lib64' -> 'lib'
+ ln -svfn ../lib /home/ioltas/git/photon/stage/photonroot/build-core-toolchain/usr/src/photon/BUILDROOT/filesystem-1.0-1.ph1.x86_64/usr/local/lib64
ln: failed to create symbolic link '/home/ioltas/git/photon/stage/photonroot/build-core-toolchain/usr/src/photon/BUILDROOT/filesystem-1.0-1.ph1.x86_64/usr/local/lib64': No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.TGOPH3 (%install)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.TGOPH3 (%install)

And if I look into stage/photonroot/build-core-toolchain/usr/src/photon/BUILDROOT/filesystem-1.0-1.ph1.x86_64 there are a bunch of creepy links using brackets:
$ ls \{*
{boot,etc:
{opt,sysconfig},home,mnt}
{dev,proc,run:
{media
{var}:
$ ls usr/
lib64  libexec  {,local

This looks rather broken to me. Tests have been done with HEAD at 227bfda.

**Comment by scriptjs** [comment]
hmm, not sure what you are doing. I have no issue building on ubuntu at 227bfda. You do not run a make install. It is simply:

```
sudo make iso
```
or if you want the iso plus all cloud iterations built, ensure you have prerequisite software installed and run

```
sudo make cloud-image all
```

**Comment by michaelpq** [comment]
It doesn't help. Both commands result in the same failure as reported above. Hm. It seems to me that the RPM spec of filesystem is causing things to be broken for me... Looking at it I am seeing the same link patterns in the spec as what I can see in the produced RPM.

**Comment by michaelpq** [comment]
My environment does not like much the use of braces with the install command, and produces directly the paths with the braces. I have never seen this pattern path pattern to be used with install up to now btw:
install -vdm 755 %{buildroot}/{dev,proc,run/{media/{floppy,cdrom},lock},sys}

I am using Ubuntu 14.04, with this version of install:
$ install --version
install (GNU coreutils) 8.21

**Comment by michaelpq** [comment]
Even after manually modifying the paths manually the following failure happens, which is surprising as well:
Processing files: filesystem-1.0-1.ph1.x86_64
Provides: config(filesystem) = 1.0-1.ph1 filesystem = 1.0-1.ph1 filesystem(x86-64) = 1.0-1.ph1
Requires(rpmlib): rpmlib(CompressedFileNames) <= 3.0.4-1 rpmlib(PayloadFilesHavePrefix) <= 4.0-1

Not sure what I am missing after setting up an environment with build-photon.md (requiring a link from  bash to sh is actually very surprising). The dependency requirements needed to build those deliverables require one to use either Fedora or Ubuntu (particularly the need of createrepo which prevents the use of Archlinux for example), still things are really failing. Are you sure that you are building everything from scratch in your builds? Perhaps you have in your cache a version of filesystem that built successfully and your build is using that?

**Comment by ppadmavilasom** [comment]
@michaelpq: make clean and make iso - does it help? are you running from a tp2 iso?

**Comment by scriptjs** [comment]
@michaelpg Hi, something is not right there. For myself I created a clean ubuntu 14.04 desktop vm on OSX. The instructions are pretty easy to follow. My advice is start over again. A vm for a clean environment is easy enough.

I built the ISO first. There are additional SDKs to install for the rest. This was fresh clone a few days back at the commit you are having trouble with. I started the build before I went to sleep and it was done when I woke up. It requires some hours to build. At this point I am now creating custom repos for software I am packaging as rpms for photon and converting images with qemu.

For the files you say you are looking into, they are rpms – archives, so not something you'd open in an editor.

I believe there is a vagrant box around if you are familiar with vagrant but I have not used it.

**Comment by michaelpq** [comment]
I have redeployed an Ubuntu VM from scratch and visibly things are working now. I am not sure what happened to be honest. That's for sure related to the fact that I have tried to remove unity to have a cleaner work interface...

**Comment by scriptjs** [comment]
michaelpg awesome, glad it worked out

**Comment by michaelpq** [comment]
How many hours does the build normally take for the target iso? A whole night? The first one is the hardest perhaps, the time to generate all the packages and then to cache them..

**Comment by scriptjs** [comment]
@michaelpg Its quite a few, likely pretty close. Rebuilding after that is not long though perhaps 5 min after everything is cached

**Comment by leon-github** [comment]
Hi I'm seeing this issue on top of tree on a clean Ubuntu 14.04.3 LTS. Seems very easy to reproduce. Or does anything missed in the doc/build-photon.md? Any hints are appreciated. 

2016-05-20 10:05:09,112 - Toolchain Utils - INFO - Building core tool chain packages.....
2016-05-20 10:05:09,121 - Toolchain Utils - INFO - Preparing build environment
2016-05-20 10:05:09,144 - Toolchain Utils - INFO - rpmbuild -ba --nocheck --define '_topdir /home/leonc/git/photon/stage/photonroot/build-core-toolchain/usr/src/photon' --define '_dbpath /home/leonc/git/photon/stage/photonroot/build-core-toolchain/var/lib/rpm' --define 'dist .ph1' --define 'photon_build_number 0d9d4f5' --define 'photon_release_version 1.0' /home/leonc/git/photon/SPECS/filesystem/filesystem.spec
2016-05-20 10:05:09,452 - Toolchain Utils - ERROR - Cannot find filesystem rpm
2016-05-20 10:05:09,453 - Toolchain Utils - ERROR - Unable to build tool chain.
Traceback (most recent call last):
  File "/home/leonc/git/photon/support/package-builder/ToolChainUtils.py", line 185, in buildCoreToolChainPackages
    self.installToolChainRPMS(chrootID)
  File "/home/leonc/git/photon/support/package-builder/ToolChainUtils.py", line 201, in installToolChainRPMS
    self.prepareBuildRoot(chrootID)
  File "/home/leonc/git/photon/support/package-builder/ToolChainUtils.py", line 61, in prepareBuildRoot
    raise Exception("Cannot find filesystem rpm")
Exception: Cannot find filesystem rpm
2016-05-20 10:05:09,453 - PackageManager - ERROR - Unable to build tool chain
2016-05-20 10:05:09,453 - PackageManager - ERROR - Cannot find filesystem rpm
2016-05-20 10:05:09,454 - /home/leonc/git/photon/stage/LOGS/Main - ERROR - Caught an exception
2016-05-20 10:05:09,454 - /home/leonc/git/photon/stage/LOGS/Main - ERROR - Cannot find filesystem rpm
Traceback (most recent call last):
  File "/home/leonc/git/photon/support/package-builder/builder.py", line 136, in main
    buildPackagesFromGivenJSONFile(options.inputJSONFile, options.buildOption, listBuildOptionPackages, options.pkgBuildOptionFile, logger, options.buildThreads)
  File "/home/leonc/git/photon/support/package-builder/builder.py", line 296, in buildPackagesFromGivenJSONFile
    pkgManager.buildPackages(listPackagesToBuild, listBuildOptionPackages, pkgBuildOptionFile, buildThreads)
  File "/home/leonc/git/photon/support/package-builder/PackageManager.py", line 105, in buildPackages
    self.buildToolChainPackages(listBuildOptionPackages, pkgBuildOptionFile, buildThreads)
  File "/home/leonc/git/photon/support/package-builder/PackageManager.py", line 99, in buildToolChainPackages
    self.buildToolChain()
  File "/home/leonc/git/photon/support/package-builder/PackageManager.py", line 96, in buildToolChain
    raise e
Exception: Cannot find filesystem rpm
make: *** [packages] Error 1

**Comment by ppadmavilasom** [comment]
@leon-github: toolchain rpms are downloaded from bintray so you will need network connectivity in the build vm. Could this be your issue?

**Comment by michaelpq** [comment]
No, the build of the RPM filesystem likely failed. Leon, you want to look at the contents of filesystem.log, which is I think containing an error that it did not build correctly. And this error is caused by filesystem.spec not able to handle correctly a couple of bracket markups in it.

**Comment by leon-github** [comment]
Thank Michael. Yes looks like it failed to create the symbol link. I'll look into it deeper but it's supposed to pass as I'm running on a clean ubuntu. 

+ ln -svfn lib /home/leonc/git/photon/stage/photonroot/build-core-toolchain/usr/src/photon/BUILDROOT/filesystem-1.0-3.ph1.x86_64/usr/lib64
'/home/leonc/git/photon/stage/photonroot/build-core-toolchain/usr/src/photon/BUILDROOT/filesystem-1.0-3.ph1.x86_64/usr/lib64' -> 'lib'
+ ln -svfn ../lib /home/leonc/git/photon/stage/photonroot/build-core-toolchain/usr/src/photon/BUILDROOT/filesystem-1.0-3.ph1.x86_64/usr/local/lib64
ln: failed to create symbolic link '/home/leonc/git/photon/stage/photonroot/build-core-toolchain/usr/src/photon/BUILDROOT/filesystem-1.0-3.ph1.x86_64/usr/local/lib64': No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.p0Fglo (%install)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.p0Fglo (%install)

**Comment by leon-github** [comment]
Yes it's kinda of bracket issue. Should it be fixed?

leonc@leonc-pa-2:~/git/photon$ ls /home/leonc/git/photon/stage/photonroot/build-core-toolchain/usr/src/photon/BUILDROOT/filesystem-1.0-3.ph1.x86_64/usr/
lib64    libexec/ {,local/

**Comment by dthaluru** [comment]
@leon-github Can you please make sure /bin/sh is a symlink to /bin/bash file? If not, can you please create symlink.

**Comment by leon-github** [comment]
@dthaluru You are right. By default /bin/sh is a symblink to /bin/dash.  It confused me as I thought it's pointing to /bin/bash. After fixed it, looks like the error is gone!!!

Thanks a lot!

**Comment by michaelpq** [comment]
This soft link is crazy btw, what's preventing us from changing a couple of scripts to not use /bin/sh?

**Comment by leon-github** [comment]
I agree on the it. Why not all go with /bin/bash?
