### ISSUE TITLE
Integrate upstream fix for kmod - failed to insert module kdbus: cosmetic

### ISSUE THREAD

**Issue by hickeng** [vmware/photon#435]
@caglar10ur reported: We are having a minor cosmetic issue here because of  asystemd/kmod interaction - it turns of that kmod is returning an incorrect error and the issue already fixed at upstream but it's not a part of any release

https://git.kernel.org/cgit/utils/kernel/kmod/kmod.git/commit/?id=114ec87c85c35a2bd3682f9f891e494127be6fb5

would it be possible to have it for the photon kmod package?
without this patch we end up seeing "systemd[1]: Failed to insert module 'kdbus'" errors during the initial boot of vmware/vic appliance

**Comment by suezzelur** [comment]
@hickeng Thanks, we will take this patch in soon.

**Comment by suezzelur** [comment]
Fixed [here](https://github.com/vmware/photon/commit/3f06d27ab79bd934963c23a32690eb6e84f6f51e)
