### ISSUE TITLE
Pull requests rotting or no response

### ISSUE THREAD

**Issue by scriptjs** [vmware/photon#438]
Hi. I have a general question. Why are pull requests not being incorporated into the code base or acted upon?

Some of the pull requests go back a year and there are no comments on requests since Dec last year. Looking at this, it can only be interpreted as discouraging when contributions are left to rot or when no response is received from the development team. I am pointing this out in hopes this will receive some attention and that you will bring this up to date.

**Comment by gregmmurray** [comment]
@scriptjs – thank you. Between your license question and looking at our management of pull requests, it’s clear that you’re genuinely interested in what we’re doing with Photon OS and, for that, I thank you. At this time, though, the best explanation  I have on why we haven’t been more responsive for the past several months is that we’ve taken advantage of an opportunity to leverage some internal processes and resources to rapidly mature Photon OS (VMware has more than a decade of experience validating guest operating systems). An unintended result and requirement of that effort is that the level of focus required forced us to go quiet on our Tech Preview releases for longer than we would have liked. 

I can tell you, however, that we recognize this pattern can’t persist beyond the Tech Preview phase. So, bear with us, just a short while longer; being responsive to the community is critical for successful projects.

**Comment by gregmmurray** [comment]
If you have a moment, drop me an email, please. I'd like to understand where you're headed and help clear some obstacles, if possible.

**Comment by scriptjs** [comment]
@gregmmurray I appreciate your reply. When pull requests have been accepted, I believe they should receive some attention so as to not fall out of sync with the code. This ensures you are helping out the person that provided the changes so they don't need to maintain a fork longer than necessary. Its also better for you so its not more difficult to incorporate that changes later. I think it's important to remember this is someone else's time that has been given to help. It respects the time they have given and provides encouragement to contribute when their changes make it into the code base.

I am happy to talk at any time. I really don't like or use email that much. Why not add a gitter channel for photon and we can talk there if you like. Would be good for others as well to use to have conversations about photon.

**Comment by frapposelli** [comment]
@scriptjs I think the gitter channel is a very good idea 👍

**Comment by scriptjs** [comment]
Awesome. It needs to be added by a person on the team there since your repos will appear in your list to add rooms. It will give you the option to add the gitter badge to your project as well where folks can click and just begin to chat. Its all good :) Probably good to expose photon and some of your other projects. Even if activity is not high because you are just getting started, its a great way to begin building a community.
