### ISSUE TITLE
Docker connectivity issue in Release Candidate

### ISSUE THREAD

**Issue by gregmmurray** [vmware/photon#442]
We're aware of an issue in the default configuration of systemd networking in our RC release. The issue might prevent Docker containers from getting access to the network, since the docker bridge does not get an IP address. To resolve the issue, we've provided an updated filesystem.rpm. 

To get the updated rpm and resolve the connectivity issue, please use:

    tdnf update filesystem; systemctl restart systemd-networkd

This issue will be addressed in the upcoming GA release.

**Comment by notes-jj** [comment]
tdnf ends up in an error. All repositiry servers are reachable via curl.

```
# tdnf update filesystem

Upgrading:
filesystem                                                                                            x86_64                                1.0-2.ph1                                                                          7.00 k

Total installed size: 7.00 k
Is this ok [y/N]:y

Downloading:
Error during download: 19: Cannot download x86_64/filesystem-1.0-2.ph1.x86_64.rpm: All mirrors were tried
Error(1622) : Invalid argument
```

```
# curl http://dl.bintray.com/vmware/photon_release_1.0_TP1_x86_64/
<html>
<head>
<script>
//1461426390715
function navi(e){
        location.href = e.target.href.replace('/:','/'); e.preventDefault();
}
</script>
</head>
<body>
<pre><a onclick="navi(event)" href=":noarch/" rel="nofollow">noarch/</a></pre>
<pre><a onclick="navi(event)" href=":repodata/" rel="nofollow">repodata/</a></pre>
<pre><a onclick="navi(event)" href=":x86_64/" rel="nofollow">x86_64/</a></pre>
</body>
</html>

```

**Comment by notes-jj** [comment]
`tdnf update filesystem` works again. And fixes the docker network bridge problem for me.

**Comment by sharathjg** [comment]
this has been fixed.
