### ISSUE TITLE
OVA Image - Disk larger than Partition - Swap in OVA Image

### ISSUE THREAD

**Issue by notes-jj** [vmware/photon#443]
The sda disk in the OVA Image is 15.6 GB large, while the two partitions on the disk occupy approx. 8 GB. This is some kind of awkward. The is no tool included to resize a partition like 'parted'. Unfortunately fdisk is can only resize partitions by deleting and creating an partition, what is a really dangerous operation. I used another Linux (knoppix) to resize the partition with gparted.

As netw0rm pointed out in Issue #211 there is now swap partition. This feature would be possible with the OVA image. Create an sdb disk with 4 gb. After the creation of the swap partition, the disk could be non persistent, so the content is deleted, when the machine is stopped.

**Comment by ppadmavilasom** [comment]
parted is available to install (tdnf install parted).  would that resolve your issue?

**Comment by notes-jj** [comment]
Yes, issue solved. 
Thank you.
