### ISSUE TITLE
sshpass package does not have dependency on openssh

### ISSUE THREAD

**Issue by mattolenik** [vmware/photon#446]
If you install with "tdnf install sshpass," sshpass will fail due to not finding ssh.

**Comment by suezzelur** [comment]
@mattolenik will fix that. Out of curiosity, what flavor of the OS installation are you using -minimal?

**Comment by mattolenik** [comment]
Yes, minimal

**Comment by suezzelur** [comment]
Did you manually remove openssh? How were you trying to ssh from the host?

**Comment by mattolenik** [comment]
No, I did not remove it. This happens on a fresh install.

"How were you trying to ssh from the host?" huh?

**Comment by suezzelur** [comment]
Openssh should be part of the packages on your system. I tried installing sshpass on TP2 and RC minimal and both work fine. Can you be a bit more clear about what error you are running into?

**Comment by mattolenik** [comment]
Sorry, that was incorrect, this was in a Photon Docker container. That's why there was no openssh already installed.

**Comment by mattolenik** [comment]
Why is this closed? This is still a bug. There is an official Photon container image, is there not? I would expect package dependencies to work correctly in containers as well as through the installed OS.

**Comment by sharathjg** [comment]
ugh. my bad, i thought the issue was that this was not installed in the container. I did not realize it was a missing dep.

**Comment by suezzelur** [comment]
This has been fixed
