### ISSUE TITLE
OVA signature is broken - 1.0-a6f0f63

### ISSUE THREAD

**Issue by notes-jj** [vmware/photon#447]
The signatur eof the OVA photon-custom-1.0-a6f0f63-RC.ova ist broken. Error Message in VM Workstation 9.0.4 build-1945795:

   "Verification of photon-custom.cert failed."

I downloaded the Package three times from two locations (different inet access), the ova file was always the same. sha1 checksums in photon-custom.mf are valid, but the signature in photon-custom.cert does not seam to match.

**Comment by smaliakkal** [comment]
Thank you for notifying this issue .
Signature attached to this OVA is the vmware official signature.  Could you please check downloaded OVAs sha1sumchecksum as below  and reply? 

sha1sum photon-custom-1.0-a6f0f63-RC.ova
ac782ded6cab8b20d24b274a5f5748f62fdc9b72  photon-custom-1.0-a6f0f63-RC.ova

**Comment by ppadmavilasom** [comment]
@notes-jj: any update on this?

**Comment by notes-jj** [comment]
I can confirm that I have the same sha1sum:

$ sha1sum.exe photon-custom-1.0-a6f0f63-RC_2016-04-23.ova
ac782ded6cab8b20d24b274a5f5748f62fdc9b72 *photon-custom-1.0-a6f0f63-RC_2016-04-23.ova

The OVA image before had no problems in this case: photon-custom-1.0-37d64ad-RC1.ova

**Comment by notes-jj** [comment]
I tested on another computer with VMWare Player 6.0.1 and it worked.
So it has something to do with VMWare Workstation 9.0.4 build-1945795 and photon-custom-1.0-a6f0f63.

I don't understand why I did not have the issue before. I used approx. 4 different ova images for the last 6 month.

PS: I opened Feature Request #453 to publish the checksum on every download page.

**Comment by ppadmavilasom** [comment]
@notes-jj: thanks for the pointer to workstation versions. will follow up on what we find. 

Thanks for raising the issue to publish checksum. Will do.

**Comment by gregmmurray** [comment]
If you look at the versions of virtual hardware, Workstation 9 supports virtual hardware version 9; Player 6.0 supports virtual hardware 10. I suspect that the issue is related to support of the virtual hardware in Photon OS 1.0/RC OVA, which is v10. It is odd that it reports as a cert failure. I'll see if the Workstation team can confirm. 

@notes-jj have you tested with the 1.0 OVA?

**Comment by notes-jj** [comment]
I'm now using VMWare Workstation 12 and can confirm that 1.0-a6f0f63 and hw10-1.0-13c08b6-GA are not running under Workstation 9 but are perfectly working under Workstation 12.
