### ISSUE TITLE
OpenJDK not installing any java binaries

### ISSUE THREAD

**Issue by schadr** [vmware/photon#448]
from TP2 to RC1.0 openJDK stopped installing java binaries such as javac.
why is there not dependency on open JRE?

Current work aroung:
install openJRE

**Comment by dthaluru** [comment]
I am working on it

**Comment by mattolenik** [comment]
Also, to be clear, there are actually two issues here: first is that the OpenJDK does not have the "bin" directory included, and the second is that the OpenJRE package has been incorrectly split. They are not two parts of a larger whole, they are independent packages. The OpenJDK should be shipping with it's own JRE that is separate from OpenJRE.

**Comment by ppadmavilasom** [comment]
Fix here: https://github.com/vmware/photon/commit/d5ddbf4e3930a0056113b188ee6c20043389aad3
