### ISSUE TITLE
inetutils not available in RC1.0

### ISSUE THREAD

**Issue by schadr** [vmware/photon#449]
but it was present in TP2 what is the replacement package?

**Comment by ppadmavilasom** [comment]
net-tools and iputils

**Comment by schadr** [comment]
Is there some documentation on all the packages that got obsolete and their replacements?

**Comment by ppadmavilasom** [comment]
Will add this to rc release notes -

**Comment by ppadmavilasom** [comment]
Updated release notes for rc2
