### ISSUE TITLE
yum is broken in Photon RC image

### ISSUE THREAD

**Issue by toliaqat** [vmware/photon#451]
Getting following error when running yum command
```
$yum
There was a problem importing one of the Python modules
required to run yum. The error leading to this problem was:

   pycurl: libcurl link-time version (7.43.0) is older than compile-time version (7.47.1)

Please install a package which provides this module, or
verify that the module is installed correctly.

It's possible that the above module doesn't match the
current version of Python, which is:
2.7.11 (default, Apr 16 2016, 18:52:46)
[GCC 4.8.2]

If you cannot solve this problem yourself, please go to
the yum faq at:
  http://yum.baseurl.org/wiki/Faq

```

## Repro Steps:

1. Run photon RC docker image using following command
`docker run -it vmware/photon`
2. Install yum using tdnf
`tdnf install -y yum`
3. Run yum command
`yum`

**Expected: **Yum running successfully and showing its options
**Actual:** Error about dependency

**Comment by ppadmavilasom** [comment]
yum is missing dependency to python-xml. Please install python-xml. I will fix yum spec and update here.

**Comment by ppadmavilasom** [comment]
https://github.com/vmware/photon/commit/5cfa65e9e3308fab9e2d73c47735b95dd99acdd8
