### ISSUE TITLE
[Feature Request] Please public sha1 checksum on download page and keep download pages up to date

### ISSUE THREAD

**Issue by notes-jj** [vmware/photon#453]
Please provide a sha1 checksum on the downlod pages for the download files (iso and ova):

Reason: I had problems with a downloaded ova image and could not verify 100% if it was a broken download or a broken image.

E.g.:
 - https://vmware.github.io/photon/

The download pages in the wiki are not consistent for the downloading. They point all to different images. Just make one page for downloading and share the current download like:

 - https://github.com/vmware/photon/wiki/Running-Project-Photon-on-vSphere#downloading-photon-os
 - https://github.com/vmware/photon/wiki/Running-Project-Photon-on-Fusion#downloading-photon-os
 - https://github.com/vmware/photon/wiki/Running-Photon-OS-on-Google-Compute-Engine#downloading-photon-os

**Comment by gregmmurray** [comment]
Great suggestion. I've updated the vSphere and Fusion Getting Started guides to point to a shared download page and published the checksums on that page. 

Keep the good suggestions coming, @notes-jj

**Comment by notes-jj** [comment]
Great work :-)
