### ISSUE TITLE
Kernel panic after adding new SCSI controller and disk

### ISSUE THREAD

**Issue by pdhamdhere** [vmware/photon#455]
* Deploy [Photon OVA](https://bintray.com/artifact/download/vmware/photon/photon-custom-1.0-a6f0f63-RC.ova)
* VM is powered on successfully
* Add new PVSCSI Controller. By default OS VMDK is on LSI Logic Parallel SCSI controller.
* Add new disk (Disk-2) to PVSCSI controller
* Reboot VM
* Kernel Panic - not syncing: VFS: Unable to mount root fs on unknown-block(8,2)

* Deleted Disk-2 leaving behind PVSCSI controller. Reboot. Guest came up successfully.

**Comment by YustasSwamp** [comment]
Thanks, Prashant. Good catch!
Fixed.

**Comment by ppadmavilasom** [comment]
@YustasSwamp could you please update what the fix is and what the path is for the op to get this fix?

**Comment by ppadmavilasom** [comment]
This is the fix. It will be in GA. https://github.com/vmware/photon/commit/4b093b7768c102fa3c63ed9ed093497fc67816f0
