### ISSUE TITLE
zsh is missing from the repos

### ISSUE THREAD

**Issue by casualjim** [vmware/photon#456]
it'd be great if there were a zsh available to install in photon

**Comment by deviantony** [comment]
Maybe it's possible to install it from sources: http://zsh.sourceforge.net/FAQ/zshfaq01.html#l7

But, yeah I agree, it would be nice to have a package.

**Comment by casualjim** [comment]
Yodl is missing for building the documentation, but you can get a working binary like this:

```
tdnf install -y make gcc tar git linux-dev binutils linux-api-headers autogen autoconf automake ncurses-devel texinfo glibc-devel
git clone git://git.code.sf.net/p/zsh/code /usr/src/zsh
cd /usr/src/zsh
./configure --prefix=/usr \
            --mandir=/usr/share/man \
            --bindir=/bin \
            --infodir=/usr/share/info \
            --enable-maildir-support \
            --enable-max-jobtable-size=256 \
            --enable-etcdir=/etc/zsh \
            --enable-function-subdirs \
            --enable-site-fndir=/usr/share/zsh/site-functions \
            --enable-fndir=/usr/share/zsh/functions \
            --with-tcsetpgrp \
            --with-term-lib="ncursesw" \
            --enable-cap \
            --enable-pcre \
            --enable-readnullcmd=pager \
            LDFLAGS="-Wl,--as-needed -g"

sudo make install
```

**Comment by harishspqr** [comment]
Its now added and in dev branch.

**Comment by suezzelur** [comment]
We have uploaded zsh to photon dev repo for now. Please add a repo file like /etc/yum.repos.d/photon-dev.repo which has baseurl as below:
[photon-dev]
name=VMware Photon Linux Dev(x86_64)
baseurl=https://dl.bintray.com/vmware/photon_dev_$basearch
gpgkey=file:///etc/pki/rpm-gpg/VMWARE-RPM-GPG-KEY
gpgcheck=1
enabled=1
skip_if_unavailable=True

And do tdnf install --refresh zsh
