### ISSUE TITLE
openssh should not require systemd

### ISSUE THREAD

**Issue by toliaqat** [vmware/photon#457]
openssh requires systemd because of some service files. But it should be installable without requiring systemd.
Also I would suggest to divide this package into openssh-client and openssh-server so that people can install what they really need without extra stuff.

**Comment by sharathjg** [comment]
created an openssh-clients rpm

**Comment by sharathjg** [comment]
with this commit https://github.com/vmware/photon/commit/1fc405a65d9aa1ad557786d3e5965036db033d70
