### ISSUE TITLE
Cannot update photon container because of filesystem package

### ISSUE THREAD

**Issue by toliaqat** [vmware/photon#462]
Filesystem update in container is broken at the moment. Trying to update all packages with `tdnf update -y` command fails because filesystem would not be updated.

Repro steps:

`docker run -it photon`
`tdnf update -y`

Expected Result: all packages got updated
Actual Result: Error from tdnf command with no explanation of the failure to update filesystem.

**Comment by ppadmavilasom** [comment]
Resolved. Please see #471
