### ISSUE TITLE
Updating Kubernetes on Photon

### ISSUE THREAD

**Issue by abrarshivani** [vmware/photon#466]
I want to upgrade k8s to version 1.2.4.  I tried the following:
> tdnf upgrade kubernetes

But it displays 'Nothing to do'. How do I upgrade the k8s to a new version?

**Comment by gregmmurray** [comment]
Until we've got an updated package in our repo, tdnf won't see the updated version.

@sharathjg - we really need to improve our freshness policy for these high-churn, container-related packages. This includes: docker, k8s, mesos, zookeeper, etcd ... any others that need to be covered, here?

Ideally, we would have the packages available within a couple of days of when they're released by the maintiner.

**Comment by abrarshivani** [comment]
@gregmmurray Is there any way for user to update repo?

**Comment by suezzelur** [comment]
The new version of kubernetes has been uploaded to the updates repo.
