### ISSUE TITLE
Installer fails with 'Oops, Installer got interrupted.'

### ISSUE THREAD

**Issue by rcpayne** [vmware/photon#467]
Using the full photon 1.0 iso with VMware Workstation. Results are the same for Minimal and Full installs, and capacity of volume makes no difference.

/var/log/installer is clean.
/var/log/installer.log ends with:
```
Photon echo[409]: info : Find the install size of: which
Photon echo[410]: info : Find the install size of: initramfs
Photon echo[412]: err : Failed install: glibc with error code 191
```
Backtracking into installer.py, I believe the command on failure is:
```
# tdnf install glibc --installroot /mnt/photon-root/photon-chroot/ --nogpgcheck --assumeyes
```
and when run directly, this produces:
```
Installing:
readline       x86_64      6.3-4.ph1       3.52 M
ncurses        x86_64      6.0-2.ph1       6.83 M
libgcc
filesystem
bash
glibc

Total installed size: 63.95 M

Downloading:
glibc       19395489      100%
Error(1471) : rpm generic error - not found
# echo $?
191
#
```
rpm or tdnf are the apparently causing error 191 ... can anyone shed light on why this occurs?

**Comment by gregmmurray** [comment]
Which version of Workstation? I just re-downloaded the ISO and was able to install Minimal on Workstation 12.1.

Did you verify the checksums on your download?

@ppadmavilasom - might be able to shed some light on the tdnf error.

**Comment by elephantlord** [comment]
@rcpayne: It's a generic error RPMRC_NOTFOUND
does rpm commands work (rpm -qa)? How much RAM is allocated to the VM?

**Comment by rcpayne** [comment]
Please disregard this issue - I will close.  Cause was a corrupted ISO.  Changed download manager, verified checksums and the full install went smoothly without issue.

For reference, I am using VMware Workstation 11.1.2 build-2780323

Thanks @gregmmurray and @elephantlord for your help and input.
