### ISSUE TITLE
Running Photon OS on vSphere documentation issues

### ISSUE THREAD

**Issue by lionelb08** [vmware/photon#469]
Issue 1: Followed this document and it an issue with iptables not accepting http traffic using the "vmwarecna/nginx" machine. Also, this seems to be httpd not nginx.

Document: Running Photon OS on vSphere
https://github.com/vmware/photon/wiki/Running-Photon-OS-on-vSphere

Resolution: Required iptables rule in container VM below for httpd to allow traffic:
iptables -I INPUT 1 -p tcp --dport 80 -j ACCEPT

Issue 2: "vmwarecna/nginx" machine - httpd only listening on IPv6

Resolution: modified /etc/httpd/httpd.conf
Listen 0.0.0.0:80

**Comment by gregmmurray** [comment]
@lionelb08 Thanks for raising this issue. 

I had @shoenisch take a look at this and he wasn't able to reproduce it. In the meantime, he did add some troubleshooting to the end of the document. We'll give his another look, shortly.

**Comment by sharathjg** [comment]
apache listens to all address families using a single socket. Its not that the ipv4 port is not being listened to.
