### ISSUE TITLE
Support for sshfs

### ISSUE THREAD

**Issue by dockerzip** [vmware/photon#470]
Please include a package for sshfs in the Photon package repository.  Alternatively, please indicate the process for installing from another package repository.  I've attempted to install from source and configure doesn't work.  The Photon FAQ links to Arch Linux, which has lots of good instructions on using sshfs, but from my understanding Arch uses a different package system.

**Comment by gregmmurray** [comment]
@sharathjg might be able to help with building/installing the package.

But, can you explain what you're using this for? Is this just an ease-of-use preference over something like scp?

**Comment by dockerzip** [comment]
I use hgfs on most of my VMWare Workstation VMs.  Ideally, I'd be able to use that with Photon eventually. I'd like to be able to set up a docker repository with images stored on the host.  Among other use cases.

**Comment by sharathjg** [comment]
added sshfs with this commit : https://github.com/vmware/photon/commit/538967bae917bf6fe729d17cabbfd08d3ea88ee7
