### ISSUE TITLE
kernel-headers are missing

### ISSUE THREAD

**Issue by casualjim** [vmware/photon#473]
Certain packages require access to kernel headers. I didn't see an immediate way of getting those through tdnf.

**Comment by casualjim** [comment]
there is a linux-api-headers package but stock rpms don't know about that package, so if falco is built from source this might not be an actual issue

**Comment by ppadmavilasom** [comment]
@casualjim are we missing spec requires/build requires?

**Comment by YustasSwamp** [comment]
'tdnf install linux-api-headers' will bring kernel headers
we recently added 'build-essential' package to install build tools and headers in a one shot.
