### ISSUE TITLE
package request: falco

### ISSUE THREAD

**Issue by casualjim** [vmware/photon#474]
I'd like to use the falco on photon os but several pieces are missing.

http://www.sysdig.org/falco/

**Comment by harishspqr** [comment]
Can you provide more specific details about what you attempted and the missing elements ?

**Comment by casualjim** [comment]
I tried to follow the install instructions for RHEL / yum based installs

https://github.com/draios/falco/wiki/How%20to%20Install%20Falco%20for%20Linux

**Comment by sarah-vmw** [comment]
Here is the result from Photon Full ISO:
Install Falco (Linux) - requires **kernel-devel** package
Install Falco (Containers) - working fine on Photon
Compile the Source Code - build success (with "git clone sysdig")

**Comment by suezzelur** [comment]
We have uploaded falco to photon dev repo for now. Please add a repo file like /etc/yum.repos.d/photon-dev.repo which has baseurl as below:
[photon-dev]
name=VMware Photon Linux Dev(x86_64)
baseurl=https://dl.bintray.com/vmware/photon_dev_$basearch
gpgkey=file:///etc/pki/rpm-gpg/VMWARE-RPM-GPG-KEY
gpgcheck=1
enabled=1
skip_if_unavailable=True

And do tdnf install --refresh falco
