### ISSUE TITLE
where is the gpg command

### ISSUE THREAD

**Issue by casualjim** [vmware/photon#476]
I can't find a way to install the gpg command on photon os, it must be there somewher because there are signed items present.

**Comment by ppadmavilasom** [comment]
@casualjim Photon has gpgme which has the libs but does not have gnupg which provides the gpg cmd

**Comment by casualjim** [comment]
the gpg command would be terribly useful. If I'm going to build containers I want to verify signatures of downloaded packages and files. How would I do that with photon OS?

**Comment by kaushik229** [comment]
I have added gnupg and all its dependency packages.
Changes should be available in dev branch soon after code review.

NOTE: Binary name is gpg2 instead of gpg.

**Comment by suezzelur** [comment]
We have uploaded gnupg to photon dev repo for now. Please add a repo file like /etc/yum.repos.d/photon-dev.repo which has baseurl as below:
[photon-dev]
name=VMware Photon Linux Dev(x86_64)
baseurl=https://dl.bintray.com/vmware/photon_dev_$basearch
gpgkey=file:///etc/pki/rpm-gpg/VMWARE-RPM-GPG-KEY
gpgcheck=1
enabled=1
skip_if_unavailable=True

And do tdnf install --refresh gnupg

**Comment by ssinghvi20** [comment]
I am facing following issue when following the same steps inside docker container vmware/photon:

Refreshing metadata for: 'VMware Photon Linux Dev(x86_64)'
Refreshing metadata for: 'VMware Photon Linux 1.0(x86_64)'
Refreshing metadata for: 'VMware Photon Linux 1.0(x86_64)Updates'
Refreshing metadata for: 'VMware Lightwave 1.0(x86_64)'
Refreshing metadata for: 'VMware Photon Extras 1.0(x86_64)'

Installing:
libksba                                                                             x86_64                         1.3.4-2.ph1                                                      277.32 k
libgcrypt                                                                           x86_64                         1.6.5-3.ph1                                                      953.19 k
pth                                                                                 x86_64                         2.0.7-1.ph1                                                       78.09 k
gnupg                                                                               x86_64                         2.0.30-1.ph1                                                       7.33 M

Total installed size: 8.61 M

Upgrading:
bash                                                                                x86_64                         4.4-1.ph1                                                          2.96 M
pcre                                                                                x86_64                         8.39-2.ph1                                                       960.91 k
readline                                                                            x86_64                         7.0-1.ph1                                                        328.63 k

Total installed size: 4.22 M

Reinstalling:
lua                                                                                 x86_64                         5.3.2-2.ph1                                                      612.40 k

Total installed size: 612.40 k
Is this ok [y/N]:y

Downloading:
gnupg                                  3138574    100%
pth                                      38756    100%
libgcrypt                               401858    100%
libksba                                 133541    100%
lua                                     293190    100%
readline                                138003    100%
pcre                                    384786    100%
bash                                    980361    100%
Found 1 problems
libreadline.so.6()(64bit) is needed by (installed) lua-5.3.2-2.ph1.x86_64
Found 1 problems
libreadline.so.6()(64bit) is needed by (installed) lua-5.3.2-2.ph1.x86_64
Error(1515) : rpm check reported errors
