### ISSUE TITLE
public AMI on AWS

### ISSUE THREAD

**Issue by casualjim** [vmware/photon#478]
I can upload the ami from binary to my S3 and use photon that way, it would be easier if it were available in the AWS marketplace though, in all regions.

Another way to approach this is the way ubuntu does this: https://cloud-images.ubuntu.com/locator/ec2/

**Comment by gregmmurray** [comment]
Totally agree. It's on the "to-do" list.

**Comment by rgeorgiev** [comment]
Any update on this one?

**Comment by casualjim** [comment]
You can find a list of public AMI's here: https://storage.googleapis.com/svd-lcm-images/lcm-ami-list.json

**Comment by suezzelur** [comment]
Photon amis are shared in the community amis.
