### ISSUE TITLE
golang package is out of date

### ISSUE THREAD

**Issue by casualjim** [vmware/photon#482]
Golang in the repos is still at 1.4.2, currently go is at 1.6.2 and it will go to 1.7.0 in august.  It would be great if we could track those releases.

**Comment by tsugliani** [comment]
+1 please

**Comment by cormachogan** [comment]
I'm trying to use Photon OS for rolling out K8S, etc on photon controller. Having old golang is a pain, so it would be great if we could get it updated.

**Comment by harishspqr** [comment]
Updated to 1.6.2 now.

**Comment by suezzelur** [comment]
We have uploaded go 1.6.3 to photon dev repo for now. Please add a repo file like /etc/yum.repos.d/photon-dev.repo which has baseurl as below:
[photon-dev]
name=VMware Photon Linux Dev(x86_64)
baseurl=https://dl.bintray.com/vmware/photon_dev_$basearch
gpgkey=file:///etc/pki/rpm-gpg/VMWARE-RPM-GPG-KEY
gpgcheck=1
enabled=1
skip_if_unavailable=True

And do tdnf install --refresh go
