### ISSUE TITLE
package request: jq

### ISSUE THREAD

**Issue by casualjim** [vmware/photon#484]
it's trivial to install but it's also useful to have in the repos

I install with:

``` shell
curl -L'#' -o /usr/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 && chmod +x /usr/bin/jq
```

**Comment by tsugliani** [comment]
Very useful tool, would be practical to have in tdnf default repositories

**Comment by gregmmurray** [comment]
@sharathjg Can you, please, evaluate bringing this package in?

I agree with @casualjim that it probably doesn't make sense in any of the binary images; but, I can definitely see the usefulness. Releases look relatively infrequent, too.

**Comment by ppadmavilasom** [comment]
will add for 2.0

**Comment by ppadmavilasom** [comment]
1.5-3 in 2.0 GA
