### ISSUE TITLE
Package for unixodbc is missing

### ISSUE THREAD

**Issue by michaelpq** [vmware/photon#485]
The UnixODBC package is missing, and should be here to allow any
ODBC-related package to work correctly on this platform. One coming
immediately to my mind is the Postgres ODBC driver (which had better
be added as well to be honest).

**Comment by sharathjg** [comment]
Fixed with this commit : https://github.com/vmware/photon/commit/10c9a4c13b05578852d062d648ad8e61aa9c2796
