### ISSUE TITLE
"Domains" field is not supported in resolve.conf

### ISSUE THREAD

**Issue by iceiilin** [vmware/photon#488]
From https://www.freedesktop.org/software/systemd/man/resolved.conf.html, "Domains" filed is supported, but it fails in my full Photon 1.0.
The configuration file is:
```
root@photon [ ~ ]# cat /etc/systemd/resolved.conf
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.
#
# Entries in this file show the compile time defaults.
# You can change settings by editing this file.
# Defaults can be restored by simply deleting this file.
#
# See resolved.conf(5) for details

[Resolve]
#DNS=
#FallbackDNS=8.8.8.8 8.8.4.4 2001:4860:4860::8888 2001:4860:4860::8844
#LLMNR=yes
Domains=example.com
DNS=172.12.88.90
```
After restart the service using
```
systemctl restart systemd-resolved
```
I got the error
```
root@photon [ ~ ]# journalctl --since "2016-07-08 14:40:00"
-- Logs begin at Wed 2016-07-06 14:54:21 HKT, end at Fri 2016-07-08 14:41:04 HKT. --
Jul 08 14:41:04 photon systemd[1]: Stopping Network Name Resolution...
Jul 08 14:41:04 photon systemd[1]: Stopped Network Name Resolution.
Jul 08 14:41:04 photon systemd[1]: Starting Network Name Resolution...
Jul 08 14:41:04 photon systemd-resolved[937]: Using system hostname 'photon'.
Jul 08 14:41:04 photon systemd-resolved[937]: [/etc/systemd/resolved.conf:18] Unknown lvalue 'Domains' i
n section 'Resolve'
Jul 08 14:41:04 photon systemd[1]: Started Network Name Resolution.
```

Does anyone have insight about this?

**Comment by suezzelur** [comment]
"Domains=" in resolved.conf is a post systemd-228 feature.

**Comment by iceiilin** [comment]
@suezzelur Do you mean that “Domains" in resolved.conf is not applied to current Photon? Is there any other way for me to configure this settings (just like "search" in resolve.conf of CentOS) currently?

**Comment by vinaykul** [comment]
Prior to systemd v229, Domains can be configured only in the .network file. Please see https://www.freedesktop.org/software/systemd/man/systemd.network.html. 

That said, there is an issue we recently discovered where static Domains settings may not get picked up and configured in the search settings in /etc/resolv.conf if static DNS is used (above use case). We are looking to fix this in an update.

**Comment by iceiilin** [comment]
Got it, thanks!
