### ISSUE TITLE
Failed to open OVF descriptor in in Fusion

### ISSUE THREAD

**Issue by deadjoe** [vmware/photon#490]
Hello,

I have downloaded "OVA with virtual hardware v11" from https://github.com/vmware/photon/wiki/Downloading-Photon-OS. And verified the MD5 to ensure the OVF file's integrity. 

And followed the instruction from https://github.com/vmware/photon/wiki/Running-Project-Photon-on-Fusion . But failed to import the OVF to VMWare Fusion.

My Fusion version is exactly the same as the instructions. It didnt go the EULA screen after i clicked "Save" button Instead, Fusion importer gave me the following error:
![image](https://cloud.githubusercontent.com/assets/2519527/16916399/4a170d28-4d2f-11e6-8ba1-39ba20c20667.png)

**Comment by sarah-vmw** [comment]
I just download the https://bintray.com/artifact/download/vmware/photon/photon-custom-hw11-1.0-13c08b6-GA.ova and import to Fusion (Professional Version 8.1.1 (3771013)), and it's working fine.
According to the error message, it looks the OVA components are distorted for some reason. (It's strange that MD5sum is correct though.)

Could you please retry after download again the OVA file?

**Comment by dthaluru** [comment]
Unable to reproduce the issue. Please reopen if issue is seen again.

**Comment by devmi** [comment]
If you downloaded the .OVA file using macOS Chrome, please make sure the file extension is  **.OVA and not .OVF**.

There seems to be a [bug on Chrome for macOS](https://blogs.vmware.com/feed-items/chrome-on-macos-downloads-ova-files-as-ovfs) that downloads .OVA files as .OVF. 

See also [issue 311218](https://bugs.chromium.org/p/chromium/issues/detail?id=311218)

**Comment by extenttech** [comment]
Thanks @devmi , this helped me a lot.. I was struggling to import large vm in fusion and did't notice the extension change. Thanks for pointing out.

**Comment by bhargavagithub** [comment]
Thanks, @devmi. I downloaded it twice, thinking the file was corrupted, but your comment helped me fix it.

**Comment by Pai-Po** [comment]
Thanks @devmi , this is ridiculous.

**Comment by syrashid** [comment]
@devmi you are a lifesaver

**Comment by kevXZY** [comment]
@devmi Thank you!! issue still there for chrome/brave
