### ISSUE TITLE
libjpeg missing

### ISSUE THREAD

**Issue by casualjim** [vmware/photon#494]
libjpeg or libjpeg-turbo are used by various other libraries to deal with jpeg images

**Comment by suezzelur** [comment]
We have uploaded libjpeg-turbo to photon dev repo for now. Please add a repo file like /etc/yum.repos.d/photon-dev.repo which has baseurl as below:
[photon-dev]
name=VMware Photon Linux Dev(x86_64)
baseurl=https://dl.bintray.com/vmware/photon_dev_$basearch
gpgkey=file:///etc/pki/rpm-gpg/VMWARE-RPM-GPG-KEY
gpgcheck=1
enabled=1
skip_if_unavailable=True

And do tdnf install --refresh libjpeg-turbo
