### ISSUE TITLE
libwebp is missing

### ISSUE THREAD

**Issue by casualjim** [vmware/photon#496]
libwebp is used by various other libraries to deal with webp images

**Comment by suezzelur** [comment]
We have uploaded libwebp to photon dev repo for now. Please add a repo file like /etc/yum.repos.d/photon-dev.repo which has baseurl as below:
[photon-dev]
name=VMware Photon Linux Dev(x86_64)
baseurl=https://dl.bintray.com/vmware/photon_dev_$basearch
gpgkey=file:///etc/pki/rpm-gpg/VMWARE-RPM-GPG-KEY
gpgcheck=1
enabled=1
skip_if_unavailable=True

And do tdnf install --refresh libwebp

**Comment by 8SKIN8** [comment]
> libwebp is used by various other libraries to deal with webp images

This is a good thing... No?
