### ISSUE TITLE
rpm-ostree is outdated

### ISSUE THREAD

**Issue by casualjim** [vmware/photon#501]
our rpm-ostree is 2015.7, they are at 2016.4

**Comment by gregmmurray** [comment]
@sharathjg Please have Danut look into this.

**Comment by ppadmavilasom** [comment]
will update for 2.0

**Comment by ppadmavilasom** [comment]
updated in dev for 2.0 -
 https://github.com/vmware/photon/commit/ff3a6d949c2c366a95567ce4e340fcaf239a8ec1

**Comment by ppadmavilasom** [comment]
2017.4-7.ph2 in 2.0 GA
