### ISSUE TITLE
ipset is missing

### ISSUE THREAD

**Issue by szechyjs** [vmware/photon#505]
This prevents the install of DC/OS.

**Comment by suezzelur** [comment]
We have uploaded ipset to photon dev repo for now. Please add a repo file like /etc/yum.repos.d/photon-dev.repo which has baseurl as below:
[photon-dev]
name=VMware Photon Linux Dev(x86_64)
baseurl=https://dl.bintray.com/vmware/photon_dev_$basearch
gpgkey=file:///etc/pki/rpm-gpg/VMWARE-RPM-GPG-KEY
gpgcheck=1
enabled=1
skip_if_unavailable=True

And do tdnf install --refresh ipset ipset-devel

**Comment by renmaosheng** [comment]
@suezzelur 
when I try to add a ipset entry, I hit below error:

 root@k8s-node-0-c49c184ebe6b4ac3 [ ~ ]# ipset create test hash:ip
ipset v6.29: Kernel error received: set type not supported

how could I load  "ip_set_hash_ip.ko" in /lib/modules/4.4.26/kernel/net/netfilter/ipset/?

I am using ﻿4.4.26-esx of photon OS

**Comment by YustasSwamp** [comment]
Ipset for linux-esx was added in 4.4.31-2 version by this commit
https://github.com/vmware/photon/commit/44f551306868837374898884058211ac066a47e3

try to update linux-esx

Thanks

**Comment by renmaosheng** [comment]
thanks a lot, is there a documnet of upgrade the kernel? sorry new to photon-os. thanks.

**Comment by YustasSwamp** [comment]
`tdnf update linux-esx`

**Comment by renmaosheng** [comment]
thanks a lot, is there an released photon OS ova whose kernel has ipset could be used? thanks.

**Comment by YustasSwamp** [comment]
currently only `tdnf update linux-esx`. we are going to ship ova for each package update

**Comment by renmaosheng** [comment]
Do we have any cadency about releasing ? Thanks.

From: Alexey Makhalov
Reply-To: vmware/photon
Date: Wednesday, January 11, 2017 at 2:02 AM
To: vmware/photon
Cc: Maosheng Ren, Comment
Subject: Re: [vmware/photon] ipset is missing (#505)


currently only tdnf update linux-esx. we are going to ship ova for each package update

**Comment by YustasSwamp** [comment]
We update 1.0 repo every 1-2 weeks. Latest update is #15 https://github.com/vmware/photon/wiki/Security-Updates-15.
For further package updates we are going to provide updated .ova
It will be available here:
https://github.com/vmware/photon/wiki/Downloading-Photon-OS

**Comment by renmaosheng** [comment]
thank you Alexey, how often is the ova updated? I can't find any tags/dates on the downloading pages.

**Comment by YustasSwamp** [comment]
we did not update ova yes, just GA. We've just decided that it's good to update ova for each package update as well.

**Comment by renmaosheng** [comment]
Got it, thanks. I ask because there are use cases that will deploy ova directly, including the new updated packages in ova will save effort to run "tdnf update" :)
