### ISSUE TITLE
more detailed documentation for kickstart options

### ISSUE THREAD

**Issue by sosher** [vmware/photon#506]
Hi, 
Is there a detailed kickstart options documentation specifically for photon?
 It works well but I feel there are a lot more options I can use.

Additionally , Can I use tdnf update in kickstart. 
I am using ipxe and would like to able to update the os as part of the installation 
Thanks.

**Comment by mxb78** [comment]
at least more info where to dig deeper in sample_ks.conf

**Comment by ppadmavilasom** [comment]
@dmoraru any updates on this?

**Comment by YustasSwamp** [comment]
@dmoraru any progress?

**Comment by invad0r** [comment]
+1

**Comment by redbaron-gt** [comment]
+1

**Comment by stuclem** [comment]
For investigation in 3.0

**Comment by stuclem** [comment]
See also https://github.com/vmware/photon/issues/794

**Comment by YustasSwamp** [comment]
here: https://github.com/vmware/photon/blob/master/installer/ks_config.txt

**Comment by imranrazakhan** [comment]
> here: https://github.com/vmware/photon/blob/master/installer/ks_config.txt

@YustasSwamp  This link is broken
