### ISSUE TITLE
vmlinuz parameters  for nfs & documentation 

### ISSUE THREAD

**Issue by sosher** [vmware/photon#507]
Hello,
Is it possible to add nfs support for pxe/ipxe installation  instead of using http ?
additionally , What other options can I pass for vmlinuz specific to photon os ?

Thanks ,

**Comment by YustasSwamp** [comment]
Currently we support only http and https for repo for pxe installation.
We'll definitely add ftp support, not sure about nfs.

Parameters we support for pxe:
repo= (https://github.com/vmware/photon/blob/master/docs/PXE-boot.md)
ks= (https://github.com/vmware/photon/blob/master/docs/kickstart.md)

Thanks,
--Alexey
