### ISSUE TITLE
Upgrade Docker in Photon repo

### ISSUE THREAD

**Issue by pdhamdhere** [vmware/photon#508]
Docker package in Photon repo is out of date. Docker has introduced some key features in 1.12 that I would love to use with Photon and vSphere Docker Volume Driver. 

```
tdnf info docker
Name          : docker
Arch          : x86_64
Epoch         : 0
Version       : 1.11.2
Release       : 1.ph1
Install Size  : 57.25 M (60028370)
Repo          : @System
Summary       : Docker
URL           : http://docs.docker.com
License       : ASL 2.0
Description   : Docker is a platform for developers and sysadmins to develop, ship and run applications.
```

```
docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 6
Server Version: 1.11.2
```

Alternatively, is there a way to manually upgrade Docker on Photon OS?

**Comment by suezzelur** [comment]
@pdhamdhere We are in the process of updating docker to 1.12
In the meantime, you can download docker 1.12 and replace the binaries in /usr/bin.
wget https://get.docker.com/builds/Linux/x86_64/docker-1.12.0.tgz
You may have to edit the docker-containerd.service file in /usr/lib/systemd/system to replace the existing ExecStart section with the following:
ExecStart=/usr/bin/docker-containerd --listen unix:///run/containerd.sock --runtime /usr/bin/docker-runc --shim /usr/bin/docker-containerd-shim
And do a systemctl daemon-reload followed by systemctl restart docker.

**Comment by nbaillie** [comment]
Is there a method for monitoring/being notified, when 1.12 is released on the repo?
Also whats the Estimate for when it might be available?

**Comment by dack** [comment]
Any update on this? Docker 1.12.0 has been out for a month and 1.12.1 was released 2 weeks ago. There are some big improvements in 1.12.x, particularly for swarm deployments.

**Comment by suezzelur** [comment]
We have uploaded docker 1.12.0 to photon dev repo. Please add a repo file like /etc/yum.repos.d/photon-dev.repo which has baseurl as below:
[photon-dev]
name=VMware Photon Linux Dev(x86_64)
baseurl=https://dl.bintray.com/vmware/photon_dev_$basearch
gpgkey=file:///etc/pki/rpm-gpg/VMWARE-RPM-GPG-KEY
gpgcheck=1
enabled=1
skip_if_unavailable=True

And do tdnf install --refresh docker

**Comment by casualjim** [comment]
docker released 1.12.1 weeks ago with swarm fixes, when will that hit the dev repo?

**Comment by bt** [comment]
👍 

Please action ASAP, I am needing to downgrade my Docker client to communicate with Photon as a workaround, otherwise will encounter this error message:

```
Error response from daemon: client is newer than server (client API version: 1.24, server API version: 1.23)
```

**Comment by msterin** [comment]
Any update ?

**Comment by sarchoi** [comment]
The dev branch has docker 1.12.1. 
https://github.com/vmware/photon/blob/dev/SPECS/docker/docker.spec

**Comment by suezzelur** [comment]
The rpms will be uploaded to the dev repo by 10/06.

**Comment by kerneltime** [comment]
Shold systemctl be triggered to reload as part of upgrade?
```
 # tdnf install --refresh docker
# docker -v
Docker version 1.12.1, build 23cf638
# systemctl stop docker
2016-10-31 05:22:33.875807646 +0000 UTC [WARNING] Received signal signal=terminated 
Warning: docker.service changed on disk. Run 'systemctl daemon-reload' to reload units.
```
