### ISSUE TITLE
Download Links are Broken

### ISSUE THREAD

**Issue by notes-jj** [vmware/photon#509]
The download links for "OVA with virtual hardware v10" and "OVA with virtual hardware v11" on the download page are broken and lead to a 404 page on bintray.com.

Download Page:
- https://github.com/vmware/photon/wiki/Downloading-Photon-OS

Broken Links:
- https://bintray.com/artifact/download/vmware/photon/photon-custom-hw10-1.0-13c08b6-GA.ova
- https://bintray.com/artifact/download/vmware/photon/photon-custom-hw11-1.0-13c08b6-GA.ova

**Comment by suezzelur** [comment]
@notes-jj We are working on fixing it within a day or two.

**Comment by suezzelur** [comment]
https://github.com/vmware/photon/wiki/Downloading-Photon-OS has been updated with new links

**Comment by luomiao** [comment]
Sorry to comment on a closed issue, but it seems the download links are OVF files instead of OVA files. Thanks.

**Comment by sarchoi** [comment]
@luomiao: The links in https://github.com/vmware/photon/wiki/Downloading-Photon-OS are OVA files. Could you please try again? 

https://bintray.com/vmware/photon/download_file?file_path=photon-custom-hw10-1.0-13c08b6.ova
https://bintray.com/vmware/photon/download_file?file_path=photon-custom-hw11-1.0-13c08b6.ova

**Comment by luomiao** [comment]
@sarchoi Thank you for your reply. The system automatically saved the downloaded files into .ovf format instead of .ova format. I changed the name and it works fine now. Sorry for the confusion.
