### ISSUE TITLE
Wiki changes for Running PhotonOS for vSphere.

### ISSUE THREAD

**Issue by tduval** [vmware/photon#512]
While reading the following wiki pages (https://github.com/vmware/photon/wiki/Running-Photon-OS-on-vSphere), with full installation, at the end it says to run the command:
`docker run -d -p 80:80 vmwarecna/nginx`

I got the following error message 

> Error starting userland proxy: listen tcp 0.0.0.0:80: listen: address already in use.

In fact, an httpd apache service is already running at the port 80. We should change either the nginx-container port or shutdown the httpd service to allow the container to bind to this port.

**Comment by sharathjg** [comment]
It looks like the default configuration for both the services are correct, If you dont need httpd, you can erase the package to free up the port or disable the service.
