### ISSUE TITLE
Need STIG/SCAP support or guide

### ISSUE THREAD

**Issue by rdachere** [vmware/photon#516]
The vSECR team provides some vulnerability scanning tools that they require product teams to run through and vet prior to shipping a release.

Could we have a list of scanners and default settings that are STIG/SCAP compliant from the base OS?

Reference:
https://en.wikipedia.org/wiki/Security_Technical_Implementation_Guide
https://wiki.eng.vmware.com/VSECR/vSDL/VulnerabilityScanning
https://scap.nist.gov/validation/index.html

**Comment by gregmmurray** [comment]
@rdachere We are working on our STIG effort. The first iteration will probably be legacy STIG documentation. We don't have a commitment around SCAP/OVAL work. Obviously, too, we'll be working to try and see where this is applicable and where it is not. 

I'd be interested to hear from anyone outside of VMware that sees a need for STIG for Photon OS. 

Orthogonally, we use cve-check-tool (https://github.com/ikeydoherty/cve-check-tool) and have been working with vSECR to ensure we've got the right kind of oversight on package-level vulnerabilities.

**Comment by kclinden** [comment]
Did this get solved?

**Comment by smaliakkal** [comment]
@kclinden 

Could you be more elaborate on your issue ? 
Photon team uses cve-check-tool, ( which is also part of Photon OS) and Appcheck scanner instances deployed within vmware for determining vulnerability  data on Photon OS. VMware Appliances which consumes Photon OS can run their security scan against appcheck.eng.vmware.com uploading their artifact. 

From Photon OS side, there are two security tools cve-check-tool and openscap (SCAP implementation) .
