### ISSUE TITLE
Need tcpdump for minimal install

### ISSUE THREAD

**Issue by rdachere** [vmware/photon#518]
This is essential for debugging network related issues and most users know this tool.

**Comment by snambakam** [comment]
It does not make sense to add this to the minimal installation. If/when someone wants to debug an issue, they can download it.

**Comment by gregmmurray** [comment]
@snambakam I had an offline conversation with @rdachere where she raised the outstanding point that, if you're troubleshooting a lack of network connectivity, downloading these packages isn't an option. They'd be only a 2MB increase. Without this, troubleshooting networking becomes a chicken-and-egg problem.

**Comment by snambakam** [comment]
I see the point about always wanting debug tools handy.

I have seen teams at VMware who consider tcpdump a security risk and therefore don't include it by default.

Is tcpdump included by default in minimal installs of SLES and Redhat?

Thanks
Sriram

Sent from my iPhone

On Sep 7, 2016, at 1:02 AM, Gregory Murray <notifications@github.com<mailto:notifications@github.com>> wrote:


@snambakam<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_snambakam&d=CwMFaQ&c=Sqcl0Ez6M0X8aeM67LKIiDJAXVeAw-YihVMNtXt-uEs&r=AOv6gXgVkXFbmxhYvlHvYsdrxTCOrtz4Nc-sIj7GL8o&m=jDoyjfhyxsC-Zsj4cNlKBeRoFBlT5d4oTgTTNkKGljU&s=NWDIV3PJYIjQP4AKvXSfX5FkggXpgWKsXqRoiWEQnIk&e=> I had an offline conversation with @rdachere<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_rdachere&d=CwMFaQ&c=Sqcl0Ez6M0X8aeM67LKIiDJAXVeAw-YihVMNtXt-uEs&r=AOv6gXgVkXFbmxhYvlHvYsdrxTCOrtz4Nc-sIj7GL8o&m=jDoyjfhyxsC-Zsj4cNlKBeRoFBlT5d4oTgTTNkKGljU&s=vRh_qbEEE5yFdxwumGkas4stLvNzRWVB56iArPGMXBU&e=> where she raised the outstanding point that, if you're troubleshooting a lack of network connectivity, downloading these packages isn't an option. They'd be only a 2MB increase. Without this, troubleshooting networking becomes a chicken-and-egg problem.

-

**Comment by snambakam** [comment]
Can whoever wants tcpdump pull it into their ova or container using tdnf?

Why do we need this in the minimal installation?

Thanks
Sriram

Sent from my iPhone

On Sep 7, 2016, at 4:11 AM, Sriram Nambakam <snambakam@vmware.com<mailto:snambakam@vmware.com>> wrote:

I see the point about always wanting debug tools handy.

I have seen teams at VMware who consider tcpdump a security risk and therefore don't include it by default.

Is tcpdump included by default in minimal installs of SLES and Redhat?

Thanks
Sriram

Sent from my iPhone

On Sep 7, 2016, at 1:02 AM, Gregory Murray <notifications@github.com<mailto:notifications@github.com>> wrote:


@snambakam<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_snambakam&d=CwMFaQ&c=Sqcl0Ez6M0X8aeM67LKIiDJAXVeAw-YihVMNtXt-uEs&r=AOv6gXgVkXFbmxhYvlHvYsdrxTCOrtz4Nc-sIj7GL8o&m=jDoyjfhyxsC-Zsj4cNlKBeRoFBlT5d4oTgTTNkKGljU&s=NWDIV3PJYIjQP4AKvXSfX5FkggXpgWKsXqRoiWEQnIk&e=> I had an offline conversation with @rdachere<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_rdachere&d=CwMFaQ&c=Sqcl0Ez6M0X8aeM67LKIiDJAXVeAw-YihVMNtXt-uEs&r=AOv6gXgVkXFbmxhYvlHvYsdrxTCOrtz4Nc-sIj7GL8o&m=jDoyjfhyxsC-Zsj4cNlKBeRoFBlT5d4oTgTTNkKGljU&s=vRh_qbEEE5yFdxwumGkas4stLvNzRWVB56iArPGMXBU&e=> where she raised the outstanding point that, if you're troubleshooting a lack of network connectivity, downloading these packages isn't an option. They'd be only a 2MB increase. Without this, troubleshooting networking becomes a chicken-and-egg problem.

-

**Comment by suezzelur** [comment]
Currently there are no plans to add debugging tools by default to the minimal ova.
