### ISSUE TITLE
Need lsof for minimal ova

### ISSUE THREAD

**Issue by rdachere** [vmware/photon#519]
This is a must-have for debugging on the platform.

**Comment by snambakam** [comment]
It does not make sense to add this to the minimal installation. If/when someone wants to debug an issue, they can download it.

**Comment by gregmmurray** [comment]
@rdachere - to expand on what @snambakam volunteered ... 

We try to keep the minimal OVA limited to things that are required for runtime. Troubleshooting tools, as Sriram said, are something that can be installed as needed. 

To install lsof, which is in our Photon OS repositories, enter:
"tdnf install lsof"
