### ISSUE TITLE
Issues with clone preparation with systemd on Photon OS

### ISSUE THREAD

**Issue by james65535** [vmware/photon#520]
When preparing Photon OS for cloning and distribution, `/etc/machine-id` should be removed and regenerated.  Manually this can be done with `systemd-machine-id-setup` but for distribution and automation purposes it may require `systemd-firstboot` which does not seem to be included in the Photon OS packaging.  This may need to be added unless there is a different recommended practice for the above.

**Comment by YustasSwamp** [comment]
echo -n > /etc/machine-id
is better then removing it.
The content will be automatically regenerated by systemd on reboot

**Comment by james65535** [comment]
Just tried that and it worked perfectly.  Also tested as part of a vagrant/packer multi-machine build and it worked great for that process.  Many thanks for your help.
