### ISSUE TITLE
Expansion of storage

### ISSUE THREAD

**Issue by tibmeister** [vmware/photon#522]
Due to the partitioning scheme it doesn't appear there's a way to expand the storage of an appliance after deployment.

**Comment by casualjim** [comment]
this worked for me, but ymmv: https://falstaff.agner.ch/2013/12/22/online-resize-root-filesystem-on-a-gpt-partition/

**Comment by sharathjg** [comment]
Assuming you increased the disk size itself. Closing this out as this is done with regular linux tools.
