### ISSUE TITLE
PhotonOS deployment on Openstack platform

### ISSUE THREAD

**Issue by nellaivijay** [vmware/photon#523]
Any document or reference available for PhotonOS deployment on OpenStack platform.

**Comment by suezzelur** [comment]
We are working on the documentation and will update the wiki soon.

**Comment by ppadmavilasom** [comment]
@suezzelur any update on this?

**Comment by scriptjs** [comment]
+1  Currently using qemu-image to convert to qcow2 compressed image after creating minimal from ISO but uncertain whether there are there tools that need to be install for vm stability, keeping time in sync etc.

**Comment by stuclem** [comment]
For investigation in the next release.

**Comment by vidya-v** [comment]
Closing this issue as per update  from @sharathjg on [Doc tasks page](https://confluence.eng.vmware.com/display/PHOTONOS/Photon+OS+3.0+Documentation+Tasks),
