### ISSUE TITLE
sysdig package does not work on Photon OVA (ESX optimized)

### ISSUE THREAD

**Issue by toliaqat** [vmware/photon#524]
Because sysdig package has a kernel module to work. But that kernel module is only for linux, not for linux-esx.

**Comment by casualjim** [comment]
when I run csysdig in a vmware workstation I get kernel dumps and that's the plain linux kernel because linux-esx fails to boot there

**Comment by suezzelur** [comment]
Can you update both sysdig and linux kernel to the latest in the photon-updates repo? sysdig kernel module is tied to the kernel config at build time and may have issues running on a kernel which was built at a different point.

**Comment by toliaqat** [comment]
Anish,
Will latest sysdig work with latest linux-esx?

**Comment by suezzelur** [comment]
It will not. The esx kernel is pretty minimal and do not support tracepoints, so even if you try to build the sysdig kernel module and install it on the esx kernel, it will not work. Please use generic kernel for debugging purposes.
