### ISSUE TITLE
photon OS deploys stopped working on AWS

### ISSUE THREAD

**Issue by casualjim** [vmware/photon#527]
#The root password is expired on the AWS image, and when you ssh into the instance it will ask you to change the password, but the password used to create the image is unknown.

**Comment by jakedsouza** [comment]
Blocked from using photon on AWS.  

```
$ ssh -i key.pem  root@54.70.3.16
You are required to change your password immediately (password aged)
Last login: Fri Sep  9 19:32:42 2016 from 208.91.2.4
Changing password for root.
(current) UNIX password:
Connection to 54.70.3.16 closed.
````

**Comment by sharathjg** [comment]
This has been fixed and the image updated from the links.
