### ISSUE TITLE
package request: google-fluentd

### ISSUE THREAD

**Issue by casualjim** [vmware/photon#528]
To make use of GCP's stackdriver we need to have  a package for googles fluentd agent

https://cloud.google.com/logging/docs/agent/

**Comment by gregmmurray** [comment]
@casualjim you probably only need this in the GCE image, right?

Obviously, we'll have to maintain it in the repo; but, this should be exclusively in the GCE binary artifact, iiuc.

**Comment by casualjim** [comment]
the package is also useful on AWS, it's a way to use stackdriver on both google cloud and aws.

**Comment by casualjim** [comment]
https://github.com/GoogleCloudPlatform/google-fluentd

**Comment by yairyog** [comment]
I'm looking into using photon as a base image for out containers. It seems getting the google-fluentd agent to install is the main obstacle

**Comment by casualjim** [comment]
We worked around it by installing fluentd as a container based instead of as a package
