### ISSUE TITLE
Hostname changes on Reboot on vSphere

### ISSUE THREAD

**Issue by vmtocloud** [vmware/photon#532]
When using Photon OS 1.0 on vSphere 6 I am able to use guest customization to set the VM name and host name and IP settings. If I reboot the VM either within the OS or from vCenter Client the Photon OS reboots fine but the host name in the guest is replaced with a random generated name for example Photon-pcft34hf

**Comment by suezzelur** [comment]
This was fixed by https://github.com/vmware/photon/commit/4bbcf05ed46ac4e2659bd8eb7c6f03e9a8218e8f
We will release this in our next update to the ova. If you want to try this out, please use the workaround in the patch. After customization, remove the following folder:
rm -rf /var/lib/cloud/seed
