### ISSUE TITLE
cloud-image ova fails 

### ISSUE THREAD

**Issue by sosher** [vmware/photon#533]
Hi,
when running cloud-image IMG_NAME=ova , it fails running 
"g++ -o ../../bin/vixdiskutil -I/usr/include -L/usr/lib/vmware vixDiskUtil.cpp -ldl -lvixDiskLib -lvixMntapi -lvixDiskLibVim -lpthread -lssl -lfuse"

with these errors

/usr/bin/ld: cannot find -lfuse
/usr/bin/ld: cannot find -lssl

this is being compiled on ubuntu 16.04

thanks

**Comment by suezzelur** [comment]
Please do sudo apt-get install libfuse-dev libssl-dev
