### ISSUE TITLE
cloud-image ova woes.

### ISSUE THREAD

**Issue by sosher** [vmware/photon#534]
I am sorry for my error, 

I am posing the last make errors I am having,
I do feel there is a lack of documentation which doesn't interact well with my lack of experience.
there are several issues popping up and in the end .the ova folder contains mostly empty ovas

warning: %post(bash-4.3.30-5.ph1.x86_64) scriptlet failed, exit status 127
/bin/sh: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory
warning: %post(glibc-2.22-9.ph1.x86_64) scriptlet failed, exit status 127
2016-09-21 21:23:23,044 - build-dialog - INFO - Installed toolchain successfully on chroot:/root/photon/stage/photonroot/build-dialog
2016-09-21 21:23:23,109 - build-dialog - INFO - List of installed packages
2016-09-21 21:23:23,109 - build-dialog - INFO - ['libgcc', 'glibc', 'readline', 'libstdc++', 'pkg-config', 'mpfr', 'file', 'm4', 'libcap', 'libgomp', 'binutils', 'nspr', 'nss', 'rpm-devel', 'libstdc++-devel', 'sed', 'perl', 'gcc', 'rpm-build', 'automake', 'util-linux-devel', 'gettext', 'bison', 'mpfr-devel', 'bzip2-devel', 'libpipeline', 'procps-ng', 'grep', 'findutils', 'make', 'tar', 'libtool', 'go', 'linux-api-headers', 'filesystem', 'bash', 'ncurses', 'zlib', 'gmp', 'bzip2', 'elfutils-libelf', 'lua', 'popt', 'flex', 'libgomp-devel', 'mpc', 'sqlite-autoconf', 'rpm', 'coreutils', 'util-linux', 'gdbm', 'libgcc-devel', 'texinfo', 'autoconf', 'groff', 'binutils-devel', 'flex-devel', 'elfutils', 'gawk', 'zlib-devel', 'gmp-devel', 'glibc-devel', 'diffutils', 'gzip', 'patch', 'xz', 'cpio', 'man-pages']
2016-09-21 21:23:23,109 - build-dialog - INFO - Installing the build time dependent packages......
2016-09-21 21:23:23,127 - build-dialog - INFO - Installing rpms:  ncurses-devel
2016-09-21 21:23:23,200 - build-dialog - INFO - Finished installing the build time dependent packages......
2016-09-21 21:23:23,238 - build-dialog - INFO - Building rpm's for package:dialog
2016-09-21 21:23:23,251 - build-dialog - INFO - Copying... Source path :dialog-1.3-20160209.tgz Source filename: /root/photon/stage/SOURCES/dialog-1.3-20160209.tgz
2016-09-21 21:23:23,265 - build-dialog - INFO - Copying... Source path :dialog-incdir.patch Source filename: /root/photon/SPECS/dialog/dialog-incdir.patch
2016-09-21 21:23:23,278 - build-dialog - INFO - Copying... Source path :dialog-multilib.patch Source filename: /root/photon/SPECS/dialog/dialog-multilib.patch
2016-09-21 21:23:23,291 - build-dialog - INFO - Copying... Source path :dialog-libs.patch Source filename: /root/photon/SPECS/dialog/dialog-libs.patch
2016-09-21 21:23:23,293 - build-dialog - INFO - Building rpm....
2016-09-21 21:23:23,293 - build-dialog - INFO - rpmbuild -ba --clean --define \"dist .ph1\" --nocheck --define \"KERNEL_RELEASE 1.ph1\" --define \"dist .ph1\" --define \"photon_build_number d045311\" --define \"KERNEL_VERSION 4.4.20\" --define \"kernelsubrelease .11315201\" --define \"photon_release_version 1.0\" /usr/src/photon/SPECS//dialog.spec
2016-09-21 21:23:37,753 - build-dialog - INFO - RPM build is successful
2016-09-21 21:23:37,756 - SourcePackageInfo - INFO - Added source package to the list:dialog
2016-09-21 21:23:37,756 - build-dialog - INFO - Successfully built the package:dialog
2016-09-21 21:23:38,122 - build-dialog - INFO - Successfully destroyed chroot:/root/photon/stage/photonroot/build-dialog
2016-09-21 21:23:38,123 - PackageManager - INFO - Waiting to acquire scheduler lock
2016-09-21 21:23:38,123 - PackageManager - INFO - Checking for next possible packages to build
2016-09-21 21:23:38,123 - PackageManager - INFO - Waiting for all remaining worker threads
2016-09-21 21:23:38,123 - PackageManager - INFO - Released scheduler lock
2016-09-21 21:23:38,124 - PackageManager - INFO - Thread WorkerThread0 is going to rest
2016-09-21 21:23:38,124 - PackageManager - INFO - All packages built successfully
2016-09-21 21:23:38,124 - PackageManager - INFO - Terminated
2016-09-21 21:23:38,124 - /root/photon/stage/LOGS/Main - INFO - Writing Package info to the file:/root/photon/common/data/pkg_info.json
2016-09-21 21:23:38,125 - SourcePackageInfo - INFO - Writing source package list to the json file
Creating OSTree repo from local PRMs in ostree-repo.tar.gz...
ostree-repo.tar.gz already present, not creating again...
Building Photon Full ISO...
Building cloud image ova...
/root/photon/support/cloud-image-builder/cloud-image-build.sh /root/photon/support/cloud-image-builder ova /root/photon /root/photon/stage/common/data /root/photon/stage/photon-1.0-d045311.iso
+ BUILD_SCRIPTS_PATH=/root/photon/support/cloud-image-builder
+ IMG_NAME=ova
+ SRC_ROOT=/root/photon
+ GENERATED_DATA_PATH=/root/photon/stage/common/data
+ PHOTON_ISO_PATH=/root/photon/stage/photon-1.0-d045311.iso
+ PHOTON_STAGE_PATH=/root/photon/stage
+ ADDITIONAL_RPMS_PATH=
+ INSTALLER_PATH=/root/photon/stage/ova
+ ISO_MOUNT_FOLDER=/root/photon/stage/iso_mount
+ PHOTON_IMG_OUTPUT_PATH=/root/photon/stage/ova
+ VMDK_CONFIG_FILE=/root/photon/support/cloud-image-builder/ova/vmdk_ova.json
+ VMDK_CONFIG_SAFE_FILE=/root/photon/support/cloud-image-builder/ova/vmdk_safe_ova.json
+ mkdir -p /root/photon/stage/ova/installer
+ cp -R /root/photon/installer /root/photon/stage/ova/
+ cd /root/photon/stage/ova/installer
+ cp /root/photon/support/cloud-image-builder/ova/vmdk_ova.json /root/photon/support/cloud-image-builder/ova/vmdk_safe_ova.json
+ cp /root/photon/support/cloud-image-builder/mk-setup-vmdk.sh .
+ cp /root/photon/support/cloud-image-builder/mk-clean-vmdk.sh .
+ [[ ova != ova* ]]
+ '[' -e /root/photon/support/cloud-image-builder/ova/mk-setup-grub.sh ']'
++ date
++ md5sum
++ cut -f 1 -d ' '
+ PASSWORD=7b291cd1aba5906033580e7b7f899c03
+ sed -i s/PASSWORD/7b291cd1aba5906033580e7b7f899c03/ /root/photon/support/cloud-image-builder/ova/vmdk_safe_ova.json
+ '[' -n '' ']'
+ ./photonInstaller.py -p /root/photon/stage/common/data/build_install_options_ova.json -r /root/photon/stage/RPMS -v /root/photon/stage/ova/photon-ova -o /root/photon/stage/common/data -f /root/photon/support/cloud-image-builder/ova/vmdk_safe_ova.json
+ LFS_OPTION=
Setting up the disk...
+ VMDK_IMAGE_NAME=mydisk.vmdk
+ ROOT_PARTITION_SIZE=8

+ SWAP_PARTITION_SIZE=2
+ [[ 7 > 0 ]]
+ key=-rp
+ shift
+ case $key in
+ ROOT_PARTITION_SIZE=8
+ shift
+ [[ 5 > 0 ]]
+ key=-sp
+ shift
+ case $key in
+ SWAP_PARTITION_SIZE=0
+ shift
+ [[ 3 > 0 ]]
+ key=-n
+ shift
+ case $key in
+ VMDK_IMAGE_NAME=/root/photon/stage/ova/photon-ova.raw
+ shift
+ [[ 1 > 0 ]]
+ key=-m
+ shift
+ case $key in
+ LFS_OPTION=
+ [[ 0 > 0 ]]
+ mkdir -p /mnt/photon-disk
++ echo 8 + 0
++ bc
+ TOTAL_SIZE=8
+ echo 'Creating raw disk file ' /root/photon/stage/ova/photon-ova.raw ' of size ' 8
+ dd if=/dev/zero of=/root/photon/stage/ova/photon-ova.raw bs=1 seek=8589934592 count=0
Creating raw disk file  /root/photon/stage/ova/photon-ova.raw  of size  8
0+0 records in
0+0 records out
0 bytes copied, 8.4622e-05 s, 0.0 kB/s
+ chmod 755 /root/photon/stage/ova/photon-ova.raw
+ echo 'Associating loopdevice to raw disk'
Associating loopdevice to raw disk
++ losetup --show -f /root/photon/stage/ova/photon-ova.raw
+ DISK_DEVICE=/dev/loop3
+ echo 'Creating partition on raw disk'
+ '[' 0 -gt 0 ']'
+ sgdisk -n 1::+2M -n 2: -p /dev/loop3
Creating partition on raw disk
./mk-setup-vmdk.sh: line 86: sgdisk: command not found
Unexpected failure, please check the logs
+ cat /root/photon/support/cloud-image-builder/ova/vmdk_safe_ova.json
{
        "hostname": "photon-machine",
        "password":
                {
                        "crypted": false,
                        "text": "7b291cd1aba5906033580e7b7f899c03"
                },
        "type": "minimal",
    "size": {"root": "8", "swap": "0"},
    "public_key":"<ssh-key-here>"
}

+ rm /root/photon/support/cloud-image-builder/ova/vmdk_safe_ova.json
+ cd /root/photon/support/cloud-image-builder
++ losetup --show -f /root/photon/stage/ova/photon-ova.raw
+ DISK_DEVICE=/dev/loop4
+ echo 'Mapping device partition to loop device'
Mapping device partition to loop device
+ kpartx -av /dev/loop4
++ echo /dev/loop4
++ cut -c6-
+ DEVICE_NAME=loop4
+ echo DISK_DEVICE=/dev/loop4
DISK_DEVICE=/dev/loop4
+ echo ROOT_PARTITION=/dev/mapper/loop4p2
ROOT_PARTITION=/dev/mapper/loop4p2
+ rm -rf /root/photon/stage/ova/photon-ova
+ mkdir /root/photon/stage/ova/photon-ova
++ blkid -s UUID -o value /dev/mapper/loop4p2
+ UUID_VALUE=
+ mkdir -p /root/photon/stage/iso_mount
+ mount -o loop /root/photon/stage/photon-1.0-d045311.iso /root/photon/stage/iso_mount
mount: /dev/loop5 is write-protected, mounting read-only
+ mount -v -t ext4 /dev/mapper/loop4p2 /root/photon/stage/ova/photon-ova
mount: special device /dev/mapper/loop4p2 does not exist
+ rm -rf /root/photon/stage/ova/photon-ova/installer
+ rm -rf /root/photon/stage/ova/photon-ova/LOGS
+ cp /root/photon/stage/ova/photon-ova/etc/shadow /root/photon/stage/ova/photon-ova/etc/shadow.bak
cp: cannot stat '/root/photon/stage/ova/photon-ova/etc/shadow': No such file or directory
+ sed -e 's/^\(root:\)[^:]*:/\1*:/' /root/photon/stage/ova/photon-ova/etc/shadow.bak
/root/photon/support/cloud-image-builder/cloud-image-build.sh: line 83: /root/photon/stage/ova/photon-ova/etc/shadow: No such file or directory
+ rm -f /root/photon/stage/ova/photon-ova/etc/shadow.bak
+ rm -f /root/photon/stage/ova/photon-ova/etc/shadow-
+ rm -f /root/photon/stage/ova/photon-ova/etc/machine-id
+ touch /root/photon/stage/ova/photon-ova/etc/machine-id
touch: cannot touch '/root/photon/stage/ova/photon-ova/etc/machine-id': No such file or directory
+ rm -f /root/photon/stage/ova/photon-ova/etc/fstab
+ echo 'UUID=    /    ext4    defaults,barrier,noatime,noacl,data=ordered 1 1'
/root/photon/support/cloud-image-builder/cloud-image-build.sh: line 89: /root/photon/stage/ova/photon-ova/etc/fstab: No such file or directory
+ mkdir -p /root/photon/stage/ova/photon-ova/var/lib/cloud/seed/nocloud
+ cat
+ cat
+ mount -o bind /proc /root/photon/stage/ova/photon-ova/proc
mount: mount point /root/photon/stage/ova/photon-ova/proc does not exist
+ mount -o bind /dev /root/photon/stage/ova/photon-ova/dev
mount: mount point /root/photon/stage/ova/photon-ova/dev does not exist
+ mount -o bind /dev/pts /root/photon/stage/ova/photon-ova/dev/pts
mount: mount point /root/photon/stage/ova/photon-ova/dev/pts does not exist
+ mount -o bind /sys /root/photon/stage/ova/photon-ova/sys
mount: mount point /root/photon/stage/ova/photon-ova/sys does not exist
+ '[' -n '' ']'
+ '[' ova '!=' ova ']'
+ umount /root/photon/stage/ova/photon-ova/sys
umount: /root/photon/stage/ova/photon-ova/sys: mountpoint not found
+ umount /root/photon/stage/ova/photon-ova/dev/pts
umount: /root/photon/stage/ova/photon-ova/dev/pts: mountpoint not found
+ umount /root/photon/stage/ova/photon-ova/dev
umount: /root/photon/stage/ova/photon-ova/dev: mountpoint not found
+ umount /root/photon/stage/ova/photon-ova/proc
umount: /root/photon/stage/ova/photon-ova/proc: mountpoint not found
+ umount /root/photon/stage/ova/photon-ova
umount: /root/photon/stage/ova/photon-ova: not mounted
+ umount /root/photon/stage/iso_mount
+ rm -rf /root/photon/stage/iso_mount
+ echo 'Deleting device map partition'
Deleting device map partition
+ kpartx -d /dev/loop4
+ rm -rf photon-ova
+ echo 'Detaching loop device from raw disk'
Detaching loop device from raw disk
+ losetup -d /dev/loop4
+ cd ova
+ ./mk-ova-image.sh /root/photon/stage/ova /root/photon
+ PHOTON_IMG_OUTPUT_PATH=/root/photon/stage/ova
+ SRC_ROOT=/root/photon
+ rm -f /root/photon/stage/ova/photon-custom.vmdk /root/photon/stage/ova/photon-ova.vmdk
+ rm -f /root/photon/stage/ova/photon-custom-1.0-d045311.ova /root/photon/stage/ova/photon-custom-hw10-1.0-d045311.ova /root/photon/stage/ova/photon-ova-1.0-d045311.ova /root/photon/stage/ova/photon-ova-hw10-1.0-d045311.ova
+ sed 's|VMDK_IMAGE|/root/photon/stage/ova/photon-ova.vmdk|' vmx-template
+ sed 's|VMDK_IMAGE|/root/photon/stage/ova/photon-custom.vmdk|' vmx-template
+ cp ../update_custom_password.py /root/photon/stage/ova/
+ cd /root/photon/tools/src/vixDiskUtil
+ mkdir -p /root/photon/tools/bin
+ make clean
make[1]: Entering directory '/root/photon/tools/src/vixDiskUtil'
rm -f ../../bin/vixdiskutil
make[1]: Leaving directory '/root/photon/tools/src/vixDiskUtil'
+ make
make[1]: Entering directory '/root/photon/tools/src/vixDiskUtil'
g++ -o ../../bin/vixdiskutil -I/usr/include -L/usr/lib/vmware vixDiskUtil.cpp -ldl -lvixDiskLib -lvixMntapi -lvixDiskLibVim -lpthread -lssl -lfuse
make[1]: Leaving directory '/root/photon/tools/src/vixDiskUtil'
+ /root/photon/tools/bin/vixdiskutil -convert /root/photon/stage/ova/photon-ova.raw -cap 16000 /root/photon/stage/ova/photon-ova.vmdk
VixDiskLib: Invalid configuration file parameter. Failed to read configuration file.
Disk "/root/photon/stage/ova/photon-ova.vmdk" is open using transport mode "file".

 Done
+ /root/photon/tools/bin/vixdiskutil -wmeta toolsVersion 2147483647 /root/photon/stage/ova/photon-ova.vmdk
VixDiskLib: Invalid configuration file parameter. Failed to read configuration file.
Disk "/root/photon/stage/ova/photon-ova.vmdk" is open using transport mode "file".
+ cd /root/photon/stage/ova
+ mkdir -p /root/photon/stage/ova/temp
+ ovftool /tmp/vmx-temp.vmx /root/photon/stage/ova/temp/photon-ova.ovf
Opening VMX source: /tmp/vmx-temp.vmx
Opening OVF target: /root/photon/stage/ova/temp/photon-ova.ovf
Writing OVF package: /root/photon/stage/ova/temp/photon-ova.ovf
Transfer Completed
Completed successfully
+ cd /root/photon/stage/ova/temp
+ sed -i s/otherGuest/other3xLinux64Guest/g /root/photon/stage/ova/temp/photon-ova.ovf
+ sed -i '/\/VirtualSystem>/i \ \t<ProductSection> \n \t\t<Info>Information about the installed software</Info> \n \t\t<Product>Photon</Product> \n \t\t<Vendor>VMware Inc.</Vendor> \n \t\t<Version>1.0</Version> \n \t\t<FullVersion>1.0</FullVersion> \n \t</ProductSection> ' /root/photon/stage/ova/temp/photon-ova.ovf
+ rm -f /root/photon/stage/ova/temp/photon-ova.mf
+ openssl sha1 photon-ova-disk1.vmdk photon-ova.ovf
+ tar cf photon-ova-1.0-d045311.ova photon-ova.ovf photon-ova.mf photon-ova-disk1.vmdk
+ mv /root/photon/stage/ova/temp/photon-ova-1.0-d045311.ova /root/photon/stage/ova/
+ cp photon-ova.ovf photon-ova-hw10.ovf
+ sed -i s/vmx-11/vmx-10/g photon-ova-hw10.ovf
+ rm -f /root/photon/stage/ova/temp/photon-ova.mf
+ openssl sha1 photon-ova-disk1.vmdk photon-ova-hw10.ovf
+ tar cf photon-ova-hw10-1.0-d045311.ova photon-ova-hw10.ovf photon-ova-hw10.mf photon-ova-disk1.vmdk
+ mv /root/photon/stage/ova/temp/photon-ova-hw10-1.0-d045311.ova /root/photon/stage/ova/
+ cd /root/photon/stage/ova
+ rm -rf photon-custom
++ losetup --show -f /root/photon/stage/ova/photon-ova.raw
+ DISK_DEVICE=/dev/loop4
+ kpartx -av /dev/loop4
++ echo /dev/loop4
++ cut -c6-
+ DEVICE_NAME=loop4
+ rm -rf /root/photon/stage/ova/photon-custom
+ mkdir /root/photon/stage/ova/photon-custom
+ mount -v -t ext4 /dev/mapper/loop4p2 /root/photon/stage/ova/photon-custom
mount: special device /dev/mapper/loop4p2 does not exist
+ cp /root/photon/stage/ova/photon-custom/etc/shadow /root/photon/stage/ova/photon-custom/etc/shadow.bak
cp: cannot stat '/root/photon/stage/ova/photon-custom/etc/shadow': No such file or directory
+ sed -e 's/^\(root:\)[^:]*:/\1x:/' /root/photon/stage/ova/photon-custom/etc/shadow.bak
./mk-ova-image.sh: line 58: /root/photon/stage/ova/photon-custom/etc/shadow: No such file or directory
+ ./update_custom_password.py changeme /root/photon/stage/ova/photon-custom
Traceback (most recent call last):
  File "./update_custom_password.py", line 32, in <module>
    crypt_password(str(sys.argv[1]), str(sys.argv[2]))
  File "./update_custom_password.py", line 17, in crypt_password
    with open(shadow_filename, "w") as destination:
IOError: [Errno 2] No such file or directory: '/root/photon/stage/ova/photon-custom/etc/shadow'
+ rm -f /root/photon/stage/ova/photon-custom/etc/shadow-
+ rm -f /root/photon/stage/ova/photon-custom/etc/shadow.bak
+ chroot /root/photon/stage/ova/photon-custom /bin/bash -c 'chage -d 0 root'
chroot: failed to run command ‘/bin/bash’: No such file or directory
+ umount /root/photon/stage/ova/photon-custom
umount: /root/photon/stage/ova/photon-custom: not mounted
+ kpartx -d /dev/loop4
+ rm -rf photon-custom
+ echo 'Detaching loop device from raw disk'
Detaching loop device from raw disk
+ losetup -d /dev/loop4
+ /root/photon/tools/bin/vixdiskutil -convert /root/photon/stage/ova/photon-ova.raw -cap 16000 /root/photon/stage/ova/photon-custom.vmdk
VixDiskLib: Invalid configuration file parameter. Failed to read configuration file.
Disk "/root/photon/stage/ova/photon-custom.vmdk" is open using transport mode "file".

 Done
+ /root/photon/tools/bin/vixdiskutil -wmeta toolsVersion 2147483647 /root/photon/stage/ova/photon-custom.vmdk
VixDiskLib: Invalid configuration file parameter. Failed to read configuration file.
Disk "/root/photon/stage/ova/photon-custom.vmdk" is open using transport mode "file".
+ mkdir -p /root/photon/stage/ova/temp1
+ ovftool /tmp/vmx-temp-custom.vmx /root/photon/stage/ova/temp1/photon-custom.ovf
Opening VMX source: /tmp/vmx-temp-custom.vmx
Opening OVF target: /root/photon/stage/ova/temp1/photon-custom.ovf
Writing OVF package: /root/photon/stage/ova/temp1/photon-custom.ovf
Transfer Completed
Completed successfully
+ cd /root/photon/stage/ova/temp1
+ sed -i s/otherGuest/other3xLinux64Guest/g /root/photon/stage/ova/temp1/photon-custom.ovf
+ sed -i '/\/VirtualSystem>/i \ \t<ProductSection> \n \t\t<Info>Information about the installed software</Info> \n \t\t<Product>Photon</Product> \n \t\t<Vendor>VMware Inc.</Vendor> \n \t\t<Version>1.0</Version> \n \t\t<FullVersion>1.0</FullVersion> \n \t</ProductSection> ' /root/photon/stage/ova/temp1/photon-custom.ovf
+ rm -f /root/photon/stage/ova/temp1/photon-custom.mf
+ openssl sha1 photon-custom-disk1.vmdk photon-custom.ovf
+ tar cf photon-custom-1.0-d045311.ova photon-custom.ovf photon-custom.mf photon-custom-disk1.vmdk
+ mv /root/photon/stage/ova/temp1/photon-custom-1.0-d045311.ova /root/photon/stage/ova/
+ cp photon-custom.ovf photon-custom-hw10.ovf
+ sed -i s/vmx-11/vmx-10/g photon-custom-hw10.ovf
+ rm -f /root/photon/stage/ova/temp/photon-custom.mf
+ openssl sha1 photon-custom-disk1.vmdk photon-custom-hw10.ovf
+ tar cf photon-custom-hw10-1.0-d045311.ova photon-custom-hw10.ovf photon-custom-hw10.mf photon-custom-disk1.vmdk
+ mv /root/photon/stage/ova/temp1/photon-custom-hw10-1.0-d045311.ova /root/photon/stage/ova/
+ cd /root/photon/stage/ova
+ rm -rf /root/photon/stage/ova/temp/
+ rm -rf /root/photon/stage/ova/temp1/
+ rm -f /root/photon/stage/ova/photon-ova.raw
+ exit 0

**Comment by suezzelur** [comment]
There are multiple issues here:
sgdisk -n 1::+2M -n 2: -p /dev/loop3 Creating partition on raw disk ./mk-setup-vmdk.sh: line 86: sgdisk: command not found Unexpected failure, please check the logs

>Please install sgdisk utility - it is part of gdisk
----
kpartx -av /dev/loop4 ++ echo /dev/loop4 ++ cut -c6-

>The later versions of Ubuntu may require kpartx -avs (you may have to specify a sync option for partitions to show up). https://github.com/vmware/photon/blob/master/support/cloud-image-builder/ova/mk-ova-image.sh also calls kpartx, please add kpartx -avs there as well if you are building on Ubuntu

**Comment by suezzelur** [comment]
There are multiple places where kpartx is being used in the build process. You have not changed all of them - https://github.com/vmware/photon/blob/master/support/cloud-image-builder/cloud-image-build.sh
You can always build this in a full installation of Photon OS.

**Comment by sosher** [comment]
Hi, 
Well I moved to ubuntu 14.04 and I am getting better results.. 
"make cloud-image  IMG_NAME=ova" returns only the following error 

_VixDiskLib: Invalid configuration file parameter. Failed to read configuration file.
Disk "/root/photon/stage/ova/photon-ova.vmdk" is open using transport mode "file"._

I get the ova files 
When I deploy them through vsphere/workstation I get kernel panic

![image](https://cloud.githubusercontent.com/assets/4083019/18814107/d3709e58-8318-11e6-9d77-f01c46b9eae1.png)


BTW I dont know if its related but I used vddk6.0.0 and vddk6.0.2

Thanks

**Comment by YustasSwamp** [comment]
Hi, PARTUUID is not properly defined in /boot/grub/grub.cfg file. --Alexey

**Comment by sosher** [comment]
Thanks Alexey, 
But I dont want to fix the deployed ova, That would defeat the purpose of trying to compile ova. I want to mass deploy them.
I want to know if its related to the vixdisklib error I get while compiling it.

Thanks.

**Comment by suezzelur** [comment]
It is unrelated to the VixDisklib error which is benign. What does your kernel command line look like in grub.cfg?

**Comment by sosher** [comment]
Thanks, I have attached the file.
[grub.zip](https://github.com/vmware/photon/files/499912/grub.zip)

**Comment by YustasSwamp** [comment]
PARTUUID is not set. How it is possible in cloud image? Anish?

**Comment by YustasSwamp** [comment]
I able to reproduce it. 
"PARTUUID is not set" - In my case it was issue with blkid tool on the build machine (ubintu-14.04).
Will check in fix shortly.

**Comment by sosher** [comment]
Much appreciated

**Comment by YustasSwamp** [comment]
Fixed with this commit:
https://github.com/vmware/photon/commit/e7eb736dd07ccf22dd9312ccbcae2afa0207e68b
