### ISSUE TITLE
Adding 2nd interface, first start of docker.service hangs for 120s

### ISSUE THREAD

**Issue by embano1** [vmware/photon#536]
Hi,

Discovered the following behavior in a Vagrant environment with box version 1.2.0 (presumably it´s the same in non-vagrant environments):
- When docker.service starts for the first time systemd-networkd-wait-online is called as a pre-req
- If the machine has more than one interface (e.g. eth0/NAT and eth1/host-only) this hangs (120s) and fails, after that docker.service starts up
- I fixed it with a [script](https://github.com/embano1/Vagrant_Docker_Enterprise/blob/master/scripts/provision/fix_networkd-wait.sh) in my repo

Can you please confirm whether this is an issue with Vagrant box v1.2.0 only or a generic issue when there´s more than one interface?

Thank you

**Comment by gregmmurray** [comment]
@frapposelli have you seen this?

@YustasSwamp would you be able to replicate in a non-vagrant-box config?

**Comment by frapposelli** [comment]
@gregmmurray I don't think this is specific to vagrant, this seems like an issue with the systemd unit for docker.

**Comment by YustasSwamp** [comment]
Can you provide a steps to reproduce, please?
I'm not familiar with vagrant. 
@frapposelli can you repro it just with a docker?

**Comment by embano1** [comment]
Well, actually it´s related to systemd-networkd-wait-online.service. Please see my workaround here: https://github.com/embano1/Vagrant_Docker_Enterprise/blob/master/scripts/provision/fix_networkd-wait.sh

This service will hang if the instance is configured with more than one interface, failing after 120s (which then allows docker.service to proceed). Forcing -i eth0 at least fixes the service and should be sufficient IMHO.

**Comment by vinaykul** [comment]
@embano1 If I am guessing your scenario correctly, one of the two interfaces does not have an IP address. 

The default behavior of networkd-wait-online is to wait for all networkd managed link to come online (get an IP) for the wait-timeout duraiton. Please see https://www.freedesktop.org/software/systemd/man/systemd-networkd-wait-online.service.html

If you know which specific interfaces are sufficient for the wait-online criteria to be met, (in your case - eth0) you can specify as you did. But we cannot assume it will be eth0 for the general case and make a generic change to networkd-wait-online consumption by docker.

**Comment by sharathjg** [comment]
this is expected behavior for the systemd-networkd-wait-online service and I believe the default behavior is correct.

**Comment by embano1** [comment]
Thanks for getting back. Actually, I was providing fixed IPs in my Vagrantfile (https://github.com/embano1/Vagrant_Docker_Enterprise/blob/master/Vagrantfile) for eth1. eth0 did not cause any issues (and works with the workaround). Even after finishing to boot (i.e. all interfaces have IPs), systemd-networkd-wait hangs for 120s.

Anyways, if it was just my environment which causes this effect, I can easily live with the workaround.
