### ISSUE TITLE
Vagrant fails adding additional interfaces

### ISSUE THREAD

**Issue by lowescott** [vmware/photon#537]
After updating to v1.2.1 of the VirtualBox box for Photon OS (to fix password expiry error), Vagrant now fails with an error when the environment adds more than 1 NIC (the default NIC) to a Photon OS instance. The error text returned by Vagrant is:

``` bash
bash: line 2: awk: command not found
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mv /tmp/bash: line 2: awk: command not found /etc/systemd/network/

Stdout from the command:



Stderr from the command:

mv: cannot stat '/tmp/bash:': No such file or directory
mv: cannot stat 'line': No such file or directory
mv: cannot stat '2:': No such file or directory
mv: cannot stat 'awk:': No such file or directory
mv: cannot stat 'command': No such file or directory
mv: cannot stat 'not': No such file or directory
mv: cannot stat 'found': No such file or directory
```

I've also updated the vagrant-guests-photon plugin to v1.0.4, but the error persists. The only way around the error (that I've found so far) is to only use a single NIC.

More information:
Host OS = OS X 10.11.5
Vagrant version = 1.8.5
VirtualBox version = 5.1.4

**Comment by embano1** [comment]
Not sure whether it´s somewhat related to my issue reported and flagged as bug: https://github.com/mitchellh/vagrant/issues/7808

(that´s why I had to stay on Vagrant 1.8.1, may be you wanna go back to 1.8.1 and try again?)

**Comment by markpeek** [comment]
The code in the [vagrant-guests-photon](https://github.com/vmware/vagrant-guests-photon) uses awk which is not present in the base Photon box (v1.2.1). You should just use the Photon guest plugin provided by more recent versions of vagrant instead (uninstall is using ```vagrant plugin uninstall vagrant-guests-photon```). You probably will run into https://github.com/mitchellh/vagrant/issues/7808 now which I would suggest just hand-editing the code to fix the typo until the [PR](https://github.com/mitchellh/vagrant/pull/7873) is pushed out in a release.

**Comment by ppadmavilasom** [comment]
@lowescott this is pointing at vagrant-guests-photon not having gawk installed (which provides awk) in the base photon (as @markpeek mentions above) please open an issue with https://github.com/vmware/vagrant-guests-photon.

**Comment by lowescott** [comment]
@ppadmavilasom No need. If you follow the thread on #7808 (IIRC) then @markpeek talks about removing the vagrant-guests-photon plugin as it is no longer needed and then hand-editing the Vagrant code to fix a typo. This addresses the issue.
