### ISSUE TITLE
sudo: policy plugin failed session initialization

### ISSUE THREAD

**Issue by moander** [vmware/photon#538]
I am not able to get sudo to work on vanilla ova installation [photon-custom-hw11-1.0-13c08b6.ova](https://bintray.com/vmware/photon/download_file?file_path=photon-custom-hw11-1.0-13c08b6.ova)

I have tried this on several installations both before and after doing a tdnf update. I have also tried to `tdnf reinstall sudo`

```
$ tdnf install sudo
$ useradd ..
$ reboot
```

The installation generates a warning saying the group wheel already exists. Not sure if that is relevant?

Before modifying sudoers I get this error
```
$ sudo -i

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

Sorry, try again.
Sorry, try again.
sudo: 3 incorrect password attempts
```

I only press `enter` once after `sudo -i`. The Sorry, try again happends all by it self.

If I add NOPASSWD to the sudoers file I get a different result:

```
$ sudo -i
sudo: policy plugin failed session initialization
```

**Comment by sharathjg** [comment]
$sudo bash  
works. 
But this is currently being looked at and will update when fixed.

**Comment by YustasSwamp** [comment]
Thanks @moander for filling a bug.
We've just fixed this issue.
Solution for the 1.0 ova is to create sudo-i pam file.
# cp /etc/pam.d/sudo /etc/pam.d/sudo-i
