### ISSUE TITLE
/proc/sys/net/ipv4/tcp_syncookies: No such file or directory

### ISSUE THREAD

**Issue by moander** [vmware/photon#539]
tcp_syncookies is not available on vanilla [photon-custom-hw11-1.0-13c08b6.ova](https://bintray.com/vmware/photon/download_file?file_path=photon-custom-hw11-1.0-13c08b6.ova)

```
iptables[356]: /etc/systemd/scripts/iptables: line 18: /proc/sys/net/ipv4/tcp_syncookies: No such file or directory
```

Is it possible to make tcp_syncookies available on Photon OS or should I just ignore this message? From what I understand this is a highly recommended kernel fw feature.

**Comment by YustasSwamp** [comment]
It's already fixed in recent linux-esx package.
