### ISSUE TITLE
[Bug] Infinite loop on systemctl enable/disable

### ISSUE THREAD

**Issue by nop144d** [vmware/photon#540]
For details, please see: https://bugzilla.redhat.com/show_bug.cgi?id=1261612

Steps to reproduce:
Download and install VMware Log Insight Agent 3.6 (rpm)
For those having access to buildweb: https://buildweb.eng.vmware.com/ob/4148343/
For others: https://my.vmware.com/web/vmware/details?downloadGroup=VRLI-360&productId=598&rPId=12336

Actually, according to the above bug, any package providing both native initd service and systemd unit files will trigger the issue. Also this is a regression, as it is not reproducible on `DISTRIB_DESCRIPTION=VMware Photon 1.0 TP1`, probably because it doesn't have chkconfig at all.

Seems the fix is updating chkconfig to chkconfig-1.6-1.

Probably, I could come up with a Pull Request, but not sure how to deal with patches: https://github.com/vmware/photon/search?p=1&q=chkconfig&utf8=%E2%9C%93

**Comment by suezzelur** [comment]
This has been fixed in dev by the following [commit](https://github.com/vmware/photon/commit/0bd5fff8a24ceb980bc70fb9e9e02140d416a380), we will be updating the 1.0 repo soon with the fix

**Comment by nop144d** [comment]
Good, thanks! Feel free to close the issue when appropriate.

**Comment by nop144d** [comment]
Could you please upload a new ISO with this fix included, so we can download it from https://github.com/vmware/photon/wiki/Downloading-Photon-OS

**Comment by suezzelur** [comment]
We released a refresh build last week which has the fix. You can find it in the above link.
