### ISSUE TITLE
PCI rescan doesn't happen on hot add of device and slot number not updated.

### ISSUE THREAD

**Issue by govint** [vmware/photon#541]
1. I'm using Photon OS, Version 1.0 — OVA with virtual hardware v11 and when I hot-add a PVSCSI controller to the VM I need to manually do a rescan (echo 1 > /sys/bus/pci/rescan) to be able to detect the device.

2. Also, the PCI bus slot number doesn't get reflected in /sys/bus/pci/slots.

How can I get these resolved.

**Comment by YustasSwamp** [comment]
It was disabled in linux-esx kernel, which goes in .ova as a default kernel.

You can switch to generic kernel by:
`tdnf install linux` - if it was not installed yet
or 
redirect symlink /boot/photon.cfg to /boot/linux-<not esx>... .cfg
or
`tdnf remove linux; tdnf install linux`

and then reboot.

BTW, linux-esx version 4.4.20-3 and higher supports. It will be available in Photon 1.0 update.

Thanks,
--Alexey
