### ISSUE TITLE
Missing IP_VS module in the kernel module which cannot run docker swarm mode in 1.12

### ISSUE THREAD

**Issue by terpsho** [vmware/photon#543]
I should make my suggestion more explicitly. Need to have ipvsadm module in photon OS repo please.
--
I was playing with Docker 1.12 for its swarm mode. I found photon os do support docker swarm init/join but it always cannot publish external port when running docker create service. It took me a while to find out it is likely that we miss IP_VS module as described in https://github.com/docker/docker/issues/26930. 

I checked the kernel config:
CONFIG_IP_VS=m
CONFIG_IP_VS_IPV6=y
which should be an external module but I cannot find it in lsmod.

**Comment by YustasSwamp** [comment]
`modprobe ip_vs` works well.
ipvs modules are in /lib/modules/4.4.20/kernel/net/netfilter/ipvs/

Thanks,
--Alexey

**Comment by nbaillie** [comment]
i think this is my issue here also - [https://github.com/vmware/photon/issues/558](url)

im getting:
Nov 14 21:44:38 photon-iRwyifBuw dockerd[18459]: time="2016-11-14T21:44:38.567354883Z" level=warning msg="Running modprobe ip_vs failed with message: `modprobe: WARNING: Module ip_vs not found.`, error: exit status 1"
Nov 14 21:44:38 photon-iRwyifBuw dockerd[18459]: time="2016-11-14T21:44:38.569066006Z" level=error msg="Could not get ipvs family information from the kernel. It is possible that ipvs is not enabled in your kernel. Native loadbalancing will not work until this is fixed."

Is there a way to fix/workthrough this?

**Comment by nbaillie** [comment]
Thanks have you any idea when the 4.4.3.1-2 will be available?

**Comment by YustasSwamp** [comment]
Commit is merged https://github.com/vmware/photon/commit/44f551306868837374898884058211ac066a47e3
So you can build it.
1.0 repo will be updated shortly
