### ISSUE TITLE
ipvlan module not found 

### ISSUE THREAD

**Issue by morquai** [vmware/photon#545]
Dear All,

Installed PhotonOS using hw10 ova, everything runs great until 'modprobe ipvlan' (Invalid module format)
'modprobe macvlan' works, however. Any suggestions?

Thanks,

Way

```
Linux photon-F3QHEkTHJ 4.4.8-esx #1-photon SMP Tue Jun 7 08:04:49 UTC 2016 x86_64 GNU/Linux

root@photon-F3QHEkTHJ` [ ~ ]# modprobe ipvlan
modprobe: FATAL: Module ipvlan not found.
root@photon-F3QHEkTHJ [ ~ ]# 

root@photon-F3QHEkTHJ [ ~ ]# locate ipvlan
/usr/lib/modules/4.4.8/kernel/drivers/net/ipvlan
/usr/lib/modules/4.4.8/kernel/drivers/net/ipvlan/ipvlan.ko
root@photon-F3QHEkTHJ [ ~ ]# 

root@photon-F3QHEkTHJ [ ~ ]# insmod /usr/lib/modules/4.4.8/kernel/drivers/net/ipvlan/ipvlan.ko
insmod: ERROR: could not insert module /usr/lib/modules/4.4.8/kernel/drivers/net/ipvlan/ipvlan.ko: Invalid module format
root@photon-F3QHEkTHJ [ ~ ]# 

```

**Comment by YustasSwamp** [comment]
Hi,

Photon OVA goes with 2 kernel: generic (4.4.8) and vSphere optimized (4.4.8-esx).
By default active is -esx kernel.
ipvlan is available only in generic kernel.

to switch between kernel point /boot/photon.cfg symlink to proper .cfg file.
and then reboot.

to verify: `uname -r`

thanks,
--Alexey
