### ISSUE TITLE
Trouble getting started with photon and swarm

### ISSUE THREAD

**Issue by tclarke** [vmware/photon#546]
Had my vmware cluster admin create a small photon platform cluster to test out and I'm having trouble getting swarm running. It's a 6 node cluster (3 mgmt, 3 cloud). The network information I was given is:
```
Management Network ID: photon
DNS: 10.81.49.100 10.81.49.200
Gateway: 192.168.55.1
Netmask: 255.255.255.0
Container Network ID: photon-t
Networking Information: DHCP
```

I created a tenant with reasonable resources and a project using all of them. I created a network with the PortGroup photon-t. Finally, I tried to create a swarm cluster with:
```
photon cluster create -n Swarm2 -k Swarm --dns 10.81.49.100 --gateway 192.168.55.1 --netmask 255.255.255.0 --etcd1 1192.168.55.2 -s 2
```
I get`
```
 0h 0m 2s [==   ] CREATE_CLUSTER : CREATE_SWARM_CLUSTER_SETUP_ETCD | Step 2/4                       
```

and it hangs with the cluster showing an error.

**Comment by casualjim** [comment]
this issue needs to move to https://github.com/vmware/photon-controller

**Comment by tclarke** [comment]
moved
