### ISSUE TITLE
Docker 1.12 exposed port issue

### ISSUE THREAD

**Issue by deviantony** [vmware/photon#551]
I've got troubles accessing ports exposed by my containers with Docker 1.12 on Photon OS. I'm wondering if anybody has successfully managed to use Docker 1.12 on Photon?

Everything works well using Docker 1.11 but after an upgrade to Docker 1.12 I cannot access exposed ports anymore.

I've opened an issue on the docker repository, you can have more details here: https://github.com/docker/docker/issues/28003

**Comment by casualjim** [comment]
did you add an iptables entry for your port?

**Comment by deviantony** [comment]
Oh yeah I already changed the default policy to:

```
iptables -P INPUT   ACCEPT
```

**Comment by sharathjg** [comment]
I am unable to repro this. both using our repository docker 1.12.1 and by swapping out the docker.1.12.3 binaries that i downloaded from docker.

**Comment by deviantony** [comment]
Ok after a `tdnf makecache && tdnf distro-sync` it's now working !

Photon version:

```shell
# cat /etc/photon-release
VMware Photon Linux 1.0
PHOTON_BUILD_NUMBER=13c08b6
```

Strange though, previously I was just downloading the binaries from Docker (from 1.11 to 1.12, thay may have caused the problem).
