### ISSUE TITLE
consul does not create consul user and group in spec 

### ISSUE THREAD

**Issue by changpil** [vmware/photon#552]
Problem 1.
         Consul service failed to start.
         I could start service with commenting out "User=consul Group=consul"
         The problem was that consul user and group were not created when installing consul.
         I think Consul Spec file should something like this so that root user also can trigger the service as well as consul user can be created.
         getent passwd consul >/dev/null || useradd -r -g consul -d / -s /sbin/nologin -c "consul user" consul
        

Problem 2.
     when I tried to erase the consul package, I had an error.
    root@photon-d68ef6cb8781 [ /etc/yum.repos.d ]# tdnf erase consul
    Removing:
    consul                                      x86_64          0.6.4-1.ph1                    14.79 M

   Total installed size: 14.79 M
   Is this ok [y/N]:y
   Testing transaction
   Running transaction
  /var/tmp/rpm-tmp.iiyagN: line 1: fg: no job control
  Error(-1) : Unknown error -1601

**Comment by suezzelur** [comment]
consul package has been deprecated from Photon OS master branch.
