### ISSUE TITLE
Performance issue while running Jira in a Docker container on Photon OS

### ISSUE THREAD

**Issue by aswinprabhu** [vmware/photon#553]
I am trying to run Jira in a Docker container (image: aprabhu/jira:7.2.3 on hub.docker.com) on a simple Photon VM, which I deployed using the OVA. But I am facing performance issues in it. The Jira instance hangs up, only when user logs in. If the user login suceeds (after a long wait) the further screens are loading fine. I am not sure if I am missing some configuration. Can anyone please help?

**Comment by ppadmavilasom** [comment]
What does Jira recommend for memory and processor? does your instance meet those requirements? are there logs that you can look at to see whats going on? Sorry i havent setup Jira myself but i would start with the above.

**Comment by aswinprabhu** [comment]
My instance does meet the memory / CPU requirements. I believe there is no default restriction on those when running inside Docker.
Logs are under /opt/atlassian/jira/logs/catalina-<date>.log . But it doesn't give much information.

**Comment by aswinprabhu** [comment]
My instance does meet the memory / CPU requirements. I believe there is no default restriction on those when running inside Docker.
Logs are under /opt/atlassian/jira/logs/catalina-<date>.log . But it doesn't give much information.
But before we get deeper into this problem, is there any Docker level configuration which I may need to look at?

**Comment by vinaykul** [comment]
@aswinprabhu How responsive is same Jira container on a Ubuntu with similar processor, disk, and memory configuration?

**Comment by aprabhuv** [comment]
Based on my interaction with @sharathjg it appears to be a client-side issue, rather than a container issue really. Hence closing this issue. Thanks.

**Comment by aswinprabhu** [comment]
Based on my interaction with @sharathjg it appears to be a client-side issue, rather than a container issue really. Hence closing this issue. Thanks.
