### ISSUE TITLE
How to setup a cron job?

### ISSUE THREAD

**Issue by deviantony** [vmware/photon#554]
I'm searching for a way to setup a cron job on Photon, but did not found any.

No `crontab` or `/etc/cron*` directories available. Is there any way to achieve this?

**Comment by suezzelur** [comment]
You can install cronie -` tdnf install cronie`

**Comment by ppadmavilasom** [comment]
tdnf provides /etc/cron* would tell you which package brings it

**Comment by deviantony** [comment]
Awesome, thanks a lot guys !
