### ISSUE TITLE
Type=notify in nomad service blocks getting variables from EnvironmentFile 

### ISSUE THREAD

**Issue by changpil** [vmware/photon#556]
I could not start nomad service because "ExecStart=/usr/bin/nomad agent $OPTIONS -config /etc/nomad.d" in service file doe snot recognizes $OPTIONS.

set up 1. 
       cat /etc/default/nomad
       OPTIONS=-dev
set up 2.
     cat /etc/nomad.d/server.hcl 
     log_level = "DEBUG"
    data_dir = "/tmp/server1"
    server {
    enabled = true
    bootstrap_expect = 1
}

Error message  after "systemctl start nomad"
systemctl status nomad.service
● nomad.service - Nomad
   Loaded: loaded (/usr/lib/systemd/system/nomad.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2016-11-03 20:19:11 PDT; 8s ago
     Docs: https://nomadproject.io/docs/
  Process: 1947 ExecStart=/usr/bin/nomad agent $OPTIONS -config /etc/nomad.d/server.hcl (code=exited, status=1/FAILURE)
 Main PID: 1947 (code=exited, status=1/FAILURE)

Nov 03 20:19:11 gosc-static-ipv6.domain_name.com nomad[1947]: 2016/11/03 20:19:11.912620 [INFO] agent: requesting shutdown
Nov 03 20:19:11 gosc-static-ipv6.domain_name.com nomad[1947]: 2016/11/03 20:19:11.912631 [INFO] client: shutting down
Nov 03 20:19:11 gosc-static-ipv6.domain_name.com nomad[1947]: 2016/11/03 20:19:11.912646 [INFO] nomad: shutting down server
Nov 03 20:19:11 gosc-static-ipv6.domain_name.com nomad[1947]: 2016/11/03 20:19:11 [WARN] serf: Shutdown without a Leave
Nov 03 20:19:11 gosc-static-ipv6.domain_name.com nomad[1947]: 2016/11/03 20:19:11.912794 [INFO] client.rpcproxy: shutting down
Nov 03 20:19:11 gosc-static-ipv6.domain_name.com systemd[1]: nomad.service: Main process exited, code=exited, status=1/FAILURE
Nov 03 20:19:11 gosc-static-ipv6.domain_name.com systemd[1]: Failed to start Nomad.

I could run nomad service with commenting out Type.
--------------------------------------------------------------------
[Service]
#Type=notify
User=root
Group=root
EnvironmentFile=-/etc/default/nomad
ExecStart=/usr/bin/nomad agent $OPTIONS -config /etc/nomad.d
-------------------------------------------------------------------

**Comment by changpil** [comment]
I am not sure that nomad requires consul service.

[Unit]
Description=Nomad
Documentation=https://nomadproject.io/docs/
Wants=network-online.target
After=network-online.target consul.service
Requires=consul.service

**Comment by casualjim** [comment]
AFAICT it wants consul https://www.nomadproject.io/docs/agent/configuration/consul.html

> The consul stanza configures the Nomad agent's communication with Consul for service discovery and key-value integration. When configured, tasks can register themselves with Consul, and the Nomad cluster can automatically bootstrap itself.

**Comment by changpil** [comment]
I think that is users' option. 
What if a user wants to use nomad service without consul stanza?

**Comment by suezzelur** [comment]
nomad package has been deprecated from Photon OS master branch.
