### ISSUE TITLE
Required password change .ova not working.

### ISSUE THREAD

**Issue by SteloNLD** [vmware/photon#557]
I just imported the .ova two times! (Photon OS, Version 1.0 — OVA with virtual hardware v11 )

It is posible to login with root and changeme and it will ask for a password change but whatever i try it wont save it, after entering a new password it will return to the login screen and the password changeme is still active.

Any ideas?

**Comment by YustasSwamp** [comment]
Password change process consists of 3 questions:
1) current password?
2) new password?
3) repeat new password?

at a first step you need to enter current password!

**Comment by SteloNLD** [comment]
I am feeling really stupid right now, i already installed an ISO version so I did not give it a second thought.
either way you were really helpful.
