### ISSUE TITLE
How to persist iptable rules in Photon OS?

### ISSUE THREAD

**Issue by tsjfd** [vmware/photon#559]
Additional iptables settings (e.g. iptables -I INPUT -p tcp -d 192.168.0.123) are gone after a reboot. How can they survive in Photon OS?

**Comment by ppadmavilasom** [comment]
you have to save using iptables-save and restore using iptables-restore

**Comment by ppadmavilasom** [comment]
@sharathjg pointed me to this 
/etc/systemd/scripts/iptables is a script thats executed on iptables service start. so you can add your rules at the end of that script and the restore will be automatic.

**Comment by tsjfd** [comment]
this works!

**Comment by ozdeadmeat** [comment]
use the ip4save file instead

**Comment by rbucker** [comment]
the proper answer: ```iptables-save >/etc/systemd/scripts/ip4save```

and there is a variation for ipv6: ```ip6tables-save >/etc/systemd/scripts/ip6save```

**Comment by willmcenaney** [comment]
> the proper answer: `iptables-save >/etc/systemd/scripts/ip4save`
> 
> and there is a variation for ipv6: `ip6tables-save >/etc/systemd/scripts/ip6save`

Unless you need to edit one of the defaults it adds after importing those configs!

**Comment by ygbillet** [comment]
> the proper answer: `iptables-save >/etc/systemd/scripts/ip4save`
> 
> and there is a variation for ipv6: `ip6tables-save >/etc/systemd/scripts/ip6save`

Isn't it better to add the lines manually in ip4save instead of dumping iptable state ?

**Comment by chetwisniewski** [comment]
> the proper answer: `iptables-save >/etc/systemd/scripts/ip4save`
> 
> and there is a variation for ipv6: `ip6tables-save >/etc/systemd/scripts/ip6save`

This works if I run the script manually (/etc/systemd/scripts/iptables), but it doesn't seem to run automatically on boot. iptables service is enabled in systemd, but tables are empty on boot. Simply running the script then fixes it. Any reason that script isn't executing automatically on service start?

**Comment by xCharg** [comment]
I've tried to add this line manually to `/etc/systemd/scripts/ip4save`:

```
    # Allow connects from host 'zabbix' on port 10050 for agent passive connection
    -A INPUT -p tcp -m tcp -s zabbix --dport 10050 -j ACCEPT
```

and I've also tried to add this line manually to `/etc/systemd/scripts/iptables`

```
    # Allow connects from host 'zabbix' on port 10050 for agent passive connection
    iptables -A INPUT -p tcp -m tcp -s zabbix --dport 10050 -j ACCEPT
```
Both did not work, as in these lines to "survive" Photon OS restart, however `iptables -L` does not show this rule as active.

What am I doing wrong?

**Comment by snapshotleisure** [comment]
Hi @xCharg, sorry dont mean to bring up an old thread, but I have figured it out and just wanted to answer here for others who might be looking at this answer.

The saving of the file in  /etc/systemd/scripts/ip4save does work, but you need to put the new rule under the existing one for ssh. 

so your file should look like:
-A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
-A INPUT -p tcp --dport 10050 -j ACCEPT

I tested this out and it does survive the restart. I found reference to this in this link on steps 7.
https://docs.vmware.com/en/VMware-Telco-Cloud-Automation/1.9.5/com.vmware.tca.userguide/GUID-F7671C24-8C77-4A2E-83FA-FE07C89CB6F6.html

Thanks

**Comment by oliverkurth** [comment]
You can set the rules with the `iptables` command like for example:
```
iptables -A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
```
Then use `iptables-save > /etc/systemd/scripts/ip4save` to make it persistent.

**Comment by snapshotleisure** [comment]
ah yes, I thought i tried that previously however it didnt work, but I think I ran only iptables-save which is the problem. I thought iptables-save did the persistence, but you actually need the full command iptables-save > /etc/systemd/scripts/ip4save.

Thanks for clearing that up for me :)

**Comment by xCharg** [comment]
> Hi @xCharg, sorry dont mean to bring up an old thread, but I have figured it out and just wanted to answer here for others who might be looking at this answer.
> 
> The saving of the file in /etc/systemd/scripts/ip4save does work, but you need to put the new rule under the existing one for ssh.
> 
> so your file should look like: -A INPUT -p tcp -m tcp --dport 22 -j ACCEPT -A INPUT -p tcp --dport 10050 -j ACCEPT
> 
> I tested this out and it does survive the restart. I found reference to this in this link on steps 7. https://docs.vmware.com/en/VMware-Telco-Cloud-Automation/1.9.5/com.vmware.tca.userguide/GUID-F7671C24-8C77-4A2E-83FA-FE07C89CB6F6.html
> 
> Thanks

Thanks, but that doesn't work - as in it already is set this way. This is VMware vCenter appliance:

```
root@vcenter101 [ ~ ]# cat /etc/*release
DISTRIB_ID="VMware Photon OS"
DISTRIB_RELEASE="3.0"
DISTRIB_CODENAME=Photon
DISTRIB_DESCRIPTION="VMware Photon OS 3.0"
NAME="VMware Photon OS"
VERSION="3.0"
ID=photon
VERSION_ID=3.0
PRETTY_NAME="VMware Photon OS/Linux"
ANSI_COLOR="1;34"
HOME_URL="https://vmware.github.io/photon/"
BUG_REPORT_URL="https://github.com/vmware/photon/issues"
VMware Photon OS 3.0
PHOTON_BUILD_NUMBER=05f9d3d8d
root@vcenter101 [ ~ ]# 
root@vcenter101 [ ~ ]# cat /etc/systemd/scripts/ip4save   
# init
*filter
:INPUT DROP [0:0]
:FORWARD DROP [0:0]
:OUTPUT DROP [0:0]
# Allow local-only connections
-A INPUT -i lo -j ACCEPT
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
#keep commented till upgrade issues are sorted
#-A INPUT -j LOG --log-prefix "FIREWALL:INPUT "
-A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
# Allow connects from host 'zabbix' on port 10050 for agent passive connection
-A INPUT -p tcp -m tcp -s zabbix --dport 10050 -j ACCEPT
-A OUTPUT -j ACCEPT
COMMIT
root@vcenter101 [ ~ ]# 
```

After reboot zabbix agent "stops working", i.e. it can't accept connection. Also `iptables -L` does not have a rule.
