### ISSUE TITLE
vim with python support

### ISSUE THREAD

**Issue by casualjim** [vmware/photon#560]
Vim is built without python support, and quite a few vim plugins depend on that support. It also seems that the vim version we include is fairly old.

```
git:(dev) ✗ ! » vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 12 2016 05:45:12)
Compiled by root
```

When I want to use photon os as a linux to write some code on it's challenging.

```
± root@photon-dev:~/github/photon  
git:(dev) ✗ ! » vim vim.spec
github-issues.vim requires Python support, sorry :c
YouCompleteMe unavailable: requires Vim 7.4.143+
UltiSnips requires py >= 2.7 or py3
Error: +python required
Press ENTER or type command to continue
```

It's not so much that I'd like to use photon os as main dev env but when working on rpm specs etc it would be easier if I could do that on photon directly.

**Comment by ppadmavilasom** [comment]
this will have side effects on somebody who requires vim without python. not building vim with python support allows for using vim in minimal dependency / install size scenarios. building with python support will bring in python2-libs at least which is at 15.3MB where as vim is 1.8MB

**Comment by casualjim** [comment]
perhaps we can have a vim-minimal and vim-full or something?

**Comment by ppadmavilasom** [comment]
wont fix. vim requiring python support should build locally as needed.
