### ISSUE TITLE
Need updated OVS Version (2.6.1) in tdf repo

### ISSUE THREAD

**Issue by yfauser** [vmware/photon#562]
Hi Photon-OS Team,

I need the support for CT NAT (contract) including Load Balancing NAT entries in OpenVSwitch. This was introduced in OVS 2.6.0. See:
https://mail.openvswitch.org/pipermail/ovs-announce/2016-September/000087.html and
https://mail.openvswitch.org/pipermail/ovs-announce/2016-November/000093.html

As for the Kernel requirements it looks like Photon-OS 1.2.1 uses Kernel 4.4.8 that already includes the OVS Kernel Support for CT.

Can you Update the package available for Photon-OS? Right now only 2.4.0 seems to be available:

root [ /home/vagrant ]# tdnf info openvswitch
Name          : openvswitch
Arch          : x86_64
Epoch         : 0
Version       : 2.4.0
Release       : 3.ph1
Install Size  : 9.11 M (9549561)
Repo          : photon
Summary       : Open vSwitch daemon/database/utilities
URL           : http://www.openvswitch.org/
License       : ASL 2.0 and LGPLv2+
Description   : Open vSwitch provides standard network bridging functions and
support for the OpenFlow protocol for remote per-flow control of
traffic.

Thanks!

**Comment by vinaykul** [comment]
@yfauser openvswitch v2.6.1 is now available. Please try it out and let me know if there are any issues.
