### ISSUE TITLE
Cloud image OVA issues after 40b7db4

### ISSUE THREAD

**Issue by sosher** [vmware/photon#564]
Hi, 
after the latest commit 40b7db4 old issues popped up.
I am not sure but I think someone removed all the fixes done to address the issue.
It look like #534  and it was fixed with e7eb736 commit.
I am referencing  the kernel panic issue.

I am attaching the following snapshot , If needed I will try to pull the logs.
![image](https://cloud.githubusercontent.com/assets/4083019/20343883/e0cf6c74-abf8-11e6-841a-485adf896c6b.png)

Thanks, sorry for the badgering.

**Comment by suezzelur** [comment]
Can you sync to the latest dev code and retry? The issue you are facing should be fixed by https://github.com/vmware/photon/commit/e8c9015189d5525736c193bf15036bd45155dc0f

**Comment by sosher** [comment]
sure, but I can test it only tomorrow.
Will reply.

Thanks.

**Comment by sosher** [comment]
Hi , I have tested it.. And it works.
Thank you..

**Comment by YustasSwamp** [comment]
Depends on how stable dev is.
Usually several days
