### ISSUE TITLE
GnuTLS not properly configured with system trust store

### ISSUE THREAD

**Issue by deinspanjer** [vmware/photon#567]
I am encountering errors trying to make a TLS connection to a server with a self-signed cert.

I've narrowed it down to the gnutls library rejecting the connection.  I tried adding the cert to /etc/pki/tls/certs/ca-bundle.crt but it seems that file isn't picked up by gnutls-cli when trying a simple test like:

`gnutls-cli google.com`
I see the error:
Error setting the x509 trust file

Could it be that gnutls wasn't built with the correct --with flags?

**Comment by YustasSwamp** [comment]
Thanks for reporting. Fix is in progress.

**Comment by YustasSwamp** [comment]
fixed
https://github.com/vmware/photon/commit/c2b6fae083ddd95bc7980a2111ecaeff08dfe0a2
