### ISSUE TITLE
Please install at least one utf-8 locale for the photon OS image

### ISSUE THREAD

**Issue by xinfengliu** [vmware/photon#568]
I'm curious that when I just started to use photon 1.0 (installed through importing the photon 1.0 OVA to VMware Fusion) and found one thing was broken: 
non-ascii chars could not be displayed correctly. Then I ran:

root@harbor [ ~ ]# locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory

(/etc/locale.conf LANG env is en_US.UTF-8)

I had to run /usr/sbin/locale-gen.sh to generate en_US.UTF-8 with the input file /etc/locale-gen.conf, then it complained /usr/share/locale/locale.alias is not found, then I had to "touch /usr/share/locale/locale.alias" to work around it.

**Comment by YustasSwamp** [comment]
Thanks for reporting. Fix is in progress.

**Comment by YustasSwamp** [comment]
done
https://github.com/vmware/photon/commit/157f64c54630a8fb94f93930ab5cb3132e9c8c38
