### ISSUE TITLE
Package request: rabbitmq

### ISSUE THREAD

**Issue by egelev** [vmware/photon#569]
We need the rabbitmq messaging server. It would be nice to have it in the default tdnf repositories with all its dependencies.

**Comment by ppadmavilasom** [comment]
in dev https://github.com/vmware/photon/commit/4636a91a81cfc677f5b3f1a9dfc4adada6f6e7e4

**Comment by machenbach** [comment]
What is the status of this package?  Is it available?  I could not install it with tdnf

**Comment by smaliakkal** [comment]
package is available. package name rabbitmq-server

**Comment by machenbach** [comment]
How do I install it.  I'm using the vmware/photon docker image, and tdnf install rabbitmq-server says no such package.  Do I need to update a repo definition?
