### ISSUE TITLE
Add PowerShell Core and PowerCLI Core to the SPECS repo

### ISSUE THREAD

**Issue by lucdekens** [vmware/photon#574]
Is it possible to add the [powershell core](https://github.com/PowerShell/PowerShell) and [powercli core](https://labs.vmware.com/flings/powercli-core) packages to the SPECS repo?

**Comment by ppadmavilasom** [comment]
@lucdekens the last i checked, powershell and dotnet are still working on supporting new distros like photon. if you are interested, i can share what i have here and we can move it forward together.

There is some history of this effort in the dotnet cli issue - https://github.com/dotnet/cli/pull/4187

you can use this repo https://vmware.bintray.com/powershell/ to get powershell working in photon. the powershell rpm here is the prebuilt one from powershell alpha. i will move libicu and libunwind to photon specs soon

@alanrenouf were you thinking about adding powercli core as an rpm in photon?

**Comment by alanrenouf** [comment]
@ppadmavilasom That could be a future thing to do but at the moment with PowerShell Core being in Alpha and PowerCLI Core being a fling we clearly need to get to the point where this is more stable first.

**Comment by ppadmavilasom** [comment]
last we checked powershell builds on distros that powershell did not already support was not straightforward. maybe we can revisit when this situation changes. not addressing at the moment.
