### ISSUE TITLE
reset the password 

### ISSUE THREAD

**Issue by rajeshr988** [vmware/photon#575]
Hi , 
How can i reset the password of photon OS 

I forgotten the password

**Comment by YustasSwamp** [comment]
Try to follow this instruction:
https://github.com/vmware/photon/blob/master/docs/photon-os-troubleshooting-guide.md#resetting-a-lost-root-password

But I usually do it slightly different, 2 changes:
rw init=/bin/bash  -> rw init=/bin/bash panic=1
reboot -f -> exit
