### ISSUE TITLE
SSH Terminal issues

### ISSUE THREAD

**Issue by sosher** [vmware/photon#577]
Hi, This might seem odd and the solution is probably in front of me.
When I ssh to a compiled ova, any kind. I can use the backspace or the delete key. 
additionally when I try to use nano or tmux I receive the following errors:
"Error opening terminal: screen."
"open terminal failed: missing or unsuitable terminal: xterm"

What am I missing ? is it a package... why is it looking for xterm ?

Thanks.

**Comment by YustasSwamp** [comment]
export TERM=linux
or
install ncurses-terminfo

Or update to recent version of openssh-server which depends on ncurses-terminfo

**Comment by sosher** [comment]
Thanks.. Both solutions work.
Regarding the openssh-server , isn't it updated already in the specs dir? 
Again Thank you

**Comment by YustasSwamp** [comment]
It’s in.
https://github.com/vmware/photon/commit/9f61469c6447e91aace2dcfcfab287a4e1882f13

**Comment by sosher** [comment]
Great .
Thanks
