### ISSUE TITLE
How do you install DNS Server like bind in Photon ?

### ISSUE THREAD

**Issue by ytoguchi** [vmware/photon#578]
Hi everyone.

I'm trying to install DNS Server in VCSA 6.5 whose appliance is based on Photon OS.
Could you please tell me the way of DNS Server installation in Photon OS ?

**Comment by ppadmavilasom** [comment]
photon does not have the bind server components. bindutils will only install client components. 
dnsmasq is available which you can install by tdnf install dnsmasq
photon will have systemd-resolved enabled by default so when using another dns server, you will have to disable systemd-resolved or look at the systemd docs to redirect to your local dns server

**Comment by ytoguchi** [comment]
Thank you for your answer. I grasp that photon have DNSMASQ for resolving names of the server instead of BIND and when using DNSMASQ, I need to disable systemd-resolved which is enabled by default settings. I try to install DNSMASQ though tdnf command. I'll share the result of my experimental.
