### ISSUE TITLE
Package request: Update Mesos to 1.1.0

### ISSUE THREAD

**Issue by Henninho** [vmware/photon#579]
Hi, could you please update the mesos package in the repositories from 0.28.2 to the latest staple version 1.1.0? We'd like to update to that version and it would help us a lot.

Thanks
Jan-Hendrik

**Comment by suezzelur** [comment]
Fixed by commit https://github.com/vmware/photon/commit/70e7c4be5b67c7cceb4c17564f669efb2703ef1c and available in the photon_dev_x86_64 repo. Refer to admin guide to add the dev repo.
