### ISSUE TITLE
VIC requires GO 1.7 - how do I efficiently do the upgrade

### ISSUE THREAD

**Issue by jandrews65** [vmware/photon#581]
The gold release of VIC requires GO 1.7 but if you 'tdnf upgrade go' you get version 1.6

I know the newer version is via 'wget https://storage.googleapis.com/golang/go1.7.linux-amd64.tar.gz'
but from here it feels kludgey and I want to be exact.

What's the best way to upgrade?

**Comment by dthaluru** [comment]
Fixed. Go 1.7.4 available in Photon OS 1.0 updates.

**Comment by dthaluru** [comment]
Sorry my bad, the fix is not yet available in Photon OS 1.0 Updates. We are targeting to release package by end of this week.

**Comment by jandrews65** [comment]
Thank you!

**Comment by dthaluru** [comment]
Go 1.7.4 is available in Photon OS 1.0 Updates.
