### ISSUE TITLE
/etc/rc.local doesn't run when powering up the Photon OS VM

### ISSUE THREAD

**Issue by waynean** [vmware/photon#582]
Dear All, I have a question over here...
Question: how to execute script automatically when powering up Photon OS?
I try to edit the /etc/rc.local but it doesn't run when powering up the VM. Not sure if this is a correct method...
Thanks!

**Comment by YustasSwamp** [comment]
Photon OS uses systemd instead of legacy sysvinit.
Standard way for systemd to start/stop a script is to create .service file for it.
You can find many examples over internet. For instance: http://unix.stackexchange.com/questions/233468/how-does-systemd-use-etc-init-d-scripts

Thanks.
