### ISSUE TITLE
How to update the Docker Engine on Photon ?

### ISSUE THREAD

**Issue by FlyingTom** [vmware/photon#588]
Hello,

What is the procedure to update the Docker Engine on a Photon machine?

Because the latest version is 1.12.5 and the one on Photon is 1.12.1.

Thanks

**Comment by YustasSwamp** [comment]
We currently have 1.12.1 version.
https://github.com/vmware/photon/blob/dev/SPECS/docker/docker.spec

Next update will be to 1.13 version, probably.

**Comment by hreidar** [comment]
Any idea when we will see 1.13?

**Comment by FlyingTom** [comment]
Could you please also share the procedure to update the Docker engine without having to rebuild the entire Photon image.

Thanks

**Comment by munishpalmakhija** [comment]
I just upgraded docker on photon OS from 1.11 to 1.12.1 using following 3 commands

tdnf upgrade docker
systemctl daemon-reload
systemctl restart docker

**Comment by FlyingTom** [comment]
good to know, waiting the support for the version 1.13 ... :)

**Comment by thomsonac** [comment]
Any estimated date for 1.13 (presumably 1.13.1)?

**Comment by thomsonac** [comment]
I was successfully able to swap out the binaries to upgrade to 1.13.1 but naturally tdnf didn't realize the change and I'd really prefer to avoid the manual step for new deployments.  Any estimated date for adding 1.13.1 to the repos?

**Comment by aguiraf** [comment]
...waiting the support for newer docker version

**Comment by bt** [comment]
👍  Can we please get 1.13.1 to the repos ASAP?

I'm trying to use `docker-compose` version 3 and it's not working because it requires at least `> 1.13.0`.

**Comment by darrenparkinson** [comment]
Any update on this -- I'm trying to use the splunk-format option which doesn't seem to be available until 1.13.  Thanks.

**Comment by ppadmavilasom** [comment]
There are some build process changes and an upcoming release causing delays. Will follow up and provide an update today

**Comment by ppadmavilasom** [comment]
Please use docker image from https://github.com/docker/docker/releases/tag/v1.13 I dont have an ETA on when this will be in photon repos at the moment.

**Comment by darrenparkinson** [comment]
Thanks for the update.

**Comment by bt** [comment]
@ppadmavilasom Thanks for the update. I believe the link should be https://github.com/docker/docker/releases/tag/v1.13.0.

Can you confirm that we can just download the image from there and do a drop-in replacement? It won't affect the stability of the Photon image (ie. no dependencies, etc.)?

I'm running this in production so that's why I'm confirming.

**Comment by casualjim** [comment]
I've been running this 17.03 series on a photon vm for a while
https://github.com/docker/docker/releases/tag/v17.03.1-ce

I install with this
```
curl -L'#' https://get.docker.com/builds/Linux/x86_64/docker-17.03.1-ce.tgz | sudo tar -C /usr/bin -xzf - 
```

**Comment by munishpalmakhija** [comment]
This would require to un-install existing docker on photonos , What steps do you follow for that ?

**Comment by ppadmavilasom** [comment]
tdnf erase docker

**Comment by casualjim** [comment]
I just copy the binaries over the previous ones and restart docker. Everything is statically linked so it's got no dependencies anywhere else on the system.

to do it cleanly

```shell
tdnf erase -y docker

curl -L'#' https://get.docker.com/builds/Linux/x86_64/docker-17.03.1-ce.tgz | sudo tar -C /usr/bin -xzf - 

groupadd -r docker

echo '[Unit]
[Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
After=network.target docker.socket
Requires=docker.socket

[Service]
Type=notify
ExecStart=/usr/bin/dockerd -H fd:// -s overlay2 
ExecReload=/bin/kill -s HUP $MAINPID
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity
TasksMax=infinity
TimeoutStartSec=0
Delegate=yes
KillMode=process

[Install]
WantedBy=multi-user.target
' > /etc/systemd/system/docker.service

echo '[Unit]
Description=Docker Socket for the API
PartOf=docker.service

[Socket]
ListenStream=/var/run/docker.sock
SocketMode=0660
SocketUser=root
SocketGroup=docker

[Install]
WantedBy=sockets.target
' > /etc/systemd/system/docker.socket

systemctl enable docker
systemclt start docker
```

**Comment by steve-gray** [comment]
You forgot one line up front, if you're using the stock image: `tndf install tar`

**Comment by ppadmavilasom** [comment]
photon is building docker from sources from 2.0 onwards and will be updating on a regular basis as and when upstream updates are available.

**Comment by fojminc** [comment]
Now I'm just updating  my Photon 1.0 to 2.0. I have found that the docker version is:
Docker version 17.06.0-ce, build 02c1d87
Current released version is 17.12. 
What are your plans? I have to decide to go with manual installation or we will get the latest image in the photon repo.

**Comment by jghartin2008** [comment]
I too want to know if we are updating via repo as well. We have Photon OS servers with Auto Deploy Proxy Cache containers on each of our sites. We would like to consistently pull updates from repo and not have to worry about manual installs.

**Comment by ppadmavilasom** [comment]
Photon's intent is to update docker when new versions are available. However, the ETA will be affected by other ongoing work. CVEs if any will be addressed with priority. You can send a PR and photon will be glad to add it if urgent.

**Comment by jnovack** [comment]
> photon is building docker from sources from 2.0 onwards and will be **updating on a regular basis** as and **when upstream updates are available**.

@ppadmavilasom There have been 3 release versions of Docker pushed upstream since 17.06 was added to the OS.

Is it likely we will see an update soon?
