### ISSUE TITLE
Max Map Count

### ISSUE THREAD

**Issue by mzac** [vmware/photon#590]
I have been doing this on my systems but it could be a nice default (for Elasticsearch for example) and it might be good to have it as a default?

`echo "vm.max_map_count=262144" >> /etc/sysctl.d/vm.conf`

**Comment by suezzelur** [comment]
We have kept this at the recommended kernel default for generic application usage. Agree that this should be set if we package elasticsearch as a config property inside the rpm. For now, prefer to leave it at the default.
