### ISSUE TITLE
Docker 1.12.6 security advisory

### ISSUE THREAD

**Issue by mzac** [vmware/photon#591]
Looks like it would be good to upgrade Docker to 1.12.6 to fix this CVE?

https://www.twistlock.com/2017/01/11/docker-1-12-6-security-advisory/

https://github.com/docker/docker/releases/tag/v1.12.6

**Comment by xiaolin-vmware** [comment]
Updated to v1.12.6 in commit cbd6ae0.

**Comment by suezzelur** [comment]
This is available in the 1.0 updates repo.
