### ISSUE TITLE
Cannot start Mesos slave service

### ISSUE THREAD

**Issue by RealLinkers** [vmware/photon#594]
Hello,

I was setting up Mesos cluster with the example provided

https://github.com/vmware/photon/wiki/Install-and-Configure-a-Production-Ready-Mesos-Cluster-on-Photon-OS

I can setup the master, I can see the UI and everything is working fine that way. However, when I try to setup Mesos slave node's I run into this error

root@pt-mesos-node1 [ /var/log ]# systemctl start mesos-slave Failed to start mesos-slave.service: Activation of org.freedesktop.systemd1 timed out

I haven't found any similar issues.
I am using the same config file (except the IP's are changed).

Here's my service config file
[Unit]
Description=Photon instance running as a Mesos slave
After=network-online.target,docker.service

[Service]
Restart=on-failure
RestartSec=10
TimeoutStartSec=0
ExecStartPre=/usr/bin/rm -f /tmp/mesos/meta/slaves/latest
ExecStart=/bin/bash -c "/usr/sbin/mesos-slave 
--master=zk://192.168.20.31:2181,192.168.20.33:2181,192.168.20.35:2181/mesos 
--hostname=$(/usr/bin/hostname) 
--log_dir=/var/log/mesos_slave 
--containerizers=docker,mesos 
--docker=/usr/bin/docker 
--executor_registration_timeout=5mins 
--ip=192.168.20.36"

[Install]
WantedBy=multi-user.target

**Comment by sarchoi** [comment]
"Activation of org.freedesktop.systemd1 timed out" looks systemctl itself issue which can be resolved after restart the VM. Could you let us know which version of Mesos and Photon OS you are using?

**Comment by sharathjg** [comment]
Closing due to lack of repro. Please reopen if it still exists.
