### ISSUE TITLE
24 character limit for hostname?

### ISSUE THREAD

**Issue by lamw** [vmware/photon#6]
I noticed we limit the "hostname" configuration to 24 characters, why is that?

For hostname, I normally specify FQDN and I was trying to use the following: 
*photon.primp-industries.com*

![screen shot 2015-04-20 at 3 15 45 pm](https://cloud.githubusercontent.com/assets/602199/7241694/2b791dfa-e770-11e4-98ab-aae6472a211b.png)

**Comment by mbassiouny** [comment]
This is fixed in dev branch. commit 61dabd25d49a2135ca8d07a0ccde6ad290c98c51
