### ISSUE TITLE
upgrading go fails with errors

### ISSUE THREAD

**Issue by reachrkr** [vmware/photon#602]
Hello , 
Upgrading go package fails with warning. 

Photon Full installation used  : photon-1.0-13c08b6.iso

root@photon-master [ ~ ]# tdnf upgrade go

> 

Upgrading:
go                                  x86_64       1.6.3-1.ph1            219.92 M

Total installed size: 219.92 M
Is this ok [y/N]:y

Downloading:
go                                    57584085    100%
Testing transaction
Running transaction
_/var/tmp/rpm-tmp.DN1lXh: line 2: syntax error near unexpected token `then'
/var/tmp/rpm-tmp.DN1lXh: line 2: `if[ $1 -eq 0 ]; then'_
Complete!

**Comment by ppadmavilasom** [comment]
this script syntax error is fixed here: https://github.com/vmware/photon/commit/e8230c683bd3f857d5925bb7941e185fd2891f8e
