### ISSUE TITLE
Error while downloading gnupg  package in photon os

### ISSUE THREAD

**Issue by ssinghvi20** [vmware/photon#605]
When I tried the workaround listed in https://github.com/vmware/photon/issues/476 ,
I am facing following issue :

Refreshing metadata for: 'VMware Photon Linux Dev(x86_64)'
Refreshing metadata for: 'VMware Photon Linux 1.0(x86_64)'
Refreshing metadata for: 'VMware Photon Linux 1.0(x86_64)Updates'
Refreshing metadata for: 'VMware Lightwave 1.0(x86_64)'
Refreshing metadata for: 'VMware Photon Extras 1.0(x86_64)'

Installing:
libksba x86_64 1.3.4-2.ph1 277.32 k
libgcrypt x86_64 1.6.5-3.ph1 953.19 k
pth x86_64 2.0.7-1.ph1 78.09 k
gnupg x86_64 2.0.30-1.ph1 7.33 M

Total installed size: 8.61 M

Upgrading:
bash x86_64 4.4-1.ph1 2.96 M
pcre x86_64 8.39-2.ph1 960.91 k
readline x86_64 7.0-1.ph1 328.63 k

Total installed size: 4.22 M

Reinstalling:
lua x86_64 5.3.2-2.ph1 612.40 k

Total installed size: 612.40 k
Is this ok [y/N]:y

Downloading:
gnupg 3138574 100%
pth 38756 100%
libgcrypt 401858 100%
libksba 133541 100%
lua 293190 100%
readline 138003 100%
pcre 384786 100%
bash 980361 100%
Found 1 problems
libreadline.so.6()(64bit) is needed by (installed) lua-5.3.2-2.ph1.x86_64
Found 1 problems
libreadline.so.6()(64bit) is needed by (installed) lua-5.3.2-2.ph1.x86_64
Error(1515) : rpm check reported errors

**Comment by ppadmavilasom** [comment]
please do the following
 tdnf erase lua
 tdnf distro-sync --refresh
 tdnf install gnupg
