### ISSUE TITLE
Systemd UseRoutes=false not working

### ISSUE THREAD

**Issue by narmitag** [vmware/photon#606]
I'm seeing the same issue as mention here in the latest photon iso

https://github.com/systemd/systemd/issues/2282

Is the change mentioned in it included in the latest systemd in photon? I can seem to work it out.

I'm running with 2nics and eth1 is still picking up a route even with

[Match]
Name=eth1
[Network]
DHCP=ipv4 
[DHCP] 
ClientIdentifier=mac 
UseRoutes=false

**Comment by narmitag** [comment]
appears the version in the dev repo fixed this issue but using the dev repo creates new problems

    base-01: Found 1 problems
    base-01: libreadline.so.6()(64bit) is needed by (installed) lua-5.3.2-2.ph1.x86_64
    base-01: + tdnf install -y python3
    base-01: Found 1 problems
    base-01: libreadline.so.6()(64bit) is needed by (installed) lua-5.3.2-2.ph1.x86_64
    base-01: Error(1515) : rpm check reported errors

**Comment by ppadmavilasom** [comment]
could you please try with --refresh 
tdnf install -y python3 --refresh or do tdnf makecache then do the install?

**Comment by ppadmavilasom** [comment]
i tried and the above suggestion might not fix the issue. the following works from a 1.0 install where i did not have dev repo but later added it. after adding dev repo, 

 tdnf erase lua
 tdnf distro-sync --refresh
 tdnf install -y python3
