### ISSUE TITLE
Upgrade system via tdnf

### ISSUE THREAD

**Issue by waghanza** [vmware/photon#607]
Hello all,

Running the `latest` **photon** version (on `Docker`), I can not update my system

~~~
tdnf update
~~~

gives me an

~~~
...
Testing transaction
Running transaction
Creating ldconfig cache
Error(-1) : Unknown error -1601
~~~

My **/etc/photon-release**
~~~
VMware Photon Linux 1.0
PHOTON_BUILD_NUMBER=62c543d
~~~

**Comment by sbinev** [comment]
We are experiencing the same issue. This leads to running older versions of various packages (openssl, glibc,gstreamer, expat, curl, pcre, bash, bzip2, etc)

Since running these older packages and currently this issue is preventing their upgrade many security scans are failing and preventing the use of Photon OS in production!

The priority of this ticket should be raised as a result of the above.

**Comment by ppadmavilasom** [comment]
@waghanza this is because the filesystem package update does not work from docker as it attempts to update /sys which is read only from docker. I will update the vmware/photon image in docker, test your scenario and update here.

**Comment by ppadmavilasom** [comment]
docker image vmware/photon is updated.

**Comment by sbinev** [comment]
@ppadmavilasom Looking at https://hub.docker.com/r/vmware/photon/tags/ I'm not seeing any update. What am I doing wrong?

**Comment by waghanza** [comment]
@sbinev The above links show an update **10 hours** `ago`
@ppadmavilasom still having the problem. seems to be with **filesystem** `1.0-9.ph1`

**Comment by ppadmavilasom** [comment]
@waghanza this is the image i am using now
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
vmware/photon       latest              45e723970500        19 hours ago        127.8 MB

from a container launched with this image,
root [ / ]# rpm -q filesystem
filesystem-1.0-9.ph1.x86_64
and i see no pending updates. is this not the case with your test? Could you check if the image is updated?

**Comment by ppadmavilasom** [comment]
please reopen if you continue to see these issues. the root cause is update of filesystem package. vmware/photon is updated to the latest filesystem and this issue should be resolved if you update the container image.

**Comment by waghanza** [comment]
still having `Error(-1) : Unknown error -1601` on **lastest** `photon`
and I see `filesystem-1.0-7.ph1.x86_64` when searching actual release of **filesystem**

PS : if it helps, I'm using this `Dockerfile`
~~~dockerfile
FROM photon:latest
~~~

**Comment by waghanza** [comment]
with 
~~~dockerfile
FROM vmware/photon:latest
~~~
**filesystem** version is `filesystem-1.0-9.ph1.x86_64` 

so this is **a** solution
