### ISSUE TITLE
pinentry module in photon os

### ISSUE THREAD

**Issue by psura** [vmware/photon#608]
One of my GPG command depends on pinentry and looks like it's not available. Appreciate any pointers. Here are more details on my OS version and what I tried so far:

About pinentry package:
https://www.gnupg.org/related_software/pinentry/index.en.html
https://www.gnupg.org/download/index.html#pinentry

I am trying to run a GPG command that verifies a passphrase by first signing a random file using user supplied fingerprint and passphrase

gpg2 -q --sign --local-user {hide-fingerprint} --passphrase-fd 0 --no-tty -o /dev/null /path-to/some-file-to-sign.txt && echo "The correct passphrase was entered."

Here is part of the exception from my logs.
[checkProcess][Process completed with [exitValue=2]. Captured standard output/error: 
gpg-agent[279]: can't connect to the PIN entry module: IPC connect call failed
gpg-agent[279]: command get_passphrase failed: No pinentry
gpg: problem with the agent: No pinentry
gpg: skipped "{hide-fingerprint}": Operation cancelled
gpg: signing failed: Operation cancelled
--------------------------------------------------------
root [ ~ ]# cat /etc/photon-release                                            
VMware Photon Linux 1.0
PHOTON_BUILD_NUMBER=62c543d
root [ ~ ]#  

root [ ~]# tdnf search pinentry                                   
libgpg-error : libgpg-error
libgpg-error : libgpg-error
libgpg-error : libgpg-error
libgpg-error : libgpg-error
libgpg-error : libgpg-error

root [ ~ ]# tdnf install pinentry                                  
No package pinentry available
Error(1011) : No matching packages

**Comment by ppadmavilasom** [comment]
pinentry is not currently available in photon. 
the search match you have is from libgpg-error package containing a file which has the text entry "pinentry" in it.

**Comment by ppadmavilasom** [comment]
pinentry is getting added to photon dev branch.
