### ISSUE TITLE
Invoke-vmscript does not work with PhotonOS

### ISSUE THREAD

**Issue by fojminc** [vmware/photon#609]
Invoke-VMScript -VM $vm -ScriptText "ls" -GuestUser $user -GuestPassword $passwd

Although the username is root and the password is correct, I am unable to run a command inside PhotonOS.
Invoke-VMScript : 2/13/2017 3:48:13 PM    Invoke-VMScript        Failed to authenticate with the guest operating
system using the supplied credentials.
At line:1 char:1
+ Invoke-VMScript -VM $vm -ScriptText "ls" -GuestUser $user -GuestPassword $passwd
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-VMScript], InvalidGuestLogin
    + FullyQualifiedErrorId : Client20_VmGuestServiceImpl_RunScriptInGuest_ViError,VMware.VimAutomation.ViCore.Cmdlets
   .Commands.InvokeVmScript

**Comment by ppadmavilasom** [comment]
@kaushik229 any updates on this?

**Comment by kaushik229** [comment]
Hi @fojminc 

Can you please provide some more information on this ?

1. Who provides this Invoke-VMScripts ? Is it provided by photon OS ?
2. How this connects to Guest OS ? which application or port ?
3. What are detail steps to reproduce the problem ?

Thanks,
Kaushik

**Comment by fojminc** [comment]
There is tool called powerCLI provided by vmware. This tool gives the possibility to manage virtual machines and also run  commands inside a linux virtual machine. This looks not working with PhotonOS.
To reproduce the problem you need a PhotonOS running in vSphere environment and PowerCLI installed on a windows machine. 
https://my.vmware.com/web/vmware/details?downloadGroup=PCLI550&productId=352
When you are connected to your vCenter server just run the following command:
 Invoke-VMScript -VM $vm -ScriptText "ls" -GuestUser $user -GuestPassword $passwd
where vm is the virtual machine object, guestuser is root, guestpassword is the password of the user 'root'.

**Comment by jtauke** [comment]
I'm also running into this issue.  Guest authentication fails no matter what I try.  Mildly annoying that VMware's container OS isn't compatible with their own PowerCLI.

**Comment by YustasSwamp** [comment]
show me `cat /etc/shells`, please?

**Comment by fojminc** [comment]
cat /etc/shells
/usr/bin/tcsh
/usr/bin/csh

**Comment by YustasSwamp** [comment]
thanks!
try to add /bin/bash to this list and try invoke-vmscript again.

**Comment by fojminc** [comment]
Thank you! It looks working after first tests 👍 
How did you find out to try this out?

**Comment by YustasSwamp** [comment]
Info from powerCLI team.
Good to know that it helped.
