### ISSUE TITLE
vmware tools guest login not working due to PAM

### ISSUE THREAD

**Issue by tompscanlan** [vmware/photon#611]
Looks like the pam module for pam_unix_auth.so isn't available or working, or the etc/pam.d/vmtoolsd is incorrectly referencing that module.  Ssh authentication is working, but same credentials via guest tool login is not working.

I've downloaded and booted into the ova from https://bintray.com/vmware/photon/download_file?file_path=photon-custom-hw11-1.0-62c543d.ova

Failing with user:password auth
`govc guest.ls ...`

Working with same user and password:
`ssh root@xxxx`

journalctl: 
```
Feb 25 16:57:23 photon-machine VGAuth[282]: PAM unable to dlopen(/usr/lib/security/pam_unix_auth.so): /usr/lib/security/pam_unix_auth.so: cannot open shared object file: No such
Feb 25 16:57:23 photon-machine VGAuth[282]: PAM adding faulty module: /usr/lib/security/pam_unix_auth.so
Feb 25 16:57:23 photon-machine VGAuth[282]: PAM unable to dlopen(/usr/lib/security/pam_unix_acct.so): /usr/lib/security/pam_unix_acct.so: cannot open shared object file: No such
Feb 25 16:57:23 photon-machine VGAuth[282]: PAM adding faulty module: /usr/lib/security/pam_unix_acct.so
Feb 25 16:57:25 photon-machine VGAuth[282]: vmtoolsd: Username and password mismatch for 'root'.
```

/etc/pam.d/vmtoolsd:
```
#%PAM-1.0
auth       required         pam_shells.so
auth       sufficient       pam_unix.so shadow
auth       required         pam_unix_auth.so shadow
account    required         pam_shells.so
account    sufficient       pam_unix.so
account    required         pam_unix_acct.so
```

Solution:
Replace /etc/pam.d/vmtoolsd with /etc/pam.d/sshd, which is known to be working.

/etc/pam.d/sshd:
```
# Begin /etc/pam.d/sshd

auth            include         system-auth
account         include         system-account
password        include         system-password
session         include         system-session

# End /etc/pam.d/sshd
```

After replacing that pam file with the working ssh version, I can now run the `govc guest.ls ...`

**Comment by ppadmavilasom** [comment]
Linux-PAM-1.2.1-4 in photon-updates has the fix.
