### ISSUE TITLE
How to change locale?

### ISSUE THREAD

**Issue by JPustkuchen** [vmware/photon#612]
Hello and thank you very much for this great project.

I have a German Keyboard and couldn't figure out how to change locale to that. I tried severaly ways but none of them worked. Working with photon is really hard with a non-EN keyboard.

Could you please tell how to change the locale / keyboard and perhaps add a related FAQ question?

Thank you very much!

**Comment by ppadmavilasom** [comment]
have you tried the instructions at: http://www.linuxfromscratch.org/lfs/view/systemd/chapter07/locale.html

**Comment by sarchoi** [comment]
If you can't see all the locales under /usr/share/i18n/locales, then you need to install glibc-i18n package first. Could you please try this?

1. run command 'tdnf install glibc-i18n'
2. edit **/etc/locale-gen.conf** by adding new line, for example 'de_DE    UTF.8'
3. run command 'locale-gen.sh de_DE' (upon step 2)
4. run 'export LANG=de_DE.UTF-8'
5. check by running 'locale' which shows current locale.

**Comment by JPustkuchen** [comment]
Thank you very much, but both did not work:
tdnf install globc-i18n gives: "Error(1011): No matching packages" :(

**Comment by sarchoi** [comment]
@JPustkuchen, is 'globc' a typo, and did you try to install 'glibc-i18n' actually? If it's failed to install glibc-i18n, then the setting of the repositories need to be updated. The link below has general information regarding tdnf command.

https://github.com/vmware/photon/wiki/Frequently-Asked-Questions#q-where-can-i-get-the-latest-version-of-a-package  

Could you please also check the version of your Photon OS, using 'uname -r'? I can try out the same build.

**Comment by rongrongqiu** [comment]
@JPustkuchen, glibc-i18n is actually not in photon.repo and photon-updates.repo, you need add photon-dev.repo into /etc/yum.repos.d/ as @sarchoi mentioned.
If your Photon OS is 1.0 GA/Refresh/1.0 update, you need "tdnf upgrade glibc-lang" first, since glibc is 2.22 in photon 1.0 and glibc-i18n need glibc-2.24 in photon-dev.repo.

**Comment by rongrongqiu** [comment]
@JPustkuchen, the second step for config locale should as following :
2.edit /etc/locale-gen.conf by adding new line, for example 'de_DE.UTF-8      UTF-8'
Hope it helps!J

**Comment by JPustkuchen** [comment]
Thank you all very much. You helped me a lot. Sadly even after reboot the keyboard still sets "y" for a "z" so is not QUERTZ yet, but the settings above have been applied successfully using these steps:

1. create a '/etc/yum.repos.d/photon-dev.repo' file with the content from https://github.com/vmware/photon/wiki/Frequently-Asked-Questions#q-where-can-i-get-the-latest-version-of-a-package
2. run command 'tdnf install glibc-i18n'
3. edit /etc/locale-gen.conf by adding new line, for example 'de_DE UTF.8'
4. run command 'locale-gen.sh de_DE' (upon step 2)
5. run 'export LANG=de_DE.UTF-8'
6. check by running 'locale' which shows current locale.

As result locale-gen.sh de_DE
returned:
> Generating locales ...
> en_US.ISO-8859-1 ... done
> ...
> de_DE.UTF-8... done
> Generation complete.

Running "locale" returns all values as de_DE.UTF-8 (without LC_ALL="" <- That value is empty)

Running "localectl" returns
> System Locale: LANG=de_DE.UTF-8
> VC Keymap: de-latin1
> X11 Layout: pc105
> X11 Options: terminate:ctrl_alt_backspace

Thank you all so much for your great help.

Now I have two issues left:
Do you have an idea why my keyboard is still wrong and how I could fix that? (which was my original intention)
If possible please add discussions results as FAQ section, I think it will help many users with different keyboard layouts.

**Comment by rongrongqiu** [comment]
@JPustkuchen, where do you install Photon OS, vsphere , cloud, workstation or fusion?  What is your basic system, windows or Mac?

**Comment by JPustkuchen** [comment]
Photon OS on VMWare vSphere on VMWare ESXI Host.

**Comment by rongrongqiu** [comment]
@JPustkuchen, could you please try "localectl status" and show me the output? Thank you for quick response.

**Comment by sarchoi** [comment]
@JPustkuchen, if "localectl list-keymaps" has an error on your VM, then you need to install kbd package. 

Here is revised version to try:
1. tdnf install glibc-lang (it looks glibc-lang package is sufficient in released version, and you don't need to enable photon-dev.repo)
2. tdnf install kbd
3. add two lines in /etc/locale-gen.conf
         de_DE		ISO-8859-1
         de_DE.UTF-8	UTF-8
4. locale-gen.sh
5. localectl set-locale LANG="de_DE.UTF-8" LC_CTYPE="de_DE.UTF-8"
6. localectl set-keymap de-latin1
7. reboot

As you can see in the screenshot below, it looks the characters are mapped to german keyboard. The de.txt has three lines in which I typed characters from left to right in the keyboard. 

![de_de_systemd228](https://cloud.githubusercontent.com/assets/12851118/24121548/e1165ec0-0d75-11e7-8ea5-837f96ed8310.png)

Hopefully it works for you, and please let us know if you have any question. Thank you so much for feedback, and I will ask @shoenisch to add these steps in FAQ.

**Comment by JPustkuchen** [comment]
@sarchoi and all others, THANK YOU SO MUCH!!!

@sarchoi's Answer worked great and now I have the correct locale and keyboard input. THANK YOU SO MUCH!

If possible please add to FAQ for the future.
