### ISSUE TITLE
no outbound internet access on AMIs in AWS

### ISSUE THREAD

**Issue by berndtj** [vmware/photon#613]
After creating an AMI (ebs-backed), I could access the instance, but I could not make any outbound connections.  Turns out the entries in /etc/resolv.conf were invalid (at least for us-west-1).  I used the following values to resolve the issue:

```
search us-west-2.compute.internal
options timeout:2 attempts:5
nameserver 10.0.0.2
```

However, the amazon AMIs have a script to generate these...

**Comment by ppadmavilasom** [comment]
@suezzelur any updates on this?

**Comment by suezzelur** [comment]
The rev2 ami image has the right DNS settings
