### ISSUE TITLE
VMCI recv() returns zero bytes

### ISSUE THREAD

**Issue by govint** [vmware/photon#614]
Hi,
     Am using VMCI on Photon and on occasion find that the VMCI client call recv() on the vsocket returns zero bytes. Don't see any kernel logs or any error. Nor does the recv() set errno.

**Comment by govint** [comment]
To add more context, the scenario is like this:

1. Guest program is talking to ESX host based service. The guest creates a VMCI STREAM socket and connects to thje host service.
2. Host service handes the guest request and returns response.
3. Guest receives response.
4. Guest request involves a magic number (4 bytes) followed by the request length and data.
5. Service response includes the same magic number followed by response length and data.

We see that at step (3) above, the guest program receives zero bytes for the magic - even after retries with a delay of one second between retries the step 3 fails with zero bytes for the magic.

Does the VMCI/vsock client implement a timeout on the recv(), if yes whats the timeout? Why don't retries help at all?

**Comment by ppadmavilasom** [comment]
not directly related to photon.
