### ISSUE TITLE
versioning is very confusing

### ISSUE THREAD

**Issue by casualjim** [vmware/photon#616]
The versioning of photon os is very confusing because I can't seem to find out which release I'm looking at when logging into a machine

```
root@icarrero-utils [ ~ ]# cat /etc/os-release 
NAME="VMware Photon"
VERSION="1.0"
ID=photon
VERSION_ID=1.0
PRETTY_NAME="VMware Photon/Linux"
ANSI_COLOR="1;34"
HOME_URL="https://vmware.github.io/photon/"
BUG_REPORT_URL="https://github.com/vmware/photon/issues"
```

The version could be something like: 1.0.2 
which is still 1.0 but at least you know which revision you're looking at inside. 
I can't just compare git hashes because they are not sequential.

**Comment by ppadmavilasom** [comment]
Photon plans to use a repo pair (release, upgrade) per version. Everything in between for a release is kept up to date via updates from the update repo of the release.

1.0 has 1.0 repo and 1.0 upgrade repos 
2.0 will have a 2.0 repo and 2.0 upgrade repo. 

Repo urls will substitute $releasever with the version of the photon-release package. So an upgrade from 1.0 to 2.0 is essentially an upgrade of photon-release to 2.0, then a distro-sync. 
However, to orchestrate this, and handle any one off preparations for upgrade, there will be an upgrade rpm which delivers a script that does upgrade using the above plan.

There is no plan to extend the version mechanism at the moment.
