### ISSUE TITLE
inode Usage

### ISSUE THREAD

**Issue by jjasghar** [vmware/photon#619]
I started to play around with Photon and noticed something interesting.

I pulled down two containers:

```
- name: ubuntu-12.04
- name: centos-6.4
```

And watched `df -i` as they were building.

It started with:
```
root@photon-machine [ /var/lib/docker/overlay ]# df -i
Filesystem     Inodes IUsed  IFree IUse% Mounted on
/dev/root      524288 20915 503373    4% /
devtmpfs       256244   286 255958    1% /dev
tmpfs          256637     1 256636    1% /dev/shm
tmpfs          256637   356 256281    1% /run
tmpfs          256637    16 256621    1% /sys/fs/cgroup
tmpfs          256637    11 256626    1% /tmp
tmpfs          256637     4 256633    1% /run/user/0
```

And ended with:

```
Filesystem     Inodes  IUsed  IFree IUse% Mounted on
/dev/root      524288 228857 295431   44% /
devtmpfs       256244    286 255958    1% /dev
tmpfs          256637      1 256636    1% /dev/shm
tmpfs          256637    359 256278    1% /run
tmpfs          256637     16 256621    1% /sys/fs/cgroup
tmpfs          256637     11 256626    1% /tmp
tmpfs          256637      4 256633    1% /run/user/0
```

This seems over the top on usage? Looking around there maybe reports of this: https://github.com/coreos/bugs/issues/264 but not much else out there. 

Any advice or suggestions would be appreciated. If you need more context I was walking through this: http://jjasghar.github.io/blog/2017/03/29/photonos-as-your-backend-for-kitchen-docker/

**Comment by jjasghar** [comment]
Talking to @jakerobinson I'm going to attempt to replicate this with an ISO install also. This was with the vanilla `OVA` build.

**Comment by jjasghar** [comment]
I've attempted to boot multiple of the `ISO`s, and none of them are bootable it seems.

I'm in the process of creating an new harddrive and mounting it at `/var` to see if that fixes the problem.

**Comment by ppadmavilasom** [comment]
"none of them are bootable" > could you please update how you are trying this?

**Comment by jjasghar** [comment]
I have put 
![image](https://cloud.githubusercontent.com/assets/810824/24561879/28ad4fbe-160e-11e7-80e3-2b88bf9e0dfc.png)
on my datastore and attempted to boot from both `ISO`s and it fails with:

![image](https://cloud.githubusercontent.com/assets/810824/24561910/4c618830-160e-11e7-9d68-e4ec0cc48afa.png)

Any advice?

**Comment by jjasghar** [comment]
I ended up creating another harddrive and formatting it with ext4, and mounted it at the `/var` partition on the OVA. It seems to have passed the initial issue reported here.

Though, I I have noticed with usage of this machine now:

```shell
Filesystem      Inodes  IUsed   IFree IUse% Mounted on
/dev/root       524288 402549  121739   77% /
devtmpfs        256244    297  255947    1% /dev
tmpfs           256637      1  256636    1% /dev/shm
tmpfs           256637    446  256191    1% /run
tmpfs           256637     16  256621    1% /sys/fs/cgroup
tmpfs           256637     11  256626    1% /tmp
/dev/sdb1      5242880 304146 4938734    6% /var
tmpfs           256637      4  256633    1% /run/user/0
overlay        5242880 304146 4938734    6% /var/lib/docker/overlay/e1c0c96764258f4a50b6e40df86a7a63199d6e4581859c167685babc0
2268d6f/merged
shm             256637      1  256636    1% /var/lib/docker/containers/e42618a2810bab2aae1b8a944f846e579bade8d0f4477677e1a462
b211db2d60/shm
overlay        5242880 304146 4938734    6% /var/lib/docker/overlay/cf16183edddbedabac4a0807ca95499960e7fc1d148e31899fb1cb8cc
f8c2bf6/merged
shm             256637      1  256636    1% /var/lib/docker/containers/b319680ea2dfcd3d08a4ede503a2cc7802485f155370826f899d98
508e155b18/shm
overlay        5242880 304146 4938734    6% /var/lib/docker/overlay/c9d567cd01adf9884bbd6ed80ea0f9a266548fd44a66c38f6cba26a34
b8e01d2/merged
shm             256637      1  256636    1% /var/lib/docker/containers/66b2b6b738b26278d421fc5b4615656bb9776bbe2c44e2632cadfe
cf95986b31/shm
```

The 77% usage for `/` seems oddly high. I think yall want to revisit the settings for the `OVA`.

**Comment by ppadmavilasom** [comment]
i tried with this - https://bintray.com/vmware/photon/download_file?file_path=photon-custom-hw10-1.0-13c08b6.ova
vm has a 16GB drive and 3% usage  Is this the case for you? 

here is what i have after pulling the images you mentioned - i couldnt find 6.4 for centos so i did latest

root@photon-8CgqFO02k [ ~ ]# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
centos              latest              98d35105a391        2 weeks ago         192.5 MB
ubuntu              12.04               b384dd9703db        4 weeks ago         103.6 MB
root@photon-8CgqFO02k [ ~ ]# df -i
Filesystem     Inodes IUsed  IFree IUse% Mounted on
/dev/root      524288 36581 487707    7% /
devtmpfs       256250   286 255964    1% /dev
tmpfs          256661     1 256660    1% /dev/shm
tmpfs          256661   327 256334    1% /run
tmpfs          256661    12 256649    1% /sys/fs/cgroup
tmpfs          256661    10 256651    1% /tmp
tmpfs          256661     4 256657    1% /run/user/0
root@photon-8CgqFO02k [ ~ ]# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root       7.8G  740M  6.7G  10% /
devtmpfs       1001M     0 1001M   0% /dev
tmpfs          1003M     0 1003M   0% /dev/shm
tmpfs          1003M  308K 1003M   1% /run
tmpfs          1003M     0 1003M   0% /sys/fs/cgroup
tmpfs          1003M  4.0K 1003M   1% /tmp
tmpfs           201M     0  201M   0% /run/user/0

**Comment by ppadmavilasom** [comment]
the solution you suggested above is the best
>> I ended up creating another harddrive and formatting it with ext4, and mounted it at the /var partition on the OVA. It seems to have passed the initial issue reported here.
