### ISSUE TITLE
Does photon OS support cron jobs. I am unable to find any relevant help docs 

### ISSUE THREAD

**Issue by reachrkr** [vmware/photon#620]
Does photon OS support cron jobs. Unable to find any relevant help docs

**Comment by ppadmavilasom** [comment]
provided via the cronie pkg

**Comment by reachrkr** [comment]
ok thanks . got it!!!

**Comment by lknite** [comment]
Is this still the right answer?  I've performed an 'apt-get update' and attempted to search 'apt-cache search cronie' and install 'apt-get install cronie' without any luck.

I can see a couple folders which make me think cron is installed and working but don't see anything when running ps ax, these exist:
- /etc/cron.d
- /etc/cron.daily

**Comment by lknite** [comment]
Found my own answer.  Though ```uname -a``` returned 'photon' the actual container base image ended up being ubuntu and to install crontab required ```apt-get install cron```.
