### ISSUE TITLE
python-pip needs python-setuptools to run

### ISSUE THREAD

**Issue by stunes** [vmware/photon#623]
The spec for python-pip declares python-setuptool as a build dependency but not as a runtime dependency. python-pip needs to declare python-setuptool as a runtime dependency.

Without it:

```
# pip install virtualenv
Traceback (most recent call last):
  File "/usr/bin/pip", line 5, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources
```

**Comment by xiaolin-vmware** [comment]
Commit 45510ce fixed this issue in dev branch, commit e0853f8 fixed this issue in 1.0 branch.

**Comment by smathaidavis** [comment]
I'm trying to upgrade setuptools in an anaconda environment in Visual Studio 2015. Can't seem to get a workaround (tried creating virtual environments). Am upgrading setuptools to be able to install quandl package. Anybody have any ideas for a workaround? Would really appreciate it.

Here is the error I am getting:

Collecting setuptools
  Using cached setuptools-34.4.1-py2.py3-none-any.whl
Requirement already up-to-date: six>=1.6.0 in c:\program files\anaconda3\lib\site-packages (from setuptools)
Requirement already up-to-date: packaging>=16.8 in c:\program files\anaconda3\lib\site-packages (from setuptools)
Requirement already up-to-date: appdirs>=1.4.0 in c:\program files\anaconda3\lib\site-packages (from setuptools)
Requirement already up-to-date: pyparsing in c:\program files\anaconda3\lib\site-packages (from packaging>=16.8->setuptools)
Installing collected packages: setuptools
  Found existing installation: setuptools 27.2.0
Cannot remove entries from nonexistent file c:\program files\anaconda3\lib\site-packages\easy-install.pth
----- Failed to install 'setuptools' -----

**Comment by ppadmavilasom** [comment]
@smathaidavis is photon involved here at some point? via docker? could you please outline the steps so we can understand how photon is involved.

**Comment by ppadmavilasom** [comment]
closing. please refer to Xiaolin's comment for commit details.
