### ISSUE TITLE
Building with PHOTON_CACHE_PATH fails

### ISSUE THREAD

**Issue by markpeek** [vmware/photon#627]
Following these [instructions](https://github.com/vmware/photon/blob/master/docs/build-photon.md#how-to-use-the-cached-toolchain-and-rpms) the build fails due to the directory tree not being correct. Is there another step required?

```
$ mkdir $HOME/photon-cache
$ sudo make iso PHOTON_CACHE_PATH=$HOME/photon-cache
/home/markpeek/photon/photon/support/sanity_check.sh
Sanity check for all json files...
Checking:/home/markpeek/photon/photon/support/../common/data/packages_appliance.json
<trim checked file list>
Checking:/home/markpeek/photon/photon/support/../installer/actionresult.py
Checking:/home/markpeek/photon/photon/support/../installer/diskpartitioner.py
Using cached RPMS...
/bin/cp: cannot stat '/home/markpeek/photon-cache/RPMS/noarch/*': No such file or directory
Makefile:305: recipe for target 'packages-cached' failed
make: *** [packages-cached] Error 1
```

**Comment by dthaluru** [comment]
There is no other step. you can built iso using command "sudo make iso", if you dont have any cached rpms.
If you have cached rpms, create photon-cache directory and place x86_64 rpms in $PHOTON_CACHE/RPMS/x86_64 directory and noarch rpms in $PHOTON_CACHE/RPMS/noarch directory.

**Comment by markpeek** [comment]
Thanks but that does sound like another step...
```
$ mkdir $HOME/photon-cache
$ <copy existing rpms into cache>
$ sudo make iso PHOTON_CACHE_PATH=$HOME/photon-cache
```
From the documentation it wasn't evident that copy was necessary. It would be good to better document how to more easily rebuild after the initial build using the cache.

**Comment by stuclem** [comment]
For investigation in the next release.

**Comment by YustasSwamp** [comment]
fixed
