### ISSUE TITLE
Hardcoded hostname in /etc/sysconfig/network

### ISSUE THREAD

**Issue by ericgray** [vmware/photon#63]
Regardless of the hostname selected during install, the `/etc/sysconfig/network` file contains `HOSTNAME=photon.eng.vmware.com` which does not seem correct.

Is `/etc/sysconfig/network` even used in Photon?  There is also `/etc/hostname`, which is manipulated by `hostnamectl`

**Comment by ppadmavilasom** [comment]
@ericgray /etc/sysconfig/network is not used and is removed in rc.
