### ISSUE TITLE
Current latest tag - numeric tag

### ISSUE THREAD

**Issue by afreege** [vmware/photon#630]
Since we encounter an issue with 1.0 while running tdnf upgrade, we wish to use the latest image and use the numeric tag instead of latest, can you please share this information?

thanks,
Avi

**Comment by ppadmavilasom** [comment]
Re: docker image
Could you please share what the issue is?

**Comment by ppadmavilasom** [comment]
photon will follow {version}-{yyyymmdd} format to tag images

The one you are looking for is vmware/photon:1.0-20170207
