### ISSUE TITLE
Network issues when running Vmware Photon on ESXI

### ISSUE THREAD

**Issue by kgrvamsi** [vmware/photon#632]
Hello,

We are trying to create the Vmware Photon implementation ,infact its a group of vm's that we need them running on a ESXI farm (5 Blade Servers) but when we tried getting them running on one of the blade server we are not getting the Network interfaces up and running either the config runs on DHCP or Static.

Once i figure out the above issue i want to use the Terraform way of bringing up the instances in the ESXI farm with all the tools i need to build.

@dthaluru @jsr  can you help me to understand what can be the best solution fixing the issue so ip assignment and i would like to know if there is a good blog to explain the performance by using vmware photon on a ESXI farm instead using Coreos or project atomic?Assuming the only case here is that Photon seems to be a tightly coupled os to a Vmware underlying layer to enhance the performance and have a clear monitoring on the kernel leaks or process overhead issues.(mainly Docker and other Microservice tools like Etcd or consul).

**Comment by ppadmavilasom** [comment]
can you post your network config 
output of ifconfig 
and 
cat /etc/systemd/network/*.network

**Comment by kgrvamsi** [comment]
![photon-01](https://cloud.githubusercontent.com/assets/1199031/25096502/17e79e54-2366-11e7-9f7b-e4c733dfb8ac.JPG)

![photon-02](https://cloud.githubusercontent.com/assets/1199031/25096511/1eefbe34-2366-11e7-9125-6c11f5a36312.JPG)

And we used the Ova file in creating this vm?Do you think this a right process or try using the ISO way of installation?

**Comment by vinaykul** [comment]
@kgrvamsi The default configuration of PhotonOS is to use DHCP IP as you see with the file Matching to Name=e* . 

It looks like you are looking to setup no IP address on eth0, and static IP on eth1. 

If that is the case, the recommended way is to remove the default dhcp config file, and create a 10-eth0.network with Name=eth0, DHCP=no. For eth1, you can have 10-eth1.network with Match.Name=eth1 and the address as configured above. Please give that a try.

**Comment by ppadmavilasom** [comment]
@kgrvamsi does @vinaykul comment resolve the issue?

**Comment by kgrvamsi** [comment]
@ppadmavilasom @vinaykul we are still working on this issue and will send you a update by today .......in the mean time can you answer my other question

_can you help me to understand what can be the best solution fixing the issue so ip assignment and i would like to know if there is a good blog to explain the performance by using vmware photon on a ESXI farm instead using Coreos or project atomic?Assuming the only case here is that Photon seems to be a tightly coupled os to a Vmware underlying layer to enhance the performance and have a clear monitoring on the kernel leaks or process overhead issues.(mainly Docker and other Microservice tools like Etcd or consul)._

**Comment by vinaykul** [comment]
For IP address management, it really depends on your purpose/objectives. I need to take a look at terraform to better advise. But the simple case would be to have a DHCP server configured on your port-group, traditional DHCP networking should work. Additional options will become available with NSX networking.

Regrading performance, PhotonOS has a ESX optimized kernel that will give you performance advantages on ESXi. CC @YustasSwamp for further details on linux-esx kernel advantages. PhotonOS has tools such as sysdig available that enable monitoring.

**Comment by kgrvamsi** [comment]
@vinaykul the network solution got resolved when we tried to install this via iso instead the ova by changing the network settings of the adapter from DHCP=yes to no.

On the performance side of it any info @YustasSwamp .Do we have a special view point to check the performance metrics from running a minified container os (Coreos for comparision) to the Photon Os.

**Comment by YustasSwamp** [comment]
For the linux-esx performance features and metrics you can search for "kernel2" in RADIO 2016 papers (internal access).

linux-esx will perform better in several areas then any other Linux kernel running as a guest on ESXi.
You can collect additional performance metrics and share with us.))
