### ISSUE TITLE
sporadic failures when running tdnf upgrade

### ISSUE THREAD

**Issue by afreege** [vmware/photon#634]
We are using the the docker photon vmware/photon:1.0-20170410 , while building the image we are getting sporadic errors on tdnf upgrade command and also errors on synchronize cache for repo 'VMware Photon Linux 1.0(x86_64)Updates', The issue is that sometimes the build is successful and sometimes it fails, need your assistant

**Comment by ppadmavilasom** [comment]
synchronize cache errors could be dns related - but if its happening only for the updates repo, it could be that the update repo was getting rebuilt or pending updates affecting the repo. I checked - the last update was April 17th - this does not look like the case.
Are you only getting errors on sync cache for update repo? Trying to rule out dns issues

**Comment by afreege** [comment]
Well we are getting several errors for example:
- Error: Failed to synchronize cache for repo 'VMware Photon Linux 1.0(x86_64)Updates' from 'https://dl.bintray.com/vmware/photon_updates_1.0_x86_64'
- Error during download: 19: Cannot download x86_64/readline-6.3-5.ph1.x86_64.rpm: All mirrors were tried
- Error during download: 19: Cannot download x86_64/tar-1.28-2.ph1.x86_64.rpm: All mirrors were tried
- Error during download: 19: Cannot download x86_64/rpm-4.11.2-12.ph1.x86_64.rpm: All mirrors were tried

And more, seems like its unstable it fails on different packages, after googling a bit this is the order that we are running the build:
RUN tdnf makecache \
	&& tdnf -y upgrade \
	&& tdnf -y install tar gzip wget procps-ng \

**Comment by ppadmavilasom** [comment]
i have repro of this if i try from machines at different geographic locations. following up with bintray. will update.

**Comment by narmitag** [comment]
Is there any update to this? It's causing major issues with our builds

**Comment by ppadmavilasom** [comment]
This is resolved. Could you please check now?

**Comment by ppadmavilasom** [comment]
please reopen if you have similar issues.
