### ISSUE TITLE
Network issues running on vmware

### ISSUE THREAD

**Issue by kparcha** [vmware/photon#637]
Hello,

I have installed PhotonOS on the VMWare ESXi host with the minimal installation ova. I have setup a static IP, modified the permissions of 10-static.network in /etc/systemd/network to 644 and restarted the network. I see the IP assigned to eth0 but I cannot ping the hosts and gateway within the network. 
Any help or pointers will help me pass through the network issues. 

Thanks
Kasturi

**Comment by smaliakkal** [comment]
Could you share your 10-static.network ? 
Please make sure you set Address=<your address>/prefix length  based on your subnet mask 
Also Gateway is correct.

**Comment by kparcha** [comment]
<img width="742" alt="screen shot 2017-04-27 at 1 23 47 pm" src="https://cloud.githubusercontent.com/assets/22490375/25502746/cb0a13a2-2b4c-11e7-9282-b375d1aa4f21.png">

**Comment by smaliakkal** [comment]
can you check your firewall rules added for icmp requests ?  if not try adding them 

iptables -A INPUT -p icmp --icmp-type echo-request -j ACCEPT
iptables -A OUTPUT -p icmp --icmp-type echo-reply -j ACCEPT

**Comment by kparcha** [comment]
Added iptables rules. 
<img width="742" alt="screen shot 2017-04-27 at 1 23 47 pm" src="https://cloud.githubusercontent.com/assets/22490375/25503558/b5ffd21e-2b4f-11e7-8eee-49df0d28f599.png">

**Comment by kparcha** [comment]
<img width="995" alt="screen shot 2017-04-27 at 1 42 04 pm" src="https://cloud.githubusercontent.com/assets/22490375/25503584/ca3145ba-2b4f-11e7-9791-c2e6d9daa38a.png">

**Comment by vinaykul** [comment]
Do you have the correct port-group connection and the cirrect subnet mask for you network? If you have DHCP server on the network, can you try configuring DHCP IP and dump the ifconfig?

**Comment by Bas-vE** [comment]
I think i'm having the same issues, What settings did you change in your port-group connections to make everything work again?
