### ISSUE TITLE
Update brings ~267 MB of packages without reduction using clean

### ISSUE THREAD

**Issue by scriptjs** [vmware/photon#638]
Updating tndf packages on minimal install followed by clean results in a much larger image size. I am running the following.

```
tdnf update
tdnf clean all
```

**Comment by ppadmavilasom** [comment]
clean all is just removing any cached metadata in /var/cache/tdnf

**Comment by scriptjs** [comment]
@ppadmavilasom clean: This command cleans up temporary files, data, and metadata. It takes the argument all.  I anticipated using photon because I don't want bloat.

**Comment by ppadmavilasom** [comment]
completely in the context of tdnf - temp files, data and metadata that tdnf accumulates. 
when you did update, did it update any packages? that would be where the size diff is coming from

**Comment by scriptjs** [comment]
This is what it is bringing in:

```
root@test [ ~ ]# tdnf update

Installing:
libsepol                                x86_64         2.5-2.ph1                  603.80 k
libselinux                              x86_64         2.5-2.ph1                  146.07 k
device-mapper-libs                      x86_64         2.02.141-5.ph1             367.22 k
libseccomp                              x86_64         2.2.3-2.ph1                453.62 k

Total installed size: 1.53 M

Upgrading:
xerces-c                                x86_64         3.1.4-1.ph1                  4.32 M
vim                                     x86_64         7.4-9.ph1                    1.93 M
util-linux                              x86_64         2.27.1-3.ph1                 4.57 M
tcsh                                    x86_64         6.19.00-6.ph1              477.08 k
systemd                                 x86_64         228-34.ph1                  29.09 M
rpm                                     x86_64         4.11.2-12.ph1                4.28 M
readline                                x86_64         6.3-5.ph1                    3.52 M
python2                                 x86_64         2.7.13-2.ph1                 1.83 M
python2-libs                            x86_64         2.7.13-2.ph1                15.29 M
python-xml                              x86_64         2.7.13-2.ph1               319.00 k
python-six                              noarch         1.10.0-3.ph1                60.42 k
python-requests                         noarch         2.13.0-1.ph1                 2.88 M
procps-ng                               x86_64         3.3.11-4.ph1                 1.04 M
openssl                                 x86_64         1.0.2k-1.ph1                 5.24 M
openssh                                 x86_64         7.4p1-3.ph1                  4.57 M
open-vm-tools                           x86_64         10.1.5-1.ph1                 2.45 M
ncurses                                 x86_64         6.0-3.ph1                    6.83 M
libgcrypt                               x86_64         1.7.6-1.ph1                  1.11 M
krb5                                    x86_64         1.14-5.ph1                   3.64 M
iptables                                x86_64         1.6.0-6.ph1                  1.46 M
linux                                   x86_64         4.4.60-1.ph1                20.34 M
initramfs                               x86_64         1.0-7.11417601.ph1          10.57 M
glibc                                   x86_64         2.22-10.ph1                 50.96 M
filesystem                              x86_64         1.0-10.ph1                   7.14 k
docker                                  x86_64         1.13.1-1.ph1                77.78 M
cracklib-dicts                          x86_64         2.9.6-3.ph1                  8.85 M
cracklib                                x86_64         2.9.6-3.ph1                 83.59 k
bash                                    x86_64         4.3.30-8.ph1                 2.50 M
Linux-PAM                               x86_64         1.2.1-4.ph1                  1.03 M

Total installed size: 267.02 M
```

**Comment by ppadmavilasom** [comment]
please do a "tdnf info installed" and see what the current installed size is. you might be able to identify things that you dont need (if any) and remove them. 
There are updates but the updates would also remove the current packages so its not a cumulative size increase rather a replace

**Comment by scriptjs** [comment]
@ppadmavilasom My total installed size is  343.67 MB, this is why I raised the issue. The update literally doubles the size of the vm. So with these old versions like docker 1.12, I expected cleaning would move away old packages as opposed to add cumulatively on top of them.

**Comment by ppadmavilasom** [comment]
i see what you mean. most of the time if anything is left behind, its probably left behind with the anticipation that the user might need it - like a database or something to do with user generated data in the hope that user might need it. there is no attempt to clean such data - its upto the user to determine and clean. 
could you tell me the steps to reach here? install from 1.0 using minimal option and do an update?

**Comment by scriptjs** [comment]
@ppadmavilasom Its pretty straight forward. I am using the iso to build a minimal image using Fusion. Currently, I only make minor adjustments to the sshd_config, then generate a qcow2 image with compression using qemu-img from my vmdk. That is it. This gives me a 197 MB image to send to ship to OpenStack with Glance. No user data or installed docker images, nothing. 

I did not update the packages before packing the image. I discovered this when I wanted to bring to the latest packages up to date in my image before packing up for OpenStack and it was substantially larger and this does not add up.

**Comment by ppadmavilasom** [comment]
valid concern - thanks for the explanation.

**Comment by markpeek** [comment]
@scriptjs one thing to try, zero the free blocks in the filesystem. Try this before you shutdown to compress via qcow2 (note: you might need to do this on a per-filesystem basis):
```
sudo dd if=/dev/zero of=/zero
sudo rm -f /zero
```

**Comment by scriptjs** [comment]
@markpeek, this looks good, thank you. I am at 186.4 MB to ship via qcow2 with zeroing :)

**Comment by ppadmavilasom** [comment]
@markpeek thanks for the resolution

**Comment by ppadmavilasom** [comment]
@scriptjs : "My total installed size is 343.67 MB," - how did you get this - by running what command?

**Comment by scriptjs** [comment]
@ppadmavilasom Hi. This line will be displayed following the listing of installed packages when running `tdnf info installed`
