### ISSUE TITLE
Package request: tinc

### ISSUE THREAD

**Issue by scriptjs** [vmware/photon#639]
Tinc is a Virtual Private Network (VPN) daemon that uses tunnelling and encryption to create a secure private network between hosts on the Internet. Would be great to have this package to ensure your private network is really private with a cloud provider or creating mesh networks of publicly available hosts. I am currently doing this by running tinc in a docker container.

**Comment by jnovack** [comment]
Isn't doing it the "docker container" way the best way?

Why is having it a native package better??

**Comment by scriptjs** [comment]
It depends on where or how you want to use it. I have since discovered wireguard that is just as simple to configure as a vpn and compiled in the linux kernel for much more speed. I expect it to come into the linux kernel and is already part of the linuxkit kernel which to build OS's that are as small and simple as possible, a fraction of the size of photon and with a specific focus on security.

**Comment by YustasSwamp** [comment]
We do not have plans to add this package. Thanks!
