### ISSUE TITLE
Unable to install docker managed plugin

### ISSUE THREAD

**Issue by pdhamdhere** [vmware/photon#640]
See https://github.com/vmware/docker-volume-vsphere/issues/1215

Copy-pasting repro instructions as reported by customer;

Steps to reproduce:

Download Photon 1.0 Rev 2 OVA
Deploy OVA to VM
Update VM to latest packages (tdnf distro-sync -y), Reboot
After reboot, enable SSH
Login via SSH, enable docker service, docker plugin install.. and watch ..

Here is most of the output from the above steps.
root@photon-machine [ ~ ]# docker ps
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
root@photon-machine [ ~ ]# systemctl enable docker
Created symlink from /etc/systemd/system/multi-user.target.wants/docker.service to /usr/lib/systemd/system/doc ker.service.
root@photon-machine [ ~ ]# systemctl start docker
root@photon-machine [ ~ ]# docker plugin ls
ID NAME DESCRIPTION ENABLED
root@photon-machine [ ~ ]# docker --version
Docker version 1.13.1, build 092cba3
root@photon-machine [ ~ ]# docker plugin install --grant-all-permissions --alias vsphere vmware/docker-volume-vsphere:latest
latest: Pulling from vmware/docker-volume-vsphere
bc8c14d82abc: Download complete
Digest: sha256:6b81577c0502f537bc8a5ccf3f1599d9f9b7276242d7043d00d04496f312b976
Status: Downloaded newer image for vmware/docker-volume-vsphere:latest
Error response from daemon: rpc error: code = 2 desc = containerd: container not started
root@photon-machine [ ~ ]# docker plugin disable vsphere
Error response from daemon: plugin "vsphere" not found
root@photon-machine [ ~ ]# docker plugin ls
ID NAME DESCRIPTION ENABLED
root@photon-machine [ ~ ]# systemctl status docker
Failed to connect to bus: No such file or directory
root@photon-machine [ ~ ]# reboot
Failed to connect to bus: No such file or directory
Failed to talk to init daemon.

and then after a "hard reset"

root@photon-machine [ ~ ]# systemctl status docker
● docker.service - Docker Daemon
Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
Active: failed (Result: exit-code) since Wed 2017-05-03 01:29:29 UTC; 16s ago
Docs: http://docs.docker.com
Process: 298 ExecStart=/usr/bin/docker daemon $DOCKER_OPTS --containerd /run/containerd.sock (code=exited, status=1/FAILURE)
Main PID: 298 (code=exited, status=1/FAILURE)

May 03 01:29:28 photon-machine systemd[1]: Starting Docker Daemon...
May 03 01:29:28 photon-machine docker[298]: Command "daemon" is deprecated, and will be removed in Docker 1.16. Please run dockerd directly.
May 03 01:29:29 photon-machine docker[298]: Error starting daemon: couldn't create plugin manager: failed to restore plugins: error reading /var/lib/docker/plugins/fd...
May 03 01:29:29 photon-machine systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
May 03 01:29:29 photon-machine systemd[1]: Failed to start Docker Daemon.
May 03 01:29:29 photon-machine systemd[1]: docker.service: Unit entered failed state.
May 03 01:29:29 photon-machine systemd[1]: docker.service: Failed with result 'exit-code'.

Variations on this that also don't work.

Download the ISO, and do a full install (vs the OVA)
enable/start docker-containerd service prior to docker plugin install
Run the VM on ESX 6.0 vSan cluster
Run the VM on ESX 6.5 vSan cluster

CC/ @shuklanirdesh82

**Comment by sharathjg** [comment]
this is our issue and being actively worked on.

**Comment by suezzelur** [comment]
The rpm with the fix has been uploaded to our 1.0 updates repo.
docker-1.13.1-3.ph1, please use `tdnf update docker` to fetch the new version.
