### ISSUE TITLE
SeLinux Enabling

### ISSUE THREAD

**Issue by Ijlalh90** [vmware/photon#644]
Hi!
I have a issue installing Selinux on Photon Os of Vmware.I cannot compile Selinux in it.I recieve following error in  it.
The issue with selinux is that photon Os don't have policy packages of selinux in their repository and they also don't include selinux configuration in /etc/sysconfig/selinux .I cannot enable selinux in photon os. And compilation errors are attached below in screenshot.
I hope your support.
![screenshot_2017-05-08_12-17-25](https://cloud.githubusercontent.com/assets/22050218/25794061/d0e2969c-33e8-11e7-9766-5344edc5c23e.png)

**Comment by YustasSwamp** [comment]
As start, try this:
# echo "SELINUX=enforcing" > /etc/selinux/config
# mount selinux -t selinuxfs /sys/fs/selinux

**Comment by Ijlalh90** [comment]
There is a issue coming i created directory and file but still  it is not working because some selinux packages which are used in centos are not  present in photon repository.
You can check in the screenshot the whereis selinux directories of Selinux in centos and photon os.And also the input packages in photon and centos.
These packages are not available from Photon repository.
![screenshot_2017-05-08_16-59-07](https://cloud.githubusercontent.com/assets/22050218/25803331/c2bd14e4-340f-11e7-9b9f-fac294428fc6.png)
![screenshot_2017-05-08_16-53-17](https://cloud.githubusercontent.com/assets/22050218/25803333/c2f70136-340f-11e7-921f-6564ccdcdde1.png)

**Comment by YustasSwamp** [comment]
We officially do not support selinux in Photon OS. And there are no plans to do it in version 2.0.
Our Linux kernel has selinux feature compiled in, but userspace binaries do not support it.

You have to build/rebuild binaries on your side to make it working.
Pull requests with selinux support are welcome))

Closing a bug since there are no actual items from out side.

Thanks
