### ISSUE TITLE
Deploy REDIS on Photon

### ISSUE THREAD

**Issue by TfromTPA** [vmware/photon#645]
Hi there,

Is there any documentation available on how to properly install Redis on Photon?  Much info exists for REDIS on Ubuntu/Debian but not Photon.  I'm new to Photon.  Any assistance would be appreciated.

Thanks
TR

**Comment by scriptjs** [comment]
Photon is a minimal OS for containers. I would suggest deploying Redis using Docker and reading up on how to do that on Docker Hub for the official Redis docker image.

**Comment by smaliakkal** [comment]
@TfromTPA 
There was somes issues in redis service start , db persistence and graceful shutdown. All issues resolved through  https://github.com/vmware/photon/commit/18ecfa67e3c451b2176881735e470ebef868d4e2 
redis can be started as a systemd service.
