### ISSUE TITLE
docker-compose should be installed by default with PhotonOS

### ISSUE THREAD

**Issue by nvpnathan** [vmware/photon#647]
curl -L https://github.com/docker/compose/releases/download/1.13.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose

**Comment by CollinChaffin** [comment]
curl -L https://github.com/docker/compose/releases/download/1.16.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose

**Comment by keerthanakalyan** [comment]
Is there a specific need for docker-compose as there are many other popular alternatives to container orchestration available today?
