### ISSUE TITLE
How can i install OVF tool on Photon OS

### ISSUE THREAD

**Issue by reachrkr** [vmware/photon#648]
Can somebody please guide me how can i install ovftool on photon OS . Tried to run  .bundle package , but it doesnt work . my photon env is  "OVA with virtual hardware v11"

**Comment by ipetkov81** [comment]
The same for me:

sh VMware-ovftool-4.2.0-4586971-lin.x86_64.bundle --console --eulas-agreed --required
Extracting VMware Installer...done.
User interface initialization failed.  Exiting.  Check the log for details.

**Comment by narmitag** [comment]
Not sure if this helps but looking at our appliance build scripts we have

`mkdir /etc/init.d`

before we install the bundle. I can't remember why it was there but we are installing ovftool ok on photon hosts.

**Comment by ipetkov7** [comment]
mkdir /etc/init.d

 sh VMware-ovftool-4.2.0-4586971-lin.x86_64.bundle --console --eulas-agreed --required
Extracting VMware Installer...done.
User interface initialization failed.  Exiting.  Check the log for details.

**Comment by narmitag** [comment]
have you got ncurses installed,

`tdnf -y install ncurses-compat`

**Comment by ipetkov7** [comment]
This time it wokred!

Thanks!

**Comment by reachrkr** [comment]
I think  ncurses  should also be included as part of the photon minimal ova package  .

**Comment by ppadmavilasom** [comment]
minimal has a specific set of pkgs to keep size in check. you can always build your own with package list to fit your need (following the https://github.com/vmware/photon/blob/master/common/data/packages_minimal.json) or install additional after deplloy
