### ISSUE TITLE
iscsi-initiator-utils

### ISSUE THREAD

**Issue by nbaillie** [vmware/photon#649]
Hi,
im looking to try the iscsi, Nimble Storage Docker Volume plug-in.

the requirements include. - iscsi-initiator-utils

TDNF reports - No package iscsi-initiator-utils available.

Are there any workaround options for me to try this driver that you could suggest?

**Comment by DheerajSShetty** [comment]
Will add the package.

**Comment by auchri** [comment]
Any news here?

**Comment by tsener** [comment]
It is, please, add it

**Comment by auchri** [comment]
Yes, I wanted to move our Nextcloud data to some iscsi target but then I noticed that it's not possible to mount iscsi targets using photon os :(

**Comment by auchri** [comment]
Please add this package..

**Comment by YustasSwamp** [comment]
We are open for contributors. Please add appropriate .spec file. We will happy to assist you.

**Comment by marukka** [comment]
+1

**Comment by NoLooseEnds** [comment]
+1

**Comment by pixdrift** [comment]
I have userspace working with a compile from SUSE Tumbleweed, but the `iscsi_tcp` kernel module isn't compiled in the Photon kernel, so need to compile that too.

```
root@photon-machine [ ~ ]# rpm -qa | grep iscsi
open-iscsi-2.0.877-52.1.ph3.x86_64
libopeniscsiusr0_2_0-2.0.877-52.1.ph3.x86_64
```

```
libkmod: kmod_module_insert_module: could not find module by name='iscsi_tcp'
iscsiadm: Could not insert module tcp. Kmod error -2
iscsiadm: iSCSI driver tcp is not loaded. Load the module then retry the command.
iscsiadm: Could not perform SendTargets discovery: iSCSI driver not found. Please make sure it is loaded, and retry the operation
```

**Comment by khayamgondal** [comment]
Is it still open? I can work on it.

**Comment by cprivite** [comment]
So now that photonOS is part of the kubernetes stuff from VMware it'd be nice to see this added so that kubernetes native storage implementations like longhorn can be deployed on it.

**Comment by sdodsley** [comment]
Any news on if this is going to get added, or otherwise can you point to some documentation on how to test a spec file should we create one for a PR

**Comment by YustasSwamp** [comment]
open-iscsi package is in internal codereview.

**Comment by YustasSwamp** [comment]
Added to 3.0 branch. https://github.com/vmware/photon/tree/3.0/SPECS/open-iscsi
Will be available in rpm repository in 1-2 days.
