### ISSUE TITLE
systemd is outdated

### ISSUE THREAD

**Issue by casualjim** [vmware/photon#657]
Currently photon os is shipping with systemd 228

There have been a number is features added to later versions of systemd that are attractive.

The ones I'm interested in are:

Better support for type=notify 
Support for marking network devices as unmanaged
better support for depending on mount units

**Comment by casualjim** [comment]
There was also a CVE about systemd

http://seclists.org/oss-sec/2017/q2/618

**Comment by vinaykul** [comment]
Thanks. I'll address the CVE soon. We are testing systemd-233 in PhotonOS 2.0.

I experimented with back porting systemd-228 (not normally done by any other distribution I'm aware of) and it introduced a degree of instability. It is a core component and would need extensive testing as opposed to a security patch update verification, which would end up being a PhotonOS 2.0 scale of effort to backport.

**Comment by YustasSwamp** [comment]
Updated systemd will be available in Photon OS 2.0
