### ISSUE TITLE
"tdnf check-udpdate" always required "tdnf clean all" to pickup updates

### ISSUE THREAD

**Issue by dlinsley** [vmware/photon#658]
`tdnf check-update` does not appear to behave like `yum check-update` in how it refreshes the repo cache to determine if new packages are available.  Cleaning the meta data is required every time in my experience with tdnf.

Example run:
```bash
dlinsley@photon-YRjrxkFmh [ ~ ]$ sudo tdnf check-update
```
_...Expecting a list available package updates here but have nothing..._
```bash
dlinsley@photon-YRjrxkFmh [ ~ ]$ sudo tdnf update
Nothing to do.
dlinsley@photon-YRjrxkFmh [ ~ ]$ sudo tdnf clean all
Cleaning repos: photon-extras photon lightwave photon-updates
Cleaning up everything
dlinsley@photon-YRjrxkFmh [ ~ ]$ sudo tdnf check-update
initramfs.x86_64                               1.0-7.11445761.ph1 photon-updates
bash.x86_64                                 4.3.30-10.ph1         photon-updates
linux-esx.x86_64                            4.4.71-1.ph1          photon-updates
linux.x86_64                                4.4.71-1.ph1          photon-updates
cloud-init.noarch                            0.7.9-1.ph1          photon-updates
python-jinja2.noarch                         2.9.5-2.ph1          photon-updates
```
Updates detected after ```tdnf clean all```

Package Version: ```tdnf-1.1.0-1.ph1.x86_64```

**Comment by ppadmavilasom** [comment]
tdnf defaults metadata_expire to 48 hours. you can override (using metadata_expire settings per repo) or using --refresh with any command to refresh first, then run the command.

yum has a default expire time of 6 hours. however, dnf has set the default to 48 hours which is what tdnf follows.

**Comment by dlinsley** [comment]
Thanks @ppadmavilasom !  I still see this behavior when `tdnf update` weeks apart.  I don't believe I would receive any updates unless a refresh is forced.

**Comment by ppadmavilasom** [comment]
@dlinsley tdnf keeps a file called "lastrefresh" for each repo in /var/cache/tdnf/<reponame> and uses the file datetime on this file to trigger a refresh. could you check if you have the marker file in the above cache directory

**Comment by dlinsley** [comment]
Looks like this is working as designed.  Noticed my `lastrefresh` file for a repo had an datetime of 7 days old.  ran `tdnf check-update` and the refresh occured.  `lastrefresha datetime was updated .
