### ISSUE TITLE
Package List URL in FAQ is incorrect

### ISSUE THREAD

**Issue by lamw** [vmware/photon#66]
The following section 

>What packages are included in Micro/Minimal?

In the Photon FAQ (https://github.com/vmware/photon/blob/master/docs/faq.md) has the incorrect URL for the package listings.

Incorrect URL: https://github.com/vmware/photon/blob/master/docs/installer/package_list.json
Correct URL: https://github.com/vmware/photon/blob/master/installer/package_list.json

**Comment by toliaqat** [comment]
Fixed, thanks for reporting.
