### ISSUE TITLE
broken dev environment

### ISSUE THREAD

**Issue by liKe2k1** [vmware/photon#660]
There is currently no 2.0 repo on bintray for the dev branch.

OR

The photon-repo package is linking to the wrong bintray repo, maybe it should point to https://bintray.com/vmware/photon_dev_x86_64 ?

**Comment by ppadmavilasom** [comment]
dev will require manual adjustment in repo url like you are pointing out above till 2.0 is beta. This is done on purpose to avoid confusion.

Disable updates repo and change photon.repo's baseurl to the dev url.

**Comment by liKe2k1** [comment]
Thanks for the info.

Maybe it is useful to add an make parameter like _PHOTON_USE_DEV_REPO=yes_ to generate a customized ISO Image for CI testing

**Comment by liKe2k1** [comment]
Is there a way to control the the $releasever in the .repo files? 

It points to 1.0 on the dev branch.
