### ISSUE TITLE
Photon on VMware Workstation 12 Pro

### ISSUE THREAD

**Issue by jayachar88** [vmware/photon#663]
Trying to run Photo 1.0 (x86_64, with kernel 4.4.41-1.ph1-esx), on VMware Workstation 12 Pro (12.5.7 build-5813279), on Windows 7 Enterprise 64-bit (6.1.7601, SP1), running on my HP Elitebook 745G3. 

The Photon VM image has been created by importing the photon-custom-hw11-1.0-62c543d.ova file. The host laptop is connected to the internet for 80% of the time through one of the several possible WLAN APs, and 20% of the time through wired Ethernet connection, and the IP being always assigned to the host by DHCP. For most of my other VMware Workstation VM's, I usually use NAT networking, which works pretty well. I see that Photon VM image uses bridge networking. 

However, after starting docker, on trying to run a docker image (vmwarecna/ngnx), which is obviously not there in the image repository, it fails to download the image. I checked to see if internet connectivity is working fine by running:

`# curl http://www.yahoo.com`
`# curl http://www.google.com`

The first two gave the expected "302 Moved" response. However this:

`# curl http://www.google.co.in`

gives a name resolution failure error. 

Therefore, I am not sure as to what the issue is. Here is the error message for "docker run" command:
`root@photon-machine [ ~ ]# docker run -d -p 80:80 vmwarecna/ngnx`
`Unable to find image 'vmwarecna/ngnx:latest' locally`
`Pulling repository docker.io/vmwarecna/ngnx`
`docker: Error: image vmwarecna/ngnx:latest not found.`
`See 'docker run --help'.`
`root@photon-machine [ ~ ]# `

**Comment by liKe2k1** [comment]
The correct image name is vmwarecna/nginx 

try 
docker run -d -p 80:80 vmwarecna/nginx

**Comment by jayachar88** [comment]
Indeed, it was a manual error on my part. Closing issue.
