### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by DrSeussFreak** [vmware/photon#665]
How can I add a proxy server to the network configuration?

**Comment by DrSeussFreak** [comment]
Also, can Photon OS handle a Proxy Pac?

**Comment by vinaykul** [comment]
It can be configured by exporting the _proxy variables, or persisted globally in /etc/sysconfig/proxy file.

**Comment by DrSeussFreak** [comment]
Does that include proxy pac files?

**Comment by vinaykul** [comment]
PhotonOS uses systemd. I'm not aware of systemd support for setting proxy via pac script.

**Comment by DrSeussFreak** [comment]
thanks!
