### ISSUE TITLE
yum update kills docker

### ISSUE THREAD

**Issue by grantcurell** [vmware/photon#668]
Steps to reproduce: 
1) Install OS (photon-1.0-62c543d)
2) Run yum update -y
3) Run systemctl start docker

See attached txt for error received.
[error.txt](https://github.com/vmware/photon/files/1185146/error.txt)

Are we not supposed to run yum update?

**Comment by markpeek** [comment]
Please try rebooting. I saw this recently and it was due to the linux kernel/modules getting updated where the bridge driver wouldn't load. Doing a reboot after the update should allow docker to start.

**Comment by grantcurell** [comment]
Too high speed. I'm going to have to ask you to slow it down there killer.

... yep... rebooting did the trick :-p
