### ISSUE TITLE
Clair doesn't recognize the photon docker image.

### ISSUE THREAD

**Issue by reasonerjt** [vmware/photon#674]
Clair is a popular docker image scanner and is integrated with vic product 1.2.
https://github.com/coreos/clair

When I use Clair to scan the photon docker image:
https://hub.docker.com/_/photon/

Clair returns an error:
`{"Error":{"Message":"worker: OS and/or package manager are not supported"}}`

We should contribute to the Clair code to enable its support for photon.

**Comment by sharathjg** [comment]
why would this issue be tracked in the photon github?
