### ISSUE TITLE
Cannot log in anymore

### ISSUE THREAD

**Issue by docbobo** [vmware/photon#675]
Whenever I am attempting to log into Photon, it asks me to change my password. However, when doing that, I get the following:

```
/usr/share/cracklib/pw_dict.pwd.gz: No such file or directory
BAD PASSWORD: error loading dictionary
```

What options do I have for recovering from this situation?

**Comment by ppadmavilasom** [comment]
Is this a 1.0 install?

https://github.com/vmware/photon/blob/master/docs/photon-os-troubleshooting-guide.md#resetting-a-lost-root-password

**Comment by docbobo** [comment]
Yes, that did the trick. Thank you. How do I get rid of the cracklib error?

**Comment by docbobo** [comment]
Nevermind. Problem disappeared after running ```tdnf makecache && tdnf upgrade```.

**Comment by febLey** [comment]
The link which was posted above doesn't work anymore, so for anyone having the same problem, here's the new link:

https://vmware.github.io/photon/assets/files/html/1.0-2.0/photon-os-troubleshooting-guide.html#resetting-a-lost-root-password
