### ISSUE TITLE
Problem with default repos?

### ISSUE THREAD

**Issue by lowescott** [vmware/photon#676]
I just spun up a Photon OS instance using Vagrant (first time in a while), and noted that `tdnf` doesn't work at all; it complains about problems with the default repositories. The Photon OS instance has connectivity to `https://dl.bintray.com/vmware/photon_release_1.0_x86_64` (the base repo, for example), but `tdnf` still doesn't work. The error message is "Failed to synchronize cache for repo".

Any suggestions?

**Comment by ppadmavilasom** [comment]
probably dns resolution
what does curl bintray.com do?

**Comment by lowescott** [comment]
@ppadmavilasom Sorry, I should have been clearer. I tested connectivity via `curl` to `dl.bintray.com/vmware/photon_release_1.0_x86_64` and it was successful (it returned the HTML for that URL). This leads me to believe that there are no issues with DNS resolution or network connectivity. Unless I'm missing something?

**Comment by ppadmavilasom** [comment]
Is it failing to synchronize cache for some other repo by chance? could you post the output pls

**Comment by lowescott** [comment]
I haven't added any other repos (this is a totally vanilla instance of version 1.2.2 of the Vagrant Photon box, and is repeatable). Here's the output of `tdnf check-update`:

```
Error: Failed to synchronize cache for repo 'VMware Photon Linux 1.0(x86_64)' from 'https://dl.bintray.com/vmware/photon_release_1.0_x86_64'
Disabling Repo: 'VMware Photon Linux 1.0(x86_64)'
Error: Failed to synchronize cache for repo 'VMware Lightwave 1.0(x86_64)' from 'https://dl.bintray.com/vmware/lightwave'
Disabling Repo: 'VMware Lightwave 1.0(x86_64)'
Error: Failed to synchronize cache for repo 'VMware Photon Extras 1.0(x86_64)' from 'https://dl.bintray.com/vmware/photon_extras'
Disabling Repo: 'VMware Photon Extras 1.0(x86_64)'
Error: Failed to synchronize cache for repo 'VMware Photon Linux 1.0(x86_64)Updates' from 'https://dl.bintray.com/vmware/photon_updates_1.0_x86_64'
Disabling Repo: 'VMware Photon Linux 1.0(x86_64)Updates'
```

Let me know what additional information you'd like to see.

**Comment by ppadmavilasom** [comment]
i dont use vagrant much.  tried now and got the same failure as you but the reason is that the vagrant vm did not have an ip address and no net connectivity. i will find a way to verify with the same env as you.

When it says failed to synchronize cache, its a network connection issue and tdnf is using libcurl for this. you have verified that curl works for one of the urls. 

strace or tcpdump might get us some more insight

**Comment by markpeek** [comment]
@lowescott is this still occurring for you? I was able to update a Fusion vagrant Photon OS two days ago and just now I was able to update via tdnf on a new VM (using a 1.2.2 box).
```
==> default: + echo 'Wed Aug 16 13:54:37 UTC 2017: photon-setup-start'
==> default: + sudo tdnf makecache
==> default: Refreshing metadata for: 'VMware Photon Extras 1.0(x86_64)'
==> default: Refreshing metadata for: 'VMware Lightwave 1.0(x86_64)'
==> default: Refreshing metadata for: 'VMware Photon Linux 1.0(x86_64)Updates'
==> default: Refreshing metadata for: 'VMware Photon Linux 1.0(x86_64)'
==> default: Metadata cache created.
==> default: + sudo tdnf update -y
==> default:
==> default: Installing:
==> default: libselinux                      x86_64      2.6-1.ph1           158.07 k
...
```

**Comment by lowescott** [comment]
@markpeek Yes, this is still happening. I just tested it on two different systems (first system is running macOS 10.11.6 with VMware Fusion and Vagrant; second system is running Fedora 25 with VirtualBox and Vagrant). I used v1.2.2 of the vmware/photon box on both systems. On both systems, running `tdnf check-update` failed; yet, on both systems I was able to use `curl` to retrieve HTML content from `http://dl.bintray.com:80/v1/content/vmware/photon_extras` (as an example). I don't know if it is HTTP redirects causing an issue (I had to use `curl -L` to retrieve the HTML content, otherwise it would simply report the content had moved to a new location) or something else.

**Comment by ppadmavilasom** [comment]
@lowescott does curl work with the https url without using -k

**Comment by lowescott** [comment]
@ppadmavilasom Yes, `curl` works without the `-k` parameter, meaning it simply indicates that the content has been moved to a different location (need to use `-L` to have it follow the redirect).

**Comment by ppadmavilasom** [comment]
@lowescott i see you pasted an http url in the last update (as opposed to https). i mentioned -k  trying to rule out if this is a certificate related issue - only valid if you are using https with curl

**Comment by lowescott** [comment]
@ppadmavilasom Gotcha, no worries. I've tried with both HTTPS and HTTP URLs; the HTTPS URL just redirects to an HTTP URL, but there's no certificate error that I've seen.

**Comment by ppadmavilasom** [comment]
sorry for these questions just cause debugging blind is a bit hard - are you root? if not, are you using sudo for tdnf commands?

**Comment by lowescott** [comment]
@ppadmavilasom No worries on the questions. No, I'm not root, but I was (am) using `sudo`. Just tried it again and it worked this time (after failing every time I tried it for the last 2 days). I have _no_ idea why it was failing, or why it worked this time.

Feel free to close this issue; I'll re-open if the problem re-surfaces.
