### ISSUE TITLE
getting compilation error at creating packaging for kubernetes

### ISSUE THREAD

**Issue by goreshmusalay** [vmware/photon#678]
Hi
I want a custom linux-esx build that i need to give input for the vic source at its compilation

I changes the config-esx under the SPEC/linux folder to enable jprobes
and executes 
sudo make all -j 4

I followed the steps that were stated in following link
https://blogs.vmware.com/cloudnative/2015/12/02/building-photon-os-from-source/

tried it multiple times, but its resulting into the same error

------------------------------------------
Building Package:kubernetes
133 {'openjdk8-sample': ['glib-devel', 'icu-devel', 'openjdk', 'openjre', 'icu', 'harfbuzz', 'harfbuzz-devel', 'freetype2', 'freetype2-devel', 'alsa-lib', 'alsa-lib-devel', 'xcb-proto', 'libXdmc    p-devel', 'libXau-devel', 'util-macros', 'xtrans', 'libxcb-devel', 'fontconfig-devel', 'proto', 'libXdmcp', 'libxcb', 'libXau', 'fontconfig', 'xtrans-devel', 'libX11', 'libX11-devel', 'libXe    xt', 'libXext-devel', 'libICE-devel', 'libSM', 'libICE', 'libSM-devel', 'libXt', 'libXmu', 'libXt-devel', 'libXmu-devel', 'libXrender', 'libXrender-devel'], 'apache-maven': ['apache-maven'],     'openjdk8-doc': ['glib-devel', 'icu-devel', 'openjdk', 'openjre', 'icu', 'harfbuzz', 'harfbuzz-devel', 'freetype2', 'freetype2-devel', 'alsa-lib', 'alsa-lib-devel', 'xcb-proto', 'libXdmcp-d    evel', 'libXau-devel', 'util-macros', 'xtrans', 'libxcb-devel', 'fontconfig-devel', 'proto', 'libXdmcp', 'libxcb', 'libXau', 'fontconfig', 'xtrans-devel', 'libX11', 'libX11-devel', 'libXext'    , 'libXext-devel', 'libICE-devel', 'libSM', 'libICE', 'libSM-devel', 'libXt', 'libXmu', 'libXt-devel', 'libXmu-devel', 'libXrender', 'libXrender-devel'], 'openjdk8': ['glib-devel', 'icu-deve    l', 'openjdk', 'openjre', 'icu', 'harfbuzz', 'harfbuzz-devel', 'freetype2', 'freetype2-devel', 'alsa-lib', 'alsa-lib-devel', 'xcb-proto', 'libXdmcp-devel', 'libXau-devel', 'util-macros', 'xt    rans', 'libxcb-devel', 'fontconfig-devel', 'proto', 'libXdmcp', 'libxcb', 'libXau', 'fontconfig', 'xtrans-devel', 'libX11', 'libX11-devel', 'libXext', 'libXext-devel', 'libICE-devel', 'libSM    ', 'libICE', 'libSM-devel', 'libXt', 'libXmu', 'libXt-devel', 'libXmu-devel', 'libXrender', 'libXrender-devel'], 'openjre8': ['glib-devel', 'icu-devel', 'openjdk', 'openjre', 'icu', 'harfbuz    z', 'harfbuzz-devel', 'freetype2', 'freetype2-devel', 'alsa-lib', 'alsa-lib-devel', 'xcb-proto', 'libXdmcp-devel', 'libXau-devel', 'util-macros', 'xtrans', 'libxcb-devel', 'fontconfig-devel'    , 'proto', 'libXdmcp', 'libxcb', 'libXau', 'fontconfig', 'xtrans-devel', 'libX11', 'libX11-devel', 'libXext', 'libXext-devel', 'libICE-devel', 'libSM', 'libICE', 'libSM-devel', 'libXt', 'lib    Xmu', 'libXt-devel', 'libXmu-devel', 'libXrender', 'libXrender-devel'], 'openjdk8-src': ['glib-devel', 'icu-devel', 'openjdk', 'openjre', 'icu', 'harfbuzz', 'harfbuzz-devel', 'freetype2', 'f    reetype2-devel', 'alsa-lib', 'alsa-lib-devel', 'xcb-proto', 'libXdmcp-devel', 'libXau-devel', 'util-macros', 'xtrans', 'libxcb-devel', 'fontconfig-devel', 'proto', 'libXdmcp', 'libxcb', 'lib    Xau', 'fontconfig', 'xtrans-devel', 'libX11', 'libX11-devel', 'libXext', 'libXext-devel', 'libICE-devel', 'libSM', 'libICE', 'libSM-devel', 'libXt', 'libXmu', 'libXt-devel', 'libXmu-devel',     'libXrender', 'libXrender-devel']}
134 Makefile:229: recipe for target 'packages' failed

**Comment by YustasSwamp** [comment]
Try just `sudo make linux-esx` instead

**Comment by goreshmusalay** [comment]
hitting into following issue 

waning: /home/gmusalay/repos/photon/stage/PUBLISHRPMS/x86_64/filesystem-1.0-7.ph1.x86_64.rpm: Header V3 RSA/SHA1 Signature, key ID 66fd4949: NOKEY
warning: %post(bash-4.4-1.ph1.x86_64) scriptlet failed, exit status 127

**Comment by YustasSwamp** [comment]
It is not an issue, just warning

**Comment by goreshmusalay** [comment]
it appears for all the rpms that it tries to build, is it also expected behavior ?

**Comment by YustasSwamp** [comment]
yes

**Comment by goreshmusalay** [comment]
can you once check for the issue i am hitting described in issue#6204

**Comment by YustasSwamp** [comment]
Is it resolved? Do you still need a help?
Thanks,
--Alexey

**Comment by YustasSwamp** [comment]
Please reopen it you still experiencing this issue.
