### ISSUE TITLE
Can you provide a mesos package of lower version

### ISSUE THREAD

**Issue by alex-ren** [vmware/photon#683]
Hi, I tried to build a photon-base chronos docker image from mesosphere/chronos:v3.0.0. I used the mesos package provided by photon and copied the jar file for chronos from mesosphere/chronos:v3.0.0. When I run the docker image, I got the following error:
19:42:14.479 [main] ERROR org.apache.mesos.chronos.scheduler.Main$ - Chronos has exited because of an unexpected error: Mesos JAR version 1.0.1 is not backwards compatible with Mesos native library version 0.28.2

Is it possible for you to provide a mesos package with Mesos native library version 0.28.1, which is compatible with chronos v3.0.0? Thanks.

**Comment by dthaluru** [comment]
We wont able to provide lower version as we are already at latest version because of security reasons. We dont have 0.28.1 but we have 0.24.0. 
If you want to use 0.24.0, use below command to install.
tdnf install mesos-0.24.0
