### ISSUE TITLE
Missing ip_gre module

### ISSUE THREAD

**Issue by nirlya** [vmware/photon#684]
Hi,

I can't load ip_gre module in the latest version.

> root@photon-machine [ / ]# uname -r
4.4.82-1.ph1-esx
> 
> root@photon-machine [ / ]# modprobe ip_gre
modprobe: FATAL: Module ip_gre not found.

It seems something change with the "-esx" :

> root@photon-machine [ /lib/modules ]# ls
4.4.82-1.ph1  4.4.82-1.ph1-esx

> root@photon-machine [ /lib/modules/4.4.82-1.ph1/kernel/net/ipv4 ]# ls
ah4.ko.xz        inet_lro.ko.xz   ipcomp.ko.xz    tunnel4.ko.xz          xfrm4_mode_transport.ko.xz
esp4.ko.xz       ip_gre.ko.xz     ipip.ko.xz      udp_diag.ko.xz         xfrm4_mode_tunnel.ko.xz
gre.ko.xz        ip_tunnel.ko.xz  netfilter       udp_tunnel.ko.xz       xfrm4_tunnel.ko.xz
inet_diag.ko.xz  ip_vti.ko.xz     tcp_diag.ko.xz  xfrm4_mode_beet.ko.xz

Thx in advance for your help.

**Comment by YustasSwamp** [comment]
ip_gre is in generic linux kernel, not in linux-esx.
To switch from -esx to generic kernel you need to point /boot/photon.cfg symlink from linux-%{version}-esx.cfg to linux-%{version}.cfg, and reboot.

**Comment by nirlya** [comment]
It works, thanks a lot.

In the Photon 2, the generic kernel disappear. Do you know if it will be back ?

**Comment by YustasSwamp** [comment]
It is on repository )
`tdnf install -y linux && reboot`
