### ISSUE TITLE
scriptlet failed, exit status 127

### ISSUE THREAD

**Issue by goreshmusalay** [vmware/photon#685]
I am trying to build the photon os
Steps followed
1) clone photon from git
2) copy RPMS from "ftp://photon-filer/builds/1.0/834-09-01-17/stage/RPMS/"
3) executed "sudo make linux-esx"

warning: /home/gmusalay/repos/photon/stage/PUBLISHRPMS/x86_64/filesystem-1.0-7.ph1.x86_64.rpm: Header V3 RSA/SHA1 Signature, key ID 66fd4949: NOKEY
warning: %post(bash-4.4-1.ph1.x86_64) scriptlet failed, exit status 127

**Comment by YustasSwamp** [comment]
It is known warning. not a real issue. Thanks.
