### ISSUE TITLE
Photon base for for given docker using Erlang

### ISSUE THREAD

**Issue by rejji** [vmware/photon#686]
I need to create a photon base docker image for eMQTT. This is basically migration of the Dockerfile from Alpyne to Photon:1.0 for this: https://github.com/emqtt/emq-docker/blob/52c8b6e559296f89e4afdbcf124e120817c55f84/Dockerfile

When I am trying to install the first package erlang, it fails talking about missing package.
Which repo I can use for erlang and all other packages here that are reqd to build the emqttd/emq-relx code base.

What are tdnf equivalents for the apk options --no-cache, --virtual, --purge,  
Thanks

**Comment by ppadmavilasom** [comment]
how are you installing erlang? could you please paste the command and output?

**Comment by rejji** [comment]
I used these commands: 

sh-4.3# wget https://packages.erlang-solutions.com/erlang-solutions-1.0-1.noarch.rpm
sh-4.3# rpm -Uvh erlang-solutions-1.0-1.noarch.rpm
error: Failed dependencies:
	rpmlib(PayloadIsXz) <= 5.2-1 is needed by erlang-solutions-1.0-1.noarch

sh-4.3# yum search rpmlib
lightwave                                                                                                                                                                            | 1.3 kB  00:00:00     
photon                                                                                                                                                                               | 1.3 kB  00:00:00     
photon-extras                                                                                                                                                                        | 1.3 kB  00:00:00     
photon-updates                                                                                                                                                                       | 1.3 kB  00:00:00     
Warning: No matches found for: rpmlib
No Matches found

-- 
sh-4.3# yum install erlang
Setting up Install Process
No package erlang available.
Error: Nothing to do

**Comment by ppadmavilasom** [comment]
erlang is not available in 1.0. 
you can try it from photon 2.0 beta - https://vmware.bintray.com/photon_release_2.0_x86_64/x86_64/erlang-19.3-1.ph2.x86_64.rpm

**Comment by rejji** [comment]
Which command you used - is it yum install only. 

Can we use photon 2.0 beta in production - are there any vSecurity concerns? What tag I can use for FROM vmware/photon:1.0 in Dockerfile? And I hope other packages are available like - erlang-orber etc. 

Any idea about tdnf equivalents for the apk options --no-cache, --virtual, --purge,

**Comment by ppadmavilasom** [comment]
root@photon-8405f8af2640 [ ~ ]# docker run -it vmware/photon
root [ / ]# curl -L https://vmware.bintray.com/photon_release_2.0_x86_64/x86_64/erlang-19.3-1.ph2.x86_64.rpm -o erlang.rpm
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 45.2M  100 45.2M    0     0  1067k      0  0:00:43  0:00:43 --:--:--  763k
root [ / ]# rpm -Uvh erlang.rpm 
Preparing...                          ################################# [100%]
Updating / installing...
   1:erlang-19.3-1.ph2                ################################# [100%]

i wouldnt recommend using beta software in production. you can build erlang and related packages on your own and use as required if needed in 1.0

not familiar with apk. tdnf works like yum and implements a useful subset of yum commands and options. please see https://github.com/vmware/photon/blob/master/docs/photon-admin-guide.md#tiny-dnf-for-package-management

**Comment by rejji** [comment]
Thanks Priyesh
