### ISSUE TITLE
photon OS 2.0RC HW13 fails import by Fusion 10.0.1

### ISSUE THREAD

**Issue by Epicyon** [vmware/photon#690]
Error dialog stating pvscsi is an invalid adapter type.

**ovftool log:**
2017-10-02T12:25:01.698-05:00 verbose OVFTool[7FFF8C6D4340] [Originator@6876 sub=Default] Creating disk /Users/jling/vm/photonOS-2.0RC.vmwarevm//photonOS-2.0RC-disk1.vmdk, 33554432 sectors, pvscsi
2017-10-02T12:25:01.718-05:00 verbose OVFTool[7FFF8C6D4340] [Originator@6876 sub=Default] Backtrace: 
--> [backtrace begin] product: VMware Fusion, version: e.x.p, build: build-6230482, tag: OVFTool, cpu: x86_64, os: macosx, buildType: release
--> backtrace[00] libvmacore.dylib[0x002AC359]
--> backtrace[01] libvmacore.dylib[0x0006790A]
--> backtrace[02] libvmacore.dylib[0x0001C7BF]
--> backtrace[03] ovftool[0x000C273F]
--> backtrace[04] ovftool[0x0018E276]
--> backtrace[05] ovftool[0x000D8590]
--> backtrace[06] ovftool[0x001CD71D]
--> backtrace[07] ovftool[0x000535AC]
--> backtrace[08] ovftool[0x000515F9]
--> backtrace[09] ovftool[0x0004FCA8]
--> backtrace[10] ovftool[0x0009CEC9]
--> backtrace[11] ovftool[0x0009E53B]
--> backtrace[12] ovftool[0x00007CB4]
--> backtrace[13] (no module)
--> [backtrace end]

**Comment by suezzelur** [comment]
This is a Fusion only issue, the fields that are not recognized by Fusion backend makes the guest Os type to change to Other (32-bit) which is the default.
 Workaround would be to manually change it to Other-64
