### ISSUE TITLE
Help need with Remote docker port expose

### ISSUE THREAD

**Issue by MichelDiz** [vmware/photon#691]
Most of the articles seem outdated with the version I'm using. Things like:

`vi /etc/default/docker`

`DOCKER_OPTS="-H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock"`

`vi /etc/systemd/scripts/iptables`

`iptables -A INPUT -p tcp --dport 2376 -j ACCEPT`
`iptables -A INPUT -p tcp --dport 2375 -j ACCEPT`

`systemctl restart iptables`

`systemctl start docker`

`systemctl enable docker`

And several other steps in other articles have no effect. I have a Photon running perfectly. The address http://192.168.76.135:2375/info does not work at all.

can anybody give me a beacon on this?

Thnks

Cheers

**Comment by vinaykul** [comment]
Hi Michel,

Could you please provide the version of docker you are using? 
Also please provide the outputs of 'ip addr show',  'iptables -L' , and 'iptables -L -t nat'?

Could you also try passing the options to dockerd directly?

```
root@p1k8test [ /usr/lib/systemd/system ]# cat docker.service.d/10-dockerd.conf 
[Service]
ExecStart=
ExecStart=/usr/bin/dockerd -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock
root@p1k8test [ /usr/lib/systemd/system ]#

```
Thanks,
Vinay

**Comment by MichelDiz** [comment]
I'm using the Photon OS 2.0 RC - I'm not with the Mac now, but the Docker inside is the native one from taht ISO.

Full ISO | 2.2GB | 5c049d5ff40c8f22ae5e969eabd1ee8cd6b834e7 | 88cc8ecf2a7f6ae5ac8eb15f54e4a821

**Comment by MichelDiz** [comment]
I set up Photon on Hyper-V in Windows 10.
Tried what you ask, but no result.

root@photon-40******* [ /usr/lib/systemd/system ]# cat docker.service.d/10-dockerd.conf
cat:  cat docker.service.d/10-dockerd.conf: No such file or directory

**Comment by vinaykul** [comment]
My earlier post was unclear .. you have to create 10-dockerd.conf as shown above. Please try the following and let me know if it unblocks you:

`

> root@footest [ ~ ]# mkdir -p /usr/lib/systemd/system/docker.service.d
> 
> root@footest [ ~ ]# echo -e "[Service]\nExecStart=\nExecStart=/usr/bin/dockerd -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock" > /usr/lib/systemd/system/docker.service.d/10-dockerd.conf
> 
> root@footest [ ~ ]# systemctl restart docker.service
> 
> root@footest [ ~ ]# curl localhost:2375/info
> {"ID":"U7C6:PHM6:7QAY:XW27:SM7N:4O7J:K7S4:AU2H:SB24:TBA7:T2L2:73US","Containers":0,"ContainersRunning":0,"ContainersPaused":0,"ContainersStopped":0,"Images":1,"Driver":"overlay2","DriverStatus":[["Backing Filesystem","extfs"],
> ...
> ...
> root@footest [ ~ ]#

`

**Comment by DanielLangenhan** [comment]
same issue....cat get it to work with photonOS 2.
root@photon-machine [ ~ ]# cat /usr/lib/systemd/system/docker.service.d/10-dockerd.conf
[Service]
ExecStart=
ExecStart=/usr/bin/dockerd -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock
Even after opening the port on IPtables....nada
curl localhost:2375/info
curl: (7) Failed to connect to localhost port 2375: Connection refused

**Comment by DanielLangenhan** [comment]
@MichelDiz The problem is properly that your network is set incorrectly. Try a pure deploy and check. The right settings for networks are:

cat > /etc/systemd/network/10-eth0-static.network << "EOF"
[Match]
Name=eth0

[Network]
DHCP=no
Address=192.168.220.15/24
Gateway=192.168.220.2
DNS=192.168.220.10
Domains=mylab.local
EOF

chmod 644 /etc/systemd/network/10-eth0-static.network
rm /etc/systemd/network/99-dhcp-en.network

**Comment by dthaluru** [comment]
Please reopen the issue if you still hitting the issue. Thanks!!

**Comment by rainabba** [comment]
For anyone else hitting this, I had to follow the steps that @MichelDiz provided AND @DanielLangenhan steps to setup a static IP (I was on DHCP before). I think it was that last bit that mattered for me.

**Comment by Ghosty141** [comment]
I also had to change both like @rainabba said. I encountered another problem though, I can't set another IP instead of 0.0.0.0

**Comment by CollinChaffin** [comment]
This issue should never have been closed as with v3 photon, none of the above works on multiple builds I've tested and god forbid a simple one page instruction be posted for this in the wiki perhaps I should post a PR.

Here are the exact commands in order I can literally copy and paste to disable (a properly upgraded, since they refuse to keep the photon repos updated) existing docker daemon and properly per docker docs I've found - to enable both local socket on demand as well as and remote API access:

# Enable Local/Remote Docker API on PhotonOS

## Prerequisites

You must have already performed the following in one form or another **as well as properly set a STATIC IP**.  Bear in mind many instructions do not properly show how to commit iptables changes on Photon which then survive reboots.

```
iptables -A INPUT -p tcp --dport 2375 -j ACCEPT
iptables -A INPUT -p tcp --dport 2376 -j ACCEPT
iptables-save > /etc/systemd/scripts/ip4save
systemctl restart iptables
```

## Perform (Re)configuration of Docker Daemon (using Proper Local Configs)
```
systemctl stop docker
systemctl disable docker
# IF NEW, DOCKER.SOCKET WON'T EVEN EXIST YET SO IGNORE ANY ERROR/WARNINGS BUT THIS ENABLES THIS TO 
# BE RERUN LATER IF NEEDED AND DOES NOT HURT TO RERUN OVER ITSELF
systemctl stop docker.socket
systemctl disable docker.socket

# FIX/CREATE LOCAL (NOT LIB COPY AS INCORRECTLY STATED BY OTHERS THAT IS OVERWRITTEN ON UPGRADES!!!
echo '[Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
After=network-online.target docker.socket
Requires=docker.socket

[Service]
Type=notify
# the default is not to use systemd for cgroups because the delegate issues still
# exists and systemd currently does not support the cgroup feature set required
# for containers run by docker
ExecStart=/usr/bin/dockerd -H fd:// -H tcp://0.0.0.0:2375
ExecReload=/bin/kill -s HUP $MAINPID
# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity
# Uncomment TasksMax if your systemd version supports it.
# Only systemd 226 and above support this version.
#TasksMax=infinity
TimeoutStartSec=0
# set delegate yes so that systemd does not reset the cgroups of docker containers
Delegate=yes
# kill only the docker process, not all processes in the cgroup
KillMode=process
# restart the docker process if it exits prematurely
Restart=on-failure
StartLimitBurst=3
StartLimitInterval=60s

[Install]
WantedBy=multi-user.target
' > /etc/systemd/system/docker.service

# FIX/CREATE THE NON-EXISTING DOCKER.SOCKET SERVICE ON PHOTONOS IF UPGRADING FROM DEFAULT DOCKER INSTALL
# AGAIN THIS IS A LOCAL NOT LIB THAT WOULD BE OVERWRITTEN ON UPGRADE
echo '[Unit]
Description=Docker Socket for the API
PartOf=docker.service

[Socket]
ListenStream=/var/run/docker.sock
SocketMode=0660
SocketUser=root
SocketGroup=docker

[Install]
WantedBy=sockets.target
' > /etc/systemd/system/docker.socket

# RESTART DOCKER AND TEST VIA SHELL FOR API OUTPUT
systemctl daemon-reload
systemctl enable docker.socket
systemctl enable docker
systemctl start docker
systemctl start docker.socket

# TEST IF WE NOW GET PROPER TCP-BASED API RESPONSE (REMOTE SHOULD NOW WORK TOO)
docker -H tcp://0.0.0.0:2375 ps
```

**Comment by CollinChaffin** [comment]
I also created a full gist of this doc as well as the equivalent as a shell script fully ready to run here:

https://git.io/fjhhO

**Comment by MichelDiz** [comment]
BTW, just to add more info.

If you wanna use the docker binary (/usr/local/bin/docker) from your machine to a remote docker daemon. Just add:
```
export DOCKER_HOST=tcp://192.168.1.100:2375 #add the IP from your machine with 2375 exposed
```

Thanks @CollinChaffin for the magic sh! it works very well.
