### ISSUE TITLE
ICMP commands

### ISSUE THREAD

**Issue by hakkurt** [vmware/photon#692]
May it possible ?
root@Web01 [ ~ ]# ping
-bash: ping: command not found

ping command is not working on Photon 2.0 RC

**Comment by ppadmavilasom** [comment]
tdnf install iputils

**Comment by hakkurt** [comment]
Thank you. Should be installed by default ?

**Comment by ppadmavilasom** [comment]
depends on if you installed full or minimal. full has it by default. minimal does not.

**Comment by avaikararkin** [comment]
IMHO, this should be available even in the minimal install. Right now I am in a chicken-egg problem as my photon installation's tdnf install is failing owing to some network issue, and in absence of ping/nslookup etc. I am unable to narrow down the issue too.

**Comment by jhosee** [comment]
What is the appropriate utility on Photon in order to perform DNS lookups?  I am unable to install dig, nslookup, or host.  Thanks!

**Comment by smaliakkal** [comment]
bindutils is the package which provides dig,nslookup and host commands which can be used for DNS lookup

**Comment by jhosee** [comment]
Thank you! Worked like a charm!

# tdnf install bindutils

**Comment by jodumont** [comment]
@avaikararkin ILOVE the fact they name it minimal and it is minimal not like when you install a minimal version ubuntu and it end with snapd and tralala.
