### ISSUE TITLE
Installation of Centrify failed due to missing pam package

### ISSUE THREAD

**Issue by abhinav-chittora** [vmware/photon#694]
Is there any way to install pam and centrify package? We need to install centrify package on appliance. 

```NAME="VMware Photon"
VERSION="1.0"
ID=photon
VERSION_ID=1.0
PRETTY_NAME="VMware Photon/Linux"
ANSI_COLOR="1;34"
HOME_URL="https://vmware.github.io/photon/"
BUG_REPORT_URL="https://github.com/vmware/photon/issues"

**Comment by ppadmavilasom** [comment]
Can you tell us how you are installing centrify?

**Comment by dthaluru** [comment]
Do you have any update?

**Comment by YustasSwamp** [comment]
No feedback for several months. Close the issue. Please reopen once you have more input. Thanks.
