### ISSUE TITLE
photon:2.0latest docker image's out of box grep does not work due to incorrect flag

### ISSUE THREAD

**Issue by khani92** [vmware/photon#696]
photon 2.0latest docker image has an alias for grep under `/etc/profile.d/dircolors.sh`

```
root [ / ]# \grep "grep" /etc/profile.d/dircolors.sh 
# Setup for /bin/ls and /bin/grep to support color, the alias is in /etc/bashrc.
alias grep='grep --color=auto'
root [ / ]# 
```
also defined here: https://github.com/vmware/photon/blob/master/SPECS/bash/bash.spec#L73, while the default grep package installed does not support `--color` flag
which is why 
`root [ / ]# env | grep "HOME"` fails with `grep: Unknown option color=auto`
but works if we bypass the alias:
```
root [ / ]# env | \grep "HOME" 
HOME=/root
```

Can we fix this to check if grep indeed has the `--color` flag before adding it to the alias
Here's a suggestion from the bash-it community for a similar issue with Alpine Linux: https://github.com/Bash-it/bash-it/issues/884

**Comment by YustasSwamp** [comment]
It is not a bug.
In photon:2.0 we switched to `toybox`. grep tool there has a limited functionality.  If you need standard `grep`- please install it: `tdnf install grep` - it will remove `toybox` and install all alternatives such as `coreutils`
Thanks.

**Comment by ppadmavilasom** [comment]
i think we have fix for this in latests vmware/photon2
