### ISSUE TITLE
PhotonOS 1.0 -- failed setting-up keyboard to "german"

### ISSUE THREAD

**Issue by typoworx-de** [vmware/photon#698]
Cannot change keyboard to german (de-latin1-nodeadkeys). Tried these instructions:

https://communities.vmware.com/thread/511570

$> localectl list-keymaps
Couldn't find any console keymaps

and:
http://kenntwas.de/2015/vmware/vmware-photon-os-deutsche-tastatur-einstellen/

$> vi /etc/sysconfig/console
```
 # Begin /etc/sysconfig/console
 #     Begin /etc/sysconfig/console
 #     KEYMAP="us"
 KEYMAP="de-latin1-nodeadkeys"
 #    FONT="lat1-16 -m utf8"
 #    FONT="lat1-16 -m 8859-1"
 #    KEYMAP_CORRECTIONS="euro2"
 #    UNICODE="1"
 #    LEGACY_CHARSET="iso-8859-1"
 # End /etc/sysconfig/console

```
$> localectl set-keymap de-latin1-nodeadkeys
(no error or response)

Keymap is still running on en_US mappings even after reboot!

$> locale-gen
> de_DE.ISO-8859-1 .... locale alias file '/usr/share/locale/locale.alias' not found ....

**Comment by gr4finger** [comment]
seems you forgot to install the key table files and utilities.
> tdnf install kbd
> localectl list-keymaps
> localectl set-keymap de-latin1

**Comment by typoworx-de** [comment]
> seems you forgot to install the key table files and utilities.
> 
> > tdnf install kbd
> > localectl list-keymaps
> > localectl set-keymap de-latin1

thanks that did it!
