### ISSUE TITLE
Photon OS 2 OVA is empty. Tried to run OVA with virtual hardware v13 (ESX 6.5 and above) on vSphere 6.5 but the VM has no boot disk.

### ISSUE THREAD

**Issue by vmtocloud** [vmware/photon#702]
Link here http://dl.bintray.com/vmware/photon/2.0/GA/ova/photon-custom-hw13-2.0-304b817.ova

**Comment by changpil** [comment]
I manually deployed this ova in my ESX6.5 and the deployment worked as expected.

**Comment by DanielLangenhan** [comment]
My vCenter6.5U1 dosnt want to load the 13 OVA either.

**Comment by ppadmavilasom** [comment]
Please use the v11 version. v11 has been updated recently

**Comment by suezzelur** [comment]
There is an existing issue with VC 6.5 UI which prevents the EFI ova to load properly. Manual deployment to ESX or ovftool deployment to VC should still work for v13 ova.
