### ISSUE TITLE
How to install Bind and Webmin?

### ISSUE THREAD

**Issue by m1chaeldg** [vmware/photon#704]
Hi,

I want to do a vCenter lab. So in installing some services like the VCSA it needs a DNS server.
It is possible to install webmin and BIND server in photonOS? If possible how will I do this?
I like to use the photon OS because it is fast and small.

Thanks

**Comment by ppadmavilasom** [comment]
you can use unbound as the dns server. 
photon does not have webmin. you can build it from sources and use
