### ISSUE TITLE
tdnf install openjdk - documentation issue

### ISSUE THREAD

**Issue by amwales** [vmware/photon#705]
The documentation https://github.com/vmware/photon/blob/master/docs/photon-admin-guide.md 

One notable difference between the two versions of Photon OS pertains to OpenJDK, the package that contains not only the Java runtime environment (openjre) but also the Java compiler (javac). The OpenJDK package appears in the full but not the minimal version of Photon OS. To add support for Java programs to the minimal version of Photon OS, install the Java packages and their dependencies:

tdnf install openjdk
Installing:
openjre 	x86_64    1.8.0.92-1.ph1    95.09 M
openjdk 	x86_64    1.8.0.92-1.ph1    37.63 M

If you try

root@photon-machine [ ~ ]# tdnf install openjdk
Refreshing metadata for: 'VMware Photon Linux 2.0(x86_64) Updates'
Refreshing metadata for: 'VMware Photon Linux 2.0(x86_64)'
Refreshing metadata for: 'VMware Photon Extras 2.0(x86_64)'
No package openjdk available               106    100%
Error(1011) : No matching packages

Intsead to install the openjdk you need to specify openjdk8 and NOT openjdk

root@photon-machine [ ~ ]# tdnf install openjdk8

Installing:
slang                             x86_64           2.3.1a-2.ph2           photon             2.96M 3105063
newt                              x86_64           0.52.20-1.ph2          photon           167.39k 171412
chkconfig                         x86_64           1.9-1.ph2              photon           732.15k 749720
openjre8                          x86_64           1.8.0.152-1.ph2        photon           104.02M 109075609
openjdk8                          x86_64           1.8.0.152-1.ph2        photon            39.27M 41172339

Total installed size: 147.13M 154274143
Is this ok [y/N]:y

Downloading:
openjdk8                              12293686    100%
openjre8                              42114688    100%
chkconfig                               219609    100%
newt                                    102265    100%
slang                                   965219    100%
Testing transaction
Running transaction
Installing/Updating: slang-2.3.1a-2.ph2.x86_64
Installing/Updating: newt-0.52.20-1.ph2.x86_64
Installing/Updating: chkconfig-1.9-1.ph2.x86_64
Installing/Updating: openjre8-1.8.0.152-1.ph2.x86_64
Installing/Updating: openjdk8-1.8.0.152-1.ph2.x86_64

Complete!

Please update the documentation

**Comment by ppadmavilasom** [comment]
Fixed. https://github.com/vmware/photon/commit/501a42d7165b00397d6bc78424ab34af213b11a0
