### ISSUE TITLE
documentation makes reference to tndf instead of tdnf

### ISSUE THREAD

**Issue by amwales** [vmware/photon#706]
The documentation https://github.com/vmware/photon/blob/master/docs/pmd-cli.md make a reference to installing the pmd-cli

root@photon-machine [ ~ ]# tndf install pmd-cli
-bash: tndf: command not found

this should be

root@photon-machine [ ~ ]# tdnf install pmd-cli

Installing:
libgpg-error                      x86_64           1.27-1.ph2             photon           118.88k 121733
cyrus-sasl                        x86_64           2.1.26-13.ph2          photon           558.79k 572200
libgcrypt                         x86_64           1.8.1-1.ph2            photon             1.18M 1235073
perl                              x86_64           5.24.1-4.ph2           photon            49.41M 51811861
libxml2                           x86_64           2.9.6-1.ph2            photon             7.30M 7651659
haveged                           x86_64           1.9.1-3.ph2            photon           186.28k 190753
openldap                          x86_64           2.4.44-3.ph2           photon             1.52M 1598869
iputils                           x86_64           20151218-4.ph2         photon           262.51k 268810
ntp                               x86_64           4.2.8p10-4.ph2         photon             6.28M 6581037
pcre                              x86_64           8.40-4.ph2             photon           699.09k 715866
pmd-libs                          x86_64           0.0.5-3.ph2            photon           330.13k 338056
lightwave-client-libs             x86_64           1.3.1-5.ph2            photon             2.20M 2308680
likewise-open                     x86_64           6.2.11.4-3.ph2         photon            11.52M 12078104
netmgmt                           x86_64           1.1.0-9.ph2            photon           149.77k 153360
pmd-cli                           x86_64           0.0.5-3.ph2            photon            58.79k 60200

Total installed size:  81.72M 85686261
Is this ok [y/N]:y

Downloading:
pmd-cli                                  33148    100%
netmgmt                                  72283    100%
likewise-open                          3899636    100%
lightwave-client-libs                   737040    100%
pmd-libs                                 93441    100%
pcre                                    301344    100%
ntp                                    3637335    100%
iputils                                 129855    100%
openldap                                890618    100%
haveged                                  75010    100%
libxml2                                1589185    100%
perl                                  18290806    100%
libgcrypt                               510631    100%
cyrus-sasl                              298403    100%
libgpg-error                             61382    100%
Testing transaction
Running transaction
Installing/Updating: libgpg-error-1.27-1.ph2.x86_64
Installing/Updating: libgcrypt-1.8.1-1.ph2.x86_64
Installing/Updating: iputils-20151218-4.ph2.x86_64
Installing/Updating: cyrus-sasl-2.1.26-13.ph2.x86_64
Installing/Updating: openldap-2.4.44-3.ph2.x86_64
Installing/Updating: perl-5.24.1-4.ph2.x86_64
Installing/Updating: ntp-4.2.8p10-4.ph2.x86_64
Installing/Updating: libxml2-2.9.6-1.ph2.x86_64
Installing/Updating: haveged-1.9.1-3.ph2.x86_64
Installing/Updating: likewise-open-6.2.11.4-3.ph2.x86_64
Waiting for lwreg startup.
ok
Installing settings from /opt/likewise/share/config/accounts.reg...
Installing settings from /opt/likewise/share/config/dcerpcd.reg...
Installing settings from /opt/likewise/share/config/eventlogd.reg...
Installing settings from /opt/likewise/share/config/lsassd.reg...
Installing settings from /opt/likewise/share/config/lwiod.reg...
Installing settings from /opt/likewise/share/config/lwreg.reg...
Installing settings from /opt/likewise/share/config/netlogond.reg...
Installing settings from /opt/likewise/share/config/privileges.reg...
Installing settings from /opt/likewise/share/config/rdr.reg...
Starting service dependency: netlogon
Starting service dependency: lwio
Starting service dependency: rdr
Starting service: lsass
Installing/Updating: lightwave-client-libs-1.3.1-5.ph2.x86_64
Installing/Updating: pmd-libs-0.0.5-3.ph2.x86_64
Installing/Updating: pcre-8.40-4.ph2.x86_64
Installing/Updating: netmgmt-1.1.0-9.ph2.x86_64
Installing/Updating: pmd-cli-0.0.5-3.ph2.x86_64

Complete!

**Comment by ppadmavilasom** [comment]
Fixed - https://github.com/vmware/photon/commit/501a42d7165b00397d6bc78424ab34af213b11a0
