### ISSUE TITLE
nfs-utils does not come with rpc.idmapd

### ISSUE THREAD

**Issue by deed02392** [vmware/photon#708]
It seems as if the nfs utility doesn't bundle rpc.idmapd. This means that UID/GIDs aren't mapped when mounting remote nfs shares and instead my mounted exports show files like so:

`drwxr-xr-x 424 4294967294 4294967294 424 Nov 15 15:32 foobar`

Is there a solution for enabling idmapd? It is not available in `tdnf` on Photon 2.0 GA Full.

**Comment by ToeiRei** [comment]
Same problem here. Looks like we're bound to the old NFS3 model

**Comment by YustasSwamp** [comment]
You can add rpc.idmapd package. We are happy to review your commit

**Comment by deed02392** [comment]
I no longer use Photon @YustasSwamp

**Comment by YustasSwamp** [comment]
Thanks

**Comment by DRoet** [comment]
this is still a problem for other people using nfsv4 tho
