### ISSUE TITLE
Docker newbie: How to run docker-compose on PhotonOS

### ISSUE THREAD

**Issue by bonne1** [vmware/photon#714]
Want to run Metasfresh. I did:

yum install git

and then followed:
http://docs.metasfresh.org/howto_collection/EN/How_do_I_setup_the_metasfresh_stack_using_Docker.html

But when trying to do "docker-compose build", I get "command unknown". I have got a lot of other docker commands... how to add the compose part?

Regards, Lars.

**Comment by Neo-Desktop** [comment]
you need to install docker-compose to a place in your path, i.e. `/usr/local/bin/docker-compose`
then docker-compose will work as expected

**Comment by ppadmavilasom** [comment]
Please follow the instructions here: https://docs.docker.com/compose/install/#install-compose
Reopen if you still have issues.
