### ISSUE TITLE
Unable to install 32 bit packages (zlib.i686, glibc.i686) on photon os (4.4.92-1.ph1 #1-photon)

### ISSUE THREAD

**Issue by sreenivasa26** [vmware/photon#718]
I'm trying to install zlib.i686 and glibc.i686 packages by using yum
`root@server [ /etc/yum.repos.d ]# yum install zlib.i686 glibc.i686

Setting up Install Process
No package zlib.i686 available.
No package glibc.i686 available.
Error: Nothing to do`

`root@server [ /etc/yum.repos.d ]# yum search zlib glibc
==================== N/S Matched: zlib ==============================
zlib-devel.x86_64 : Header and development files for zlib
zlib.x86_64 : Compression and decompression routines

==================== N/S Matched: glibc ==============================
glibc-devel.x86_64 : Header files for glibc
glibc-lang.x86_64 : Additional language files for glibc
glibc.x86_64 : Main C library

  Name and summary matches mostly, use "search all" for everything.`

**Comment by YustasSwamp** [comment]
Photon OS does not provide 32bit packages. Thanks.

**Comment by sreenivasa26** [comment]
Is there any way that I can install zlib.i686 and glibc.i686 packages on Photon OS?

**Comment by YustasSwamp** [comment]
In container. 32 bit container should work.
