### ISSUE TITLE
Static routes not working

### ISSUE THREAD

**Issue by patrikwm** [vmware/photon#719]
I have a problem with both static routes and adding routes through DHCP.

Im using the default 99-dhcp-en.network rule in /etc/systemd/network

i added following config to the same file to get routs from windows server DHCP (121 classic static route)

[DHCP]
UseRoutes=true

This did not work. I added following to the same file.

[Route]
Gateway=10.10.10.1
Destination=20.20.20.0/24 

When i updated config i ran "systemctl restart systemd-networkd" to reload it. This did not add the routes to the list shown by "ip route show" command.
Reboot does not add routes either.

Only way i can update a route is through the command "ip route add 20.20.20.0/24 via 10.10.10.1" that is not persistant though.

Any suggestions?

**Comment by muhfugen** [comment]
What version of Photon? Does it work if you assign the VM a static IP? What if your reverse the order or `Gateway` and `Destination`? On photon 1.0 the following works fine for me with a static IP.

```
[Route]
Destination=10.1.0.0/16
Gateway=10.5.0.1
```

**Comment by patrikwm** [comment]
Hi! I tried following config which did not work

```
[Match]
Name=e*

[Network]
DHCP=yes
IPv6AcceptRA=no

[Route]
Destination=10.1.0.0/16
Gateway=10.5.0.1
```
Then i tried with static IP address and the route is there as expected.

```
[Match]
Name=e*

[Network]
DHCP=no
IPv6AcceptRA=no
Address=10.5.0.2/24
Gateway=10.5.0.1

[Route]
Destination=10.1.0.0/16
Gateway=10.5.0.120
```

The gateway for network 10.1.0.0/16 goes through a different firewall than the default gateway so i need this route to access the machine internally.

**Comment by muhfugen** [comment]
I can confirm that happens on Photon 2.0 with systemd-233-9.ph2. I think you will probably have to report this upstream to the systemd project's github to get it fixed if it is a supported configuration. As a work around you can write a systemd unit to manually add these routes at boot time and whenever systemd-networkd is restarted.

**Comment by patrikwm** [comment]
It seems like it's already reported to systemd github page. Thanks for all the help! Ill continue to follow that thread.
[https://github.com/systemd/systemd/issues/1850](https://github.com/systemd/systemd/issues/1850)

**Comment by kaushik229** [comment]
Thanks Patrik,

We ll also monitor this and once the fix is available, will patch systemd in photon distribution.

Thanks,
Kaushik

**Comment by ssahani** [comment]
```GatewayOnlink=```  option works with [Route] section

```
[Match]                                                                                                                                                                                        
Name=veth-test                                                                                                                                                                                 
                                                                                                                                                                                               
[Network]                                                                                                                                                                                      
DHCP=no                                                                                                                                                                                        
IPv6AcceptRA=no                                                                                                                                                                                
                                                                                                                                                                                               
[Route]                                                                                                                                                                                        
Destination=10.1.0.0/16                                                                                                                                                                        
Gateway=10.5.0.1                                                                                                                                                                               
GatewayOnlink=true   
```

ip route
```
default via 192.168.225.1 dev wlan0 proto dhcp metric 600 
10.1.0.0/16 via 10.5.0.1 dev veth-test proto static onlink  <===============================
172.16.130.0/24 dev vmnet8 proto kernel scope link src 172.16.130.1 
```

If you don't set this 

```

lo: Unmanaged
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_31 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=41 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
veth-test: Could not set route: Network is unreachable <===========================

```

As  per 
```
[DHCP]
UseRoutes=true
```
>> This did not work. I added following to the same file.

Not working can be only debugged via setting log level to debug
```
SYSTEMD_LOG_LEVEL=debug /lib/systemd/systemd-networkd
Failed to read $container of PID 1, ignoring: Permission denied
Found container virtualization none.
Bus n/a: changing state UNSET → OPENING
Bus n/a: changing state OPENING → AUTHENTICATING
Failed to open configuration file '/etc/systemd/networkd.conf': Success
timestamp of '/etc/systemd/network' changed
timestamp of '/run/systemd/network' changed
Ignoring /run/systemd/network/test-veth.network, because it's not a regular file with suffix .netdev.
Ignoring /run/systemd/network/test-peer.network, because it's not a regular file with suffix .netdev.
Ignoring /usr/lib/systemd/network/tmp, because it's not a regular file with suffix .netdev.
veth-test: loaded veth

```

**Comment by ssahani** [comment]
BTW my guess is ```https://github.com/systemd/systemd/blob/master/src/network/networkd-dhcp4.c#L100```

take a wireshark dump and see what options your dhcp server is offering.

**Comment by ssahani** [comment]
Please try with  https://github.com/systemd/systemd/pull/10938

**Comment by MikeVL** [comment]
i add default gateway to DHCP option 121
![Снимок экрана 2019-04-10 в 13 59 43](https://user-images.githubusercontent.com/118285/55873674-f2e8a400-5b98-11e9-8af7-e23c26dcfdaa.jpg)

Now Photon v3.0 set default gateway.

But Photon v2.0 set it twice:
![Снимок экрана 2019-04-10 в 14 00 47](https://user-images.githubusercontent.com/118285/55873731-127fcc80-5b99-11e9-8f9a-9eb63cd504b4.jpg)

**Comment by YustasSwamp** [comment]
Was it resolved?

**Comment by ssahani** [comment]
I pulled the patch already. https://github.com/vmware/photon/commit/d3b66847a4ab42ec2effe3bcc1f220d37f297185

**Comment by YustasSwamp** [comment]
Thanks!

**Comment by concept-trainer** [comment]
Hi,

After very long troubleshooting i resolved by this.

OS Version:
##############################################
NAME="VMware Photon OS"
VERSION="3.0"
ID=photon
VERSION_ID=3.0
PRETTY_NAME="VMware Photon OS/Linux"
###############################################

##########################################
vi /etc/systemd/network/10-eth0.network

[Match]
Name=eth0

[Network]
Domains=concept-trainer.com concept-trainer.com
Gateway=10.26.36.1
Address=10.26.36.93/24
DHCP=no

[Route]
Destination=10.25.0.0/24
Gateway=10.26.36.101
GatewayOnlink=true


[DHCP]
UseDNS=false
UseRoutes=true

################################################


This is the Correct Configuration for the mentioned OS and its working fine for me.

i decided to help of others.
