### ISSUE TITLE
Changing the docker0 subnet range and IP allocation

### ISSUE THREAD

**Issue by statseeker** [vmware/photon#726]
This is more of a question than an issue,

How do you adjust the default docker0 IP range that gets assigned to dockers as I do not want to use the 172.17.x.x network and rather use my own.

I have tried a few options documented elsewhere however it seemed to break things in photonOS

Any help would be appreciated.

**Comment by ropetry** [comment]
You already did change the /etc/flannel/flanneld.conf ? 
but i´m not sure.. just started my journey with photon today..

**Comment by vinaykul** [comment]
Could you please try the config example mentioned in https://docs.docker.com/engine/userguide/networking/default_network/custom-docker0/? 

On photon 2.0, I'm able to customize the container IP range using the documented options (see below). What specific issues do you see if you have tried the above steps?


> root@p2ga [ ~ ]# mkdir -p /usr/lib/systemd/system/docker.service.d
root@p2ga [ ~ ]# echo -e "[Service]\nExecStart=\nExecStart=/usr/bin/dockerd --bip=192.168.1.1/24 --fixed-cidr=192.168.1.64/26" > /usr/lib/systemd/system/docker.service.d/10-docker.conf
root@p2ga [ ~ ]# systemctl daemon-reload && systemctl restart docker.service 
root@p2ga [ ~ ]# ip a s docker0
21: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:2c:c5:fd:49 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.1/24 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:2cff:fec5:fd49/64 scope link 
       valid_lft forever preferred_lft forever
root@p2ga [ ~ ]# docker run --rm -ti busybox
/ # ip a s eth0
26: eth0@if27: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue 
    link/ether 02:42:c0:a8:01:40 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.64/24 scope global eth0
       valid_lft forever preferred_lft forever
/ # ping -c2 time.google.com
PING time.google.com (216.239.35.0): 56 data bytes
64 bytes from 216.239.35.0: seq=0 ttl=46 time=60.290 ms
64 bytes from 216.239.35.0: seq=1 ttl=46 time=60.306 ms

--- time.google.com ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 60.290/60.298/60.306 ms
/ # exit
root@p2ga [ ~ ]#

**Comment by statseeker** [comment]
I will give the above a try and let you know the results

**Comment by ropetry** [comment]
@vinaykul 
Your way is for Docker native networking i think. Did you also try to use the "flannel" way as photon uses this network provider normally ? Hope iám not wrong with this.

i´m new to photon and try to understand what is the preferred way on photon for network setup of the containers.. the photon wiki has no info about the flannel daemon nor the "docker" way of networking.
