### ISSUE TITLE
Photon 2.0 ISO Install and tdnf behind proxy not working

### ISSUE THREAD

**Issue by ropetry** [vmware/photon#727]
Hello, i have just installed photon 2.0 in a new vm. Network ist up and running.
i am in a corporate environment where i have to use a squid proxy.. i have declared the
http and https proxy under /etc/sysconfig/proxy and i can use wget without a problem to access the internet..
i habe also declared the proxy in the tdnef.conf

root@container-dev [ /etc/tdnf ]# cat tdnf.conf
[main]
gpgcheck=1
installonly_limit=3
clean_requirements_on_remove=true
repodir=/etc/yum.repos.d
cachedir=/var/cache/tdnf
proxy="http://wwwproxy.domain.tld:3128/"

but my tdnf update prints this:

root@container-dev [ /etc/tdnf ]# tdnf update
Refreshing metadata for: 'VMware Photon Linux 2.0(x86_64) Updates'
curl#7: Couldn't connect to server
Error: Failed to synchronize cache for repo 'VMware Photon Linux 2.0(x86_64) Updates' from 'https://dl.bintray.com/vmware/photon_updates_2.0_x86_64'
Disabling Repo: 'VMware Photon Linux 2.0(x86_64) Updates'
Refreshing metadata for: 'VMware Photon Extras 2.0(x86_64)'
curl#7: Couldn't connect to server
Error: Failed to synchronize cache for repo 'VMware Photon Extras 2.0(x86_64)' from 'https://dl.bintray.com/vmware/photon_extras_2.0_x86_64'
Disabling Repo: 'VMware Photon Extras 2.0(x86_64)'
Refreshing metadata for: 'VMware Photon Linux 2.0(x86_64)'
curl#7: Couldn't connect to server
Error: Failed to synchronize cache for repo 'VMware Photon Linux 2.0(x86_64)' from 'https://dl.bintray.com/vmware/photon_release_2.0_x86_64'
Disabling Repo: 'VMware Photon Linux 2.0(x86_64)'
Nothing to do.

export shows the proxy settings are active. 
am i missing something or is proxy support broken ? The logfile of the proxy servers shows also no access.

thanks and bye
roman

**Comment by ropetry** [comment]
Hi. Back again.. Found my error.
/etc/sysconfig/proxy has a higher priority as the tdnf.conf proxy setting. 
Setting in tdnf.conf was
proxy="http://wwwproxy.dillinger.de:3128/"

i commented this line out and checked the system settings..

With error:
# Example: HTTPS_PROXY="https://proxy.provider.de:3128/"
HTTPS_PROXY="https://wwwproxy.domain.tld:3128/"
Without error
HTTPS_PROXY="http://wwwproxy.domain.tld:3128/""

later one worked..

**Comment by ppadmavilasom** [comment]
tdnf uses libcurl. curl will use systemwide proxy settings if set. (env vars http_proxy etc). did you want a different proxy for your repos? 
could you update output of "curl -v https://dl.bintray.com/vmware/photon_release_2.0_x86_64" with original settings?

**Comment by statseeker** [comment]
How does this type of info get back into the photonOS documentation as it would be useful for other users to find it there instead of going through the issues.

Can anyone update the documentation ?

Thanks

**Comment by ropetry** [comment]
@ppadmavilasom 
i was not sure if the proxy settings of the systems get used for tdnef ( no info found about that) and so i tried the system settings way and the tdnf way. sadly i have a error in the system https_proxy string and that was the cause of my problem.. i use only the system proxy settings and it worked for me, now.

 Anyway i would suggest if the admin provides a special proxy in the tdnf.conf this proxy should get used and should overwrite the system proxy. sometimes you have to use special proxys for special purpose in a corporate env 8-).
Sorry for the delay: As you have requested. 
`root@container-dev [ /var/lib/docker ]# curl -v https://dl.bintray.com/vmware/photon_release_2.0_x86_64
*   Trying xxx.xxx.x.xxx...
* TCP_NODELAY set
* Connected to wwwproxy.domain.tld (xxx.xx.x.xxx) port 3128 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to dl.bintray.com:443
> CONNECT dl.bintray.com:443 HTTP/1.1
> Host: dl.bintray.com:443
> User-Agent: curl/7.56.1
> Proxy-Connection: Keep-Alive
>
< HTTP/1.0 200 Connection established
<
* Proxy replied 200 to CONNECT request
* CONNECT phase completed!
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* CONNECT phase completed!
* CONNECT phase completed!
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* NPN, negotiated HTTP1.1
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Unknown (67):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=*.bintray.com
*  start date: Nov  9 00:00:00 2017 GMT
*  expire date: Nov  9 23:59:59 2019 GMT
*  subjectAltName: host "dl.bintray.com" matched cert's "*.bintray.com"
*  issuer: C=US; O=GeoTrust Inc.; OU=Domain Validated SSL; CN=GeoTrust DV SSL CA - G3
*  SSL certificate verify ok.
> GET /vmware/photon_release_2.0_x86_64 HTTP/1.1
> Host: dl.bintray.com
> User-Agent: curl/7.56.1
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Server: nginx
< Date: Wed, 10 Jan 2018 07:00:41 GMT
< Content-Type: text/html
< Transfer-Encoding: chunked
< Connection: keep-alive
< Location: https://dl.bintray.com/vmware/photon_release_2.0_x86_64/
<
* Connection #0 to host wwwproxy.domain.tld left intact
<html><body>Moved to <a href="http://dl.bintray.com:80/v1/content/vmware/photon_release_2.0_x86_64/">http://dl.bintray.com:80/v1/content/vmware/photon_release_2.0_x86_64/</a></body></html>root@container-dev [ /var/lib/docker ]#
`

bye and thx

**Comment by ropetry** [comment]
@statseeker . I had the same question in my mind.. Don´t know..
you have to set proxy infos on some special files, so documentation here would be create.
a docker pull is also not possible with system proxy env.. you have to set it in the docker startup service file.. as far as i have come..
8-)

**Comment by ropetry** [comment]
Just created an initial wiki page for proxy-settings.
https://github.com/vmware/photon/wiki/Photon-Proxy-Settings

**Comment by lucdekens** [comment]
A (somewhat) related question.
On a freshly installed and configured Photon 2.0, I have populated the /etc/sysconfig/proxy file with the correct entries (including the user and password for the proxy) via a GuestOperations call.

When I send the command 'tdnf update -y', again via GuestOperations.  The tdnf command can not refresh the metadata.
Now when I open a SSH session to the same VM. And when I send the 'tdnf update -y' again via GuestOperations, everything seems to work ok.
There are no proxy entries to be found in the tdnf.conf file.

What is the SSH session together with a run of tdnf changing?
Why will the tdnf command not find the repo when run via GuestOperations?

**Comment by lucdekens** [comment]
The cause of the issue seems to be the environment variables that are present in a process started through the GuestOperations.
These processes only have a minimal set of environment variables, and the proxy related ones are not in there.
This is what a call to ReadEnvironmentVariableInGuest returns:
LANG=en_US.UTF-8
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
INVOCATION_ID=bfed39d6d69b472cb4c7a4aa67a6df86
JOURNAL_STREAM=7:5191
USER=root
HOME=/root
SHELL=/bin/bash

The variables defined in /etc/sysconfig/proxy are not in there.
A restart of the VMware Tools daemon doesn't change this.

When you start a process via the StartProgramInGuest method, you can add an array of environment variables. Perhaps that's the way to go?

**Comment by VFrontDe** [comment]
There is some other caveat to keep in mind: The examples in /etc/sysconfig/proxy use environment variables in capital letters (HTTP_PROXY and HTTPS_PROXY), but tdnf looks for the variables in lower case. SO I added http_proxy and https_proxy to the file, and after that tdnf used the proxy server and worked as expected.

**Comment by lucdekens** [comment]
Thanks Andreas.

Shows that a wiki page for proxy settings in Photon would really serve a purpose.
