### ISSUE TITLE
TDNF iputils install fails

### ISSUE THREAD

**Issue by paroque28** [vmware/photon#728]
When I run 
```bash
docker run vmware/photon:1.0 tdnf install -y iputils
```

this is the output:
```bash
Refreshing metadata for: 'VMware Lightwave 1.0(x86_64)'
Refreshing metadata for: 'VMware Photon Linux 1.0(x86_64)'
Refreshing metadata for: 'VMware Photon Linux 1.0(x86_64)Updates'
Refreshing metadata for: 'VMware Photon Extras 1.0(x86_64)'

Installing:
libtasn1                        x86_64      4.12-1.ph1          166.62 k
nettle                          x86_64      3.2-2.ph1           554.86 k
autogen-libopts                 x86_64      5.18.7-2.ph1        133.24 k
gnutls                          x86_64      3.5.15-1.ph1          3.58 M
libgcrypt                       x86_64      1.7.6-3.ph1           1.12 M
iputils                         x86_64      20151218-3.ph1      251.96 k

Total installed size: 5.77 M

Downloading:
iputils                                 113634    100%
libgcrypt                               487706    100%
gnutls                                 2211499    100%
autogen-libopts                          64552    100%
nettle                                  285318    100%
libtasn1                                106649    100%
Testing transaction
Running transaction
Error(-1) : Unknown error -1601
```

**Comment by paroque28** [comment]
Also with verbose output:
```
docker run vmware/photon:1.0 tdnf install -y --rpmverbosity=verbose iputils
Refreshing metadata for: 'VMware Lightwave 1.0(x86_64)'
Refreshing metadata for: 'VMware Photon Linux 1.0(x86_64)'
Refreshing metadata for: 'VMware Photon Linux 1.0(x86_64)Updates'
Refreshing metadata for: 'VMware Photon Extras 1.0(x86_64)'

Installing:
libtasn1                        x86_64      4.12-1.ph1          166.62 k
nettle                          x86_64      3.2-2.ph1           554.86 k
autogen-libopts                 x86_64      5.18.7-2.ph1        133.24 k
gnutls                          x86_64      3.5.15-1.ph1          3.58 M
libgcrypt                       x86_64      1.7.6-3.ph1           1.12 M
iputils                         x86_64      20151218-3.ph1      251.96 k

Total installed size: 5.77 M

Downloading:
iputils                                 113634    100%
libgcrypt                               487706    100%
gnutls                                 2211499    100%
autogen-libopts                          64552    100%
nettle                                  285318    100%
error: unpacking of archive failed on file /usr/bin/ping;5a53eb1b: cpio: cap_set_file
error: iputils-20151218-3.ph1.x86_64: install failed

Testing transaction
Running transaction
Error(-1) : Unknown error -1601

```

**Comment by robertqi** [comment]
Looks like no repo on my side: tried 3 times:
docker run vmware/photon:1.0 tdnf install -y iputils
Refreshing metadata for: 'VMware Photon Linux 1.0(x86_64)Updates'
Refreshing metadata for: 'VMware Lightwave 1.0(x86_64)'
Refreshing metadata for: 'VMware Photon Linux 1.0(x86_64)'
Refreshing metadata for: 'VMware Photon Extras 1.0(x86_64)'

Installing:
libtasn1                        x86_64      4.12-1.ph1          166.62 k
nettle                          x86_64      3.2-2.ph1           554.86 k
autogen-libopts                 x86_64      5.18.7-2.ph1        133.24 k
gnutls                          x86_64      3.5.15-1.ph1          3.58 M
libgcrypt                       x86_64      1.7.6-3.ph1           1.12 M
iputils                         x86_64      20151218-3.ph1      251.96 k

Total installed size: 5.77 M

Downloading:
iputils                                 113634    100%
libgcrypt                               487706    100%
gnutls                                 2211499    100%
autogen-libopts                          64552    100%
nettle                                  285318    100%
libtasn1                                106649    100%     
Testing transaction
Running transaction

Complete!

**Comment by ppadmavilasom** [comment]
@paroque28 here are some details of an attempt to repro. could not repro. could you give us some more details of your env.

root@testm [ ~ ]# cat /etc/os-release 
NAME="VMware Photon"
VERSION="1.0"
ID=photon
VERSION_ID=1.0
PRETTY_NAME="VMware Photon/Linux"
ANSI_COLOR="1;34"
HOME_URL="https://vmware.github.io/photon/"
BUG_REPORT_URL="https://github.com/vmware/photon/issues"
root@testm [ ~ ]# docker -v
Docker version 1.11.0, build 4dc5990
root@testm [ ~ ]# docker run vmware/photon:1.0 tdnf install -y iputil
...
Downloading:
iputils                                 113634    100%
libgcrypt                               487706    100%
gnutls                                 2211499    100%
autogen-libopts                          64552    100%
nettle                                  285318    100%
libtasn1                                106649    100%
Testing transaction
Running transaction

Complete!

**Comment by paroque28** [comment]
Hi all,
This is my distribution:
```bash
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
```
I found a workaround here https://github.com/moby/moby/issues/6980.
```
DOCKEROPTS="-s devicemapper"
```
But I don't think changing the storage driver is a real solution

**Comment by vinaykul** [comment]
@paroque28: Are you using AUFS? Could you please provide the output of 'docker info' command?

**Comment by paroque28** [comment]
I think this doesn't happen on Ubuntu 16.04 but haven't confirmed
```bash
$ docker info
Containers: 18
 Running: 0
 Paused: 0
 Stopped: 18
Images: 179
Server Version: 17.11.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 246
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 992280e8e265f491f7a624ab82f3e238be086e49
runc version: 0351df1c5a66838d0c392b4ac4cf9450de844e2d
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 3.16.0-40-generic
Operating System: Ubuntu 14.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.798GiB
Name: pegasus
ID: SZP2:KBHM:VNPJ:GNMX:ESYF:AOWX:S4HO:6WGD:2Q5J:IFD5:JPKZ:CHHB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by ppadmavilasom** [comment]
"I think this doesn't happen on Ubuntu 16.04 but haven't confirmed"
>>this seems to be the case per an update in the thread you posted. could you check? would that work for you?

**Comment by paroque28** [comment]
My server is updated running Ubuntu 14.04.2 LTS. Can't go to 16.04 due to other software issues.
But again it shouldn't matter which distribution I use

**Comment by vinaykul** [comment]
@paroque28 Sorry for the delay getting to this, I just got around to trying this on 14.04. This is a docker issue with AUFS on 14.04, the same issue occurs with centos container as well. Please use the workaround devicemapper or overlay as storage driver.
