### ISSUE TITLE
Add PowerShell Core, aka PS v6, to the SPECS repo for Photon 2

### ISSUE THREAD

**Issue by lucdekens** [vmware/photon#729]
Now that PowerShell v6 will be GA (very) shortly, can we revisit #574 ?
And once PowerCLI Core is GA, the same question of course.

**Comment by ppadmavilasom** [comment]
Yes. Will update here once this work is started.

**Comment by alanrenouf** [comment]
FYI GA Version of PowerShell Core.... https://github.com/PowerShell/PowerShell/releases/tag/v6.0.0

**Comment by suezzelur** [comment]
Powershell6 and dependencies were added to the master branch. You can consume the rpms from our dev repo: http://dl.bintray.com/vmware/photon_dev_x86_64/x86_64/

**Comment by suezzelur** [comment]
It is also available in our 2.0 release.
