### ISSUE TITLE
installer: /dev/vda support

### ISSUE THREAD

**Issue by omadjoudj** [vmware/photon#733]
Photon Installer exists silently on KVM wih VirtIO, since lsblk returns 0 line [0] which causes a division by zero, below the traceback [1] when running the installer under a debugger.

Possible fix is to include VirtIO block device major (254) in ```installer/device.py``` ie: ```lsblk -d -I 8,254,259 -n --output NAME,SIZE,MODEL ```, unless it was filtered out for a reason.

[0] https://github.com/vmware/photon/blob/3533157b2510f334fee8c5e168339e6e660f22b7/installer/device.py#L17

[1]
![image](https://user-images.githubusercontent.com/143351/35363118-bc95d2f0-0168-11e8-94b3-ca5ab8777c08.png)

**Comment by jodumont** [comment]
Hi;

yes officially Photon don't plan to support paravirtualized device such as /dev/vda
so you have to force your host to give you a /dev/sda which is by using a IDE/SATA/SCSI Bus

see: https://github.com/vmware/photon/issues/600

the funny fact it's after the installation you just have to edit /etc/fstab
and replace /dev/sda by /dev/vda and everything works fine

**Comment by YustasSwamp** [comment]
Photon itself supports it. but its installer does not.
It is small fix in installer.
Waiting for contributors!))

**Comment by khayamgondal** [comment]
@YustasSwamp @omadjoudj Is it still open? I can take it.

**Comment by khayamgondal** [comment]
@YustasSwamp @omadjoudj Is it still open? I can take it.

**Comment by YustasSwamp** [comment]
Yes, please!

**Comment by khayamgondal** [comment]
cool, i ll take it. You can put my name on it.

**Comment by YustasSwamp** [comment]
done. thanks!
