### ISSUE TITLE
How to install samba related package in Photon OS

### ISSUE THREAD

**Issue by lipingxue** [vmware/photon#734]
I need to install some samba related package such as "samba" and "samba-common-tools" inside a docker container running photon OS, but it seems does not work for me. I believe the image from "vmware/photon" is Photon 1.0.
```
root@sc-rdops-vm18-dhcp-57-89:~# docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
14c8352d7dea        vmware/photon       "/bin/sh"           18 hours ago        Up 18 hours                             samba
root@sc-rdops-vm18-dhcp-57-89:~# docker exec -it 14c8352d7dea /bin/sh
sh-4.3# tdnf install
Error(1001) : Package name expected but was not provided
sh-4.3# tdnf install samba
No package samba available
Error(1011) : No matching packages

```

I was able to install those package in a docker container running alpine and ubuntu.

Can anyone help me on this?

**Comment by ppadmavilasom** [comment]
samba packages are not available in photon. quickest path for you would be to build it from sources using photon toolchain

**Comment by lipingxue** [comment]
@ppadmavilasom Thanks.  I am new to photon OS, could you share some example on how to build a package using photon toolchain. Is there any wiki/document that I use as a reference?

**Comment by ppadmavilasom** [comment]
Please see https://github.com/vmware/photon/blob/master/docs/build-photon.md#building-rpms-from-their-source-rpms

**Comment by bish0polis** [comment]
that may be https://github.com/vmware/photon/blob/master/docs/photon_admin/building-a-package-from-a-source-rpm.md now.
