### ISSUE TITLE
Module ip_vs not found

### ISSUE THREAD

**Issue by arnydo** [vmware/photon#735]
Setting up HAProxy with KeepaliveD and running into the following:

```modprobe: FATAL: Module ip_vs not found in directory /lib/modules/4.9.66-1.ph2-esx```

Linux dockerdevp-1 4.9.66-1.ph2-esx #1-photon SMP Thu Dec 7 01:41:22 UTC 2017 x86_64 Intel(R) Xeon(R) CPU E5-2643 0 @ 3.30GHz GenuineIntel GNU/Linux

**Comment by arnydo** [comment]
Not sure if this helps:

```root@dockerdevp-1 [ ~ ]# dmesg | grep ip_vs
[ 2706.758086] ip_vs: version magic '4.9.76-1.ph2-esx SMP mod_unload ' should be '4.9.66-1.ph2-esx SMP mod_unload '
[ 2714.068518] ip_vs_rr: version magic '4.9.76-1.ph2-esx SMP mod_unload ' should be '4.9.66-1.ph2-esx SMP mod_unload '```

**Comment by YustasSwamp** [comment]
Looks like you updated the kernel but didn't reboot after that.
Installed and running kernel should match
running kernel: `uname -r`
installed kernel: `rpm -q linux-esx`

**Comment by arnydo** [comment]
Oh man, that was it.

I did reboot after an update; not sure why it didn't finish.

Well, looks like it is good now.

Thank you @YustasSwamp!

**Comment by YustasSwamp** [comment]
Glad it helped!
