### ISSUE TITLE
auid/loginuid not set

### ISSUE THREAD

**Issue by UntilDoomsday** [vmware/photon#737]
Audit results show an auid of "4294967295" aka not set for all events. Using cat /proc/self/loginuid shows the same unset id.  I attempted to set the module in PAM to get this information but it did not work, so it appears other issues are not allowing it to work. Without the auid getting set I am unable to distinguish what user actually performed a task and this greatly reduces the ability to audit events.

Version: Full ISO 2.0 GA

**Comment by UntilDoomsday** [comment]
I was able to get the ID's set and represented correctly in the audit logs by adding "session optional pam_loginuid.so" to /etc/pam.d/sshd for ssh connections. The man page for pam_loginuid states:

The pam_loginuid module sets the loginuid process attribute for the process that was authenticated. This is necessary for applications to be correctly audited. This PAM module should only be used for entry point applications like: login, sshd, gdm, vsftpd, crond and atd.

**Comment by YustasSwamp** [comment]
Thanks for raising the issue and providing a solution!
We will work on that.

**Comment by YustasSwamp** [comment]
Fixed.
