### ISSUE TITLE
Peer Cert Errors with CA Certs

### ISSUE THREAD

**Issue by jhosee** [vmware/photon#738]
Hello,

I have a cloned template of PhotonOS 2.0 and am unable to access the repos when trying to install packages?  I would appreciate any guidance that can help me resolve this as I'm new to this OS.  Thank you very much:

$ cat /etc/os-release
NAME="VMware Photon OS"
VERSION="2.0"
ID=photon
VERSION_ID=2.0
PRETTY_NAME="VMware Photon OS/Linux"
ANSI_COLOR="1;34"
HOME_URL="https://vmware.github.io/photon/"
BUG_REPORT_URL="https://github.com/vmware/photon/issues"

$ tdnf install netcat
curl#60: Peer certificate cannot be authenticated with given CA certificates
Error: Failed to synchronize cache for repo 'VMware Photon Linux 2.0(x86_64) Updates' from 'https://dl.bintray.com/vmware/photon_updates_2.0_x86_64'
Disabling Repo: 'VMware Photon Linux 2.0(x86_64) Updates'
curl#60: Peer certificate cannot be authenticated with given CA certificates
Error: Failed to synchronize cache for repo 'VMware Photon Linux 2.0(x86_64)' from 'https://dl.bintray.com/vmware/photon_release_2.0_x86_64'
Disabling Repo: 'VMware Photon Linux 2.0(x86_64)'
curl#60: Peer certificate cannot be authenticated with given CA certificates
Error: Failed to synchronize cache for repo 'VMware Photon Extras 2.0(x86_64)' from 'https://dl.bintray.com/vmware/photon_extras_2.0_x86_64'
Disabling Repo: 'VMware Photon Extras 2.0(x86_64)'
No package netcat available
Error(1011) : No matching packages

**Comment by YustasSwamp** [comment]
Is date correct on your Photon VM instance?

**Comment by sharathjg** [comment]
closing on no response. please reopen if you still see this.
