### ISSUE TITLE
Fusion filesystem errors Photon 2

### ISSUE THREAD

**Issue by scriptjs** [vmware/photon#743]
When installing Photon 2 GA with 'hypervisor optimized' with VMWare Fusion 8.5.10, it boots with the following messages:
```
ext4-fs sda2 could not mount as ext 3 due to feature incompatibilities
ext4-fs sda2 could not mount as ext 2 due to feature incompatibilities
```

**Comment by suezzelur** [comment]
This is just a warning message

**Comment by scriptjs** [comment]
@suezzelur Photon is a professional product that is meant to work with VMware's paid products. I have attached the screen shot of the errors. These are not identified as warnings. I expect some action to be taken on this issue to identify and correct the incompatibility so I may have confidence in vmware products I am paying to use.

![screen shot 2018-03-06 at 9 46 41 am](https://user-images.githubusercontent.com/13335501/37035983-b0d66f3e-2124-11e8-9cdc-03afe6d8ba54.png)
