### ISSUE TITLE
Photon 2 qcow2 does not boot

### ISSUE THREAD

**Issue by scriptjs** [vmware/photon#744]
I have been creating vmdk images and converting them to qcow2 using qemu-img after configuring what I need in  Fusion from the Photon ISO using the minimal install. This process has been successful for creating images for OpenStack for Photon 1. 

In Photon 2, there are now two options for installation for 'hypervisor optimized' and 'generic' from the ISO.

If I install using 'hypervisor optimized', it boots in Fusion with errors as reported in

https://github.com/vmware/photon/issues/743

There is no point going further to a qcow2 conversion on this basis.

If I build from the 'generic' selection, the resulting qcow2 image does not boot for the following reason:

```
A start job is running for dev_disk.xxxx.device
```
First, what are the differences between 'hypervisor optimized' and 'generic'? Second this seems to 
point to an issue with kernel drivers not being loaded for KVM or something else, perhaps related to fstab. I see that fstab has changed between the two distributions. Someone care to comment on the differences in mount options. Either way, I am not finding it possible to create a viable image for OpenStack. 

It would help to elaborate about changes between Photon 1 and 2 that could have lead to this issue. Help determining a solution would be appreciated.

**Comment by suezzelur** [comment]
Hypervisor optimized kernel is optimized for booting in a VMware hypervisor. It will not work on KVM. The generic kernel not booting looks like due to missing device drivers in initrd.

**Comment by scriptjs** [comment]
Hello, yes thanks for this. VMWare Fusion is a VMWare hypervisor and it does not work with this product. I have the issue above with booting in Fusion as indicated.

I am able to create an image with Fusion using the generic setting but the conversion needed for OpenStack results in an unbootable image. The generic kernel is what I am expecting to be able to be converted to work on OpenStack or other KVM hypervisor. 

Yes, I agree on the drivers and have said as much above. I am anticipating your help since I cannot perform a routine conversion that is essential to using the OS. I have have run a couple of basic checks. The iscsi drivers appear to be there for virtio using
```
$ find find /lib/modules/ -name *virtio*
```
I also attempted to convert the raw image from untarred ami package with same outcome. So this is a problem for the GA in general.

**Comment by suezzelur** [comment]
You can try and create your own initrd after modifying /var/lib/initramfs/kernel/<file> to add drivers required (virtio_blk, virtio_pci could be missing) and generate a new initrd with mkinitrd command

**Comment by scriptjs** [comment]
Thanks. I will look into this. Btw, I noticed initramfs does not exist at this location in Photon 1. Where can I compare what was previously loaded from Photon 1?

**Comment by scriptjs** [comment]
@suezzelur Any answer to my question?

**Comment by jodumont** [comment]
I succeed running Photon 2 and 3 under KVM based on the ISO image.

### During the installation

I simply choose a **FullVirtualized** Bus such as IDE/SATA/SCSI which give you a `/dev/sda` disk

then if you are picky like me and want a **Paravirtualized** Bus such as VirtIO which give you a '/dev/vda' disk you simply have to 

1. reboot with a livecd
2. mount Photon partition 
3. replace /dev/sda by /dev/vda in /etc/fstab
4. reboot into Photon

**Comment by YustasSwamp** [comment]
Answer is - limited resources & not aligned with our roadmap. Looking for contributors:
https://github.com/vmware/photon/issues/733

PS: Photon officially supports para-virtualization for vSphere, AWS, GCE(KVM)

**Comment by YustasSwamp** [comment]
Feature is supported as for now.
