### ISSUE TITLE
this docker image can not work on VMware Photon OS 2.0,but can work on  Photon OS 1.0

### ISSUE THREAD

**Issue by allenyang0812** [vmware/photon#745]
I run this docker image (vmware/fabric-explorer:1.0) on photon OS, can work on Photon OS 1.0, but can not work on Photon OS 2.0.

pthoton 1.0: 
pthoton os 1.0  pthoton-release 
VMware Photon Linux 1.0
PHOTON_BUILD_NUMBER=13c08b6

docker-release
Docker version 1.12.1, build 23cf638

---------------------------------------------------------
pthoton 2.0:
pthoton os 1.0  pthoton-release
VMware Photon OS 2.0
PHOTON_BUILD_NUMBER=8553d58

dokcer-release
Docker version 17.06.0-ce, build 02c1d87

when I run fabric-explorer docker image with the follow command
#docker run -it vmware/fabric-explorer:1.0 bash

the pthoton 1.0 can work, the  pthoton 2.0 can not work, exitcode is 139, can you help me look for the reason lead to the problem?

Thanks very much in advance!

**Comment by suezzelur** [comment]
Can you try the 2.0 GA build? It looks like you are on RC. We were unable to reproduce this on 2.0 GA. Also, please post uname -r output

**Comment by allenyang0812** [comment]
@suezzelur output on photon os 2.0
#uname -r
 4.9.43-1.ph2-esx

**Comment by allenyang0812** [comment]
@suezzelur I have tried, this image can work on 2.0 GA. thanks very much !
