### ISSUE TITLE
no audit support in kernel

### ISSUE THREAD

**Issue by joshuaalm** [vmware/photon#746]
Trying to STIG a Photon VM, I get this error when trying to start auditd:

Error - audit support not in kernel

This occurs despite adding 'audit=1' to kernel options in /boot/grub/grub.cfg

**Comment by YustasSwamp** [comment]
Audit was disabled in `linux-esx` and we just recently enabled it.
Generic kernel (`linux` package) does support it.

Try to update linux-esx: `tdnf update linux-esx` (and then reboot)
If still on audit support - install generic kernel: `tdnf install linux` (and then reboot)

Please reply if it helps.
btw, is it 1.0 or 2.0 ?

**Comment by srivatsabhat** [comment]
Hi @joshuaalm,

On Photon OS 1.0, the `linux` package has audit support, but `linux-esx` doesn't.
On Photon OS 2.0, both `linux` and `linux-esx` packages have audit support.

**Comment by joshuaalm** [comment]
OK, and I understand that auditd.service can't be restarted with systemctl, but the service command isn't present on Photon, so is there an accepted workaround?  Thank you both for contributing an explanation!

**Comment by YustasSwamp** [comment]
Photon OS does not have `service` tool like Ubuntu, use standard systemd way instead.
`systemctl [start|stop|status] auditd`

**Comment by joshuaalm** [comment]
# systemctl stop auditd
Failed to stop auditd.service: Operation refused, unit auditd.service may be requested by dependency only (it is configured to refuse manual start/stop).
See system logs and 'systemctl status auditd.service' for details.
# systemctl restart auditd
Failed to restart auditd.service: Operation refused, unit auditd.service may be requested by dependency only (it is configured to refuse manual start/stop).
See system logs and 'systemctl status auditd.service' for details.

**Comment by srivatsabhat** [comment]
If you simply want to reload auditd, you can run:
`systemctl reload auditd`

As for restarting auditd, if you look at /usr/lib/systemd/system/auditd.service, there is this particular line:
`RefuseManualStop=yes`
That's what prevents you from restarting auditd via systemctl.

So, if you really want to restart auditd for some reason and _you know what you are doing_, you can replace that line with:
`RefuseManualStop=no`
and then run:
```
systemctl daemon-reload
systemctl restart auditd
```
(and remember to set it back to `RefuseManualStop=yes`).

**Comment by jasonkyzer** [comment]
@joshuaalm Did you ever get your photon image to be STIG compliant?
