### ISSUE TITLE
Unable to install util-linux-devel in photon 2  docker container

### ISSUE THREAD

**Issue by narayanasamyr** [vmware/photon#747]
I am trying to install util-linux-devel using tdnf but it gave me below error

root [ / ]# tdnf install util-linux-devel
Found 1 problem(s) while resolving
1. package util-linux-devel-2.29.2-5.ph2.x86_64 requires util-linux = 2.29.2-5.ph2, but none of the providers can be installed
Error(1301) : Hawkey general runtime error

Repo List:
tdnf repolist
repo id             repo name                               status    
photon              VMware Photon Linux 2.0(x86_64)         enabled   
photon-extras       VMware Photon Extras 2.0(x86_64)        enabled   
photon-updates      VMware Photon Linux 2.0(x86_64) Updates enabled

**Comment by ppadmavilasom** [comment]
this is an issue in tdnf which is recently resolved (rpms might not be updated yet) - please do tdnf install util-linux util-linux-devel

**Comment by narayanasamyr** [comment]
Error again

root [ / ]# tdnf install util-linux util-linux-devel 
Found 1 problem(s) while resolving
1. package util-linux-2.29.2-5.ph2.x86_64 conflicts with toybox provided by toybox-0.7.3-6.ph2.x86_64
Error(1301) : Hawkey general runtime error

**Comment by ppadmavilasom** [comment]
toybox provides core tools for photon2  docker to keep the size of the image down. this conflict is expected.
please do 
tdnf erase toybox
then do installs as you need.

**Comment by suezzelur** [comment]
Are you still facing issues with the install?
