### ISSUE TITLE
Photon - ManageEngine Enquiry - Does photon support standard linux based commands

### ISSUE THREAD

**Issue by Frustrated12345** [vmware/photon#748]
I am trying to get my VCentre Server to appear in ManageEngine OpManager. Their support teams have asked if photon supports standard Linux commands. I suspect it does but VMware support were unable to help and sent me to this github link.
Can anyone confirm if there are any unusual quirks to photon that would affect OpManager?

**Comment by suezzelur** [comment]
Your question is very vague, what exact linux commands are not working for you?

**Comment by Frustrated12345** [comment]
Trying to get op manager to return cpu and memory values.
My question is vague as I am merely asking the question manage engine support asked me. Sorry. I will ask for more clarity.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by YustasSwamp** [comment]
list of our packages are here: https://github.com/vmware/photon/tree/master/SPECS
Please reopen the issue once you have a request for specific package to add.
Close for now.
