### ISSUE TITLE
tdnf install wget -y issue

### ISSUE THREAD

**Issue by KalpeshKharade** [vmware/photon#749]
Hello Team,

I have installed Photon OS for Webhook Shims configuration. The configuration step has a command 'tdnf install wget -y'. But that command is showing an error of 'Couldn't resolve the hostname'. We checked the file '/etc/resolv.conf' and found the name servers 8.8.8.8, 8.8.4.4 are available. From the server, we are not able to curl google.com as well.

Please suggest for any resolution.

**Comment by ppadmavilasom** [comment]
its possible that your org blocks dns servers like 8.8.x.  please check with your admins and adjust dns servers for your local instance.

**Comment by suezzelur** [comment]
This is a DNS issue at user side
