### ISSUE TITLE
Issues with compling photon through make file in ubuntu os.

### ISSUE THREAD

**Issue by anirudhvyas21** [vmware/photon#75]
I wanted to compile photon on my 64 bit ubuntu os , when i executed the make command , there were some missing packages which were to be imported after that when i again executed make then compiling was unsuccessful showing this:-

anirudh@ubuntu:~/Downloads/photon-master$ make
Pulling sources from bintary...
Downloading sha1-all...
Traceback (most recent call last):
  File "/home/anirudh/Downloads/photon-master/support/pullsources/pullsources.py", line 101, in <module>
    p.pull(args[0])
  File "/home/anirudh/Downloads/photon-master/support/pullsources/pullsources.py", line 78, in pull
    package_file_path = self.downloadFile(sources_dir, 'sha1-all')
  File "/home/anirudh/Downloads/photon-master/support/pullsources/pullsources.py", line 61, in downloadFile
    with open(file_path, 'wb') as handle:
IOError: [Errno 2] No such file or directory: '/home/anirudh/Downloads/photon-master/stage/SOURCES/sha1-all'
make: *** [sources] Error 1

please provide a solution as soon as possible , so that i can compile successfully.

**Comment by toliaqat** [comment]
Have you tried 'sudo make'?

**Comment by anirudhvyas21** [comment]
yes sir still the issue exists

**Comment by toliaqat** [comment]
I haven't seen this error before. The script is trying to create ./stage/SOURCES/sha1-all but could not for some reason. Make sure you have stage/SOURCES folders present and if not then create them manually which script is suppose to be doing itself. After creating these two folders try again. Also make sure you are not missing anything in https://github.com/vmware/photon/blob/master/docs/build-photon.md

**Comment by anirudhvyas21** [comment]
Thanks a lot! toliaqat your advice helped photon can only be compiled from the home directory , i was trying it from downloads

**Comment by toliaqat** [comment]
Thanks for your update.
