### ISSUE TITLE
Module usbserial not found in /lib/modules/4.9.80-1.ph2-esx

### ISSUE THREAD

**Issue by docbobo** [vmware/photon#750]
It seems that the usbserial module is not available in Photon 2.0, at least not with the esx kernels:

```
root@photon-machine [ ~ ]# uname -a
Linux photon-machine 4.9.80-1.ph2-esx #1-photon SMP Wed Feb 14 14:45:42 UTC 2018 x86_64 Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz GenuineIntel GNU/Linux
```

```
root@photon-machine [ ~ ]# modprobe usbserial
modprobe: FATAL: Module usbserial not found in directory /lib/modules/4.9.80-1.ph2-esx
```

It can be found in the modules folder of ```4.9.53-3.ph2``` though.

**Comment by YustasSwamp** [comment]
@docbobo, for what use case do you need usbserial in VM? Will generic kernel ("linux" package) work for you?
And what usb2serial converted device/chip do you use?

Thanks.

**Comment by YustasSwamp** [comment]
At least generic kernel ('linux' package) has support for usbserial.
Close for now.
Please re-open once you have more input. Thanks.

**Comment by ronj** [comment]
I would also like to have the usbserial kernel module present.

My use-case is running a home-automation VM, needing access to a ZWave dongle and an ftdi-based cable that reads my smart meter.

**Comment by docbobo** [comment]
+1 - that's the exact same thing that I was trying to do. Though I did not yet have time to test this with the generic kernel, I'd prefer to use the ESXi version as I am running this on... ESXi ;)

**Comment by docbobo** [comment]
@YustasSwamp, can you please re-open this issue?

**Comment by ronj** [comment]
Thanks! I have compiled Photon OS with your changes and I can confirm this works. My z-wave dongle needs another patch to enable cdc-acm. I will test and come back with a pull request.

**Comment by srivatsabhat** [comment]
@ronj Thanks a lot for testing and for the pull request! We are currently running your patch through our build/test pipeline, and we will get it merged soon :)

**Comment by srivatsabhat** [comment]
Merged the pull request (with a few minor changes - enabled USB_ACM in linux as well): https://github.com/vmware/photon/commit/e73d25de580e9989ba33481d4187e6a6a27dcf6f

Thank you!

**Comment by YustasSwamp** [comment]
Can we also add it to 3.0, please?
