### ISSUE TITLE
Kernel patching without reboot and maintenance

### ISSUE THREAD

**Issue by scriptjs** [vmware/photon#751]
I have previously asked about a systematic approach to maintaining Photon with a container workload which is a requirement for security and uptime. This was unfortunately closed without consideration to improving documentation or tooling that might improve adoption of Photon and provide better insight as to whether Photon should be considered anything but an experiment at this point. 

https://github.com/vmware/photon/issues/740

A few critical pieces are missing.

1. An ability to receive package updates to Photon on an automated basis. In considering this, is Photon 2 at a state beyond experimental use where one could have assurance that package updates will not break currently installed packages and configuration?
2. A kernel patching solution that enables Photon to receive updates to its kernel without rebooting the system. Will VMware create or launch a solution or will there be work with an existing solution such as kpatch for kernel maintenance?
3. A focus in the administration guide for recommended for maintaining Photon at scale if this operating system is to be taken seriously.
4. Efforts to involve Photon in SCAP or STIG. Will this occur for security and hardening assurance?

I realize some efforts have gone into a API for an agent to interact with Photon for package management, users, and firewalls. Perhaps this needs some connection to the above to clarify the direction of this project.

**Comment by YustasSwamp** [comment]
Rebootless upgrade is not in the Photon OS roadmap.
