### ISSUE TITLE
TDNF or Yum updates failing Error(1622) : Invalid argument

### ISSUE THREAD

**Issue by captainfresh** [vmware/photon#753]
Unable to update Photon OS 2.0 with tdnf update or yum update. I have tried tdnf clean all and a reboot but the errors persist.
The error occurs randomly on different package downloads.
Is there an alternate repo site I could try or is there an issue with the repo hosting??

Sample:
Total installed size: 760.93M 797890077
Is this ok [y/N]:y

Downloading:
file-libs                               316941    100%
keyutils                                 67063    100%
Error: 502 when downloading https://dl.bintray.com/vmware/photon_updates_2.0_x86_64/x86_64/serf-1.3.9-1.ph2.x86_64.rpm
. Please check repo url.
Error(1622) : Invalid argument

**Comment by suezzelur** [comment]
Are you still facing network issues? We cannot repro this from our end.

**Comment by captainfresh** [comment]
I finally got all the updates after about 15 tries. Going to the URL via a browser was also really slow to load up. I also tried a few different sites to determine if my connection was the culprit but they all seemed to be fine. Anyway, all good now :)

**Comment by suezzelur** [comment]
The repo hosting site has been having issues today with its CDN: http://status.bintray.com/
