### ISSUE TITLE
Port forwarding not working because socat requires openssl 1.1

### ISSUE THREAD

**Issue by alexeyzimarev** [vmware/photon#754]
There is an issue with k8s port forwarding, which uses `socat`. There is a similar issue on CoreOS but they provide `kubelet-wrapper` to have all dependencies properly installed.

On Photon, I get this:

> E0327 14:17:09.006899    9069 portforward.go:331] an error occurred forwarding 46871 -> 44134: error forwarding port 44134 to pod 98a85a9018c6e66106ff951c6552a421564764bcd1ac966f0ffeae9a47eb4b23, uid : exit status 127: /usr/bin/socat: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
Error: transport is closing

**Comment by suezzelur** [comment]
I am able to do kubectl port-forward without the errors mentioned above. What version of Photon OS are you running this in? What does ldd /usr/bin/socat list?

**Comment by alexeyzimarev** [comment]
I use Photon OS 1.0. socat is not found on host machines.

**Comment by alexeyzimarev** [comment]
Photon 2.0 _or_ cache update caused socat to appear in the package list, so this seems to be resolved.

**Comment by alexeyzimarev** [comment]
This is what I do to test it:

```
~/Downloads  kubectl run --image=gcr.io/kuar-demo/kuard-amd64:1 kuard
deployment "kuard" created
~/Downloads  kubectl get pods -o wide
NAME                     READY     STATUS    RESTARTS   AGE       IP           NODE
kuard-59f4bf4795-bxj76   1/1       Running   0          6s        172.1.35.3   lar-dev-k8s-node1
~/Downloads  kubectl port-forward kuard-59f4bf4795-bxj76 8080:8080
Forwarding from 127.0.0.1:8080 -> 8080
Handling connection for 8080
Handling connection for 8080
E0328 10:57:22.051586    2634 portforward.go:331] an error occurred forwarding 8080 -> 8080: error forwarding port 8080 to pod eef63dd1ce92e04e67489051b3b81905f99c99d973edc82a5b6a35aa2121b90f, uid : exit status 127: /usr/bin/socat: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
E0328 10:57:22.053173    2634 portforward.go:331] an error occurred forwarding 8080 -> 8080: error forwarding port 8080 to pod eef63dd1ce92e04e67489051b3b81905f99c99d973edc82a5b6a35aa2121b90f, uid : exit status 127: /usr/bin/socat: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
Handling connection for 8080
E0328 10:57:22.057580    2634 portforward.go:331] an error occurred forwarding 8080 -> 8080: error forwarding port 8080 to pod eef63dd1ce92e04e67489051b3b81905f99c99d973edc82a5b6a35aa2121b90f, uid : exit status 127: /usr/bin/socat: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
^C%                                                    
```

**Comment by suezzelur** [comment]
Did you do tdnf install socat? Where is your /usr/bin/socat from?

**Comment by alexeyzimarev** [comment]
Kubelet container has its own socat inside and it requires OpenSsl 1.1 shared library. 

I can start socat on the host OS but I cannot start socat from inside the kubelet container.

**Comment by jnovack** [comment]
@alexeyzimarev I saw you upgraded to photon 2.0 in the meantime.  Is this still an issue on 2.0?

**Comment by alexeyzimarev** [comment]
Photon 2.0 has OpelSSL 1.0.2 as well so the issue remained. We had to manually update OpenSSL.

**Comment by tickers** [comment]
alexeyzimarev --- How did you update OpenSSL? Stuck in the same boat here...

**Comment by alexeyzimarev** [comment]
I have to ask, it was not me. Can ask on Monday only.

**Comment by tickers** [comment]
alexeyzimarev - Thank You! Photon is kicking my butt on this one and I tried several umm creative steps that all failed. 
The error
helm install . --name my-todo-app --set serviceType=LoadBalancer
E0406 19:51:48.167121   17441 portforward.go:331] an error occurred forwarding 40255 -> 44134: error forwarding port 44134 to pod afba2ce228514365266fb3a6b527b5192a8405c304c5db1c9bc31c5e87018d2f, uid : exit status 127: /usr/bin/socat: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
Error: transport is closing
