### ISSUE TITLE
No package photon-upgrade available

### ISSUE THREAD

**Issue by alexeyzimarev** [vmware/photon#755]
The wiki article [Upgrading to Photon OS 2.0](https://github.com/vmware/photon/wiki/Upgrading-to-Photon-OS-2.0) says that I need to install the upgrade package.

But when I do this, I get "package not found" error.

```
root@k8s-master [ ~ ]# tdnf install photon-upgrade
No package photon-upgrade available
Error(1011) : No matching packages
```

**Comment by suezzelur** [comment]
Can you do a `tdnf repolist` and post the output? Maybe your cache needs an update - you can either do `tdnf makecache` followed by `tdnf install photon-upgrade` or do `tdnf install  photon-upgrade --refresh`

**Comment by alexeyzimarev** [comment]
Thanks, `tdnf makecache` helped.
