### ISSUE TITLE
Upgrade PostgreSQL packages to v10

### ISSUE THREAD

**Issue by michaelpq** [vmware/photon#759]
As of now, Photon packages are using PostgreSQL 9.6.7. They are lagging one minor release behind to begin with, as community has released 9.6.8.

A new major version has been released as well, v10 which is already at 10.3 (the new version number schema is made of two digits). So let's do something like commit 5b2a35ab which has done the upgrade from 9.5 to 9.6, ut this time up to v10 to keep up to date.

**Comment by jnovack** [comment]
I wish it was that simple...

*"Version 10 contains a number of changes that may affect compatibility with previous releases."*
-- https://www.postgresql.org/docs/10/static/release-10.html

**Comment by michaelpq** [comment]
We cannot stay on past version's as well ;) Please note that each major version brings in its set of small breakages which impact existing applications.

I have gone through the process for vCenter, and the most painful point has been the handling of meta-data sequences because of some... Design issues with some of the code involved. Except that this is just changing one SQL query and all things are hard failures which are easy to detect. Not upgrading those packages is of course your call, but in the past the switch from 9.5 to 9.6 has been done without caring about any applications, and it is impossible to predict if things are going to be broken without doing the switch.

At the same time, we could not be seeing problems if Photon took care of the problem of storing each major version of PostgreSQL into a different path like other Linux distributions do, which can also take care of problems with pg_upgrade where the set of binaries of *old* and *new* versions are needed.

**Comment by YustasSwamp** [comment]
it is 11.5 now
