### ISSUE TITLE
Remove deprecated "vSphere Storage for Docker" package from repository

### ISSUE THREAD

**Issue by zul-jin** [vmware/photon#760]
VMware deprecated the RPM version of the vSphere Storage for Docker plugin [back in March 2017](https://github.com/vmware/vsphere-storage-for-docker/releases/tag/0.13), but a very old version of it can still be installed from the Photon repository. I think the package should be removed since it's no longer being maintained.

![putty_2018-04-03_20-19-14](https://user-images.githubusercontent.com/34521995/38267635-609f4374-377c-11e8-8a6c-b64f017556a0.png)

**Comment by jnovack** [comment]
I think that just means general DEB/RPMs will not be generated by the VDVS maintainers, but that does not stop any repository owners from generating their own. 

Semantically, the package isn't deprecated, the RPM version is.  The `master` branch is up to v0.21 and had a last commit of 9 days ago (as of this post).

It is my opinion that the photon repository be updated by the photon repository maintainers with the latest `docker-volume-storage` version, not removed from the repository.

**Comment by YustasSwamp** [comment]
Old RPMs are in repository and we will not remove them.
Since it is no longer being maintained - consumers won't see any updates for this package.

Thanks.
