### ISSUE TITLE
Package Request: mlocate (for VM backup with Veeam)

### ISSUE THREAD

**Issue by Foxi352** [vmware/photon#763]
We run 2 Photon OS 2.0 VM's on our vSphere 6.5 Cluster. We backup using the widely used Veeam Backup & Replication 9.5 Software.

To function correctly it needs the mlocate package installed in linux VM's which is missing in your repos. Would it be possible to include it ?

Thank you.

**Comment by jnovack** [comment]
Suggestion: Change title to "Package Request: mlocate"

**Comment by jnovack** [comment]
> *The 'm' stands for "merging": updatedb reuses the existing database to avoid rereading most of the file system, which makes updatedb faster and does not trash the system caches as much as traditional locate implementations.*

For more information, the makers of the software might be better to answer why `mlocate`.  https://www.veeam.com/support.html

**Comment by Foxi352** [comment]
The problem is Veeam Backup Solution wants mlocate installed. Personally i have no clue why. All i know is that for file indexing to work on linux systems that package needs to be there. And i doubt that i can get Veeam to change their system :-) And i think we agree that this is a widely used backup solution for vSphere.

**Comment by YustasSwamp** [comment]
added

**Comment by t3easy** [comment]
> My two cents:
> 
> I have installed Photon OS 2.0 minimal a few days back and found tdnf installed mlocate without any problems.
> BUT, the updatedb.mlocate failed due to uncreated mlocate group and also there is no mlocate cron created. I have manually solved this issues but VEEAM continues to complain about mlocate not found.
> 
> I have check the mlocate paths vs other working linux systems and they are identical.

I have the same problem right now.
mlocate is installed but veeam throws an error that it's not.
Any hint what to do @neuromancer-es?

**Comment by elekgeek** [comment]
Still having the same warning for vCenter 7.0.2.00200 appliance indexing and Veeam 11.0.0.837........

Here is what I did, may be it's useful for others:

```bash
tdnf install mlocate
groupadd mlocate
chgrp mlocate /var/lib/mlocate
chmod g=rx,o= /var/lib/mlocate
touch /var/lib/mlocate/mlocate.db
chgrp mlocate /var/lib/mlocate/mlocate.db
updatedb.mlocate
```

To keep mlocate.db up-to-date:
```bash
# run the following
tee /etc/cron.daily/updatedb-mlocate-run <<EOF
#!/bin/bash
updatedb.mlocate
EOF
```

However, still Veeam reports ```Failed to index guest file system. mlocate was not found.``` But mlocate really works!!!

**Comment by t3easy** [comment]
@elekgeek See: https://github.com/vmware/photon/issues/1075

**Comment by elekgeek** [comment]
Thank you @t3easy for pointing me out to this thread, I spent the last night trying to figure out what's going on, I opened a case with Veeam, no answers yet, but I read this thread carefully, and it seems that Veeam should be using ```updatedb.mlocate -V``` rather than ```locate -V```.

I just moved ```/usr/bin/updatedb to /etc/alternatives``` and ```ln -s /usr/bin/updatedb.mlocate /usr/bin/updatedb``` so indexing works now :)

I will report this to Ceeam people once they reply to my ticket.

Thanks!
