### ISSUE TITLE
Kubernetes air gap install process

### ISSUE THREAD

**Issue by bgrissin** [vmware/photon#765]
Is there an offline kubernetes install alternative for Photon 2.0 available.  I have been using the git repo reference provided below, which offers a tdnf installation method, but the current lab I have only has access to an AMI on AWS that has iptables and docker 17.09 CE installed

https://github.com/vmware/photon/blob/master/docs/kubernetes.md

The 2.0 AMI had docker and iptables already installed, however there isn’t a preinstalled Kubernetes.

I also don’t have a repo inside of the AWS VPC that allows me a path to the kubernetes package install using TDNF
So I was wondering if there is a download or out of band way to copy in the k8s installation for managers and nodes

**Comment by sharathjg** [comment]
you essentially have to create your own ami after installing the kubernetes RPMS. The alternative approach is to cache the necessary RPMS in an S3 bucket and install it from there.
you can get them from : http://dl.bintray.com/vmware/photon_updates_2.0_x86_64/x86_64/
