### ISSUE TITLE
How to only build Photon OS kernel?

### ISSUE THREAD

**Issue by ljian236** [vmware/photon#767]
I have tried to build the whole Photon OS but failed because of different causes. I want to know it is possible to only compile OS kernel? For example patch kernel codes by myself. Thanks.

**Comment by YustasSwamp** [comment]
`make <package name>` will build package's requirements and package itself.

as a package name option you can use `linux` or `linux-esx` - depends on what flavor of kernel you need.

Thanks.

**Comment by sharathjg** [comment]
however, can you let us know your build environment that is causing the whole OS build failure and start another issue?
