### ISSUE TITLE
Deploying photonOS ova with virtual hardware v13 on vSphere fails

### ISSUE THREAD

**Issue by auchri** [vmware/photon#772]
Hi,

I'm trying to deploy the provided `OVA with virtual hardware v13 (ESX 6.5 and above)` on our vSphere environment.

Unfortunately, the deployment fails with an error message like

>The specified object /photon-ova/nvram was not found.

**Comment by stickystyle** [comment]
I'm seeing the same behaviour. Deploying the v11 version of the OVA works fine.

VMware ESXi, 6.5.0, 7967591
vCenter, 6.5.0, 7515524

**Comment by suezzelur** [comment]
There is an existing issue with VC 6.5 UI which prevents the EFI ova to load properly. Manual deployment to ESX or ovftool deployment to VC should still work for v13 ova.
