### ISSUE TITLE
Mount iSCSI drive

### ISSUE THREAD

**Issue by auchri** [vmware/photon#773]
Hi,

I want to mount an iSCSI drive to PhotonOS.
How can I achieve that?

**Comment by suezzelur** [comment]
We currently do not have the tools required to do this. We will look into adding them.

**Comment by gflex** [comment]
11 months later and 3.0 GA, still no iSCSI utils.

**Comment by marukka** [comment]
+1

**Comment by cprivite** [comment]
+1 well over a year later.

**Comment by YustasSwamp** [comment]
Added open-iscsi package to 3.0 branch. https://github.com/vmware/photon/tree/3.0/SPECS/open-iscsi
Will be available in rpm repository in 1-2 days.

**Comment by ElanHasson** [comment]
Thanks!
