### ISSUE TITLE
photon2 no longer boots after tdnf update

### ISSUE THREAD

**Issue by francisreader** [vmware/photon#774]
esxi6.5, VM created from minimal install template created from photon-2.0-304b817.iso 

Install works fine.
Login as root, and 
`tdnf update`
`reboot`

VM no longer boots

**Comment by srivatsabhat** [comment]
I just tried the same steps with both Generic and Hypervisor-optimized kernels, but could not reproduce the problem. Are you able to reproduce this issue reliably?

Do you see any error messages on the console when you try the reboot? If yes, can you share a screenshot?

It would also be great to know the exact versions of various rpms that the package manager is updating to. So, can you send us the output of `tdnf update` after a fresh install, before your reboot?

**Comment by francisreader** [comment]
Screengrab attached, rebooting after updates. Is there a grub entry to get more verbose? Or is there a way to edit photon-params ?
![screenshot from 2018-05-08 08-27-39](https://user-images.githubusercontent.com/14354078/39766904-4d60341a-529a-11e8-8584-2a0ad29a3743.png)


Updates after running "tdnf update"
```

Installing:
file-libs                x86_64       5.30-3.ph2       photon-updates   4.80M 5031416

Total installed size:   4.80M 5031416

Upgrading:
util-linux-libs          x86_64       2.32-1.ph2       photon-updates 715.26k 732424
util-linux               x86_64       2.32-1.ph2       photon-updates   4.86M 5101168
tdnf                     x86_64       1.2.3-2.ph2      photon-updates 194.86k 199539
systemd                  x86_64       233-13.ph2       photon-updates  18.16M 19043477
sqlite-libs              x86_64       3.22.0-2.ph2     photon-updates 876.16k 897184
shadow-tools             x86_64       4.2.1-15.ph2     photon-updates 140.34k 143704
shadow                   x86_64       4.2.1-15.ph2     photon-updates   1.56M 1632662
rpm-libs                 x86_64       4.13.0.1-7.ph2   photon-updates 810.16k 829607
rpm                      x86_64       4.13.0.1-7.ph2   photon-updates 280.09k 286816
python3-setuptools       noarch       3.6.5-1.ph2      photon-updates   1.59M 1664282
python3-xml              x86_64       3.6.5-1.ph2      photon-updates 331.30k 339250
python3-libs             x86_64       3.6.5-1.ph2      photon-updates  23.87M 25034304
python3                  x86_64       3.6.5-1.ph2      photon-updates   2.78M 2917183
pcre-libs                x86_64       8.41-1.ph2       photon-updates 271.53k 278048
openssl                  x86_64       1.0.2o-1.ph2     photon-updates   4.41M 4627117
openssh-server           x86_64       7.5p1-10.ph2     photon-updates 901.73k 923372
openssh-clients          x86_64       7.5p1-10.ph2     photon-updates   3.78M 3962221
openssh                  x86_64       7.5p1-10.ph2     photon-updates   0.00b 0
xml-security-c           x86_64       1.7.3-4.ph2      photon-updates   1.38M 1443456
xerces-c                 x86_64       3.2.1-1.ph2      photon-updates   4.46M 4678200
open-vm-tools            x86_64       10.2.0-3.ph2     photon-updates   2.14M 2241505
ncurses-terminfo         x86_64       6.0-13.ph2       photon-updates   1.87M 1956112
ncurses-libs             x86_64       6.0-13.ph2       photon-updates 574.50k 588285
ncurses                  x86_64       6.0-13.ph2       photon-updates 316.05k 323633
linux-esx                x86_64       4.9.98-1.ph2     photon-updates   9.70M 10175143
krb5                     x86_64       1.16-1.ph2       photon-updates   3.07M 3218433
hawkey                   x86_64       2017.1-6.ph2     photon-updates 146.12k 149624
glibc                    x86_64       2.26-10.ph2      photon-updates   7.47M 7830573
file                     x86_64       5.30-3.ph2       photon-updates  38.03k 38943
curl-libs                x86_64       7.59.0-1.ph2     photon-updates 524.53k 537120
curl                     x86_64       7.59.0-1.ph2     photon-updates 266.53k 272924
cloud-init               noarch       0.7.9-14.ph2     photon-updates   2.64M 2766175
bash                     x86_64       4.4.12-3.ph2     photon-updates   3.02M 3161863
```

**Comment by francisreader** [comment]
Oh, I only installed the hypervisor optimised kernel when creating the VM. 
I'm happy to reset my password to something, and upload the template VM?

**Comment by francisreader** [comment]
I edditted photon.cfg before the reboot and have additional info in the screengrab as it froze. 
![screenshot from 2018-05-08 08-48-49](https://user-images.githubusercontent.com/14354078/39767917-b35df7aa-529c-11e8-964c-87218080fab3.png)

**Comment by YustasSwamp** [comment]
Thanks to reporting.

We still unable to reproduce it. What is a VM configuration? Mem size?

Try to remove `quiet` and modify loglevel to `loglevel=15` in photon.cfg before reboot.

**Comment by francisreader** [comment]
That did not result in any different output. The tdnf did result in a different kernel, as I can see the new cfg. On a default disk configuration, which drives should be root / boot?

```
89966c5c621c50d2e933dabe81373daa  /boot/config-4.9.53-5.ph2-esx
ac41b90d43067c3f73626116666712ea  /boot/linux-4.9.53-5.ph2-esx.cfg
ac41b90d43067c3f73626116666712ea  /boot/photon.cfg
c18ea9317f2d3266dc0201cfdea8dba4  /boot/systemd.cfg
01af5bfd3ef5cf9e949565f896f70d6c  /boot/System.map-4.9.53-5.ph2-esx
475688107fa9ba5cb74336577db22a72  /boot/vmlinuz-4.9.53-5.ph2-esx
after updating
fe253d24ad2f0b0d282c0ce2d1d63a4c  /boot/config-4.9.98-1.ph2-esx
8b30b09f409367f4db634754b5d2a671  /boot/linux-4.9.98-1.ph2-esx.cfg
8b30b09f409367f4db634754b5d2a671  /boot/photon.cfg
c18ea9317f2d3266dc0201cfdea8dba4  /boot/systemd.cfg
36fcae232c891941214172fece13e987  /boot/System.map-4.9.98-1.ph2-esx
b63737b740ca28454647e9061fdd9660  /boot/vmlinuz-4.9.98-1.ph2-esx
francis@e3-1246 /tmp $ 
```

**Comment by srivatsabhat** [comment]
Thank you for sharing the screenshots. It looks like those 2 boot attempts freeze at different points. Also, it takes 23 seconds to get to the ext4 mounting, which is rather slow... So, could you please confirm that this is an actual hang, and not merely slow to boot? You can give it a full 5 minutes or so to see if it still doesn't make any progress.

Also, it would help if you could share the following info:

- What is the exact ESX version/build/patch number on the host?

- Does the Generic kernel (with tdnf update) also show the same symptoms?

- Can you try a specific version of the Hypervisor-optimized kernel and see if that makes any difference? To do that, install a minimal Photon OS from ISO and run:
`tdnf update linux-esx-<version>.ph2`, where version is : 4.9.90-1, 4.9.94-1 and 4.9.94-2 [ Some non-trivial changes went in 4.9.94-2, so I'm curious to see if that boots fine. If you'd like to try other versions as well, you can run `tdnf list linux-esx` to see all the available versions. ]

**Comment by francisreader** [comment]
Happy to assist. 
The two different boot attempts are due to me removing quiet from the kernel boot params in grub

```
Hypervisor:	VMware ESXi, 6.5.0, 5310538 
Model:	X8DTN 
Processor Type:	Intel(R) Xeon(R) CPU L5630 @ 2.13GHz 
Logical Processors:	16 
NICs:	4 
```


Ok, looks like I was VERY impatient. 
It did boot. But took 5minutes....
What made you think of 5mins? Any specific timeout event?

See attached dmesg.

[dmesg.txt.gz](https://github.com/vmware/photon/files/1985227/dmesg.txt.gz)

**Comment by francisreader** [comment]
Trying to install an older alternate linux kernel, I get "There is no upgrade path for linux-esx-4.9.90-1.ph2."

**Comment by srivatsabhat** [comment]
Oh! Glad to hear that it did finally boot! 5 minutes was just a lucky guess ;-)

To switch to a lower version of linux-esx, you'll have to use `tdnf downgrade linux-esx-<version>.ph2` It would be good to know if other kernel versions also suffer the same slow boot.

From your dmesg log, it looks like there is almost a 5 minute delay in initializing the random driver:
[    8.620593] mousedev: PS/2 mouse device common for all mice
[  304.974799] random: crng init done

This can be caused by a lack of entropy, particularly in a virtualized environment. Could you try installing the following tools to remedy that and see if that speeds up your booting?

```
tdnf install -y haveged
systemctl enable haveged
systemctl start haveged

tdnf install -y rng-tools
systemctl enable rngd
systemctl start rngd

```

**Comment by francisreader** [comment]
linux-esx-4.9.94-2.ph2 works fine (a little slower, gets to console login after 12second, and then see the crng init mesg appear after 30seconds. )

linux-esx-4.9.97-1.ph2 starts incurring the large 5minute delay to boot. 

Installed haveged and rngd and it didn't improve the boot time. 

Anything else I can check for you, to understand what changes 94-2 -> 97-1 could be at fault?

**Comment by YustasSwamp** [comment]
It might be timeout in userspace (systemd)
@francisreader , can you provide output of these commands, please?:
`systemd-analyze`
`systemd-analyze critical-chain`

**Comment by francisreader** [comment]
[root@photon-master [ ~ ]# systemd-analyze 
Startup finished in 7.721s (kernel) + 5min 24.733s (userspace) = 5min 32.455s
root@photon-master [ ~ ]# systemd-analyze critical-chain 
The time after the unit is active or started is printed after the "@" character.
The time the unit takes to start is printed after the "+" character.

multi-user.target @5min 24.719s
└─vmtoolsd.service @5min 24.719s
  └─cloud-final.service @5min 23.609s +1.109s
    └─cloud-config.service @5min 22.449s +1.158s
      └─network-online.target @5min 22.449s
        └─cloud-init.service @5min 10.043s +12.402s
          └─systemd-networkd-wait-online.service @5min 8.072s +1.970s
            └─systemd-networkd.service @5min 8.041s +26ms
              └─network-pre.target @5min 8.040s
                └─cloud-init-local.service @263ms +5min 7.731s
                  └─systemd-remount-fs.service @227ms +29ms
                    └─system.slice @220ms
                      └─-.slice @208ms
](url)

**Comment by francisreader** [comment]
So there's something in the newer kernel, forcing a block in a userspace daemon,.,

**Comment by francisreader** [comment]
Discussion here on cloud-init blocking due to lack of entropy:
[](https://bugs.launchpad.net/ubuntu/+source/cloud-init/+bug/1727358)

**Comment by francisreader** [comment]
Keeping on earlier kernel. 

With cloud-init removed, the VM boots within 10s. Removing cloud-init had side effect of ssh server not accepting connections so my workaround for now, is to go back to earlier kernel version.


I'll put the VM up on a google-drive
https://drive.google.com/open?id=1aJJag4wiZqty82bnkpu-ozMiK_4ioCvx

Once I notice it has been download I'll remove. (or at the weekend)

**Comment by srivatsabhat** [comment]
Can you try the following steps and see if it helps speed up booting?

```
tdnf install -y haveged rng-tools
systemctl edit haveged
```
Then add the following lines and save it:

```
[Unit]
DefaultDependencies=no
Before=cloud-init-local.service

```
Do the same thing for rngd:

`systemctl edit rngd`

Then add the following lines and save it:

```
[Unit]
DefaultDependencies=no
Before=cloud-init-local.service
```

**Comment by francisreader** [comment]
A lot quicker, 20s to boot. 
What will be the proposed long term soln for people? I'm happy for this workaround.. 

```
root@photon-master [ ~ ]# systemd-analyze 
Startup finished in 7.590s (kernel) + 18.184s (userspace) = 25.774s
root@photon-master [ ~ ]# systemd-analyze critical-chain 
The time after the unit is active or started is printed after the "@" character.
The time the unit takes to start is printed after the "+" character.

multi-user.target @18.176s
└─vmtoolsd.service @18.176s
  └─cloud-final.service @17.017s +1.157s
    └─cloud-config.service @15.863s +1.152s
      └─network-online.target @15.862s
        └─cloud-init.service @4.202s +11.659s
          └─systemd-networkd-wait-online.service @2.475s +1.726s
            └─systemd-networkd.service @2.454s +19ms
              └─network-pre.target @2.453s
                └─cloud-init-local.service @236ms +2.177s
                  └─systemd-remount-fs.service @210ms +21ms
                    └─systemd-journald.socket @210ms
                      └─-.mount @199ms
                        └─system.slice @204ms
                          └─-.slice @199ms
root@photon-master [ ~ ]# 

```

**Comment by srivatsabhat** [comment]
Great! Thank you for verifying it!

As an immediate fix, I'm working on releasing updates to haveged and rng-tools packages to make their services run before cloud-init-local.service. So, that should take care of the issue for those who are willing to install those packages.

On the other hand, it was really the recent changes to the kernel that caused the boot speed regression; so I'm planning to get that addressed within the kernel itself soon.

**Comment by francisreader** [comment]
Is there an issue with the repos?
I've not changed network configs in my network and i'm not using a proxy.

```
tdnf -v update 
curl#7: Couldn't connect to server        1325    100%
Error: Failed to synchronize cache for repo 'VMware Photon Linux 2.0(x86_64)' from 'https://dl.bintray.com/vmware/photon_release_2.0_x86_64'
Disabling Repo: 'VMware Photon Linux 2.0(x86_64)'
```

Ideas as I'm not able to make the recommended changes on my virgin photon2 template.

**Comment by pinkwin** [comment]
This looks like bug described in [https://unix.stackexchange.com/questions/442698/when-i-log-in-it-hangs-until-crng-init-done] introduced in commit [https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=43838a23a05fbd13e47d750d3dfd77001536dd33].

**Comment by MikeVL** [comment]
Same problem with kernel 4.9.98-2.ph2-esx

```
> systemd-analyze blame
4h 12min 39.291s cloud-init-local.service
         13.082s systemd-networkd-wait-online.service
          8.612s cloud-init.service
          2.083s docker.service
           910ms cloud-config.service
           905ms cloud-final.service
           337ms dev-sda2.device
           165ms iptables.service
           140ms systemd-journald.service
           136ms systemd-udev-trigger.service
           129ms systemd-networkd.service
           115ms systemd-logind.service
           112ms user@0.service
            98ms systemd-journal-flush.service
            37ms systemd-resolved.service
            29ms systemd-remount-fs.service
            21ms systemd-udevd.service
            17ms sys-kernel-debug.mount
            16ms tmp.mount
            15ms dev-mqueue.mount
            15ms systemd-timesyncd.service
            14ms dev-hugepages.mount
            13ms systemd-sysctl.service
            11ms kmod-static-nodes.service
            10ms systemd-tmpfiles-setup-dev.service
             9ms systemd-tmpfiles-setup.service
             9ms systemd-update-utmp.service
             8ms systemd-tmpfiles-clean.service
             5ms systemd-random-seed.service
             4ms systemd-update-utmp-runlevel.service
             4ms systemd-user-sessions.service
```

**Comment by srivatsabhat** [comment]
Updates to haveged and rng-tools packages in Photon OS 2.0 are now available in our repos (haveged-1.9.1-4 and rng-tools-5-2). These updates make sure that haveged and rngd run before cloud-init-local.service, thus providing the necessary entropy to speed up booting. This workaround should be sufficient to fix the slow boot problem. Do let us know if you still see issues after upgrading to these package versions.

As for the kernel change that triggered this problem, there is ongoing discussion in the community to figure out how to resolve it: https://lkml.org/lkml/2018/4/13/513  At the same time, I'm also working on a slightly different solution for the Photon OS kernel, so stay tuned.

**Comment by MikeVL** [comment]
@srivatsabhat In my system, these packages were not installed. Are they necessary?

**Comment by srivatsabhat** [comment]
@MikeVL These packages provide additional sources of entropy on an entropy-starved VM. Installing them helps solve the slow boot problem because cloud-init-local.service appears to block on getrandom() during boot.

On the other hand, the proper fix would be to either modify cloud-init-local service such that it doesn't depend on cryptographic strength random numbers, or modify the kernel to utilize additional sources of entropy to satisfy getrandom() requests. Until such solutions are available, installing the latest versions of haveged/rng-tools will help you move past this issue.

**Comment by srivatsabhat** [comment]
I added a kernel driver to enhance the available entropy using rdrand. With this change, you don't need to install haveged or rng-tools packages to solve the slow boot problem.

To test this, do the following:
# Remove haveged and rng-tools if you have installed it already
`tdnf remove haveged rng-tools`
# Install the latest kernel with the new rdrand-rng driver (linux-esx-4.9.109-3)
`tdnf update linux-esx --refresh`
# Install the latest systemd package which autoloads this kernel driver at boot (systemd-233-14)
`tdnf update systemd --refresh`
# Reboot
reboot
# Observe how long it takes to boot
`systemd-analyze`
`systemd-analyze blame`

Your testing and feedback would be much appreciated! Thank you!

**Comment by francisreader** [comment]
Much Much Slower than the workaround, and slower than the original. 
```
root@photon2-master [ ~ ]# systemd-analyze 
Startup finished in 7.539s (kernel) + 5min 37.523s (userspace) = 5min 45.062s
root@photon2-master [ ~ ]# systemd-analyze blame
    3min 23.061s cloud-init-local.service
      2min 160ms systemd-networkd-wait-online.service
         11.745s cloud-init.service
          1.148s cloud-config.service
          1.141s cloud-final.service
           436ms dev-sda2.device
           198ms systemd-udev-trigger.service
           162ms systemd-journald.service
            79ms systemd-journal-flush.service
            78ms iptables.service
            54ms systemd-udevd.service
            50ms systemd-timesyncd.service
            42ms systemd-logind.service
            28ms systemd-resolved.service
            24ms systemd-update-utmp.service
            23ms user@0.service
            17ms systemd-networkd.service
            16ms systemd-tmpfiles-setup.service
            16ms dev-mqueue.mount
            15ms sys-kernel-debug.mount
            15ms systemd-remount-fs.service
            15ms dev-hugepages.mount
            15ms systemd-tmpfiles-setup-dev.service
            13ms tmp.mount
            13ms kmod-static-nodes.service
            10ms systemd-modules-load.service
             9ms systemd-sysctl.service
             6ms systemd-user-sessions.service
             6ms systemd-update-utmp-runlevel.service
             5ms systemd-random-seed.service

root@photon2-master [ ~ ]# tdnf list installed | grep linux-esx
linux-esx.x86_64                            4.9.109-3.ph2            @System
root@photon2-master [ ~ ]# tdnf list installed | grep systemd
systemd.x86_64                              233-14.ph2 



```

**Comment by francisreader** [comment]
looks like rng_core is loaded, 
```
root@photon2-master [ ~ ]# lsmod
Module                  Size  Used by
nf_conntrack_ipv6       8933  1
nf_defrag_ipv6         24217  1 nf_conntrack_ipv6
ip6table_filter         1641  1
ip6_tables             15336  1 ip6table_filter
xt_conntrack            3081  2
iptable_mangle          1651  0
iptable_nat             1887  0
nf_conntrack_ipv4       8554  2
nf_defrag_ipv4          1411  1 nf_conntrack_ipv4
nf_nat_ipv4             4763  1 iptable_nat
nf_nat                 11967  1 nf_nat_ipv4
iptable_filter          1699  1
xt_LOG                  1743  0
nf_conntrack           68228  5 nf_conntrack_ipv6,nf_conntrack_ipv4,xt_conntrack,nf_nat_ipv4,nf_nat
mousedev               10048  0
psmouse                78764  0
evdev                  11006  0
vmxnet3                44874  0
vmwgfx                206858  1
drm_kms_helper         82045  1 vmwgfx
ttm                    68782  1 vmwgfx
drm                   254058  4 vmwgfx,ttm,drm_kms_helper
sr_mod                 13143  0
cdrom                  43267  1 sr_mod
i2c_core               25958  2 drm_kms_helper,drm
processor              21863  0
rng_core                5788  0
ipv6                  332566  24 nf_conntrack_ipv6,nf_defrag_ipv6

```

**Comment by srivatsabhat** [comment]
rng_core is just the hw_random core infrastructure, which doesn't do anything on its own. What you need is the rdrand-rng driver which actually provides the extra entropy (which in turn depends on rng_core). Without loading that driver, the kernel won't boot fast; so the results you saw are not surprising. However, the entry in /etc/modules-load.d/ should have automatically loaded rdrand-rng successfully during boot (provided that your CPU supports rdrand).

Can you please share the output of:
`dmesg`
`cat /proc/cpuinfo`
and the contents of /etc/modules-load.d/

**Comment by francisreader** [comment]
```
[oot@photon2-master [ ~ ]# cat /proc/cpuinfo 
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 37
model name	: Intel(R) Xeon(R) CPU           L5630  @ 2.13GHz
stepping	: 1
microcode	: 0x14
cpu MHz		: 2133.409
cache size	: 12288 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 11
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts nopl xtopology tsc_reliable nonstop_tsc aperfmperf pni pclmulqdq ssse3 cx16 sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes hypervisor lahf_lm epb kaiser tsc_adjust dtherm ida arat
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass
bogomips	: 4266.81
clflush size	: 64
cache_alignment	: 64
address sizes	: 43 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 37
model name	: Intel(R) Xeon(R) CPU           L5630  @ 2.13GHz
stepping	: 1
microcode	: 0x14
cpu MHz		: 2133.409
cache size	: 12288 KB
physical id	: 2
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 2
initial apicid	: 2
fpu		: yes
fpu_exception	: yes
cpuid level	: 11
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts nopl xtopology tsc_reliable nonstop_tsc aperfmperf pni pclmulqdq ssse3 cx16 sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes hypervisor lahf_lm epb kaiser tsc_adjust dtherm ida arat
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass
bogomips	: 4266.81
clflush size	: 64
cache_alignment	: 64
address sizes	: 43 bits physical, 48 bits virtual
power management:

processor	: 2
vendor_id	: GenuineIntel
cpu family	: 6
model		: 37
model name	: Intel(R) Xeon(R) CPU           L5630  @ 2.13GHz
stepping	: 1
microcode	: 0x14
cpu MHz		: 2133.409
cache size	: 12288 KB
physical id	: 4
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 4
initial apicid	: 4
fpu		: yes
fpu_exception	: yes
cpuid level	: 11
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts nopl xtopology tsc_reliable nonstop_tsc aperfmperf pni pclmulqdq ssse3 cx16 sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes hypervisor lahf_lm epb kaiser tsc_adjust dtherm ida arat
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass
bogomips	: 4266.81
clflush size	: 64
cache_alignment	: 64
address sizes	: 43 bits physical, 48 bits virtual
power management:

processor	: 3
vendor_id	: GenuineIntel
cpu family	: 6
model		: 37
model name	: Intel(R) Xeon(R) CPU           L5630  @ 2.13GHz
stepping	: 1
microcode	: 0x14
cpu MHz		: 2133.409
cache size	: 12288 KB
physical id	: 6
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 6
initial apicid	: 6
fpu		: yes
fpu_exception	: yes
cpuid level	: 11
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts nopl xtopology tsc_reliable nonstop_tsc aperfmperf pni pclmulqdq ssse3 cx16 sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes hypervisor lahf_lm epb kaiser tsc_adjust dtherm ida arat
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass
bogomips	: 4266.81
clflush size	: 64
cache_alignment	: 64
address sizes	: 43 bits physical, 48 bits virtual
power management:

root@photon2-master [ ~ ]# ls -ltr /etc/modules-load.d/
total 4
-rw-r--r-- 1 root root 76 Jul  3 12:05 10-rdrand-rng.conf
root@photon2-master [ ~ ]# cat /etc/modules-load.d/10-rdrand-rng.conf
# Automatically load the following kernel modules on every boot.
rdrand-rng
root@photon2-master [ ~ ]# 
](url)
```

**Comment by francisreader** [comment]
also 
[dmesg.txt](https://github.com/vmware/photon/files/2161705/dmesg.txt)

**Comment by srivatsabhat** [comment]
Ah, looks like your CPU doesn't support the 'rdrand' instruction (it would have shown 'rdrand' under "flags" in your /proc/cpuinfo output, if your CPU supported it).

For example, here is the output of `cat /proc/cpuinfo` on a test machine with a processor which supports 'rdrand':
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 62
model name	: Intel(R) Xeon(R) CPU E5-2440 v2 @ 1.90GHz
stepping	: 4
microcode	: 0x42c
cpu MHz		: 1900.000
cache size	: 20480 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts nopl xtopology tsc_reliable nonstop_tsc pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c **rdrand** hypervisor lahf_lm ibrs ibpb stibp kaiser fsgsbase tsc_adjust smep arat arch_capabilities
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass
bogomips	: 3800.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 43 bits physical, 48 bits virtual
power management:

Unfortunately, without the processor supporting 'rdrand', the rdrand-rng kernel driver won't be useful (which is why it exited during module load itself). So I'm afraid you'll have to switch back to the previous workaround (i.e., installing haveged or rng-tools) to speed up booting on your system. Sorry about that! And thanks a lot for your testing and feedback!
