### ISSUE TITLE
Tomcat configuration files are overwritten at each update

### ISSUE THREAD

**Issue by abaldoni** [vmware/photon#776]
Tomcat configuration files in  /var/opt/apache-tomcat/conf are overwritten at each tdnf update that comes with a new Tomcat release.
The expected behaviour is to keep the existing files.
The owner of the following file /var/opt/apache-tomcat/logs/catalina.out is also changed from tomcat:tomcat to root:root preventing Tomcat to start.

**Comment by suezzelur** [comment]
@xiaolin-vmware can you take a look?

**Comment by YustasSwamp** [comment]
Fixed in version 8.5.31-2
