### ISSUE TITLE
photon 2.0 v13 hardware ova missing file

### ISSUE THREAD

**Issue by wideglide** [vmware/photon#777]
This ova file seems to be missing the `nvram` file.
http://dl.bintray.com/vmware/photon/2.0/GA/ova/photon-custom-hw13-2.0-304b817.ova

Here's the error message during OVF deploy in vSphere/ESXi 6.5:
> The specified object /photon-custom-hw13-2.0-304b817/nvram could not be found.

I was able to deploy the v11 hardware ovf just fine, and upgrade to v13 subsequently.

**Comment by suezzelur** [comment]
There is an existing issue with VC 6.5 UI which prevents the EFI ova to load properly. Manual deployment to ESX or ovftool deployment to VC should still work for v13 ova.
