### ISSUE TITLE
Add kubectl-extras package to deliver client kubectl binaries

### ISSUE THREAD

**Issue by ghost** [vmware/photon#782]
See Pull Request #779. The vCenter WCP team would be hugely grateful if we could get something like this merged for us. We're using Kubernetes from Photon directly, and it'd make both a lot of sense and our lives a lot easier if (at least in the short run) we can also deliver kubectl for alternative platforms that matches our Kubernetes deliverable versions and compatibility from the same location.

**Comment by sharathjg** [comment]
pr has been merged and artifacts published
