### ISSUE TITLE
Add disk to Photon OS

### ISSUE THREAD

**Issue by iGlaedr** [vmware/photon#783]
Hi 
I might just don't see the solution.
I'm trying to add a secondary disk to the Photon OS.
I've created a ext4 Partition on it and added it to the /etc/fstab but now the VM does not boot properly:

/etc/fstab
```
UUID=446d3d1f-bcab-4a2d-b3d1-c689fd54860b    /     ext4    defaults 1 1
UUID=4a77e177-6da6-4fc1-848e-7c8c0d6927f2    /srv/ ext4    defaults 1 1
```
with this settings i get this on boot:
You are in emergency mode. after logging in .....

Thanks for the Help
iGlaedr

**Comment by YustasSwamp** [comment]
try "defaults 0 0" for this partition

**Comment by iGlaedr** [comment]
Still the same

**Comment by iGlaedr** [comment]
Is this repo down ?
I can't reach it (neither from my work/phone/home).

**Comment by suezzelur** [comment]
Do you see fsck errors when you boot up just before you go into emergency mode?

**Comment by YustasSwamp** [comment]
Can you try:
UUID=446d3d1f-bcab-4a2d-b3d1-c689fd54860b    /     ext4    defaults 1 1
UUID=4a77e177-6da6-4fc1-848e-7c8c0d6927f2    /srv/ ext4    user,noauto 0 0

Boot it.
And then manually run:
# mount /srv

**Comment by iGlaedr** [comment]
Thanks for the help it worked without the "mount /srv"
