### ISSUE TITLE
unable to find screen  package in Photon 2.0 

### ISSUE THREAD

**Issue by reachkrr** [vmware/photon#784]
Hi , 

Can somebody point me to correct  package for  screen  library in Photon 2.0 repo . 

Regards
Raj

**Comment by YustasSwamp** [comment]
We do have `tmux` package in 2.0 repo.
`tdnf install tmux` should work.

**Comment by reachkrr** [comment]
I am looking for screen especially  and not tmux

**Comment by YustasSwamp** [comment]
We do not have `screen` package.
