### ISSUE TITLE
netdata package missing from tdnf

### ISSUE THREAD

**Issue by tsener** [vmware/photon#786]
I'd like to install  netdata for performance monitoring on Photon.
Package is missing from tdnf repo, and te statically compiled binary fails to run, too.

Link to the software: 
https://github.com/firehol/netdata

**Comment by WriteCodeEveryday** [comment]
Seconding this one.

They have a list of OS, but we're dead last here.

**Comment by vowywowy** [comment]
Not saying this isn't an issue, but what's preventing you from running it in a container? That's how I'm running it and that's kinda the whole point of Photon.

**Comment by YustasSwamp** [comment]
We do not provide netdata package, but you can use netdata container in Photon as suggested by @vowywowy
