### ISSUE TITLE
Unable to install yum in PhotonOS

### ISSUE THREAD

**Issue by Nerr1x** [vmware/photon#787]
I am trying to install yum over tdnf, but i keep getting the error below:

tdnf install yum

Found 1 problem(s) while resolving
1. package pmd-0.0.5-5.ph2.x86_64 requires libtdnf.so.0()(64bit), but none of the providers can be installed
Error(1301) : Hawkey general runtime error

The three standard repos are enabled.

**Comment by suezzelur** [comment]
Please use tdnf for Photon OS 2.0. tdnf obsoletes yum in 2.0 release.

**Comment by AbeHariz** [comment]
Hi,

I need help on the usage of PhotonOS.

How to check the history of the updates that have been done?

If in RHEL, we can use "yum history list all" , but what about for PhotonOS?

Kindly advice. 

Thank you.
