### ISSUE TITLE
BMDMA: BAR4 is zero, falling back to PIO

### ISSUE THREAD

**Issue by GiganteX** [vmware/photon#788]
See screenshot here:
http://nebol.se:81/photonos_cant_boot.PNG

I am running PhotonOS, downloaded and deployed today, on a Dell r710 with ESXI 6.7.

Directly at boot it displays the above error message, then it continues with the booting. 

What does the error mean?

**Comment by sharathjg** [comment]
im not able to accesss the image from that link.

**Comment by GiganteX** [comment]
I put it on dropbox instead:
https://www.dropbox.com/s/d6445pue97z1h1a/photonos_cant_boot.PNG?dl=0

**Comment by NikolayDachev** [comment]
+ 1 for the same issue, ctl+c solve it .. I think this happen on reboot only

**Comment by k1rked** [comment]
![capture](https://user-images.githubusercontent.com/4130494/45839196-e53d0100-bcd0-11e8-9be3-524eaac67664.PNG)

I have the same problem and it frequently hangs here.
