### ISSUE TITLE
Question: tracking kernel updates

### ISSUE THREAD

**Issue by scriptjs** [vmware/photon#793]
Where can I track updates to the photon kernel?

**Comment by suezzelur** [comment]
@scriptjs for released versions of Photon OS, we have not made a minor version update for linux kernel yet. You can follow the patch version updates here: https://github.com/vmware/photon/wiki/Security-Advisories These are mainly done for fixing security issues.

**Comment by scriptjs** [comment]
Looking through all security updates for the latest kernel version and patch is pretty time consuming. It seems the better way I found is to seek the latest published version of the kernel on bintray at https://dl.bintray.com/vmware/photon_release_2.0_x86_64/x86_64/ and grepping the linux package version.

**Comment by suezzelur** [comment]
Alternatively, you can do tdnf updateinfo info OR tdnf list linux to list all versions.
