### ISSUE TITLE
Better docs for Kickstart postinstall Section

### ISSUE THREAD

**Issue by tibmeister** [vmware/photon#794]
So having a little bit of a time wrapping my brain around the kickstart format, specifically the post install section.  The file itself doesn't look like a "good ole fashioned kickstart" but rather a JSON file, which is where my confusion comes into play.

I have a ton of post install/pre login customization I want to do, and it will be in several ks files, one for each of my hosts, so I can rapidly rebuild if needed.  The issue is I do a lot of here files and such, so wrapping my head around doing something like 

`cat > /etc/systemd/network/10-static-en.network << "EOF"
[Match]
Name=eth0

[Network]
Address=192.168.0.56/24
Gateway=192.168.0.1
EOF

chmod 644 10-static-en.network
sed -i -e 's/DHCP=yes/DHCP=no/g' /etc/systemd/network/99-dhcp-en.network

cat > /etc/systemd/resolved.conf << "EOF"
[Resolve]
DNS=8.8.8.8
DOMAINS=mysupercoolnetwork.com
EOF

systemctl restart system-network
#Setup SSH
sed -i -e 's/PermitRootLogin no/PermitRootLogin yes/g' /etc/ssh/sshd_config
systemctl restart sshd`

My plan is to have one for each of my systems, then create a custom isolines.cfg to have a menu of them and villa, I just boot the iso and select which system I want.  This will be scripted for larger deployments, but just how do I do this in the kickstart format used in Photon?

**Comment by tibmeister** [comment]
So actually the lack of documentation goes further into the kickstartfile, for example, partitions.  The size parameter, what's the unit, bytes, kb, mb, gb???  Is the kickstart based on another project that could be referenced or is the kickstart format completely custom to Photon?  It's not the same format used by ESXi/ESX, which is really what I've used the most of.

**Comment by suezzelur** [comment]
@tibmeister Are you talking about the documentation here: https://github.com/vmware/photon/blob/master/docs/kickstart.md
What is the config that you provided and what happens when you try to boot the iso?
For partitioning, did you not have luck trying to use the cfg from this commit: https://github.com/vmware/photon/commit/c3771c3512c72e168fd570c9ab935c269ceff979#diff-a6a6368b6f3fed817a7905f93a564c31
The units are in MB.

**Comment by tibmeister** [comment]
So I did a lot of playing and yes, that doc is the one that I was trying to use.  What basically I ended up doing is writing the shells script I needed to accomplish what I wanted, then put quotes and commas on every line, then pasted all of that into the json of the kickstart.

Doing some of the more advanced stuff, like installing s3fus, the desired version of docker-ce, and such I ended up using the ks file to copy a script from the iso then using the "Create a Startup Service" portion of the admin guide, I created a service that fired the script, which the script removed the service at the end because I couldn't find how to run a one-time script at first-boot in the docs.

I just think this can be a bit better for environments that don't run DHCP in the datacenter and require a little more bootstrapping to bring up a PhotonOS server to act as a docker host.  Granted after almost a week of messing with it I have an iso that I can boot from that deploys the host in about 90 seconds then another 5 minutes for the script to finish the setup.  I have a separate system that I use to generate the per-host kickstart files for ESXi so I adapted that to generate the per-host kickstart files for PhotonOS.

It would be nice to see what other options there are for using the kickstart file, this seems very limited and the doc barely even touches the surface.

**Comment by nimDevOps** [comment]
There are always several ways to achieve the same goal. Correct me if I'm wrong the kick-start file is designed to help automate answering questions provided by iso installer: account, password, locale, disk layout etc. Once you created image, iterating might be done via additional tool like provisioning.
Yes, I agree that KS is limited by json, and I also wondering if it could be parametrized ( for example using values passing from variables).

**Comment by stuclem** [comment]
For investigation in the next release.

**Comment by YustasSwamp** [comment]
Up to date documentation for kickstart: https://github.com/vmware/photon/blob/master/installer/ks_config.txt
