### ISSUE TITLE
pmd-cli usr groupadd returns error

### ISSUE THREAD

**Issue by nitinbhojwani** [vmware/photon#796]
Got following error when tried executing:

> pmd-cli usr groupadd group-name
Error(382312602) : Failed to connect to the remote host, reason = rpc_s_no_name_mapping (0x16c9a09a).

### Steps to reproduce:
I am trying to create a docker image from base image vmware/photon:2.0 by installing pmd-cli (and several other packages also) by:

> tdnf -y install pmd-cli
-> At this point pmd-cli gets installed

Now when I try to use it to add a group by:
>pmd-cli usr groupadd group-name
Throws error: Error(382312602) : Failed to connect to the remote host, reason = rpc_s_no_name_mapping (0x16c9a09a).

**Comment by ppadmavilasom** [comment]
did you install pmd (server) and start the service? there is no current path to install pmd server in a container. you will have to do

**Comment by erickrog28** [comment]
you need install package pmd from next command

tdnf install pmd -y in a vm

next start service

systemctl start pmd.service

and finally enable service

systemctl enable pmd.service

and pmd-cli work fine!!

regards!!

**Comment by ssahani** [comment]
Closing
