### ISSUE TITLE
Photon vmtools

### ISSUE THREAD

**Issue by kstst** [vmware/photon#797]
I just installed photon-custom-lsilogic-hw11-2.0-304b817.ova 
And have a running photon-custom-lsilogic-hw11-2.0-304b817.vmx which will not size or allow copy paste operations from windows 10. HOST Windows version 10.0, build 16299, platform 2, "", SMP
Photon-machine vmtoolsd -v shows 10.1.10.63510 (build-6082533)
Host VMware Workstation 12.5.9 build-7535481.
I have other VMs' running fine. Fedora 28 and Kali.

**Comment by kstst** [comment]
Is it normal to have to Ctrl-Alt to break out of the VM session when using Photon?

**Comment by tibmeister** [comment]
That's pretty standard when you are using a console window into a VM.
