### ISSUE TITLE
unable to mount floppy image

### ISSUE THREAD

**Issue by constiks** [vmware/photon#798]
floppy image connection seems to be ignored:

steps to reproduce:
1. create floppy image
mkfs.msdos -C /tmp/floppy.img 1440
mkdir -p /media/floppy/
mount -o loop /tmp/floppy.img /media/floppy/
cp files/* /media/floppy/
umount /media/floppy/

2. connect the floppy image to photon2 VM

vmware.log shows that image is connected:
2018-07-07T07:40:09.392Z| vmx| A100: ConfigDB: Setting floppy0.fileType = "file"
2018-07-07T07:40:09.392Z| vmx| A100: ConfigDB: Setting floppy0.fileName = "/vmfs/volumes/59106a1f-a63128d1-3d2f-44a8421553f6/ISO/floppy.img"
2018-07-07T07:40:09.446Z| vmx| I125: VigorTransport_ServerSendResponse opID=VmConfigFormMediator-applyOnMultiEntity-5865784-ngc:70248289-9b-52-c189 seq=74076: Completed Floppy request.

but floppy device /dev/fd0 does not appear

tested same image on ubuntu VM - appeared correctly as /dev/fd0

**Comment by YustasSwamp** [comment]
To be honest, we have never tried floppy in Photon. Probably we have missing drivers for it.
What kernel do you use? `uname -r`

**Comment by constiks** [comment]
uname -r
4.9.111-1.ph2-esx

**Comment by YustasSwamp** [comment]
It is linux-esx, can you try generic linux, please?
`tdnf install linux` and then reboot.

**Comment by constiks** [comment]
tried, same result

root [ / ]# uname -r
4.9.111-4.ph2

root [ / ]# ls -la /dev/f*
crw-rw---- 1 root video 29,   0 Jul 20 10:59 /dev/fb0
lrwxrwxrwx 1 root root       13 Jul 20 10:59 /dev/fd -> /proc/self/fd
crw-rw-rw- 1 root root   1,   7 Jul 20 10:59 /dev/full
crw-rw-rw- 1 root root  10, 229 Jul 20 10:59 /dev/fuse

**Comment by YustasSwamp** [comment]
Sorry for the long delay.
We can add floppy disk support. Can you provide more info about your project/product, please?
Where do you need support for FD? As I can see from the initial post it is linux-esx in Photon 2.0?
Thanks

**Comment by srivatsabhat** [comment]
Closing this, due to lack of info. Please reopen this issue if you still need floppy disk support.

**Comment by dotcarls** [comment]
@srivatsabhat Floppy disk support would be nice to have when using Packer to build Photon VMs on a remote ESX instance. [From the docs](https://www.packer.io/docs/builders/vmware-iso.html#using-a-floppy-for-linux-kickstart-file-or-preseed):

> Depending on your network configuration, it may be difficult to use packer's built-in HTTP server with ESXi. Instead, you can provide a kickstart or preseed file by attaching a floppy disk. An example below, based on RHEL...
