### ISSUE TITLE
IPv4 & IPv6 APIPA addresses generated

### ISSUE THREAD

**Issue by lucdekens** [vmware/photon#800]
I'm deploying Photon 2.0, appliance, into a vSphere 6.7 environment.
Although I only have static IPv4 defined afaik, I keep getting APIPA addresses (IPv4 & IPv6).

The static IPv4 file looks ok to me.
And the assigned IPv4 address is not a duplicate.

Am I missing something?

<pre><code>
root@photon [ ~ ]# networkctl status eth0
● 2: eth0
       Link File: /usr/lib/systemd/network/99-default.link
    Network File: /etc/systemd/network/10-static-en.network
            Type: ether
           State: routable (configured)
            Path: pci-0000:0b:00.0
          Driver: vmxnet3
      HW Address: 00:50:56:9c:66:56 (VMware, Inc.)
         Address: 192.168.1.91
                  <b>169.254.118.213</b>
                  <b>fe80::250:56ff:fe9c:6656</b>
         Gateway: 192.168.1.254
             DNS: 192.168.1.2
                  192.168.1.3
  Search Domains: local.lab
             NTP: 192.168.1.2
                  192.168.1.3

root@photon [ ~ ]# cat /etc/systemd/network/10-static-en.network
[Match]
Name=eth0

[Network]
Address=192.168.1.91/24
Gateway=192.168.1.254
DNS=192.168.1.2 192.168.1.3
Domains=local.lab
NTP=192.168.1.2 192.168.1.3
# Disable IPv6
LinkLocalAddressing=ipv4
IPv6AcceptRA=no
</pre>

**Comment by YustasSwamp** [comment]
unable to reproduce

**Comment by sudtek** [comment]
Hi, 
i have got the same problem an be able to reproduce.

My first goal was to disable ipv6 address from my network 10.0.0.0/8 and avoid DHCP lease. I was not able to find gai.conf so i had add this options to my /etc/systemd/network/10-static-en.network :

LinkLocalAddressing=ipv4
DHCP=no

root@photonos01 [ ~ ]# networkctl status eth0
● 2: eth0
       Link File: /usr/lib/systemd/network/99-default.link
    Network File: /etc/systemd/network/10-static-en.network
            Type: ether
           State: routable (configured)
            Path: pci-0000:0b:00.0
          Driver: vmxnet3
          Vendor: VMware
           Model: VMXNET3 Ethernet Controller
      HW Address: 00:0c:29:67:2a:b2 (VMware, Inc.)
         Address: 10.99.9.120
                  169.254.165.1
                  fe80::20c:29ff:fe67:2ab2
         Gateway: 10.255.24.30
  Search Domains: COL-xxxxxxxx.LOCAL
             NTP: 10.255.24.29
                  195.83.132.135

As you can see i have a ghost ip 169.254.165.1

Delete the 2 options, update and restart

root@photonos01 [ ~ ]# networkctl status eth0
● 2: eth0
       Link File: /usr/lib/systemd/network/99-default.link
    Network File: /etc/systemd/network/10-static-en.network
            Type: ether
           State: routable (configured)
            Path: pci-0000:0b:00.0
          Driver: vmxnet3
          Vendor: VMware
           Model: VMXNET3 Ethernet Controller
      HW Address: 00:0c:29:67:2a:b2 (VMware, Inc.)
         Address: 10.99.9.120
                  fe80::20c:29ff:fe67:2ab2
         Gateway: 10.255.24.30 (VMware, Inc.)
  Search Domains: COL-xxxxxx.LOCAL
             NTP: 10.255.24.29
                  195.83.132.135

No more ghost ip !

Now with this temporary 10-static-en.network no more ghost ip.
[Match]
Name=eth0

[Network]
IPv6AcceptRA=no
Address=10.99.9.120/8
Gateway=10.255.24.30
Dns=10.255.24.29
Domains=COL-xxxxxxxxx.LOCAL
NTP=10.255.24.29 195.83.132.135
#LinkLocalAddressing=ipv4
#DHCP=no



But i always have the ipv6 fe80::20c:29ff:fe67:2ab2 ....

Thanks

**Comment by ssahani** [comment]
Please Pick https://github.com/systemd/systemd/commit/0e2fdb83bb5e22047e0c7cc058b415d0e93f02cf

**Comment by lucdekens** [comment]
Will do when I'm back on site

**Comment by lucdekens** [comment]
I see the same on photon 3.
By enabling network debugging, it looks like the IP address is obtained by LLDP.

Apr 09 19:03:14 photon systemd-networkd[198]: LLDP: Started LLDP client
Apr 09 19:03:14 photon systemd-networkd[198]: eth0: Started LLDP.
Apr 09 19:03:14 photon systemd-networkd[198]: eth0: Gained carrier
Apr 09 19:03:14 photon systemd-networkd[198]: eth0: Acquiring IPv4 link-local address
Apr 09 19:03:14 photon systemd-networkd[198]: IPV4LL: Picked new IP address 169.254.193.10

Which corresponds with what I see later on

● 2: eth0
       Link File: /usr/lib/systemd/network/99-default.link
    Network File: /etc/systemd/network/10-static-en.network
            Type: ether
           State: routable (configured)
            Path: pci-0000:0b:00.0
          Driver: vmxnet3
          Vendor: VMware
           Model: VMXNET3 Ethernet Controller
      HW Address: 00:50:56:b6:4b:f4 (VMware, Inc.)
         Address: 192.168.10.70
                  169.254.193.10
         Gateway: 192.168.10.1 (VMware, Inc.)
             DNS: 192.168.10.2
                  192.168.10.3

Is there a way to disable this LLDP client?

**Comment by ssahani** [comment]
IP addresses are not obtained by LLDP. 
In the network section
LLDP=no

**Comment by lucdekens** [comment]
Ok, thanks.
The LLDP client is gone.

I still see

Apr 09 21:04:55 photon systemd-networkd[194]: eth0: Gained carrier
Apr 09 21:04:55 photon systemd-networkd[194]: eth0: Acquiring IPv4 link-local address
Apr 09 21:04:55 photon systemd-networkd[194]: IPV4LL: Picked new IP address 169.254.146.239.

Where is this coming from?
And can I avoid it?

**Comment by lucdekens** [comment]
Finally found the answer.

The presence of the IPV4LL and IPV6LL is controlled through the **LinkLocalAddressing** entry in the [Network] section.
To have no APIPA address for LL, just set
```
[Network]
LinkLocalAddressing=no
```
