### ISSUE TITLE
Google BBR not enabled in kernel

### ISSUE THREAD

**Issue by bluedevils23** [vmware/photon#801]
I want to enable google BBR TCP congestion avoid algo, seems not enabled in current kernel.

**Comment by srivatsabhat** [comment]
Any updates? Do you still need this?

**Comment by bluedevils23** [comment]
Thanks srivat, I managed to achieve it with building from source code. So I think it is no longer

**Comment by khayamgondal** [comment]
@srivatsabhat @bluedevils23 is it still open?

**Comment by srivatsabhat** [comment]
Let us close it, since @bluedevils23 mentioned in the comment above that there is no longer a need to add this to Photon.

**Comment by zz5678** [comment]
now my photon's core version:
```
uname -r
4.19.79-1.ph3-esx
```
is it right way to update the core to sth like `4.19.12-1.el7.elrepo.x86_64` from `http://mirror.rc.usf.edu/compute_lock/elrepo/kernel/el7/x86_64/RPMS/`??
or photon has its own core patch?
now?

there is little info on google or here

**Comment by YustasSwamp** [comment]
We can consider adding CONFIG_TCP_CONG_BBR=m in generic kernel.
@zz5678 do you want to add it and to send pull request?

**Comment by lakxtxue** [comment]
I also need this module. I tried to compile ova image according to the official documentation. This failed. I compiled under branch 3.0. When will this module be included?

**Comment by srivatsabhat** [comment]
Closing this issue as @shatur93 enabled BBR in linux (generic) kernel in Photon 3.0

**Comment by Tw-C** [comment]
Sorry for reviving this thread, but it appears TCP BBR congestion algorithm isn't enabled in latest Photon OS 5.0 GA, also can't seem to find any online documentation about enabling it. Any pointer would be helpful & appreciated.
