### ISSUE TITLE
Docker build fails with unexpected EOF

### ISSUE THREAD

**Issue by gwiesenekker** [vmware/photon#803]
Hi,

I have installed Photon 2 minimal from the 304b817 ISO. When I try to build the following Dockerfile:

FROM ubuntu:14.04
MAINTAINER GW
RUN apt-get update
RUN apt-get install -y nginx
RUN echo 'Hi, I am in your container' >/usr/share/nginx/html/index.html
EXPOSE 80

It fails with the error:

Error response from daemon: Error processing tar file(exit status 1): expected EOF

It fails both when building as a regular user (member of the docker group) and as the root user. The Dockerfile builds on Centos and Ubuntu hosts.

Any ideas?
Gijsbert

**Comment by kyos0109** [comment]
I also encountered the same error.

I rollback docker to old version, from docker-17.06.0-6.ph2.x86_64 => docker-17.06.0-5.ph2.x86_64.

https://dl.bintray.com/vmware/photon_updates_2.0_x86_64/x86_64

**Comment by gwiesenekker** [comment]
That resolved the issue, thanks!

Regards,
Gijsbert

**Comment by vowywowy** [comment]
Getting the same failure here. Every ```docker build``` fails with the same error.

**Comment by xme** [comment]
+1
Fresh install, testing it and it fails to build a simple container... That's a nice start :(

**Comment by Anganthier** [comment]
+1
It works after downgrading the package (tdnf downgrade docker # 17.06.0-6 -> 17.06.0-5)

**Comment by SamuelLayNZ** [comment]
Had to downgrade twice 17.06.0-7 -> 17.06.0-5
Now works after the downgrade.
