### ISSUE TITLE
CONFIG_NUMA=n only on config-esx

### ISSUE THREAD

**Issue by rfrail3** [vmware/photon#805]
Numa is disabled only on "config-esx" while in the other "config" and "config-aws" have it enabled.

I look into the VMware papers about Numa and I don't find any recomendation for disable it. Why that change? It is due a special requirement?

Thanks,

**Comment by YustasSwamp** [comment]
The assumption here is that linux-esx kernel will be running on nun numa VMs

**Comment by rfrail3** [comment]
Sorry, but why it need to be running on non numa VMs? It is documented in some place?

**Comment by YustasSwamp** [comment]
It is purely Photon OS initiative to disable this feature. Linux-esx is request driven kernel flavor. We would like to keep it small and fast. Only requested features will added into it. For instance audit was added just recently while it was present in other flavors. Nobody requested numa support in linux-esx over last 3 years.
