### ISSUE TITLE
How to install the latest ceph in photon

### ISSUE THREAD

**Issue by Ge1ge** [vmware/photon#807]
Hi friends, I want to deploy the latest ceph named mimic in the photon. But the repositories just have jewel.So  I upgrade the ceph-deploy and add a new ceph.repo file in the /etc/yum.repo.d/ to install the latest ceph, but errors show like that
[ceph_deploy][ERROR ] UnsupportedPlatform: Platform is not supported: VMware Photon OS  2.0.
So any other way to install latest ceph in the photon? I need your help.
great thanks!

**Comment by DheerajSShetty** [comment]
Ceph deploy by default does not support Photon OS. You can install the ceph deploy provided by Photon and try it again.

**Comment by gentlewind** [comment]
After changing the deploy script, we can download the ceph from the ceph official website. But the runtime error arise when ceph-deploy install the ceph (for centos).
![image](https://user-images.githubusercontent.com/6801512/45191810-dc334500-b277-11e8-8eb1-1317655f9983.png)

**Comment by DheerajSShetty** [comment]
As I had mentioned in the mail, installing other rpms on Photon can lead to run time dependency errors. Please raise a request for the Ceph version that you need.

**Comment by YustasSwamp** [comment]
Ceph was removed from Photon 3.0.
Ceph maintenance in 2.0 is under question.
Mark it as a wontfix and close a bug.

**Comment by proofquantu** [comment]
Running out of reasons to run PhotonOS  "Mark it as a wontfix and close a bug."
No support for rpi4 after 9mths 
"on Sep 12, 2019

Thanks @johncchampion for this Feature Request.
We also would like to have Photon OS 64-bit on Raspberry Pi 4 and soon we will work on this."
