### ISSUE TITLE
mount.fuse?

### ISSUE THREAD

**Issue by xme** [vmware/photon#808]
Hi *,

I installed s3fs because I've containers which must read/write files into S3 buckets. I can mount my buckets from the cmdline but I'd like to add them to the /etc/fstab for automatic mount.
It seems that mount.fuse is not available on Photon OS!? Any idea?

Here is the line in /etc/fstab:

`s3fs#data-xxxxxxxx /xxxxxxxx fuse allow_other,use_cache=/tmp/cache,uid=0,gid=0 0 0
`

And the mount error:

`mount: /xxxxxxxx: wrong fs type, bad option, bad superblock on s3fs#data-xxxxxxxx, missing codepage or helper program, or other error.`

/x

**Comment by drew442** [comment]
I have this same issue when mounting sshfs from fstab. I can mount from the shell with no problem.

**Comment by suezzelur** [comment]
Do you have fuse package installed?

**Comment by tibmeister** [comment]
You should be able to install the fuse package, the add the s3s-fuse package.

git clone https://github.com/s3fs-fuse/s3fs-fuse.git
cd s3fs-fuse
./autogen.sh
./configure --prefix=/usr --with-openssl
make
make install

I've used this to mount MinIO volumes to the PhotonOS,   Here's the GH issue I referenced when wanting to do this via fstab.


https://github.com/s3fs-fuse/s3fs-fuse/issues/417

**Comment by srivatsabhat** [comment]
It looks like installing the fuse package should solve your problem. Please reopen if the issue persists.
