### ISSUE TITLE
pmd-cli fails to connect to host

### ISSUE THREAD

**Issue by DivXZero** [vmware/photon#812]
I've deployed a new Photon OS VM to ESXi 6.5 using both the ISO and the OVA. Immediately upon completion, the first step I attempt to perform is set the network interface to a static IP. Following the documentation, I'm led to install the pmd-cli utility with the following command:

    tdnf install pmd-cli

This installs pmd-cli along with a few other packages, I then attempt to run any command with it, and am met with the following error:

    > pmd-cli net ip4_address --get --interface eth0
    Error (382312602) : Failed to connect to the remote host, reason = rpc_s_no_name_mapping

I'd expect the default behavior to connect locally since no host is specified. I also don't understand why pmd-cli wasn't included in a full ISO install or OVA deployment either, since it's most likely going to be the first tool any administrator needs.

**Comment by suezzelur** [comment]
Do you have pmd.service running?

**Comment by erickrog28** [comment]
you need install package pmd from next command

tdnf install pmd -y in a vm

next start service

systemctl start pmd.service

and finally enable service

systemctl enable pmd.service

  and pmd-cli work fine!!

regards!!
