### ISSUE TITLE
SMB/CIFS versions 2&3 are broken

### ISSUE THREAD

**Issue by bzeidan** [vmware/photon#813]
Recently, I noticed that my CIFS fstab mounts were not working:
```
uname -r
4.9.124-2.ph2-esx
```

```
tdnf list cifs-utils
cifs-utils.x86_64                                                                       6.7-1.ph2                                                @System
cifs-utils.x86_64                                                                       6.7-1.ph2                                                 photon
```

Trying without setting the SMB version:
```
mount -t cifs //<<IP ADD>>/Data /mnt/nas/Data -o credentials=/root/.smb
mount error(95): Operation not supported
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)

```
(dmesg output):
```
[ 4259.801934] 0000 4500 53ff 424d 0072 0000 0000 c801  ...E.SMBr.......
[ 4259.801937] 0000 0000 0000 0000 0000 0000 0000 0a1c  ................
[ 4259.801940] 0000 0001 2200 0200 4d4c 2e31 5832 3030  ....."..LM1.2X00
[ 4259.801942] 0032 4c02 4e41 414d 324e 312e 0200 544e  2..LANMAN2.1..NT
[ 4259.801942] 20 4c 4d 20 30 2e 31 32 00                        LM 0.12.
[ 4259.817471] 0000 2500 53ff 424d 0072 0000 8000 c003  ...%.SMBr.......
[ 4259.817474] 0000 0000 0000 0000 0000 0000 0000 0a1c  ................
[ 4259.817475] 00 00 01 00 01 ff ff 00 00                       .........
[ 4259.817490] 0000 2500 53ff 424d 0072 0000 8000 c003  ...%.SMBr.......
[ 4259.817492] 0000 0000 0000 0000 0000 0000 0000 0a1c  ................
[ 4259.817493] 00 00 01 00 01 ff ff 00 00                       .........
```

Trying to set version to SMB3, says Invalid Argument:
```
mount -t cifs //<<IP ADD>>/Data /mnt/nas/Data -o credentials=/root/.smb,vers=3.0
mount error(22): **Invalid argument**
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
```

**Comment by bzeidan** [comment]
It seems similar to https://github.com/vmware/photon/issues/717
Eventually another kernel update might have affected the CIFS functionality again. (just a supposition)

**Comment by bzeidan** [comment]
After some additional investigation, I realized that CIFS mounting stopped working after I upgraded by FreeNAS server to latest version 11.1-U6. In the latest freenas release, support for SMBv1 was disabled by default, as a security measure. In fact, this broke the Photon SMB connectivity, as I can see Photon was using SMBv1 instead of more advanced and secure SMB 2.x or 3.x. 
As workaround, I enabled SMBv1 on FreeNAS again, and mount from Photon worked again. 
This does not mean that reason for issue is resolved, as Photon is still unable to mount CIFS using SMB v2 or v3.

**Comment by srivatsabhat** [comment]
Which kernel flavor are you running? Can you share the output of `uname -r`?

It looks like SMB2/3 support is disabled in linux-esx kernel. Try using the linux (generic) flavor and see if that works for you. (`tdnf install linux && sync && reboot`)

**Comment by bzeidan** [comment]
Hi Sri, this was actually the first command I shared:
uname -r
4.9.124-2.ph2-esx

This is running on top of ESXi, just to have a few docker containers, so I really wanted to keep it minimalist.

**Comment by srivatsabhat** [comment]
Hi @bzeidan, sorry I missed that. Could you try linux (generic) just to confirm that it works? You can switch back to linux-esx immediately after that for your regular use. If linux works for you, that means there is no other kernel bug to investigate, and I'll be happy to enable SMB2/3 support in linux-esx.

**Comment by bzeidan** [comment]
Hi Sri, I followed your instructions and tried the linux kernel (`tdnf install linux && sync && reboot`)

Result was successful, I managed to mount it with both version on SMB 2.1 and SMB 3.0:
**Testing SMB 2.1**
```
# mount -t cifs //<<IP ADDRESS>>/Backups /mnt/nas/Backups/ -o rw,credentials=/root/.smb,uid=2000,gid=1001,vers=2.1
# mount
<...>
//<<IP ADDRESS>>/Backups on /mnt/nas/Backups type cifs (rw,relatime,vers=2.1,sec=ntlmssp,cache=strict,username=<<user>>,domain=NAS-CENTRAL,uid=2000,forceuid,gid=1001,forcegid,addr=<<IPADDRESS>>,file_mode=0755,dir_mode=0755,nounix,serverino,mapposix,rsize=1048576,wsize=1048576,echo_interval=60,actimeo=1)
```
**Testing SMB 3.0**
```
# umount /mnt/nas/Backups
# mount -t cifs //<<IP ADDRESS>>/Backups /mnt/nas/Backups/ -o rw,credentials=/root/.smb,uid=2000,gid=1001,vers=3.0
# mount
//<<IPADDRESS>>/Backups on /mnt/nas/Backups type cifs (rw,relatime,vers=3.0,sec=ntlmssp,cache=strict,username=<<user>>,domain=NAS-CENTRAL,uid=2000,forceuid,gid=1001,forcegid,addr=<<IPADDRESS>>,file_mode=0755,dir_mode=0755,nounix,serverino,mapposix,rsize=1048576,wsize=1048576,echo_interval=60,actimeo=1)
```

Considering this, it would be possible to enable SMB2/3 support in linux-esx as well?

Thanks a lot for the support.

**Comment by srivatsabhat** [comment]
Hi @bzeidan 

Great! Thanks a lot for verifying with the generic linux kernel. I'm working on enabling SMB2/3 in linux-esx; I'll report back as soon as it is available.

Thank you!

**Comment by bzeidan** [comment]
Hi Sri, sorry, but I have little experience of manipulating which photon
kernel to use:

To move to linux generic kernel, I have used your instructions: (tdnf
install linux && sync && reboot)

What would be the command to revert back to linux-esx kernel? (tdnf install
linux-esx && sync && reboot)??

**Comment by srivatsabhat** [comment]
Hi @bzeidan, Yes, that's the right command. Please give it a try and let me know if it works for you. You may also use --refresh (as in, `tdnf install linux-esx --refresh`) to make sure that tdnf syncs with the upstream repo to fetch the latest available linux-esx rpm.

**Comment by bzeidan** [comment]
Hi Sri, thanks for enabling SMB2/3 support on linux-esx!
I can confirm it is working fine with the new version of the esx kernel. In
order to apply the esx kernel again, I have used (tdnf reinstall linux-esx).

uname -r

4.9.130-3.ph2-esx


mount

//<<IP ADDRESS>>/Pictures on /mnt/nas/Pictures type cifs
(ro,relatime,vers=3.0,sec=ntlmssp,cache=strict,username=<<user>>,domain=<<host>>,uid=2000,forceuid,gid=1001,forcegid,addr=<<IP
ADDRESS>>,file_mode=0755,dir_mode=0755,nounix,serverino,mapposix,rsize=1048576,wsize=1048576,echo_interval=60,actimeo=1)


Many thanks for your support!


Cheers!

**Comment by srivatsabhat** [comment]
Awesome! Thanks a lot for reporting the problem and confirming the fix!

**Comment by antonmatsiuk** [comment]
I hit the same problem with 4.9.210-3.ph2-esx while mounting Azure Files share via CIFS, the same command works fine on CentOS 7.5:
```
mount -v -t cifs //***.file.core.windows.net/***/*** -cifs -o dir_mode=0777,file_mode=0777,username=***,password=***

mount error(11): Resource temporarily unavailable
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
```
