### ISSUE TITLE
Upgrade docker service to 18.x ? getting errors here

### ISSUE THREAD

**Issue by stefangweichinger** [vmware/photon#819]
I have a small docker-compose.yml to deploy php-fpm app using bitnami images (nginx and fpm).
This works great when I run it locally on my Fedora 28 workstation with docker 18.06 but fails when I try to deploy to a Photon OS VM which runs docker 17.0.6

Basically the problem is mounting a local file into the container:

```
volumes:
     - ./nginx/site.conf:/opt/bitnami/nginx/conf/vhosts/my_vhost.conf:ro
```

fails with:

```
web_1     | 
web_1     | INFO  ==> Starting nginx... 
web_1     | 2018/10/15 13:54:43 [crit] 1#0: pread() "/opt/bitnami/nginx/conf/vhosts/my_vhost.conf" failed (21: Is a directory)
web_1     | nginx: [crit] pread() "/opt/bitnami/nginx/conf/vhosts/my_vhost.conf" failed (21: Is a directory)
```

My tests and researches show that 17.x might have a bug, similar Issues at the bitnami-php-fpm github issue tracker were solved by upgrading docker.

pls provide 18.0.6 or so / or point me at how to upgrade my VM ...

EDIT: before you ask: same/similar issues with other images as well. Not only with bitnami/nginx!

**Comment by stefangweichinger** [comment]
updated my Photon server VM as mentioned in #723 (thanks!) ... same issue.

**Comment by stefangweichinger** [comment]
@cblomart thanks for your feedback, but I have (a) upgraded to docker-18.0.6 or so within that Photon-VM a while ago and (b) also tested my docker-compose.yml against a Debian host (with docker-18.x as well). So the issue is not related to docker-17.x IMO.

**Comment by cblomart** [comment]
I shall then open another issue. The point was that sources still installs 17.06 which is not supported by docker (https://github.com/vmware/photon/blob/master/SPECS/docker/docker.spec)

**Comment by stefangweichinger** [comment]
@cblomart Is your issue related to bitnami/nginx? For reference here my related issue there:

https://github.com/bitnami/bitnami-docker-nginx/issues/108

**Comment by YustasSwamp** [comment]
We updated docker to 18.06.
Is the issue still here?

**Comment by stefangweichinger** [comment]
after all the months I can't tell anymore, since I had to quickly find a solution ... Not relevant anymore.
