### ISSUE TITLE
docker is not running out of the box

### ISSUE THREAD

**Issue by veto64** [vmware/photon#821]
- we install photon os
- after i installed docker with tdf install docker
- than i run the test docker:  docker run hello-world
# docker run hello-world
docker: Error response from daemon: failed to create endpoint gracious_hodgkin on network bridge: failed to add the host (veth8042e35) <=> sandbox (veth5e81561) pair interfaces: operation not supported.

**Comment by suezzelur** [comment]
start docker service manually after installing using `systemctl start docker`
