### ISSUE TITLE
Package request: GNU Emacs

### ISSUE THREAD

**Issue by veto64** [vmware/photon#823]
just testing photon,
i can find nano, vi etc but no emacs.
please add this to your repository
thanks
Package request: GNU Emacs

**Comment by ssahani** [comment]
yeah I miss it too. I am going to work on this.

**Comment by ashwinstar** [comment]
Please add it, seems must for developers on Greenplum team. We are just starting to play with Photon and having Emacs would make the rid smooth :-)

**Comment by ssahani** [comment]
We added it to dev recently https://github.com/vmware/photon/blob/master/SPECS/emacs/emacs.spec. Will open a PR for 3.0.

**Comment by ssahani** [comment]
closing as https://github.com/vmware/photon/commit/62375536717339b088d45dc989d335132b8809ff is merged.
