### ISSUE TITLE
Docker 17.06 not supported by docker/moby

### ISSUE THREAD

**Issue by cblomart** [vmware/photon#824]
sources still installs 17.06 which is not supported by docker (https://github.com/vmware/photon/blob/master/SPECS/docker/docker.spec)

Had some issues with docker and opened a issue with docker/moby (moby/moby#37881)

The installed version of docker in photon os 2 is not supported by docker/moby anymore:
" Note that Docker 17.06 CE has reached end of life in september 2017, and has no longer been maintained since"

**Comment by DRoet** [comment]
FYI latest docker version on photon 2/3 is now 18.06.1
