### ISSUE TITLE
Chromium builds are failed to run

### ISSUE THREAD

**Issue by SergioFalcone** [vmware/photon#825]
Hi,

I'm stuck with the process of creating a headless chrome installation on Photon 1 or 2. The problem arise when the binary (I was able to build it from Chromium sources) wants to reach out one of the hundreds of its dependencies. Neigther tdnf nor yum cannot find the corresponding CentOS, Fedora or Red Hat package names in their repos. So I've been bound to build the required libs from sources. Unfortunately not all deps could be easily found.
 So this is the story but the question is how the docker image

 justinribeiro/chrome-headless

 is running without a problem? I was looking into its dockerfile and observed:

apt-get update && apt-get install -y \
	apt-transport-https \
	ca-certificates \
	curl \
	gnupg \
	--no-install-recommends \
	&& curl -sSL https://dl.google.com/linux/linux_signing_key.pub | apt-key add - \
	&& echo "deb https://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list \
	&& apt-get update && apt-get install -y \
	google-chrome-stable \
	**fontconfig** \
	**fonts-ipafont-gothic** \
	**fonts-wqy-zenhei** \
	**fonts-thai-tlwg** \
	**fonts-kacst** \
	**fonts-symbola** \
	**fonts-noto** \
	**ttf-freefont** \
	--no-install-recommends \
	&& apt-get purge --auto-remove -y curl gnupg \
	&& rm -rf /var/lib/apt/lists/*

Could someone help me with the bold out packages? I suspect they could be found from the https://www.google.com/linuxrepositories/.

Thanks,
Sergio

**Comment by kganugapati** [comment]
Awesome, really interested in this.  Do you possibly know what the list of packages needed are? I'd like to add this to the vivace repository so that we can compile  Chromium for  Photon 3.0 on bpth x64 and the RPI3 . Could you please provide the listing of all packages?

**Comment by kganugapati** [comment]
Also did you use  1.0 or 2.0 - I'm going to try porting Chromium on to 2.0

**Comment by SergioFalcone** [comment]
I was using Photon 1.0, also please note, that the result buld is just a headless-shell.
I will refine the steps and post here. But actually what I'm sure is required is a manual build for fresher gzip (1.9), and libpango with:
`yum install pango.x86_64 -y`

..will come up with ultimate steps list

**Comment by usemat** [comment]
Please try the steps below and give a feedback on the packages versions and installation correctness. Note, that the system requirements are 100Gb free space. Build runs longer on my VM but you may try to speedup it with a different options.

There are the steps I had so far (start with root user):

tdnf install yum

// I had installed gzip 1.9
mkdir gzip
cd gzip
wget https://ftp.gnu.org/gnu/gzip/gzip-1.9.tar.xz
tar xvf gzip-1.9.tar.xz
cd gzip-1.9/
./configure
make & make install

yum install pango.x86_64 -y
  
yum install http://avi.alkalay.net/software/webcore-fonts/webcore-fonts-3.0-1.noarch.rpm

useradd -m admin
passwd admin
su admin

git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git

export PATH="$PATH:${HOME}/depot_tools"
export PATH="$PATH:/usr/local/bin"

mkdir ~/chromium && cd ~/chromium
fetch --nohooks chromium
gclient sync
cd ~/chromium/src

gclient runhooks

mkdir -p out/Debug
echo 'import("//build/args/headless.gn")' > out/Debug/args.gn
gn gen out/Debug

use_jumbo_build=true
symbol_level=0
remove_webcore_debug_symbols=true
enable_nacl=false
linux_use_bundled_binutils=false
use_debug_fission=false
is_clang=false

ninja -C out/Debug headless_shell

cd ./out/Debug
./headless_shell --disable-gpu --remote-debugging-port=9222 --user-data-dir=/home/admin



Last line should start the headless chrome. Also please see the instructions here:
https://github.com/chromium/chromium/tree/0919936b300874925621c3280be0746fabbc39a1/headless
