### ISSUE TITLE
Photon Os 2.0 - auditd - cannot open netlink audit socket

### ISSUE THREAD

**Issue by lanyi-jozsef** [vmware/photon#826]
The photon OS 2.0 is installed serveral vmWhare machine, but fot the last is got  error, when i start auditd service. 

Error:
- cannot start auditd or use it

System info - cat /etc/*-release
```
 DISTRIB_ID="VMware Photon OS"
 DISTRIB_RELEASE="2.0"
 DISTRIB_CODENAME=Photon
 DISTRIB_DESCRIPTION="VMware Photon OS 2.0"
 NAME="VMware Photon OS"
 VERSION="2.0"
 ID=photon
 VERSION_ID=2.0
 PRETTY_NAME="VMware Photon OS/Linux"
 ANSI_COLOR="1;34"
 HOME_URL="https://vmware.github.io/photon/"
 BUG_REPORT_URL="https://github.com/vmware/photon/issues"
 VMware Photon OS 2.0
 PHOTON_BUILD_NUMBER=304b817

```

Error message:

```
auditctl -v:
Error - audit support not in kernel
Cannot open netlink audit socket

systemd log:
nov 05 11:24:50 .... auditd[11672]: Error - audit support not in kernel
nov 05 11:24:50 .... auditd[11672]: Cannot open netlink audit socket

```

**Comment by srivatsabhat** [comment]
I'm assuming that you are using the linux-esx kernel. Audit support was added to linux-esx in version 4.9.66-2. So please upgrade your kernel and let us know if it still doesn't work.

To update your entire distro to the latest available versions of all packages, run `tdnf distro-sync --refresh` (and then reboot, to account for kernel updates). Instead, if you want to update only your kernel, run `tdnf update linux-esx` and then reboot your machine.

**Comment by lanyi-jozsef** [comment]
thank, its worked.

**Comment by srivatsabhat** [comment]
Thank you for confirming!
