### ISSUE TITLE
Creating a Startup Srevice (Documentation) 

### ISSUE THREAD

**Issue by dropshoty** [vmware/photon#827]
Creating a Startup Service documentation

https://github.com/vmware/photon/blob/master/docs/photon-admin-guide.md

Currently Reads  - 

[Service]
ExecStart=/bin/ifconfig eth0 mtu 1460 up
Type=oneshot

I'm on verison 2.0 - and Ifconfig inst located in /bin

- For version Photon version 2  this worked
ExecStart=/usr/sbin/ifconfig eth0 mtu 1460 up

**Comment by vidya-v** [comment]
http://photon-jenkins.eng.vmware.com:8082/#/c/6376/

**Comment by YustasSwamp** [comment]
It is incorrect way of setting MTU. Use systemd-networkd features instead.
https://www.freedesktop.org/software/systemd/man/systemd.network.html

**Comment by ssahani** [comment]
yes https://www.freedesktop.org/software/systemd/man/systemd.network.html#MTUBytes=. I think we can close this.
