### ISSUE TITLE
Secure boot error after updating to kernel linux-4.9.137-1.ph2

### ISSUE THREAD

**Issue by leander091** [vmware/photon#829]
Hello,

After updating my 2.0 image with the latest update the machine won't boot anymore. 
I'm receiving an error related to the signing status of the kernel or bootloader. 

I could solve this by disabling secure boot but I rather prefer to leave it enabled.

Could the required files be signed again?

Thanks in advance

**Comment by YustasSwamp** [comment]
Thanks for reporting.  Trying to reproduce it.

**Comment by smaliakkal** [comment]
we identified the issue and fixed the signature. Bintray repository for 2.0 is refreshed with fixed rpms. 
Could you retry now ?

**Comment by leander091** [comment]
The issue is solved. Thanks for the quick fix guys.
