### ISSUE TITLE
Was trying to compile 64 bit photon on 32 bit ubuntu ? Encountered the following error?

### ISSUE THREAD

**Issue by anirudhvyas21** [vmware/photon#83]
build-nspr: Building
        Clean build directory: ^[[1;32mSUCCESS^[[0;39m
        Change directory: BUILD: ^[[1;32mSUCCESS^[[0;39m
        Unpacking: nspr-4.10.3: ^[[1;32mSUCCESS^[[0;39m
        Change directory: nspr-4.10.3: ^[[1;32mSUCCESS^[[0;39m
        Configure: ^[[1;32mSUCCESS^[[0;39m
        Make: ^[[1;32mSUCCESS^[[0;39m
        Install: ^[[1;32mSUCCESS^[[0;39m
        Restore directory: ^[[1;32mSUCCESS^[[0;39m
        Restore directory: ^[[1;32mSUCCESS^[[0;39m
build-nss: Building
        Clean build directory: ^[[1;32mSUCCESS^[[0;39m
        Change directory: BUILD: ^[[1;32mSUCCESS^[[0;39m
        Unpacking: nss-3.15.4: ^[[1;32mSUCCESS^[[0;39m
        Change directory: nss-3.15.4: ^[[1;32mSUCCESS^[[0;39m
        Patch: ^[[1;32mSUCCESS^[[0;39m
        Make: ^[[1;31mFAILURE^[[0;39m
or please provide a guide to convert it to 32 bit using the python scripted make file?

**Comment by toliaqat** [comment]
Hi @anirudhvyas21,

We are not supporting 32 bit build at the moment. If you somehow able to build 32bit Photon then we would be happy to have your fixes.
Closing this issue for now.

Thanks,
Touseef
