### ISSUE TITLE
Set static IP address from kickstart.json

### ISSUE THREAD

**Issue by dkirrane** [vmware/photon#830]
I'm trying to automate the Install. How can I set the following from the `kickstart.json`

- static IP address
- netmask
- gateway
- dns
- open-vm-tools
- Timezone/Language settings

**Comment by YustasSwamp** [comment]
Just implemented))

1-4: use "network" option https://github.com/vmware/photon/blob/master/installer/ks_config.txt#L138
5: use "additional_packages" or "packages" 
6: use "postinstall" script for additional post install configuration.

**Comment by jzhang2018** [comment]
I understand this is closed and the feature is baked in the new release. I am using Packer 1.5.5, vsphere-iso 2.3 and Photon 3GA. I have network section in ks json file. But it does not seems working. The ipv4 ip address is not set, only ipv6 ip. What version of code you have this new feature?
