### ISSUE TITLE
tdnf installs one packet at a time, but not all

### ISSUE THREAD

**Issue by hanscees** [vmware/photon#832]
Hi,

if I do 
tdnf update bash this runs fine:

Upgrading:
bash                                 x86_64             4.4.12-3.ph2             photon-updates       3.02M 3161863

Total installed size:   3.02M 3161863
Is this ok [y/N]:y

Downloading:
bash                                   1037936    100%
Testing transaction
Running transaction
Installing/Updating: bash-4.4.12-3.ph2.x86_64
Removing: bash-4.4-6.ph2.x86_64

Complete!

if I do
/usr/bin/tdnf distro-sync

I get a long list, type yes and then:

Downloading:
Error(1471) : rpm generic error - not found

Any ideas?

**Comment by suezzelur** [comment]
Do you know what rpm is causing this error? maybe use --rpmverbosity debug in the tdnf distro-sync command

**Comment by hanscees** [comment]
yep

root@unbound [ ~ ]# /usr/bin/tdnf distro-sync

Installing:
file-libs                x86_64       5.30-4.ph2       photon-updates   4.80M 5031576

Total installed size:   4.80M 5031576

Upgrading:
file                     x86_64       5.30-4.ph2       photon-updates  38.16k 39079

Total installed size:  38.16k 39079
Is this ok [y/N]:y

Downloading:
Error(1471) : rpm generic error - not found

**Comment by hanscees** [comment]
> Do you know what rpm is causing this error? maybe use --rpmverbosity debug in the tdnf distro-sync command

debug gives little more information I am afraid:

Total installed size:  38.16k 39079
Is this ok [y/N]:y

Downloading:
fdio:       1 reads,        0 total bytes in 0.000001 secs
Error(1471) : rpm generic error - not found

**Comment by YustasSwamp** [comment]
It might be bintray issue.
Is issue still here?

**Comment by CollinChaffin** [comment]
I just started also getting this generic error as of updates yesterday.

**Comment by YustasSwamp** [comment]
Thanks for the update!

**Comment by matveyrv** [comment]
> 
> 
> EDIT: Solved. Apparently the `tdnf clean all` does absolutely NOTHING to the `/var/cache/tdnf` as far as downloaded RPMs....which I would think is one of only a very small handful of reasons you'd want to clean the cache to begin with. Looking there, I found several ZERO-BYTE rpms of the updates, which obviously were continually being seen as usable/downloaded so tdnf refused to ever re-download even after the clean all command.
> 
> The solution for anyone else having these issues might be to simply delete THE CONTENTS OF (NOT THE DIRECTORY ITSELF) of `/var/cache/tdnf` and immediately executing `tdnf makecache`. After that is successful, running the tdnf update related all worked fine and the 1471 rpm error was eliminated for me.

Collin, Thank for your advice. This workaround solve the problem
