### ISSUE TITLE
Basic system packages should include manpage by default

### ISSUE THREAD

**Issue by yilmi-vmw** [vmware/photon#833]
Hi Team,

Not having man pages on the system makes it difficult to work on a Photon deployment terminal without having to switch back to a browser when we need to check something.

At least we should include man pages for the default packages, the overhead in disk space can't be that much, for instance a man page for tdnf seems like the bare minimum (for instance to tell the difference between `tdnf update` and `tdnf distro-sync`?)

Thanks
Yassine

**Comment by YustasSwamp** [comment]
man tool (+deps) itself is heavy. But you can always install it.
`tdnf install man-db`
Thanks
