### ISSUE TITLE
gawk missing from 3.0RC minimal build

### ISSUE THREAD

**Issue by Rob-Wal** [vmware/photon#835]
gawk is missing from the minimal build.  It is needed to use TAB completion with docker commands. For us lazy or shorthand typers, when running a docker command and using tab key in the command name or image name it errors out with awk not found.

example - hitting tab after run:
`root@Photon3rc [ ~ ]# docker run -bash: awk: command not found`

fix:
`tdnf install -y gawk`

#example - hitting tab after run with gawk installed and only hello-world:
`root@Photon3-Docker02 [ ~ ]# docker run hello-world`

**Comment by YustasSwamp** [comment]
proper fix is: docker should have "requires gawk" since its bash_completion file uses it.

**Comment by RobTiki** [comment]
> proper fix is: docker should have "requires gawk" since its bash_completion file uses it.

@YustasSwamp 
I am going to assume that @ganboing will take care of this and I do not need to cross post this issue to the docker-ce repo?  

I am a sys engineer/admin but a curious one.  How do the devs get the requirements for the SPEC files?  I do not see any requirements listed over on the docker-ce repos.

**Comment by YustasSwamp** [comment]
Working on the fix
