### ISSUE TITLE
Cannot install cmake on 3.0RC

### ISSUE THREAD

**Issue by SteveOss** [vmware/photon#836]
Trying to install cmake:

# tdnf install cmake
Found 1 problem(s) while resolving
1. package cmake-3.12.1-3.ph3.x86_64 requires bzip2, but none of the providers can be installed

So tried to install bzip2:

tdnf install bzip2
Found 1 problem(s) while resolving
1. package bzip2-1.0.6-9.ph3.x86_64 conflicts with toybox provided by toybox-0.7.7-1.ph3.x86_64

Looks like toybox is preventing installation of bzip2 as it implements bunzip2 but not bzip2.

**Comment by YustasSwamp** [comment]
Remove toybox first. It will bring in all alternatives including bzip2.

**Comment by SteveOss** [comment]
@YustasSwamp This fixed the problem thanks.
