### ISSUE TITLE
CIFS bugs again

### ISSUE THREAD

**Issue by herouxb** [vmware/photon#837]
Hi, i am trying to use cifs it is broken again like #717 and #813 ?

Using CIFS 1-2-3 i always have:

mount error(95): Operation not supported
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)

I did try both kernel, same:
4.19.6-1.ph3
4.19.6-1.ph3-esx

**Comment by srivatsabhat** [comment]
Hi @herouxb 

I'm unable to reproduce the problem on my end (I'm able to mount SMB shares successfully in Photon OS 3.0). Can you please share your exact command line and output from dmesg?

**Comment by herouxb** [comment]
Hi, thanks for the follow up, the command i use is: 
mount -v -t cifs //IP/Movies /share/Movies/ -o credentials=/etc/.passwords

The content of the .passwords is:
username=myuser
password=mypassword

thanks for your help !

**Comment by srivatsabhat** [comment]
Great, thank you for the info! We have disabled support for legacy SMB dialects such as vers=1.0 and 2.0 in Photon OS 3.0, because they offer weaker security guarantees as compared to modern SMB dialects such as 2.1 and above . So, can you try with vers=2.1 or 3.0 and see if that works?

**Comment by herouxb** [comment]
I did try that and it didn't work, so i went to see the SMB config on the server (Synology NAS), and i was version 1 minimum to version 2 maximum (on advanced settings), so i put version 3 maximum and now it is working with vers=2.1 and vers=3.  

Too bad then for version 1.0, as long as it work and it does now... thanks for helping me figure this out.  Thanks for your time !

**Comment by srivatsabhat** [comment]
No problem! I'm glad to hear that it works for you now. Thank you!

**Comment by fishslapman** [comment]
Is there a solution to this for those of us running older an NAS where SMB ver1.0 is the only option?
