### ISSUE TITLE
Docker upgrades in Photon 3.0

### ISSUE THREAD

**Issue by DRoet** [vmware/photon#839]
Hi,

Can we expect more frequent docker updates in photon os 3.0? 2.0 was stuck on `17.06` for quite awhile...
I noticed the addition of `18.06` in https://github.com/vmware/photon/commit/287f6aa73b48acba9a977249b25a20c95c5d85e4 but the latest docker release is already `18.09.1` so I was just wondering if 3.0 will allow for quicker updates in the future.

thanks,

Daan

**Comment by BoxedBrain** [comment]
@DRoet could you tell me how you did the upgrade? Here is what I have tried so far:

> root@HOST01 [ ~ ]# **tdnf clean all**
> Cleaning repos: photon photon-extras photon-updates
> Cleaning up everything
> root@HOST01 [ ~ ]# **docker -v**
> Docker version 17.06.0-ce, build 02c1d87
> root@HOST01 [ ~ ]# **tdnf upgrade docker**
> Nothing to do.                         3324462    100%
> root@HOST01 [ ~ ]# **docker -v**
> Docker version 17.06.0-ce, build 02c1d87
> root@HOST01 [ ~ ]# **tdnf info docker**
> Name          : docker
> Arch          : x86_64
> Epoch         : 0
> Version       : 17.06.0
> Release       : 7.ph3
> Install Size  :  91.52M 95968263 (95968263)
> Repo          : @System
> Summary       : Docker
> URL           : http://docs.docker.com
> License       : ASL 2.0
> Description   : Docker is a platform for developers and sysadmins to develop, ship and run applications.
> 
> Name          : docker
> Arch          : x86_64
> Epoch         : 0
> Version       : 17.06.0
> Release       : 7.ph3
> Install Size  :  91.52M 95967703 (95967703)
> Repo          : photon
> Summary       : Docker
> URL           : http://docs.docker.com
> License       : ASL 2.0
> Description   : Docker is a platform for developers and sysadmins to develop, ship and run applications.
> 
> 
> Total Size: 183.04M 191935966 (191935966)

**Comment by DRoet** [comment]
@BoxedBrain are you already using Photon 3? I haven't tried it out yet, like I said I just found the `18.06` upgrade in the `dev` branch (which is photon 3 only, I assume).

Photon 3 is still in RC so I'm personally waiting till it hits GA

**Comment by RobTiki** [comment]
I have been running photon3 since beta and been running the RC since release.  Its still on 17.0.6.  Today I updated photon2 and its now running 18, but I ran into [rdrand Issue](https://github.com/vmware/photon/issues/774)

```
root@Photon3-Docker01 [ ~ ]# rpm -qi photon-release
Name        : photon-release
Version     : 3.0
Release     : 2.ph3
Architecture: noarch
Install Date: Fri 14 Dec 2018 05:23:49 PM EST
Group       : System Environment/Base
Size        : 483
License     : Apache License
Signature   : RSA/SHA1, Fri 14 Dec 2018 02:47:19 PM EST, Key ID c0b5e0ab66fd4949
Source RPM  : photon-release-3.0-2.ph3.src.rpm
Build Date  : Thu 13 Dec 2018 07:50:14 PM EST
Build Host  : photon-fb62ca8ba279
Relocations : (not relocatable)
Vendor      : VMware, Inc.
URL         : https://vmware.github.io/photon/
Summary     : Photon release files
Description :
Photon release files such as yum configs and other /etc/ release related files
root@Photon3-Docker01 [ ~ ]# docker -v
Docker version 17.06.0-ce, build 02c1d87
root@Photon3-Docker01 [ ~ ]# docker info
Containers: 5
 Running: 1
 Paused: 0
 Stopped: 4
Images: 12
Server Version: 17.06.0-ce
```
```
root@photon-machine [ ~ ]# rpm -qi photon-release
Name        : photon-release
Version     : 2.0
Release     : 2.ph2
Architecture: noarch
Install Date: Thu 24 Jan 2019 11:25:31 PM UTC
Group       : System Environment/Base
Size        : 483
License     : Apache License
Signature   : RSA/SHA1, Fri 14 Sep 2018 05:45:50 AM UTC, Key ID c0b5e0ab66fd4949
Source RPM  : photon-release-2.0-2.ph2.src.rpm
Build Date  : Thu 13 Sep 2018 10:50:46 PM UTC
Build Host  : photon-fb62ca8ba279
Relocations : (not relocatable)
Vendor      : VMware, Inc.
URL         : https://vmware.github.io/photon/
Summary     : Photon release files
Description :
Photon release files such as yum configs and other /etc/ release related files
root@photon-machine [ ~ ]#
root@photon-machine [ ~ ]# docker -v
Docker version 18.06.1, build e68fc7a

```
Now looking for a way to deploy vagrant in docker so I could try building the recent releases of 2.0.  Down the Rabbit hole.

**Comment by CondormanFr** [comment]
> I was able to upgrade to `18.06` without any issues. 


How to you upgrade docker ?
tdnf update docker or tdnf upgrade docker answers : nothing to do ...
But `tdnf info docker `returns
```
Name          : docker
Arch          : x86_64
Epoch         : 0
Version       : 18.06.1
Release       : 1.ph2
Install Size  : 189.23M 198417948 (198417948)
Repo          : @System
Summary       : Docker
URL           : http://docs.docker.com
License       : ASL 2.0
Description   : Docker is an open source project to build, ship and run any application as a lightweight container.

```

**Comment by jodumont** [comment]
Hi @CondormanFr;

as @DRoet mentioned
if you are using Photon 3.0

you simply have to do an update

![image](https://user-images.githubusercontent.com/5204724/53494562-58c41500-3a9e-11e9-8a0c-e5e134ea43ba.png)

but as your Release info suggest you are using Photon 2.0

**Comment by RobTiki** [comment]
@CondormanFr at the time of my post version 18.06.1 was the latest.  Thats the same version you had.

I switched my container hosts to centos minimal.  I just created a vm template and started using the latest stable repo from docker.  That way I was able to update to the 18.09.2 as soon as the runc cve was address.

I still love photon and hope it continues to grow.

**Comment by jodumont** [comment]
After receiving a few time the message "Waiting for contributors!" in different issues I followed, it gave me the impression of a overwhelm team.

as like @RobTiki; I still love photon and hope a great future; but I also decide to move back to Debian.

**Comment by CollinChaffin** [comment]
99.9% of folks I would bet are using this distro for one thing - Docker.  Why on earth is every single version of Docker, down to nightlies not being built on Photon DEV repo?

It's just a bit absurd there is such a nice SPEC workflow clearly in place to produce the RPMs for Docker, yet we are all having to erase and abandon Docker via package manager and perform shell script installs instead when we can simply use just about any other distro and have a far easier time with Docker updates.

If it's really a bandwidth issue (how many new builds of Docker are released daily?) then would it be possible to have some details better documented on compiling the SPEC files required for us to contribute the PRs to assist in providing those new Docker builds?

**Comment by ppadmavilasom** [comment]
https://vmware.github.io/photon/assets/files/html/1.0-2.0/build-photon.html

**Comment by DRoet** [comment]
I was hoping to see more frequent docker upgrades in Photon 3.0, but we are still on `18.06.x` whilst `18.09.x` and `19.03.x` have been out for a while 😞

**Comment by LoudSoftware** [comment]
Same here, there's a bug in 18.06 [(Issue)](https://github.com/moby/moby/issues/37581) that was fixed in 18.09. Would love to see new docker versions built for photon 3.

**Comment by YustasSwamp** [comment]
Photon 3.0 has docker 18.06 and 18.9 now: https://github.com/vmware/photon/tree/3.0/SPECS/docker

**Comment by thej4ck** [comment]
how about 19.x ?
