### ISSUE TITLE
PhotonOS 3.0 (aarch64) Extra & Updates Repo fail

### ISSUE THREAD

**Issue by lamw** [vmware/photon#840]
It looks like the PhotonOS 3.0 ARM64 Extra & Updates repo aren't valid ... 

This is what happens when I run an update after installing PhotonOS 3.0 RC on rPI

```
root@photon-machine [ ~ ]# tdnf -y update
Refreshing metadata for: 'VMware Photon Extras 3.0(aarch64)'
Error: 404 when downloading https://dl.bintray.com/vmware/photon_extras_3.0_aarch64/repodata/repomd.xml
. Please check repo url.
Error: Failed to synchronize cache for repo 'VMware Photon Extras 3.0(aarch64)' from 'https://dl.bintray.com/vmware/photon_extras_3.0_aarch64'
Disabling Repo: 'VMware Photon Extras 3.0(aarch64)'
Refreshing metadata for: 'VMware Photon Linux 3.0(aarch64)'
Refreshing metadata for: 'VMware Photon Linux 3.0(aarch64) Updates'
Error: 404 when downloading https://dl.bintray.com/vmware/photon_updates_3.0_aarch64/repodata/repomd.xml
. Please check repo url.
Error: Failed to synchronize cache for repo 'VMware Photon Linux 3.0(aarch64) Updates' from 'https://dl.bintray.com/vmware/photon_updates_3.0_aarch64'
Disabling Repo: 'VMware Photon Linux 3.0(aarch64) Updates'
```

**Comment by YustasSwamp** [comment]
Hi William,

It is will be available after GA, as part of packages update process.
For now, there is only main (release) repo. (photon.repo file)

Thanks,
--Alexey

**Comment by nfrush** [comment]
@YustasSwamp When do you expect 3.0 to hit GA?

**Comment by smaliakkal** [comment]
@lamw  These repos are online now . Could you check now ?

**Comment by lamw** [comment]
Verified

**Comment by yourprince9429** [comment]
Refreshing metadata for: 'VMware Photon Extras 3.0 (aarch64)'
curl#6: Couldn't resolve host name
Error(1207) : Unknown error
Error: Failed to synchronize cache for repo 'VMware Photon Extras 3.0 (aarch64)' from 'https://packages.vmware.com/photon/3.0/photon_extras_3.0_aarch64'
Disabling Repo: 'VMware Photon Extras 3.0 (aarch64)'
Refreshing metadata for: 'VMware Photon Linux 3.0 (aarch64) Updates'
curl#6: Couldn't resolve host name
Error(1207) : Unknown error
Error: Failed to synchronize cache for repo 'VMware Photon Linux 3.0 (aarch64) Updates' from 'https://packages.vmware.com/photon/3.0/photon_updates_3.0_aarch64'
Disabling Repo: 'VMware Photon Linux 3.0 (aarch64) Updates'
Refreshing metadata for: 'VMware Photon Linux 3.0 (aarch64)'
curl#6: Couldn't resolve host name
Error(1207) : Unknown error
Error: Failed to synchronize cache for repo 'VMware Photon Linux 3.0 (aarch64)' from 'https://packages.vmware.com/photon/3.0/photon_release_3.0_aarch64'
Disabling Repo: 'VMware Photon Linux 3.0 (aarch64)'
Nothing to do.
