### ISSUE TITLE
Photon 2.0 takes near 15 minutes on Hyper-V

### ISSUE THREAD

**Issue by krishgan** [vmware/photon#845]
Hi all, Photon 2.0 takes near 15 minutes to come up on Hyper-V :-) Hope you are testing on Hyper-V :-)

**Comment by RobTiki** [comment]
Same issue on esxi, with the latest 2.0.  Caused by CPU support of rng.  There is a workaround for it.  See if this works: [link](https://github.com/vmware/photon/issues/774#issuecomment-388202358)

**Comment by srivatsabhat** [comment]
@krishgan An upstream kernel fix to the random subsystem which was included in linux-stable 4.9.97 slowed down booting, especially in virtualized environments where there is a scarcity of entropy during early boot. There are 2 alternatives available in Photon 2.0 to solve this problem:

1. If your CPU supports the RDRAND instruction, then you can use any Photon kernel with version >= 4.9.109-2 and systemd >= 233-14. This automatically loads a kernel driver (rdrand-rng) during boot to feed the kernel's entropy pool using RDRAND.

2. If your CPU doesn't support RDRAND, install haveged or rng-tools package (minimum versions: haveged-1.9.1-4, rng-tools-5-2). Either of those packages will supply additional entropy from userspace, solving the slow boot issue.

If none of these solutions work, please let us know!
