### ISSUE TITLE
How to detect Photon OS remount file system to read-only?

### ISSUE THREAD

**Issue by xinjiandong** [vmware/photon#846]
Hi,  
   We met one some issues that vm has  a VSAN storage issue, can ping this vm but can't ssh to it until power cycle, we suspect if OS remounts a filesystem as read-only on certain storage errors to prevent data corruption.
   So if Photon OS has a mechanism to check this case happened(remount to read-only file system)  w/o knowing the guest OS credentials, but having vCenter credentials?

thanks,
Jiandong

**Comment by YustasSwamp** [comment]
Are you VC developer? If so, contact me internally.

**Comment by YustasSwamp** [comment]
didn't get back for 1 year, closing the bug
