### ISSUE TITLE
Photon repo disabled

### ISSUE THREAD

**Issue by chipzoller** [vmware/photon#849]
Why is the repo failing to sync?

`root@photonos [ /tmp ]# tdnf clean all
Error: Failed to synchronize cache for repo 'VMware Photon Linux 3.0(x86_64)' from 'https://dl.bintray.com/vmware/photon_release_3.0_x86_64'
Disabling Repo: 'VMware Photon Linux 3.0(x86_64)'
Cleaning repos: photon-updates photon-extras
Cleaning up everything
root@photonos [ /tmp ]# tdnf install python2
Error: Failed to synchronize cache for repo 'VMware Photon Linux 3.0(x86_64)' from 'https://dl.bintray.com/vmware/photon_release_3.0_x86_64'
Disabling Repo: 'VMware Photon Linux 3.0(x86_64)'
No package python2 available               106    100%
Error(1011) : No matching packages`

**Comment by A9G-Data-Droid** [comment]
The download links are similarly dead:
https://github.com/vmware/photon/wiki/Downloading-Photon-OS

EXAMPLE:
http://dl.bintray.com/vmware/photon/3.0/GA/ova/photon-hw13_uefi-3.0-26156e2.ova

**Comment by chipzoller** [comment]
Odd. They were working as of yesterday.

**Comment by suezzelur** [comment]
The repos should be active now, can you check?

**Comment by chipzoller** [comment]
Synchronization is still failing for VMware Photon Linux 3.0(x86_64).

**Comment by smaliakkal** [comment]
@chipzoller , this repo is active.

if you see the error again  

Could you check after "tdnf makecache"

**Comment by chipzoller** [comment]
Thank you, `tdnf makecache` seemed to fix the dead repo issue.

**Comment by A9G-Data-Droid** [comment]
The download link I'm trying to get is still "File not found". Should I open a new issue for that? (I thought they were related)

**Comment by chipzoller** [comment]
It seems like it's up but is, for some odd reason, now requiring BinTray authentication to allow downloading. This is a new change as of a few days ago wasn't behaving this way.

**Comment by smaliakkal** [comment]
3.0 GA rpm repos and artifacts are public now. Could you check now ?

**Comment by A9G-Data-Droid** [comment]
Thanks. I am downloading now.

**Comment by chipzoller** [comment]
Download is good. Do we have access to a change log between RC and GA versions?

**Comment by vzovko** [comment]
On a Raspberry Pi 3 with the 3.0 GA release there is a quite similar issue with the repos:

```
root@photon-rpi3 [ /etc/yum.repos.d ]# tdnf repolist
Refreshing metadata for: 'VMware Photon Linux 3.0(aarch64) Updates'
Error: 404 when downloading https://dl.bintray.com/vmware/photon_updates_3.0_aarch64/repodata/repomd.xml
. Please check repo url.
Error: Failed to synchronize cache for repo 'VMware Photon Linux 3.0(aarch64) Updates' from 'https://dl.bintray.com/vmware/photon_updates_3.0_aarch64'
Disabling Repo: 'VMware Photon Linux 3.0(aarch64) Updates'
Refreshing metadata for: 'VMware Photon Extras 3.0(aarch64)'
Error: 404 when downloading https://dl.bintray.com/vmware/photon_extras_3.0_aarch64/repodata/repomd.xml
. Please check repo url.
Error: Failed to synchronize cache for repo 'VMware Photon Extras 3.0(aarch64)' from 'https://dl.bintray.com/vmware/photon_extras_3.0_aarch64'
Disabling Repo: 'VMware Photon Extras 3.0(aarch64)'
repo id             repo name                               status
photon              VMware Photon Linux 3.0(aarch64)        enabled

```

**Comment by suezzelur** [comment]
This has been taken care of, please reopen if you face the issue again.
