### ISSUE TITLE
ADD <URL> DEST is not unpacking tar.gz in DEST

### ISSUE THREAD

**Issue by riav** [vmware/photon#851]
Hello everyone.
After updating docker to 18.06.1-1.ph2, when running a build I realized that the tar.gz file that is added by the ADD tag is not being decompressed. Something that does not happen if it is already on the local disk.

My scenery:
# uname -r
4.9.140-3.ph2-esx
# cat /etc/photon-release
VMware Photon OS 2.0
PHOTON_BUILD_NUMBER=0922243
# rpm -qa | grep docker
docker-18.06.1-1.ph2.x86_64

Case with error:
FROM centos:7.6.1810
ADD http://ftp.unicamp.br/pub/apache/tomcat/tomcat-9/v9.0.16/bin/apache-tomcat-9.0.16.tar.gz /opt/
RUN ls -la /opt

Case without error:
FROM centos:7.6.1810
ADD apache-tomcat-9.0.16.tar.gz /opt/
RUN ls -la /opt

**Comment by suezzelur** [comment]
This is expected
https://docs.docker.com/v18.03/engine/reference/builder/#add

https://docs.docker.com/engine/reference/builder/#add


If <src> is a local tar archive in a recognized compression format (identity, gzip, bzip2 or xz) then it is unpacked as a directory. Resources from remote URLs are not decompressed.
