### ISSUE TITLE
Why the initrd-switch-root.service cost too much time

### ISSUE THREAD

**Issue by taibai233** [vmware/photon#855]
The initrd-switch-root.service costs 10.640s while others only cost less than 1s.
Is that normal or something wrong?

**Comment by suezzelur** [comment]
Anything from journalctl | grep fsck?

**Comment by taibai233** [comment]
> Anything from journalctl | grep fsck?
Here it is 
![snipaste_2019-02-18_10-02-22](https://user-images.githubusercontent.com/20180572/52923809-886b7280-3364-11e9-866e-b69b80c62a1d.png)

**Comment by YustasSwamp** [comment]
Is it still reproducible?
Can you attach full journalctl output right after boot, please?
And also, what does `systemd-analyze critical-chain` say?

Thanks

**Comment by YustasSwamp** [comment]
No updates, closing the bug.
