### ISSUE TITLE
Vlan Tagging

### ISSUE THREAD

**Issue by PunkSp** [vmware/photon#856]
Couldn´t find any documentation about vlan tagging. How should I do vlan tagging inside photon Os

**Comment by csj-github** [comment]
.1q vlan is a capability provided by the base Linux kernel.  I could see that there is a vlan module already installed.

> /usr/lib/modules/4.19.15-2.ph3/kernel/drivers/net/ipvlan/ipvlan.ko.xz

my guess is 'ip' command should provide you with the capability to do vlan tagging or untagging. something like the following command should work.

> ip link add link eth0 name eth0.100 type vlan id 100

**Comment by PunkSp** [comment]
Thank you! I could find a documentation:
https://www.freedesktop.org/software/systemd/man/systemd-networkd.service.html, same configuration as we do on ArchLInux
