### ISSUE TITLE
Kickstart over http does not work with 3.0GA

### ISSUE THREAD

**Issue by kstaniek** [vmware/photon#862]
Used: https://github.com/vmware/photon-packer-templates

This works fine:
```
packer build -only=vagrant-vmware_desktop -var-file=vars/iso-2.0GA.json packer-photon.json
```

Then added ios-3.0GA.json:
```
$ more vars/iso-3.0GA.json
{
   "product_version" : "3.0GA",
   "iso_sha1sum" : "1c38dd6d00e11d3cbf7768ce93fc3eb8913a9673",
   "iso_file" : "http://dl.bintray.com/vmware/photon/3.0/GA/iso/photon-3.0-26156e2.iso"
}
```

The run:
```
packer build -only=vagrant-vmware_desktop -var-file=vars/iso-3.0GA.json packer-photon.json
```

And the boot stops with the following prompt:
```
root [ /installer ]#
```

<img width="802" alt="image" src="https://user-images.githubusercontent.com/1431706/53303827-50d25e00-386f-11e9-843f-d3057177bda7.png">

**Comment by kstaniek** [comment]
Installer log:
<img width="799" alt="image" src="https://user-images.githubusercontent.com/1431706/53303871-e66ded80-386f-11e9-8185-a9ff25280b0b.png">

**Comment by kstaniek** [comment]
Any update? It's rather easy to reproduce!

**Comment by suezzelur** [comment]
You will need to do a couple of changes for 3.0:
The kernel cmdline will need to append photon.media=cdrom
photon-kickstart.json no longer takes in a "type" : "minimal", instead you will have to provide a json file with the desired install profile, for example:
"packagelist_file": "packages_minimal.json"

`
diff --git a/packer-photon.json b/packer-photon.json
index 9013413..c93b7ad 100644
--- a/packer-photon.json
+++ b/packer-photon.json
@@ -35,7 +35,7 @@
         },
         "boot_command": [
           "<esc><wait>",
-          "vmlinuz initrd=initrd.img root=/dev/ram0 loglevel=3 ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/photon-kickstart.json",
+          "vmlinuz initrd=initrd.img root=/dev/ram0 loglevel=3 ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/photon-kickstart.json photon.media=cdrom",
           "<enter>"
         ]
     },
diff --git a/scripts/photon-kickstart.json b/scripts/photon-kickstart.json
index b1513ab..c876542 100644
--- a/scripts/photon-kickstart.json
+++ b/scripts/photon-kickstart.json
@@ -6,7 +6,7 @@
             "text": "2RQrZ83i79N6szpvZNX6"
         },
     "disk": "/dev/sda",
-    "type": "minimal",
+    "packagelist_file": "packages_minimal.json",
     "postinstall": [
                     "#!/bin/sh",
                     "sed -i 's/PermitRootLogin no/PermitRootLogin yes/g' /etc/ssh/sshd_config",
diff --git a/vars/iso-3.0GA.json b/vars/iso-3.0GA.json
new file mode 100644
index 0000000..663153d
--- /dev/null
+++ b/vars/iso-3.0GA.json
@@ -0,0 +1,5 @@
+{
+   "product_version" : "3.0GA",
+   "iso_sha1sum" : "1c38dd6d00e11d3cbf7768ce93fc3eb8913a9673",
+   "iso_file" : "http://dl.bintray.com/vmware/photon/3.0/GA/iso/photon-3.0-26156e2.iso"
+}
`

**Comment by kstaniek** [comment]
Where can I find those files "packages_minimal.json"?

**Comment by suezzelur** [comment]
https://github.com/vmware/photon/blob/3.0/common/data/packages_minimal.json
minimal is a meta package that brings in a number of default packages - https://github.com/vmware/photon/blob/3.0/SPECS/minimal/minimal.spec

**Comment by kstaniek** [comment]
@suezzelur Anish, thanks for your response. Please update the Admin Guide with the new kickstart file options. I wasted a lot of time before concluded it must be bug/undocumented change.

**Comment by suezzelur** [comment]
@kstaniek [Documentation ](https://vmware.github.io/photon/assets/files/html/3.0/photon_user/kickstart.html)updated
