### ISSUE TITLE
RFC: Change the boot splash screen

### ISSUE THREAD

**Issue by kstaniek** [vmware/photon#864]
Is it possible to change/customize the Photon OS splash screen during boot up?

**Comment by YustasSwamp** [comment]
Yes, it is. Look at /boot/grub/themes/photon/ folder.

**Comment by kstaniek** [comment]
Is that /boot/grub/... or /boot/grub2/.... ?

**Comment by kstaniek** [comment]
/boot/grub/themes/photon/ does the job! Thanks!
