### ISSUE TITLE
IPv6 Stateless Autoconfiguration

### ISSUE THREAD

**Issue by vo243** [vmware/photon#866]
For the life of me I can't figure out how to get my test lab photon os 3.0 install to pull a stateless autoconfig IPv6 (newbie alert). I have a windows guest on my vmware esxi 6.5 server which obtains it fine.  My 99-dhcp-en.network file in /etc/systemd/network is stock except that I changed IPv6AcceptRA=yes.  I do not have a DHCPv6 running on my LAN. Are there other settings needed to make this work?

Thanks in advance!

**Comment by YustasSwamp** [comment]
Who does provide router advertisement on your LAN?

I would also recommend you to check that `accept_ra` sysctl is set to 1 (or even 2) for the ipv6 of your interface
https://www.kernel.org/doc/Documentation/networking/ip-sysctl.txt

**Comment by vo243** [comment]
My edge firewall does it.  It's provided it fine for both physical hosts (OSX desktop) and a virtual guest (Windows 10) on the same subnet.

I've set the following on the fly:
sysctl -w net.ipv6.conf.eth0.accept_ra=1 
and
sysctl -w net.ipv6.conf.eth0.autoconf=1
in an attempt to get it to work as well, but that doesn't seem to affect it.  The Photon OS version I'm testing is a fresh minimal deployment from OVA, so the only customization of it right now is my password.

**Comment by YustasSwamp** [comment]
You might need to enable icmpv6.
```
ip6tables -A INPUT -p icmpv6 --icmpv6-type router-advertisement -m hl --hl-eq 255 -j ACCEPT
ip6tables -A INPUT -p icmpv6 --icmpv6-type neighbor-solicitation -m hl --hl-eq 255 -j ACCEPT
ip6tables -A INPUT -p icmpv6 --icmpv6-type neighbor-advertisement -m hl --hl-eq 255 -j ACCEPT
ip6tables -A INPUT -p icmpv6 --icmpv6-type redirect -m hl --hl-eq 255 -j ACCEPT
```
or simply 
`ip6tables -P INPUT ACCEPT`

**Comment by vo243** [comment]
Bingo!  That's it.  I did the catch all ACCEPT rule first to test, then a reboot and adjusted ip6tables as you suggested for just the icmpv6 items, and that did it.  Stateless Autoconfiguration is working now, no other changes other than the IPv6AcceptRA=yes I had done before. 

Thank you so much, YustasSwamp.  A virtual high-five from me!

**Comment by YustasSwamp** [comment]
Glad to hear that it helped.
While looking on iptables.stop I also found that `systemctl stop iptables` does not drop ip6tables rules. Will be fixed soon.

Thank you.
