### ISSUE TITLE
Does Photon OS 3.0 support docker (18.09.2) and Kubernetes (1.13.3)?

### ISSUE THREAD

**Issue by harshneelmore** [vmware/photon#868]

**Comment by suezzelur** [comment]
not yet, but there are plans to add it in the near future.

**Comment by harshneelmore** [comment]
Do you know what versions of Kubernetes and Docker is supported by Photon OS 3.0?

**Comment by DRoet** [comment]
Docker: `Docker version 18.06.2, build 6d37f41`
kubernetes: ` GitVersion:"v1.11.3"` &  ` GoVersion:"go1.10.7"`

**Comment by david-ecc** [comment]
Kubernetes 1.17 was released a few days ago.

**Comment by YustasSwamp** [comment]
and docker also
