### ISSUE TITLE
Photon add vRA 7.4

### ISSUE THREAD

**Issue by goliatblack** [vmware/photon#869]
Hi 
During the add Photon 3.0 to vRA 7.4 the process is stop and isn't possible.

**Comment by goliatblack** [comment]
http://www.doublecloud.org/2015/05/how-to-enable-remote-management-for-docker-in-vmware-photon/

**Comment by suezzelur** [comment]
What is the issue you are running into?

**Comment by YustasSwamp** [comment]
Closing as no updates now.
