### ISSUE TITLE
tdnf on photon 2 does not restart docker after updating 

### ISSUE THREAD

**Issue by hanscees** [vmware/photon#870]
Hi,
on several of my dockerhosts docker went down after an update by tdnf.

see https://github.com/vmware/tdnf/issues/83

**Comment by suezzelur** [comment]
@hanscees I am not able to repro this

root@photon-51135e546fc5 [ ~ ]# tdnf list installed | grep docker
docker.x86_64                               18.06.1-1.ph2            @System
root@photon-51135e546fc5 [ ~ ]# systemctl is-active docker
active
root@photon-51135e546fc5 [ ~ ]# tdnf update -y docker-18.06.2-1.ph2

Upgrading:
docker                                               x86_64                     18.06.2-1.ph2                       photon-updates             189.24M 198435468

Total installed size: 189.24M 198435468

Downloading:
docker                                57229145    100%
Testing transaction
Running transaction
Installing/Updating: docker-18.06.2-1.ph2.x86_64
Removing: docker-18.06.1-1.ph2.x86_64

Complete!
root@photon-51135e546fc5 [ ~ ]# systemctl is-active docker
active

**Comment by YustasSwamp** [comment]
Reproducible while updating from `17.06.0-ce` to `18.09.9`

root@photon-machine [ ~ ]# docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.1
 Git commit:   02c1d87
 Built:        Thu Oct 26 06:33:23 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.1
 Git commit:   02c1d87
 Built:        Thu Oct 26 06:34:46 2017
 OS/Arch:      linux/amd64
 Experimental: false
root@photon-machine [ ~ ]# tdnf update -y docker
Refreshing metadata for: 'VMware Photon Linux 2.0(x86_64) Updates'
Refreshing metadata for: 'VMware Photon Linux 2.0(x86_64)'
Refreshing metadata for: 'VMware Photon Extras 2.0(x86_64)'
photon-extras                              106    100%
Installing:
runc                                                           x86_64                          1.0.0.rc9-2.ph2                           photon-updates                       10.24M 10737533
libapparmor                                                    x86_64                          2.13-4.ph2                                photon-updates                          95.28k 97568
containerd                                                     x86_64                          1.2.10-2.ph2                              photon-updates                       76.25M 79959119
docker-engine                                                  x86_64                          18.09.9-2.ph2                             photon-updates                       91.27M 95706610
docker-cli                                                     x86_64                          18.09.9-2.ph2                             photon-updates                       72.77M 76300641

Total installed size: 250.63M 262801471

Upgrading:
docker                                                         x86_64                          18.09.9-2.ph2                             photon-updates                               0.00b 0

Total installed size:   0.00b 0

Downloading:
docker-cli                            21049715    100%
docker-engine                         28083618    100%
containerd                            24214286    100%
libapparmor                              46630    100%
runc                                   3315756    100%
docker                                    6198    100%
Testing transaction
Running transaction
Installing/Updating: runc-1.0.0.rc9-2.ph2.x86_64
Installing/Updating: containerd-1.2.10-2.ph2.x86_64
Installing/Updating: libapparmor-2.13-4.ph2.x86_64
Installing/Updating: docker-engine-18.09.9-2.ph2.x86_64
Installing/Updating: docker-cli-18.09.9-2.ph2.x86_64
Installing/Updating: docker-18.09.9-2.ph2.x86_64
Removing: docker-17.06.0-4.ph2.x86_64

Complete!
root@photon-machine [ ~ ]# docker version
Client: Docker Engine - Community
 Version:           18.09.9
 API version:       1.39
 Go version:        go1.11.13
 Git commit:        039a7df
 Built:             Thu Jan  9 03:25:01 2020
 OS/Arch:           linux/amd64
 Experimental:      false
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
root@photon-machine [ ~ ]# systemctl start docker
root@photon-machine [ ~ ]# docker version
Client: Docker Engine - Community
 Version:           18.09.9
 API version:       1.39
 Go version:        go1.11.13
 Git commit:        039a7df
 Built:             Thu Jan  9 03:25:01 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.9
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.13
  Git commit:       039a7df
  Built:            Thu Jan  9 03:25:54 2020
  OS/Arch:          linux/amd64
  Experimental:     false

**Comment by YustasSwamp** [comment]
It was issue of already published 17.06.0 and fixed in 18+
