### ISSUE TITLE
photon-rpi3 unable to install tdnf packages

### ISSUE THREAD

**Issue by nareshbvemula** [vmware/photon#871]
root@photon-rpi3 [ ~ ]# tdnf install iputils
Refreshing metadata for: 'VMware Photon Linux 3.0(aarch64) Updates'
curl#6: Couldn't resolve host name
Error: Failed to synchronize cache for repo 'VMware Photon Linux 3.0(aarch64) Updates' from 'https://dl.bintray.com/vmware/photon_updates_3.0_aarch64'
Disabling Repo: 'VMware Photon Linux 3.0(aarch64) Updates'
Refreshing metadata for: 'VMware Photon Linux 3.0(aarch64)'
curl#6: Couldn't resolve host name
Error: Failed to synchronize cache for repo 'VMware Photon Linux 3.0(aarch64)' from 'https://dl.bintray.com/vmware/photon_release_3.0_aarch64'
Disabling Repo: 'VMware Photon Linux 3.0(aarch64)'
No package iputils available
Error(1011) : No matching packages
root@photon-rpi3 [ ~ ]#
root@photon-rpi3 [ ~ ]#

root@photon-rpi3 [ ~ ]# cat /etc/resolv.conf
```
### # This file is managed by man:systemd-resolved(8). Do not edit.
#
# This is a dynamic resolv.conf file for connecting local clients to the
# internal DNS stub resolver of systemd-resolved. This file lists all
# configured search domains.
#
# Run "resolvectl status" to see details about the uplink DNS servers
# currently in use.
#
# Third party programs must not access this file directly, but only through the
# symlink at /etc/resolv.conf. To manage man:resolv.conf(5) in a different way,
# replace this symlink by a static file or a different symlink.
#
# See man:systemd-resolved.service(8) for details about the supported modes of
# operation for /etc/resolv.conf.

nameserver 127.0.0.53
root@photon-rpi3 [ ~ ]#
```

**Comment by smaliakkal** [comment]
@nareshbvemula , Could you try "tdnf install iputils --refresh"   and see if it resolves ?

**Comment by suezzelur** [comment]
You are probably running into dns issues
curl#6: Couldn't resolve host name
Please check if you can `dig dl.bintray.com`
