### ISSUE TITLE
telegraf in 3.0 is out of date

### ISSUE THREAD

**Issue by mzeier** [vmware/photon#876]
Latest package version is 1.10. Needs to be updated in the 3.0 AMI.

**Comment by bala-** [comment]
Any idea, when this issue will be addressed.

**Comment by YustasSwamp** [comment]
On roadmap for 4.0, will be backported to 3.0 then.

**Comment by ssahani** [comment]
https://github.com/vmware/photon/blob/3.0/SPECS/telegraf/telegraf.spec#L3 latest is 1.16.1
