### ISSUE TITLE
3.0 AMI doesn't include chrony

### ISSUE THREAD

**Issue by mzeier** [vmware/photon#878]
AWS AMI should support chrony to be on par with Amazon Linux 2 and should default to the ip4v link local address (`169.254.169.123`).

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-time.html

**Comment by voor** [comment]
The better issue is that there isn't a `chrony` package in Photon right now.

**Comment by ssahani** [comment]
Chrony is part of photon now. Clossing. https://github.com/vmware/photon/tree/3.0/SPECS/chrony
