### ISSUE TITLE
ISO installer, docs do not match the process

### ISSUE THREAD

**Issue by vanayr** [vmware/photon#883]
https://vmware.github.io/photon/assets/files/html/3.0/photon_installation/installing-the-iso-image-for-photon-os-30.html

The documentation references Minimal, Full, and OSTree, however the installer prompts for Minimal, Developer, and Edge with no explanation as to what the differences are.

**Comment by vidya-v** [comment]
This has been fixed and is available in the latest documentation.
cc @VinodJIsaac
