### ISSUE TITLE
What are the supported Kubernetes version for Photon 2.0? 

### ISSUE THREAD

**Issue by harshneelmore** [vmware/photon#886]
Currently, on Photon OS 2, I am using Kubernetes v1.10.11 and docker 17.06.09
I am trying to upgrade the image to use the latest docker and Kuberentes version. I see that docker 18.06.2 is supported but not able to get supported versions for Kubernetes.

I am looking to upgrade to Kubernetes version apart from (v1.0.0-1.10.x, v1.11.0-1.11.7, v1.12.0-1.12.5, v1.13.0-1.13.3) as these contain a kubernetes-api-server vulnerability.

**Comment by suezzelur** [comment]
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.13.md#external-dependencies
