### ISSUE TITLE
Static IP breaks network connections in Photon OS on vSphere 

### ISSUE THREAD

**Issue by Bas-vE** [vmware/photon#888]
So before I created this issue, I've read all the related issues to this problem and none of them gave me the right answer. So when I try to set a static IP on my Photon 3 VM which is running on vSphere. But the moment I set the IP like described in the [manual here](https://vmware.github.io/photon/assets/files/html/3.0/photon_admin/setting-a-static-ip-address.html) all incoming and outgoing connections are getting blocked.

The configuration I used is:
`cat > /etc/systemd/network/10-static-en.network << "EOF"

[Match]
Name=eth0

[Network]
DHCP=no
Address=192.168.178.222/24
Gateway=192.168.178.1
DNS=192.168.178.1
EOF`

after that I set the correct access permissions and I restart the deamon  like described in the manual. When I try to connect to the new IP with SSH(which was working fine with DHCP) I cant connect. when I ping from my VM to 8.8.8.8 or even my own gateway all my packages are lost and i get the message: "Destination Unreachable", when I pinged when DHCP was still active, there was no problem. I've tried to redeploy Photon OS, and that also didnt make a difference.

When I run ifconfig
![image](https://user-images.githubusercontent.com/16207111/55235566-21c45900-522e-11e9-8682-d935fc63ceb9.png)

I dont know what i'm doing wrong. i'm out of ideas.

**Comment by AaronArb** [comment]
Check out the issue (92) that I just raised, I reckon we are talking about the same thing... its a default route that shows up on the lo0 loopback interface which kills all comms...

issue
`route delete -net 0.0.0.0` 
and let me know if that fixes your problem

**Comment by ssahani** [comment]
I don't think think is not related to your issue.  `>"Destination Unreachable",` can be fixed by `GatewayOnLink=` https://www.freedesktop.org/software/systemd/man/systemd.network.html#GatewayOnLink=.

This is already fixed in 239 version .

**Comment by Blizzardo1** [comment]
This is a similar issue. I'm working with two nics right now and when I have an external static route online, its route takes precedence therefore I cannot route any IPSEC traffic to it or from it. it causes a mass service disconnection internally and can only be fixed when I turn off the external connection. Any ideas? I'm pulling out my gray hairs over here lol.

**Comment by ssahani** [comment]
you need to configure routing rules for that. https://www.freedesktop.org/software/systemd/man/systemd.network.html#%5BRoutingPolicyRule%5D%20Section%20Options

**Comment by ssahani** [comment]
Closing because of lack of response
