### ISSUE TITLE
Powershell Core's ConsoleHost not initialized correctly in Docker image

### ISSUE THREAD

**Issue by lyuboasenov** [vmware/photon#889]
Powershell Core's ConsoleHost not initialized correctly in Docker image on top of Photon OS 2/3.

### Steps To Reproduce
docker run -v ${pwd}\app.ps1:/root/app.ps1 vmware/powerclicore pwsh app.ps1

### app.ps1 Content
Write-Host ($host.UI.RawUI | Format-List | Out-String)

### Current Result
ForegroundColor       : -1
BackgroundColor       : -1
CursorPosition        : 0,0
WindowPosition        : 0,0
CursorSize            : 100
BufferSize            : -1,-1
WindowSize            : -1,-1
MaxWindowSize         : -1,-1
MaxPhysicalWindowSize : -1,-1
KeyAvailable          :
WindowTitle           :

### Result from using vmware/powerclicore:ubuntu16.04
ForegroundColor       : -1
BackgroundColor       : -1
CursorPosition        : 0,0
WindowPosition        : 0,0
CursorSize            : 100
BufferSize            : 80,40
WindowSize            : 80,40
MaxWindowSize         : 80,40
MaxPhysicalWindowSize : 80,40
KeyAvailable          :
WindowTitle           :

**Comment by ppadmavilasom** [comment]
Please try with the updated powershell-6.2.3

root [ / ]# pwsh
PowerShell 6.2.3
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/pscore6-docs
Type 'help' to get help.

PS /> Write-Host ($host.UI.RawUI | Format-List | Out-String)

ForegroundColor       : -1
BackgroundColor       : -1
CursorPosition        : 0,23
WindowPosition        : 0,0
CursorSize            : 100
BufferSize            : 134,24
WindowSize            : 134,24
MaxWindowSize         : 134,24
MaxPhysicalWindowSize : 134,24
KeyAvailable          : False
WindowTitle           :
