### ISSUE TITLE
Unable to install coreutils in Photon OS docker image 3.0

### ISSUE THREAD

**Issue by dereksolar** [vmware/photon#890]
#> tdnf install coreutils
Found 1 problem(s) while resolving
1. package coreutils-8.30-1.ph3.x86_64 conflicts with toybox provided by toybox-0.7.7-1.ph3.x86_64
Error(1301) : Solv general runtime error

**Comment by ppadmavilasom** [comment]
please remove toybox (tdnf erase toybox) if you need to install coreutils.

**Comment by dereksolar** [comment]
Thanks
