### ISSUE TITLE
Update powershell package

### ISSUE THREAD

**Issue by lucdekens** [vmware/photon#891]
The current powershell package contains PowerShell 6.1.1, which dates from Nov 2018.
The PowerShell 6.2 version went GA end of March 2019.

Can the package please be updated?

**Comment by lucdekens** [comment]
Since PowerShell is open source, the update frequency is quite high.
Can this be automated in some way?
Or do we really need to install [Ubuntu development environment](https://github.com/vmware/photon/wiki/Frequently-Asked-Questions#q-how-to-build-new-package-for-photon-os)?

**Comment by CollinChaffin** [comment]
Why can't the optional dev repo at least not be automated to pull the latest psh?

**Comment by ppadmavilasom** [comment]
updated to 6.2.3 and includes PSReadLine, PowerShellGet and PackageManagement modules

**Comment by lucdekens** [comment]
Did you also tackle the 2nd part?
I.e. automated updating of the package when a new PS release is published.

**Comment by ppadmavilasom** [comment]
There are no plans for automation at the moment.
