### ISSUE TITLE
Unable to install photon-hw13_uefi-3.0-26156e2.ova  on ESXi-6.7.0

### ISSUE THREAD

**Issue by bignay2000** [vmware/photon#900]
Unable to install photon-hw13_uefi-3.0-26156e2.ova on ESXi-6.7.0-20190402001-standard

Select creation Type: Deploy a virtual machine from an OVF or OVA file
Select OVF and VMDK files:
	Name: photon3
	File: photon-hw13_uefi-3.0-26156e2.ova
Select storage: nvme
License agreements: i agree
Deployment options:
	Network Mappings: VM Network
	Disk Provisioning: Thin
	Power on automatically checked
	
	
Unfortunately, we hit an error that we weren't expecting.

The client may continue working, but at this point, we recommend refreshing your browser and submitting a bug report.

Press the Esc key to hide this dialog and continue without refreshing.

Unhandled exception (2)
Cause: Possibly unhandled rejection: {}
Version: 1.33.3
Build: 12923304
ESXi: 6.7.0
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36

Exception stack:

TypeError: Cannot read property 'keyValue' of undefined
    at updateSummaryPortlet (https://192.168.1.100/ui/scripts/main.js:375:415)
    at $scope.wizardOptions.onFinish (https://192.168.1.100/ui/scripts/main.js:375:5968)
    at https://192.168.1.100/ui/scripts/main.js:324:23176
    at m.$digest (https://192.168.1.100/ui/scripts/main.js:324:28780)
    at https://192.168.1.100/ui/scripts/main.js:324:30503
    at e (https://192.168.1.100/ui/scripts/main.js:323:10071)
    at https://192.168.1.100/ui/scripts/main.js:323:11522

Once this Error occurs, I get resent to the ESXi login page.

![unhandled exception](https://user-images.githubusercontent.com/11713022/57389342-f49d8b80-7187-11e9-8cad-2ef45ff1032b.jpg)

[ovafail.mp4.zip](https://github.com/vmware/photon/files/3158341/ovafail.mp4.zip)

**Comment by bignay2000** [comment]
This OVA file works fine to create a photon vm on my Macbook using Fusion 11 Pro.  Not sure where the null value is not being defined.

**Comment by bignay2000** [comment]
ovftool gives the following warnings:


Opening OVA source: /Users/bignay2000/iso/photon-hw13_uefi-3.0-26156e2.ova
The manifest validates
Source is signed and the certificate validates 
Warning:
 - Line -1: Unsupported value 'firmware' for attribute 'key' on element 'ExtraConfig'.
 - Line -1: Unsupported value 'uefi.secureBoot.enabled' for attribute 'key' on element 'ExtraConfig'.

**Comment by smaliakkal** [comment]
@bignay2000  , I deployed  ESX 6.7 14016607 using Nimbus , then deployed photon-hw13_uefi-3.0-26156e2.ova on that esx using host ui using chrome Version 74.0.3729.169 (Official Build) (64-bit), but no issue found . 
what exactly is ESXi-6.7.0-20190402001-standard;  could you specify the build number ESXi 6.7 build number ?

**Comment by beshkenadze** [comment]
Same issue here.
ESXi Version:
6.7.0 Update 2 (Build 13006603)
OVA: photon-hw11-3.0-26156e2/photon-hw13_uefi-3.0-49fd219

**Comment by bvivi57** [comment]
Hi
It's a bug with 6.7.0 update 2 and OVA : https://communities.vmware.com/thread/609629

You can use "ovftool" for import OVA photon to your cluster: https://www.vmware.com/support/developer/ovf/

**Comment by YustasSwamp** [comment]
Thanks for the information!
