### ISSUE TITLE
external interface not reachable when configuring internal interface?

### ISSUE THREAD

**Issue by wilfriedwolf** [vmware/photon#901]
Hi there!
I'm desperately trying to configure my photonos instance according to my needs:
First of all the machine has 2 interfaces one in the internal net, the other in the DMZ.

Configuring both separately just works fine. When I put the 2 of them together, the DMZ interface just is dead, at least I can neither ping nor ssh to it.

Here is my configuration:

10-static-eth0.network:
[Match]
Name=eth0
﻿
[Network]
Address=xx.yy.zz.xx/26
Gateway=xx.yy.zz.aa
DNS=xx.yy.zz.bb
Domain=example.com

20-static-eth1.network:
[Match]
Name=eth1
﻿
[Network]
Address=192.168.209.xx/24
Gateway=192.168.209.254
DNS=192.168.209.57
Domain=example.intern

Doing 'ip addr' the addresses appear on the network. 

Any help is greatly apprecieated.

Best regards,

Willi

**Comment by ssahani** [comment]
>Configuring both separately just works fine. When I put the 2 of them together, the DMZ interface just is dead, at least I can neither ping nor ssh to it.

I don#t figure what is meant by "configuring separately" . networkd works per link basis. Can you figure   from ```ip route show ``` command when you do via ip route command and what is the difference when you do via networkd also could you set ```SYSTEMD_LOG_LEVEL=debug``` environment variable to generate debugging logs?
Please create a drop-in config file like the following
```
# /etc/systemd/system/systemd-networkd.service.d/override.conf
[Service]
Environment=SYSTEMD_LOG_LEVEL=debug
```

Please paste the commands you use to configure via ip route tool

**Comment by ssahani** [comment]
Closing because of lack of response.
