### ISSUE TITLE
Feature: Logical Volume

### ISSUE THREAD

**Issue by vampire337** [vmware/photon#903]
Originally asked about in VMWare community: https://communities.vmware.com/thread/610795

In short, I am able to add a VMDK to the VM and add it to the total disk pool without having to mount each VMDK as separate folders.  Photon doesn't appear to be capable of this, or maybe I just haven't figured it out.  Currently I have a Univention VM with 4 1TB VMDKs which works as a single 4TB logical volume:
![image](https://user-images.githubusercontent.com/3717803/57962830-f387ff00-78e9-11e9-961d-bf826fc5524a.png)

I'm not sure how big a technical undertaking this would be for Photon, but I thought I'd post the suggestion and see what the experts think.

**Comment by suezzelur** [comment]
Please do a `tdnf install -y lvm2` before attempting this

**Comment by vampire337** [comment]
Installing lvm2 alone doesn't create any logical partition for Photon to run on.  Your answer doesn't accomplish the task proposed in this feature request.
