### ISSUE TITLE
dnf distro-sync -y returned a non-zero code: 255 Error(-1) : Unknown error -1601

### ISSUE THREAD

**Issue by ahnselina** [vmware/photon#905]
hi~, when I wanted to build harbor offline package, I met this problem in my VM:
"
.....
Removing: photon-release-2.0-1.ph2.noarch
Removing: photon-repos-2.0-1.ph2.noarch
Removing: tdnf-1.2.2-2.ph2.x86_64
Removing: curl-7.54.1-1.ph2.x86_64
Removing: curl-libs-7.54.1-1.ph2.x86_64
Removing: ca-certificates-20170406-3.ph2.x86_64
Removing: krb5-1.15.2-1.ph2.x86_64
Removing: hawkey-2017.1-4.ph2.x86_64
Removing: rpm-libs-4.13.0.1-6.ph2.x86_64
Removing: nss-libs-3.31-3.ph2.x86_64
Removing: sqlite-libs-3.19.3-1.ph2.x86_64
Removing: libsolv-0.6.26-3.ph2.x86_64
Removing: libssh2-1.8.0-1.ph2.x86_64
Removing: ca-certificates-pki-20170406-3.ph2.x86_64
Removing: openssl-1.0.2l-2.ph2.x86_64
Removing: libgcc-6.3.0-6.ph2.x86_64
Removing: elfutils-libelf-0.169-2.ph2.x86_64
Removing: ncurses-libs-6.0-12.ph2.x86_64
Removing: bash-4.4-6.ph2.x86_64
Removing: glibc-2.26-6.ph2.x86_64
Error(-1) : Unknown error -1601
The command '/bin/sh -c touch /etc/localtime.bak     && tdnf distro-sync -y     && tdnf install -y sed shadow gzip postgresql >> /dev/null    && groupadd -r postgres --gid=999     && useradd -r -g postgres --uid=999 postgres     && mkdir -p /docker-entrypoint-initdb.d     && mkdir -p /run/postgresql     && chown -R postgres:postgres /run/postgresql     && chmod 2777 /run/postgresql     && mkdir -p "$PGDATA" && chown -R postgres:postgres "$PGDATA" && chmod 777 "$PGDATA"     && sed -i "s|#listen_addresses = 'localhost'.*|listen_addresses = '*'|g" /usr/share/postgresql/postgresql.conf.sample     && sed -i "s|#unix_socket_directories = '/tmp'.*|unix_socket_directories = '/run/postgresql'|g" /usr/share/postgresql/postgresql.conf.sample     && touch /usr/share/locale/locale.alias     && locale-gen.sh en_US.UTF-8     && tdnf clean all' returned a non-zero code: 255
make[1]: *** [_build_postgresql] 错误 255
make[1]: 离开目录“/root/harbor-1.5.1”
make: *** [build] 错误 2
"

I try to figure out this, then I find that "tdnf distro-sync -y " excuted failed.
I use " tdnf distro-sync -y --rpmverbosity debug", the output result as follow:
"
........
D: skip 100755 1 ( 0, 0) 33016 /usr/lib64/gconv/IBM1046.so
D: skip 100755 1 ( 0, 0) 33064 /usr/lib64/gconv/IBM1026.so
D: skip 100755 1 ( 0, 0) 32312 /usr/lib64/gconv/IBM1025.so
D: skip 100755 1 ( 0, 0) 20360 /usr/lib64/gconv/IBM1008_420.so
D: skip 100755 1 ( 0, 0) 33016 /usr/lib64/gconv/IBM1008.so
D: skip 100755 1 ( 0, 0) 33064 /usr/lib64/gconv/IBM1004.so
D: skip 100755 1 ( 0, 0) 32696 /usr/lib64/gconv/IBM038.so
D: skip 100755 1 ( 0, 0) 32696 /usr/lib64/gconv/IBM037.so
D: skip 100755 1 ( 0, 0) 33080 /usr/lib64/gconv/HP-TURKISH8.so
D: skip 100755 1 ( 0, 0) 33064 /usr/lib64/gconv/HP-THAI8.so
D: skip 100755 1 ( 0, 0) 33080 /usr/lib64/gconv/HP-ROMAN9.so
D: skip 100755 1 ( 0, 0) 33080 /usr/lib64/gconv/HP-ROMAN8.so
D: skip 100755 1 ( 0, 0) 33064 /usr/lib64/gconv/HP-GREEK8.so
D: skip 100755 1 ( 0, 0) 33048 /usr/lib64/gconv/GREEK7.so
D: skip 100755 1 ( 0, 0) 33064 /usr/lib64/gconv/GREEK7-OLD.so
D: skip 100755 1 ( 0, 0) 33064 /usr/lib64/gconv/GREEK-CCITT.so
D: skip 100755 1 ( 0, 0) 33072 /usr/lib64/gconv/GOST_19768-74.so
D: skip 100755 1 ( 0, 0) 32376 /usr/lib64/gconv/GEORGIAN-PS.so
D: skip 100755 1 ( 0, 0) 32384 /usr/lib64/gconv/GEORGIAN-ACADEMY.so
D: skip 100755 1 ( 0, 0)166072 /usr/lib64/gconv/GBK.so
D: skip 100755 1 ( 0, 0) 38576 /usr/lib64/gconv/GBGBK.so
D: skip 100755 1 ( 0, 0) 92944 /usr/lib64/gconv/GBBIG5.so
D: skip 100755 1 ( 0, 0)243384 /usr/lib64/gconv/GB18030.so
D: skip 100755 1 ( 0, 0)108056 /usr/lib64/gconv/EUC-TW.so
D: skip 100755 1 ( 0, 0) 64992 /usr/lib64/gconv/EUC-KR.so
D: skip 100755 1 ( 0, 0) 66400 /usr/lib64/gconv/EUC-JP.so
D: skip 100755 1 ( 0, 0)138864 /usr/lib64/gconv/EUC-JP-MS.so
D: skip 100755 1 ( 0, 0) 76496 /usr/lib64/gconv/EUC-JISX0213.so
D: skip 100755 1 ( 0, 0) 69040 /usr/lib64/gconv/EUC-CN.so
D: skip 100755 1 ( 0, 0) 32384 /usr/lib64/gconv/ECMA-CYRILLIC.so
D: skip 100755 1 ( 0, 0) 32696 /usr/lib64/gconv/EBCDIC-US.so
D: skip 100755 1 ( 0, 0) 33064 /usr/lib64/gconv/EBCDIC-UK.so
D: skip 100755 1 ( 0, 0) 32696 /usr/lib64/gconv/EBCDIC-PT.so
D: skip 100755 1 ( 0, 0) 32696 /usr/lib64/gconv/EBCDIC-IT.so
D: skip 100755 1 ( 0, 0) 33088 /usr/lib64/gconv/EBCDIC-IS-FRISS.so
D: skip 100755 1 ( 0, 0) 32696 /usr/lib64/gconv/EBCDIC-FR.so
D: skip 100755 1 ( 0, 0) 32712 /usr/lib64/gconv/EBCDIC-FI-SE.so
D: skip 100755 1 ( 0, 0) 32720 /usr/lib64/gconv/EBCDIC-FI-SE-A.so
D: skip 100755 1 ( 0, 0) 33064 /usr/lib64/gconv/EBCDIC-ES.so
D: skip 100755 1 ( 0, 0) 32712 /usr/lib64/gconv/EBCDIC-ES-S.so
D: skip 100755 1 ( 0, 0) 33064 /usr/lib64/gconv/EBCDIC-ES-A.so
D: skip 100755 1 ( 0, 0) 32712 /usr/lib64/gconv/EBCDIC-DK-NO.so
D: skip 100755 1 ( 0, 0) 32720 /usr/lib64/gconv/EBCDIC-DK-NO-A.so
D: skip 100755 1 ( 0, 0) 32712 /usr/lib64/gconv/EBCDIC-CA-FR.so
D: skip 100755 1 ( 0, 0) 32712 /usr/lib64/gconv/EBCDIC-AT-DE.so
D: skip 100755 1 ( 0, 0) 32720 /usr/lib64/gconv/EBCDIC-AT-DE-A.so
D: skip 100755 1 ( 0, 0) 33064 /usr/lib64/gconv/DEC-MCS.so
D: skip 100755 1 ( 0, 0) 32352 /usr/lib64/gconv/CWI.so
D: skip 100755 1 ( 0, 0) 32376 /usr/lib64/gconv/CSN_369103.so
D: skip 100755 1 ( 0, 0)146712 /usr/lib64/gconv/CP932.so
D: skip 100755 1 ( 0, 0) 33256 /usr/lib64/gconv/CP775.so
D: skip 100755 1 ( 0, 0) 32360 /usr/lib64/gconv/CP774.so
D: skip 100755 1 ( 0, 0) 32360 /usr/lib64/gconv/CP773.so
D: skip 100755 1 ( 0, 0) 32360 /usr/lib64/gconv/CP772.so
D: skip 100755 1 ( 0, 0) 32360 /usr/lib64/gconv/CP771.so
D: skip 100755 1 ( 0, 0) 32360 /usr/lib64/gconv/CP770.so
D: skip 100755 1 ( 0, 0) 33224 /usr/lib64/gconv/CP737.so
D: skip 100755 1 ( 0, 0) 56432 /usr/lib64/gconv/CP1258.so
D: skip 100755 1 ( 0, 0) 33064 /usr/lib64/gconv/CP1257.so
D: skip 100755 1 ( 0, 0) 33064 /usr/lib64/gconv/CP1256.so
D: skip 100755 1 ( 0, 0) 59672 /usr/lib64/gconv/CP1255.so
D: skip 100755 1 ( 0, 0) 33064 /usr/lib64/gconv/CP1254.so
D: skip 100755 1 ( 0, 0) 33064 /usr/lib64/gconv/CP1253.so
D: skip 100755 1 ( 0, 0) 33064 /usr/lib64/gconv/CP1252.so
D: skip 100755 1 ( 0, 0) 33064 /usr/lib64/gconv/CP1251.so
D: skip 100755 1 ( 0, 0) 33064 /usr/lib64/gconv/CP1250.so
D: skip 100755 1 ( 0, 0) 32360 /usr/lib64/gconv/CP1125.so
D: skip 100755 1 ( 0, 0) 32360 /usr/lib64/gconv/CP10007.so
D: skip 100755 1 ( 0, 0) 33040 /usr/lib64/gconv/BRF.so
D: skip 100755 1 ( 0, 0)284264 /usr/lib64/gconv/BIG5HKSCS.so
D: skip 100755 1 ( 0, 0)130200 /usr/lib64/gconv/BIG5.so
D: skip 100755 1 ( 0, 0) 33064 /usr/lib64/gconv/ASMO_449.so
D: skip 100755 1 ( 0, 0) 33912 /usr/lib64/gconv/ARMSCII-8.so
D: skip 100755 1 ( 0, 0) 64248 /usr/lib64/gconv/ANSI_X3.110.so
D: skip 100755 1 ( 0, 0) 37624 /usr/lib64/audit/sotruss-lib.so
D: skip 040755 1 ( 0, 0) 6 /usr/lib/locale
D: skip 100755 1 ( 0, 0) 5291 /usr/bin/xtrace
D: skip 100755 1 ( 0, 0) 13207 /usr/bin/tzselect
D: skip 100755 1 ( 0, 0) 80864 /usr/bin/sprof
D: skip 100755 1 ( 0, 0) 4277 /usr/bin/sotruss
D: skip 100755 1 ( 0, 0)294240 /usr/bin/rpcgen
D: skip 100755 1 ( 0, 0) 54424 /usr/bin/pldd
D: skip 100755 1 ( 0, 0) 28744 /usr/bin/pcprofiledump
D: skip 100755 1 ( 0, 0) 63896 /usr/bin/makedb
D: skip 100755 1 ( 0, 0)1453680 /usr/bin/localedef
D: skip 100755 1 ( 0, 0)138904 /usr/bin/locale
D: skip 100755 1 ( 0, 0) 5768 /usr/bin/ldd
D: skip 100755 1 ( 0, 0)263816 /usr/bin/iconv
D: skip 100755 1 ( 0, 0) 85192 /usr/bin/getent
D: skip 100755 4 ( 0, 0) 60928 /usr/bin/getconf
D: skip 100755 1 ( 0, 0) 87424 /usr/bin/gencat
D: skip 100755 1 ( 0, 0) 3284 /usr/bin/catchsegv
D: skip 100755 1 ( 0, 0)3357952 /sbin/sln
D: skip 100755 1 ( 0, 0) 1040 /sbin/locale-gen.sh
D: skip 100755 1 ( 0, 0)4238520 /sbin/ldconfig
D: skip 120777 1 ( 0, 0) 15 /lib64/libutil.so.1
D: skip 100755 1 ( 0, 0) 34696 /lib64/libutil-2.22.so
D: skip 120777 1 ( 0, 0) 19 /lib64/libthread_db.so.1
D: skip 100755 1 ( 0, 0)262768 /lib64/libthread_db-1.0.so
D: skip 120777 1 ( 0, 0) 13 /lib64/librt.so.1
D: skip 100755 1 ( 0, 0)216864 /lib64/librt-2.22.so
D: skip 120777 1 ( 0, 0) 17 /lib64/libresolv.so.2
D: skip 100755 1 ( 0, 0)398024 /lib64/libresolv-2.22.so
D: skip 120777 1 ( 0, 0) 18 /lib64/libpthread.so.0
D: skip 100755 1 ( 0, 0)1019648 /lib64/libpthread-2.22.so
D: skip 100755 1 ( 0, 0) 12560 /lib64/libpcprofile.so
D: skip 120777 1 ( 0, 0) 22 /lib64/libnss_nisplus.so.2
D: skip 100755 1 ( 0, 0)328016 /lib64/libnss_nisplus-2.22.so
D: skip 120777 1 ( 0, 0) 18 /lib64/libnss_nis.so.2
D: skip 100755 1 ( 0, 0)259960 /lib64/libnss_nis-2.22.so
D: skip 120777 1 ( 0, 0) 21 /lib64/libnss_hesiod.so.2
D: skip 100755 1 ( 0, 0)101632 /lib64/libnss_hesiod-2.22.so
D: skip 120777 1 ( 0, 0) 20 /lib64/libnss_files.so.2
D: skip 100755 1 ( 0, 0)270528 /lib64/libnss_files-2.22.so
D: skip 120777 1 ( 0, 0) 18 /lib64/libnss_dns.so.2
D: skip 100755 1 ( 0, 0) 97248 /lib64/libnss_dns-2.22.so
D: skip 120777 1 ( 0, 0) 17 /lib64/libnss_db.so.2
D: skip 100755 1 ( 0, 0)172832 /lib64/libnss_db-2.22.so
D: skip 120777 1 ( 0, 0) 21 /lib64/libnss_compat.so.2
D: skip 100755 1 ( 0, 0)136968 /lib64/libnss_compat-2.22.so
D: skip 120777 1 ( 0, 0) 14 /lib64/libnsl.so.1
D: skip 100755 1 ( 0, 0)589264 /lib64/libnsl-2.22.so
D: skip 120777 1 ( 0, 0) 15 /lib64/libmvec.so.1
D: skip 100755 1 ( 0, 0)214880 /lib64/libmvec-2.22.so
D: skip 100755 1 ( 0, 0) 45048 /lib64/libmemusage.so
D: skip 120777 1 ( 0, 0) 12 /lib64/libm.so.6
D: skip 100755 1 ( 0, 0)3312576 /lib64/libm-2.22.so
D: skip 120777 1 ( 0, 0) 13 /lib64/libdl.so.2
D: skip 100755 1 ( 0, 0)106104 /lib64/libdl-2.22.so
D: skip 120777 1 ( 0, 0) 16 /lib64/libcrypt.so.1
D: skip 100755 1 ( 0, 0)143784 /lib64/libcrypt-2.22.so
D: skip 120777 1 ( 0, 0) 15 /lib64/libcidn.so.1
D: skip 100755 1 ( 0, 0)276912 /lib64/libcidn-2.22.so
D: skip 120777 1 ( 0, 0) 12 /lib64/libc.so.6
D: skip 100755 1 ( 0, 0)10709816 /lib64/libc-2.22.so
D: skip 120777 1 ( 0, 0) 14 /lib64/libanl.so.1
D: skip 100755 1 ( 0, 0) 77808 /lib64/libanl-2.22.so
D: skip 100755 1 ( 0, 0) 71960 /lib64/libSegFault.so
D: skip 120777 1 ( 0, 0) 23 /lib64/libBrokenLocale.so.1
D: skip 100755 1 ( 0, 0) 21192 /lib64/libBrokenLocale-2.22.so
D: skip 120777 1 ( 0, 0) 10 /lib64/ld-linux-x86-64.so.2
D: skip 100755 1 ( 0, 0)893960 /lib64/ld-2.22.so
D: skip 100644 1 ( 0, 0) 1634 /etc/rpc
D: skip 100644 1 ( 0, 0) 227 /etc/nsswitch.conf
D: skip 100644 1 ( 0, 0) 2387 /etc/nscd.conf
D: skip 100644 1 ( 0, 0) 650 /etc/locale-gen.conf
D: skip 040755 1 ( 0, 0) 6 /etc/ld.so.conf.d
D: skip 100644 1 ( 0, 0) 95 /etc/ld.so.conf
D: skip 100644 1 ( 0, 0) 8596 /etc/ld.so.cache
D: %postun(glibc-2.22-19.ph1.x86_64): scriptlet start
D: %postun(glibc-2.22-19.ph1.x86_64): execv(/sbin/ldconfig) pid 522
D: %postun(glibc-2.22-19.ph1.x86_64): waitpid(522) rc 522 status 0
D: Plugin: calling hook scriptlet_post in syslog plugin
D: --- h# 3 glibc-2.22-19.ph1.x86_64
D: adding "glibc" to Name index.
D: adding 918 entries to Basenames index.
D: adding "Applications/System" to Group index.
D: adding 52 entries to Requirename index.
D: adding 354 entries to Providename index.
D: adding 16 entries to Dirnames index.
D: adding 1 entries to Installtid index.
D: adding 1 entries to Sigmd5 index.
D: adding "871473e49dc1221c418784ea5e408a7731f017b5" to Sha1header index.
D: Plugin: calling hook psm_post in ima plugin
D: Plugin: calling hook psm_post in syslog plugin
D: ========== +++ filesystem-1.1-3.ph1 x86_64-linux 0x0
error: filesystem-1.1-3.ph1.x86_64: erase skipped
D: running post-transaction scripts
D: read h# 48 Header V3 RSA/SHA1 Signature, key ID 66fd4949: OK
D: unknown: glibc-2.22-26.ph1.x86_64 has 0 files
D: Plugin: calling hook psm_post in ima plugin
D: Plugin: calling hook psm_post in syslog plugin
D: read h# 49 Header V3 RSA/SHA1 Signature, key ID 66fd4949: OK
D: unknown: ncurses-6.0-9.ph1.x86_64 has 0 files
D: Plugin: calling hook psm_post in ima plugin
D: Plugin: calling hook psm_post in syslog plugin
D: read h# 50 Header V3 RSA/SHA1 Signature, key ID 66fd4949: OK
D: unknown: bash-4.3.48-3.ph1.x86_64 has 0 files
D: Plugin: calling hook psm_post in ima plugin
D: Plugin: calling hook psm_post in syslog plugin
D: read h# 51 Header V3 RSA/SHA1 Signature, key ID 66fd4949: OK
D: unknown: openssl-1.0.2r-1.ph1.x86_64 has 0 files
D: Plugin: calling hook psm_post in ima plugin
D: Plugin: calling hook psm_post in syslog plugin
D: read h# 52 Header V3 RSA/SHA1 Signature, key ID 66fd4949: OK
D: unknown: pkg-config-0.28-3.ph1.x86_64 has 0 files
D: Plugin: calling hook psm_post in ima plugin
D: Plugin: calling hook psm_post in syslog plugin
D: read h# 53 Header V3 RSA/SHA1 Signature, key ID 66fd4949: OK
D: unknown: ca-certificates-20190521-1.ph1.x86_64 has 0 files
D: Plugin: calling hook psm_post in ima plugin
D: Plugin: calling hook psm_post in syslog plugin
D: read h# 54 Header V3 RSA/SHA1 Signature, key ID 66fd4949: OK
D: unknown: libssh2-1.8.2-1.ph1.x86_64 has 0 files
D: Plugin: calling hook psm_post in ima plugin
D: Plugin: calling hook psm_post in syslog plugin
D: read h# 55 Header V3 RSA/SHA1 Signature, key ID 66fd4949: OK
D: unknown: libdb-5.3.28-1.ph1.x86_64 has 0 files
D: Plugin: calling hook psm_post in ima plugin
D: Plugin: calling hook psm_post in syslog plugin
D: read h# 56 Header V3 RSA/SHA1 Signature, key ID 66fd4949: OK
D: unknown: libsolv-0.6.19-6.ph1.x86_64 has 0 files
D: Plugin: calling hook psm_post in ima plugin
D: Plugin: calling hook psm_post in syslog plugin
D: read h# 57 Header V3 RSA/SHA1 Signature, key ID 66fd4949: OK
D: unknown: elfutils-libelf-0.169-4.ph1.x86_64 has 0 files
D: Plugin: calling hook psm_post in ima plugin
D: Plugin: calling hook psm_post in syslog plugin
D: read h# 58 Header V3 RSA/SHA1 Signature, key ID 66fd4949: OK
D: unknown: file-5.24-3.ph1.x86_64 has 0 files
D: Plugin: calling hook psm_post in ima plugin
D: Plugin: calling hook psm_post in syslog plugin
D: read h# 59 Header V3 RSA/SHA1 Signature, key ID 66fd4949: OK
D: unknown: pcre-8.41-2.ph1.x86_64 has 0 files
D: Plugin: calling hook psm_post in ima plugin
D: Plugin: calling hook psm_post in syslog plugin
D: read h# 60 Header V3 RSA/SHA1 Signature, key ID 66fd4949: OK
D: unknown: glib-2.47.6-3.ph1.x86_64 has 0 files
D: Plugin: calling hook psm_post in ima plugin
D: Plugin: calling hook psm_post in syslog plugin
D: read h# 61 Header V3 RSA/SHA1 Signature, key ID 66fd4949: OK
D: unknown: rpm-4.13.0.2-1.ph1.x86_64 has 0 files
D: Plugin: calling hook psm_post in ima plugin
D: Plugin: calling hook psm_post in syslog plugin
D: read h# 62 Header V3 RSA/SHA1 Signature, key ID 66fd4949: OK
D: unknown: hawkey-2014.1-6.ph1.x86_64 has 0 files
D: Plugin: calling hook psm_post in ima plugin
D: Plugin: calling hook psm_post in syslog plugin
D: read h# 63 Header V3 RSA/SHA1 Signature, key ID 66fd4949: OK
D: unknown: curl-7.59.0-7.ph1.x86_64 has 0 files
D: Plugin: calling hook psm_post in ima plugin
D: Plugin: calling hook psm_post in syslog plugin
D: read h# 64 Header V3 RSA/SHA1 Signature, key ID 66fd4949: OK
D: unknown: sqlite-autoconf-3.27.2-2.ph1.x86_64 has 0 files
D: Plugin: calling hook psm_post in ima plugin
D: Plugin: calling hook psm_post in syslog plugin
D: read h# 65 Header V3 RSA/SHA1 Signature, key ID 66fd4949: OK
D: unknown: util-linux-2.27.1-4.ph1.x86_64 has 0 files
D: Plugin: calling hook psm_post in ima plugin
D: Plugin: calling hook psm_post in syslog plugin
D: read h# 66 Header V3 RSA/SHA1 Signature, key ID 66fd4949: OK
D: unknown: vim-7.4-11.ph1.x86_64 has 0 files
D: Plugin: calling hook psm_post in ima plugin
D: Plugin: calling hook psm_post in syslog plugin
D: Plugin: calling hook tsm_post in syslog plugin
D: ========== +++ filesystem-1.1-4.ph1 x86_64/linux 0x0
D: ========== +++ glibc-2.22-26.ph1 x86_64/linux 0x2
D: ========== +++ ncurses-6.0-9.ph1 x86_64/linux 0x2
D: ========== +++ bash-4.3.48-3.ph1 x86_64/linux 0x2
D: ========== +++ openssl-1.0.2r-1.ph1 x86_64/linux 0x2
D: ========== +++ pkg-config-0.28-3.ph1 x86_64/linux 0x2
D: ========== +++ ca-certificates-20190521-1.ph1 x86_64/linux 0x0
D: ========== +++ libssh2-1.8.2-1.ph1 x86_64/linux 0x2
D: ========== +++ libdb-5.3.28-1.ph1 x86_64/linux 0x2
D: ========== +++ libsolv-0.6.19-6.ph1 x86_64/linux 0x2
D: ========== +++ elfutils-libelf-0.169-4.ph1 x86_64/linux 0x2
D: ========== +++ file-5.24-3.ph1 x86_64/linux 0x2
D: ========== +++ pcre-8.41-2.ph1 x86_64/linux 0x2
D: ========== +++ glib-2.47.6-3.ph1 x86_64/linux 0x2
D: ========== +++ rpm-4.13.0.2-1.ph1 x86_64/linux 0x2
D: ========== +++ hawkey-2014.1-6.ph1 x86_64/linux 0x2
D: ========== +++ curl-7.59.0-7.ph1 x86_64/linux 0x2
D: ========== +++ sqlite-autoconf-3.27.2-2.ph1 x86_64/linux 0x2
D: ========== +++ util-linux-2.27.1-4.ph1 x86_64/linux 0x2
D: ========== +++ vim-7.4-11.ph1 x86_64/linux 0x2
D: ========== --- curl-7.59.0-1.ph1 x86_64/linux 0x2
D: ========== --- util-linux-2.27.1-3.ph1 x86_64/linux 0x2
D: ========== --- glib-2.47.6-2.ph1 x86_64/linux 0x2
D: ========== --- sqlite-autoconf-3.22.0-3.ph1 x86_64/linux 0x2
D: ========== --- ca-certificates-20160109-5.ph1 x86_64/linux 0x0
D: ========== --- libssh2-1.8.0-1.ph1 x86_64/linux 0x2
D: ========== --- openssl-1.0.2o-2.ph1 x86_64/linux 0x2
D: ========== --- vim-7.4-9.ph1 x86_64/linux 0x2
D: ========== --- hawkey-2014.1-5.ph1 x86_64/linux 0x2
D: ========== --- libsolv-0.6.19-4.ph1 x86_64/linux 0x2
D: ========== --- rpm-4.13.0.1-4.ph1 x86_64/linux 0x2
D: ========== --- elfutils-libelf-0.169-1.ph1 x86_64/linux 0x2
D: ========== --- file-5.24-2.ph1 x86_64/linux 0x2
D: ========== --- db-6.1.26-2.ph1 x86_64/linux 0x2
D: ========== --- pkg-config-0.28-2.ph1 x86_64/linux 0x2
D: ========== --- pcre-8.41-1.ph1 x86_64/linux 0x2
D: ========== --- ncurses-6.0-8.ph1 x86_64/linux 0x2
D: ========== --- bash-4.3.48-2.ph1 x86_64/linux 0x2
D: ========== --- glibc-2.22-19.ph1 x86_64/linux 0x2
D: ========== --- filesystem-1.1-3.ph1 x86_64/linux 0x0
D: closed db index /var/lib/rpm/Packages
D: closed db index /var/lib/rpm/Enhancename
D: closed db index /var/lib/rpm/Supplementname
D: closed db index /var/lib/rpm/Suggestname
D: closed db index /var/lib/rpm/Recommendname
D: closed db index /var/lib/rpm/Transfiletriggername
D: closed db index /var/lib/rpm/Filetriggername
D: closed db index /var/lib/rpm/Sha1header
D: closed db index /var/lib/rpm/Sigmd5
D: closed db index /var/lib/rpm/Installtid
D: closed db index /var/lib/rpm/Dirnames
D: closed db index /var/lib/rpm/Triggername
D: closed db index /var/lib/rpm/Obsoletename
D: closed db index /var/lib/rpm/Conflictname
D: closed db index /var/lib/rpm/Providename
D: closed db index /var/lib/rpm/Requirename
D: closed db index /var/lib/rpm/Group
D: closed db index /var/lib/rpm/Basenames
D: closed db index /var/lib/rpm/Name
D: closed db environment /var/lib/rpm
Error(-1) : Unknown error -1601
"

How can I fix this problem?

**Comment by jackalsh** [comment]
We have same problem

Steps to reproduce:
docker run -it vmware/photon:1.0 /bin/bash
In the shell run:
tdnf upgrade -y

Command ends with:
`
/var/tmp/rpm-tmp.RvQbnI: line 1: sed: command not found
/var/tmp/rpm-tmp.RvQbnI: line 4: sed: command not found
Error(-1) : Unknown error -1601
`

Same exception happens when using image vmware/photon:2.0
When using image vmware/photon:3.0 I get completely different exception: 
`
docker: Error response from daemon: manifest for vmware/photon:3.0 not found
`
But this tag exists in DockerHub.

**Comment by ahnselina** [comment]
change "FROM vmware/photon:1.0" to "FROM photon:2.0", then solve the problem
