### ISSUE TITLE
how to offline upgrade / update photon 2.0 or create local repo

### ISSUE THREAD

**Issue by csyeow** [vmware/photon#906]
hi 

i am new to photon 2.0, i try to find out the step to create local repo and other photon 2.0 vm able to update//upgrade from my local repo.

in centos i will using reposync and createrepo to create local repo.

i try to read document https://vmware.github.io/photon/assets/files/html/1.0-2.0/ but still cant figure out how to create local repo

my question as below, hope some one able to assists 
1. which command (tdnf  or rpm-ostree) should i use to upgrade photon 2.0 vm ? 
2. do photon 2.0 provide reposync and create repo command to create local repo ?
3. if using rpm-ostree to create local repo, any step to mirror internet repo to local repo (refer to create rpm-ostree server and mirror officer repo to local rpm-ostree server)

**Comment by suezzelur** [comment]
Unfortunately, reposync is not a tool that is present in Photon.

**Comment by csyeow** [comment]
hi suezzelur 

thanks for information, 
which command should i use to upgrade photon 2.0 rpm-ostree or tdnf ?
thanks in advance

**Comment by suezzelur** [comment]
tdnf
There is a package called photon-upgrade, which has a script that can be run to upgrade to the new version. This again requires a remote repo. Let us know if you need additional info
