### ISSUE TITLE
Module:hfs and hfsplus missing

### ISSUE THREAD

**Issue by chenliu1993** [vmware/photon#907]
Hi, I am trying to load hfs and hfsplus module into photon-esx, but there is no modules provides. So I built one myself based on official linux-${version}. But when I rum 'insmod hfs.ko', error ' missing symbol: kmem_cache_alloc_trace missing'
Is there any way I can fix this? 
Thanks very much!

Photon OS version:
linux-esx-4.9.137-1.ph2.x86_64

**Comment by srivatsabhat** [comment]
Hi @chenliu1993 

I tried to do the same and it worked well for me. So let me share the steps I used below and you can see if it works for you.

[ linux version I used : `linux-4.9.182` ]

`wget https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.9.182.tar.xz`
`tar -xf linux-4.9.182.tar.xz`
`cd linux-4.9.182`
`cd fs/hfs`
# Since linux-esx config doesn't enable HFS, edit the Makefile:
replace
	`obj-$(CONFIG_HFS_FS) += hfs.o`
with
	`obj-m += hfs.o`
(with no change in indentation of course).

`tdnf install linux-esx-devel -y`

While still being in the fs/hfs directory in your kernel source code, run:

`make -C /lib/modules/4.9.182-1.ph2-esx/build M=$PWD`
`insmod hfs.ko`

(and similarly for `hfsplus`)

**Comment by chenliu1993** [comment]
Got it! Thank you very much!

**Comment by chenliu1993** [comment]
> make -C /lib/modules/4.9.182-1.ph2-esx/build M=$PWD

Is there a way to download a specific version of esx linux-kernel-devel? I run 'tdnf install linux-esx-devel -y'? then the newest version will be downloaded.

**Comment by chenliu1993** [comment]
> tdnf install linux-esx-devel -y

How can i download a older version of linux-kernel-devel? 'tdnf install linux-esx-devel -y' always download the newest one.

**Comment by srivatsabhat** [comment]
> > make -C /lib/modules/4.9.182-1.ph2-esx/build M=$PWD
> 
> Is there a way to download a specific version of esx linux-kernel-devel? I run 'tdnf install linux-esx-devel -y'? then the newest version will be downloaded.

Try running `tdnf install linux-esx-devel-4.9.137-1.ph2`. That should get you the specific version that you want.

**Comment by chenliu1993** [comment]
> > > make -C /lib/modules/4.9.182-1.ph2-esx/build M=$PWD
> > 
> > 
> > Is there a way to download a specific version of esx linux-kernel-devel? I run 'tdnf install linux-esx-devel -y'? then the newest version will be downloaded.
> 
> Try running `tdnf install linux-esx-devel-4.9.137-1.ph2`. That should get you the specific version that you want.

It gives me the 'no package .... avaliable'. I tried to downgrade but it can only be downgraded to 4.19.15

**Comment by chenliu1993** [comment]
> > > make -C /lib/modules/4.9.182-1.ph2-esx/build M=$PWD
> > 
> > 
> > Is there a way to download a specific version of esx linux-kernel-devel? I run 'tdnf install linux-esx-devel -y'? then the newest version will be downloaded.
> 
> Try running `tdnf install linux-esx-devel-4.9.137-1.ph2`. That should get you the specific version that you want.

This is my tdnf repolist results:
photon-updates      VMware Photon Linux 2.0(x86_64) Updates enabled
photon-extras       VMware Photon Extras 2.0(x86_64)        enabled
photon              VMware Photon Linux 2.0(x86_64)         enabled

**Comment by srivatsabhat** [comment]
> > > > make -C /lib/modules/4.9.182-1.ph2-esx/build M=$PWD
> > > 
> > > 
> > > Is there a way to download a specific version of esx linux-kernel-devel? I run 'tdnf install linux-esx-devel -y'? then the newest version will be downloaded.
> > 
> > 
> > Try running `tdnf install linux-esx-devel-4.9.137-1.ph2`. That should get you the specific version that you want.
> 
> It gives me the
> 'No package linux-esx-devel-4.9.137-1.ph2 available
> Error(1011) : No matching packages'.
> 

Actually, are you sure that your linux-esx version is 4.9.137-1? Because I can only see the 4.9.137-2 rpm on bintray (http://dl.bintray.com/vmware/photon_updates_2.0_x86_64/x86_64/).

Can you try installing linux-esx-devel-4.9.137-2.ph2 ?

Also can you share the output of `tdnf list linux-esx-devel` ?

> I tried to downgrade but it can only be downgraded to 4.19.15

That's strange! There are no 4.19.* kernels in Photon 2.0; they are available only in Photon 3.0.

**Comment by chenliu1993** [comment]
> > > > > make -C /lib/modules/4.9.182-1.ph2-esx/build M=$PWD
> > > > 
> > > > 
> > > > Is there a way to download a specific version of esx linux-kernel-devel? I run 'tdnf install linux-esx-devel -y'? then the newest version will be downloaded.
> > > 
> > > 
> > > Try running `tdnf install linux-esx-devel-4.9.137-1.ph2`. That should get you the specific version that you want.
> > 
> > 
> > It gives me the
> > 'No package linux-esx-devel-4.9.137-1.ph2 available
> > Error(1011) : No matching packages'.
> 
> Actually, are you sure that your linux-esx version is 4.9.137-1? Because I can only see the 4.9.137-2 rpm on bintray (http://dl.bintray.com/vmware/photon_updates_2.0_x86_64/x86_64/).
> 
> Can you try installing linux-esx-devel-4.9.137-2.ph2 ?
> 
> Also can you share the output of `tdnf list linux-esx-devel` ?
> 
> > I tried to downgrade but it can only be downgraded to 4.19.15
> 
> That's strange! There are no 4.19.* kernels in Photon 2.0; they are available only in Photon 3.0.

1.tdnf repolist shows 2.0 because I change it because I think it may be the solution which actually didn't help, Sorry for the misunderstanding infomation I post.
2.This is what uname -r shows:
    4.9.137-1.ph2-esx
3.This is what tdnf list linux-esx-devel shows:
   linux-esx-devel.x86_644.19.15-2.ph3photon-updates
   linux-esx-devel.x86_644.19.29-1.ph3photon-updates
   linux-esx-devel.x86_644.19.32-2.ph3photon-updates
   linux-esx-devel.x86_644.19.32-3.ph3photon-updates
   linux-esx-devel.x86_644.19.40-2.ph3photon-updates
   linux-esx-devel.x86_644.19.52-1.ph3photon-updates
   linux-esx-devel.x86_644.19.15-1.ph3photon.

And I found the linux-esx-kernel 4.9.137 version. Thank you for your patient answers.☺

**Comment by srivatsabhat** [comment]
No problem! Glad I could help and happy to know that the problem is resolved :-)
