### ISSUE TITLE
Intel e1001e 3.2.6-k driver will drop packets

### ISSUE THREAD

**Issue by dave-redfern** [vmware/photon#908]
I know this isn't the intended use case, but I installed PhotonOS onto a Lenovo M720p Tiny to run primarily as a docker host. Initially this worked really well, but then my SSH sessions started to get very laggy and ping times to the gateway were sporadic. I then tried Fedora 30 and experienced the exact same thing. It turned out the network driver that is bundled in the 4.X kernel branch appears to have some major bugs probably to do with power management (https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1785171), that will exhibit on any I219 based network chip.

On Fedora 30 I was able to compile up a new version of the driver from the sourceforge page (https://sourceforge.net/projects/e1000/files/e1000e%20stable/3.4.2.4/) and load it into the kernel (after removing the current one). That resolved the network issues under F30 entirely.

I later re-installed PhotonOS 3 but this time with a bunch of BIOS tweaks to turn off power management and it had been working fine for the last couple of weeks. I had to power off and move the box around and now the network issue is back. I believe it is the driver again. I did previously try to compile a driver for Photon but was unable to load it as the kernel doesn't support module loading?? Admittedly I am out of my depth on that front.

Kernel version: `Linux photon 4.19.40-3.ph3 #1-photon SMP Wed Jun 5 03:46:15 UTC 2019 x86_64 GNU/Linux`

The driver messages from dmesg:
```
[    1.503627] e1000e: Intel(R) PRO/1000 Network Driver - 3.2.6-k
[    1.503627] e1000e: Copyright(c) 1999 - 2015 Intel Corporation.
[    1.503903] e1000e 0000:00:1f.6: Interrupt Throttling Rate (ints/sec) set to dynamic conservative mode
[    1.951760] e1000e 0000:00:1f.6 0000:00:1f.6 (uninitialized): registered PHC clock
[    2.039624] e1000e 0000:00:1f.6 eth0: (PCI Express:2.5GT/s:Width x1) <snip>
[    2.039626] e1000e 0000:00:1f.6 eth0: Intel(R) PRO/1000 Network Connection
[    2.039687] e1000e 0000:00:1f.6 eth0: MAC: 13, PHY: 12, PBA No: FFFFFF-0FF
[    7.497917] e1000e: eth0 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: Rx/Tx
```
ifconfig -a:
```
eth0      Link encap:Ethernet  HWaddr <snip>  
          inet addr:192.168.1.5  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: <snip> Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:4234 errors:782 dropped:0 overruns:0 frame:391
          TX packets:3994 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:1775688 (1.7 MB)  TX bytes:590310 (590.3 KB)
          Interrupt:17 Memory:b1200000-b1220000 
```
Here's a ping test to the local gateway:
```
PING 192.168.1.1 (192.168.1.1) 56(84) bytes of data.
64 bytes from 192.168.1.1: icmp_seq=1 ttl=255 time=524 ms
64 bytes from 192.168.1.1: icmp_seq=2 ttl=255 time=1008 ms
64 bytes from 192.168.1.1: icmp_seq=3 ttl=255 time=1.35 ms
64 bytes from 192.168.1.1: icmp_seq=4 ttl=255 time=1016 ms
64 bytes from 192.168.1.1: icmp_seq=5 ttl=255 time=2.15 ms
64 bytes from 192.168.1.1: icmp_seq=6 ttl=255 time=55.7 ms
64 bytes from 192.168.1.1: icmp_seq=7 ttl=255 time=1006 ms
64 bytes from 192.168.1.1: icmp_seq=8 ttl=255 time=2.30 ms
64 bytes from 192.168.1.1: icmp_seq=9 ttl=255 time=1016 ms
64 bytes from 192.168.1.1: icmp_seq=10 ttl=255 time=2.48 ms
64 bytes from 192.168.1.1: icmp_seq=11 ttl=255 time=45.1 ms
64 bytes from 192.168.1.1: icmp_seq=12 ttl=255 time=446 ms
64 bytes from 192.168.1.1: icmp_seq=13 ttl=255 time=1028 ms
64 bytes from 192.168.1.1: icmp_seq=14 ttl=255 time=1.68 ms
64 bytes from 192.168.1.1: icmp_seq=15 ttl=255 time=606 ms
64 bytes from 192.168.1.1: icmp_seq=16 ttl=255 time=76.3 ms
```
Is there any chance of getting the more recent driver integrated into the PhotonOS kernel? From my own tests on F30 the newer driver resolved the issues, and that has been reported as fixing the issue in the Ubuntu thread linked earlier too. It's possible that this driver issue may impact people who do PCI pass-thru with this chipset, though not sure it is embedded on any external NICs or not.

Other than this driver issue, Photon has been fine on real hardware and I've not had any other issues.

**Comment by YustasSwamp** [comment]
Thanks for reporting the issue.
Interesting to know, that we have Photon OS bare metal users.
Module loading works. In our Kernel e1000e driver is built in the kernel that's why I was not able to load the module.
We will investigate this and definitely will need more info from you.

**Comment by dave-redfern** [comment]
@YustasSwamp Let me know what you need and I'll do my best to get it.

**Comment by dave-redfern** [comment]
Update: I hooked the M720 up to a monitor and keyboard to get into the BIOS. BIOS all fine, ASPM, WoL and other ethernet related power saving all disabled. Secure boot disabled, UEFI boot only enabled, Windows specific features disabled etc etc.

Booted Photon back up and tried to do the package update; this time it worked. All packages downloaded without issue and now ethernet is responding "normally". The only difference, I left the HDMI cable connected (keyboard disconnected). I have been running multiple ping tests with times <2ms as expected.

It appears that disconnecting the HDMI cable for whatever reason, seems to cause some kind of power management related glitch that interferes with the ethernet chipset - that's just bizarre! I don't think it's a hardware issue with the device. I still have the original NVMe drive with Windows 10 I can use to do other diagnostics if necessary though.

I am curious to know if a more recent e1001e driver resolves this weirdness and will allow headless mode to work.

**Comment by dave-redfern** [comment]
Following up on this: I bought a $10 HDMI monitor faker adaptor (whatever you want to call it) and now I can restart without an external monitor connected. The driver still seems to be broken for the I219 chipset. Hopefully the later driver versions will get merged into the kernel.

**Comment by YustasSwamp** [comment]
Hi Dave,

Can you do this experiment:
1) to boot directly to the Linux and to try to reproduce the issue.
2) to boot Windows and then _reboot_ in to Linux, and try to reproduce.

Hypotheses: Windows might be using enhanced features of the network chip but Linux does not, and Linux does not drop them on reboot, and this features remain in the state initialized by Windows.

**Comment by dave-redfern** [comment]
I don't have Windows installed on the current SSD. I do have Windows 10 on the original M2 SSD (never used it) so I could switch those around, but I cannot then reboot back to Photon. It would have to be a power off and switch the SSD over - probably negating that test unfortunately.

To re-produce in Linux all I have to do is remove the HDMI dongle (or external monitor) and restart. Within a few minutes I'll start getting packet loss.

**Comment by YustasSwamp** [comment]
We've got Intel NUC with same chip, will try to repro there. Thanks again.

**Comment by dave-redfern** [comment]
@YustasSwamp I can try this weekend with the original SSD, but I'd have to setup Ubuntu or Fedora instead of Photon on the Win SSD. Right now I need the box as it's my docker host for work.

**Comment by YustasSwamp** [comment]
If it happens just on Linux after poweroff cycle, then I do not see the point in this experiment.

**Comment by ssahani** [comment]
Closing as I agree with @YustasSwamp .
