### ISSUE TITLE
Photon 3.0 GA kickstart issue in Dell GW3000

### ISSUE THREAD

**Issue by PlaylikeaRaven** [vmware/photon#913]
Hey Guys,

I've try the installation script in the website for GW3000 (photon-3.0-26156e2.iso)
1.Use USB tool to download the ISO to USB
2.Change GRUB, Sample.ks
3.Boot with Legacy and found the system stock and show the following message.

"Failed to mount the cd, retry in a second"

ever try to take a look for some of the error message.

dmesg grep cdrom 
1. The initrd=initrd.img root=/dev/ram0 loglevel=3 photon.media=cdrom boot_IMAGE=vmlinuz.
grep fail ->no cdrom related found.

Do you have any guidance for the GA3.0 one or the GW3000 only test with GA2.0?

**Comment by YustasSwamp** [comment]
https://vmware.github.io/photon/assets/files/html/3.0/photon_installation/Installing-Photon-OS-on-Dell-300X.html

**Comment by suezzelur** [comment]
Please re-open if you are still facing issues after following the documentation

**Comment by PlaylikeaRaven** [comment]
Thanks, seems only put the file to let it work. Not that complicit with rufus. :)
