### ISSUE TITLE
pl2303 for aarch64

### ISSUE THREAD

**Issue by sooslaca** [vmware/photon#915]
hi team,

can pl2303 enabled as module in
[https://github.com/vmware/photon/blob/master/SPECS/linux/config_aarch64#L4593](https://github.com/vmware/photon/blob/master/SPECS/linux/config_aarch64#L4593)

just like it is enabled in
[https://github.com/vmware/photon/blob/master/SPECS/linux/config#L4164](https://github.com/vmware/photon/blob/master/SPECS/linux/config#L4164)
?

Thank you

**Comment by YustasSwamp** [comment]
Sure! can you describe your use case, please? RPi3, one more serial over USB?

**Comment by sooslaca** [comment]
hi @YustasSwamp , actually that's a really good question, I got no idea why I never thought of using onboard serial :) I did it today and works perfectly, thanks for the suggestion.

And I was also managed to cross-compile the pl2303 module with [build_spec.sh](https://github.com/vmware/photon/blob/master/tools/scripts/build_spec.sh) so I think we can close this thread.

Thanks for your reply.
