### ISSUE TITLE
License of vixDiskUtil.cpp

### ISSUE THREAD

**Issue by t-8ch** [vmware/photon#916]
It seems that `vixDiskUtil.cpp` is carrying an explicit  copyright notice negating the normal open source licensing of the rest of the toolchain. This would make it impossible to build an OVA image from the source repository.

```
/* *************************************************
 * Copyright 2007-2015 VMware, Inc.  All rights reserved.
 * *************************************************/
```

**Comment by sharathjg** [comment]
Can you elaborate on what it is specifically about this copyright statement that you feel prevents this file from being used to build an ova?

**Comment by t-8ch** [comment]
If I read it correctly the explicit "All rights reserved" inhibits the open source license of the whole project to apply to this file.

Especially because of the follwing note in `COPYING` (emphasis mine):

> The files of PhotonOS version 3.0 are licensed under the terms of the Apache License v2.0 or alternatively under the terms of the GNU General Public License (GPL) v2 **UNLESS otherwise noted at the beginning of the file** or a LICENSE file present in a directory subtree declares a separate license.


So the right to use (and study) this file still lies solely with VMware.

I am not a lawyer, but I discussed it with a colleague experienced with open source and he is of the same opinion. We both are uncomfortable to touch this file in any way in its current state.

**Comment by sharathjg** [comment]
That is a fairly common misinterpretation of the meaning of the ‘All rights reserved’ phrase. To avoid this confusion, we have removed the phrase from the Copyright notice.
