### ISSUE TITLE
How to get sound on aarch64 image

### ISSUE THREAD

**Issue by sooslaca** [vmware/photon#917]
Hi team,

Anyone supposedly have a guide on how to get onboard audio working on Raspberry Pi?

config.txt already has
```
hdmi_drive=1
# Enable audio (loads snd_bcm2835)
dtparam=audio=on
```

Modules are loaded:
```
root@rpi [ / ]# lsmod | grep snd
snd_bcm2835            36864  0
vchiq                 323584  1 snd_bcm2835
snd_pcm               114688  1 snd_bcm2835
snd_timer              36864  1 snd_pcm
snd                    77824  3 snd_bcm2835,snd_timer,snd_pcm
soundcore              16384  1 snd
```

But PCM device does not exist:
```
root@rpi [ / ]# ls -la /dev/snd/
total 0
drwxr-xr-x  2 root root       60 Jun 22  2018 .
drwxr-xr-x 14 root root     3380 Jul 17 16:47 ..
crw-rw----  1 root audio 116, 33 Jun 22  2018 timer
```

Thanks in advance.

**Comment by akaher** [comment]
@sooslaca, Thanks for reporting this issue.

This issue is because of missing audio entry in device tree i.e. /proc/device-tree/soc/audio.
Soon we will provide the device tree overlay support, using this you can add or enable audio.

/boot/config.txt is Raspbian OS specific file and with-in Photon OS you may not have the same behaviour.

**Comment by sooslaca** [comment]
thanks @akaher for your reply, I'll waiting for it and test once available.

**Comment by sooslaca** [comment]
hi @akaher, do you happen to have an ETA for this? Thanks

**Comment by akaher** [comment]
@sooslaca, it's in review.

**Comment by sooslaca** [comment]
hi @akaher , I see [this commit](https://github.com/vmware/photon/commit/d8b45846ad625a34d4e90b966893babe01cfd003) enabled device-tree for audio and it's in current update (vmlinuz-4.19.72-1.ph3)

I managed to get manually inserted like you wrote in your commit message:
```
root@rpi [ / ]# mkdir  /sys/kernel/config/device-tree/overlays/audio8
root@rpi [ / ]# cat /boot/broadcom/overlays/bcm2837-rpi-enable-audio.dtbo >  /sys/kernel/config/device-tree/overlays/audio8/dtbo
```
```
root@rpi [ / ]# ls -la /dev/snd/
total 0
drwxr-xr-x  3 root root      140 Sep 25 09:50 .
drwxr-xr-x 14 root root     3420 Sep 25 09:40 ..
drwxr-xr-x  2 root root       60 Sep 25 09:50 by-path
crw-rw----  1 root audio 116,  0 Sep 25 09:50 controlC0
crw-rw----  1 root audio 116, 16 Sep 25 09:50 pcmC0D0p
crw-rw----  1 root audio 116, 17 Sep 25 09:50 pcmC0D1p
crw-rw----  1 root audio 116, 33 Sep 25 09:40 timer
```

Can you help me please how I can insert it automatically on boot? what's the proper way? Just put this into somewhere in systemd to run one or there is a more sophisticated way to do that.

(not yet tested sound though, will feedback)

Thanks

**Comment by akaher** [comment]
Please try with /etc/profile as of now.
Thanks for having patience and above confirmation.

**Comment by sooslaca** [comment]
ended up with system service, sharing if someone might need it.

```
root@rpi [ ~ ]# cat /etc/systemd/system/overlay_audio.service
[Unit]
Description=Load audio overlay
ConditionFileNotEmpty=/boot/broadcom/overlays/bcm2837-rpi-enable-audio.dtbo
Before=docker.service

[Service]
Type=forking
ExecStart=/bin/sh -c 'if [ ! -f /sys/kernel/config/device-tree/overlays/audio8/dtbo ]; then \
            mkdir -p /sys/kernel/config/device-tree/overlays/audio8; \
            cat /boot/broadcom/overlays/bcm2837-rpi-enable-audio.dtbo > /sys/kernel/config/device-tree/overlays/audio8/dtbo; \
            fi'
TimeoutSec=0
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
```

Still yet to test sound...

**Comment by akaher** [comment]
@sooslaca, could we close this issue.
