### ISSUE TITLE
unsigned rpm packages

### ISSUE THREAD

**Issue by OrlinVasilev** [vmware/photon#918]
when trying to install something simple as unzip I'm getting RPM unsigned ..
cannot use --nogpgcheck since we have regulations that we must use only signed packages.

any ideas how to fix it?

root [ / ]# tdnf install -y unzip

Installing:
unzip                                                          x86_64                          6.0-13.ph3                                photon-updates                        265.27k 271641

Total installed size: 265.27k 271641

Downloading:
Error(1512) : RPM not signed. Use --nogpgcheck to ignore.

**Comment by dennisvanderpool** [comment]
root@photon1 [ ~ ]# tdnf update

Upgrading:
unzip                                                           x86_64                          6.0-13.ph3                                 photon-updates                         265.27k 271641                  
systemd                                                         x86_64                          239-12.ph3                                 photon-updates                        19.98M 20945949                  
libxml2                                                         x86_64                          2.9.9-1.ph3                                photon-updates                          7.30M 7650023                  
glib                                                            x86_64                          2.58.0-4.ph3                               photon-updates                          3.11M 3265152                  

Total installed size:  30.64M 32132765
Is this ok [y/N]:y

Downloading:
unzip                                   131373    100%
Error(1512) : RPM not signed. Use --nogpgcheck to ignore.

**Comment by OrlinVasilev** [comment]
same is valid for openjdk8 package ... not sure why is that though...

**Comment by suezzelur** [comment]
A few rpms with the latest updates had signature issues, we have removed and re-uploaded them, please re-check.

**Comment by dennisvanderpool** [comment]
Please re-open. I've still got the issue. Is there a temporary download dir where the old downloads are?

root@photon1 [ ~ ]# tdnf update

Upgrading:
unzip                                                  x86_64                      6.0-13.ph3                           photon-updates                  265.27k 271641
systemd                                                x86_64                      239-12.ph3                           photon-updates                 19.98M 20945949
libxml2                                                x86_64                      2.9.9-1.ph3                          photon-updates                   7.30M 7650023
glib                                                   x86_64                      2.58.0-4.ph3                         photon-updates                   3.11M 3265152

Total installed size:  30.64M 32132765
Is this ok [y/N]:y

Downloading:
Error(1512) : RPM not signed. Use --nogpgcheck to ignore.

**Comment by keerthanakalyan** [comment]
Could you please try with "tdnf --refresh update". It might be because of the older repocache in tdnf.

**Comment by dennisvanderpool** [comment]
Hi, did not help.

root@photon1 [ ~ ]# tdnf --refresh update
photon                                    1325    100%
Upgrading:
unzip                                                  x86_64                      6.0-13.ph3                           photon-updates                  265.27k 271641
systemd                                                x86_64                      239-12.ph3                           photon-updates                 19.98M 20945949
libxml2                                                x86_64                      2.9.9-1.ph3                          photon-updates                   7.30M 7650023
glib                                                   x86_64                      2.58.0-4.ph3                         photon-updates                   3.11M 3265152

Total installed size:  30.64M 32132765
Is this ok [y/N]:y

Downloading:
Error(1512) : RPM not signed. Use --nogpgcheck to ignore.

**Comment by dennisvanderpool** [comment]
root@photon1 [ ~ ]# tdnf --refresh clean all
Cleaning repos: photon photon-updates photon-extras00%
Cleaning up everything

Did not help either

**Comment by OrlinVasilev** [comment]
on my side everything looks ok now .. thanks

**Comment by smaliakkal** [comment]
@dennisvanderpool , Could you clear your cache , /var/cache/tdnf/photon-updates and retry ?

**Comment by dennisvanderpool** [comment]
@smaliakkal Yes, that worked, thanks :)
