### ISSUE TITLE
Problems with build essentials instructions

### ISSUE THREAD

**Issue by markpeek** [vmware/photon#919]
1. Install the Photon OS 3.0 OVA image [here](http://dl.bintray.com/vmware/photon/3.0/GA/ova/photon-hw13_uefi-3.0-26156e2.ova)
1. Update using ```tdnf distro-sync```
1. Follow the instructions [here](https://github.com/vmware/photon/wiki/Frequently-Asked-Questions#q-how-to-install-all-build-essentials) to install the build essentials.
1. Note when running ```wget -qO- https://get.docker.com/ | sh``` this error occurs:
```
root@photon-machine [ ~ ]# wget -qO- https://get.docker.com/ | sh
-bash: wget: command not found
```

Fix: either add wget to the build essentials list or add ```tdnf -y install wget``` to the instructions.

After installing wget, try running the command again:
```
root@photon-machine [ ~ ]# wget -qO- https://get.docker.com/ | sh
# Executing docker install script, commit: 6bf300318ebaab958c4adc341a8c7bb9f3a54a1a
Warning: the "docker" command appears to already exist on this system.

If you already have Docker installed, this script can cause trouble, which is
why we're displaying this warning and provide the opportunity to cancel the
installation.

If you installed the current Docker package using this script and are using it
again to update Docker, you can safely ignore this message.

You may press Ctrl+C now to abort this script.
+ sleep 20

ERROR: Unsupported distribution 'photon'
```

OK, let's add docker...
```
root@photon-machine [ ~ ]# tdnf -y install docker
Package docker is already installed.
Nothing to do.
```

Doh! Already there...

**Comment by ppadmavilasom** [comment]
should have been "tdnf install -y build-essential" instead got swapped with docker install instructions. will fix
