### ISSUE TITLE
 ip_vs_rrw, ip_vs_sh modules are missing from config-esx

### ISSUE THREAD

**Issue by artw** [vmware/photon#920]
Two modules that are required by kube-proxy in ipvs mode are missing from config-esx. These are present in every other kernel
```
CONFIG_IP_VS_WRR=m
CONFIG_IP_VS_SH=m
```
[https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/ipvs/README.md](url)

**Comment by YustasSwamp** [comment]
Assume branch is 3.0. Fixed in linux-esx-4.19.65-3.ph3

**Comment by artw** [comment]
thanks!
