### ISSUE TITLE
Unable to Reset Root Password

### ISSUE THREAD

**Issue by vampire337** [vmware/photon#921]
Using the latest version of Photon 3.0, VM hardware version 14, UEFI enabled (VBS unchecked).  I am trying to reset the root password, following the instructions at https://vmware.github.io/photon/assets/files/html/3.0/photon_troubleshoot/resetting-a-lost-root-password.html

Unfortunately, after I type in the "rw init=/bin/bash" on the Linux line and press F10, my VM console goes to black and doesn't do anything (I've let it sit up to half an hour and no dice). If I go to the Grub menu and just press F10 it works fine (except I don't have the password for this VM).  I notice that the commands default in my Grub are different from those pictured in the screenshot in the walkthrough. I've used tab to confirm it is finding /bin/bash (so I'm not missing a vmdk somewhere). No matter what I do I get a black screen when I press F10 on this screen:
![image](https://user-images.githubusercontent.com/3717803/63116137-dd302480-bf66-11e9-9d33-9417e51c0557.png)

**Comment by vampire337** [comment]
Anyone available to confirm or offer a bone?

**Comment by vampire337** [comment]
Well, I tried a number of permutations of the init= string that I found on the web, and nothing worked with my VM, so I moved onto the next best thing...  Hopefully this helps someone in my position:
1. I deployed a new Photon OS VM. I updated and rebooted the new VM.
2. I shut down my original VM.
3. I added the VMDK of the old VM to the new VM.
4. Via SSH terminal to the new VM I entered `lsblk` to confirm that the new VMDK was mounted as /dev/sdb (/dev/sdb1 and /dev/sdb2).
5. I created a temporary folder "temp" in /mnt/.
6. I edited /etc/fstab and added the following:
`/dev/sdb1	/mnt/temp	ext4	defaults	0	0`
7. I mounted the filesystem from my old VM in the new VM.
`mount /mnt/temp/`
8. I copied the first line from /etc/shadow and pasted it over the first line in /mnt/temp/etc/shadow (it starts with root:).
9. I saved my changes to /mnt/temp/etc/shadow.
10. I unmounted the VMDK from my new VM
`unmount /mnt/temp`
11. I powered on my old VM.
12. I logged onto my old VM using the password on my new VM.

**Comment by lostinfuture** [comment]
Same issue for me

**Comment by YustasSwamp** [comment]
What actually happening is kernel booted and bash process started, but efi framebuffer driver is not loaded (because init=bash, nobody loads the module)

Fixed in linux-esx-4.19.65-3.ph3 by moving EFI_FB driver from module to kernel.
To make it working - update linux-esx package.

Thanks!

**Comment by vampire337** [comment]
Just confirmed this now works. Thanks @YustasSwamp!

**Comment by CondormanFr** [comment]
I have the same issue.
How to :

> update linux-esx package.

**Comment by vampire337** [comment]
tdnf distro-sync

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________
