### ISSUE TITLE
Failing tdnf distro-sync updating cloud-init 19.2-2 on Photon 3.0

### ISSUE THREAD

**Issue by vampire337** [vmware/photon#922]
When attempting to run tdnf distro-sync on a freshly deployed Photon 3.0 (photon-hw13_uefi-3.0-26156e2.ova):
```
Error: 404 when downloading https://dl.bintray.com/vmware/photon_updates_3.0_x86_64/noarch/cloud-init-19.1-2.ph3.noarch.rpm
. Please check repo url.
Error(1622) : Invalid argument
```

![image](https://user-images.githubusercontent.com/3717803/63290554-9e181100-c28f-11e9-94c7-75a56b7c5d63.png)

**Comment by suezzelur** [comment]
Can you refresh the cache and try again? 
`tdnf distro-sync --refresh`

**Comment by vampire337** [comment]
> Can you refresh the cache and try again?
> `tdnf distro-sync --refresh`

Appears to work now. Thanks for whatever magic you worked in the background!

**Comment by suezzelur** [comment]
> Appears to work now. Thanks for whatever magic you worked in the background!
The 19.1 cloud-init rpm had to be removed due to some deployment issues leaving stray metadata in the repo, which had to be refreshed.
