### ISSUE TITLE
Unable to mount an NFS share with the RPI image

### ISSUE THREAD

**Issue by bvivi57** [vmware/photon#923]
Hello,
I use several PhotonOS machines. I mix VMs (OVA) and RPI3. The same NFS sharing can be easily mounted on my VMs but does not work on my RPIs. 
PhotonOS is up to date on my RPI.
I encounter the error: mount.nfs: Protocol not supported

On RPI version PhotonOS : 

_mount -vv -t nfs storage.coolcorp.priv:/volume1/docker /mnt/nfs/
mount.nfs: timeout set for Mon Aug 19 22:17:05 2019
mount.nfs: trying text-based options 'vers=4.2,addr=192.168.10.152,clientaddr=192.168.10.82'
mount.nfs: mount(2): Protocol not supported
mount.nfs: trying text-based options 'vers=4,minorversion=1,addr=192.168.10.152,clientaddr=192.168.10.82'
mount.nfs: mount(2): Protocol not supported
mount.nfs: trying text-based options 'vers=4,addr=192.168.10.152,clientaddr=192.168.10.82'
mount.nfs: mount(2): Protocol not supported
mount.nfs: trying text-based options 'addr=192.168.10.152'
mount.nfs: prog 100003, trying vers=3, prot=6
mount.nfs: trying 192.168.10.152 prog 100003 vers 3 prot TCP port 2049
mount.nfs: prog 100005, trying vers=3, prot=17
mount.nfs: trying 192.168.10.152 prog 100005 vers 3 prot UDP port 892
mount.nfs: Protocol not supported_

On VM PhotonOS

_root@cluvm02 [ ~ ]# mount -vv -t nfs storage.coolcorp.priv:/volume1/docker /mnt/nfs/
mount.nfs: timeout set for Mon Aug 19 22:19:13 2019
mount.nfs: trying text-based options 'vers=4.2,addr=192.168.10.152,clientaddr=192.168.10.84'
mount.nfs: mount(2): Protocol not supported
mount.nfs: trying text-based options 'vers=4,minorversion=1,addr=192.168.10.152,clientaddr=192.168.10.84'
mount.nfs: mount(2): Protocol not supported
mount.nfs: trying text-based options 'vers=4,addr=192.168.10.152,clientaddr=192.168.10.84'
mount.nfs: mount(2): Protocol not supported
mount.nfs: trying text-based options 'addr=192.168.10.152'
mount.nfs: prog 100003, trying vers=3, prot=6
mount.nfs: trying 192.168.10.152 prog 100003 vers 3 prot TCP port 2049
mount.nfs: prog 100005, trying vers=3, prot=17
mount.nfs: trying 192.168.10.152 prog 100005 vers 3 prot UDP port 892_

**Comment by bvivi57** [comment]
Hi
I found the problem. I must install " iana-etc" package. 
It seems to be installed as a base with the OVA version and "nfs-utils" is enough, but on the RPI image, you have to install "iana-etc" in addition to "nfs-utils".

**Comment by YustasSwamp** [comment]
Thanks, @bvivi57. Good to know that!
