### ISSUE TITLE
Photon 3 minimal (aka esx flavor) does not include kernel module - docker not starting

### ISSUE THREAD

**Issue by mxb78** [vmware/photon#924]
Docker not starting under Photon 3 esx-flavor (install_linux_esx: true)  -- missing a lot of modules.
Example is aufs, bridge etc.

**Comment by YustasSwamp** [comment]
Can you provide steps to reproduce docker failure, please?

**Comment by vampire337** [comment]
Without the steps you took to get there, I might not have the right answer for your exact scenario, but when I deploy the OVA to my (ESXi 6.7) host I have to enter "systemctl start docker" to actually start the docker component. Actually, when I deploy a new instance of Photon, I always log onto the console and do the following:
1. Update the password (it makes you do this)
2. "tdnf distro-sync"
3. "y"
4. "systemctl enable docker"
5. "reboot"
Updates and a clean reboot are just a good start to any new appliance, imo.

**Comment by mxb78** [comment]
I tried to reproduce this without success.
I PXE-installed photon 3.0 (files came from photon-3.0-26156e2.iso) and after 'tdnf update' with reboot, I was able to start dockerd.
I'll try without 'tdnf update'.

my kickstart for photon:

{
    "hostname": "photon-baseinstall",
    "password":
        {
            "crypted": true,
            "text": "<passwd>" 
        },
    "disk": "/dev/sda",
    "partitions": [
                        {"mountpoint": "/", "size": 0, "filesystem": "ext4"},
                        {"mountpoint": "/boot", "size": 128, "filesystem": "ext4"},
                        {"mountpoint": "/root", "size": 128, "filesystem": "ext4"},
                        {"size": 128, "filesystem": "swap"}
                    ],
    "packagelist_file": "packages_minimal.json",
    "additional_packages": ["vim", "lvm2"],
    "postinstall": [
                        "#!/bin/sh",
                        "echo \"PubkeyAcceptedKeyTypes ssh-dss\" >> /etc/ssh/sshd_config",
                        "systemctl restart sshd.service"
                   ],
    "install_linux_esx": true,
    "public_key": "<key>"

}

**Comment by mxb78** [comment]
hm, this is really odd. It worked even without update.
