### ISSUE TITLE
[Question] Is there a pbcopy/xclip alternative for PhotonOS?

### ISSUE THREAD

**Issue by CollinChaffin** [vmware/photon#925]
Since there is no xclip package in photon, even attempting to grab the rpm from CentOS then needs missing/unavailable X11 libs.

I'm hoping someone has an alternative they have tested that works on Photon to simply be able to push shell to/from the clipboard.

TIA!

**Comment by YustasSwamp** [comment]
Clipboard in Photon console? 
Sorry, I didn't get you. Can you provide more details, please?

**Comment by YustasSwamp** [comment]
If you are looking for copy/paste, you need to ssh to Photon using your preferable terminal and use copy/paste there.

Thanks.
