### ISSUE TITLE
Feature Request: Raspberry Pi 4 Support

### ISSUE THREAD

**Issue by johncchampion** [vmware/photon#926]
With the new Pi 4 release, a supported Photon image utilizing the increased memory, USB3, and 1GB NIC would be very useful.

**Comment by webzrout** [comment]
Lol...

**Comment by akaher** [comment]
Thanks @johncchampion for this Feature Request. 
We also would like to have Photon OS 64-bit on Raspberry Pi 4 and soon we will work on this.

**Comment by proofquantu** [comment]
Any progress / news on Photon OS for RPI4 ?  

Have all the rpi4's been hijacked by the esxi on arm team?  ;-)

**Comment by akaher** [comment]
We have considered this request, new images need to release for Rpi4 as H/W is different from Rpi3.
Please let us know your requirement which would require Photon OS on Rpi4.

**Comment by proofquantu** [comment]
Thank you for your consideration.

Requirements:
Pretty much the same reasons as running photonOS on rpi3 - but would like to use the faster cpu, more ram etc on a pi4
Having the same container optimised OS running on vms (vsphere) and rpi means I can re-use the same automation playbooks across virtual and physical platforms.

Specifically, I'm running 4x rpi3 nodes with photonOS using nomad+consul for scheduling to run clustered piHole.
Looking to migrate/experiment with kubernetes on same rpi3 stack but would prefer to use rpi4's to run more containers

Nice to have:
cloudinit read metadata + userdata from sd card fat partititon (/boot)  to simplify deployment of multiple pi's

Based on your 12th Sept comment "We also would like to have Photon OS 64-bit on Raspberry Pi 4 and **soon we will work on this.**"  I thought I'd ask how it was going.

This page is the #1 result for the google search "photonOS on rpi4"

**Comment by akaher** [comment]
Thanks for using Photon OS and sharing your Requirements.

**Comment by afreeman28** [comment]
what is the current status of Photon OS support on Raspberry pi 4?

**Comment by akaher** [comment]
You could try this one:
https://packages.vmware.com/photon/4.0/Beta/rpi/rpi-4.0-d98e681.tar.xz

Refer known issues here: 
https://github.com/vmware/photon/wiki/What-is-New-in-Photon-OS-4.0
If HDMI not working. Comment out line starts with 'dtoverlay=' from config.txt of FAT32 Partition.

**Comment by ssahani** [comment]
Please test with 4.0 GA https://github.com/vmware/photon/wiki/Downloading-Photon-OS

**Comment by theCiscoGeek** [comment]
I wanted to post a quick comment on this since nobody responded - I have briefly tested the latest 4.0 GA on both a 4gb and 8gb pi4. Basic operations seem to work great, although I didn't test anything crazy.

**Comment by ssahani** [comment]
Thanks @theCiscoGeek . @akaher I think this can be closed then ?

**Comment by akaher** [comment]
@theCiscoGeek Thanks for the update.
