### ISSUE TITLE
Docker slow startup

### ISSUE THREAD

**Issue by ImMaury** [vmware/photon#928]
Docker takes about 3 minutes to start after a system reboot. I'm experiencing this issue on ESXi 6.5 U2 (HPE custom image) using the OVA file with virtual hardware v13 (which should be compatible with ESXi 6.5). Using the ISO image and the OVA file with virtual hardware v11, Docker is fast to start.

These are the commands I use to test the issue using a fresh install:

1. yum upgrade
2. systemctl enable docker
3. reboot

After the reboot, Docker takes approximately 3 minutes to start (I check with systemctl status docker).

Let me know if I need to show any log file.

**Comment by YustasSwamp** [comment]
Is it still reproducible? I would like to analyze some boot log files.

**Comment by premar** [comment]
Had the same problem and was able to trace it back to the network. After the restart, the server had no IP. So I assume he tried to get it with dhcp. After deleting the config 99-static-en.network in /etc/systemd/network/, the server boots without problems.

**Comment by ImMaury** [comment]
In the end I switched from ESXi to Proxmox and I'm not using PhotonOS any more, so I cannot gather the boot logs.
