### ISSUE TITLE
[Request] yum-utils support

### ISSUE THREAD

**Issue by CollinChaffin** [vmware/photon#930]
I have struggled to make my own package on this, and since there has never apparently been a build spec for PhotonOS I am putting in the request.

Since MANY packages seem to not install properly or even pull proper depends with tdnf, it would REALLY help to be able to at least have the means to pull down from CentOS repo a package tree that _would_ run on Photon, but just doesn't because it's not in the repo (think Mono because of broken xamarin depends - and many others).

TIA!

**Comment by YustasSwamp** [comment]
Adding yum-utils will not resolve the initial concern.
Unfortunately, RPMs from CentOS repo won't work on Photon OS, but CentOS container will.

Closing the bug as won't fix.
