### ISSUE TITLE
Question: How to automate the initial password change

### ISSUE THREAD

**Issue by nanw1103** [vmware/photon#933]
By default, Photon has root password "changeme", and mandates password change upon the first login. How to automate the initial password change in vSphere environment?

**Comment by dcasota** [comment]
There were blog articles see https://www.virtuallyghetto.com/2017/09/automating-vm-keystrokes-using-the-vsphere-api-powercli.html and see http://www.lucd.info/2018/08/14/deploy-photon-2-0-part-1/ (+part2) describing the use of the powershell cmdlet functionality Set-VMKeystrokes for change Photon OS default root password. HTH

**Comment by nanw1103** [comment]
Thanks dcasota.

**Comment by nanw1103** [comment]
ping 127.1 > nul
govc vm.keystrokes -vm.ipath=%VM_BUILD_BASE_IPATH% -s "root"
govc vm.keystrokes -vm.ipath=%VM_BUILD_BASE_IPATH% -c 0x28
ping 127.1 > nul
govc vm.keystrokes -vm.ipath=%VM_BUILD_BASE_IPATH% -s "changeme"
govc vm.keystrokes -vm.ipath=%VM_BUILD_BASE_IPATH% -c 0x28
ping 127.1 > nul
govc vm.keystrokes -vm.ipath=%VM_BUILD_BASE_IPATH% -s "changeme"
govc vm.keystrokes -vm.ipath=%VM_BUILD_BASE_IPATH% -c 0x28
ping 127.1 > nul
govc vm.keystrokes -vm.ipath=%VM_BUILD_BASE_IPATH% -s "HlcmDeployer3"
govc vm.keystrokes -vm.ipath=%VM_BUILD_BASE_IPATH% -c 0x28
ping 127.1 > nul
govc vm.keystrokes -vm.ipath=%VM_BUILD_BASE_IPATH% -s "HlcmDeployer3"
govc vm.keystrokes -vm.ipath=%VM_BUILD_BASE_IPATH% -c 0x28
ping 127.1 > nul
