### ISSUE TITLE
[Bug] GnuPG is missing on PhotonOS v3

### ISSUE THREAD

**Issue by nop144d** [vmware/photon#937]
'gpg' command which is particularly used for checking package (rpm) signatures is missing on Photon. Please consider adding it for security reasons.

**Comment by ppadmavilasom** [comment]
gnupg provides this

**Comment by nop144d** [comment]
Agree, but this is something that I think should be pre-installed and tested. Almost all VMware products are migrating to PhotonOS, lots of installed stuff relies on 'gpg'.

**Comment by ppadmavilasom** [comment]
gnupg is available in photon repos. you can install it as needed (tdnf install gnupg -y)

**Comment by suezzelur** [comment]
Please have your product bundle this in the build process.
