### ISSUE TITLE
where is domain from DHCP server

### ISSUE THREAD

**Issue by rbucker** [vmware/photon#940]
the network config is not pulling the domain from DHCP and applying it resolv.conf.

**Comment by ssahani** [comment]
Are you using networkd ?  then it should be ```/run/systemd/resolve/resolv.conf``` . Please create a symlink. to ```/etc/resolv.conf```

**Comment by rbucker** [comment]
I have a DHCP server in my network that photon is using to get it's IP, however, it is not pulling the DOMAIN name and adding it to ```/etc/systemd/network/99-dhcp-en.network``` and by extension ```/etc/resolv.conf```. I had to edit ```/etc/systemd/network/99-dhcp-en.network``` and then reboot.

my point is photonos is not setting the search attribute unless I hardcode it.

**Comment by ssahani** [comment]
networkd does not update the config file ```/etc/systemd/network/99-dhcp-en.network``` . 
Please use ```UseDomains=```  to ` yes`. See https://www.freedesktop.org/software/systemd/man/systemd.network.html#UseDomains=

No need to reboot just restart network.

**Comment by rbucker** [comment]
this does not work...  I tried to use ```yes``` instead of ```true``` both failed

```
[Match]
Name=e*

[Network]
DHCP=yes
IPv6AcceptRA=no

[DHCPv4]
useDomain=true
```

**Comment by rbucker** [comment]
And :

```
$ sudo systemctl restart networkd
Failed to restart networkd.service: Unit networkd.service not found.
```

**Comment by ssahani** [comment]
photon uses version 239 so use . 
```
[DHCP]
useDomains=true
```
DHCPv4 and DHCPv6 options got different  section though it has backward compatibility.

```systemctl restart systemd-networkd```

**Comment by rbucker** [comment]
no change

```
[Match]
Name=e*

[Network]
DHCP=yes
IPv6AcceptRA=no

[DHCP]
useDomains=true
```

**Comment by ssahani** [comment]
You need to restart ```systemd-resolved```  too if that does not work capture dhcp packets via tcpdump and attach. Let's confirm your DHCP server is sending the domains.

Also you can see ```networkctl status [interface]``` to see whether networkd has saved domains in it's states file.

**Comment by ssahani** [comment]
Please provide debugging logs of networkd. The log can be generated by creating e.g. the following drop-in config:

```
# /etc/systemd/system/systemd-networkd.service.d/override.conf
[Service]
Environment=SYSTEMD_LOG_LEVEL=debug
```

**Comment by rbucker** [comment]
```
"/etc/systemd/system/systemd-networkd.service.d/override.conf"                                                                                                                                                                
"/etc/systemd/system/systemd-networkd.service.d/override.conf" E212: Can't open file for writing
Press ENTER or type command to continue
```

**Comment by rbucker** [comment]
in the logfile:

```
/etc/systemd/network/99-dhcp-en.network:9: Unknown lvalue 'useDomains' in section 'DHCP'
```

**Comment by rbucker** [comment]
and I tried this because the doc said to

```
/etc/systemd/network/99-dhcp-en.network:9: Unknown lvalue 'useDomains' in section 'DHCPv4'
```

**Comment by rbucker** [comment]
OK, got it......

```UseDomains=```   need to CAP the U and the D

Also... certainly was ```[DHCP]``` and not ..v4

Logs helped... needed to create the missing folder.

THAKS!
