### ISSUE TITLE
likewise-open - assumedefaultdomain

### ISSUE THREAD

**Issue by jeffrson** [vmware/photon#947]
Hi,

I joined my domain by likewise-open's domainjoin-cli. I can log in via SSH with user
DOMAIN\username or username@DOMAIN.
Then I set the AssumeDefaultDomain flag, which works fine, actually. Now I can use username to log in.
However, now I cannot log in with root anymore. Obviously, I don't have a DOMAIN\root user - but shouldn't local users be preferred? At least this is what I'd experienced with Samba or sssd previously.

Edit: It seems. that after "domainjoin-cli configure --enable ssh" I can login as root again (but, of course, I have to do this before activating AssumeDefaultDomain, because otherwise I don't have a privileged account left).

**Comment by ppadmavilasom** [comment]
please open this in https://github.com/vmware/likewise-open
