### ISSUE TITLE
likewise-open - sudoers

### ISSUE THREAD

**Issue by jeffrson** [vmware/photon#948]
Hi,

I joined my domain by likewise-open's domainjoin-cli. I can log in via SSH with user
DOMAIN\username or username@DOMAIN.

With or without the AssumeDefaultDomain flag I cannot get the system to accept my domain username in /etc/sudoers - it works however with groups (DOMAIN\group).

Is this known? Intentional?

Edit: Also, adding DOMAIN\username to group "sudo" does not work with AssumeDefaultDomain - it does, however, without this flag. Strange thing: id username does only show remote (AD) groups - no local (neither sudo nor docker). Needless to say, docker doesn't work as well for this user.
The group thing might be another issue...

**Comment by ppadmavilasom** [comment]
please open this in https://github.com/vmware/likewise-open
