### ISSUE TITLE
likewise-open - create home directory

### ISSUE THREAD

**Issue by jeffrson** [vmware/photon#949]
Hi,

I joined my domain by likewise-open's domainjoin-cli. I can log in via SSH with user
DOMAIN\username or username@DOMAIN.

Unfortunately, although there's the flag CreateHomeDir, the home directory /home/local/DOMAIN/username is not created. It seems this is due to /home/local/DOMAIN not existing.

Of course I can create /home/local/DOMAIN manually, but the actual home directory is not created, because it appears that write permission is missing?! What permissions should /home/local/DOMAIN have?

**Comment by ppadmavilasom** [comment]
please open this in https://github.com/vmware/likewise-open
