### ISSUE TITLE
cloud.cfg not having (harmless) modules enabled by default

### ISSUE THREAD

**Issue by sooslaca** [vmware/photon#950]
hi,

what's the sense behind not enabling all - harmless - modules by default?

Like power_state:
https://github.com/vmware/photon/blob/ca433bd21aaae69b4ac022917a6667aa77d0168c/SPECS/cloud-init/cloud-photon.cfg#L96

If no `power_state:` section is in the user-data file then it does nothing.

Problem is without it a custom image needs to be built where `power-state-change` is enabled in `cloud.cfg`, doesn't it?

Thanks

**Comment by lucdekens** [comment]
+1 on this request

**Comment by sshedi** [comment]
Check the latest cloud-init (version 19.1-8), all harmless options are enabled by default.

**Comment by sshedi** [comment]
@suezzelur - can we close this issue?
