### ISSUE TITLE
Unable to reset ADMIN PW on UAG

### ISSUE THREAD

**Issue by TFDocta** [vmware/photon#951]
Hi Guys,

I'm unable to reset my UAG admin password for my hosts running Photon OS. 

I can log into root, but cant reset the admin password. 

I have tried the firstboot.properties reset method to no avail unfortunately. 

Could I get some assistance if possible?

**Comment by dcasota** [comment]
Have you tried to redeploy UAG with use of another password for the admin account? It may be a password complexity issue, and afaik, Gui-deployed, it does not tell you that.

You may find more specific Horizon UAG appliance-related information in communities.vmware.com, and in https://docs.vmware.com/en/Unified-Access-Gateway release notes.

**Comment by sharathjg** [comment]
Id request you to take this up with UAG support. closing this as there is non default OS configuration involved.
