### ISSUE TITLE
Support for CNI plugin version 0.8.x

### ISSUE THREAD

**Issue by thanhy** [vmware/photon#952]
We need CNI plugin upgrade to version 0.8.x.  

https://github.com/hashicorp/nomad/issues/6689

**Comment by idrennanvmware** [comment]
+1 

Updating the CNI to the latest version would help with the same issue mentioned by @thanhy 

Could someone from the Photon team comment on the effort required to do this?

**Comment by suezzelur** [comment]
https://github.com/vmware/photon/commit/5819ee089b1b854394ee1991ac6240c0d58c6973 takes care of this in 3.0
