### ISSUE TITLE
Photon 3.0 r2 pxe boot install fail repo= not handled properly

### ISSUE THREAD

**Issue by kl1059** [vmware/photon#953]
Photon 3.0 pxe boot installs with repo=http://192.168.1.1/RPMS/ fine
./installer/iso_config.py detects repo= in the kernel args and sets rpm_path accordingly

In Photon 3.0 Rev 2 pxe boot installs fail, repo= is no longer correctly handled

in ./installer/isoInstaller.py repo_path = options.repo_path which may not be null

later "if not repo_path: repo_path = arg[len("repo="):]

perhaps the "if not repo_path:" at line 32 should be removed?

**Comment by cbsiddharth** [comment]
@kl1059, not sure what you mean. The repo path passed to isoInstaller.py takes precedence over that sent over kernel command line.

`options.repo_path` will be None if command line switch `-r/--repo-path` is not passed to isoInstaller.py. In that cases, it will look for kernel command line to have `repo=`. For this reason, we must have the `if not repo_path:` condition.

Let me know if this helps.

**Comment by YustasSwamp** [comment]
In Photon 3.0 Rev 2 we introduced command line parameter '--repo-path' for isoInstaller.py.
And it has higher priority over kernel 'repo=' parameter.

If '--repo-path' is not set, then kernel's 'repo=' will be used.

What kind of installation failure are you facing? Can you attach screenshot or /var/log/installer.log file, please?

**Comment by kl1059** [comment]
PXE boot install of photon-3.0 succeeds

PXE boot install of photon-3.0 rev 2 fails just after answering Yes to the
partitioning step.  repo= is ignored.  the installer tries to mount the
CD/DVD device and this fails.

pxe cfg entries:
LABEL Photon Linux 3.0 Revision 2
MENU LABEL Photon Linux 3.0 Revision 2
kernel photon-3.0.2/vmlinuz
append initrd=photon-3.0.2/initrd.img root=/dev/ram0 loglevel=3 repo=http://192.168.1.1/photon-3.0.2-RPMS/

LABEL Photon Linux 3.0
MENU LABEL Photon Linux 3.0
kernel photon-3.0/vmlinuz
append initrd=photon-3.0/initrd.img root=/dev/ram0 loglevel=3 repo=http://192.168.1.1/photon-3.0-RPMS/
[installer.log](https://github.com/vmware/photon/files/3867060/installer.log)
![Screenshot from 2019-11-19 20-17-14](https://user-images.githubusercontent.com/7696398/69204531-bad11880-0b0c-11ea-8b41-d8fc30b1360b.png)

**Comment by YustasSwamp** [comment]
From the log file I see 'repo' was set to /mnt/cdrom/RPMS. Which seems incorrect.
Looks like it was forced to that value in /bin/bootphotoninstaller script. Hmm regression.

After you have "Oops, Installer got interrupted", press Ctrl+C and then
1) Modify this script by running:
`sed -i 's@ -r /mnt/cdrom/RPMS@@' /bin/bootphotoninstaller`
2) Run installer again:
`/bin/bootphotoninstaller`

**Comment by kl1059** [comment]
the change to /bin/bootphotoninstaller works!  we will make a new initrd with this change.  thanks.

this did, however, raise another issue which would only be seen by a pxe boot with an http repo.

the mode of the rpm files on the 3.0 CD are 644.

most of the rpm files on the 3.0 rev 2 CD have the execute bit lit and some http servers do not like to serve executeable files if they are not explicity declared as cgi.

it is a minor nitpick and we can change the mode of files on the http server easily.

**Comment by YustasSwamp** [comment]
Glad that it worked. We are fixing it right now.
Thank you for pointing to file permissions issue, will address it as well.

**Comment by YustasSwamp** [comment]
updated 3.0 r2 bits.
