### ISSUE TITLE
Network unstable - vmxnext3

### ISSUE THREAD

**Issue by vthinsel** [vmware/photon#954]
Hello,

We deployed an 8 node swarm cluster using Photon 3, on top of a VxRail cluster. It works pretty well except the fact at network is pretty unstable : at some poitn of time, several VMs will loose connectivity, and show messages in logs such as "TX hangs". We de-activated TSO and GSO cluster wide on the hosts but there are still issues : IPVS: rr: FWM ...... no destination available
This is very annoying, and VMWare is not providing support for Photon OS. I'll try with other distro to see if the problems come from other layers (physical network,....).
If interested, I have the VM support packages available.
Any hints on this issue ?
Thanks

**Comment by ssahani** [comment]
>We deployed an 8 node swarm cluster using Photon 3, on top of a VxRail cluster. It works pretty well except the fact at network is pretty unstable :

 There is no way I can figure out what is going on in your system. Can you provide the logs and your conf.  How you configure your network ?

**Comment by vthinsel** [comment]
Network is based on a standard DVS, everything on a flat network, using default vmxnet3 drivers.
Would attaching the vm-support file help or would you require other infoat the same time ?

**Comment by ssahani** [comment]
I am sorry. I am bit confused. Are you opened this against photons os networking.

**Comment by dcasota** [comment]
Might be a Docker Volume Service DNS related issue ("IPVS: rr: FWM ...... no destination available") when backend goes down for a while ("unstable").

**Comment by vthinsel** [comment]
I do not know if this is photon OS, photon networking stack, of photon vmxnet3 drivers issue but by just changing the template from photon to centos in the terraform file that deploys all the docker swarm platform, all network instability problems diseappeared. Docker version is also more advanced on the CentOS 

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:24:18 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
