### ISSUE TITLE
Installation Failure

### ISSUE THREAD

**Issue by VenomousToucan** [vmware/photon#955]
I'm getting the following while trying to install a photon instance onto a server.

Photon-installer login: root (automatic login)
mount: /mbt/cdrom: special device /dev/cdrom does not exist.
Failed to mount the cd, retry in a second
mount: /mbt/cdrom: special device /dev/cdrom does not exist.
Failed to mount the cd, retry in a second
mount: /mbt/cdrom: special device /dev/cdrom does not exist.
Failed to mount the cd, retry in a second
Failed to mount the cd, exiting the installer
check the logs for more details
Traceback (most recent  last call):
   File "./isoInstaller.py", line 139 in <module>
      IsoInstaller(options)
   File "./isoInstaller.py', line 42, in __init__
      self.mount_cd(cd_search)
   File "./isoInstaller.py", line 127 in mount_cd
      raise Exception("Can not mount the cd")
Exception: Can not mount the cd

This server dose not have not should it ever have a CD drive so the fact that the ISO is demanding one when trying to install from a USB drive that did mount correctly is odd. Any suggestions or am I just stuck compiling my own ISO rather then using the prebuilt one?

**Comment by YustasSwamp** [comment]
Did you try to add kernel parameter:
photon.media=UUID=<usb drive partition UUID here>
or
photon.media=LABEL=<usb drive partition LABEL here>
in the installer boot screen?

**Comment by VenomousToucan** [comment]
I Tried both with several failures. Looks like it was due to using a NTFS file system on the USB drive and when I tried to install it on a FAT32 one the ISO kept saying the files were to big for the 4GB limit.

Looked at this hardware and Decided to go with Ubuntu server here and try photon again in a few days on some of the other systems in this server cluster. Thanks for the suggestions.
