### ISSUE TITLE
Detailed information on how to contribute to Photon

### ISSUE THREAD

**Issue by dcasota** [vmware/photon#956]
Is it possible to get more information on how to contribute to Photon?

I have read the [Contributing guidelines](https://github.com/vmware/photon/blob/master/contributing.md) and the [FAQ](https://cla.vmware.com/faq), but in reference to
```Before submitting a pull request, please make sure that you can build Photon OS. See Building an ISO from the Source Code for Photon OS.``` the [Build-Photon-weblink](https://github.com/vmware/photon/blob/master/docs/build-photon.md) provided does not work, but it could be this [weblink ](https://vmware.github.io/photon/assets/files/html/3.0/photon_installation/build_the_iso.html)(?). 

Git clone works, however I'm not sure if Github Code display contains the latest source as some Photon OS packages installed are newer as the source code upfront (???). 

Where to progress officially sign an ICLA? (I'm simply a VMware enthusiast!)

**Comment by suezzelur** [comment]
It should be https://github.com/vmware/photon/blob/master/docs/photon_installation/build-photon.md, we will fix that link.
You will be notified to sign the CLA once you send a pull request.

**Comment by dcasota** [comment]
link works, thanks for the quick replay!
