### ISSUE TITLE
Additional rpms install failure does not fail the build

### ISSUE THREAD

**Issue by nikhail** [vmware/photon#958]
Photon installer supports this "additional_rpms" feature to slipstream bunch of rpms during the ova build. However if the additional rpms fail to install, then the overall build does not fail, that rpm install failure gets logged and errors is suppressed from further escalation.
https://github.com/vmware/photon/blob/e282ee3d7704998f21dddd6c52af9c1dd1b6918e/installer/installer.py#L825
```
        if self.cmd.run(['rpm', '--root', self.photon_root, '-U', rpms_path + '/*' ]) != 0:
            self.logger.info('Failed to install additional_rpms from ' + rpms_path)    # <=== error suppressed, missing self.exit_gracefully() after this line?
```
This makes it difficult to judge whether the built ova really does have additional rpms installed or not (scraping logs for a specific log message is really quite awkward way to determine build errors).

**Comment by suezzelur** [comment]
29171080eaddc2e1e15ece77ddf1299ee1f202a5
