### ISSUE TITLE
Installing coreutils (after removing toybox) is missing some utils

### ISSUE THREAD

**Issue by ayashjorden** [vmware/photon#959]
Steps:
1. Boot photon Docker image `docker run -ti photon:3.0 `
2. `tdnf erase -y toybox`
3. `tdnf install -y coreutils`

Result is that `find` and `sed` and probably others are missing.

Found that while trying to compile nodejs12 from source.

**Comment by YustasSwamp** [comment]
You need to install findutils and sed in addition to coreutils.
`tdnf install -y findutils sed`
