### ISSUE TITLE
typo at /var/log/maillog file in rsyslog.conf

### ISSUE THREAD

**Issue by gflex** [vmware/photon#960]
file is https://github.com/vmware/photon/blob/master/SPECS/rsyslog/rsyslog.conf
Currently content is as:
```
# Log all the mail messages in one place.
mail.*                                                  /var/log/maillog"
```

whereas it must be 

```
# Log all the mail messages in one place.
mail.*                                                  /var/log/maillog
```
thus maillog is saved in `/var/log/maillog"` file

**Comment by tapakund** [comment]
Thanks @gflex for reporting this issue. We will fix this.

**Comment by tapakund** [comment]
Fixed with https://github.com/vmware/photon/commit/a98f72cff64d32ea8911273cd5da76ff1ebe17a4
