### ISSUE TITLE
Make sure the photon 2.0 trust the CA of AWS RDS

### ISSUE THREAD

**Issue by reasonerjt** [vmware/photon#961]
Hello, Harbor leverages photon 2.0 base docker image.

There are use case that Harbor use AWS RDS as database service.

I'm notified that the RDS CA certificate will be rotated:
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL-certificate-rotation.html

May I confirm if the new CA is trusted by the photon 2.0 image on docker hub?

**Comment by YustasSwamp** [comment]
Thanks for the info, we will double check.
