### ISSUE TITLE
3.0R2 cloud-init prevents networking

### ISSUE THREAD

**Issue by FredFoo** [vmware/photon#962]
I try a PXE/kickstart install of minimal Photon OS 3.0 build 49d932d. The basic user and meta data files are copied into seed/nocloud by kickstart during install. When the instance comes up, cloud-init local starts and then I get a 2 minute timeout of the systemd-networkd-wait-online service. When you login after the boot is finished the network is down and you can activate it using systemctl restart systemd-networkd. I tried with iptables service deactivated, but no change. I can see on the host using tcpdump that no dhcp requests are send by the instance.

In the log, the error that kicks is `sd-netlink: callback failed: Invalid argument`. Googled it, not knowing more now.

When you reboot the machine a second time, everything works as intended - no network issues. 

Cannot find out what cloud init local does that caused it. Running `cloud-init --debug init --local` looks totally harmless and I dont know where to look.

Any ideas?

Attaching two logs, one from the first boot that fails and one from the second that succeeds. 

[bad.log](https://github.com/vmware/photon/files/4009046/bad.log)
[good.log](https://github.com/vmware/photon/files/4009049/good.log)

**Comment by ssahani** [comment]
May be related to https://github.com/systemd/systemd/issues/10320 . Please paste the `.network `file

**Comment by FredFoo** [comment]
The only .network in the system is the original, untouched version that got installed and it contains

```[Match]
Name=e*

[Network]
DHCP=yes
IPv6AcceptRA=no
```

**Comment by FredFoo** [comment]
Just had this idea of setting kernel parameter `ipv6.disable=1` - but did not change the behaviour a bit. Staring at the timeout counter again ... :)

**Comment by ssahani** [comment]
> Just had this idea of setting kernel parameter `ipv6.disable=1` - but did not change the behaviour a bit. Staring at the timeout counter again ... :)

No its not related to this. Error message would have been permission denied

**Comment by FredFoo** [comment]
There is an [older issue on systemd](https://github.com/systemd/systemd/issues/9759) that might be related - deals with what the system thinks the hostname is.

**Comment by ssahani** [comment]
If I backport it can you test?

**Comment by ssahani** [comment]
I have back ported that now . Once updated I will update you.

**Comment by FredFoo** [comment]
I did move on since then and worked around this problem. But I can try your package once we get there.

**Comment by YustasSwamp** [comment]
Thanks for the update.
Closing as for now, reopen with the updates if you mind.
