### ISSUE TITLE
Vivace SPEC files license

### ISSUE THREAD

**Issue by krishgan** [vmware/photon#966]
Hello Photon Team,

Happy New Year!

Could you kindly clarify the license for the Vivace SPEC files? We would like to use the SPEC files and contribute fixes as needed.

Best,
Krishna

**Comment by snambakam** [comment]
Hi Krishna,

Wish you a Happy New Year!

We have determined that the license for the Vivace SPEC files should be similar to the one for the Photon projeect. We will get this updated soon.

Thanks for offering to contribute to this effort!

**Comment by YustasSwamp** [comment]
License file has been updated.
