### ISSUE TITLE
default route 0.0.0.0 appears on interface lo0

### ISSUE THREAD

**Issue by AaronArb** [vmware/photon#967]
Hi all,

Forgive me if this is not the place to ask, but I cannot find a forum somewhere that deals with photon support.

I have just deployed 2 instances of photon-hw13_uefi-3.0-9355405.ova and when i configure the network card via creating a .network file in the /etc/systemd/network directory I get a route for 0.0.0.0 via interface lo0 which ultimately causes the machine to lose network connectivity.

Am I doing something wrong?

following doco i found 'somewhere' the .network file is below

```
[match]
Name=eth0

[Network]
DHCP=no
Address=192.168.203.28/24
Gateway=192.168.203.1
Domains=ensat.local
DNS=192.168.1.10
DNS=192.168.1.11
```

To fix this I simply issue a 
`route delete -net 0.0.0.0 `
command and it removes the lo0 default route and all is well again.

**Comment by ssahani** [comment]
>I get a route for 0.0.0.0 via interface lo0 

I can't reproduce this . Which version of systemd is this? `rpm -qi systemd` . Could you set SYSTEMD_LOG_LEVEL=debug environment variable to generate debugging logs? Please create a drop-in config file like the following
```
# /etc/systemd/system/systemd-networkd.service.d/override.conf
[Service]
Environment=SYSTEMD_LOG_LEVEL=debug
```

```
root@photon-85fd68af8149 [ /etc/systemd/network ]# cat 99-dhcp-en.network
[Match]
Name=e*

[Network]
DHCP=no
IPv6AcceptRA=no
Address=XX.XXX.195.57
Gateway=XX.XXX.195.253
```

```
root@photon-85fd68af8149 [ /etc/systemd/network ]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 00:0c:29:19:49:0a brd ff:ff:ff:ff:ff:ff
    inet XX.XXX.195.57/8 brd 10.255.255.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::20c:29ff:fe19:490a/64 scope link
       valid_lft forever preferred_lft forever

ip route
default via XX.XXX.195.253 dev eth0 proto static
XX.0.0.0/8 dev eth0 proto kernel scope link src XX.XXX.195.57

```

**Comment by AaronArb** [comment]
I am using the OVA that I specified in the original question that is published, so whatever version that is... I will fire up a new VM of this (I am using the other 2 that I have) now and report back for you.

**Comment by AaronArb** [comment]
In the process of generating this for you I found the problem

I had 

`[match]`

instead of 

`[Match]`

turns out case really does matter

**Comment by YustasSwamp** [comment]
Thanks!
