### ISSUE TITLE
kickstart documentation clarification

### ISSUE THREAD

**Issue by rui-su-bnet** [vmware/photon#969]
Looking at the https://github.com/vmware/photon/blob/master/docs/photon_user/kickstart.md documentation mentions install_linux_esx, if we enable this option does this mean that kickstart will install the esxi optimized linux instead of the standard linux?
```
"install_linux_esx":"true"
```
How do you crypt the password?  (any examples will be welcome)
```
password:
crypted: true/false

text: password text
```

**Comment by YustasSwamp** [comment]
1) correct.
2) "crypted": "false"
     "text": "mypassword"
or
    "crypted": "true"
    "text": <encrypted password here> - content for 2nd column of /etc/shadow file (see https://www.cyberciti.biz/faq/understanding-etcshadow-file/)

**Comment by rui-su-bnet** [comment]
Thank you @YustasSwamp I will make a pull request against the documentation to improve upon it
