### ISSUE TITLE
ISO build is failing due to Maven Central switching to HTTPS only

### ISSUE THREAD

**Issue by 195858** [vmware/photon#972]
The make iso target fails e.g. for cassandra and lightwave as during the build processes attempts are being made to retrieve files from Maven Central repos using HTTP.

This has been disabled as of January 15 ... see https://support.sonatype.com/hc/en-us/articles/360041287334

**Comment by YustasSwamp** [comment]
What branch do you use? Can you attach corresponding build log file please?

**Comment by YustasSwamp** [comment]
closing as not enough info. We are not seeing issues with these packages in our internal builds.
