### ISSUE TITLE
Kernel Update fails Secure Boot

### ISSUE THREAD

**Issue by harryhmtse** [vmware/photon#974]
Performed tdnf update on a Photon VM, which updated
linux-esx to 4.19.87-5.ph3
Upon restarting the VM, the bootloader reports invalid signature on the primary and the fallback entries, performs a restart, and hangs at the boot splash screen.  Escaping the boot splash screen will show that it's dropped into the GRUB shell.  

It can be worked around by disabling Secure Boot setting on the Virtual Machine.

**Comment by ecerichter** [comment]
Same problem here!

**Comment by harryhmtse** [comment]
Issue persists in 4.19.97-1.ph3

**Comment by gizmotronic** [comment]
I downgraded to the 4.19.87-1 kernel to get back up and running with UEFI Secure Boot enabled, testing each version along the way. So far the following versions all fail to boot:

4.19.87-4
4.19.87-5
4.19.97-1

**Comment by ecerichter** [comment]
Seems support requests are not getting attention, I'll just fallback to more supported OS distro like CentOS.

**Comment by YustasSwamp** [comment]
Reason: Secure boot certificate in the virtual firmware has expired.

Solution: Now we sign kernel images with new key, and its certificate has to be added to firmware manually, as for now, here is a link: https://github.com/vmware/photon/wiki/Frequently-Asked-Questions#q-after-updating-Kernel-rpm-VM-fails-to-boot-with-secure-boot

**Comment by harryhmtse** [comment]
@YustasSwamp thanks for the update.  This sounds like it's going to need to be resolved through an update of the hosting ESXi-based product.  (vSphere, Fusion, Workstation), is this already in the pipeline or should we be submitting support tickets for those products?

**Comment by YustasSwamp** [comment]
You are right.
There are 2 possible solutions to resolve it.
1) update of the hosting ESXi-based product, as you've mentioned - will be available soon.
2) update Photon's shim to include new certificate -  in process, there is some delay on shin-review side: https://github.com/rhboot/shim-review/issues/75

**Comment by harryhmtse** [comment]
Thanks @YustasSwamp for the clarification and the workaround, I think you've put us all at ease explaining the problem, and letting us know there's a fix in the pipeline, and knowing that this ticket isn't just going to go stale.

**Comment by Megachip** [comment]
Running into the same issue. Disabling secure boot seems not working (will be enabled automatically again :(

**Comment by YustasSwamp** [comment]
@Megachip try this:
- power off VM
- disable secure boot
- remove .nvram file in VM folder
- power on VM

**Comment by ElanHasson** [comment]
This fixed it for me:
https://github.com/vmware/photon/wiki/Frequently-Asked-Questions#q-after-updating-kernel-rpm-vm-fails-to-boot-with-secure-boot

**Comment by gizmotronic** [comment]
That's a useful workaround, @ElanHasson, thanks! Unfortunately it doesn't scale well, so I'm still hoping for an ESXi update to land soon.

**Comment by r24-IT** [comment]
Fresh install of OVA, update... dead. That shouldn't happen :(

**Comment by YustasSwamp** [comment]
Agree. Fix here is to release new shim (with updated certificate) signed by UEFI CA.
And it is blocked at shim-review stage for several months already ((

So, current workaround is to inject current certificate to the firmware as describer here:
https://github.com/vmware/photon/wiki/Frequently-Asked-Questions#q-after-updating-Kernel-rpm-VM-fails-to-boot-with-secure-boot

**Comment by mmlakin** [comment]
The workaround in the FAQ did not resolve this for me.  I had to disable secure boot by deleting these lines from the VMX file:

```
uefi.secureBoot.enabled = "TRUE"
uefi.secureBoot.dbDefault.file0 = "vmware_sb2017.der"
```

**Comment by YustasSwamp** [comment]
@mmlakin did you remove `nvram` file? What was the error, when it didn't boot?

**Comment by mmlakin** [comment]
Yes, I deleted the `.nvram` file every time I tried a change.  It gives the same error as before:

`error: /boot/vmlinuz-4.19.132-4.ph3-esx has invalid signature.`

I downloaded the certificate file again, deleted and re-uploaded the modified .vmx file a few times, tried all this again after a successful boot with secure boot disabled, and every time it gives the same error.  The only way I can get it to boot is with a .vmx file that doesn't contain the `eufi.secureBoot` parameters.

**Comment by YustasSwamp** [comment]
Thanks for update. We switched to different certificate because of BootHole issue. Will provide solution/update shortly.

**Comment by YustasSwamp** [comment]
@mmlakin bootloader binaries (with fixed BootHole vulnerability) have to be updated on your system

	1.	Download https://github.com/vmware/photon/raw/3.0/installer/EFI_x86_64/BOOT/bootx64.efi and https://github.com/vmware/photon/raw/3.0/installer/EFI_x86_64/BOOT/grubx64.efi
	2.	Copy downloaded binaries to /EFI/Boot folder of EFI Special Partition (ESP), replacing existing ones.
	⁃	ESP on Photon OS 3.0 rev2 is mounted to /boot/efi.
	⁃	Before 3.0 rev2 ESP can be found by running fdisk:  
		First 3 steps are only for "Before 3.0 rev2" instance
		# fdisk -l | grep "EFI System"
		/dev/sda2  10240    26623    16384   8M EFI System
		# mkdir -p /boot/efi
		# mount /dev/sda2 /boot/efi

		# cd /boot/efi/EFI/Boot
		# rm *.efi
		# wget  https://github.com/vmware/photon/raw/3.0/installer/EFI_x86_64/BOOT/bootx64.efi
		# wget https://github.com/vmware/photon/raw/3.0/installer/EFI_x86_64/BOOT/grubx64.efi
		# sha256sum *.efi
		bc5769ca377ed6c7149d884496f3602e905d7a8d4935b134557584543818ee2d  bootx64.efi
		c5c342488b5ff89f19120e44dde7ffdb169909db5c16603c7b8d52af749bb3d7  grubx64.efi

No needs to add vmware_sb2017.der certificate, but it does not harm.

**Comment by mmlakin** [comment]
Thanks for your quick responses!

Following those directions did not resolve my problem, and left me with an unbootable system.  I restored from backup so I'm all good now.

First, wget was not found so I used `curl -O` instead, and the directory on my system was `BOOT` and not `Boot` as listed in the instructions.  The shasum did change after replacing them with the newly downloaded binaries, but did not match the output in the instructions.
```
root@photon-machine [ ~ ]# cp bootx64.efi /boot/efi/EFI/BOOT
root@photon-machine [ ~ ]# cp grubx64.efi /boot/efi/EFI/BOOT
root@photon-machine [ ~ ]# sha256sum /boot/efi/EFI/Boot/*.efi
5559cec34ff09e7dc75e757cbf64f6a0655f24c4cbd825890abc66ea9c4c6fe3  /boot/efi/EFI/Boot/bootx64.efi
ff8c14de51ec089265ed14d8a97227226b1f866304241d34b824670dc7cfb609  /boot/efi/EFI/Boot/grubx64.efi
```

Also, I was able to download the dbxupdate, but when running  the command I got the following error:
```
root@photon-machine [ ~ ]# dbxtool -a ./dbxupdate_x64.bin
dbxtool only supports timestamped updates
```
Since I had a recent backup, I rebooted just to test it and my system could no longer boot, even with secure boot disabled.  No error message about signature this time, just a splash screen showing boot entries it tried, and then it showed a BIOS screen.  I restored and tried the entire process again, for good measure, deleting the old .efi files and re-downloading them in place and got the same result.  I've restored again and I'm just leaving secure boot off for now.

**Comment by YustasSwamp** [comment]
Hashsums of your binaries are incorrect. Here is what I have:
```
root@photon [ ~ ]# wget -q https://github.com/vmware/photon/raw/3.0/installer/EFI_x86_64/BOOT/grubx64.efi
root@photon [ ~ ]# wget -q https://github.com/vmware/photon/raw/3.0/installer/EFI_x86_64/BOOT/bootx64.efi
root@photon [ ~ ]# sha256sum *.efi
bc5769ca377ed6c7149d884496f3602e905d7a8d4935b134557584543818ee2d  bootx64.efi
c5c342488b5ff89f19120e44dde7ffdb169909db5c16603c7b8d52af749bb3d7  grubx64.efi
root@photon [ ~ ]# 
```

Regarding dbx update, try adding `-f` option:
```
root@photon [ ~ ]# dbxtool -a -f dbxupdate_x64.bin
Applying 1 updates
Applying "dbxupdate_x64.bin" 2010-3-6 19:17:21
```

**Comment by mmlakin** [comment]
Thanks, I got it working.  For whatever reason this photon install from the OVF doesn't have `wget`, so I needed to use `curl -L` for it to follow the redirect.  System is fully updated along with dbx and Secure Boot is working.  I appreciate your help!

**Comment by YustasSwamp** [comment]
Always welcome, and thank you for dogfooding our updated instructions.

**Comment by Megachip** [comment]
So funny 3/4 years later, photon updates and is dead :( Is that issue so hard to fix? 

So, I have a bunch of VM (on ESXi Hypervisors), which are now dead. How to fix this?

**Comment by Megachip** [comment]
> @mmlakin bootloader binaries (with fixed BootHole vulnerability) have to be updated on your system
> Please follow updated instructions:
> https://github.com/vmware/photon/wiki/Frequently-Asked-Questions#q-after-updating-kernel-rpm-vm-fails-to-boot-with-secure-boot
> No needs to add vmware_sb2017.der certificate, but it does not harm.

`cp: error writing '/boot/efi/EFI/Boot/grubx64.efi': No space left on device`

**Comment by mmlakin** [comment]
@Megachip I was able to resolve this issue by following the instructions in the FAQ.  From your error `No space left on device` it looks like your disk is full?  Check your disk usage with the `df` command; if you're near 100% on your boot volume, navigate to the root of this volume and use `du -h | sort -h` to find where you might be able to free up some space.

**Comment by Megachip** [comment]
> @Megachip I was able to resolve this issue by following the instructions in the FAQ. From your error `No space left on device` it looks like your disk is full? Check your disk usage with the `df` command; if you're near 100% on your boot volume, navigate to the root of this volume and use `du -h | sort -h` to find where you might be able to free up some space.

FAQ Is a bit useless in that case, cause the VM didn't boot, so you have to access the vmdk from Hypervisor. 
What temp. solved the issue for me is remove/comment the secure boot in the vmx and delete the .nvram ...  Than I can follow the FAQ, but seems the out of the box partition layout didn't fit to faq (maybe I've to delete the grubx64.efi instead of overwrite)

**Comment by YustasSwamp** [comment]
@Megachip did you try to remove 2 files from ESP first and then copy new ones?
Important to check sha sums of binaries before reboot.
What is the size of ESP partition you have?

**Comment by Megachip** [comment]
> Hashsums of your binaries are incorrect. Here is what I have:
> 
> ```
> bc5769ca377ed6c7149d884496f3602e905d7a8d4935b134557584543818ee2d  bootx64.efi
> c5c342488b5ff89f19120e44dde7ffdb169909db5c16603c7b8d52af749bb3d7  grubx64.efi
> ```

```
sha256sum *.efi
bc5769ca377ed6c7149d884496f3602e905d7a8d4935b134557584543818ee2d  bootx64.efi
9efbd619fa93f0fb694c422fd0160eabdcd7055ab3372d686871c3ca5f282d32  grubx64.efi
```
Strange
