### ISSUE TITLE
Install PostgreSQL 12 using RPM or YUM repository

### ISSUE THREAD

**Issue by ecerichter** [vmware/photon#975]
Trying to install the yum repository using

https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-42.0-6.noarch.rpm

I get error "missing redhat-release dependency"
I understand that pgdg-redhat-repo is related to redhat/centos/etc like rpm based install.

Is there any change on installing Postgresql from Postgresql own site?

**Comment by YustasSwamp** [comment]
Postgresql own site does not contain RPMs for Photon OS.

But you can try installing postgresql rpm for Redhat with --nodeps

rpm -Uvh --nodeps  postgresql*.rpm

**Comment by ssahani** [comment]
Closing because of lack of response.
