### ISSUE TITLE
Static IP address as boot option

### ISSUE THREAD

**Issue by pierreyves-lebrun** [vmware/photon#976]
I want to build a Photon OS template using Packer but my environment doesn't include a DHCP so the Photon OS VM can't ever get the kickstart file from Packer [http server](https://vmware.github.io/photon/assets/files/html/3.0/photon_user/kickstart_through_http.html).

Is there any way to specify a static IP address along with gateway information to the VM using boot_command?

With CentOS it is as easy doing the following:
`text ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/ks.cfg ip=IPADDRESS::GATEWAY:SUBNET:HOSTNAME:INTERFACE:none `

With Photon OS I would have to create a /etc/systemd/network/10-static-en.network file but as far as I know I cannot do that before installation.

**Comment by dcasota** [comment]
In reference to https://vmware.github.io/photon/assets/files/html/3.0/photon_user/kickstart.html you could use ```ks=cdrom:/isolinux/my_ks.cfg```, for copying services files the json field ```additional_files```, and setting a static IP address through the network json field.  Didn't try it out but the sample configuration file https://vmware.github.io/photon/assets/files/html/3.0/photon_user/kickstart.html#sample-configuration-file shows the way to go at least for dhcp.

**Comment by pierreyves-lebrun** [comment]
> In reference to https://vmware.github.io/photon/assets/files/html/3.0/photon_user/kickstart.html you could use `ks=cdrom:/isolinux/my_ks.cfg`, for copying services files the json field `additional_files`, and setting a static IP address through the network json field. Didn't try it out but the sample configuration file https://vmware.github.io/photon/assets/files/html/3.0/photon_user/kickstart.html#sample-configuration-file shows the way to go at least for dhcp.

I did think of similar workaround but rejected it because in my case the whole point of assigning a static IP address is to let the VM access my kickstart file through DHCP.

Additionally I kind of dislike the idea of customising the ISO as it somewhat defeats the purpose of building an image via a single Packer configuration file.

Though for the moment I'll go for the option you mentioned, accessing the kickstart file that way being better than not accessing it at all. :-)

Thanks for your advice!

**Comment by YustasSwamp** [comment]
Did you try to use ip= boot parameter?
ip=<client-ip>:<server-ip>:<gw-ip>:<netmask>:<hostname>:<device>:<autoconf>:
   <dns0-ip>:<dns1-ip>:<ntp0-ip>

https://www.kernel.org/doc/Documentation/filesystems/nfs/nfsroot.txt

**Comment by pierreyves-lebrun** [comment]
I did try that but the VM never seems to be getting an IP

**Comment by ssahani** [comment]
> I did try that but the VM never seems to be getting an IP

Please see https://github.com/vmware/network-config-manager

https://github.com/vmware/network-config-manager#generate-network-config-from-kernel-command-line. it's not packaged now with photon 3.

**Comment by pierreyves-lebrun** [comment]
> it's not packaged now with photon 3.

Thanks for the information. If nmctl is not packaged how can I use it at OS installation time?

**Comment by jzhang2018** [comment]
Photon seems having trouble to assign static IP address during boot time. This makes downloading kickstart file from http server approach useless. The only way to make it happen is to use DHCP (I have not done that as my environment disable DHCP due to security reason. I use ISO bundling kickstart file approach as dcasota pointed out above and it works fine.

I am facing another issue here. When VM is built, even I assign static IP address in kickstart file (the online doc only have 'dhcp' type but reference has static and ip address) but the eth0 interface has ony IPv6 ip address and no IPv4 ip address. I have a case open (https://github.com/vmware/photon/issues/1010) for it.

Thanks,

J

**Comment by cbsiddharth** [comment]
@pierreyves-lebrun, have you tried using the "network" key in [ks_config](https://github.com/vmware/photon/blob/master/installer/ks_config.txt#L167)?

**Comment by pierreyves-lebrun** [comment]
> @pierreyves-lebrun, have you tried using the "network" key in [ks_config](https://github.com/vmware/photon/blob/master/installer/ks_config.txt#L167)?

Sorry I stopped using photon OS and can’t remember whether I tried that already

**Comment by ssahani** [comment]
Closing because of lack of response
