### ISSUE TITLE
error: /boot/vmlinuz-4.19.97.2.ph3-esx has invalid signature.

### ISSUE THREAD

**Issue by alsemo** [vmware/photon#979]
My Photon 3 is a vm in ESXi 6.5 with Secure Boot enabled.

After I've upgraded the Photon system, I restarted the vm and it no longer boot. Kept being stuck at Photon loading screen.

Unfortunately, unlike others, I'm unable to disable the secure boot thus, I'm lost. Seriously? Update without signed for secure boot?

Any help on how to get this system running again? Thanks

**Comment by YustasSwamp** [comment]
We are working on this issue and solution will be provided soon.
Meanwhile, how do you disable secure boot? Is VM is powered off during reconfiguration?

**Comment by alsemo** [comment]
Hi,

The VM is off, but each time I Edit the Boot setting and try to untick the Secure Boot, after I Save then it will revert back to tick.

If I choose BIOS Boot instead of EFI, the VM will not power on and at the log there will be error "Failed - Module 'SecureBoot' power on failed."

In worst case scenario, can I reinstall Photon on top of existing installation, with regards of it not overwriting my contents, most importantly my dockers inside?

**Comment by YustasSwamp** [comment]
Did you try manually editing .vmx file in VM directory? Also you can try to remove .nvram file before powering on the VM.

**Comment by alsemo** [comment]
YustasSwamp,YOU'RE THE MAN!

For my reference:

- Log in to ESXi web, power off the VM
- Browse datastore, go to the VM's folder.
- Download *.vmx file. Edit the file.
- Change: uefi.secureBoot.enabled = "FALSE"
- Upload the *.vmx file back to ESXi datastore.
- remove *.nvram file.
- start the VM.
- Thanks the dev!

You made my day! Thanks a lot!
