### ISSUE TITLE
`date` commands outputs wrong.

### ISSUE THREAD

**Issue by chenliu1993** [vmware/photon#982]
Hi, I am using date to show the system time on Photon VM. But interestingly, `date` output and `date -u` output are interchanged. Please see below:
```
sh-4.4# date
Thu Feb 27 11:50:42 UTC 2020
sh-4.4# date -u
Thu Feb 27 11:50:43 GMT 2020
```
Seems the output are not right.  And I assume `date -u` and `date` should shows different time if I am in a different area?
Any solutions to this? Thank you.

**Comment by tapakund** [comment]
Could you check once if your TZ is set correct. As i could not repro the issue at my end.

Pls have a look at log below.

```
root@photon-4a0e7f2307d4 [ ~ ]# ls -la /etc/localtime
lrwxrwxrwx 1 root root 33 Feb 27 10:02 /etc/localtime -> /usr/share/zoneinfo/Asia/Calcutta
root@photon-4a0e7f2307d4 [ ~ ]# date
Thu Feb 27 10:02:51 IST 2020
root@photon-4a0e7f2307d4 [ ~ ]# date -u
Thu Feb 27 04:32:53 UTC 2020
root@photon-4a0e7f2307d4 [ ~ ]#
root@photon-4a0e7f2307d4 [ ~ ]# timedatectl
               Local time: Thu 2020-02-27 10:04:00 IST
           Universal time: Thu 2020-02-27 04:34:00 UTC
                 RTC time: Thu 2020-02-27 04:34:00
                Time zone: Asia/Calcutta (IST, +0530)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no
root@photon-4a0e7f2307d4 [ ~ ]#
```

**Comment by chenliu1993** [comment]
there is no /etc/localtime or TZ env because I am only using the photon 3.0 kernel.
Is this the core issue? That only a complete Photon env will works normally.

**Comment by tapakund** [comment]
If i remove tzdata package which contains /etc/localtime and other timezones informations, and check the date, i see both date and date -u shows universal time:

```
root@photon-4a0e7f2307d4 [ ~ ]# date
Thu Feb 27 05:15:35 UTC 2020
root@photon-4a0e7f2307d4 [ ~ ]# date -u
Thu Feb 27 05:15:38 UTC 2020
root@photon-4a0e7f2307d4 [ ~ ]# timedatectl
               Local time: Thu 2020-02-27 05:15:48 UTC
           Universal time: Thu 2020-02-27 05:15:48 UTC
                 RTC time: Thu 2020-02-27 05:15:48
                Time zone: n/a (UTC, +0000)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no
root@photon-4a0e7f2307d4 [ ~ ]#
```

Let me check more into this and get back.

**Comment by chenliu1993** [comment]
Thank you very much😊

**Comment by tapakund** [comment]
Pls let us know if installing tzdata and setting the right time zone fixes this problem?

**Comment by chenliu1993** [comment]
Sure. but how can i find the tzdata installer?

**Comment by sharathjg** [comment]
tdnf install tzdata

**Comment by chenliu1993** [comment]
hi, I install tzdata in the VM, now it looks like this:
```
ls -l /etc/localtime
lrwxrwxrwx 1 201 201 23 2020-03-26 15:33 /etc/localtime -> /usr/share/zoneinfo/UTC
```
and `date` command gives the same result without installing tzdata.
```
#date
Thu Mar 26 15:34:50 UTC 2020
```
While I also try to link localtime to the place at Asia
```
ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
ls -l /etc/localtime
lrwxrwxrwx 1 0 0 33 2020-03-26 15:35 /etc/localtime -> /usr/share/zoneinfo/Asia/Shanghai
```
and then executes `date` comamnd, it gives the below results:
```
date
Thu Mar 26 15:36:47 UTC 2020
```
However I install tzdata using a RPM, not tdnf.

**Comment by chenliu1993** [comment]
> hi, I install tzdata in the VM, now it looks like this:
> 
> ```
> ls -l /etc/localtime
> lrwxrwxrwx 1 201 201 23 2020-03-26 15:33 /etc/localtime -> /usr/share/zoneinfo/UTC
> ```
> 
> and `date` command gives the same result without installing tzdata.
> 
> ```
> #date
> Thu Mar 26 15:34:50 UTC 2020
> ```
> 
> While I also try to link localtime to the place at Asia
> 
> ```
> ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
> ls -l /etc/localtime
> lrwxrwxrwx 1 0 0 33 2020-03-26 15:35 /etc/localtime -> /usr/share/zoneinfo/Asia/Shanghai
> ```
> 
> and then executes `date` comamnd, it gives the below results:
> 
> ```
> date
> Thu Mar 26 15:36:47 UTC 2020
> ```
> 
> However I install tzdata using a RPM, not tdnf.

The `15:36` is not UTC time, it is China standard time.

**Comment by chenliu1993** [comment]
`date -u` gives the same output as `date`

**Comment by tapakund** [comment]
> ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

I tried the same on my VM.

root@photon-4a0e7f2307d4 [ /WS/photon-dev/photon ]# ls -la /etc/localtime
lrwxrwxrwx 1 root root 33 Mar 26 15:42 /etc/localtime -> /usr/share/zoneinfo/Asia/Shanghai
root@photon-4a0e7f2307d4 [ /WS/photon-dev/photon ]# date
Thu Mar 26 15:43:07 CST 2020
root@photon-4a0e7f2307d4 [ /WS/photon-dev/photon ]# date -u
Thu Mar 26 07:43:13 UTC 2020
root@photon-4a0e7f2307d4 [ /WS/photon-dev/photon ]#

Which photon release you have been using? 

also let us know the output for "rpm -q tzdata"

**Comment by tapakund** [comment]
Also could you paste the o/p for "timedatectl"

**Comment by YustasSwamp** [comment]
@chenliu1993 is issue resolved? Please reopen the bug if you need more support.

**Comment by chenliu1993** [comment]
yes, closed is ok, it is solved
