### ISSUE TITLE
nftables package is missing

### ISSUE THREAD

**Issue by hanscees** [vmware/photon#983]
Hi,
I know nftables can fight with iptables and docker uses iptables.

Nevertheless, I am using a docker email-server: https://github.com/tomav/docker-mailserver

I want to block all incoming email from spam-countries like RU etc. There is not a good / easy way to do that with iptables. (you have to use dkms to do so).
There is an easy way in nftables : https://wiki.nftables.org/wiki-nftables/index.php/GeoIP_matching

So if an nftables pachage could be provided that would certainly help.

Thanks.

```
tdnf install nftables
No package nftables available
Error(1011) : No matching packages
```

**Comment by hanscees** [comment]
apparently docker is using nftables via a compatability layer it seems when I read this issue 
https://github.com/moby/moby/issues/26824

The more reason to add nft package to photon to be able to see what is going on under the hood.

**Comment by hanscees** [comment]
Today I found out photon probably does not have nftables in its kernel. Can anybody conferm that. 
see https://github.com/moby/moby/issues/26824

**Comment by ssahani** [comment]
photon 3 kernel supports nf_table.
```
▶ modprobe nf_tables
~
▶ lsmod | grep nf_tables
nf_tables             114688  0
nfnetlink              16384  3 nf_conntrack_netlink,nf_tables

~
▶ uname -a
Linux photon 4.19.129-1.ph3 #1-photon SMP Tue Jun 30 02:21:48 UTC 2020 x86_64 GNU/Linux
```

But does not have the userspace package https://git.netfilter.org/nftables/
```
▶ ./nft add table ip filter
▶ ./nft list tables
table ip filter
```

**Comment by infraengineer-sre** [comment]
> But does not have the userspace package https://git.netfilter.org/nftables/

underlaying libs a right there:

```
Name          : libnftnl
Version       : 1.1.1
Release       : 1.ph3

Name          : libmnl
Version       : 1.0.4
Release       : 3.ph3
```

**Comment by ssahani** [comment]
For photon 4.0 it's planned and already merged. https://github.com/vmware/photon/blob/master/SPECS/nftables/nftables.spec

**Comment by ssahani** [comment]
This is in review will be added soon. thanks!

**Comment by ssahani** [comment]
https://github.com/vmware/photon/commit/1ad7d7af70c5fb8535a67d9e94870aed4d2bbdb5 is now merged . Hence closing thanks .
