### ISSUE TITLE
Package for PowerShell v7

### ISSUE THREAD

**Issue by lucdekens** [vmware/photon#984]
Now that PowerShell v7 is GA since March 4th 2020, can the PowerShell package for photon be updated to PSv7?

**Comment by dcasota** [comment]
A manual side setup with 6.2.3 worked for me.
[Pwsh7.0.0OnPhotonOS.sh.zip](https://github.com/vmware/photon/files/4304004/Pwsh7.0.0OnPhotonOS.sh.zip)

There aren't any earlier 6.x installation culprits anymore (powershellget,packagemanagement), and the console output is really fast!
A simple ```install-module -name VMware.PowerCLI``` works as expected, at least in a non-fxdependent Pwsh7 session, on an Azure Photon OS vm console.
Pwsh7.0.0 is LTS, and the underlying .NET core runtime 3.1.2 is a supported patch version for that https://github.com/dotnet/core/blob/master/microsoft-support.md.

A built-in Pwsh 7.0.0 package with .NET core runtime 3.1.2 would be nice. +1

**Comment by lucdekens** [comment]
Anyone from VMW still looking at the Issues?

**Comment by lucdekens** [comment]
Any progress?

**Comment by lucdekens** [comment]
Anyone?

**Comment by dcasota** [comment]
Bump. An official learning video on how to create/build an (update) package on a Photon OS dev environment would be helpful. From a learning curve perspective the content of [here ](https://vmware.github.io/photon/assets/files/html/3.0/photon_admin/compiling-c-code-on-the-minimal-version-of-photon-os.html)and [here](https://vmware.github.io/photon/assets/files/html/3.0/photon_admin/building-a-package-from-a-source-rpm.html ) is scarce.

**Comment by shreyasbe** [comment]
It's under code review.

**Comment by lucdekens** [comment]
I noticed there is a powershell-7.0.0-1.ph3.x86_64.rpm package created on May 14th.
It installed flawless on my photon box.

Is this still under code review?
Or is this the GA for the PSv7 package?

**Comment by shreyasbe** [comment]
> I noticed there is a powershell-7.0.0-1.ph3.x86_64.rpm package created on May 14th.
> It installed flawless on my photon box.
> 
> Is this still under code review?
> Or is this the GA for the PSv7 package?

Already merged to Photon-3.0.

**Comment by dcasota** [comment]
```docker pull vmware/powerclicore``` comes with v6.2.3 yet. Download&docker-run from https://github.com/vmware/powerclicore works flawlessly. Good to know it's all LTS. Little difference to ```tdnf install powershell```: it doesn't show up the teaser for the Non-LTS v7.0.1 release :-)

Nice! Both docker container with PowerCLI 12.0, , each with its prereqs for powershell&dotnet, on the same Photon box.

**Comment by dcasota** [comment]
Wohoo! PSv7 runs successfully on Photon3 as rpm (```tdnf install powershell```) or in a PowerCLI docker container (```docker pull vmware/powerclicore &&  docker run -it vmware/powerclicore```).

**Comment by ssahani** [comment]
Closing as nnew version is in. https://github.com/vmware/photon/blob/3.0/SPECS/powershell/powershell.spec#L3
