### ISSUE TITLE
How to force ipv4 for tdnf ?

### ISSUE THREAD

**Issue by JOduMonT** [vmware/photon#989]
Hi;

When I active IPv6, I'm able to `ping -4 google.com` and `ping -6 google.com` but tdnf don't work.

it is possible to enforce tdnf config so it will use **IPv4** such as I do with Debian

> echo -e "Acquire::ForceIPv4 \"true\";\\n" > /etc/apt/apt.conf.d/force-ipv4

**Comment by tapakund** [comment]
Right place for tdnf issues is https://github.com/vmware/tdnf

**Comment by JOduMonT** [comment]
> Right place for tdnf issues is https://github.com/vmware/tdnf

ya bah I'm more a left-handed person
