### ISSUE TITLE
how to install dd command

### ISSUE THREAD

**Issue by bitsf** [vmware/photon#990]
Hi,
I just can't find command dd in photon, and can't even find how to install this common tool.
I'm quite appreciate if anyone can help.

**Comment by YustasSwamp** [comment]
You need `coreutils` package.
In docker container, you might need to remove `toybox`.

**Comment by bitsf** [comment]
> You need `coreutils` package.
> In docker container, you might need to remove `toybox`.

yes, you are right.
I just run `tdnf remove toybox`, it will also install coreutils too. Awesome.

![image](https://user-images.githubusercontent.com/188115/77427766-e729d800-6e11-11ea-85ac-65422766c1ca.png)

**Comment by bitsf** [comment]
BTW, another way I find is I directly copy /bin/dd from a ubuntu linux to the docker container.
