### ISSUE TITLE
ovas dont work with virtualbox

### ISSUE THREAD

**Issue by osde8info** [vmware/photon#992]
ovas dont work with virtualbox 

just get a blank screen

**Comment by YustasSwamp** [comment]
Hi @osde8info 
What OVAa are you referencing to?
In most OVAs we use `linux-esx` kernel which is designed and optimized to work only under VMware hypervisor (ESXi/Workstation/Fusion).
You can to try ova with generic `linux` kernel.
BTW, we do not test virtualbox scenario.

**Comment by osde8info** [comment]
where can i find the OVA with generic kernel ?

these are the OVAs that dont work

http://dl.bintray.com/vmware/photon/3.0/GA/ova/photon-hw11-3.0-26156e2.ova
http://dl.bintray.com/vmware/photon/3.0/Rev2/ova/photon-hw11-3.0-9355405.ova

http://dl.bintray.com/vmware/photon/3.0/GA/ova/photon-hw13_uefi-3.0-26156e2.ova
http://dl.bintray.com/vmware/photon/3.0/Rev2/ova/photon-hw13_uefi-3.0-9355405.ova

**Comment by suezzelur** [comment]
Currently, only OVAs with `linux-esx` kernel are being published. You may have to build the ova locally on your own.

**Comment by YustasSwamp** [comment]
@osde8info you can try to convert GCE image, as we package generic linux kernel there.
https://github.com/vmware/photon/wiki/Downloading-Photon-OS
