### ISSUE TITLE
Kubernetes packages are pretty old

### ISSUE THREAD

**Issue by ahuffman** [vmware/photon#993]
Just looking to install at least v1.17 of kubernetes, from photon built packages, but the latest packages are from Oct. 2019 and we're going into April 2020.  v1.18 came out last week as well.

**Comment by vmware-go** [comment]
Any plan to update the kubernetes to 1.8? Or any suggestion to install it manually or pull it from other repo?

**Comment by ppadmavilasom** [comment]
install from https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
#download key
root@photon-9a8c05dd97e9 [ ~ ]# curl -L https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg -o /etc/pki/rpm-gpg/GOOGLE-RPM-GPG-KEY
#import to rpm
root@photon-9a8c05dd97e9 [ ~ ]# rpm --import /etc/pki/rpm-gpg/GOOGLE-RPM-GPG-KEY
#ensure keys are installed
root@photon-9a8c05dd97e9 [ ~ ]# rpm -qa | grep gpg-pubkey | xargs -n1 rpm -q --queryformat "%{NAME} %{PACKAGER}\n"
gpg-pubkey VMware, Inc. -- Linux Packaging Key -- <linux-packages@vmware.com>
gpg-pubkey Google Cloud Packages RPM Signing Key <gc-team@google.com>

root@photon-9a8c05dd97e9 [ ~ ]# cat /etc/yum.repos.d/kubernetes.repo 
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1

root@photon-9a8c05dd97e9 [ ~ ]# tdnf list kubelet-1.17.2
Loaded plugin: tdnfrepogpgcheck
kubelet.x86_64                                       1.17.2-0                    kubernetes

**Comment by vmware-go** [comment]
Thanks! But install fails - below is for 18.0, but same for 17-2

root@WDC-VL102-5005 [ /etc/yum.repos.d ]# tdnf install kubelet

Installing:
libnfnetlink                                      x86_64                   1.0.1-1.ph3                      photon                       52.46k 53723
libnetfilter_queue                                x86_64                   1.0.3-1.ph3                      photon                       51.04k 52270
libnetfilter_cttimeout                            x86_64                   1.0.0-1.ph3                      photon                       41.56k 42556
libnetfilter_cthelper                             x86_64                   1.0.0-1.ph3                      photon                       37.40k 38302
libnetfilter_conntrack                            x86_64                   1.0.7-1.ph3                      photon                     149.92k 153519
libmnl                                            x86_64                   1.0.4-3.ph3                      photon                       26.05k 26680
kubernetes-cni                                    x86_64                   0.7.5-0                          kubernetes                35.26M 36970984
socat                                             x86_64                   2.0.0.b9-1.ph3                   photon                     626.33k 641366
ethtool                                           x86_64                   4.18-1.ph3                       photon                     401.95k 411599
ebtables                                          x86_64                   2.0.10-4.ph3                     photon                     438.21k 448732
conntrack-tools                                   x86_64                   1.4.5-2.ph3                      photon-updates             486.85k 498531
kubelet                                           x86_64                   1.18.0-0                         kubernetes               108.01M 113255202

Total installed size: 145.52M 152593464
Is this ok [y/N]:y

Downloading:
libnfnetlink                             28695    100%
libnetfilter_queue                       26676    100%
libnetfilter_cttimeout                   21738    100%
libnetfilter_cthelper                    21618    100%
libnetfilter_conntrack                   66584    100%
libmnl                                   16386    100%
kubernetes-cni                        10641458    100%
Error(1622) : Invalid argument

**Comment by ppadmavilasom** [comment]
Can you please check if your kubernetes.repo file has gpgkey entry. i dont see that line included when i posted last

[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/GOOGLE-RPM-GPG-KEY

**Comment by vmware-go** [comment]
Cool - solved, 👍 Thank you!
