### ISSUE TITLE
required lsb packages for vmware photon OS

### ISSUE THREAD

**Issue by agollaravi** [vmware/photon#994]
Hi, 

I have installed vmware appliance server 6.7 version. After installing sever appliance it created a VM in my Vcenter. I am using that VM for my application.

The VM contains Photon OS: 4.4.171-1.ph1
VMware Photon Linux 1.0
PHOTON_BUILD_NUMBER=62c543d

My Issue:

I have installed my product agent on that VM which contains Photons OS. The installation was successful.

When I start the service of my product, it was throwing an error :
/lib/lsb/init-functions: No such file or directory

how can I get the lsb packages for Photon OS. Can anyone guide me on this.

Mostly I was looking like these below packages. These below packages are installed in rhel8. but i was looking similar kind of packages for Vmware Photon OS.

redhat-lsb-core.i686                   4.1-47.el8      
redhat-lsb-cxx.i686                    4.1-47.el8      
redhat-lsb-desktop.i686                4.1-47.el8      
redhat-lsb-languages.i686              4.1-47.el8     
redhat-lsb-printing.i686               4.1-47.el8     
redhat-lsb-submod-multimedia.i686      4.1-47.el8     
redhat-lsb-submod-security.i686 

Thanks,
Ravi

**Comment by YustasSwamp** [comment]
Photon OS uses systemd service management from the very beginning.
Please use systemd unit files for services in your product.
https://www.freedesktop.org/software/systemd/man/systemd.unit.html
