### ISSUE TITLE
httpd fails to start after reboot on clean install /var/run/httpd directory missing)

### ISSUE THREAD

**Issue by doug-baer** [vmware/photon#995]
I performed an install using the photon-hw11-3.0-9355405.ova (PhotonOS 3, rev 2)
Once I set the password, I installed apache using the package (2.4.41-1.ph3)
`# tdnf install httpd
`
I started the webserver and enabled it
```
# systemctl start httpd
# systemctl enable httpd
```

I tested the install and it returns as expected, running:
```
# curl http://localhost
<html><body><h1>It works!</h1></body></html>
```
After rebooting the machine, however, the httpd service will fail to start

```
# curl http://localhost
curl: (7) Failed to connect to localhost port 80: Connection refused
```

Then... 
```
# systemctl status httpd.service
● httpd.service - The Apache HTTP Server
   Loaded: loaded (/lib/systemd/system/httpd.service; enabled; vendor preset: disabled)
   Active: failed (Result: timeout) since Thu 2020-04-02 16:02:24 UTC; 2min 16s ago
  Process: 217 ExecStart=/usr/sbin/httpd -k start (code=exited, status=0/SUCCESS
)

Apr 02 16:00:54 photon-base systemd[1]: Starting The Apache HTTP Server...
Apr 02 16:00:54 photon-base systemd[1]: httpd.service: Can't open PID file /var/
run/httpd/httpd.pid (yet?) after start: No such file or directory
Apr 02 16:02:24 photon-base systemd[1]: httpd.service: Start operation timed out. Terminating.
Apr 02 16:02:24 photon-base systemd[1]: httpd.service: Failed with result 'timeout'.
Apr 02 16:02:24 photon-base systemd[1]: Failed to start The Apache HTTP Server.
```

== == ==
**The root cause of the failure is that the /var/run/httpd directory is removed at reboot/shutdown and the httpd service tries to create its pidfile in a path that does not exist.** 

I do not know if this is the "preferred" way to fix the issue, but it works for me. 
I add the following line to the /usr/lib/tmpfiles.d/var.conf file to recreate the directory at startup

`d /var/run/httpd 0755 - - -
`

After doing this and rebooting, apache comes up fine

**Comment by shanmugara** [comment]
I have the same issue. RHEL 7.6

httpd-2.4.6-89.el7_6.1.x86_64

I manually created /var/httpd after reboot and restarted fine. Whats the permanent fix for this?

**Comment by dweepadvani** [comment]
This was fixed by https://github.com/vmware/photon/commit/97f926d092c1dd32c2d2f3a6db446323799a9d81

**Comment by dweepadvani** [comment]
This issue is fixed but accidentally it was unassigned

**Comment by ssahani** [comment]
Thanks @dweepadvani closing then.
