### ISSUE TITLE
I want to build harbor-log image but it will use photon as base image

### ISSUE THREAD

**Issue by sarathvindu** [vmware/photon#996]
Dear All,

Actually i am trying to build the harbor-log image for log rotation with specific user but while creating the user from dockerfile i am getting error "groupadd: PAM: Authentication token is no longer valid;new password is need." can some one advise dockerfile for building harbor-log image along with user creation.
Note: harbor-log will use photon as base image.

**Comment by suezzelur** [comment]
What is the base image you are using?

**Comment by sarathvindu** [comment]
Hi,

I am using goharbor/harbor-v1.10.0

Thanks,
Sarath.A

**Comment by suezzelur** [comment]
The password policy in Photon is to set the expiry to 90 days for root and new accounts (this is done by shadow package). The base image must have been created with that default causing this error. Looks like https://github.com/goharbor/harbor/tree/v1.10.0 was released more than 90 days ago. Can you use a later image and also open an issue with harbor to modify the setting?

**Comment by YustasSwamp** [comment]
Closing the bug as expired.
@sarathvindu reopen it if needed.
