### ISSUE TITLE
VCH machine dont boot

### ISSUE THREAD

**Issue by dpuls** [vmware/photon#999]
Hello,

my VCH VM stops booting after a ESXi update, please see screen:
![image](https://user-images.githubusercontent.com/8395071/78722581-14a27580-792a-11ea-9795-70740ac3182f.png)

Has anybody an idea where can I fix this issue?

Thanks

**Comment by YustasSwamp** [comment]
Hi,

These messages won't stop from booting.
Need more info.
1) Can you increase 'loglevel=7' and remove 'quite' from kernel cmdline.
2) What VM log (vmware.log) says? Look at lines with "Guest: ..."

**Comment by ssahani** [comment]
Which version is this ? Writable `/sys` in container is not supported.  Please make `/sys` readonly. See https://systemd.io/CONTAINER_INTERFACE/

**Comment by dpuls** [comment]
Hello YustasSwamp,

thanks for your reply. My answers  between your 2 points.

Regards.

> Hi,
> 
> These messages won't stop from booting.
> Need more info.
> 
> 1. Can you increase 'loglevel=7' and remove 'quite' from kernel cmdline.
- Can you please explain how to increase logleven and remove quite?

> 2. What VM log (vmware.log) says? Look at lines with "Guest: ..."
- attached you find my vmware.log after a fresh start from the affected VM.
[vmware.log](https://github.com/vmware/photon/files/4448934/vmware.log)

**Comment by dpuls** [comment]
> Which version is this ? Writable `/sys` in container is not supported. Please make `/sys` readonly. See https://systemd.io/CONTAINER_INTERFACE/

Hello ssahani,

the version is vSphere Integrated Containers Appliance v1.5.4:
vic-v1.5.4-7589-e70af4fe.ova from VMware downloads.

I dont know how I can change in this state some permissions, with /sys readonly, in my opinion I can not acces some files in the current situation.

Thanks

**Comment by YustasSwamp** [comment]
@dpuls, Sorry for long delay.
From vmware.log VM is running and healthy.
please use this document as an instruction to
1) enable debug shell
2) increase systemd loglevel 
https://vmware.github.io/photon/assets/files/html/3.0/photon_troubleshoot/enabling-systemd-debug.html
3) in addition you can add `loglevel=7` there as well to increase kernel loglevel.

(2) and (3) will give you extra verbose messages in console
(1) will allow you to login to the VM from tty9 (ctrl+F9)

**Comment by ssahani** [comment]
Closing because of lack of response . If issue persists then please repen.
